### ISSUE TITLE
Core: iframe.html no longer built with --preview-url

### ISSUE THREAD

**Issue by sarahbethfederman** [storybookjs/storybook#14591] opened 2021-04-14 06:11 UTC
**Describe the bug**
Since upgrading to 6.2.7 from 6.1.21, we're no longer seeing an iframe.html generated, and it seems the --preview-url flag has been removed from the CLI? I didn't see any release notes about this, and it's causing our CDN deploy to break. 
Our build script looks like this

```
STORYBOOK_BASE_URL=$STORYBOOK_BASE_URL yarn build:storybook:docs --preview-url="${STORYBOOK_BASE_URL}iframe.html"
```

**Screenshots**
Before: 
![](https://user-images.githubusercontent.com/5673114/114662406-f7be3080-9d3b-11eb-9d1a-9bb14f2fd467.png)
After:
![](https://user-images.githubusercontent.com/5673114/114662427-ff7dd500-9d3b-11eb-98d2-ceff9fa37204.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
Please paste the results of `npx sb@next info` here.

**Additional context**

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231368/1200194209758764) by [Unito](https://www.unito.io)

**Comment by shilman** [comment] 2021-04-14 08:14
Argh, that looks like a fairly serious regression caused the by the webpack4/5 refactor. Looking into it now.

**Comment by shilman** [comment] 2021-04-14 08:31
Hi @sarahbethfederman can you tell me more about your setup? I tried reproducing the problem in our monorepo (`examples/standalone-preview`) and everything is behaving as I would expect.

When you run `build-storybook` with `--preview-url` I wouldn't expect any `iframe.html` to be generated, and I'm not seeing one. Was there an `iframe.html` generated in 6.1.x?

**Comment by sarahbethfederman** [comment] 2021-04-14 11:23
The situation we have is described here: https://github.com/storybookjs/storybook/issues/3699 there was previously an iframe.html generated and we were using the --preview-url to point it to the correct CDN url instead of `/iframe.html`

**Comment by shilman** [comment] 2021-04-15 03:41
Ok, I've confirmed that `iframe.html` was generated in 6.1.x and is no longer generated in 6.2.x. My impression is that this is actually a bugfix that ended up being a breaking change in your case, is that correct? It shouldn't be hard to restore the old behavior, but I don't really understand why it's needed. Can you clarify a bit? I didn't understand https://github.com/storybookjs/storybook/issues/3699#issuecomment-457713459

**Comment by sarahbethfederman** [comment] 2021-04-15 04:03
By default our router/CDN setup only fetches the index.html, so all static assets need to refer to an absolute path with the ugly url that's generated in our deployment pipeline. The `publicPath` webpack setting works for this with mostly, with the exception of the iframe.html which doesn't respect this setting. By default src in the index.html refers to `/iframe.html` and the only way to point it to our `<ugly_url>/iframe.html` without going through a whole bunch of router settings I don't have access to was to use the --preview-url flag. If https://github.com/storybookjs/storybook/issues/3699 were fixed it would eliminate the need for this.

**Comment by sarahbethfederman** [comment] 2021-04-15 04:04
I'm not sure if it was a "bugfix" because the actual use case for --preview-url didn't seem to be documented :)

**Comment by shilman** [comment] 2021-04-15 04:18
Ok thanks for explaining. I'll see if i can restore the old behavior for now (or maybe fix the other bug?!), and there's a good chance we'll be revisiting the preview url feature in the coming months

**Comment by sarahbethfederman** [comment] 2021-04-15 04:24
Awesome, thanks!!

**Comment by shilman** [comment] 2021-04-15 07:29
@sarahbethfederman I don't think the build points to `/iframe.html` anymore, but instead to `iframe.html`, which should solve the real issue here. Can you give that a try on your end and let me know if it's doing the right thing for you? If not, would it be possible to create a simple repro illustrating the problem?

Side note: I've taken a look at the 6.1 => 6.2 changes and it would be easy to roll this back. However, I'd like to solve the real problem here if possible.

**Comment by sarahbethfederman** [comment] 2021-04-15 08:46
Yeah unfortunately that will still create a 404 since it needs the absolute path (similar to delivering images via CDN). I can't really set up a repro without creating a new pipeline atm. I guess I'm just unclear as to why the publicPath would effect everything but the iframe location. Was that a conscious design choice, or is it something that can be changed?

**Comment by manuelpuyol** [comment] 2021-05-03 20:51
@shilman I'm having the same issue with v6.2 :(

In [primer_view_components](https://github.com/primer/view_components) we demo our components using a Rails app that servers the static Storybook files. We place them at `public/view-components/stories` so it is accessible at `localhost:4000/view-components/stories`.

Initially, we built the static files with `build-storybook -o public/view-components/stories`. But we had an issue that when accessing `localhost:4000/view-components/stories` requested all JS files correctly, but tried to fetch `iframe.html` from `localhost:4000/view-components/iframe.html`, which did not exist, instead of `localhost:4000/view-components/stories/iframe.html`.

The only way to fix that was adding a trailing `/` to the URL: `localhost:4000/view-components/stories/` fetched the correct `iframe.html` path. Digging more, we discovered `--preview-url=/view-components/stories/iframe.html`, which forced `iframe.html` to always be fetched correctly, even without the trailing `/`.

That was all in v6.1, but now in v6.2 our storybook reverted to fetch the incorrect `iframe.html` and will only work with a trailing `/`.

**Comment by KarlBao** [comment] 2021-05-12 06:25
Same problem. I'd like to deploy the storybook with subpath. So I change the config referenced to [this answer](https://github.com/storybookjs/storybook/issues/3172#issuecomment-795255956).
However, the `iframe.html` is not generated when I set `--preview-url` option in the command.

**Comment by shilman** [comment] 2021-05-25 16:53
Hurrah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.45 containing PR #15030 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2021-05-25 16:53 UTC
Labels: P0, bug, core

**Comment by votemike** [comment] 2021-06-01 20:22
@shilman I can confirm that your fix fixes the problem which I believe was the problem the OP had.
However, it seems like a lot of people are using `--preview-url` to allow storybook to be served from a sub-directory as suggested here: https://github.com/storybookjs/storybook/issues/1291#issuecomment-795251283
Perhaps if there was some documentation on the correct way to serve storybook from a subdirectory and some more information on what `--preview-url` should be used for, there would not be this confusion and the need for cli options such as `--force-build-preview`
