### ISSUE TITLE
The count of controls not adjusted when some are disabled

### ISSUE THREAD

**Issue by reno1979** [storybookjs/storybook#13632] opened 2021-01-14 09:12 UTC
**Describe the bug**
When I disable some controls (see: https://storybook.js.org/docs/react/essentials/controls#disable-controls-for-specific-properties) the count of the number of controls does not change. 

**To Reproduce**
 
https://storybook.js.org/docs/react/essentials/controls#disable-controls-for-specific-properties

**Expected behavior**
I would expect the number to match the count of actual usable controls. (including hidden ones, if I could make them appear) But when I disable some controls I can not view and use them, so the displayed number of controls is confusing. 

**Screenshots**
The video inside the link shows the same behaviour: 
https://storybook.js.org/docs/react/essentials/controls#disable-controls-for-specific-properties

**Comment by apapadopoulou** [comment] 2021-04-04 19:30
Hello! Is anyone working on this?

**Comment by shilman** [comment] 2021-04-05 03:04
@apapadopoulou not as far as i know. are you interested in taking a shot?

**Comment by apapadopoulou** [comment] 2021-04-17 13:55
I am currently working on another issue, but I could take a look at this afterwards. To begin with, I think it needs more reproduction, as the step to reproduce that is mentioned is the link to the Storybook doc about controls.

**Comment by JohannesFischer** [comment] 2021-05-14 14:25
I haven't tried it myself yet but you can see in the video on the linked doc page after **foo** is disabled in the control table but the count in the control panel title does not update and remains **Controls (2)**.

**Comment by JohannesFischer** [comment] 2021-10-18 10:07
I created a basic repo based of the Storybook setup script, that should help to reproduce the issue. It only contains the demo Button component with the primary Button showing four controls in the controls tab despite two of the four controls being disabled.

**Primary button story**
<img width="839" alt="Screen Shot 2021-10-18 at 17 25 18" src="https://user-images.githubusercontent.com/28100/137710082-c693212f-6822-428e-800f-acddea50dbcb.png">

**Secondary button story**
<img width="839" alt="Screen Shot 2021-10-18 at 17 25 10" src="https://user-images.githubusercontent.com/28100/137710146-0bf1d78b-5bb3-440a-b21c-5f0a32f2fbf9.png">

To reproduce the follow these steps:
* Clone the [storybook-disabled-controls](https://github.com/JohannesFischer/storybook-disabled-controls) repository
* Run `npm i && npm run storybook`
* Confirm that all stories show a control count of 4

My laptop freezes when trying to run the dev environment but I assume the issue originates in the [register file](https://github.com/storybookjs/storybook/blob/03149e8253e7a4bcab7b60095fb7f510bbce19bd/addons/controls/src/register.tsx#L12) of the controls addon, that doesn't seems to take disabled stories into account.

**Comment by tmakic** [comment] 2022-03-02 06:51
I'll try this issue for my first contribute!

**Comment by itsajay1029** [comment] 2022-10-28 19:22
Is anyone working on this issue ?

**Comment by JohannesFischer** [comment] 2022-11-28 03:12
Looks like this issue has been resolved in #18780

**Closed** 2023-01-17 22:52 UTC
Labels: bug, help wanted, needs reproduction, addon: controls
