### ISSUE TITLE
[BUG] Can't navigate on mobile

### ISSUE THREAD

**Issue by Sidnioulz** [storybookjs/storybook#23908] opened 2023-08-21 15:15 UTC
### Describe the bug

When using the mobile view of Storybook, and navigating to a new page, the canvas always resets to a specific story. This makes navigation impossible in mobile.

When clicking on the sidebar in my SB instance, or in any sandbox/repro made in the core repo
When selecting any docs / story entry in the sidebar...

**What happens**

- I see the preview gets updated with the page I wanted to open ✅
- But when I click on 'canvas', I get navigated to another component story (always the same, looks like it's the first story) ⚠️

**What should happen**

- I see the preview gets updated with the page I wanted to open
- When I click on 'canvas', the page I opened stays on

### To Reproduce

* Decrease your window size to get the mobile view rendered
* Open the sidebar and click on any story/docs page
* Re-open the canvas and notice you get teleported to a different story (always the same though, as if the canvas failed to find the current story and defaulted somewhere)

### System

```shell
System:
    OS: Linux 6.2 Arch Linux
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
  Binaries:
    Node: 20.5.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.8.1 - /usr/bin/npm
```

### Additional context

I've noticed it on any sandbox and on `yarn storybook:ui` as well as on my own SB instance.

**Comment by vanessayuenn** [comment] 2023-08-21 15:29
Thanks for raising this! However, I am going to close it since this is a duplicate of #23723.

**Closed by vanessayuenn** 2023-08-21 15:29 UTC
Labels: bug, needs triage
