### ISSUE TITLE
Add .env file support

### ISSUE THREAD

**Issue by Lehakos** [storybookjs/storybook#1833] opened 2017-09-11 13:58 UTC
Do you have a plan to add support of .env file? With CRA we can add NODE_PATH variable to .env, but storybook does not support it.

**Comment by ndelangen** [comment] 2017-09-11 14:16
I would welcome a PR to add support!

**Comment by canercandan** [comment] 2017-09-20 19:26
@Lehakos https://www.npmjs.com/package/dotenv could be a good candidate to approach this

**Comment by canercandan** [comment] 2017-09-21 06:48
@ndelangen I will need this feature too so will probably provide a PR soon, though in the meantime if someone wants to keep up on this you can use https://github.com/mrsteele/dotenv-webpack to enable dotenv through webpack this will require to setup a custom webpack setup that includes the webpack plugin `Dotenv`.

**Comment by ndelangen** [comment] 2017-09-21 08:07
@canercandan That might be a valid permanent solution too?
To include this in our internal webpack configs?

**Comment by Luchanso** [comment] 2017-10-07 21:46
@bsr203 thank you a lot of, it's work for me

**Comment by agarrharr** [comment] 2017-10-30 17:38
@canercandan I can't figure out how to add `dotenv-webpack` to my storybook's custom webpack setup.

@bsr203 Can you explain more about your workaround? I'm not sure where to put that config or what it does.

**Comment by bsr203** [comment] 2017-10-30 18:05
@agarrharr Not sure what is your purpose, but for me, I wanted to avoid using relative path in my imports. So, instead of importing something like

```
import { path } from '../../services/menu';
```

I want to import like

```
import { path } from 'src/common/services/menu';
```

so only thing I have to do is to add `NODE_PATH=.` in my package.json `storybook` script as shown above.

I you do `NODE_PATH=./src`, you can import like `import { path } from 'common/services/menu';`

hope other variable also can set here, but my requirement is simple and happy with the workaround.
HTH.

**Comment by agarrharr** [comment] 2017-10-31 20:41
@bsr203 That doesn't sound like what I'm trying to do. I want to have access to environment variables, which are stored in a `.env` file.

According to the Storybook docs, you can use environment variables that start with `STORYBOOK_`: https://storybook.js.org/configurations/env-vars/

So, I can do something like this in my scripts in `packages.json`:

```
"storybook": "cross-env STORYBOOK_SOME_API_KEY=asdf1234adsf start-storybook -p 9001 -c .storybook -s ./public/mr_assets"
```

But I don't want to put my API key in `package.json`. I would rather leave it in `.env`.

**Comment by RWOverdijk** [comment] 2017-11-08 08:17
CRA and others have support for .env files. This supports needs to be available when using storybook one way or another.

So I solved it like this:

*.storybook/webpack.config.js:*

```js
const Dotenv           = require('dotenv-webpack');
const genDefaultConfig = require('@storybook/react/dist/server/config/defaults/webpack.config.js');

module.exports = (baseConfig, env) => {
  const config = genDefaultConfig(baseConfig, env);

  config.plugins.push(new Dotenv());

  return config;
};
```

Uses the default webpack, and just adds support for the env files.

**Comment by ndelangen** [comment] 2017-11-09 15:22
@RWOverdijk If you can add this to our default webpack config(s) I'd be happy to merge that!

Provided it works if there's no dotfile.

**Comment by RWOverdijk** [comment] 2017-11-09 15:24
If there's no dotfile, nothing happens. I'd be glad to add it for the react one, I think that's the only place it should be added anyway. Otherwise this workaround is just fine as long as it's documented.

Your call! :)

**Comment by agarrharr** [comment] 2017-11-10 20:14
@RWOverdijk This workaround works great! I love to see this either added to the default webpack config, or in the Storybook documentation: https://storybook.js.org/configurations/env-vars/

**Comment by ndelangen** [comment] 2017-11-11 10:33
@RWOverdijk Why wouldn't it work for Vue? Just curious really, I'd ♥️ a PR adding it to the default webpack config and docs!

**Comment by RWOverdijk** [comment] 2017-11-13 08:02
@ndelangen Will do. I'm guessing dist is generated, where can I find the webpack config to make a PR?

**Comment by ndelangen** [comment] 2017-11-14 15:54
Here:
https://github.com/storybooks/storybook/blob/master/app/react/src/server/config/webpack.config.js

Also a prod version, and version per app:
https://github.com/storybooks/storybook/blob/master/app/vue/src/server/config/webpack.config.js

**Comment by RWOverdijk** [comment] 2017-11-20 11:21
@ndelangen Alright. Final question, where do I add `dotenv-webpack` as a dependency then? If this is default behavior, it might break apps if they removed it (ejected for instance). Shouldn't it be optional then?

**Comment by ndelangen** [comment] 2017-11-21 16:58
@RWOverdijk when a user ejects CRA, that is of no concequence to storybook I think.
Please tell me what problems you see that could happen.

The place to add the dependency is in the `package.json` of the `app/*` as a regular dependency.

**Comment by ndelangen** [comment] 2018-01-05 18:34
This has been added with `3.3.0`

**Comment by chris-fran** [comment] 2019-04-24 21:35
where is the documentation for this?  

My components can't read the environment variables I have defined on my `.env.development` so it's not working?

**Comment by shilman** [comment] 2019-04-24 23:48
@chris-fran it's possible that this regressed in 5.0. do you have a repro?

**Comment by chris-fran** [comment] 2019-04-25 14:02
@shilman I'll have to make some time to put up a repro.

However, just incase the problem is me doing something wrong, my project goes like this:
```
 |-- .storybook/
 |-- src/
 |-- .env.development  // I got `REACT_APP_` env variables that are not loaded by storybook, so my components don't work properly
```

Maybe I am supposed to setup something to make it work?

**Comment by jayarjo** [comment] 2020-06-26 17:59
How to make this work?

**Comment by DylanCulfogienis** [comment] 2020-10-29 20:59
Can we get some documentation for this?

**Comment by DavidLozzi** [comment] 2020-10-30 00:03
is this supported, if so how? I see you @ndelangen  mentioned it v3

**Comment by JMo911** [comment] 2020-11-20 22:01
Any luck with this?

**Comment by jamie-sanger** [comment] 2020-11-23 03:18
Also very keen to see this fixed.
We have recently moved to a white labelled solution which is predominantly defined by process.env variables.

**Comment by federicom-scale** [comment] 2020-12-04 14:57
Currently struggling with this

**Comment by jonniebigodes** [comment] 2020-12-05 18:14
@federicom-scale take a look [here](https://github.com/jonniebigodes/storybook_env_variables_example) for a bare-bones example of a Storybook with env file support. Inside you'll find the components, storys and a test example. The `.env` files are split into environments (development, prod, test). The deployed version is [here](https://tender-turing-e9d62f.netlify.app/?path=/story/mycomponent-with-env-file--example). The documentation is rather "slim" (pardon the bad pun) regarding this topic. I've been tackling other documentation aspects, but this one did not not go unnoticed. A pull request with a more comprehensive approach will be up shortly. 

Hope the repo i shared helps you get unblocked.

Stay safe

**Comment by jonniebigodes** [comment] 2021-01-20 15:53
Going to close this issue if you all don't mind. A recent pull request was merged that addressed this.

Feel free to re-open regarding any follow up. 

Stay safe

**Closed by jonniebigodes** 2021-01-20 15:53 UTC
Labels: documentation, feature request, has workaround, help wanted
