### ISSUE TITLE
Storybook doesn't work with React Native 0.61

### ISSUE THREAD

**Issue by Undeadlol1** [storybookjs/storybook#8613] opened 2019-10-29 10:22 UTC
**Describe the bug**
There are two problems:
1) Storybook starts with "No addons loaded" page.
2) After making changes to components "No addons loaded." page appears again and warnings show up.

**To Reproduce**
Use this repo: 
https://github.com/Undeadlol1/rn61StorybookIssue
Or create fresh React Native repo via:
```
react-native init rn61StorybookIssue --version 0.61.2;
cd rn61StorybookIssue;
npx -p @storybook/cli sb init --type react_native;
npm run ios
```

**Expected behavior**
Storybook should start properly. Initial page should be "Preview" or "Navigator".
Simulator refresh must not redirect to "Addons" page constantly.

**Screenshots**
1) Storybook starts with "No addons loaded." page.
![image](https://user-images.githubusercontent.com/4124323/67756753-66320480-fa5c-11e9-85b6-59f297532f2a.png)
2) After making changes to components "No addons loaded" page appears again and warnings show up.
![image](https://user-images.githubusercontent.com/4124323/67757132-08ea8300-fa5d-11e9-875b-78435ae2d0ee.png)

**System:**
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.10.1 - ~/.yarn/bin/yarn
    npm: 6.11.3 - ~/.node_modules/bin/npm
  Browsers:
    Chrome: 78.0.3904.70
    Safari: 13.0

**Comment by Gongreg** [comment] 2019-10-30 05:15
Hey, I hope I will have a chance to work on storybook during weekend/next week. I will take a look into current issues regarding react native.

**Comment by Gongreg** [comment] 2019-11-02 20:20
Hey,
I've created a PR to fix the issue. Also I am closing the issue since it is a duplicate of https://github.com/storybookjs/storybook/issues/8274

**Closed by Gongreg** 2019-11-02 20:20 UTC
Labels: app: react-native, bug, help wanted

**Comment by Undeadlol1** [comment] 2019-11-03 09:17
Thank you.

**Comment by shilman** [comment] 2019-11-03 09:45
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.38 containing PR #8681 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
