### ISSUE TITLE
Default for function prop overrides action argType

### ISSUE THREAD

**Issue by kazdegroot** [storybookjs/storybook#12120] opened 2020-08-18 23:48 UTC
**Describe the bug**
When creating a story for a component that sets empty functions as defaults for (some) event handling props, the default functions get passed in through args, even though the argType for the prop is set to `{ action: 'actionName'}`.

**To Reproduce**

1. Create a component that accepts a function as a prop.
2. Give the prop a function as default value (e.g. `() => {}`)
3. Create a story, which sets the argType for the prop to `{action: 'actionName'}`
4. Trigger the function in storybook.

**Expected behavior**
A log of the action 'actionName' in the Actions tab.

**Code snippets**
TestStory.js:
```js
import React from 'react';

const TestStory = ({ onClick = () => { console.log('test') } }) => <button onClick={onClick}>Click me!</button>;

export default TestStory;
```

TestStory.stories.js:
```js
import React from 'react';
import TestStory from './TestStory';

export default {
  title: 'core/Test case',
  component: TestStory,
  args: {},
  argTypes: {
    onClick: { action: 'onClick', control: null }
  }
};

export const Default = args => {
  console.log(args.onClick);
  return <TestStory {...args} />;
};
```

**System:**
Environment Info:

  System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - ~/.nvm/versions/node/v12.13.1/bin/npm
  Browsers:
    Chrome: 84.0.4147.135
    Safari: 13.1.2

**Additional context**
If the component is in the same file as the story, the problem doesn't occur. If storybook is unable to fetch info about the components properties the issue also doesn't occur: when storybook is unable to prefill the ArgTable in the Controls tab.

**Comment by shilman** [comment] 2020-08-19 02:14
Do you have a reproduction?

**Comment by kazdegroot** [comment] 2020-08-19 07:55
The two code snippets together are the smallest scenario I could find that (in our environment)  shows the issue.

**Comment by kmckee** [comment] 2020-08-27 15:07
I'm experiencing this issue as well.

I created a [repo that reproduces this issue](https://github.com/kmckee/action-issue-repro).  

Steps taken to create it are:

1. `npx create-react-app foo && cd foo`
2. `npx sb init`
3. `npm run storybook` and confirm that button actions are getting logged.
3. In `Button.js`, change defaultProp of onClick to empty function.
4. actions are no longer logged.

**Comment by luizeboli** [comment] 2020-08-28 22:53
Same problem here, my example is exactly as the one provided by @yannickcornaille

**Comment by Sinled** [comment] 2020-09-23 19:03
Any updates on this issue? Have the same problem/

**Comment by thebinaryfelix** [comment] 2020-10-14 18:51
This worked for me. I'm using Storybook version 6.0.5

```
export default {
  component: Button,
  title: 'Button',
 // Add the defaultValue property
  argTypes: { onClick: { defaultValue: null, action: 'clicked' } },
};

const Template = (args) => <Button {...args} />;

export const Basic = Template.bind({});
```

Reference:
I had the same problem, but I've found a work around based on this test file.

https://github.com/storybookjs/storybook/blob/9b1d2d30f31f54992b1fdd19987bcce47c7c1f71/addons/actions/src/preset/addArgs.test.ts#L61

**Comment by lordfpx** [comment] 2020-10-17 20:40
Same bug here, it's quite anoying :-(.

**Comment by glrodasz** [comment] 2020-10-23 17:59
@thebinaryfelix answer fix the issue per story, but then if you want to use the general solution in `.storybook/preview.js` it has the same problem.

```js
export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
} 
```

**Comment by deividmarques** [comment] 2020-10-27 14:18
I used it and it worked
```
argTypes: {​​​​​​​​ onOpen: {​​​​​​​​ defaultValue: null, }​​​​​​​​, onChange: {​​​​​​​​ defaultValue: null, }​​​​​​​​, }​​​​​​​​
````
````
parameters: {
  actions: { argTypesRegex: '^on.*' },
},
````
![md](https://user-images.githubusercontent.com/1235904/97313912-e93f9380-1845-11eb-80f7-83c486928a52.gif)

**Comment by stubar** [comment] 2021-01-28 09:56
I have a related issue with typescript.  When defining a fixture I am using the interface for the component's props, I have an onChange event that is mandatory, so I set this as `() => {}` in the fixture.   However this prevents the action from running. 

My work around is to use `Omit<ComponentProps, 'onChange'> ` on my fixture interface but this feels clunky.  It would be good to have the action still run transparently by maybe using a `call` or `apply` on the fixture's event.  This could be via an argType param if not suitable as default.

**Comment by tmeasday** [comment] 2021-02-15 03:32
OK, so the reason for this is quite clear -- we prefer a defined `defaultValue` to the action:

https://github.com/storybookjs/storybook/blob/60772cbbeb3507831b7f9ce01a2a5e814c03246f/addons/actions/src/preset/addArgs.ts#L44:L44

I'm not sure if this is intentional or not. Will discuss with @shilman

**Comment by shilman** [comment] 2021-02-15 06:44
¡Ay Caramba!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.28 containing PR #13912 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2021-02-15 06:44 UTC
Labels: P0, addon: actions, args, bug, has workaround, todo
