### ISSUE TITLE
[Bug]: NullInjectorError: No provider for InjectionToken USER_PROVIDED_NGXS_EXECUTION_STRATEGY!

### ISSUE THREAD

**Issue by squelix** [storybookjs/storybook#21905] opened 2023-04-04 07:19 UTC
### Describe the bug

Ngxs is no longer working with Storybook 7.

### To Reproduce

I juste have my app with a global `preview.ts`: 

```typescript
const preview: Preview = {
  parameters: {
    actions: { argTypesRegex: '^on[A-Z].*' },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/,
      },
    },
    docs: { inlineStories: true },
    layout: 'fullscreen',
    viewport: {
      viewports: INITIAL_VIEWPORTS,
    },
  },
  decorators: [
    // useTheme,
    componentWrapperDecorator((story) => `<tui-root>${story}</tui-root>`),
    moduleMetadata({
      imports: [
        CommonModule,
        HttpClientModule,
        RouterTestingModule,
        BrowserModule,
        BrowserAnimationsModule,
        NgxsModule.forRoot([], {
          developmentMode: true,
          executionStrategy: NoopNgxsExecutionStrategy,
          compatibility: {
            strictContentSecurityPolicy: true,
          },
          selectorOptions: {
            suppressErrors: false,
            injectContainerState: true,
          },
        }),
        NgxsRouterPluginModule.forRoot(),
        ScrollToModule.forRoot(),
        ReactiveFormsModule,
        TuiRootModule,
        TuiDialogModule,
        NgxsReduxDevtoolsPluginModule.forRoot({ name: 'Obendy Storybook', disabled: false }),
      ],
      providers: [
        {
          provide: APP_BASE_HREF,
          useValue: '/',
        },
        { provide: LOCALE_ID, useValue: 'fr' },
        { provide: TUI_SANITIZER, useClass: NgDompurifySanitizer },
        {
          provide: TUI_ICONS_PATH,
          useValue: iconsPath,
        },
        {
          provide: TUI_LANGUAGE,
          useValue: of(TUI_FRENCH_LANGUAGE),
        },
        {
          provide: TUI_VALIDATION_ERRORS,
          useValue: {
            required: 'Ce champ est requis',
            email: 'Votre email est invalide',
            emailAlreadyExists: 'Cette adresse email est déjà utilisée',
          },
        },
        PlanPresentationService,
      ],
    }),
  ],
};

export default preview;
```

### System

```shell
System:
    OS: macOS 13.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    Yarn: 3.5.0 - ~/.yvm/shim/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Edge: 111.0.1661.62
    Firefox: 111.0.1
    Safari: 16.4
  npmPackages:
    @storybook/addon-a11y: 7.0.2 => 7.0.2 
    @storybook/addon-actions: 7.0.2 => 7.0.2 
    @storybook/addon-docs: 7.0.2 => 7.0.2 
    @storybook/addon-essentials: 7.0.2 => 7.0.2 
    @storybook/addon-interactions: 7.0.2 => 7.0.2 
    @storybook/addon-links: 7.0.2 => 7.0.2 
    @storybook/angular: 7.0.2 => 7.0.2 
    @storybook/testing-library: 0.1.0 => 0.1.0
```

**Comment by squelix** [comment] 2023-04-04 07:38
The error is the following
```
NullInjectorError: No provider for InjectionToken USER_PROVIDED_NGXS_EXECUTION_STRATEGY!
Error: NullInjectorError: No provider for InjectionToken USER_PROVIDED_NGXS_EXECUTION_STRATEGY!
    at NullInjector.get (http://localhost:6006/vendors-node_modules_angular_common_locales_global_fr_js-node_modules_angular_localize_fesm20-1eb4d2.iframe.bundle.js:48002:21) [angular]
    at R3Injector.get (http://localhost:6006/vendors-node_modules_angular_common_locales_global_fr_js-node_modules_angular_localize_fesm20-1eb4d2.iframe.bundle.js:48433:27) [angular]
    at R3Injector.get (http://localhost:6006/vendors-node_modules_angular_common_locales_global_fr_js-node_modules_angular_localize_fesm20-1eb4d2.iframe.bundle.js:48433:27) [angular]
    at Object.factory (http://localhost:6006/vendors-node_modules_angular_common_locales_global_fr_js-node_modules_angular_localize_fesm20-1eb4d2.iframe.bundle.js:92132:40) [angular]
    at R3Injector.hydrate (http://localhost:6006/vendors-node_modules_angular_common_locales_global_fr_js-node_modules_angular_localize_fesm20-1eb4d2.iframe.bundle.js:48523:29) [angular]
    at R3Injector.get (http://localhost:6006/vendors-node_modules_angular_common_locales_global_fr_js-node_modules_angular_localize_fesm20-1eb4d2.iframe.bundle.js:48424:23) [angular]
    at R3Injector.get (http://localhost:6006/vendors-node_modules_angular_common_locales_global_fr_js-node_modules_angular_localize_fesm20-1eb4d2.iframe.bundle.js:48433:27) [angular]
    at injectInjectorOnly (http://localhost:6006/vendors-node_modules_angular_common_locales_global_fr_js-node_modules_angular_localize_fesm20-1eb4d2.iframe.bundle.js:44736:29) [angular]
    at Module.ɵɵinject (http://localhost:6006/vendors-node_modules_angular_common_locales_global_fr_js-node_modules_angular_localize_fesm20-1eb4d2.iframe.bundle.js:44740:59) [angular]
    at Object.InternalNgxsExecutionStrategy_Factory [as factory] (http://localhost:6006/vendors-node_modules_angular_common_locales_global_fr_js-node_modules_angular_localize_fesm20-1eb4d2.iframe.bundle.js:92617:105) [angular]
    at R3Injector.hydrate (http://localhost:6006/vendors-node_modules_angular_common_locales_global_fr_js-node_modules_angular_localize_fesm20-1eb4d2.iframe.bundle.js:48523:29) [angular]
    at R3Injector.get (http://localhost:6006/vendors-node_modules_angular_common_locales_global_fr_js-node_modules_angular_localize_fesm20-1eb4d2.iframe.bundle.js:48424:23) [angular]
    at injectInjectorOnly (http://localhost:6006/vendors-node_modules_angular_common_locales_global_fr_js-node_modules_angular_localize_fesm20-1eb4d2.iframe.bundle.js:44736:29) [angular]
    at Module.ɵɵinject (http://localhost:6006/vendors-node_modules_angular_common_locales_global_fr_js-node_modules_angular_localize_fesm20-1eb4d2.iframe.bundle.js:44740:59) [angular]
```

**Comment by ndelangen** [comment] 2023-04-04 07:46
@squelix can you supply a reproduction perhaps?

Did this work in the RC release of storybook 7?

This is related to angular, when I do a search for the error I find this article:
https://stackoverflow.com/questions/53317225/angular-injectiontoken-throws-no-provider-for-injectiontoken
@valentinpalkovic ☝️ 

@squelix Did you follow the migration guide?

**Comment by squelix** [comment] 2023-04-04 07:50
Yes i follow the migration guide with the command line. And i made some manual migration like `main.js` => `main.ts` et `preview.js` => `preview.ts`.

**Comment by squelix** [comment] 2023-04-04 08:47
I'll make a repro reproduction asap.

**Comment by valentinpalkovic** [comment] 2023-04-04 19:05
@squelix please follow the migration guide: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#angular-application-providers-and-modulewithproviders

**Comment by valentinpalkovic** [comment] 2023-04-04 19:18
Duplicate of https://github.com/storybookjs/storybook/issues/21896

**Closed by valentinpalkovic** 2023-04-04 19:18 UTC
Labels: bug, needs reproduction, angular, duplicate
