### ISSUE TITLE
Scrollbars always appear in the story iframe

### ISSUE THREAD

**Issue by danielschwartz85** [storybookjs/storybook#7724] opened 2019-08-08 15:29 UTC
Hi 
**The main story iframe is now always with scrollbars**
Introduced in @storybook/react@2.1.10 
We use this iframe to visual test the components, this creates false negative test images for the component screen. 

**To Reproduce**
1. install and run SB with the basic example

**Expected behavior**
Small components would not be in such a big div.

**Screenshots**
![scroll](https://user-images.githubusercontent.com/4113198/62716026-3dc0de00-ba0a-11e9-8afc-9c86260f9e86.png)

**Additional context**
Note that SB beta still has this issue but only with vertical scroll.
Thanks.

**Comment by shilman** [comment] 2019-08-10 14:00
Closing this as a duplicate of https://github.com/storybookjs/storybook/issues/7646

Let me know if you think it's something else

**Closed by shilman** 2019-08-10 14:00 UTC
Labels: bug, ui

**Comment by quentind** [comment] 2019-08-12 12:46
@shilman Thanks for looking into this. I'm experiencing the same issue on 5.1.10 and I don't think it is the same problem as the one referenced in #7646 which pertain to the `height` of the preview area. 

This issue is related to the viewport having unwanted scrollbars due to whitespace/margin on the body, which is a regression compared to (live demo running on 5.1.3)[https://storybooks-official.netlify.com/?path=/story/ui-panel--default].

I've submitted [a pull request](https://github.com/storybookjs/storybook/pull/7742) which solves this issue.

Thanks!

**Comment by shilman** [comment] 2019-08-13 01:36
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.29 containing PR #7750 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by shilman** [comment] 2019-08-13 02:02
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.1.11 containing PR #7750 that references this issue. Upgrade today to try it out!

**Comment by shilman** [comment] 2019-09-25 18:48
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.3 containing PR #7742 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
