### ISSUE TITLE
Sidebar navigation does not work in production (6.0.0-rc.5 + addon-docs)

### ISSUE THREAD

**Issue by koop-stripe** [storybookjs/storybook#11590] opened 2020-07-16 23:16 UTC
**Describe the bug**
Sidebar navigation does not work when building addon-docs for production.

**To Reproduce**

1. Build storybook for production `build-storybook --docs -c .storybook -o .storybook-dist`
2. Start the server, load a page in your browser.
3. Try to navigate to another page by clicking a page title in the sidebar.

**Expected behavior**
The browser URL changes and storybook navigates to the new page.

**Actual behavior**
The browser URL changes but the preview doesn’t change.

**System:**

 System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
  Binaries:
    Node: 10.16.0 - ~/.nodenv/versions/10.16.0/bin/node
    Yarn: 1.19.1 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nodenv/versions/10.16.0/bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 78.0.1
    Safari: 13.1
  npmPackages:
    @storybook/addon-docs: 6.0.0-rc.5 => 6.0.0-rc.5
    @storybook/react: 6.0.0-rc.5 => 6.0.0-rc.5

**Comment by shilman** [comment] 2020-07-16 23:19
Looks like a regression due to https://github.com/storybookjs/storybook/pull/11537

**Comment by ndelangen** [comment] 2020-07-17 10:37
I'm investigating!

**Comment by ndelangen** [comment] 2020-07-21 09:16
I'm trying to reproduce, but I'm unable to. The navigation seems to work for me, in both dev & prod mode.

Could you make me a reproduction repo?

**Comment by blaine-stripe** [comment] 2020-07-21 19:26
@ndelangen This was happening on rc.5 but I upgraded to rc.13 and I can't reproduce. Where you checking rc.5? Anyway, might have been fixed in between!

**Comment by blaine-stripe** [comment] 2020-07-21 19:40
Doing some more digging here, so might continue to update with some information:

When I navigate, an error is thrown in my console that says
```
TypeError: Cannot read property 'toLowerCase' of null
    at sanitize (index.js:66)
    at sanitizeSafe (index.js:73)
    at toId (index.js:87)
```

It looks like null values are being passed to the sanitize method through `toId`

**Comment by blaine-stripe** [comment] 2020-07-21 21:29
Alright, I think I've tracked the issue down to the method it is happening in (and why it only happens in the production build).

In production, the `window['DOCS_MODE']` is set to true, so [`collapseAllStories`](https://github.com/storybookjs/storybook/blob/next/lib/ui/src/components/sidebar/Tree/State.tsx#L10) is called instead of [`collapseDocsOnlyStories`](https://github.com/storybookjs/storybook/blob/next/lib/ui/src/components/sidebar/Tree/State.tsx#L79). I've not figured out what differences between those 2 methods are causing the problem, but I'll keep digging.

**Comment by shilman** [comment] 2020-07-22 01:24
Thanks @blaine-stripe. Closing this & will follow up on the other issue.

**Closed by shilman** 2020-07-22 01:24 UTC
Labels: addon: docs, bug, core, tracked
