### ISSUE TITLE
Build Storybook iframe.html Failed to load resource

### ISSUE THREAD

**Issue by s-ong-c** [storybookjs/storybook#11694] opened 2020-07-27 02:49 UTC
Hi,

When build storybook is executed, output is executed or distributed.
However, it failed to load resoure despite the bundle file in iframe.html.
Of course, you can change the path to absolute path directly in iframe.html, but do you have to do this every time?

Version
   "@storybook/addon-docs": "^5.3.19",
    "@storybook/cli": "^5.3.19",

**To Reproduce**
1. build storybook
2. output storybook-static
3. load to index.html

**Screenshots**

<img width="523" alt="Screen Shot 2020-07-27 at 11 44 46 AM" src="https://user-images.githubusercontent.com/34743425/88498852-3f125e80-cfff-11ea-9ea2-0869727f48c7.png">

The path is wrong, as in the code below.

<img width="603" alt="Screen Shot 2020-07-27 at 2 38 18 PM" src="https://user-images.githubusercontent.com/34743425/88507198-d636e080-d016-11ea-9dcc-b5d7fb45190f.png">

**Comment by hyochan** [comment] 2020-07-27 09:24
We had this issue so I've managed to fix this by running `shell script` in `postbuild` step in [PR](https://github.com/dooboolab/dooboo-ui/pull/259).

**Comment by ndelangen** [comment] 2020-07-28 09:38
Do you have an example?

When I build storybook, and host it: `npx http-server ./static-storybook` it works!

We can't hard-code an absolute url, because some people host static-storybook in a sub-directory.

**Comment by s-ong-c** [comment] 2020-07-28 10:02
@ndelangen Thanks for the response,
code is in the repository below.
[https://github.com/dooboolab/dooboo-ui/tree/master/doc](https://github.com/dooboolab/dooboo-ui/tree/master/doc.)
We deploy gh-page branch after build.

**Comment by ndelangen** [comment] 2020-07-28 11:02
So you change:
```html
<script src="runtime~app.1491145c4d6866f9125d.bundle.js"></script>
```
into:
```html
<script src="/runtime~app.1491145c4d6866f9125d.bundle.js"></script>
```

Why are your assets and html pages not in the same directory when deploying?

Why would this 'hack' not be needed for `index.html`, but it is for `iframe.html`?

**Comment by s-ong-c** [comment] 2020-07-28 12:08
`package.json` script 
```
yarn build
```
build result 
<img width="527" alt="스크린샷 2020-07-28 오후 9 07 51" src="https://user-images.githubusercontent.com/34743425/88663401-817a8f00-d116-11ea-9563-75a85822a29c.png">

incorrect
```
<script src="/runtime~app.1491145c4d6866f9125d.bundle.js"></script>
```

When you create a build storybook
 
 Deploy the files in the storybook-static folder to git-pages.

The build result index.html, iframe.html and iframe.html are created. When I open the iframe.html file, the output of the bundle.js file is incorrect and it outputs

**Comment by ndelangen** [comment] 2020-07-29 09:31
@s-ong-c I'm having difficulty understanding what you mean.

Can you tell me if this statement is correct?
https://github.com/storybookjs/storybook/issues/11694#issuecomment-664975697

When I look at `https://dooboolab.github.io/dooboo-ui/iframe.html` 

I observe:
<img width="359" alt="Screenshot 2020-07-29 at 11 30 47" src="https://user-images.githubusercontent.com/3070389/88783375-fa1d3200-d18e-11ea-917d-35e5bc676f51.png">

So are you removing the `/` slashes rather then adding them?

**Comment by s-ong-c** [comment] 2020-07-29 11:00
@ndelangen 
Sorry for not giving a good explanation

first 
in the doc directory
<img width="777" alt="Screen Shot 2020-07-29 at 6 53 04 PM" src="https://user-images.githubusercontent.com/34743425/88786496-8e0dee80-d1cd-11ea-9bd5-3f84af3ef7b2.png">

build 
<img width="331" alt="Screen Shot 2020-07-29 at 6 53 24 PM" src="https://user-images.githubusercontent.com/34743425/88791184-450d6880-d1d4-11ea-8f79-0687ffa8ed04.png">

<img width="278" alt="Screen Shot 2020-07-29 at 6 53 43 PM" src="https://user-images.githubusercontent.com/34743425/88791239-5ce4ec80-d1d4-11ea-9bec-a6c056d45f0e.png">

build result static-storybook directory
<img width="469" alt="Screen Shot 2020-07-29 at 6 54 32 PM" src="https://user-images.githubusercontent.com/34743425/88791267-679f8180-d1d4-11ea-9c56-1b078c56f212.png">


<img width="605" alt="Screen Shot 2020-07-29 at 6 54 21 PM" src="https://user-images.githubusercontent.com/34743425/88791254-61a9a080-d1d4-11ea-82e4-ed2a67981b06.png">

<img width="450" alt="Screen Shot 2020-07-29 at 6 55 04 PM" src="https://user-images.githubusercontent.com/34743425/88791300-79812480-d1d4-11ea-9d57-d82927493bf0.png">

<img width="493" alt="Screen Shot 2020-07-29 at 6 55 00 PM" src="https://user-images.githubusercontent.com/34743425/88791288-738b4380-d1d4-11ea-9b6b-5be3842f7ee5.png">


The src path in Iframe.html is wrong as below.
<img width="533" alt="Screen Shot 2020-07-29 at 6 55 41 PM" src="https://user-images.githubusercontent.com/34743425/88791316-7ede6f00-d1d4-11ea-9a50-0b5db2daa3b1.png">

<img width="856" alt="Screen Shot 2020-07-29 at 6 56 50 PM" src="https://user-images.githubusercontent.com/34743425/88791342-869e1380-d1d4-11ea-9472-d44bf3711790.png">

but The src path in index.html is correct as below.
<img width="396" alt="Screen Shot 2020-07-29 at 7 52 00 PM" src="https://user-images.githubusercontent.com/34743425/88791666-0f1cb400-d1d5-11ea-8d95-e5ea8f8705d0.png">


<img width="1039" alt="Screen Shot 2020-07-29 at 6 56 39 PM" src="https://user-images.githubusercontent.com/34743425/88791329-8271f600-d1d4-11ea-8523-55e07ae6db19.png">

So are you removing the / slashes rather then adding them?  YES

But should I do this every time??

**Comment by ndelangen** [comment] 2020-07-30 10:22
That does sound like a bug..

Would you be open to trying the 6.0.0 RC? I think it's fixed in that. If you really need a patch on 5.x, could you assist?
We could schedule a meeting so I could help you get setup:
https://calendly.com/ndelangen/storybook

**Comment by shilman** [comment] 2020-07-31 10:54
Try upgrading to 6.0 RC?

```
npx sb@next upgrade --prerelease
```

**Comment by s-ong-c** [comment] 2020-07-31 12:32
> Try upgrading to 6.0 RC?
> 
> ```
> npx sb@next upgrade --prerelease
> ```

 I tried to upgrade, but the same error
so https://calendly.com/ndelangen/storybook schedule a meeting was booked.

**Comment by Marklb** [comment] 2020-08-01 04:19
Not sure what the fix would be, since I don't know anything about Expo, but I took a look and see what is happening, if that hadn't been found. Not sure if the problem was just about a fix or why it is happening, because the cause seems intentional, for some reason that may make sense if you know about expo.

The `withUnimodules` function that is wrapping the config in `.storybook/webpack.config.js` makes sure `webpackConfig.output.publicPath` resolves from the root. Seems like a strict assumption, but since I don't know anything about Expo, maybe it makes sense for those projects.

Only affects `iframe.html`, because `index.html` is built from Storybook's manager webpack-config, but Storybook's preview webpack-config scripts use `.storybook/webpack.config.js`, not manager.

Instead of a `postbuild` shell script, I did the following, to reset `output.publicPath` back to `''`:
```
// .storybook/webpack.config.js
...

module.exports = ({ config, mode }) => {
  ...

  const wUni = withUnimodules(config, {
    projectRoot: resolve(__dirname, '../'),
    // babel: {
    //   dangerouslyAddModulePathsToTranspile: [
    //     // Ensure that all packages starting with @evanbacon are transpiled.
    //     'dooboo-ui',
    //   ],
    // },
  });
  wUni.output.publicPath = ''
  return wUni
};
```

Following `withUnimodules` source for anything that would affect `output.publicPath` lead to https://github.com/expo/expo-cli/blob/ca0c33e353887da7593a8ce4fa7ad5ef654845b6/packages/webpack-config/src/env/paths.ts#L156, which describes what its doing.

**Closed** 2020-08-04 09:32 UTC
Labels: build-storybook, question / support, tracked

**Comment by s-ong-c** [comment] 2020-08-04 11:24
> Not sure what the fix would be, since I don't know anything about Expo, but I took a look and see what is happening, if that hadn't been found. Not sure if the problem was just about a fix or why it is happening, because the cause seems intentional, for some reason that may make sense if you know about expo.
> 
> The `withUnimodules` function that is wrapping the config in `.storybook/webpack.config.js` makes sure `webpackConfig.output.publicPath` resolves from the root. Seems like a strict assumption, but since I don't know anything about Expo, maybe it makes sense for those projects.
> 
> Only affects `iframe.html`, because `index.html` is built from Storybook's manager webpack-config, but Storybook's preview webpack-config scripts use `.storybook/webpack.config.js`, not manager.
> 
> Instead of a `postbuild` shell script, I did the following, to reset `output.publicPath` back to `''`:
> 
> ```
> // .storybook/webpack.config.js
> ...
> 
> module.exports = ({ config, mode }) => {
>   ...
> 
>   const wUni = withUnimodules(config, {
>     projectRoot: resolve(__dirname, '../'),
>     // babel: {
>     //   dangerouslyAddModulePathsToTranspile: [
>     //     // Ensure that all packages starting with @evanbacon are transpiled.
>     //     'dooboo-ui',
>     //   ],
>     // },
>   });
>   wUni.output.publicPath = ''
>   return wUni
> };
> ```
> 
> Following `withUnimodules` source for anything that would affect `output.publicPath` lead to https://github.com/expo/expo-cli/blob/ca0c33e353887da7593a8ce4fa7ad5ef654845b6/packages/webpack-config/src/env/paths.ts#L156, which describes what its doing.

I saw you late. You're right. Thank you very much.

**Comment by badnutz** [comment] 2021-09-17 14:29
I had a similar issue, for me, the resources were not loaded because I set in the .storybook/preview-head.html a <base href='/'>tag, after removing it the resources loaded correctly
