### ISSUE TITLE
Docgen: Errors on TS components whose names are keywords

### ISSUE THREAD

**Issue by pelotom** [storybookjs/storybook#11419] opened 2020-07-05 00:16 UTC
It appears that a change introduced in `6.0.0-beta.24` is causing my storybook to fail to load:

![image](https://user-images.githubusercontent.com/128019/86522911-c06c3c00-be19-11ea-95ff-e3f0b2e8087f.png)

I'm not sure exactly what is going on here because source maps don't seem to be working.

**Comment by shilman** [comment] 2020-07-05 04:24
Works in beta.23? Lots of changes in beta.24...

https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.24

**Comment by pelotom** [comment] 2020-07-05 04:30
Yes, it works in `6.0.0-beta.23` and before. I don't have a minimal repro currently, but can work on putting one together.

**Comment by baurine** [comment] 2020-07-15 04:02
Meet the same issue by 6.0.0-rc.3, details in https://github.com/storybookjs/storybook/issues/9514#issuecomment-658528692

**Comment by baurine** [comment] 2020-07-15 06:45
related comment: https://github.com/storybookjs/storybook/issues/9514#issuecomment-658578009

**Comment by pelotom** [comment] 2020-07-15 19:43
This seems to happen in cases where a static property is assigned to a component which is exported at its declaration site, e.g.

```ts
export default function Foo() {
  return null;
}
Foo.x = 42;
```

A workaround seems to be separating the export from the declaration:

```ts
export default Foo;
function Foo() {
  return null;
}
Foo.x = 42;
```

Class components with static properties suffer from the same problem:

```ts
export default class Foo() {
  static x = 42;
  render() { return null; }
}
```

and the workaround is the same:

```ts
export default Foo;
class Foo() {
  static x = 42;
  render() { return null; }
}
```

**Comment by baurine** [comment] 2020-07-16 02:03
Got it, thanks @pelotom !

**Comment by garrrettt** [comment] 2020-07-28 17:15
I just had this exact same issue using Storybook v5.3.19 (current latest) and fixed it with the solution above.

**Comment by dangreen** [comment] 2020-08-31 10:24
> Uncaught SyntaxError: Unexpected token '.'

switch.stories.jsx:
```jsx
import Switch from './switch'

export default {
  title: 'UI/Switch',
  decorators: [withKnobs],
  component: Switch,
}
```

```
try {
    // @ts-ignore
    switch.displayName = "switch"; // <==
    // @ts-ignore
```

**Comment by sibelius** [comment] 2020-09-01 17:19
for us, the error was because we have some old stories without using CSF format

we just moved most of them to CSF and everything is fixed

**Comment by DanielHoffmann** [comment] 2020-09-04 14:24
Still getting this error on storybook v6.0.21 and @pelotom workaround works. It is definitely related to assigning after exporting (not only in the story, but anything the story imports).

I tried to create a minimum reproducible project:
https://github.com/DanielHoffmann/storybook-bug

to run:
```
npm install 
npm run storybook
```

but I could NOT reproduce the bug in a clean project. I imagine the problem is some mix of dependencies, maybe some babel configuration as I am using a custom webpack config in my storybook project



Unfortunately my whole codebase uses this pattern:

```javascript
import gql from 'graphql-tag'
export function Component() {
  ...
}
Component.fragment = gql`
   fragment Component on Type {
      ...
   }
`
```

so I will refrain from updating until this has been figured out

**Comment by jesprider** [comment] 2020-10-02 09:45
I'm getting the same problem with v6.0.22.
After some experiments, I found that if I remove typescript from the local build it starts working again.

So `yarn remove typescript` fixed it for me. The problem now is that there is a warning in the console:
```
Module Warning (from ./node_modules/eslint-loader/dist/cjs.js):
Failed to load parser '@typescript-eslint/parser' declared in 'BaseConfig » /Users/romanalekseev/w/lib-web-uicomponents/node_modules/eslint-config-react-app/index.js#overrides[0]': Cannot find module 'typescript'
```

And another problem is that I need typescript for the rollup build.

**Comment by machinek56** [comment] 2020-10-14 07:28
I my case the problem was in naming of component - _default.tsx,_ changed it to _simple.tsx_ resolved this issue.

**Comment by phatNfqAsia** [comment] 2021-01-08 07:37
I also experience this when my 'default.[exported-component]` is not understood by Story, which should be consider as unacceptable because the way I write code should not be affected by how a document-purpose framework works.

**Comment by sibelius** [comment] 2021-01-18 22:05
![image](https://user-images.githubusercontent.com/2005841/104966584-06f14480-59c0-11eb-8dd6-b63b632a000e.png)

it is happening again for us

`Uncaught SyntaxError: Unexpected token '.'`

can we disable react doc gen?

**Comment by sibelius** [comment] 2021-01-18 22:07
related to https://github.com/storybookjs/storybook/issues/11980

**Comment by shilman** [comment] 2021-02-21 23:41
closing as dupe to #11980

**Closed by shilman** 2021-02-21 23:41 UTC
Labels: P1, block: argstable, bug, duplicate, has workaround, needs reproduction
