### ISSUE TITLE
[Bug]: (React) TypeError: Cannot read properties of undefined (reading 'clientApi')

### ISSUE THREAD

**Issue by shajjhusein** [storybookjs/storybook#24483] opened 2023-10-16 11:58 UTC
When trying to set up snapshot testing using @storybook/addon-storyshots, I encounter the following error:
 
**Steps to Reproduce:**

Set up a basic Storybook configuration in the .storybook directory at the root of the project.
Install @storybook/addon-storyshots and create a storyshots.test.js file with the default initStoryshots() call.
Run Jest tests.
**Expected Behavior:**

Storyshots should generate snapshot tests for the Storybook stories without errors.

**Actual Behavior:**

`Jest fails with the error TypeError: Cannot read properties of undefined (reading 'clientApi').`

**Additional Information:**

Storybook version:7.4.5
@storybook/addon-storyshots version: 7.4.6
Node.js version:18.18.0
Operating System: linux
Jest:29.7.0,
react :18
framework: react / @storybook/react-webpack5

**Comment by fregante** [comment] 2023-10-18 05:23
Duplicate of https://github.com/storybookjs/storybook/issues/23124

**Closed** 2023-10-19 10:25 UTC
Labels: bug, addon: storyshots, needs triage

**Comment by jonniebigodes** [comment] 2023-11-28 18:03
In case anyone reaches to this issue, the Storyshots addon is officially deprecated and will be removed in a future release of Storybook. To help with the transition process, we've created a [migration guide](https://storybook.js.org/docs/writing-tests/storyshots-migration-guide) for the available options and common use cases.
