### ISSUE TITLE
[Bug]: Storybook build breaks due to cjs/esm mismatch in its dependencies

### ISSUE THREAD

**Issue by JesseKoldewijn** [storybookjs/storybook#23608] opened 2023-07-26 07:09 UTC
### Describe the bug

Storybook build breaks instantly due to requires used in the Storybook CLI (cli-table3 package specifically).
As far as I can see this breaks the build flow on v7 and above.

We got a very simple config as well and I've tested this issue against v7.0.1, v7.0.9 and 7.1.1 with the same result. This cli-table3 dependency comes from a core package in the storybook server.

config:
```
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');
module.exports = {
	stories: [
		'../components/**/*.stories.@(js|jsx|ts|tsx|mdx)',
		'../stories/**/*.stories.@(js|jsx|ts|tsx|mdx)',
	],
	addons: [
		'@storybook/addon-links',
		'@storybook/addon-essentials',
		'@storybook/addon-interactions',
		'@storybook/addon-mdx-gfm',
	],
	framework: {
		name: '@storybook/nextjs',
		options: {},
	},
	webpackFinal: async (config) => {
		config.resolve.plugins = [
			...(config.resolve.plugins || []),
			new TsconfigPathsPlugin({
				extensions: config.resolve.extensions,
			}),
		];
		return config;
	},
	docs: {
		autodocs: true,
	},
};
```

### To Reproduce

Install the deps shown in the system output together with storybook itself in a Next.js/React.js project and try to build

### System

```shell
Environment Info:
  System:
    OS: Linux 5.15 Arch Linux
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  Binaries:
    Node: 18.17.0 - ~/.volta/tools/image/node/18.17.0/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 9.7.2 - ~/.volta/tools/image/npm/9.7.2/bin/npm
  npmPackages:
    @storybook/addon-actions: ^7.0.1 => 7.1.1 
    @storybook/addon-essentials: ^7.0.1 => 7.1.1 
    @storybook/addon-interactions: ^7.0.1 => 7.1.1 
    @storybook/addon-links: ^7.0.1 => 7.1.1 
    @storybook/addon-mdx-gfm: ^7.0.1 => 7.1.1 
    @storybook/nextjs: ^7.0.1 => 7.1.1 
    @storybook/react: ^7.0.1 => 7.1.1
```

**Comment by valentinpalkovic** [comment] 2023-07-26 07:14
I think this is a duplicate of https://github.com/storybookjs/storybook/issues/22431. Please take a look at the following comment/workaround: https://github.com/storybookjs/storybook/issues/22431#issuecomment-1630086092. Closing

**Closed by valentinpalkovic** 2023-07-26 07:14 UTC
Labels: bug, needs triage, upgrade:7.x
