### ISSUE TITLE
Autodocs: Hide "stories" section when component contains only a single story

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#21005] opened 2023-02-08 04:11 UTC
![Image](https://user-images.githubusercontent.com/488689/217431557-c748070f-4d99-4b3b-985a-c81f1fd20a16.png)

> My use case is having just a single story to show on that docs page with some description, for a very simple component. Having the same story rendered below is superfluous and looks like a mistake

https://discord.com/channels/486522875931656193/1072612950747132004/1072612950747132004

**Comment by JReinhold** [comment] 2023-02-08 08:18
Closing as duplicate of https://github.com/storybookjs/storybook/issues/20969, let's keep the discussion there.

**Closed by JReinhold** 2023-02-08 08:18 UTC
Labels: bug, addon: docs
