### ISSUE TITLE
vue3 can not use mdx `@mdx-js_react.js  does not provide an export named 'mdx'`

### ISSUE THREAD

**Issue by rashagu** [storybookjs/storybook#18451] opened 2022-06-10 08:05 UTC
**Describe the bug**
vue3 can not use mdx The requested module 
`'/node_modules/.vite-storybook/deps/@mdx-js_react.js?v=fdc54a7b' does not provide an export named 'mdx'`

**To Reproduce**

**System**
Please paste the results of `npx sb@next info` here.
  ```System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.33)
```
sb: 6.5.8 
vue3: 3.2.37

**Additional context**

**Comment by joshwooding** [comment] 2022-06-11 23:16
This is a vite builder issue and a duplicate of https://github.com/storybookjs/builder-vite/issues/398. @rashagu please check that issue for a workaround for now.

**Closed by joshwooding** 2022-06-11 23:16 UTC
Labels: bug, needs triage, vite
