### ISSUE TITLE
Regression: Slowed Builds with react-docgen-typescript

### ISSUE THREAD

**Issue by clintandrewhall** [storybookjs/storybook#7998] opened 2019-09-04 21:31 UTC
**Describe the bug**

This is a regression from the resolved state of #6430.  It may be an issue with RDTL, perhaps not.  They have https://github.com/styleguidist/react-docgen-typescript/issues/112 still open.

In that bug, @strothj and @denieler were able to improve `react-docgen-typescript-loader` to reuse the parser instance to improve performance.  I've updated our dependencies to `5.1.11` and there has been a regression.

![Screen Shot 2019-09-04 at 4 19 02 PM](https://user-images.githubusercontent.com/297604/64292889-06721e00-cf31-11e9-9da6-dc7dc7ae1a4a.png)

If I comment `react-docgen-typescript-loader` out, I get much faster build times:

![Screen Shot 2019-09-04 at 4 29 26 PM](https://user-images.githubusercontent.com/297604/64292965-2efa1800-cf31-11e9-9f11-f51883e5e1e4.png)

**To Reproduce**

1. Enable react-docgen-typescript-loader for .tsx? files, as recommended.
2. Have a repo with 10+ stories.
3. See slow build time.

You can view our config [here](https://github.com/elastic/kibana/tree/master/x-pack/legacy/plugins/canvas/.storybook).

**Comment by shilman** [comment] 2019-09-05 02:11
@clintandrewhall A few questions:
1) Is this a bug with storybook or with the overall experience of using it?
2) You say repo with 10+ stories, but in your config you've excluded `*.example.tsx` - does this fix the problem?
3) Do you know which files RDTL is running on? Is it possible there are .tsx files in node_modules that are getting unnecessarily processed?

**Comment by clintandrewhall** [comment] 2019-09-05 02:23
@shilman 

1. I'd say it's a bug that surfaces when adding Typescript documentation to components within stories using `react-docgen-typescript/-loader`.
2. I've excluded `*.examples.tsx` in that portion of the webpack config because without it, `react-docgen-typescript` tries to glean properties from my Storybook files, (which doubles the time).
3. I can alter the webpack config to [also ignore](https://github.com/elastic/kibana/blob/master/x-pack/legacy/plugins/canvas/.storybook/webpack.config.js#L53) `node_modules`... but it's unlikely our dependencies have many `.tsx` files in them.   Additionally, this regressed without a change to that rule.

**Comment by clintandrewhall** [comment] 2019-09-05 04:01
Excluding `node_modules` reduced startup time somewhat, about 20s.  Is it possible to output how many files were processed?

![Screen Shot 2019-09-04 at 10 59 49 PM](https://user-images.githubusercontent.com/297604/64310952-e3af2c00-cf67-11e9-890a-3be4e720a2a2.png)

**Comment by atanasster** [comment] 2019-09-05 17:40
@clintandrewhall what do you think about #7942 - loading prop tables from file and generating prop tables manually only when interfaces are changed. Linked in there is also my custom scripts.
Another option i was considering to create a new webpack react docgen plugin that will resemble more the webpack uglify js plugin with caching and parallel execution options.

**Comment by clintandrewhall** [comment] 2019-09-05 20:34
@atanasster @shilman a prop table cache would be sick.

**Comment by clintandrewhall** [comment] 2019-10-22 16:45
Any update on this?  I don't want this to go stale... it's still a time sync for us.

**Comment by atanasster** [comment] 2019-10-24 07:07
@clintandrewhall i am getting back from an extended vacation and we discussed with michael to make my scripts into an external webpack plugin. Hopefully soon, but in the meantime you can try my wip scripts as i posted and let me know your input.
If you need help setting up the scripts, please send a message on discord, i will be happy to assist.

**Comment by atanasster** [comment] 2019-12-02 22:10
@clintandrewhall :
I just released https://github.com/atanasster/webpack-react-docgen-typescript for caching and speed up of parsing typescript prop tables. Feedback and issues welcome to get it stable

**Comment by The-Code-Monkey** [comment] 2020-03-04 13:54
@shilman any update as to when this issue will be fixed and what version it will be fixed in?

**Comment by shilman** [comment] 2020-03-04 21:36
@The-Code-Monkey yes. we are recommending a new configuration in 6.0 and will be updating the docs this week.

**Comment by thany** [comment] 2020-03-30 14:07
@atanasster Sorry to but in, but since I'm experiencing this issue as well, I thought I'd try your plugin.

Our build time almost doubled. Went from 54sec to 1.8min 🤔
I suppose it needs to build up caches. So I gave it one more build, and that time it finished in 52sec. So that's back to where we started. A difference of 2sec over alost a minute is within the margin of error.

Any ideas?

**Comment by shilman** [comment] 2020-03-30 14:16
@The-Code-Monkey @thany 6.0 recommendations updated here https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#react-prop-tables-with-typescript

**Comment by thany** [comment] 2020-03-30 14:18
Excellent! But unfortunately that requires Storybook 6.0, doesn't it?
If only 6.0 would be final. That's why I'm hunting for a solution in 5.3.

**Comment by shilman** [comment] 2020-03-30 14:23
@thany I believe it should work with 5.3 as well. Please give it a try!

**Comment by shilman** [comment] 2020-05-21 08:23
We've just released zero-config typescript support in 6.0-beta. Please upgrade and test it!

- [Release 6.0.0-beta.12+](https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.12)
- [Migration instructions](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#zero-config-typescript)
- [Updated docs](https://github.com/storybookjs/storybook/blob/next/docs/src/pages/configurations/typescript-config/index.md)

Thanks for your help and support getting this stable for release!

**Comment by rafaelalmeidatk** [comment] 2020-08-12 16:55
I finished migrating a project from 5.3 to 6.0 and I don't have problem with the TS increased times anymore. The difference is amazing, from ~3 minutes to ~21 seconds:

![image](https://user-images.githubusercontent.com/11896398/90043821-0501b780-dca3-11ea-831d-28f6c11ac2ad.png)

**Comment by coreybruyere** [comment] 2021-04-05 19:22
I recently had to wipe node modules and package-lock while debugging an issue when implementing jest+enzyme into a project and am now getting extremely slow start times for Storybook. Initially I was getting [this error](https://github.com/storybookjs/storybook/issues/12093):
```
'loose' mode configuration must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled).
```
but seemed to have resolved it with [this](https://github.com/babel/babel/issues/11622#issuecomment-638609015).


Can't share my repo since it's for my company, but here's my main.ts:

```

**Comment by shilman** [comment] 2021-04-05 23:37
All of your storybook package versions should match.

You can do this automatically (recommended) by:
- stable: `npx sb upgrade`
- prerelease: `npx sb upgrade --prerelease`

**Comment by coreybruyere** [comment] 2021-04-06 17:13
@shilman - Thanks. That seems to have worked. Not sure what happened to my babelrc but I ended up having to add these changes like someone else noted in this thread:
```
"plugins": ["@babel/plugin-proposal-class-properties", "@babel/plugin-proposal-private-methods"],
```

**Comment by shilman** [comment] 2023-06-08 02:45
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

**Closed by shilman** 2023-06-08 02:45 UTC
Labels: question / support, performance issue, todo, typescript
