### ISSUE TITLE
Slash "/" hotkey undesirably activates while entering text-based controls

### ISSUE THREAD

**Issue by kevinzang** [storybookjs/storybook#14046] opened 2021-02-25 04:07 UTC
**Describe the bug**
Slash "/" hotkey undesirably activates while entering text-based controls.

**To Reproduce**

1. Go to https://next--storybookjs.netlify.app/official-storybook/?path=/story/addons-controls--basic.
2. Type "https:/" in one of the text-based Controls.
3. Notice focus goes to the search as soon as you type "/". I have to manually focus back on the Control to finish typing my url.

**Expected behavior**
Hotkeys should not respond when I'm typing in an unrelated input.

**Comment by ghengeveld** [comment] 2021-02-25 21:48
Duplicate of #13943

**Closed by ghengeveld** 2021-02-25 21:48 UTC
