### ISSUE TITLE
Storyshots Addon:  Cannot find module 'jest-preset-angular/setupJest' from 'loader.js'

### ISSUE THREAD

**Issue by n3utrino** [storybookjs/storybook#9072] opened 2019-12-05 08:23 UTC
**Describe the bug**
Starting the jest storyshots test fails with

```js
Cannot find module 'jest-preset-angular/setupJest' from 'loader.js'

      at Resolver.resolveModule (../node_modules/jest-runtime/node_modules/jest-resolve/build/index.js:230:17)
      at setupAngularJestPreset (../node_modules/@storybook/addon-storyshots/dist/frameworks/angular/loader.js:29:11)
      at Object.load (../node_modules/@storybook/addon-storyshots/dist/frameworks/angular/loader.js:37:3)
      at loadFramework (../node_modules/@storybook/addon-storyshots/dist/frameworks/frameworkLoader.js:31:17)
      at Object.testStorySnapshots [as default] (../node_modules/@storybook/addon-storyshots/dist/api/index.js:57:36)
```
this is due to a change in the `jest-preset-angular` module structure the library moved the code in the npm package from the root dir to `./build`

**To Reproduce**
Set up a Storybook Angular project with storyshots addon. And start the jest screenshot test.

**Expected behavior**
tests should run

**Workaround**

Mapping the `jest-preset-angular` module to the new path
```js
moduleNameMapper: {
        'jest-preset-angular/(.*)':'<rootDir>/../node_modules/jest-preset-angular/build/$1'
    }
```

**Additional context**

I think fixes should be applied here

```js
// storybook/addons/storyshots/storyshots-core/src/frameworks/angular/loader.ts
 require.requireActual('jest-preset-angular/setupJest');
```
```js

// storybook/addons/storyshots/storyshots-core/src/frameworks/angular/renderTree.ts

// eslint-disable-next-line import/no-extraneous-dependencies
import AngularSnapshotSerializer from 'jest-preset-angular/AngularSnapshotSerializer';
// eslint-disable-next-line import/no-extraneous-dependencies
import HTMLCommentSerializer from 'jest-preset-angular/HTMLCommentSerializer';
```

**Comment by shilman** [comment] 2019-12-06 07:58
@Hypnosphi any chance you can take this?

**Comment by emanguy** [comment] 2019-12-06 21:30
I had this problem too. My workaround was to install jest-preset-angular at version 6.x where the file structure matched that of the instructions.

See if running `npm install --save-dev jest-preset-angular@6.x` fixes the issue for now.

**Comment by ConnorDY** [comment] 2020-04-15 15:47
This is still an issue. Please re-open this.

**Comment by adover** [comment] 2020-05-09 08:24
This looks like it is covered in the migration guide. I will attempt a PR.

**Comment by shilman** [comment] 2020-05-11 09:02
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.5 containing PR #10699 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2020-05-11 09:02 UTC
Labels: addon: storyshots, app: angular, bug, dependencies

**Comment by cloakedninjas** [comment] 2020-06-10 10:59
Would you accept a PR that would update this dependency for users running Storybook 5?

We don't want to upgrade do a beta release in a our production app, but even if v8 came out tomorrow, this would incur work going through the breaking change list.

Or is there something incompatible with Storybook v5 and `jest-preset-angular` 8.2 ?

**Comment by shilman** [comment] 2020-06-11 02:52
I tried to patch the changes from `next` back into `master` because people clearly want the new version in 5.3. However, I couldn't get it working in `master` and ran out of time. I don't have more time to spend on getting this working, but if there's a PR for it against `master` and the CI is green, I'd be happy to merge & release.

**Comment by JMainol** [comment] 2020-11-03 11:08
I have 1 solution that works for me. I am working with these versions:
```
"jest": "^26.6.2",
"jest-preset-angular": "^7.1.1",
```
The problem is in jest-preset-angular module the dir root has changed. Now the folder /build doesnt exist. So you have to change calls to jest-preset-angular dir structure on these two files 

storybook/addons/storyshots/storyshots-core/src/frameworks/angular/loader.ts
storybook/addons/storyshots/storyshots-core/src/frameworks/angular/renderTree.ts

Here is properly explained: 
https://www.gitmemory.com/issue/storybookjs/storybook/9072/562472401
