### ISSUE TITLE
[Bug]: Archlinux, Svelte, Unable to find versions of @storybook/cli using npm

### ISSUE THREAD

**Issue by alemNative** [storybookjs/storybook#27236] opened 2024-05-23 07:18 UTC
### Describe the bug

Since i wanna update to Storybook 8 i get this error. tyin to install the cli globaly, set the ownership and so on to the user but noring helps.

### Reproduction link

localhost

### Reproduction steps

just try to install with the command npx sb init

### System

```bash
Archliniux
```

### Additional context

npx sb init
Error: Unable to find versions of @storybook/cli using npm
    at NPMProxy.runGetVersions (/usr/lib/node_modules/@storybook/cli/node_modules/@storybook/core-common/dist/index.js:37:639)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async doInitiate (/usr/lib/node_modules/@storybook/cli/dist/generate.js:146:992)
    at async withTelemetry (/usr/lib/node_modules/@storybook/cli/node_modules/@storybook/core-server/dist/index.js:28:3599)
    at async initiate (/usr/lib/node_modules/@storybook/cli/dist/generate.js:180:245)

attention => Storybook now collects completely anonymous telemetry regarding usage.
This information is used to shape Storybook's roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://storybook.js.org/telemetry

**Comment by mmorozov-noltic** [comment] 2024-05-24 12:14
I had the same issue. Thanks @mariowenak, I downgraded npm version to 10.5 and now it is working

**Comment by alex-ahumada** [comment] 2024-05-27 07:00
This also happens in macOS with init and upgrade commands. Downgrading npm to 10.5 fixes the error.

**Comment by sainu** [comment] 2024-05-28 03:35
I had the same issue with `node v22.1.0` and `npm v10.8.0`. Downgrading `node` to `v20.x` and `npm` to `10.5` fixes the error. Downgrading only `npm` to `10.5` did not fix it.

**Comment by CurlyDev1** [comment] 2024-05-29 14:26
Is there a fix for this ? 

I'm seeing the error when running `npx storybook@8.1.4 init`

Environment details
**OS:** Ubuntu 22.04.4
**Node:** v20.12.2
**NPM:** v10.5.0

Looking at the source file https://github.com/storybookjs/storybook/blob/v8.1.4/code/lib/core-common/src/js-package-manager/NPMProxy.ts#L244 it tries to parse the result as JSON, but if searching for a single version would always return a  single string which might be the reason it is failing.

Not sure if that's an issue with the `npm info` command with the --json flag as  the following just returns a string rather than json

`npm info storybook version --json`
`"8.1.4"`

**Comment by CurlyDev1** [comment] 2024-05-29 16:44
ignore me, I somehow had npm@10.8.0 installed in my dependencies for my project

**Comment by valentinpalkovic** [comment] 2024-05-31 14:49
It seems the issue is resolved in `npm@10.8.1`. Could someone please verify this?

**Comment by Bazyli12** [comment] 2024-06-01 16:24
> It seems the issue is resolved in `npm@10.8.1`. Could someone please verify this?

![image](https://github.com/storybookjs/storybook/assets/79319856/02eba194-1709-4309-addd-3720854bde28)

` npm i -g npm@10.8.1`

seems to be working

**Closed** 2024-06-01 16:57 UTC
Labels: bug, has workaround, npm, sev:S3
