### ISSUE TITLE
Uncaught TypeError: Object(...) is not a function - @emotion

### ISSUE THREAD

**Issue by theiliad** [storybookjs/storybook#4796] opened 2018-11-15 22:18 UTC
**Describe the bug**
When updating `@storybook/react` to `4.0.7`, we are receiving the following error:

![image](https://user-images.githubusercontent.com/14989804/48585305-414f8a80-e8fa-11e8-90e4-09751334e091.png)

**To Reproduce**
1. Go to https://github.com/IBM/carbon-charts
2. Update `@storybook/react` version in `packages/react/package.json` to `4.0.7`
3. Run `npm install` on the root folder of the repo
4. Run `npm run storybook` in `packages/react`

**Comment by shilman** [comment] 2018-11-16 08:46
https://github.com/storybooks/storybook/blob/next/MIGRATION.md#react-163

Please upgrade to React 16.3+ and this problem should go away. We hope to re-introduce support for older versions of React in Storybook 4.1 coming soon.

**Comment by theiliad** [comment] 2018-11-16 16:04
Working again, thanks 👍

**Comment by magicspon** [comment] 2018-11-28 16:35
I'm seeing this issue.

Using react 16.6.3, 
@storybook/react 4.0.9 
and @emotion/core 10.0.0

cheers

**Comment by psabharwal123** [comment] 2018-11-28 21:20
i am using **preact** instead of react, what changes are required in preact to make this work (basically what is the specific change from old react to 16.3+), also should i open a new bug?

**Comment by MarcNq** [comment] 2018-11-29 13:22
Also seeing this issue when trying to use emotion for my own components.

Using:
React 16.3.2 + @storybook/react 4.0.2
React 16.6.3 + @storybook/react 4.0.2
React 16.6.3 + @storybook/react 4.0.9
And @emotion/core 10.0.0 in all cases.

**Comment by immuzov** [comment] 2018-12-04 05:36
I'm seeing this issue.

Using react 16.7.0-alpha.2,
@storybook/4.1.0-alpha.10
and @emotion/core 10.0.1

cheers

**Comment by asnewman** [comment] 2018-12-06 08:55
Same

"react": "^16.2.0"
"@storybook/react": "^4.0.12"
"@emotion/core": "^0.13.1",

**Comment by nullobject** [comment] 2018-12-07 03:54
I'm seeing this issue too:

react 16.6.3
@storybook/react 4.0.7

**Comment by ysgk** [comment] 2018-12-12 07:53
I had the same problem.

- react 16.6.3
- @storybook/react 4.0.12
- @emotion/core 10.0.4
- @emotion/styled 10.0.4

After all, I downgraded emotion to 0.x.x and it's working fine now. 

- @emotion/core 0.13.1
- @emotion/styled 0.10.6

I should have taken the warning message 😅 
```
warning "@storybook/addon-knobs > @emotion/styled > @emotion/styled-base@0.10.6" has incorrect peer dependency "@emotion/core@0.x.x".
```

**Comment by igor-dv** [comment] 2018-12-12 09:15
Linking the #4925 pr for reference.

**Comment by tureey** [comment] 2018-12-15 11:37
I have:
```
"@emotion/core": "^10.0.5",
"@emotion/styled": "^10.0.5",
"@storybook/react": "^4.1.1",
"react": "^16.5.1",
"react-dom": "^16.5.1"
```

And it's not working either.

**Comment by diegopamio** [comment] 2018-12-19 20:58
Any clue on how to overcome this? I'd gladly try to fix it, but I'm not certain if I would be able to do it.

**Comment by tureey** [comment] 2018-12-20 09:40
@diegopamio I tried but I could not :cry:

**Comment by MarcNq** [comment] 2018-12-20 16:11
I think what should be done is **upgrading storybook's Emotion to last version**, but I'm not sure how could that affect to people using prior versions of Emotion, or whether that is relevant for Storybook's authors. After all, retrocompatibility can be like being flatmates with an ex.

For the ones who are looking for a nice alternative:
I recommend using [Fela](http://fela.js.org/) instead of Emotion. It's a nice library that supports the same syntax as Emotion, and more. That obviously solves the issue.

**Comment by sievan** [comment] 2018-12-21 15:00
@MarcNq This seems to be happening already 😄 https://github.com/storybooks/storybook/issues/4525

**Comment by agutoli** [comment] 2018-12-21 15:18
I just installed `@emotion/core 0.13.1` and added a resolver at webpack to force use this version.

It's working for me.

module.exports = {
  plugins: [
    // your custom plugins
  ],
  module: {
    rules: [
      // add your custom rules.
    ],
  },
  resolve: {
    alias: {
      "emotion": path.resolve(__dirname, 'node_modules/@emotion')
    }
  }
};

node: `v8.11.1`
npm: `5.10.0`
@storybook/addon-actions: `4.0.0`
@storybook/addon-links: `4.0.0`
@storybook/addons: `4.0.0`
@storybook/react: `4.0.0`

**Comment by slikts** [comment] 2018-12-30 11:04
This should not be closed; I'm using React 16.7 and getting the same error.

**Comment by slikts** [comment] 2018-12-30 11:14
I fixed this for myself by downgrading to Storybook 3.

**Comment by farcaller** [comment] 2018-12-30 11:51
That's not a "fix", it's a workaround at most. The issue needs to be addressed.

**Comment by igor-dv** [comment] 2018-12-31 17:03
This issue is being addressed as mentioned in previous comments.

**Comment by viczhuravlev** [comment] 2019-01-09 20:56
I have:

```
"@emotion/core": "10.0.6",
"@emotion/styled": "10.0.6",
"@storybook/react": "^4.1.1",
"react": "16.7.0",
"react-dom": "16.7.0"
"@storybook/react": "4.1.6",
```

And it's not working for me.

**Comment by shilman** [comment] 2019-01-10 02:09
Support for Emotion 10 is part of Storybook 5.0, which hasn't reached alpha yet. I'll post here when it's ready to try out -- ETA next week.

**Comment by vjpr** [comment] 2019-01-22 21:36
@shilman Any update on this?

**Comment by travi** [comment] 2019-01-22 21:44
@vjpr i've been using emotion v10 successfully with the v5 alpha of storybook

**Comment by vjpr** [comment] 2019-01-22 22:15
Just realized v5 alpha is out and it works for me. Should this issue be closed.

**Comment by shilman** [comment] 2019-01-23 12:48
Sorry, forgot to comment on this issue. v5 is in alpha on the `next` NPM tag. Here's the latest alpha: https://github.com/storybooks/storybook/releases/tag/v5.0.0-alpha.8

Upgrade today to try it out. We're hoping to progress to RC by next week!

**Comment by ahmadalfy** [comment] 2019-02-18 09:43
Can confirm upgrading to storyboard 5.0.0-RC1 fixed it

**Comment by Rolandisimo** [comment] 2019-02-18 10:17
Also, ran into an issue throwing `Uncaught TypeError: Object(...) is not a function`. 
Have a CRA2 build. Nothing worked until I tried the 5.0.0-alpha version of @storybook/react.

Thanks!

**Comment by ahmadalfy** [comment] 2019-02-18 11:51
@Rolandisimo better than using `alpha` you can use [5.0.0-RC1](https://github.com/storybooks/storybook/releases/tag/v5.0.0-rc.1)

**Comment by Rolandisimo** [comment] 2019-02-18 12:31
@ahmadalfy Fails with any 4.x.x storybook/addon I've tried. 
Reference issue: https://github.com/storybooks/storybook/issues/5645

**Comment by SebPez** [comment] 2019-02-25 05:22
@viczhuravlev did you manage to fix it?

**Comment by SebPez** [comment] 2019-02-25 05:45
I was able to use Storybook 4 and Emotion 10 *ONLY* when I installed with `yarn` instead of `npm` even with different node versions starting a 8.x.x.



```
     node v11.10.0
    "react": "^16.7.0",
    "react-dom": "^16.7.0"
    "gatsby": "^2.0.115",

    "@babel/core": "7.2.2",
    "babel-loader": "8.0.5",

    "@storybook/addon-actions": "^4.1.11",
    "@storybook/addon-info": "^4.1.11",
    "@storybook/addon-knobs": "^4.1.11",
    "@storybook/react": "4.1.11",

    "@emotion/core": "^10.0.7",
    "@emotion/styled": "^10.0.7",
    "emotion-normalize": "^10.0.0",
```

**Comment by Ziv-Barber** [comment] 2019-03-04 09:30
To fix this remove all the '@emotion' packages from package.json, remove node_modules and yarn.lock (or package json lock) and yarn install.

**Comment by artemirq** [comment] 2019-03-05 19:58
> After all, I downgraded emotion to 0.x.x and it's working fine now.
> @emotion/core 0.13.1
> @emotion/styled 0.10.6

@ysgk Thanks, it's works

**Comment by angelozehr** [comment] 2019-04-03 12:28
Has anyone found out what caused the problem in the first place? I am running on the latest versions and still encounter this error

**Comment by shilman** [comment] 2019-04-03 13:44
@angelozehr the original problem was caused by a dependency on react 16.3+ that was introduced in storybook 4.0 due to emotion. Users trying to run older react projects in 4.0 ran into this error. However, in SB4.1 we split the "manager" (UI) and "preview" (user components) into two separate processes so that it was possible to use SB4.1 with older versions of React. Now in 5.0 it appears that the same error message has come back, possibly for a different underlying problem. To make things more difficult/confusing yarn appears to have some weird interactions with Storybook, so in some cases clearing your `node_modules` and `yarn.lock` fix some dependency-related problems. 😢

**Comment by shilman** [comment] 2019-04-10 03:53
@angelozehr It is a regression. See https://github.com/storybooks/storybook/issues/6474

**Comment by kirtrainford** [comment] 2019-07-04 09:04
Still getting this problem, not using @emotion package
```
    "@storybook/react": "^5.1.9",
    "react": "^16.8.6"
```
Addons:
```
    "@storybook/addon-actions": "^5.1.9",
    "@storybook/addon-knobs": "^5.1.9",
    "@storybook/addon-links": "^5.1.9",
    "@storybook/addon-options": "^5.1.9",
    "@storybook/addon-storyshots": "^5.1.9",
    "@storybook/addons": "^5.1.9",
```

**Comment by lppedd** [comment] 2019-10-01 08:30
Still happening on 5.2.1. A bit frustrating.

**Comment by shilman** [comment] 2019-10-01 13:31
@lppedd Are you saying React15 support is broken in 5.2.1?

**Comment by lppedd** [comment] 2019-10-01 13:39
@shilman apparently yes.

**Comment by shilman** [comment] 2019-10-01 13:50
confirmed 😭

**Comment by shilman** [comment] 2019-10-01 14:19
@ndelangen this is broken in `cra-react15` and also on the now deployment, but since storyshots are enabled it apparently doesn't break the build. any ideas?

**Comment by shilman** [comment] 2019-10-14 11:00
Closing this as a dupe to #8284

**Closed by shilman** 2019-10-14 11:00 UTC
Labels: app: react, high priority, question / support

**Comment by abudi1416** [comment] 2021-11-07 10:27
having the same issue when using Storybook along with Angular 11 project
