### ISSUE TITLE
TypeError: The "id" argument must be of type string. Received an instance of Object

### ISSUE THREAD

**Issue by icaro-capobianco** [storybookjs/storybook#18801] opened 2022-07-27 19:56 UTC
After running storybook-start or build-sb I get the following

The error doesn't stop the execution and after a few seconds I get to use storybook or build it. Unfortunately this might relate to Chromatic which I am trying to use.

https://github.com/chromaui/chromatic-cli/issues/618
```
ERR! TypeError: The "id" argument must be of type string. Received an instance of Object
ERR!     at new NodeError (node:internal/errors:371:5)
ERR!     at validateString (node:internal/validators:119:11)
ERR!     at Module.require (node:internal/modules/cjs/loader:998:3)    
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at interopRequireDefault (C:\Users\icaro\Desktop\code\gsg\gsg-workspace\node_modules\.pnpm\@storybook+core-common@6.5.9_6mntlpnkhn6c7tucibhqtuw2yq\node_modules\@storybook\core-common\dist\cjs\presets.js:178:16)
ERR!     at getContent (C:\Users\icaro\Desktop\code\gsg\gsg-workspace\node_modules\.pnpm\@storybook+core-common@6.5.9_6mntlpnkhn6c7tucibhqtuw2yq\node_modules\@storybook\core-common\dist\cjs\presets.js:194:10)     
ERR!     at loadPreset (C:\Users\icaro\Desktop\code\gsg\gsg-workspace\node_modules\.pnpm\@storybook+core-common@6.5.9_6mntlpnkhn6c7tucibhqtuw2yq\node_modules\@storybook\core-common\dist\cjs\presets.js:203:20)     
ERR!     at C:\Users\icaro\Desktop\code\gsg\gsg-workspace\node_modules\.pnpm\@storybook+core-common@6.5.9_6mntlpnkhn6c7tucibhqtuw2yq\node_modules\@storybook\core-common\dist\cjs\presets.js:256:18
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (C:\Users\icaro\Desktop\code\gsg\gsg-workspace\node_modules\.pnpm\@storybook+core-common@6.5.9_6mntlpnkhn6c7tucibhqtuw2yq\node_modules\@storybook\core-common\dist\cjs\presets.js:255:18)    
ERR!  TypeError: The "id" argument must be of type string. Received an 
instance of Object
ERR!     at new NodeError (node:internal/errors:371:5)
ERR!     at validateString (node:internal/validators:119:11)
ERR!     at Module.require (node:internal/modules/cjs/loader:998:3)    
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at interopRequireDefault (C:\Users\icaro\Desktop\code\gsg\gsg-workspace\node_modules\.pnpm\@storybook+core-common@6.5.9_6mntlpnkhn6c7tucibhqtuw2yq\node_modules\@storybook\core-common\dist\cjs\presets.js:178:16)
ERR!     at getContent (C:\Users\icaro\Desktop\code\gsg\gsg-workspace\node_modules\.pnpm\@storybook+core-common@6.5.9_6mntlpnkhn6c7tucibhqtuw2yq\node_modules\@storybook\core-common\dist\cjs\presets.js:194:10)     
ERR!     at loadPreset (C:\Users\icaro\Desktop\code\gsg\gsg-workspace\node_modules\.pnpm\@storybook+core-common@6.5.9_6mntlpnkhn6c7tucibhqtuw2yq\node_modules\@storybook\core-common\dist\cjs\presets.js:203:20)     
ERR!     at C:\Users\icaro\Desktop\code\gsg\gsg-workspace\node_modules\.pnpm\@storybook+core-common@6.5.9_6mntlpnkhn6c7tucibhqtuw2yq\node_modules\@storybook\core-common\dist\cjs\presets.js:256:18
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (C:\Users\icaro\Desktop\code\gsg\gsg-workspace\node_modules\.pnpm\@storybook+core-common@6.5.9_6mntlpnkhn6c7tucibhqtuw2yq\node_modules\@storybook\core-common\dist\cjs\presets.js:255:18) {  
ERR!   code: 'ERR_INVALID_ARG_TYPE'
ERR! }
```

**Comment by icaro-capobianco** [comment] 2022-07-27 20:40
I added the following to debug and workaround the issue.

```
function interopRequireDefault(filePath) {
  // Log was giving me { type: "presets", name: undefined }
  console.log(filePath)
  // So I skipped that one
  if ( filePath.type === 'presets' && undefined === filePath.name ) {
    return {}
  }
  // eslint-disable-next-line global-require,import/no-dynamic-require
  var result = require(filePath);

  var isES6DefaultExported = typeof result === 'object' && result !== null && typeof result.default !== 'undefined';
  return isES6DefaultExported ? result.default : result;
}
```

This also fixed my issue with chromatic https://github.com/chromaui/chromatic-cli/issues/618

**Comment by lukesiedle** [comment] 2022-07-28 14:11
Had the same issue (using vite), but turned out to be an addon defined in `.storybook/main.js` that I had actually removed from dependencies.  Removing the addon from here solved the issue.  

```
module.exports = {
  ...,
  addons: [ ] 
}
```

**Comment by ColmBhandal** [comment] 2022-08-09 12:40
Given @lukesiedle's discovery, it would be helpful if running Storybook failed with a more informative error in the case where an addon is used and that addon does not exist as a dependency in the project. E.g. something like:

`WARNING: Addon X is defined in ...path/main.js/module.exports but does not exist as a dependency in this project. The addon will be skipped.`

**Comment by rosskevin** [comment] 2022-08-10 18:15
Agreed, as I was migrating our addon to 7.0.0-alpha.18, I forgot to change (inside the addon project)

```diff
- addons: ["../preset.js", "@storybook/addon-essentials"],
+ addons: ["../manager.js", "@storybook/addon-essentials"],
```

So this error bubbled up.  A more informative message would indeed be helpful.

**Comment by mzehetho** [comment] 2022-08-11 07:33
Changing 
```diff
- addons: ['@storybook/addon-links/preset'],
+ addons: ['@storybook/addon-links'],
```
fixed it for me

**Comment by robespmun** [comment] 2022-09-16 10:25
> Changing
> 
> ```diff
> - addons: ['@storybook/addon-links/preset'],
> + addons: ['@storybook/addon-links'],
> ```
> 
> fixed it for me

Fixed it for me too! Thanks for the tip

**Comment by janaagaard75** [comment] 2022-10-03 10:13
We had this issue because `addons: ["@storybook-react-i18next"]` should have been written `addons: ["storybook-react-i18next"]`. The misconfiguration wasn't reported with Storybook 6.5.9, but it became apparent with version 6.5.12.

**Comment by BibhushanKarki** [comment] 2022-10-18 05:38
I'm using storybook v6.5.12. I'm getting this same error. How to fix this?

**Comment by EricDeColS** [comment] 2022-10-19 21:11
It just started happening to me, it broke down earlier, I made it work again,  wento to work, came back to my personal project without touching a finger on it, and now it's just broken

**Comment by bryanhidalgo** [comment] 2022-10-26 18:40
I had the same issue with '@storybook/preset-create-react-app`, I removed it and that fixed it.

**Comment by hyeongrok7874** [comment] 2022-11-09 15:10
> I had the same issue with `@storybook/preset-create-react-app`, I removed it and that fixed it.

Thanks I solved it 😍

**Comment by robksawyer** [comment] 2022-11-23 01:13
I removed `@whitespace/storybook-addon-html` and it worked for me.

**Comment by LordZombi** [comment] 2022-12-02 11:22
Error message is really confusing.
Point is to have installed (listed in your package.json) all the addons you are using in storybook.
So I think proper fix is just update an error message.

**Comment by Jero786** [comment] 2022-12-23 20:46
I needed to remove both add-ons in order to avoid that error 
```
"@storybook/preset-create-react-app",
"@storybook/addon-a11y"
```

**Comment by shilman** [comment] 2023-01-13 16:21
Zoinks!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.26 containing PR #20455 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2023-01-13 16:21 UTC
Labels: bug, needs triage

**Comment by kevzettler** [comment] 2023-01-31 04:23
I am getting this issue only when I use `yarn`s  plug n play mode. If I install dependencies to `node_modules` I get this error

I have tried following @shilman suggestion and try upgrading with
`npx sb@next upgrade --prerelease`

However the upgrade process then fails at the babel migration step with error:

```
✅ ran autodocsTrue migration
⚠️  failed to check fix missing-babelrc
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@babel/plugin-proposal-class-properties' imported from /Users/kevzettler/code/react-regl/babel-virtual-resolve-base.js
    at new NodeError (/Users/kevzettler/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:2240:5)
    at packageResolve (/Users/kevzettler/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:2776:9)
    at moduleResolve (/Users/kevzettler/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:2804:18)
    at defaultResolve (/Users/kevzettler/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:2835:13)
    at /Users/kevzettler/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:2855:14
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/kevzettler/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:45:103)
    at _next (/Users/kevzettler/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:46:194)
    at /Users/kevzettler/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:46:364
    at new Promise (<anonymous>) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

**Comment by IanVS** [comment] 2023-01-31 12:57
@kevzettler would you mind opening a new issue with a reproduction that we can take a look into?

**Comment by kevzettler** [comment] 2023-01-31 17:45
@IanVS I have opened a bug at: https://github.com/storybookjs/storybook/issues/20861

**Comment by Rutulpatel7077** [comment] 2023-02-18 00:58
@shilman Looks like `npx sb@next upgrade --prerelease` fixes issues with Yarn PnP
