### ISSUE TITLE
Spec for Story Actions API

### ISSUE THREAD

**Issue by ghengeveld** [storybookjs/storybook#29108] opened 2024-09-12 09:30 UTC
```ts
experimental_setActions(actionId, {
  [storyId]: {
    icon: PlayIcon,
    title: 'Run component tests',
    event: PROVIDER_ID + '_RUN',
    payload: { storyIds: [storyId] }
  }
})
```

**Comment by JReinhold** [comment] 2024-11-05 09:16
Duplicate of #29101

**Closed by JReinhold** 2024-11-05 09:16 UTC
