### ISSUE TITLE
[Bug]: CSP - unsafe-eval. SB7 with angular library shows CSP error.

### ISSUE THREAD

**Issue by miszol1** [storybookjs/storybook#24355] opened 2023-10-03 08:33 UTC
### Describe the bug

SB7 with angular library shows CSP error :
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'".

    at new Function (<anonymous>)
    at Array.revive (chunk-6XESPNK2.js:34:3836)
    at JSON.parse (<anonymous>)
    at parse (chunk-6XESPNK2.js:34:6221)
    at PostmsgTransport.handleEvent (runtime.js:1:3062)

In reproduction CSP header is :
script-src 'self' 'unsafe-inline'.

### To Reproduce

https://stackblitz.com/edit/github-m6jtth?file=.storybook%2Fmanager-head.html

### System

Environment Info:

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
  npmPackages:
    @storybook/addon-a11y: ~7.0.27 => 7.0.27 
    @storybook/addon-actions: ~7.0.27 => 7.0.27 
    @storybook/addon-essentials: ~7.0.27 => 7.0.27 
    @storybook/addon-links: ~7.0.27 => 7.0.27 
    @storybook/addon-storyshots: ~7.0.27 => 7.0.27 
    @storybook/angular: ~7.0.27 => 7.0.27 
    @storybook/testing-library: ~0.2.0 => 0.2.2 
    @storybook/theming: ~7.0.27 => 7.0.27

**Comment by drzamich** [comment] 2023-10-05 19:29
I'm having the same issue with Storybook `6.5.16`

**Comment by valentinpalkovic** [comment] 2023-10-14 17:43
I have tracked this issue down to the library `telejson`:
https://github.com/storybookjs/telejson/blob/master/src/index.ts#L373

@Marklb 
Could we figure avoiding the `telejson` package. This commit has introduced it:
https://github.com/storybookjs/storybook/commit/477eec56ea0e866d080f6937fb4be38c7b33d8f6

Do you have any idea ideas in mind to compare `moduleMetadata`?

**Comment by Marklb** [comment] 2023-10-15 02:09
@valentinpalkovic I will take a look, but I don't think this is caused by Angular stringifying `moduleMetadata`. The line that you linked in `telejson` is in the reviver, but we never parse the stringified `moduleMetadata`. So, the reviver doesn't get used.

Removing `'@storybook/addon-a11y'` from `.storybook/main.ts` will stop the error.

The following is what I have narrowed the cause down to, but I haven't looked for a solution, yet.

From the error in the reproduction, the error is thrown by a line in the transport code:
![image](https://github.com/storybookjs/storybook/assets/8348647/90f457f9-c16c-4b24-8856-dc54d7d1f1e6)
I put a breakpoint on the error and stepped back through the call stack to where it parses data and it appears to be from `@storybook/addon-ally`:
![image](https://github.com/storybookjs/storybook/assets/8348647/c6f937b9-1c0c-4776-9fdf-7d1153745b18)
In that string, I see a `"_constructor-name__"` property that would get handled by the line you referenced in `telejson`:
![image](https://github.com/storybookjs/storybook/assets/8348647/4366aec9-ce85-48e3-b7e1-9b6f9a68c5e3)
The error is thrown, when it tries to revive this value, which I assume is a class from the `axe` tool, but I haven't dug into that. yet:
![image](https://github.com/storybookjs/storybook/assets/8348647/a60d8c8c-7745-4c89-b8a1-a9fbe7b22d4c)

**Comment by valentinpalkovic** [comment] 2023-10-15 13:02
@Marklb It seems I was too hasty with tracking down the cause. Thank you for the correction!

**Comment by miszol1** [comment] 2023-10-27 08:42
@Marklb any news here? is there a workaround for it?

**Comment by Marklb** [comment] 2023-10-27 16:41
@miszol1 I submitted a PR, but it hasn't been merged. #24477

**Closed** 2023-10-27 17:46 UTC
Labels: bug, addon: a11y
