### ISSUE TITLE
[Bug]: TypeError: Cannot redefine property: default

### ISSUE THREAD

**Issue by pedro3g** [storybookjs/storybook#23314] opened 2023-07-05 02:54 UTC
### Describe the bug

I've been trying to configure the Storybook in Next.js for a few hours now. It turns out that when running "npm run storybook" and accessing it in the browser, I get an error message:
![image](https://github.com/storybookjs/storybook/assets/30221184/709fd9ca-ea9e-4cab-ad43-6894e65e8dae)

I created a repository containing the code that is generating error. It's just code generated by "create-next-app" and "nb init"
https://github.com/pedro3g/nextjs-storybook-issue

### To Reproduce

https://github.com/pedro3g/nextjs-storybook-issue

### System

```shell
Environment Info:

  System:
    OS: Linux 6.1 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  Binaries:
    Node: 20.3.1 - ~/.nvm/versions/node/v20.3.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.3.1/bin/yarn
    npm: 9.7.2 - ~/.nvm/versions/node/v20.3.1/bin/npm
  npmPackages:
    @storybook/addon-essentials: ^7.0.25 => 7.0.25 
    @storybook/addon-interactions: ^7.0.25 => 7.0.25 
    @storybook/addon-links: ^7.0.25 => 7.0.25 
    @storybook/blocks: ^7.0.25 => 7.0.25 
    @storybook/nextjs: ^7.0.25 => 7.0.25 
    @storybook/react: ^7.0.25 => 7.0.25 
    @storybook/testing-library: ^0.0.14-next.2 => 0.0.14-next.2
```

**Comment by JungHoonGhae** [comment] 2023-07-05 03:10
this is exactly what I am getting right now.....

**Comment by roottool** [comment] 2023-07-05 03:11
I am also experiencing this issue. I use Storybook latest version(7.0.25) and Next.js latest version(13.4.8).
But I don't reproduce it when I use Next.js v13.4.7.

**Comment by fqf** [comment] 2023-07-05 03:20
the same problem

**Comment by fqf** [comment] 2023-07-05 03:25
> I am also experiencing this issue. I use Storybook latest version(7.0.25) and Next.js latest version(13.4.8). But I don't reproduce it when I use Next.js v13.4.7.

It really works for me. I downgrade next version and the problem has gone. Thank you.

**Comment by sookmax** [comment] 2023-07-05 07:56
Guys, this issue has been resolved with this pull request #23296. I'm not sure when this fix is going to be released, but you can follow up #23287, which is the same issue reported earlier.

**Comment by federicocappellotto97** [comment] 2023-07-05 09:20
Same here. Upgraded next to 13.4.8 and storybook is not working anymore

**Comment by shilman** [comment] 2023-07-05 10:22
Fixed in https://github.com/storybookjs/storybook/releases/tag/v7.0.26 and also in the latest beta

**Closed by shilman** 2023-07-05 10:22 UTC
Labels: bug, needs triage

**Comment by Atralbus** [comment] 2023-07-21 21:38
If you are still experiencing this issue on new versions, it may be related to the change you made in `preview.ts` file to unoptimize the image: https://github.com/storybookjs/storybook/issues/23561

**Comment by mbret** [comment] 2023-07-28 13:02
I still have the error on latest version and I never did any change to preview for unoptimizing images
