### ISSUE TITLE
Storybook Server UI bottom pane renders BEHIND top pane

### ISSUE THREAD

**Issue by stheobald** [storybookjs/storybook#6493] opened 2019-04-12 00:44 UTC
When running the storybook serverUI (ReactNative project), the header, and content of the bottom pane (addons etc) is rendered behind the (transparent) story pane.

Expected that the bottom pane would have sole occupancy of the area below its draggable header.

Seen on Linux Chrome, and confirmed by @benoitdion 
![sb_serverUI](https://user-images.githubusercontent.com/10693305/56004634-826c8f00-5d20-11e9-9da9-c899dbabe9d9.png)

**Comment by divbhasin** [comment] 2019-04-13 15:49
@stheobald @shilman @benoitdion I would like to work on this issue, but haven't been able to duplicate it. I created a react-native project, setup Storybook for react-native, installed some add-ons, and ran `yarn storybook`. Is there something I'm missing here?

**Comment by shilman** [comment] 2019-04-13 17:10
@divbhasin Haven't repro'd myself yet, but from what I can tell from the screenshot the page is in its loading state. Is that what you're looking at?

**Comment by divbhasin** [comment] 2019-04-14 00:07
@shilman I didn't see the crna app in the examples-native folder before. I'm able to reproduce on that app. I will work on a fix.

**Comment by shilman** [comment] 2019-06-04 18:12
Yay!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.1.0-rc.5 containing PR #6968 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2019-06-04 18:12 UTC
Labels: app: react-native-server, bug, ui
