### ISSUE TITLE
[Bug]: BigInt support

### ISSUE THREAD

**Issue by gagarin55** [storybookjs/storybook#25309] opened 2023-12-22 15:47 UTC
### Describe the bug

I don't know why you have closed the issue - https://github.com/storybookjs/storybook/issues/13950

I'm using latest version of Storybook and it still crashes on BigInt

### To Reproduce

to reproduce you have to use BigInt type in args for component. See - https://github.com/storybookjs/storybook/issues/13950

### System

```bash
Storybook Environment Info:

  System:
    OS: Linux 5.15 Linux Mint 21 (Vanessa)
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 4.0.1 - ~/.nvm/versions/node/v18.17.1/bin/yarn <----- active
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
  Browsers:
    Chrome: 120.0.6099.109
  npmPackages:
    @storybook/addon-essentials: ^7.5.3 => 7.5.3 
    @storybook/addon-interactions: ^7.5.3 => 7.5.3 
    @storybook/addon-links: ^7.5.3 => 7.5.3 
    @storybook/addon-onboarding: ^1.0.8 => 1.0.8 
    @storybook/addon-themes: ^7.5.3 => 7.5.3 
    @storybook/blocks: ^7.5.3 => 7.5.3 
    @storybook/react: ^7.5.3 => 7.5.3 
    @storybook/react-webpack5: ^7.5.3 => 7.5.3 
    @storybook/testing-library: ^0.2.2 => 0.2.2 
    eslint-plugin-storybook: ^0.6.15 => 0.6.15 
    storybook: ^7.5.3 => 7.5.3
```

**Comment by valentinpalkovic** [comment] 2023-12-22 16:02
Duplicate of https://github.com/storybookjs/storybook/issues/22452

**Closed by valentinpalkovic** 2023-12-22 16:02 UTC
Labels: bug, needs triage
