### ISSUE TITLE
storybook on react-native does not work with hmr (hot module reload) properly

### ISSUE THREAD

**Issue by macrozone** [storybookjs/storybook#2081] opened 2017-10-18 11:25 UTC
For HMR (hot module reload) to work, the root component has to be a class, as it seems.

I therefore added this to storybook/storybook.js :

```
const StorybookUIOrg = getStorybookUI({ port: 7007, onDeviceUI: true })

const StorybookUI = class extends Component {
  render() {
    return <StorybookUIOrg />
  }
}

AppRegistry.registerComponent('homestory', () => StorybookUI)
```

This used to work in the past, but with latest version, i just see the native ui menu and some warnings like:

"The prop url is marked as required in `StoryView` but it's value is null"

and 

"The prop url is marked as required in `OnDeviceUI`, but it's value is null"

Edit: without the class above, there is no warning. But hot reload does not work. On the simulator it notifies about "hot reloading", but nothing changes.

Edit 2: if i change to a different story after hot reload and back, the changes are applied... So what's wrong? 

I now switched back to live reload, HMR seems broken at the time beeing

**Comment by danielduan** [comment] 2017-10-30 15:16
This is related to https://github.com/storybooks/storybook/issues/2117

**Comment by macrozone** [comment] 2017-11-02 12:30
@danielduan The issue is not resolved. I updated storybook to yesterdays version (3.2.14) and verified that the storybook index file matches this template https://github.com/storybooks/storybook/pull/2194 (I already had the base component as a class instead of a stateless function).

HMR still does not work in this setup. Any change to a file will trigger a refresh in the app, but it will crash with: 
```
console.error: "(node) warning: possible EventEmitter memory leak detected. %d listeners added. Use emitter.setMaxListeners() to increase limit.", 11

Object.console.error
    hashAssetFiles:55868:11
EventEmitter.addListener
    hashAssetFiles:166001:15
 (...)
```

by using the debugger i see that this happens in 

```
 _this3._events.on('setCurrentStory', function (d) {
          return _this3._selectStory(d);
        });
```

**Comment by danielduan** [comment] 2017-11-02 13:45
The decorators might break hmr because they're not classes. I'd love a pr if you can help out and see what you can find.

**Comment by danielduan** [comment] 2017-11-08 00:18
Do you have a repo so I can try to reproduce this? @macrozone 

I just tried in our CRNA example and it seems to work:
```
7:14:27 PM: [React Transform HMR] Patching Welcome

7:14:45 PM: [React Transform HMR] Patching Welcome
```

**Comment by Maxim-Filimonov** [comment] 2018-02-03 12:29
I found this issue while trying to figure out why 3.3.12 is not working with HMR.
It does print in the console as expected, however the storybook itself doesn't get updated. 
See [the video](https://youtu.be/iY3fZzZtpaM) of the issue. Repository is fresh from GitHub - bootstraped using `yarn bootstrap`.

**Comment by macrozone** [comment] 2018-02-08 13:40
it's hard to tell what's wrong with hmr and react-native. It works for some time, but starts to get slower and slower, eats cpu on both the device and the computer, throwing errors like the dreaded "possible event emitter leaked" and now kills the server eventually (see https://github.com/storybooks/storybook/issues/2923)

So it basically "works" but extremly unreliable and i therefore wonder if anyone successfully uses it on real projects

**Comment by axelnormand** [comment] 2018-03-09 09:15
I too am getting this error.
For now I've added this hack to my init storybook function to at least delay the error for a bit :)
I'll report back if it works or not.

```
require('events').EventEmitter.defaultMaxListeners = 200;
```

I'm not using decorators but am using create react native app, typescript and storyshots.
Happy to attempt a PR if anyone can suggest the best place to look

**Comment by Gongreg** [comment] 2018-11-09 08:44
Hey @jqn, so to be clear you had to create StorybookUIHMRRoot even though we already create it in getStorybookUI?

**Comment by jjm340** [comment] 2019-02-14 21:04
@jqn This worked for me as well

**Comment by shilman** [comment] 2019-03-22 15:35
Shiver me timbers!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.12 that addresses this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment] 2019-03-22 15:50
We’ve released a brand new `@storybook/react-native` with a bunch of core improvements. It’s available in the latest `5.1-alpha` on `next` and has been verified by several RN users on their existing apps. It should fix a bunch of compatibility issues, especially if you’re using the web server feature. Please give it a try and comment here if it fixes your problem. Migration instructions available here: https://github.com/storybooks/storybook/blob/next/MIGRATION.md#react-native-server

@macrozone @odino @b3ngineer @maxhungry @tonyxiao @Bardiamist @danielduan @EskelCz @Maxim-Filimonov @axelnormand @jqn @jjm340 @iamolegga @FunkSoulNinja @miltoneiji @Gongreg

**Comment by stereodenis** [comment] 2019-07-25 09:00
Still not working on 5.1 for me

**Comment by shilman** [comment] 2019-07-25 09:02
@stereodenis try `5.2-beta`? 🙈

**Comment by stereodenis** [comment] 2019-07-25 09:27
@shilman  5.2-beta.7
![image](https://user-images.githubusercontent.com/1406461/61862996-6fe52280-aed7-11e9-953b-fba56f132a12.png)

**Comment by Gongreg** [comment] 2019-07-25 10:05
Sadly there was no effort done to fix hmr

**Comment by Gongreg** [comment] 2019-11-02 20:18
React Native 0.61 has a new reload format, so closing this issue. The new issue is #7916

**Closed by Gongreg** 2019-11-02 20:18 UTC
Labels: app: react-native, bug, help wanted, todo
