### ISSUE TITLE
addon-docs: `obj.serialize is not a function` when using Webpack 5 filesystem cache

### ISSUE THREAD

**Issue by umpox** [storybookjs/storybook#15702] opened 2021-07-28 14:06 UTC
**Describe the bug**
It seems the Webpack 5 cache isn't able to handle files through `addon-docs`
```
<w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/Users/tomross/dev/storybook-repod/example/node_modules/babel-loader/lib/index.js??ruleSet[1].rules[0].use[0]!/Users/tomross/dev/storybook-repod/example/stories/Container.tsx': obj.serialize is not a function
<w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> Array { 5 items } -> react-docgen-typescript-plugin/dist/dependency
```

**To Reproduce**
Clone https://github.com/umpox/storybook-repod

```
cd example

yarn

yarn storybook
```

**System**
```
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
  Browsers:
    Chrome: 92.0.4515.107
    Firefox: 88.0
    Safari: 14.1.2
  npmPackages:
    @storybook/addon-actions: ^6.3.6 => 6.3.6 
    @storybook/addon-essentials: ^6.3.6 => 6.3.6 
    @storybook/addon-links: ^6.3.6 => 6.3.6 
    @storybook/builder-webpack5: ^6.3.6 => 6.3.6 
    @storybook/manager-webpack5: ^6.3.6 => 6.3.6 
    @storybook/react: ^6.3.6 => 6.3.6 

```

**Comment by shilman** [comment] 2021-07-29 02:35
@bebraw any idea what's going on here?

**Comment by bebraw** [comment] 2021-07-29 07:36
@shilman After debugging, I found out we should add a couple of webpack 5 related serialization methods to the doc dependency. I pushed the fix to https://github.com/hipstersmoothie/react-docgen-typescript-plugin/pull/45 and you can cherrypick it through the commit 543e9056e51a3b27 from my branch to test against. Maybe it's good to do a canary release first to confirm the fix.

**Comment by umpox** [comment] 2021-07-29 08:34
Thanks for the quick response! FWIW I patched my `node_modules` with your changes and everything worked great for me

**Comment by bebraw** [comment] 2021-07-29 08:38
@umpox Cool, that's how I tested it as well. 👍

**Comment by 7rulnik** [comment] 2021-12-29 14:11
Related upstream PR https://github.com/storybookjs/react-docgen-typescript-plugin/pull/6/

**Comment by 7rulnik** [comment] 2022-01-14 15:24
@bebraw @shilman I'm trying to use cache and getting cache invalidation

```
#17 45.99     [webpack.cache.PackFileCacheStrategy] Pack got invalid because of write to:
ResolverCachePlugin|normal|path=|/client/src/components/best_price|request=|./best_price.stories.mdx
```

In the first place, I thought that it's prettier in my pipeline or something. I checked this idea and had no luck.

After that, I decided to look into react-docgen-typescript-plugin and I think it could be related to it.

So we inject code like this into a module:
```
try {
    // @ts-ignore
    ErrorDialog.displayName = "ErrorDialog";
    // @ts-ignore
    ErrorDialog.__docgenInfo = { "description": "", "displayName": "ErrorDialog", "props": { "visible": { "defaultValue": null, "description": "", "name": "visible", "required": true, "type": { "name": "boolean" } }, "onClose": { "defaultValue": null, "description": "", "name": "onClose", "required": true, "type": { "name": "() => void" } }, "onRetry": { "defaultValue": null, "description": "", "name": "onRetry", "required": true, "type": { "name": "(args: any) => void" } } } };
    // @ts-ignore
    if (typeof STORYBOOK_REACT_CLASSES !== "undefined")
        // @ts-ignore
        STORYBOOK_REACT_CLASSES["client/src/components/faq/error_dialog/error_dialog.stories.tsx#ErrorDialog"] = { docgenInfo: ErrorDialog.__docgenInfo, name: "ErrorDialog", path: "client/src/components/faq/error_dialog/error_dialog.stories.tsx#ErrorDialog" };
}
catch (__react_docgen_typescript_loader_error) { }
```

I think that problem that causes this is that the order of keys in __docgenInfo is not deterministic. And it leads to compilation invalidation.

Related code lines: https://github.com/storybookjs/react-docgen-typescript-plugin/blob/next/src/generateDocgenCodeBlock.ts#L312-L315

**Comment by 7rulnik** [comment] 2022-02-02 21:57
Well, yeah, seems that we need to stabilize the order of keys. Just made 2 build in row and got this diff
![image](https://user-images.githubusercontent.com/5969049/152244103-b8eee592-f751-453e-8ac6-6504c7cad9e2.png)

**Comment by shilman** [comment] 2023-06-08 02:55
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

**Closed by shilman** 2023-06-08 02:55 UTC
Labels: question / support, builder-webpack5
