### ISSUE TITLE
Crashes on Doc pane with JSX

### ISSUE THREAD

**Issue by Sebastien-Ahkrin** [storybookjs/storybook#18148] opened 2022-05-05 13:22 UTC
**Describe the bug**
The application crashes if you go on the "doc" panel with a story who contains JSX / TSX and handle function in props

**To Reproduce**
As you can see if this [repository](https://github.com/Sebastien-Ahkrin/storybook-crashes)  i created 2 story. one called "WithCrashes" who Crash if you go on the Doc panel.  And another one with the "WithoutCrashes" name who will not crash if  you go on the "Doc" pane.

To reproduce this bug is pretty simple, because you just need a component who need an array with jsx inside like
```tsx
interface {
  label: string;
  value: ReactNode;
}
```

After that add a function to handle a click with the storybook system
```jsx
export function WithCrashes(props) {
  return (
    <Component
      handleClick={props.handleClick}
      options={[{ label: "a", value: <Icon /> }]}
    />
  );
}
```

**System**
```
Environment Info:

  System:
    OS: macOS 12.3
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.13.2 - ~/.volta/tools/image/node/16.13.2/bin/node
    npm: 8.1.2 - ~/.volta/tools/image/node/16.13.2/bin/npm
  Browsers:
    Chrome: 100.0.4896.127
    Safari: 15.4
  npmPackages:
    @storybook/addon-actions: ^6.4.22 => 6.4.22 
    @storybook/addon-essentials: ^6.4.22 => 6.4.22 
    @storybook/addon-interactions: ^6.4.22 => 6.4.22 
    @storybook/addon-links: ^6.4.22 => 6.4.22 
    @storybook/builder-webpack5: ^6.4.22 => 6.4.22 
    @storybook/manager-webpack5: ^6.4.22 => 6.4.22 
    @storybook/node-logger: ^6.4.22 => 6.4.22 
    @storybook/preset-create-react-app: ^4.1.0 => 4.1.0 
    @storybook/react: ^6.4.22 => 6.4.22 
    @storybook/testing-library: ^0.0.11 => 0.0.11 
```

**Comment by taismassaro** [comment] 2022-07-08 15:23
We were investigating the same issue with the Docs tab crashing for stories that had `<img>` tags passed as props but we couldn't figure out what was happening (we're on 6.5.9).  It was solved by assigning it to a variable before passing it to the component, so thanks @Sebastien-Ahkrin for sharing your workaround, it unblocked us.

**Comment by Benur21** [comment] 2023-03-31 11:19
Doing this workaround is cumbersome and doesn't work when it's done inside a lib, please fix.

**Comment by jaydenseric** [comment] 2023-09-13 06:09
Potentially related:

- https://github.com/storybookjs/storybook/issues/17877
- https://github.com/storybookjs/storybook/issues/19575
- https://github.com/storybookjs/storybook/issues/23408

Explanation:

https://github.com/storybookjs/storybook/issues/19575#issuecomment-1668917993

Workaround:

https://github.com/storybookjs/storybook/issues/19575#issuecomment-1290903798

**Comment by tmeasday** [comment] 2023-10-27 01:35
👋 @jaydenseric !

This seems to me to be a dupe of #19575. You have a "props that contain rendered elements":

```tsx
      options={[{ label: "a", value: <Icon /> }]}
```

The simplest workaround is [the one ](https://github.com/storybookjs/storybook/issues/19575#issuecomment-1290903798). Let's try and revive fixing that issue.

**Closed by tmeasday** 2023-10-27 01:35 UTC
Labels: bug, has workaround, addon: docs
