### ISSUE TITLE
Controls not working 

### ISSUE THREAD

**Issue by Alfrex92** [storybookjs/storybook#12153] opened 2020-08-20 04:53 UTC
**Describe the bug**
I followed the tutorial that is being described in this [article](https://medium.com/storybookjs/storybook-controls-ce82af93e430). Controls tab is being displayed but there is a message saying that `This story is not configured to handle controls. Learn how to add controls »` and controls can't be used.

**To Reproduce**

1. Create a story and paste the following code (same code provided in the tutorial)
```
import React from 'react'
import { Button } from '@storybook/react/demo';
export default { title: 'Button/Controls', component: Button };
export const Basic = (args: any) => <Button {...args} />;
Basic.args = { children: 'hello' };
```

**Expected behavior**
Able to edit controls

**Screenshots**
![screenshot 2020-08-20 at 13 47 54](https://user-images.githubusercontent.com/22891582/90718259-6d2c4b00-e2ec-11ea-9721-3381486a0f0d.JPG)

**Additional context**
```
"@storybook/addon-actions": "^6.0.13",
    "@storybook/addon-controls": "^6.0.13",
    "@storybook/addon-knobs": "^6.0.13",
    "@storybook/addon-links": "^6.0.13",
    "@storybook/addons": "^6.0.13",
    "@storybook/preset-create-react-app": "^3.1.4",
    "@storybook/react": "^6.0.13",
```

**Comment by yannbf** [comment] 2020-08-20 08:21
Hey @Alfrex92! Indeed this doesn't look like the expected behaviour, thanks for opening this issue!
It seems like there was a regression in the automatic detection for react components.

For now, you could [annotate your properties manually](https://storybook.js.org/docs/react/essentials/controls#annotation) like this:
```tsx
import React from 'react'
import { Meta, Story } from '@storybook/react'
import { Button } from '@storybook/react/demo'

export default {
  title: 'Button/Controls',
  component: Button,
  argTypes: {
    children: {
      control: 'text',
    },
  },
} as Meta

export const Basic: Story<{ children: React.ReactNode }> = args => (
  <Button {...args} />
)
Basic.args = { children: 'hello' }
```

As soon as the issue is fixed then you could just remove argTypes entirely (if you want default automatic detection rather than specific overrides).

p.s. I see that you're using typescript, so I added an example of how to use the new Storybook types as well :)

**Comment by Alfrex92** [comment] 2020-08-21 02:46
Thanks for your reply and also for adding an example using Typescript. 

Unfortunately, the solution didn't work 😢. I'm not seeing the message anymore but I can't edit controls.

![screenshot 2020-08-20 at 13 47 54](https://user-images.githubusercontent.com/22891582/90846810-feaac400-e3a3-11ea-9eb0-cc57ffbfa4f8.JPG)

**Comment by astorije** [comment] 2020-08-21 04:20
Hey @yannbf, thanks for providing a snippet to play with!
I think I am encountering the same issue (with all 6.0.x versions of Storybook. Here is the code of a story written from your comment above:

```tsx
import { Meta, Story } from '@storybook/react';
import React from 'react';

import { SearchInput } from '../../src/SearchInput';

export default {
  title: 'SearchInput',
  component: SearchInput,
  argTypes: { value: { control: 'text' } },
} as Meta;

export const searchInputDemo: Story<{ value: string }> = (args) => (
  <SearchInput {...args} />
);

searchInputDemo.args = {
  value: 'Hello!',
};
```

I do not get that warning, but the `value` argument gets no control:

<img width="355" alt="Screen Shot 2020-08-21 at 12 05 10 AM" src="https://user-images.githubusercontent.com/113730/90851226-076aae00-e342-11ea-97ad-f64e0ebf16c8.png">

However, we have multiple `tsconfig.json` files and I am wondering if that might be why Storybook is unable to generate the controls. Here is a very simplified tree structure of our (private, unfortunately) repo:

```
├─ src
|  ├─ ...
|  ├─ SearchInput.tsx
|  └─ ...
├─ storybook
|  ├─ stories
|  |  ├─ ...
|  |  ├─ SearchInput.story.tsx
|  |  └─ ...
|  └─ tsconfig.json
└─ tsconfig.json
```

`storybook/tsconfig.json` contains:

``` json
{
  "compilerOptions": {
    "rootDir": "../",
    "outDir": "../storybook_dist"
  },
  "extends": "../tsconfig.json"
}
```

That's because we do not include stories in the JS bundle of the library itself.

Does this seem unusual to you, and do you think the extra `tsconfig.json` could explain the lack of controls?

**Comment by shilman** [comment] 2020-08-21 06:15
@astorije do you have a repro?

**Comment by lsbet** [comment] 2020-08-21 08:49
After the latest updates in the SB 6 the Controls have disappeared from the ArgsTable completely for me 🤔

**Comment by lsbet** [comment] 2020-08-24 05:21
Reverting back to 6.0.0 for playbook-react, addon-controls and addon-docs fixed the issue for me!

``` "@storybook/addon-controls": "^6.0.0",
    "@storybook/addon-docs": "^6.0.0",
    "@storybook/addon-info": "^5.3.19",
    "@storybook/addon-links": "^6.0.10",
    "@storybook/addons": "^6.0.10",
    "@storybook/react": "^6.0.0",```

This currently works.

**Comment by astorije** [comment] 2020-08-24 22:09
> @astorije do you have a repro?

Thanks for replying! I was playing with this just now, and somehow got it to work by replacing:

```ts
  argTypes: {
    value: { control: 'text' },
  },
```

with:

```ts
  argTypes: {
    value: { control: { type: 'text' } },
  },
```

Even though the [doc doesn't say so](https://storybook.js.org/docs/react/writing-stories/args#component-args).
🤯

**Comment by jonniebigodes** [comment] 2020-08-24 22:20
@astorije i've been working on the documentation. If you can supply a repo i'm more than glad to take a look at it. And if need be adjust the code snippet. 

Feel free to provide feedback

**Comment by shilman** [comment] 2020-08-24 23:52
Looks like a bug in Storybook not in the documentation. Looking at it.

**Comment by shilman** [comment] 2020-08-25 16:47
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.18 containing PR #12230 that references this issue. Upgrade today to try it out!

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2020-08-25 16:47 UTC
Labels: addon: controls, question / support

**Comment by astorije** [comment] 2020-08-25 22:03
@shilman, thanks a lot! It does seem to work much better, this is awesome!!

Just one clarification though to make sure I'm not deeply misguided as to how Arguments/Controls are supposed to work: are the controls supposed to be inferable from the available TS type information?
For example, adjusting my snippet above:

```tsx
import { Meta, Story } from '@storybook/react';
import React from 'react';

import { SearchInput, SearchInputProps } from '../../src/SearchInput';

// Assuming:
// interface SearchInputProps {
//   disabled?: boolean;
//   value?: string;
// }

export default {
  title: 'SearchInput',
  component: SearchInput,
} as Meta;

export const searchInputDemo: Story<SearchInputProps> = (args) => (
  <SearchInput {...args} />
);
```

Would Storybook be able to infer that `disabled` and `value` are to be available as controls, without having to specify:

```tsx
searchInputDemo.args = {
  disabled: false,
  value: '',
};
```

?

Reading [the doc on `addon-controls`](https://storybook.js.org/docs/react/essentials/controls), it seems like args are opt-in, but other places in the doc lead me to believe they should be auto-inferred (FYI we are not using the docs addon nor do we have a direct dependency on `react-docgen-typescript`). Thanks in advance and apologies for hijacking the thread, I wasn't sure if this was relevant as a follow-up here!
And thanks again for all of this!

**Comment by shilman** [comment] 2020-08-26 02:18
@astorije For historical reasons, the docs addon contains the code that does the auto-inference. So in 6.0 you'll need to add that to get auto-generated controls. You can disable the docs tab if you don't want it to be part of your UI.

You can also specify `argTypes` by hand: https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#my-controls-arent-being-auto-generated-what-should-i-do

It's not required to specify `.args`--you typically use those to specify the initial value of the args in the stories, since each story will have different settings.

**Comment by astorije** [comment] 2020-08-26 12:43
Thank you @shilman, excellent!

**Comment by mohit242** [comment] 2020-10-01 07:08
I am currently working with Gatsby + Storybook + Typescript and storybook is not auto-detecting controls for any of the components. eg-
```typescript
import React from "react"
import { Story, Meta } from "@storybook/react"
// default import
import  StyledButton, {StyledButtonProps } from "./StyledButton.styles"

export default {
  title: "Components/StyledButton",
  component: StyledButton,
} as Meta

const Template: Story<StyledButtonProps> = args => <StyledButton {...args} />

// controls are not detected
export const Default = Template.bind({})
```
But, everything starts working when I make the component into a named export, instead of a default export.
```typescript
import React from "react"
import { Story, Meta } from "@storybook/react"
// named import
import {StyledButton, StyledButtonProps } from "./StyledButton.styles"

export default {
  title: "Components/StyledButton",
  component: StyledButton,
} as Meta

const Template: Story<StyledButtonProps> = args => <StyledButton {...args} />

// controls are auto-detected
export const Default = Template.bind({})
```

**Comment by GuidovdRiet** [comment] 2020-10-30 10:09
For me the problem was that I exported the interface in the `Button` components. Exported interfaces are not automatically added to the controls/docs.

Solution: don't export interface or import interface and add manually.

**Comment by GuidovdRiet** [comment] 2020-11-05 15:02
For me the problem is solved when I give my component a named export:

As the docs of `react-docgen-typescript` mentions:
`Warning: only named exports are supported. If your project uses default exports, you still need to include named exports for react-docgen-typescript.`

``` 
export interface IconButtonProps {
  onClick?: () => void;
  type?: 'button' | 'submit' | 'reset';
  dataTestId?: string;
  disabled?: boolean;
  size?: 'small' | 'normal' | 'large' | 'compact';
  variant?: 'default' | 'borderless' | 'primary';
  border?: 'square' | 'rounded';
  children: {
    icon?: SVGElement;
  };
}

export const IconButtonComp: FC<IconButtonProps> = ({
  children,
  type = 'button',
  onClick,
  dataTestId = 'button',
  variant = 'default',
  border = 'square',
  disabled = false,
  size = 'normal',
}) => (
  <Button
    onClick={onClick}
    variant={variant}
    border={border}
    size={size}
    type={type}
    disabled={disabled}
    data-testid={dataTestId}
  >
    {children}
  </Button>
);
```

**Comment by phoniks** [comment] 2021-02-03 18:08
> @astorije For historical reasons, the docs addon contains the code that does the auto-inference. So in 6.0 you'll need to add that to get auto-generated controls. 

This is info that would be great to have surfaced sooner and more visibly in the documentation imho.

**Comment by shilman** [comment] 2021-02-17 03:11
@phoniks this is surfaced by the CLI, which is about as visible as we can make it. where else should we list it?

```
WARN Expected '@storybook/addon-docs' to be listed before '@storybook/addon-controls' (or '@storybook/addon-essentials'). Check your main.js?
```

**Comment by Rush** [comment] 2021-03-16 05:41
> Even though the [doc doesn't say so](https://storybook.js.org/docs/react/writing-stories/args#component-args).

Wow. I was banging my head against the wall, went through all the docs but stumbled upon your post. I've changed my code to:
```ts
    text: {
      control: { type: 'text' },
    },
```
and voila .. it works.

Does anybody have any idea how to annotate Angular components for Storybook to pick up the fields on its own?

**Comment by shilman** [comment] 2021-03-16 06:33
@Rush what version are you using?

**Comment by Rush** [comment] 2021-03-16 06:48
6.2.0-rc.0 with Angular

**Comment by donpernino** [comment] 2021-03-23 16:41
> > Even though the [doc doesn't say so](https://storybook.js.org/docs/react/writing-stories/args#component-args).
> 
> Wow. I was banging my head against the wall, went through all the docs but stumbled upon your post. I've changed my code to:
> 
> ```ts
>     text: {
>       control: { type: 'text' },
>     },
> ```
> 
> and voila .. it works.
> 
> Does anybody have any idea how to annotate Angular components for Storybook to pick up the fields on its own?

Thanks a lot, banged my head as well but this fixed the controls customization for me!

**Comment by jferragut** [comment] 2021-04-05 04:07
FYI, I had this problem as well with NextJS, Typescript, Storybook.

If I used the following syntax, it resulted in Storybook not detecting my controls and giving the warning:
```typescript
const Template: Story<ButtonProps> = (args) => <Button {...args} />;

export const Primary = Template.bind({});
Primary.args = {
  label: 'Primary Button',
};
```
I used template syntax because it was more convenient for multiple variants, but the following fixed the warning:

```typescript
export const Primary: Story<ButtonProps> = (args) => <Button {...args} />;
Primary.args = {
  label: 'Primary Button',
};
```

It seems like the template bind is messing with the detection, but I haven't dug in to see what is going on. Hope this helps someone.

**Comment by shilman** [comment] 2021-04-05 04:35
@jferragut I believe the typescript setting `strictBindCallApply` must be `true`. @jonniebigodes can we get this in the documentation as a troubleshooting step?

Reference: https://discord.com/channels/486522875931656193/490070912448724992/774340693941551165

**Comment by CH9587** [comment] 2021-04-05 13:45
I got hints from @GuidovdRiet and @mohit242, but for me, it was a combination of both using a named export for my component, as well as NOT using `React.FC` when declaring the component, and instead importing `FC` from react explicitly and doing `FC<MyType>` during the component declaration.

**Comment by FreeSoulsDotBat** [comment] 2022-01-19 13:48
I'm having trouble generating controls automatically too.

My main.js:
``` javascript
module.exports = {
	stories: ['../stories/**/*.stories.@(ts|tsx|js|jsx)'],
	addons: [
		'@storybook/addon-docs',
		'@storybook/addon-controls',
		'@storybook/addon-links'
	],
	// https://storybook.js.org/docs/react/configure/typescript#mainjs-configuration
	typescript: {
		check: true // type-check stories during Storybook build
	},
	features: {
		postcss: false
	}
}
```

My component:
``` tsx
import React, {
	ButtonHTMLAttributes,
	FC,
	ReactElement,
	ReactNode,
	useState
} from 'react'
import classNames from 'classnames'
import './Button.css'

export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
	icon?: ReactElement
	iconOnly?: boolean
	children: ReactNode
	active?: boolean
	submitFunction: () => void
}

export const Button: FC<ButtonProps> = ({
	icon,
	children,
	iconOnly = false,
	active = false,
	submitFunction,
	...rest
}) => {
	const [buttonActive, setButtonActive] = useState(active)

	const classesButton = classNames(
		'button',
		{
			'button--active': buttonActive
		},
		{ 'button-size--normal': !iconOnly },
		{ 'button-size--icononly': iconOnly }
	)

	const classesChildren = classNames('button__text', {
		'text--active': buttonActive
	})

	const classesIcon = classNames('button__icon', {
		'icon--active': buttonActive
	})

	const handleClick = () => {
		submitFunction()
		setButtonActive(!buttonActive)
	}

	return (
		<button
			className={classesButton}
			onClick={() => handleClick()}
			{...rest}
		>
			{!iconOnly ? (
				<p data-testid="text" className={classesChildren}>
					{children}
				</p>
			) : null}
			{icon ? (
				<i data-testid="icon" className={classesIcon}>
					{icon}
				</i>
			) : null}
		</button>
	)
}
```
My storie:
```tsx
import React, { ReactElement } from 'react'
import { Button } from '../src'
import { ComponentMeta, ComponentStory, Meta, Story } from '@storybook/react'

import { RiUserFollowFill } from 'react-icons/ri'
import { ButtonProps } from '../src/components/Button/Button'

export default {
	title: 'Components/Button',
	argTypes: {
		icon: {
			description:
				'Prop that receives a icon to render in the Button. (svg or react-icons)'
		}
	},
	parameters: {
		component: Button,
		componentSubtitle:
			'The Button component is for performing actions in most situations.'
	},
	type: 'code'
} as Meta

const Template: Story<ButtonProps> = (args) => {
	const submit = () => {
		console.log('Hello')
	}

	return <Button submitFunction={submit} {...args} />
}

export const Default = Template.bind({})
Default.args = { children: 'Cadastrar' }

export const Icon = Template.bind({})
Icon.args = {
	children: 'Cadastrar',
	icon: <RiUserFollowFill />,
	iconOnly: false
}

export const IconOnly = Template.bind({})
IconOnly.args = {
	children: 'Cadastrar',
	icon: <RiUserFollowFill />,
	iconOnly: true
}
```

But seems that isn't creating the controls and docs(types of props for example) automatically:
![image](https://user-images.githubusercontent.com/65923588/150142672-2aa60b8c-3a1a-4cd3-a768-cb7eb9e87aa1.png)
![image](https://user-images.githubusercontent.com/65923588/150142807-fcf92317-81dd-43af-8d14-9f9955c3d98d.png)


What I am doing wrong? (I am using the last version of storybook and addons)

**Comment by Tordek** [comment] 2022-02-03 23:46
@FreeSoulsDotBat I had the same issue; it appears `react-docgen-typescript` doesn't work with `extends`.

**Comment by Tordek** [comment] 2022-02-04 01:26
@FreeSoulsDotBat you seem to be using `export default { ..., parameters: { component: Foo}}` and it's just `export default { component: Foo}`.

I'm having the same issue, and it seems to be that `react-docgen-typescript` does not look at `extends`.

If I have a component like

```
import { Button, ButtonProps } from 'reactstrap';
type MyProps extends ButtonProps { size: string; };
const MyButton = (...: MyProps) {...}
```

Storybook detects my `size` prop but none of the others defined in `ButtonProps`.

**Comment by yannbf** [comment] 2022-02-06 09:59
> @FreeSoulsDotBat you seem to be using `export default { ..., parameters: { component: Foo}}` and it's just `export default { component: Foo}`.
> 
> I'm having the same issue, and it seems to be that `react-docgen-typescript` does not look at `extends`.
> 
> If I have a component like
> 
> ```
> import { Button, ButtonProps } from 'reactstrap';
> type MyProps extends ButtonProps { size: string; };
> const MyButton = (...: MyProps) {...}
> ```
> 
> Storybook detects my `size` prop but none of the others defined in `ButtonProps`.

Hey @Tordek I believe your Typescript example is not valid. The `extends` operator is used only in interfaces for what you're trying to achieve in `MyProps`.

type + `extends` are used for distributive conditional types, like so:
```ts
type MyProps = ButtonProps extends ResizableElement
  ? { dimensions: { width: number; height: number } }
  : { size: string }
```

You should do either:
```ts
import { Button, ButtonProps } from 'reactstrap';
type MyProps = ButtonProps & { size: string; };
const MyButton = (...: MyProps) {...}
```

or
```ts
import { Button, ButtonProps } from 'reactstrap';
interface MyProps extends ButtonProps { size: string; };
const MyButton = (...: MyProps) {...}
```

**Comment by Tordek** [comment] 2022-02-06 23:53
Sorry, the syntax is because I tried both of your latter options and made a typo when reporting here.

Both of your examples have the same issue: The props specified directly (i.e., size) appear in the docs, but those in the `extends`/`&` do not.

**Comment by yannbf** [comment] 2022-02-18 22:19
> Hey storybook team - I'm having an issue only with boolean controls not working. They display fine, but cannot be toggled. All other controls working as expected. Not sure if this is a known issue. They were working fine earlier in the week but are no longer working

Could you please create an issue and provide a reproduction for the error? Thanks!

**Comment by Conviley** [comment] 2022-10-14 13:16
I just updated to 6.5.12 and replicating OP's post controls are not showing for me either. I currently have the issue that some controls work on some stories and others are said to not be configured. 

I duplicated one of my stories that did have working controls into a new story file and that new story file with the exact same content does not work.

**Comment by metawort** [comment] 2023-01-17 09:35
On version 6.5.15 I still (or again) have this issue.

Like @Conviley I copied an older component for which the controls auto-detection worked back when is has been created (and for which the controls are still there). For the copied component however there are zero auto-detected controls.

I'm especially helpless when it comes to controls for props that expect an enum or union type. For the older components, Storybook automatically created sets of radio buttons as control for those. How can I do that manually?

**Comment by vmohir** [comment] 2023-08-19 13:37
I had the same issue with @storybook-angular. Surprisingly the issue was related to `"compodoc": true` in `angular.json`.

The fix:

angular.json - set compodoc to false
```
"storybook-sdk": {
          "builder": "@storybook/angular:start-storybook",
          "options": {
            "configDir": ".storybook",
            "browserTarget": "myapp:build",
            "compodoc": false,
            "compodocArgs": ["-e", "json", "-d", "."],
            "port": 6006
          }
        },
```

then run `compodoc -p ./tsconfig.json -e json -d .` and `ng run huma-sdk:storybook`
