### ISSUE TITLE
[Bug]: ReferenceError: exports is not defined after update to 7.6

### ISSUE THREAD

**Issue by ramirezcgn** [storybookjs/storybook#25383] opened 2023-12-29 13:20 UTC
### Describe the bug

Hi, after updating storybook version from 7.4 to 7.6 I'm getting this error:

`ReferenceError: exports is not defined
    at ./src/compo1/compo1.stories.jsx (http://localhost:6006/compo1-compo1-stories.iframe.bundle.js:46:1)
    at __webpack_require__ (http://localhost:6006/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:6006/runtime~main.iframe.bundle.js:299:21)
    at http://localhost:6006/main.iframe.bundle.js:171:10
    at async StoryStore.importFn (http://localhost:6006/main.iframe.bundle.js:104:27)
    at async StoryStore.loadStory (http://localhost:6006/sb-preview/runtime.js:47:9920)
    at async http://localhost:6006/sb-preview/runtime.js:81:9005
    at async StoryRender.runPhase (http://localhost:6006/sb-preview/runtime.js:81:8766)
    at async StoryRender.prepare (http://localhost:6006/sb-preview/runtime.js:81:8924)
    at async PreviewWeb.renderSelection (http://localhost:6006/sb-preview/runtime.js:101:3102)`

I noticed that if I remove the babel plugin "@babel/plugin-transform-modules-commonjs" it works, but I need that plugin for the rest of the project, I created a repo using the sandbox to show the problem.

### To Reproduce

https://github.com/ramirezcgn/sbsandbox

### System

```bash
Storybook Environment Info:

  System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 PRO 7730U with Radeon Graphics
  Binaries:
    Node: 16.20.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD <----- active
  Browsers:
    Edge: Chromium (120.0.2210.61)
  npmPackages:
    @storybook/addon-actions: ^7.6.6 => 7.6.6
    @storybook/addon-docs: ^7.6.6 => 7.6.6
    @storybook/addon-essentials: ^7.6.6 => 7.6.6
    @storybook/addon-interactions: ^7.6.6 => 7.6.6
    @storybook/addon-links: ^7.6.6 => 7.6.6
    @storybook/addon-onboarding: ^1.0.10 => 1.0.10
    @storybook/blocks: ^7.6.6 => 7.6.6
    @storybook/react: ^7.6.6 => 7.6.6
    @storybook/react-webpack5: ^7.6.6 => 7.6.6
    @storybook/test: ^7.6.6 => 7.6.6
    @storybook/testing-library: ^0.2.2 => 0.2.2
    storybook: ^7.6.6 => 7.6.6
```

**Comment by shilman** [comment] 2023-12-30 09:02
@ndelangen do you know if any updates in 7.5 or 7.6 that could cause this change of behavior?

**Comment by gontovnik** [comment] 2024-01-03 08:13
Facing the same issue

**Comment by ndelangen** [comment] 2024-01-03 09:04
@shilman nothing that jump at me, no.
 
 @gontovnik you could customize the babel config storybook uses within your `.storybook/main.ts` file.
https://storybook.js.org/docs/api/main-config-babel#babelconfig

**Comment by ramirezcgn** [comment] 2024-01-03 14:03
> @shilman nothing that jump at me, no.
> 
> @gontovnik you could customize the babel config storybook uses within your `.storybook/main.ts` file. https://storybook.js.org/docs/api/main-config-babel#babelconfig

I just tried it by adding only the "@babel/plugin-transform-modules-commonjs" plugin and it still gives the same error

**Comment by mlazari** [comment] 2024-01-04 08:27
I see the same issue and I think the first version in which this happens is `"@storybook/react-webpack5": "7.6.0-alpha.5"`, because I see it with that version but I don't see it with "@storybook/react-webpack5": "7.6.0-alpha.4".

**Comment by mlazari** [comment] 2024-01-04 10:18
- I cloned the repro in the description of this issue - https://github.com/ramirezcgn/sbsandbox
- Locked `@storybook/react-webpack5` to latest working version: `"@storybook/react-webpack5": "7.6.0-alpha.4",`, removed `.gitignore` (so I can track the changes in `node_modules`), ran `npm install` and committed this working version locally
- Locked `@storybook/react-webpack5` to first version having this issue: `"@storybook/react-webpack5": "7.6.0-alpha.5",` ran `npm install`
- If I discard the changes to `node_modules/@storybook/builder-webpack5/dist/presets/preview-preset.js` and add back the removed `node_modules/babel-plugin-named-exports-order` folder and its content, then the issue goes away

The issue seems to be caused by the changes in this commit as far as I can tell: https://github.com/storybookjs/storybook/commit/5d1ba5e95fcc9489b0411cf6f36dd4131b2c4cac


Another way I confirmed the issue was introduced in `"@storybook/builder-webpack5": "7.6.0-alpha.5"` (dependency of `"@storybook/react-webpack5": "7.6.0-alpha.5"`) is that I added an override in package.json to keep `@storybook/builder-webpack5` on version `7.6.0-alpha.4` and that was also fixing the issue:
```
  "devDependencies": {
    // ...
    "@storybook/react-webpack5": "7.6.0-alpha.5",
    // ...
  },
  "overrides": {
    "@storybook/builder-webpack5": "7.6.0-alpha.4"
  }
```

**Comment by mlazari** [comment] 2024-01-04 12:50
Another thing I see in the file in the error stack trace (http://localhost:6006/compo1-compo1-stories.iframe.bundle.js):

This code snipped `"@storybook/react-webpack5": "7.6.0-alpha.4",`:
```
Object.defineProperty(exports, "__esModule", ({
    value: true
}));
exports["default"] = exports.Default = void 0;
```

changes to this after the update to `"@storybook/react-webpack5": "7.6.0-alpha.5",`:
```
Object.defineProperty(__webpack_exports__, "__esModule", ({
    value: true
}));
exports.default = exports.Default = void 0;
```

**Comment by sindrisig** [comment] 2024-01-08 11:37
Stumbled onto this issue while trying to figure out an issue i was having updating from 7.5 to 7.6 and was seeing a similar issue where stories would not load.

Story would be rendering `Component A`. 
Component A would import `IconOne` from `Package B`.
Story would fail with `ReferenceError: IconTwo is not defined` 

Even though the particular export was not being referenced in the story or the component that was rendered by that story. Commenting out the import from this package would solve the issue.

Tested downgrading `@storybook/react-webpack5` to `@storybook/react-webpack5": "7.6.0-alpha.4` and that solves the issue for me.

**Comment by shilman** [comment] 2024-01-08 12:01
@dannyhw @ndelangen this looks the issue we're seeing in the RNW addon https://github.com/storybookjs/addon-react-native-web/issues/76

**Comment by dannyhw** [comment] 2024-01-08 13:39
yes I can confirm this is easy to reproduce in addon-react-native-web by just updating storybook to 7.6. All working fine on 7.5.

**Comment by dannyhw** [comment] 2024-01-08 14:12
interestingly in the deployed version the error is slightly different

"Cannot access '__namedExportsOrder' before initialization"

https://618d44792e48fd003a482f88-roaoznyxld.chromatic.com/?path=/story/libraries-paper-card--basic

**Comment by valentinpalkovic** [comment] 2024-01-08 14:27
As a workaround

Could you configure your babel plugin so that the `@babel/plugin-transform-modules-commonjs` plugin isn't applied to stories files? Something like this:

```js
// .babelrc.js
module.exports = {
  "presets": [...],
  // Don't put "@babel/plugin-transform-modules-commonjs" here
  "plugins": [...],
  "overrides": [
    {
      "exclude": /\.stories\.([tj])sx?$|(stories|story)\.mdx$/,
      "plugins": ["@babel/plugin-transform-modules-commonjs"]
    }
  ]
}
```

**Comment by dannyhw** [comment] 2024-01-08 14:47
I don't really understand because @babel/plugin-transform-modules-commonjs is a dependency of builder-webpack5 via webpack-virtual-modules so isn't it required?

**Comment by dannyhw** [comment] 2024-01-08 14:52
@valentinpalkovic just tried it and didn't see any change, though my config doesn't have `@babel/plugin-transform-modules-commonjs` directly anyway, maybe via a preset.

**Comment by valentinpalkovic** [comment] 2024-01-08 14:59
@mlazari

Do you also use `@babel/plugin-transform-modules-commonjs`?

**Comment by mlazari** [comment] 2024-01-08 15:25
@valentinpalkovic I don't use it directly, my `babel.config.js` looks like this:
```
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: ['react-native-reanimated/plugin'],
  };
};
```

But I see it in `package-lock.json` as a dependency of `@babel/preset-env` which is a dependency of `babel-preset-expo`.

**Comment by dannyhw** [comment] 2024-01-08 15:41
fyi in my case and in the example from the issue poster there is a babel loader being added in webpackFinal

**Comment by mlazari** [comment] 2024-01-08 17:15
If I comment this `magicString.append(...)` code the error goes away: https://github.com/storybookjs/storybook/blob/v7.6.7/code/builders/builder-webpack5/src/loaders/export-order-loader.ts#L23

If I log `magicString` before and after this line it looks like it is adding `;export const __namedExportsOrder = [];` to some commonJS code (with `require`, without `import` / `export`). Could this cause this error?

This is `magicString.toString()` after that append:
```
var _interopRequireDefault=require("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(exports,"__esModule",{value:true});exports.Typography=Typography;exports.default=void 0;var _slicedToArray2=_interopRequireDefault(require("@babel/runtime/helpers/slicedToArray"));var _View=_interopRequireDefault(require("react-native-web/dist/exports/View"));var _Text=require("../controls/Text.styles");var _Text2=require("../controls/Text");var _theme=require("../theme");var Spacing=_interopRequireWildcard(require("./spacing"));var _jsxRuntime=require("react/jsx-runtime");var _Typography$parameter,_Typography$parameter2,_Typography$parameter3;function _getRequireWildcardCache(e){if("function"!=typeof WeakMap)return null;var r=new WeakMap(),t=new WeakMap();return(_getRequireWildcardCache=function _getRequireWildcardCache(e){return e?t:r;})(e);}function _interopRequireWildcard(e,r){if(!r&&e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var t=_getRequireWildcardCache(r);if(t&&t.has(e))return t.get(e);var n={__proto__:null},a=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var u in e)if("default"!==u&&Object.prototype.hasOwnProperty.call(e,u)){var i=a?Object.getOwnPropertyDescriptor(e,u):null;i&&(i.get||i.set)?Object.defineProperty(n,u,i):n[u]=e[u];}return n.default=e,t&&t.set(e,n),n;}var _default=exports.default={title:'Foundation/Typography',parameters:{viewport:{defaultViewport:'responsive'},importFrom:'@waybetter/react/theme',options:{showPanel:false},controls:{disable:true},actions:{disable:true}}};function Lorem(props){return(0,_jsxRuntime.jsx)(_Text2.Text,Object.assign({},props,{children:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}));}function Variant(_ref){var variant=_ref.variant;var properties=Object.assign({},_theme.text.base,_theme.text[variant]);var friendly=function friendly(text){return text.replace(/^./,function(x){return x.toUpperCase();}).replace(/([a-z])([A-Z])/g,'$1 $2').replace(/([0-9]+)/gi,' $1 ').trim();};var findColorName=function findColorName(value){var _Object$entries$find;return(_Object$entries$find=Object.entries(_theme.palette).find(function(x){return x[1]===value;}))==null?void 0:_Object$entries$find[0];};return(0,_jsxRuntime.jsxs)(_View.default,{style:{marginBottom:Spacing.MEDIUM,flexDirection:'row'},children:[(0,_jsxRuntime.jsxs)(_View.default,{style:{width:220},children:[(0,_jsxRuntime.jsx)(_View.default,{style:{marginBottom:Spacing.XX_SMALL},children:(0,_jsxRuntime.jsx)(_Text2.Text,{variant:variant,children:friendly(variant)})}),Object.entries(properties).map(function(_ref2){var _ref3=(0,_slicedToArray2.default)(_ref2,2),name=_ref3[0],value=_ref3[1];return(0,_jsxRuntime.jsxs)(_View.default,{style:{flexDirection:'row'},children:[(0,_jsxRuntime.jsx)(_View.default,{style:{width:Spacing.XXX_LARGE},children:(0,_jsxRuntime.jsxs)(_Text2.Text.Caption,{children:[friendly(name),":"]})}),(0,_jsxRuntime.jsx)(_Text2.Text.Caption,{children:name==='color'?`${findColorName(String(value))} (${String(value)})`:String(value)})]},name);})]}),(0,_jsxRuntime.jsx)(_View.default,{style:{flex:1},children:(0,_jsxRuntime.jsx)(Lorem,{variant:variant,numberOfLines:4})})]});}function Typography(){return(0,_jsxRuntime.jsx)(_jsxRuntime.Fragment,{children:_Text.VariantNames.map(function(variant){return(0,_jsxRuntime.jsx)(Variant,{variant:variant},variant);})});}Typography.parameters=Object.assign({},Typography.parameters,{docs:Object.assign({},(_Typography$parameter=Typography.parameters)==null?void 0:_Typography$parameter.docs,{source:Object.assign({originalSource:"function Typography() {\n  return <>\n      {VariantNames.map(variant => <Variant variant={variant} key={variant} />)}\n    </>;\n}"},(_Typography$parameter2=Typography.parameters)==null?void 0:(_Typography$parameter3=_Typography$parameter2.docs)==null?void 0:_Typography$parameter3.source)})});;export const __namedExportsOrder = [];
```

**Comment by mlazari** [comment] 2024-01-08 17:19
If I comment this `magicString.append(...)` code the error goes away: https://github.com/storybookjs/storybook/blob/v7.6.7/code/builders/builder-webpack5/src/loaders/export-order-loader.ts#L23

If I log `magicString` before and after this line it looks like it is adding `;export const __namedExportsOrder = [];` to some commonJS code (with `require`, without `import` / `export`). Could this cause this error?

This is `magicString.toString()` after that append:
```
var _interopRequireDefault=require("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(exports,"__esModule",{value:true});exports.Typography=Typography;exports.default=void 0;var _slicedToArray2=_interopRequireDefault(require("@babel/runtime/helpers/slicedToArray"));var _View=_interopRequireDefault(require("react-native-web/dist/exports/View"));var _Text=require("../controls/Text.styles");var _Text2=require("../controls/Text");var _theme=require("../theme");var Spacing=_interopRequireWildcard(require("./spacing"));var _jsxRuntime=require("react/jsx-runtime");var _Typography$parameter,_Typography$parameter2,_Typography$parameter3;function _getRequireWildcardCache(e){if("function"!=typeof WeakMap)return null;var r=new WeakMap(),t=new WeakMap();return(_getRequireWildcardCache=function _getRequireWildcardCache(e){return e?t:r;})(e);}function _interopRequireWildcard(e,r){if(!r&&e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var t=_getRequireWildcardCache(r);if(t&&t.has(e))return t.get(e);var n={__proto__:null},a=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var u in e)if("default"!==u&&Object.prototype.hasOwnProperty.call(e,u)){var i=a?Object.getOwnPropertyDescriptor(e,u):null;i&&(i.get||i.set)?Object.defineProperty(n,u,i):n[u]=e[u];}return n.default=e,t&&t.set(e,n),n;}var _default=exports.default={title:'Foundation/Typography',parameters:{viewport:{defaultViewport:'responsive'},importFrom:'@myorg/react/theme',options:{showPanel:false},controls:{disable:true},actions:{disable:true}}};function Lorem(props){return(0,_jsxRuntime.jsx)(_Text2.Text,Object.assign({},props,{children:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}));}function Variant(_ref){var variant=_ref.variant;var properties=Object.assign({},_theme.text.base,_theme.text[variant]);var friendly=function friendly(text){return text.replace(/^./,function(x){return x.toUpperCase();}).replace(/([a-z])([A-Z])/g,'$1 $2').replace(/([0-9]+)/gi,' $1 ').trim();};var findColorName=function findColorName(value){var _Object$entries$find;return(_Object$entries$find=Object.entries(_theme.palette).find(function(x){return x[1]===value;}))==null?void 0:_Object$entries$find[0];};return(0,_jsxRuntime.jsxs)(_View.default,{style:{marginBottom:Spacing.MEDIUM,flexDirection:'row'},children:[(0,_jsxRuntime.jsxs)(_View.default,{style:{width:220},children:[(0,_jsxRuntime.jsx)(_View.default,{style:{marginBottom:Spacing.XX_SMALL},children:(0,_jsxRuntime.jsx)(_Text2.Text,{variant:variant,children:friendly(variant)})}),Object.entries(properties).map(function(_ref2){var _ref3=(0,_slicedToArray2.default)(_ref2,2),name=_ref3[0],value=_ref3[1];return(0,_jsxRuntime.jsxs)(_View.default,{style:{flexDirection:'row'},children:[(0,_jsxRuntime.jsx)(_View.default,{style:{width:Spacing.XXX_LARGE},children:(0,_jsxRuntime.jsxs)(_Text2.Text.Caption,{children:[friendly(name),":"]})}),(0,_jsxRuntime.jsx)(_Text2.Text.Caption,{children:name==='color'?`${findColorName(String(value))} (${String(value)})`:String(value)})]},name);})]}),(0,_jsxRuntime.jsx)(_View.default,{style:{flex:1},children:(0,_jsxRuntime.jsx)(Lorem,{variant:variant,numberOfLines:4})})]});}function Typography(){return(0,_jsxRuntime.jsx)(_jsxRuntime.Fragment,{children:_Text.VariantNames.map(function(variant){return(0,_jsxRuntime.jsx)(Variant,{variant:variant},variant);})});}Typography.parameters=Object.assign({},Typography.parameters,{docs:Object.assign({},(_Typography$parameter=Typography.parameters)==null?void 0:_Typography$parameter.docs,{source:Object.assign({originalSource:"function Typography() {\n  return <>\n      {VariantNames.map(variant => <Variant variant={variant} key={variant} />)}\n    </>;\n}"},(_Typography$parameter2=Typography.parameters)==null?void 0:(_Typography$parameter3=_Typography$parameter2.docs)==null?void 0:_Typography$parameter3.source)})});;export const __namedExportsOrder = [];
```

**Comment by mlazari** [comment] 2024-01-08 18:30
@valentinpalkovic I see the same thing for the project in this issue description:

With `@babel/plugin-transform-modules-commonjs`:
```
"use strict";
function _define_property(obj, key, value) {
    if (key in obj) {
        Object.defineProperty(obj, key, {
            value: value,
            enumerable: true,
            configurable: true,
            writable: true
        });
    } else {
        obj[key] = value;
    }
    return obj;
}
function _object_spread(target) {
    for(var i = 1; i < arguments.length; i++){
        var source = arguments[i] != null ? arguments[i] : {};
        var ownKeys = Object.keys(source);
        if (typeof Object.getOwnPropertySymbols === "function") {
            ownKeys = ownKeys.concat(Object.getOwnPropertySymbols(source).filter(function(sym) {
                return Object.getOwnPropertyDescriptor(source, sym).enumerable;
            }));
        }
        ownKeys.forEach(function(key) {
            _define_property(target, key, source[key]);
        });
    }
    return target;
}
Object.defineProperty(exports, "__esModule", {
    value: true
});
exports.default = exports.Default = void 0;
var _react = _interopRequireDefault(require("react"));
var _compo = require("./compo1");
var _jsxRuntime = require("react/jsx-runtime");
function _interopRequireDefault(obj) {
    return obj && obj.__esModule ? obj : {
        default: obj
    };
}
var _default = exports.default = {
    title: "Components/Compo1",
    component: _compo.Compo1,
    parameters: {
        layout: "container"
    }
};
var Template = function(args) {
    return /*#__PURE__*/ (0, _jsxRuntime.jsx)(_compo.Compo1, _object_spread({}, args));
};
var Default = exports.Default = Template.bind({});
;export const __namedExportsOrder = [];
```

Without `@babel/plugin-transform-modules-commonjs`:
```
function _define_property(obj, key, value) {
  if (key in obj) {
    Object.defineProperty(obj, key, {
      value: value,
      enumerable: true,
      configurable: true,
      writable: true
    });
  } else {
    obj[key] = value;
  }
  return obj;
}
function _object_spread(target) {
  for (var i = 1; i < arguments.length; i++) {
    var source = arguments[i] != null ? arguments[i] : {};
    var ownKeys = Object.keys(source);
    if (typeof Object.getOwnPropertySymbols === "function") {
      ownKeys = ownKeys.concat(Object.getOwnPropertySymbols(source).filter(function (sym) {
        return Object.getOwnPropertyDescriptor(source, sym).enumerable;
      }));
    }
    ownKeys.forEach(function (key) {
      _define_property(target, key, source[key]);
    });
  }
  return target;
}
import React from "react";
import { Compo1 } from "./compo1";
import { jsx as _jsx } from "react/jsx-runtime";
export default {
  title: "Components/Compo1",
  component: Compo1,
  parameters: {
    layout: "container"
  }
};
var Template = function (args) {
  return /*#__PURE__*/_jsx(Compo1, _object_spread({}, args));
};
export var Default = Template.bind({});
Default.parameters = {
  ...Default.parameters,
  docs: {
    ...Default.parameters?.docs,
    source: {
      originalSource: "args => <Compo1 {...args} />",
      ...Default.parameters?.docs?.source
    }
  }
};;export const __namedExportsOrder = ["Default"];
```

I am not familiar with the code / webpack loaders, but to me it looks like `export-order-loader` assumes it is a ES module, but when `@babel/plugin-transform-modules-commonjs` is used, it is a CommonJS module which makes it not work as intended?

**Comment by mlazari** [comment] 2024-01-09 09:58
@valentinpalkovic Could something like this work - https://github.com/mlazari/storybook/commit/fbb91b3bf16cd48f8503ed63b7c91d76723bd36f? I don't have have experience with contributing here and I didn't test that change, but I imagine it should add `module.exports.__namedExportsOrder = ...` instead of `export const __namedExportsOrder = ...` if it's not an ES module. If you think that change is correct, feel free to copy it and do any necessary adjustments to it.

**Comment by mlazari** [comment] 2024-01-10 08:39
In case someone is looking for a temporary fix, this is what we did in our project to workaround the issue:

**.storybook/main.js**
```
module.exports = {
  // ...
  webpackFinal: async (config) => {
    // ...

    // Remove export-order-loader since it doesn't work properly for CommonJS code
    // It currently appends ES code to CommonJS code resulting in a "exports is not defined" error
    // See https://github.com/storybookjs/storybook/issues/25383
    // This might result in the order of stories not corresponding to the order of exports,
    // although from my testing it doesn't seem to be the case and works fine without it
    // TODO: remove this fix once it is fixed in the library
    config.module.rules = config.module.rules.filter(
      (rule) =>
        !rule?.use?.some?.((u) =>
          String(u?.loader)?.includes?.('export-order-loader')
        )
    );

    // ...

    return config;
  },
  // ...
};
```

This removes the export-order-loader, which as I understand is required only for making the order of stories correspond to the order of exports, since webpack5 doesn't guarantee to preserve the original export order (as per the babel plugin docs this loader is replacing since version `7.6.0-alpha.4` - https://www.npmjs.com/package/babel-plugin-named-exports-order). Per my testing it seems to preserve the export order even without this loader, at least in our project, so I don't see any behaviour change when removing it.

**Comment by valentinpalkovic** [comment] 2024-01-10 10:27
@mlazari Thank you for the workaround.

I will try to provide a fix soon.

**Comment by narajaon** [comment] 2024-01-10 10:29
@mlazari just tested and it actually works, thanks !

**Comment by mlazari** [comment] 2024-01-10 12:04
Thank you @valentinpalkovic 
BTW I was able to test my changes in a fork of the repro provided in the description. Except for a small bug (I was using `findIndex` instead of `indexOf`, fixed version -> https://github.com/mlazari/storybook/commit/b1efd8a29af70837ec6622428b8cac2ebcca7690), it seems to work correctly as far as I can tell.

https://github.com/mlazari/sbsandbox/commit/c70c40d06d617abfe6f111dfb7000f53bd3911ea

Output source of the loader with and without `@babel/plugin-transform-modules-commonjs`: https://github.com/mlazari/sbsandbox/blob/main/loader-changes.md

**Comment by valentinpalkovic** [comment] 2024-01-10 12:36
@mlazari Awesome! Actually, yesterday evening, I was also searching for a CSJ alternative to the `es-module-lexer.` I am happy that you went forward and actually implemented it by using `cjs-module-lexer`! Would you mind creating a PR?

**Comment by valentinpalkovic** [comment] 2024-01-10 12:44
I will take care of these errors :)

**Comment by mlazari** [comment] 2024-01-10 12:56
@valentinpalkovic https://github.com/storybookjs/storybook/pull/25540

**Comment by valentinpalkovic** [comment] 2024-01-10 13:17
@mlazari Thank you for the deep dive and the provided PR! Much appreciated.

**Closed** 2024-01-16 12:28 UTC
Labels: bug, help wanted, configuration babel / webpack, has workaround, sev:S2, upgrade:7.6
