### ISSUE TITLE
[Bug]: Vite: Pre-transform error: Failed to load url /sb-preview/runtime.js. Does the file exist?

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#25287] opened 2023-12-20 15:09 UTC
### Describe the bug

When loading any URL in Storybook I get the following error in the terminal:

```
[vite] Pre-transform error: Failed to load url /sb-preview/runtime.js (resolved id: /sb-preview/runtime.js). Does the file exist?
```

### To Reproduce

For 8.0, in an empty directory type:
```
pnpx storybook@next init
```

Then select the Vite-React option.

For 7.6 do it by hand:

```
pnpm create vite
cd vite-react
pnpx storybook@latest init
```

### System

```bash
System:
    OS: macOS 14.1.2
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm <----- active
    pnpm: 8.12.1 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 120.0.6099.109
    Safari: 17.1.2
  npmPackages:
    @storybook/addon-essentials: ^7.6.6 => 7.6.6 
    @storybook/addon-interactions: ^7.6.6 => 7.6.6 
    @storybook/addon-links: ^7.6.6 => 7.6.6 
    @storybook/addon-onboarding: ^1.0.10 => 1.0.10 
    @storybook/blocks: ^7.6.6 => 7.6.6 
    @storybook/react: ^7.6.6 => 7.6.6 
    @storybook/react-vite: ^7.6.6 => 7.6.6 
    @storybook/test: ^7.6.6 => 7.6.6 
    eslint-plugin-storybook: ^0.6.15 => 0.6.15 
    storybook: ^7.6.6 => 7.6.6 
```
```


### Additional context

_No response_

**Comment by JReinhold** [comment] 2023-12-20 23:18
Closing as duplicate of https://github.com/storybookjs/storybook/issues/25256 that has more info

**Closed by JReinhold** 2023-12-20 23:18 UTC
Labels: bug, builder-vite, sev:S2
