### ISSUE TITLE
[RN] hierarchySeparator

### ISSUE THREAD

**Issue by ManAnRuck** [storybookjs/storybook#8307] opened 2019-10-06 15:59 UTC
**Is your feature request related to a problem? Please describe.**
on desktop hierarchySeparator option works to separate storiesOf by separator after including addon-options

**Describe the solution you'd like**
ondevice-addon for same behaviour of hierarchySeparator

**Describe alternatives you've considered**
full support of Addon-options or just the part for hierarchySeparator

**Are you able to assist bring the feature to reality?**
no

**Additional context**
<img width="465" alt="Bildschirmfoto 2019-10-06 um 17 58 41" src="https://user-images.githubusercontent.com/2183135/66271845-f9638a00-e862-11e9-8557-1266e21022b9.png">
<img width="484" alt="Bildschirmfoto 2019-10-06 um 17 58 36" src="https://user-images.githubusercontent.com/2183135/66271846-fc5e7a80-e862-11e9-9aa0-5e0a204842ab.png">
<img width="208" alt="Bildschirmfoto 2019-10-06 um 17 58 20" src="https://user-images.githubusercontent.com/2183135/66271852-fff20180-e862-11e9-82ba-2515d877a701.png">
<img width="545" alt="Bildschirmfoto 2019-10-06 um 17 58 10" src="https://user-images.githubusercontent.com/2183135/66271853-fff20180-e862-11e9-9176-b2e4768bf3f9.png">

**Comment by Gongreg** [comment] 2019-11-03 06:14
Duplicate of #3905

**Closed by Gongreg** 2019-11-03 06:14 UTC
Labels: app: react-native, bug
