### ISSUE TITLE
[Bug]: Horizontal scroll in onboarding

### ISSUE THREAD

**Issue by cdedreuille** [storybookjs/storybook#24317] opened 2023-09-27 14:30 UTC
### Describe the bug

Hello 👋 I found a bug where you can scroll horizontally in the onboarding process. No big deal but I guess your designers will not be happy about it.

![Screenshot 2023-09-27 at 9 23 42 AM](https://github.com/storybookjs/storybook/assets/1540635/996abdad-f1dc-4f9c-a6da-ea60de5fc5c8)

### To Reproduce

1. Set up a new project with `npx storybook@next init` on Safari
2. Run the onboarding
3. On the code part, you'll see a scrolling horizontal

### System

```bash
Environment Info:

  System:
    OS: macOS 13.5.2
    CPU: (12) arm64 Apple M2 Pro
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    Yarn: 3.6.3 - /opt/homebrew/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
  Browsers:
    Chrome: 117.0.5938.92
    Safari: 16.6
  npmPackages:
    @storybook/design-system: ^7.15.15 => 7.15.15
    @storybook/theming: ^7.5.0-alpha.3 => 7.5.0-alpha.3
```

### Additional context

🙏

**Comment by lalitkumawat1m** [comment] 2023-10-25 11:38
Hello Team I want to work on this issue please assign to me

**Comment by yannbf** [comment] 2023-10-25 13:51
Hey @lalitkumawat1m thank you for your interest!
The onboarding addon is part of this repo: https://github.com/storybookjs/addon-onboarding

**Comment by dylantrepos** [comment] 2023-11-16 13:53
Hello @yannbf, I don't know if someone is still working on this, but I did some researches. 

The problem is a false positive, it comes from the `const Snippet` setting the style in the file _src/components/SyntaxHighlighter/Snippet/Snippet.tsx_ of this repo [https://github.com/storybookjs/addon-onboarding](https://github.com/storybookjs/addon-onboarding).

The font size there is set with rem unit like so `fontSize: "0.8125rem"`.
Rem unit can be different on Safari browser, because Safari increase the size to get a readable size for the users, and it might  not be a good idea to try to change this because you'll loose accessibility for some users.

Thus, I suggest to not make any change in the code for this.

More info can be found here : 
[Stackoverflow](https://stackoverflow.com/questions/13237782/safari-doesnt-calculate-rem-units-correct-when-scaling-with-media-width-heigh)
[Reddit](https://www.reddit.com/r/Frontend/comments/txgygs/same_fontsize_across_safari_and_chrome/)

**Comment by yannbf** [comment] 2023-12-01 11:53
> Hello @yannbf, I don't know if someone is still working on this, but I did some researches.
> 
> The problem is a false positive, it comes from the `const Snippet` setting the style in the file _src/components/SyntaxHighlighter/Snippet/Snippet.tsx_ of this repo [storybookjs/addon-onboarding](https://github.com/storybookjs/addon-onboarding).
> 
> The font size there is set with rem unit like so `fontSize: "0.8125rem"`. Rem unit can be different on Safari browser, because Safari increase the size to get a readable size for the users, and it might not be a good idea to try to change this because you'll loose accessibility for some users.
> 
> Thus, I suggest to not make any change in the code for this.
> 
> More info can be found here : [Stackoverflow](https://stackoverflow.com/questions/13237782/safari-doesnt-calculate-rem-units-correct-when-scaling-with-media-width-heigh) [Reddit](https://www.reddit.com/r/Frontend/comments/txgygs/same_fontsize_across_safari_and_chrome/)

Oh wow, great job researching this. WDYT @cdedreuille ?

**Closed** 2024-02-19 11:51 UTC
Labels: bug, good first issue, help wanted, ui, sev:S4
