### ISSUE TITLE
[Feature Request]: A way to export multiple stories at once in an array, rather than named exports

### ISSUE THREAD

**Issue by rwacarter** [storybookjs/storybook#21687] opened 2023-03-20 13:30 UTC
### Is your feature request related to a problem? Please describe

So the typical way to export stories from a file is named exports:
```
export const Basic = Template.bind({});
export const Another = Template.bind({});
```
My use case is that I would like to be able to generate the stories in another file, and export them from the stories file. Something like this:
```
export const stories = getStoriesForTemplate(Template);
```
Where `getStoriesForTemplate` is a function that will manipulate the Template is various ways, and return an array of stories.

### Describe the solution you'd like

As above, the ability to export all stories as an array rather than individual named exports:
```
export const stories = getStoriesForTemplate(Template);
```
I think this will help people who have collections of predefined stories they would like to apply to different components, without needing to know exactly what the stories are.

### Describe alternatives you've considered

When I asked about this in the discussions, I was pointed to a (kind of) solution here: https://github.com/storybookjs/storybook/discussions/21559. However, this produces a number of errors, and seems like a solution from previous versions of Storybook, that may be deprecated relatively soon. A more first-class citizen solution that ties in better with the named exports route that Storybook is taking would be preferred if possible.

### Are you able to assist to bring the feature to reality?

no

**Comment by shilman** [comment] 2023-03-20 13:39
Closing this as a duplicate of #9828. Please continue the discussion there.

We rely on named exports to statically analyze the contents of story files without evaluating them. This is necessary for performance reasons. We don't plan to provide an interface for dynamically generating an array of stories since it would make this optimization impossible.

As a workaround for your use case, I would recommend checking out [CSF3](https://storybook.js.org/blog/storybook-csf3-is-here/). You could probably do something like this:

```js
export default {
  component: MyComponent,
}

export { A, B, C, D } from './StoriesToReuseAcrossComponents';
```

**Closed by shilman** 2023-03-20 13:39 UTC
Labels: feature request, needs triage
