### ISSUE TITLE
[Addon-docs] Invalid hook call error with MDX

### ISSUE THREAD

**Issue by Yama-Tomo** [storybookjs/storybook#10752] opened 2020-05-12 15:35 UTC
**Describe the bug**

Occurs the Invalid hook call error with MDX.

**To Reproduce**
1. clone my sample repo  https://github.com/Yama-Tomo/type-checking-MDX-in-storybook
2. run `nvm use` or use node v12.16.3
3. check out `reproduction-invalid-hook-call` branch
4. run `yarn sb`

**Screenshots**
<img width="1091" alt="screenshot" src="https://user-images.githubusercontent.com/4970917/81712263-5dac9300-94af-11ea-9f3d-d6dd3656270d.png">

**System:**
```
  System:
    OS: macOS Mojave 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
  Browsers:
    Chrome: 81.0.4044.138
    Safari: 12.1
  npmPackages:
    @storybook/addon-docs: ^6.0.0-beta.6 => 6.0.0-beta.6
    @storybook/addon-storyshots: ^6.0.0-beta.6 => 6.0.0-beta.6
    @storybook/addon-storyshots-puppeteer: ^6.0.0-beta.6 => 6.0.0-beta.6
    @storybook/addons: ^6.0.0-beta.6 => 6.0.0-beta.6
    @storybook/cli: ^6.0.0-beta.6 => 6.0.0-beta.6
    @storybook/preset-create-react-app: ^2.1.2 => 2.1.2
    @storybook/react: ^6.0.0-beta.6 => 6.0.0-beta.6
```

**Additional context**

It works when remove the `component` prop.

```diff
--- a/src/stories/HelloWorld.stories.mdx
+++ b/src/stories/HelloWorld.stories.mdx
@@ -1,7 +1,7 @@
 import { Source, Meta, Story, Preview, Props } from "@storybook/addon-docs/blocks";
 import HelloWorld from '~/components/HelloWorld';

-<Meta title="example/HelloWorld" component={HelloWorld} />
+<Meta title="example/HelloWorld" />
```

**Comment by belev** [comment] 2020-06-05 09:56
Hi,

The same error occurs when trying to use any kind of code block. For example having:
```javascript
function a() {
  console.log(42);
}
```
is resulting in `Invalid hook call` error.

React version 16.13.1, Storybook version 5.3.18.

Error stack trace:
```
<SyntaxHighlighter> component:
    in SyntaxHighlighter
    in Styled(SyntaxHighlighter)
    in Source (created by CodeOrSourceMdx)
    in CodeOrSourceMdx (created by MDXCreateElement)
    in MDXCreateElement (at documentation.story.mdx:214)
    in pre
    in Styled(pre)
    in pre (created by MDXCreateElement)
    in MDXCreateElement (at documentation.story.mdx:214)
    in wrapper (created by MDXCreateElement)
    in MDXCreateElement (at documentation.story.mdx:25)
    in MDXContent (at documentation.story.mdx:399)
    in AddContext (at documentation.story.mdx:399)
    in page
    in div
    in Styled(div) (created by DocsContainer)
    in div
    in Styled(div) (created by DocsContainer)
    in MDXProvider (created by DocsContainer)
    in ThemeProvider (created by DocsContainer)
```

Any ideas what could be causing this?

**Comment by dlvhdr** [comment] 2020-06-10 10:29
This is happening for me as well.
Any chance to investigate it?

**Comment by shilman** [comment] 2020-06-11 02:56
Have you guys tried a recent beta? I think @tooppaaa made some changes to this code

**Comment by Yama-Tomo** [comment] 2020-06-11 03:35
ummm... still have error in 6.0.0-beta.23

**Comment by tooppaaa** [comment] 2020-06-11 07:42
@shilman Dupe of https://github.com/storybookjs/storybook/issues/10895
There is more info and reproduction on the other issue. 
Let's move discussion there ?

**Comment by shilman** [comment] 2020-06-11 10:43
Ok, closing this as a dupe of #10895

**Closed by shilman** 2020-06-11 10:43 UTC
Labels: addon: docs, mdx, question / support
