### ISSUE TITLE
single stories are pulling in every other stories' stylesheets?

### ISSUE THREAD

**Issue by moimikey** [storybookjs/storybook#729] opened 2017-03-21 15:02 UTC
Hi,

I'm trying to figure out why i'm having this particular issue. I'm dynamically loading stories like this:

```js
function loadStories() {
	const req = require.context('../components', true, /story.js$/);
	req.keys().forEach(filename => req(filename));
}
configure(loadStories, module);
```

and each `story.js` file has a respective sass or css file that is imported into it (for the purpose of story specific styles that are outside of the component that `story.js` would import, to display:

```js
import './story.sass';
```

I have about 4 stories right now and this is the source of each story iframe... loading every stylesheet:

<img width="651" alt="screen shot 2017-03-21 at 9 56 22 am" src="https://cloud.githubusercontent.com/assets/182661/24153796/6acba31c-0e1d-11e7-9fe6-62eece4d9c25.png">

Is this normal behavior...?

--

demo

https://github.com/moimikey/729-single-stories-pulling-all-stylesheets

**Comment by moimikey** [comment] 2017-03-21 16:27
also, webpack is emitting all of those stories, so i'm wondering if it's how i've configured webpack?

<img width="226" alt="screen shot 2017-03-21 at 11 27 10 am" src="https://cloud.githubusercontent.com/assets/182661/24158122/6bc665ca-0e29-11e7-801e-00232030392f.png">

**Comment by moimikey** [comment] 2017-03-21 17:17
i tried to use a decorator also, and this ended up being half broken, as i was able to at least isolate the additional stylesheet to the story, but as i traversed through others, those styles would break unless i did a hard refresh.

```js
	.addDecorator((getStory) => {
		require('./story.sass');
		return getStory();
	})
```

**Comment by moimikey** [comment] 2017-03-21 19:34
@arunoda @mnmtanish

**Comment by ndelangen** [comment] 2017-03-28 13:58
Interesting!, do you have a repo that demonstrates this?

**Comment by moimikey** [comment] 2017-03-28 13:59
@ndelangen will make one shortly

**Comment by moimikey** [comment] 2017-03-28 14:11
@ndelangen https://github.com/moimikey/729-single-stories-pulling-all-stylesheets

**Comment by ndelangen** [comment] 2017-04-05 22:48
Still trying to find the time to check this out..

**Comment by moimikey** [comment] 2017-04-05 22:49
thanks ;D it's a weird one. i've given it a look, but i'm uncertain where to start.

**Comment by ndelangen** [comment] 2017-04-05 22:54
So what I think is happenings is all the CSS files are getting picked up by webpack style-loader and just injected into the head. wether they are used or not.

**Comment by ndelangen** [comment] 2017-04-05 22:57
But how to fix? 

What I've done for my CSS is use CSS-modules. and import the generated classnames into my JS. Even if all CSS is injected together into the head, it doesn't matter, because it's guaranteed to be unique classes/selectors.

It doesn't reall solve the exact problem you're having. But I think this is the intended behaviour of the style-loader.

**Comment by moimikey** [comment] 2017-04-05 23:10
this is true. i (and my company) are scoping with css, but we're doing a huge code redevelopment, so we have shared styles, thus a combination of `styleName` and `className`. so what ends up affecting storybook are those "outsider" css files.

i'll look into storybook code again tonight after i've had some beers and figure out how to perhaps solve this, implementation wise.

**Comment by mnmtanish** [comment] 2017-04-08 11:10
@moimikey for your problem I guess you have to skip the style-loader and load css files manually with a decorator. Something like this perhaps:

```jsx
.addDecorator(getStory => (
  <div>
    <link ... />
    {getStory()}
  </div>
))
```

**Comment by moimikey** [comment] 2017-04-09 02:41
Wow .... that never crossed my mind... I'll try that.

**Comment by moimikey** [comment] 2017-04-09 03:18
ick but then again, using sass... x_x

**Comment by moimikey** [comment] 2017-04-09 04:18
so @mnmtanish. thank you for your guidance. i've solved my issue with your inspiration:

```
.addDecorator((getStory) => {
  require('./story.sass');
  return getStory();
})
```

**Comment by moimikey** [comment] 2017-04-09 04:32
mmm so the only issue then now is that when you navigate from story to story, it's stacking the styles :(

**Comment by mnmtanish** [comment] 2017-04-09 07:38
Maybe the style loader can be configured to insert it somewhere other than HEAD so it can be removed. I haven't done this so not sure if it's even possible. Check [these](https://github.com/webpack-contrib/style-loader#insertat) out.

**Comment by ConneXNL** [comment] 2017-04-13 23:00
Isn't it the responsibility of react storybook to load the component in complete isolation and thus only have JavaScript/CSS ran that is related to the current selected story?

**Comment by moimikey** [comment] 2017-04-13 23:13
@ConneXNL  yes. good point. this is true... ;X

**Comment by moimikey** [comment] 2017-04-13 23:16
@mnmtanish my next response of course leads to another issue, `insertAt` might be useful, but it only available in the latest version of `style-loader`, which is not possible to use with storybook, because it uses `loader-utils@1.x`. storybook is still using `0.x`. the latest possible version we can use is `style-loader@0.13.1` :(...

**Comment by ndelangen** [comment] 2017-05-22 21:46
Hey @moimikey maybe you can try the approach the last mentioned with the alpha release?

**Comment by ConneXNL** [comment] 2017-06-08 14:55
Isn't it better/safer to create a new iframe element when switching stories?

**Comment by ndelangen** [comment] 2017-06-08 20:35
That'd be safe, and also bad for performance.

The new iframe would have to parse the javascript, parse the CSS, connect to the postmessage-channel, reconnect to the websocket, and probably more stuff.

Maybe removing `<style>` elements on story-switch is enough to resolve this issue?

Of course there are no global styles and everything is properly namespaced, this wouldn't be an issue outright. Wishful thinking I guess. 😃

**Comment by ndelangen** [comment] 2017-06-08 20:36
If someone can prove the above statements are false or can demonstrate there's no negative consequences, I'm all ears!

**Comment by ConneXNL** [comment] 2017-06-08 22:53
I did some tests today. The decorator pattern worked well so that styles are only injected once you switch to the story. However, I had the same issue where the styles aren't removed when switching stories.

I played around with removing styles in a decorator but it seems the required style is only applied once. Is it possible to re-trigger a require()? I tried using singleton: false but that didn't fix the problem.

**Comment by ndelangen** [comment] 2017-06-09 00:03
I'm almost hesitant to even suggest this, but you could try busting the webpack cache:
https://webpack.github.io/docs/api-in-modules.html#advanced

This is webpack 1 docs, but might still work.

**Comment by ndelangen** [comment] 2017-07-07 13:37
Idea: you could write an addon that removes all `<style>...</style>`'s when switching stories. To clean-up the styles not relevant to the current story.

**Comment by ConneXNL** [comment] 2017-07-18 21:32
I am almost there. In the webpack config I use
`'style-loader/useable' instead of 'style-loader',`

This adds an API for you to work with. .use() to add the styles, unuse() to remove them. In my stories file I use the decorator like:

`.addDecorator((c) => <ReactStylesheet stylesheets={[require('./stories.scss')]}>{ c() }</ReactStylesheet> )`

Using the following React Component to add and remove the styles.

import * as React from 'react';

```
export class ReactStylesheet extends React.Component{

    componentWillUnmount(){
        let stylesheets = Array.isArray(this.props.stylesheets) ? this.props.stylesheets : [this.props.stylesheets];
        stylesheets.forEach((stylesheet) => {
            console.log("Unmounting....");
            stylesheet.unuse();
        });

    }

    componentDidMount(){
         let stylesheets = Array.isArray(this.props.stylesheets) ? this.props.stylesheets : [this.props.stylesheets];
        stylesheets.forEach((stylesheet) => {
            console.log("Mounting....");
            stylesheet.use();
        });
    }

    render(){
        return this.props.children;
    }
}
```

Changing the stylesheet correctly hot reloads the styles. Switching to a different story unuse() is called and the stylesheets are cleaned. However, the method breaks when re-adding the styles as it ads the non hrm updated version of the stylesheet. Doing any change after that also throws this error:

```
Uncaught (in promise) TypeError: Cannot read property 'refs' of undefined
    at update (webpack:///./~/style-loader/addStyles.js?:63:4)
    at eval (webpack:///./src/Component/stories.scss?:32:4)
    at Object.hotApply [as apply] (http://dev.test:6006/static/preview.bundle.js:499:14)
    at cb (webpack:///(webpack)-hot-middleware/process-update.js?:52:36)
    at eval (webpack:///(webpack)-hot-middleware/process-update.js?:68:13)
    at <anonymous>
```

I am not sure how to update the require statement to point to the latest HRM version.

**Comment by ndelangen** [comment] 2017-07-19 08:35
Fantastic investigative work! I looked around for something like this, before and wasn't able to find it.

Anything we can do on this side to help @ConneXNL ?

**Comment by moimikey** [comment] 2017-07-19 13:56
the solutions are getting close. the idea of `stylesheet.use()` and `unuse` was foreign to me, but this seems like it's getting on the right track.

**Comment by moimikey** [comment] 2017-08-03 18:40
this is also another interesting thing for sandboxing storybook https://github.com/Wildhoney/ReactShadow

**Comment by ndelangen** [comment] 2017-12-16 10:34
@ConneXNL to finish this issue up, do you think you could help us with improving the docs in this regard?

If you can't find a good place for it, just punk it down somewhere in markdown format. I'll take take of placing it in.

🙇

**Comment by soundstep** [comment] 2019-05-13 12:43
Same issue here, storybook doesn't isolate each story, making it unusable for any visual testing/ acceptance testing.

**Comment by bennypowers** [comment] 2019-09-19 04:41
Putting up a shadow root around stories would instantly solve this problem without @ndelangen 's performance concerns

**Comment by ndelangen** [comment] 2019-09-24 08:25
@bennypowers interesting! would you have a code sample on how to achieve that? 🙇 

Might be interesting for @shilman too.

**Comment by iheredia** [comment] 2019-10-22 19:42
Hi. I'm also experiencing this issue
Was this fixed or is there any workaround?

**Comment by bennypowers** [comment] 2019-10-27 09:10
@ndelangen 

The quickest path to satisfaction here is probably @moimikey's suggestion to use [ReactShadow](https://github.com/Wildhoney/ReactShadow)

The strategy to take might be to wrap the root in a ReactShadow component, then bring in the styles with [`adoptedStyleSheets`](https://developers.google.com/web/updates/2019/02/constructable-stylesheets) (or a `<style>` element for non-supporting browsers)

https://github.com/storybookjs/storybook/blob/ba74d889fcfd87849a6ae9369f5e4176e8149d33/lib/core/src/client/preview/start.js#L253

**Comment by aendrew** [comment] 2020-01-02 15:25
Please re-open this, this issue makes adding custom styles on a per-story basis exceedingly difficult. I have totally separate MDX stories that implement custom styling for their examples, and globally including all styles from every story makes this use case untenable.

**Comment by moimikey** [comment] 2020-01-06 23:56
I hope for this to be solved by March 21st, 2020.

**Comment by shilman** [comment] 2020-01-07 01:46
@moimikey Any interest in taking this on? Best way to ensure it's done by a certain date ... 😉

**Comment by pocka** [comment] 2020-01-07 09:01
IMO we should add parameters or addon to handle this feature instead of adding special functionality just for stylesheets. It'll cause inconsistent behavior between stylesheets and scripts. But maybe it's a good time to consider how "isolation" should be?

I wrote a quick PoC for the addon approach, for who wonder it's possible.
https://github.com/pocka/storybook-addon-css

**Comment by shilman** [comment] 2020-01-07 12:35
@pocka You are AWESOME! 💯

**Comment by moimikey** [comment] 2020-01-07 14:44
yazzzzz. cheers @pocka

**Comment by aendrew** [comment] 2020-01-07 16:49
Worth noting @pocka's solution doesn't work if you're using MDX stories because of mdx-js/mdx#894.

**Comment by pocka** [comment] 2020-01-08 03:32
@aendrew 
Thank you for pointing out that, I completely forgot about MDX :no_mouth:
I updated PoC and [added MDX examples](https://storybook-addon-css.netlify.com/?path=/docs/test--foo).

With the addon approach  (per story styles), in contrast to the file-scoping approach (per file styles), the Docs tab will get all stylesheets of every story. In [my example](https://storybook-addon-css.netlify.com/?path=/docs/test--foo), "foo" and "baz" story importing `foo.css` and "bar" story importing `bar.css`, then Docs tab gets both `foo.css` and `bar.css`. I think this is unavoidable and I don't know this is acceptable or not.

**Comment by ndelangen** [comment] 2020-01-09 09:39
@pocka I think that approach might work out well with https://github.com/storybookjs/storybook/tree/next/addons/cssresources WDYT?

**Comment by pocka** [comment] 2020-01-10 03:38
@ndelangen 
Ah, that's right!

```js
foo.story = {
  parameters: {
    cssresources: [
      {
        id: 'foo',
        code: `<style>${require('!to-string-loader!css-loader!./foo.css')}</style>`,
        picked: true
      }
    ]
  }
}
```

One concern: if a user imports very large stylesheets, the "CSS Resources" tab will be messy.

**Comment by ndelangen** [comment] 2020-01-23 12:23
@pocka right, I think the cssresources addon can be vastly improved in that department. Do you feel like taking that on?

**Comment by pocka** [comment] 2020-01-23 15:36
@ndelangen 
Yes :smiley:

By the way, what do you think about letting users to write raw-webpack-query? (like `!to-string-loader!...`) I think we need a lot of black magic in the addon code if we want to get rid of this...

**Comment by ndelangen** [comment] 2020-01-23 15:39
I think we support babel-macros by default, so users could be using [macro-preval](https://github.com/kentcdodds/preval.macro) to inject file-contents into the bundle as well?

**Comment by pocka** [comment] 2020-01-23 15:41
I didn't know that, will take a look at it soon!

**Comment by valec-openmind** [comment] 2020-02-20 20:32
Hi there, i'm experiencing the same issue.

**Comment by pocka** [comment] 2020-02-21 15:37
For anyone facing the issue, please try [this workaround](https://github.com/storybookjs/storybook/issues/729#issuecomment-572858966). (It needs a little deep webpack knowledge though).

---

@ndelangen I took a look at the macro but what it enables is "loading CSS files from file system", right? I think many users want to import SASS, Less, Stylus, CSS files with PostCSS, or etc, so that approach wouldn't satisfy the needs. My current idea is CSSResource addon adding a rule that imports CSS file with `to-string-loader` (or `file-loader`) so that the user could import a CSS file then use it for the addon.

```js
// adding a rule like this
{
  test: /\.css$/,
  resourceQuery: /cssresources/,
  use: ['to-string-loader', 'css-loader', 'postcss-loader']
}
```

For pre-processors, an option to customize `test` and `use` is also needed. It's possible to pick a rule for style file then modify it with `oneOf` but it would be so complicated...

**Comment by ndelangen** [comment] 2020-02-24 10:08
@pocka yeah that sounds like an interesting concept!

**Comment by gptt916** [comment] 2020-03-16 21:29
Hi, wondering if this is still being worked on? I am also experiencing the issue, I am aware of the work around but would like to know if a fix will be available any time soon.

**Comment by meantsaki** [comment] 2020-03-25 19:25
Hi, can you provide a example of the workaround with a Vue Story.?

**Comment by tylersticka** [comment] 2020-04-09 16:22
As far as I can tell, [the workaround](https://github.com/storybookjs/storybook/issues/729#issuecomment-572858966) still results in stylesheets stacking after initial view, at least if you're using the Docs add-on. 😕

**Comment by rhendric** [comment] 2020-04-27 16:23
With no disrespect intended, I find @pocka's addon approach rather lacking, as it doesn't isolate styles that have been imported in component files as opposed to in the story files, which I think is the more common pattern. My personal desire—I suspect this may be shared by others in this thread—is to be able to have an `import './Button.css'` inside of `Button.jsx` that only gets used in story files where `Button.jsx` is imported. Per-story styling, in the manner that @pocka has provided, isn't nearly as important to me as making sure that no component that doesn't itself import `Button` (directly or indirectly) isn't affected by any CSS rules from `Button.css`. (The concern here is wanting to make sure that `OtherWidget.css`, say, isn't lacking some rules that inadvertently ended up in `Button.css` instead—maybe they got overlooked in a refactoring or something—and missing it because the stories for OtherWidget get all the statically-imported CSS of the entire app, so OtherWidget still looks fine in Storybook.)

What I think I would do instead is change *all* CSS loaders to inject with `lazyStyleTag`, and then use webpack API to generate a new module that groups the CSS modules by the story files that ultimately require them and listens to story change events to turn the appropriate modules on and off.
Has this approach already been considered and discarded, or are there any issues with it that you see now? I think I can do it all in a Storybook addon, but it might be cleaner if integrated into Storybook as a core feature.

**Comment by bennypowers** [comment] 2020-04-27 17:06
If you want strong style encapsulation, browsers ship with it. At the risk of exposing my own ignorance here, I'm still not sure why all this userland JavaScript (with its associated complexity costs) is necessary to accomplish something that's built-in and ready to go.

Why not just render each story's DOM into a shadow root with something like this

```js
customElements.define('encapsulated-story', class EncapsulatedStory extends HTMLElement {
  constructor() {
    super();
    this.attachShadow({ mode: 'open' });
  }

  /* not sure why we'd need this getter, but let's say */
  get storyHTML() {
    return this.shadowRoot.innerHTML;
  }

  set storyHTML(string) {
    this.shadowRoot.innerHTML = storyHTML;
  }
});
```

and whenever the story changes

```js
encapsulatedStory.storyHTML = theStoryDOMStringWithAllStyleTags;
```

and done? Here, `theStoryDOMStringWithAllStyleTags` is just the concatenation of a story's HTML with all associated styles concated as inline `<style>` tags. Story's could style the host element with the `:host` selector, as normal.

That's a bare-minumum starting point, which could be built on later on perhaps with some library code, but at least it will accomplish the goal of strong style encapsulation without the need for all these new proposed APIs.

**Comment by rhendric** [comment] 2020-04-27 17:18
How does that work with webpack, though? Webpack packages everything up into a JavaScript bundle, not a DOM string; and the way webpack is currently configured, it packages all stories up into a single bundle. I don't think a shadow root helps when the JavaScript being (hot-re)loaded inserts styles directly into the document's head. You need to do some hairy webpack configuration one way or another to change that.

Using the shadow DOM to completely isolate each story would also mean replicating the style tags shared by many stories into each one; using a shared style as bundled by webpack will be more efficient. Maybe not enough to make a huge difference, but possibly enough to offset the benefits, if there are any, of using the shadow DOM instead of using `lazyStyleTag` (which I think is the only piece of complexity that shadow roots would save you).

**Comment by danielo515** [comment] 2020-06-15 10:27
I am also interested on seeing this fixed sooner or later.

**Comment by matthias-ccri** [comment] 2020-10-01 00:28
> That'd be safe, and also bad for performance.
> 
> The new iframe would have to parse the javascript, parse the CSS, connect to the postmessage-channel, reconnect to the websocket, and probably more stuff.

@ndelangen sorry to quote you from 2017, but is this still your perspective, that reloading an iframe is too expensive? Browsers do this type of thing constantly; they're probably very optimized for it. In this case it would be even faster than a regular page load, since there are no network requests involved.

To me, the benefit outweighs the cost, because I would very much prefer a fresh iframe for each story. I would tolerate a delay of as much as 600ms for such a luxury.

(My use case is that I'm trying to render some legacy angularjs components in storybook, and let's just say that the components aren't very pure. They're very stateful; they have side effects and make use of angularjs services which are also very stateful. Things break in unexpected ways.)

One idea for an API surface is to configure storybook in `.storybook/manager.js`.
```
addons.setConfig({
  refreshBetweenStories: true,
})
```
This could be considered a UI setting if you tilt your head the right way.

There would be no runtime cost for people who do not enable this flag, and for those who do enable it, they _really_ need it, so any such delay would be tolerable.

**Comment by shilman** [comment] 2020-10-01 04:25
If you want this fixed, please upvote by adding a 👍 to the issue description. We use this to help prioritize!

**Comment by ashvin777** [comment] 2020-10-29 06:17
Hi @shilman , Isn't it fixed here https://github.com/sourcegraph/sourcegraph/pull/10033 already ?

**Comment by joneldiablo** [comment] 2020-12-04 19:12
> .addDecorator((getStory) => {
>   require('./story.sass');
>   return getStory();
> })

HI!!!!
where can I put this one?!!!

**Comment by ashleynolan** [comment] 2021-07-14 09:51
We're seeing the same issue on an instance of Storybook running with Vue.

We have a component mono-repo and where components are shared across larger components (for example, a button component, which is then used inside a modal component and a banner component) the styles from both components are loaded in and they conflict (even though they are using CSS Modules to scope the CSS).

As we have visual regression tests running against Storybook, it means that visually our components look different in Storybook to how they do when properly built as a library component. Being able to run these components in true isolation from the other component styles would solve this issue.

Are there any plans to work on this use-case? We'd be happy to help find a solution to this and contribute back, but not really sure where to start so would need some help to do so.

**Comment by helloanil** [comment] 2021-09-05 23:19
Is there any working solution for this, for Storybook 6?

**Comment by bennypowers** [comment] 2021-09-15 09:54
> Is there any working solution for this, for Storybook 6?

try this

```js
import { render, html } from 'lit-html';

let id = 1;


function shadowDecorator(storyFn) {
  // generate a tagname. maybe use storyname here?
  const tagName = `shadow-story-${id++}`;
  // define a custom element which renders the story to its shadow root
  // optionally, include a css reset here?
  customElements.define(tagName, class ShadowStory extends HTMLElement {
    constructor() {
      super();
      this.attachShadow({ mode: 'open' });
      // season to taste, depending on sb flavour
      render(storyFn(), this.shadowRoot);
    }
  });
  return document.createElement(tagName);
}

export const decorators = [shadowDecorator];
```

**Comment by shilman** [comment] 2021-09-20 14:58
closing this as duplicate to #16016 .. let's continue discussion there!

**Closed by shilman** 2021-09-20 14:58 UTC
Labels: bug, todo

**Comment by JoostVanVelthoven** [comment] 2022-08-26 06:27
I worked around it with the follow snippet used as a decorator:

`  var css1 = require('!raw-loader!./main.css')
   
    return <>
        <style>{css1.default}</style>
        {children}
    </>`
