### ISSUE TITLE
[Bug]: Vue 3 Source Code Panel No Longer Show Custom Template Content

### ISSUE THREAD

**Issue by TNGD-YQ** [storybookjs/storybook#29990] opened 2024-12-09 09:15 UTC
### Describe the bug

Before 8.3.0 release, we can get the additional attributes and customised templare in source code preview as expected.

![Image](https://github.com/user-attachments/assets/a3482a24-d3d7-4248-bf60-1f520c72f9ea)

https://stackblitz.com/edit/github-pzabiw5o-y7gttwv2?file=src%2Fstories%2FButton.stories.ts,package.json,.stackblitzrc&preset=node

On 8.3.0 release,I believe a new improvement to support `v-bind` code display override the original implementation

![Image](https://github.com/user-attachments/assets/5481e7d2-46fb-4e27-a671-b7a67324f0ce)

### Reproduction link

https://stackblitz.com/edit/github-pzabiw5o?file=src%2Fstories%2FButton.stories.ts&preset=node

### Reproduction steps

1. open the Reproduction link above.
2. enter Button component page a right side preview panel.
3. expand the source code panel.
4. expect to see the template with custom content, now all overridden.

### System

```bash
Storybook Environment Info:

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm <----- active
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @storybook/addon-essentials: ^8.5.0-alpha.18 => 8.5.0-alpha.18 
    @storybook/addon-interactions: ^8.5.0-alpha.18 => 8.5.0-alpha.18 
    @storybook/addon-onboarding: ^8.5.0-alpha.18 => 8.5.0-alpha.18 
    @storybook/blocks: ^8.5.0-alpha.18 => 8.5.0-alpha.18 
    @storybook/test: ^8.5.0-alpha.18 => 8.5.0-alpha.18 
    @storybook/vue3: ^8.5.0-alpha.18 => 8.5.0-alpha.18 
    @storybook/vue3-vite: ^8.5.0-alpha.18 => 8.5.0-alpha.18 
    storybook: ^8.5.0-alpha.18 => 8.5.0-alpha.18
```

**Comment by valentinpalkovic** [comment] 2024-12-24 12:04
Duplicate of https://github.com/storybookjs/storybook/issues/29718

**Closed by valentinpalkovic** 2024-12-24 12:04 UTC
Labels: bug, needs triage
