### ISSUE TITLE
Importing and rendering MD in *.stories.mdx doesn't render code blocks correctly

### ISSUE THREAD

**Issue by mattfelten** [storybookjs/storybook#13589] opened 2021-01-09 02:08 UTC
**To Reproduce**
I have a Markdown file being imported into a `.stories.mdx` file and, while it renders, I'm noticing differences between the imported version and writing it directly in the mdx file. See code snippets and screenshots below.

**Expected behavior**
I would expect the code fence to look the same in the imported file as is does if I wrote it in the `*.stories.mdx` file.

**Screenshots**
![](https://p195.p4.n0.cdn.getcloudapp.com/items/v1u4zxlA/db138bfe-feb7-464e-be59-86bf97d2d893.png?v=0d709bd6de64baf3b478ccf8aae14153)
![](https://p195.p4.n0.cdn.getcloudapp.com/items/geuoQqln/22973c4b-b07f-4ef3-bcc2-f7e73e5dddab.png?v=bb19b1e02655e127700d24c5b1d28244)

**Code snippets**
If applicable, add code samples to help explain your problem.
```
// Readme.md

An `inline` codeblock

` ``
A fenced codeblock (without extra spaces)
` ``
```
```
// Overview.stories.mdx
import { Meta, Description } from '@storybook/addon-docs/blocks';
import Readme from '../Readme.md';

<Meta title="Overview" />

<Description>{Readme}</Description>
```

**System**
#### Environment Info:

  System:
    OS: macOS 11.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.19.0/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 84.0
    Safari: 14.0.2

**Additional context**
It seemed like some people were having similar issues over in #7644

**Comment by SS-Evelyn** [comment] 2021-01-09 02:10
你们

**Comment by TheMightyPenguin** [comment] 2021-03-18 22:24
@shilman I'd like to give this one a shot! 😄

**Comment by TheMightyPenguin** [comment] 2021-03-28 18:18
After some debugging, the cause of this is that the MDX components used by the [`Description`](https://github.com/storybookjs/storybook/blob/6a937b6d032b91c3fbd3ca057a7ee58696a0dcfd/lib/components/src/blocks/Description.tsx#L16) for `code` blocks is different than the one being used by [`DocsContainer`](https://github.com/storybookjs/storybook/blob/6a937b6d032b91c3fbd3ca057a7ee58696a0dcfd/addons/docs/src/blocks/DocsContainer.tsx#L19-L24). This causes this difference in styles and behavior when rendering code blocks!.

I have a fix working, I'll do some cleanup and open a PR! I have a concern tho, does this count as a breaking change? as it changes how Storybook behaves for this functionality?

**Comment by TheMightyPenguin** [comment] 2021-04-07 01:21
@shilman I opened a PR fixing this 😄 https://github.com/storybookjs/storybook/pull/14495

**Comment by shilman** [comment] 2021-04-16 21:35
Yippee!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.9 containing PR #14495 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2021-04-16 21:35 UTC
Labels: PN, block: other, bug, good first issue, help wanted, mdx
