### ISSUE TITLE
[Bug] Dynamic require of "@storybook/global" is not supported

### ISSUE THREAD

**Issue by adrianwix** [storybookjs/storybook#25655] opened 2024-01-18 14:25 UTC
### Describe the bug

The following error is show when installing this Addon

Error: Dynamic require of "@storybook/global" is not supported
    at http://localhost:6006/node_modules/.cache/sb-vite/deps/chunk-2LSFTFF7.js?v=d48453e7:13:9
    at ../../lib/channels/dist/index.js (http://localhost:6006/node_modules/.cache/sb-vite/deps/@storybook_addon-console.js?v=d48453e7:3656:28)
    at http://localhost:6006/node_modules/.cache/sb-vite/deps/@storybook_addon-console.js?v=d48453e7:843:54
    at node_modules/@storybook/addon-actions/dist/index.js (http://localhost:6006/node_modules/.cache/sb-vite/deps/@storybook_addon-console.js?v=d48453e7:3866:35)
    at __require2 (http://localhost:6006/node_modules/.cache/sb-vite/deps/chunk-2LSFTFF7.js?v=d48453e7:19:50)
    at node_modules/@storybook/addon-console/dist/index.js (http://localhost:6006/node_modules/.cache/sb-vite/deps/@storybook_addon-console.js?v=d48453e7:4135:25)
    at __require2 (http://localhost:6006/node_modules/.cache/sb-vite/deps/chunk-2LSFTFF7.js?v=d48453e7:19:50)
    at http://localhost:6006/node_modules/.cache/sb-vite/deps/@storybook_addon-console.js?v=d48453e7:4374:16

### Steps to reproduce the behavior

1. Install the addon
2. Go to any Story

### Expected behavior

The stories should render

### Screenshots and/or logs

<img width="1440" alt="image" src="https://github.com/storybookjs/storybook-addon-console/assets/37629556/8ea0e2ed-8ad7-4a73-8bab-73566434ce73">

### Environment

 - OS: MacOs 14.2.1
 - Node.js version: v16.20.0
 - NPM version: 8.19.4

### Additional context

```
    "@storybook/addon-console": "^2.0.0",
    "@storybook/addon-essentials": "^7.6.9",
    "@storybook/addon-interactions": "^7.6.9",
    "@storybook/addon-links": "^7.6.9",
    "@storybook/addon-mdx-gfm": "^7.6.9",
    "@storybook/blocks": "^7.6.9",
    "@storybook/preset-create-react-app": "^7.6.9",
    "@storybook/react": "^7.6.9",
    "@storybook/react-vite": "^7.6.9",
```

main.ts

```ts
import type { StorybookConfig } from '@storybook/react-vite';

const config: StorybookConfig = {
  stories: ['../src/**/*.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/preset-create-react-app',
    '@storybook/addon-interactions',
    '@storybook/addon-console',
  ],
  core: {},
  framework: {
    name: '@storybook/react-vite',
    options: {},
  },
  docs: {
    autodocs: 'tag',
  },
  staticDirs: ['../public'],
};

export default config;
```

preview.ts

```tsx
import React from 'react';
import ThemeConfig from '../src/theme';
import ThemePrimaryColor from '../src/components/ThemePrimaryColor';
import ThemeLocalization from '../src/components/ThemeLocalization';
import type { Preview } from '@storybook/react';

import { withConsole } from '@storybook/addon-console';

const preview: Preview = {
  parameters: {
    actions: { argTypesRegex: '^on[A-Z].*' },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/,
      },
    },
  },
  decorators: [
    Story => (
      <ThemeConfig>
        <ThemePrimaryColor>
          <ThemeLocalization>
            <Story />
          </ThemeLocalization>
        </ThemePrimaryColor>
      </ThemeConfig>
    ),
    (storyFn, context) => withConsole()(storyFn)(context),
  ],
};

export default preview;

```

**Comment by raymondluong** [comment] 2024-01-18 21:43
https://github.com/storybookjs/storybook/issues/25130

**Comment by valentinpalkovic** [comment] 2024-01-18 22:05
Duplicate of https://github.com/storybookjs/storybook/issues/25130

**Closed by valentinpalkovic** 2024-01-18 22:05 UTC
Labels: bug
