### ISSUE TITLE
Storybook + Svelte + Webpack5 in an ESM package crashes on require('@storybook/svelte')

### ISSUE THREAD

**Issue by nickpalmer** [storybookjs/storybook#17945] opened 2022-04-13 05:16 UTC
**Describe the bug**
Storybook + Svelte + Webpack5 inside a package using `"type":"module"` in the top level package.json crashes on a require in the main.iframe.bundle.js

**To Reproduce**
Please see the README.md at:

https://github.com/nick-codes/storybook-svelte-webpack5-bug-repro

**System**
```
Environment Info:

  System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 3.2.0 - /opt/homebrew/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 100.0.4896.88
    Safari: 15.3
  npmPackages:
    @storybook/addon-actions: ^6.5.0-alpha.62 => 6.5.0-alpha.62
    @storybook/addon-docs: ^6.5.0-alpha.62 => 6.5.0-alpha.62
    @storybook/addon-essentials: ^6.5.0-alpha.62 => 6.5.0-alpha.62
    @storybook/addon-links: ^6.5.0-alpha.62 => 6.5.0-alpha.62
    @storybook/builder-webpack5: ^6.4.21 => 6.4.21
    @storybook/manager-webpack5: ^6.4.21 => 6.4.21
    @storybook/svelte: ^6.5.0-alpha.62 => 6.5.0-alpha.62
```

**Additional context**
I'm really not sure how to get the main iframe bundle to use `__webpack_require__` instead of the generated require statement.

**Comment by benbender** [comment] 2022-04-18 16:16
Should be fixed with https://github.com/storybookjs/storybook/commit/6415d8ec47a85cbbe1f919c92da8112a3b772102

**Comment by nickpalmer** [comment] 2022-05-05 03:32
Thanks! This makes it work properly.

**Comment by shilman** [comment] 2023-06-08 04:32
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

**Closed by shilman** 2023-06-08 04:32 UTC
Labels: bug, has workaround, svelte, builder-webpack5
