### ISSUE TITLE
Cant use enum's in template

### ISSUE THREAD

**Issue by MickL** [storybookjs/storybook#16386] opened 2021-10-18 10:54 UTC
**Describe the bug**
Within an Angular component, declaring a class-/template-variable that is an enum, does not work in Storybook templates.

**To Reproduce**

```ts
export enum Animals {
   Cat,
   Dog,
   Mouse,
}
```

```ts
@Component({...})
export class MyComponent {
     Animals = Animals;
     someVal = Animals.Cat;
}
```

```html
<div *ngIf="someVal === Animals.Cat">Works!</div>
```

I noticed this already in earlier versions of Storybook. Weirdly if I rename the enum while Storybook is running, it suddenly works. But if I stop the process or make build, its not working again.

**System**
```
  System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.8.0 - ~/.nvm/versions/node/v16.8.0/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v16.8.0/bin/yarn
    npm: 7.21.1 - ~/.nvm/versions/node/v16.8.0/bin/npm
  Browsers:
    Chrome: 94.0.4606.81
    Safari: 15.0
  npmPackages:
    @storybook/addon-actions: ^6.4.0-beta.13 => 6.4.0-beta.13 
    @storybook/addon-essentials: ^6.4.0-beta.13 => 6.4.0-beta.13 
    @storybook/addon-links: ^6.4.0-beta.13 => 6.4.0-beta.13 
    @storybook/angular: ^6.4.0-beta.13 => 6.4.0-beta.13 
    @storybook/builder-webpack5: ^6.4.0-beta.13 => 6.4.0-beta.13 
    @storybook/manager-webpack5: ^6.4.0-beta.13 => 6.4.0-beta.13 
```

**Comment by MickL** [comment] 2021-10-18 15:35
It seems like Storybook has problems with enum's in general and it is not dependent on the name as I first stated:
After a restart of Storybook it is not working again, even with the changed name. Now if I rename the variable (to the same name as the enum) it works again.

So it seems like enum's are not correctly working in the template but if I rename the variable while Storybook is running it works.

Also I checked another project and a lot of stories don't work because of the same problem.

**Comment by MickL** [comment] 2021-11-17 14:16
Will this ever be fixed or at least reviewed? Storybook is currently unusable in multiple huge projects we work on.

**Comment by shilman** [comment] 2021-11-19 02:37
@storybookjs/angular This one is pretty strange. Is there something non-standard about how we compile templates? I can reproduce with the repo @MickL has provided above

**Comment by Marklb** [comment] 2021-11-19 04:23
This seems to be an issue with Storybook and Compodoc.

Looking at Compodoc output the "defaultValue" is "Animals", which is not correct. I don't know what Compodoc should be expected to put for the default value, because I don't know how enums are supposed to be serialized/deserialized, but if Compodoc would have specified the "type" as "enum" then it would at least be more clear that the "defaultValue" shouldn't be a string.

The bigger issue is that Storybook should have never touched that property. The property is not an input/output, so I see no reason for there to even be a control in the ArgsTable, unless there is a control manually configured in the "argTypes" for that story.

**Comment by mateuszo** [comment] 2022-03-16 11:41
I've bumped into this issue myself. The workaround I used was to declare enum as a getter instead of a field like this:
``` typescript
@Component({...})
export class MyComponent {
    get animals() {
     return Animals;
    }
}
```


It's a simple workaround, but I dislike that it requires modifying the component code to make a component work with both storybook and app.

**Comment by MickL** [comment] 2022-07-14 21:41
Coming back to Storybook 1 year later, still not fixed. Sadly our team decided to use Storybook for a project.

**Comment by stefanoschrs** [comment] 2022-10-28 10:44
Same issue here. When running Storybook all the enums stop working, when you rename the enum and rebuild it works...

**Comment by Crylion** [comment] 2022-11-28 15:14
I agree, it's really not great having the enums not working.
We use enums a lot in our templates to avoid just using arbitrary string values. And for the actual angular applications, that never posed any problem.

**Comment by secheverryl** [comment] 2022-12-20 16:30
This needs fixing not only enums are not working but binding formControl has the same issue!.

please fix as soon as possible. !urgent

**Comment by FrancoisTurpinLeocare** [comment] 2023-02-13 11:45
Same for me. I notice that it's work's fine until documentation.json was regenerated, from that controls of enum not working anymore...

Can't use storybook in my angular project without this...

**Comment by FrancoisTurpinLeocare** [comment] 2023-02-13 15:00
@valentinpalkovic I link a screenshot of my package.json
<img width="363" alt="Capture d’écran 2023-02-13 à 15 58 47" src="https://user-images.githubusercontent.com/125270003/218493211-1f7cd76e-00e4-438d-a61e-ab1d2bf97911.png">

**Comment by valentinpalkovic** [comment] 2023-02-13 15:04
Thank you @FrancoisTurpinLeocare. In Storybook 7.0 (currently in beta) we did a lot of improvements also related to Angular. Please check it out and let me know, if the issue still exists for you. Please read the [migration guide](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md) and upgrade today if you want

```
npx storybook@next upgrade --prerelease
```

**Comment by shilman** [comment] 2023-02-14 07:30
Removing this from the 7.0 burndown until we have a 7.0 reproduction

**Comment by valentinpalkovic** [comment] 2023-05-03 12:09
Closing the issue because I cannot reproduce it in Storybook 7.0.x

**Closed by valentinpalkovic** 2023-05-03 12:09 UTC
Labels: bug, needs reproduction, angular
