### ISSUE TITLE
Sidebar subheadings unexpectedly appearing 

### ISSUE THREAD

**Issue by astrotim** [storybookjs/storybook#11692] opened 2020-07-26 11:36 UTC
Since upgrading from `v6-beta` to `v6-rc`, we've noticed that some stories are getting the [non-expandable groupings in the sidebar](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#removed-hierarchy-separators) while others aren’t, and I can’t see any difference in how they are implemented.

For example our MDX page for Button appears in a folder in alphabetical order. 

<img width="169" alt="docs-button" src="https://user-images.githubusercontent.com/2671362/88477523-0d0fe680-cf84-11ea-94b8-3696ca5e07e4.png">

It is marked up with the Meta component

```js
// Button.stories.mdx
<Meta title="Button/Docs" />
```

while our MDX page for List appears with a subheading, at the end of the alphabetical list. It is marked up the same

<img width="175" alt="docs-list" src="https://user-images.githubusercontent.com/2671362/88477524-0ed9aa00-cf84-11ea-8d58-c8a3c4deb5e1.png">

```js
// List.stories.mdx
<Meta title="List/Docs" />
```

The configuration of these two components is very similar. 

```js
// Button.js
export default Button
```

```js
// Button.story.js
export default {
  title: 'Button',
}
```

```js
// List.js
export default List
```

```js
// List.story.js
export default {
  title: 'List',
}
```

Note: we use `ComponentName.stories.mdx` and `ComponentName.story.js` simply to make the MDX appear before the CSF in the navigation order.

**To Reproduce**
We don't have any public-facing URLs to share unfortunately, but the Storybook admins may have access to view our Chromatic builds. There are also some illustrative screenshots below.

[Chromatic build using v6-rc](https://5c6e26425cd0f000248f636b-riqzbsbgqo.chromatic.com/?path=/story/intro--storybook) which demonstrates the appearance of 6 subheadings below the main alphabetically ordered story list.

**Expected behavior**
I expected not to see subheadings since there were no code changes related to opting in to this appearance.

[Chromatic build using v6-beta](https://5c6e26425cd0f000248f636b-hyonktiimn.chromatic.com/?path=/story/intro--storybook) which shows the same 6 components folders in alphabetical order without any sub headings.

**Screenshots**

After: v6-rc.3 (sub headings appearing - screenshot simplifed for brevity)
<img width="165" alt="stories-order" src="https://user-images.githubusercontent.com/2671362/88477819-7e509900-cf86-11ea-8eb4-e0e46541aefb.png">

Before: v6-beta (no subheadings - screenshot simplifed for brevity)
<img width="192" alt="story-order-v6-beta" src="https://user-images.githubusercontent.com/2671362/88477823-81e42000-cf86-11ea-975d-7f4f53a153de.png">

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
_Results of `npx -p @storybook/cli@next sb info`_ - TBD

Packages installed:

```json
"@storybook/addon-actions": "6.0.0-rc.3",
"@storybook/addon-backgrounds": "6.0.0-rc.3",
"@storybook/addon-controls": "6.0.0-rc.3",
"@storybook/addon-docs": "6.0.0-rc.3",
"@storybook/addon-knobs": "6.0.0-rc.3",
"@storybook/addon-viewport": "6.0.0-rc.3",
"@storybook/addons": "6.0.0-rc.3",
"@storybook/react": "6.0.0-rc.3",
```

**Additional context**
We have worked around this for now by disabling the subheadings via:

```js
addons.setConfig({
  showRoots: false
});
```

But we would like to evolve towards using the subheadings, so it would be great to understand why and how to use them properly.

**Comment by ndelangen** [comment] 2020-08-03 09:59
@astrotim Do you think you could help me reproduce this?

I'm sure there's a bug / unwanted feature in there, but in our official storybook example (which does use a combination of storieOf, MDX, CSF)

Do you have any pointers to what you think might be the cause of this?

**Comment by astrotim** [comment] 2020-08-05 11:08
@ndelangen I haven't been able to spot any clues on this one, but I'll try reproducing it on a branch in the Storybook example and see how that goes.

**Comment by ndelangen** [comment] 2020-08-17 09:31
Thanks @astrotim 👍

**Comment by doublejosh** [comment] 2020-10-15 22:03
I've was stumped by the subheading logic as well. Seems to only appear when components are put into a folder with no root component/story, or the story path root has no component/story.

**Comment by shilman** [comment] 2020-11-04 02:25
Can you try upgrading to 6.1 and see if it's fixed with the new sidebar?

```
npx sb upgrade --prerelease
```

**Comment by astrotim** [comment] 2020-11-04 02:56
OK, will do!

**Comment by doublejosh** [comment] 2021-01-05 23:35
Here's the docs on "roots"...
https://storybook.js.org/docs/react/configure/sidebar-and-urls#roots

**Comment by shilman** [comment] 2021-02-26 20:57
Closing this for now. Please let me know if there's more to be done here!

**Closed by shilman** 2021-02-26 20:57 UTC
Labels: PN, bug, needs reproduction, ui
