### ISSUE TITLE
Story decorators are not working properly  after 6.2

### ISSUE THREAD

**Issue by mauroencinas** [storybookjs/storybook#14608] opened 2021-04-15 00:22 UTC
**Describe the bug**
- When using another component as a story decorator, the controls stop working completely (this did not happen before 2.6) 
![controls-not-working](https://user-images.githubusercontent.com/32255583/114922379-319d3e80-9df1-11eb-8dd2-bac8dd50f9a5.gif)

- When using Div or another html element as a decorator and when using the controls, the component changes state abruptly and you cannot see a smooth transition (this did not happen before 2.6) 
![controls-change-abruptly](https://user-images.githubusercontent.com/32255583/114922406-382bb600-9df1-11eb-8ef9-bb29e29b380b.gif)

- Everything works fine and I can see smooth transitions when not using story decorators 
![controls-ok](https://user-images.githubusercontent.com/32255583/114922325-24804f80-9df1-11eb-9e9e-9239aed85356.gif)
**To Reproduce**

1. Create a story
2. Import and use a component as a decorator or html element, in my case I discovered this using layout components (to dynamically create sections and columns)
3. Try to manipulate the component controls 

**Expected behavior**
A clear and smooth transition between controls, as always.

**Code snippets**
```javascript

//This story have a hard transition between states
import React from 'react'
import { Story, Meta } from '@storybook/react'
import QoriLogo, { Props } from './logo'

export default {
	title: 'Qori/Logo',
	component: QoriLogo,
	argTypes: {
		status:{
			description:"Choose the status of animation",
			table: {
				type: { summary: 'loading | offline' },
				defaultValue: { summary: 'loading' },
			},
			control: {type: 'radio'},
			options: [
					'loading', 
					'offline',
			]
		}
	},
	decorators: [
		(Story) => (
			<div style={{margin:"3rem"}}>
				<Story />
			</div>
		),
	]
} as Meta

const Template: Story<Props> = args => (
		<QoriLogo {...args} />
)

export const Default = Template.bind({})
Default.args = {
    status:'loading'
}
```

```javascript
//This story does not change state after manipulating the controls , broke controls
import React from 'react'
import { Story, Meta } from '@storybook/react'
import QoriLogo, { Props } from './logo'

import Section from '../layout/section'

export default {
	title: 'Qori/Logo',
	component: QoriLogo,
	argTypes: {
		status:{
			description:"Choose the status of animation",
			table: {
				type: { summary: 'loading | offline' },
				defaultValue: { summary: 'loading' },
			},
			control: {type: 'radio'},
			options: [
					'loading', 
					'offline',
			]
		}
	},
	decorators: [
		(Story) => (
			<Section>
				<Story />
			</Section>
		),
	]
} as Meta

const Template: Story<Props> = args => (
		<QoriLogo {...args} />
)

export const Default = Template.bind({})
Default.args = {
    status:'loading'
}




```

**System**
Environment Info:

  System:
    OS: Linux 5.8 Alpine Linux
    CPU: (2) x64 AMD A4-3310MX APU with Radeon(tm) HD Graphics
  Binaries:
    Node: 14.3.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  npmPackages:
    @storybook/addon-essentials: ^6.2.8 => 6.2.8 
    @storybook/react: ^6.2.8 => 6.2.8 
    @storybook/theming: ^6.2.8 => 6.2.8 

**Additional context**
Maybe, I'm missing something? **THANKS FOR EVERYTHING**

**Comment by shilman** [comment] 2021-04-15 01:25
@mauroencinas do you mean 6.2? what version are you upgrading from?

**Comment by mauroencinas** [comment] 2021-04-15 01:43
@shilman , thanks  , yes, I mean 6.2, I'm upgrading from:

 "@storybook/addon-essentials": "^6.0.25",
 "@storybook/addons": "^6.0.25",
 "@storybook/react": "^6.1.21",
 "@storybook/theming": "^6.0.21",

**Comment by shilman** [comment] 2021-04-15 01:55
i think it might be fixed by https://github.com/storybookjs/storybook/pull/13049

**Comment by mauroencinas** [comment] 2021-04-15 18:51
Thank you very much again, I have uploaded screenshots to illustrate the problems, while reviewing the information you shared with me

**Comment by shilman** [comment] 2023-06-08 02:46
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

**Closed by shilman** 2023-06-08 02:46 UTC
Labels: question / support, react
