### ISSUE TITLE
[Bug]: In Next project with the experimental-nextjs-vite we need to install @storybook/core in the user's package

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#29798] opened 2024-12-04 08:21 UTC
### Describe the bug

Reproduction: https://github.com/storybookjs/storybook-rsc-demo/

Upgrade using:

```
npx storybook@next upgrade
```

You will get the error:

```
4:17:54 PM [vite] Pre-transform error: Failed to resolve import "@storybook/core/preview/runtime" from "/virtual:/@storybook/builder-vite/vite-app.js". Does the file exist?
  Plugin: vite:import-analysis
  File: /virtual:/@storybook/builder-vite/vite-app.js:1:24
  1  |  import { setup } from '@storybook/core/preview/runtime';
     |                         ^
  2  |    import '/virtual:/@storybook/builder-vite/setup-addons.js';
  3  |  
4:17:54 PM [vite] Internal server error: Failed to resolve import "@storybook/core/preview/runtime" from "/virtual:/@storybook/builder-vite/vite-app.js". Does the file exist?
  Plugin: vite:import-analysis
```

Installing `@storybook/core` in `package.json` fixes the problem, but we shouldn't have to do that.

### Reproduction link

N/A

### System

```bash
any?
```

**Comment by JReinhold** [comment] 2024-12-04 09:31
This happens because of the faulty change from `storybook/internal` to `@storybook/core` here: https://github.com/storybookjs/storybook/pull/29172/files#diff-1dccfe4dfb3f001d9d6a83bd9f73476be42896870722a32c1c56cc54ac1c9ae9R70

It happens in all Vite-based sandboxes that uses **pnpm** because of it's stricter dependency system - probably also happens in Yarn PnP as well. Basically the user's project depends on `storybook`, not `@storybook/core`, so it can't import from it in a strict environment. So it's not related to `experimental-nextjs-vite`.

I've confirmed that this doesn't happen in `alpha.15`, https://github.com/storybookjs/storybook/pull/29172 was released in `alpha.16`.

**Closed** 2024-12-04 10:11 UTC
Labels: bug, nextjs, builder-vite, addon: test
