### ISSUE TITLE
Addon-docs: can't set link with absolute path.

### ISSUE THREAD

**Issue by ezhikov** [storybookjs/storybook#9005] opened 2019-11-29 08:22 UTC
**Describe the bug**
When I try add link to some external page, either with markdown or anchor element, this URL automatically added to `path` parameter instead. On other hand, if I add URL without leading slash, it works as expected - as relative link.

**To Reproduce**
1. Create new or open existing `.mdx` doc.
1. Add link to some external page, e.g. `/example/`:
    ```md
    [absolute example](/example/)
    [relative example](example/)
    ```
1. Go to this page in started or builded storybook
1. First link points to `?path=/example/`, and second points to `%storybook_path%/example`

**Expected behavior**
1. Both links should work similarly. Either point to pages inside storybook, or to external pages
2. There should be clear way to add links to other parts within same domain.

**Screenshots**
![code](https://user-images.githubusercontent.com/4413493/69854164-71659380-1299-11ea-9d94-23eeac718e7f.png)
![rendered result](https://user-images.githubusercontent.com/4413493/69854256-b2f63e80-1299-11ea-96f0-2b78e82e22ae.png)

**Code snippets**
```mdx
[absolute example](/example/)
<a href="/example">absolute example</a>
[relative example](example/)
<a href="example">relative example</a>
```

**System:**
```
$ npx -p @storybook/cli@next sb info

Environment Info:

  System:
    OS: Linux 4.19 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 10.16.3 - ~/.nodenv/versions/10/bin/node
    Yarn: 1.19.1 - /usr/bin/yarn
    npm: 6.9.0 - ~/.nodenv/versions/10/bin/npm
  npmPackages:
    @storybook/addon-a11y: ^5.3.0-beta.10 => 5.3.0-beta.10
    @storybook/addon-docs: ^5.3.0-beta.10 => 5.3.0-beta.10
    @storybook/preset-typescript: ^1.1.0 => 1.1.0
    @storybook/react: ^5.3.0-beta.10 => 5.3.0-beta.10
```

**Comment by ezhikov** [comment] 2019-12-20 10:31
Hi. This issue still bugging me, but I don't have time at the moment to look at it myself. I believe in a week or two I'll be able to give it a shot.

**Comment by jorenbroekema** [comment] 2019-12-20 11:00
I think I have the same issue. 
In .mdx I got the following: `[bug in axios](https://github.com/axios/axios/issues/385)`

and it turns into: `<a href="http://localhost:9002https://github.com/axios/axios/issues/385" class="sbdocs sbdocs-a css-1cvpre6">bug in axios</a>`

**Comment by jorenbroekema** [comment] 2020-01-09 10:16
Any idea if this will get fixed for 5.3.0? Can I help somehow? If so, please point me in the direction if you guys know where the source of the issue may be. Is it in MDX to JS or in addon-docs?

It's quite important for our documentation to be able to link to external pages..

**Comment by shilman** [comment] 2020-01-09 13:46
@jorenbroekema I'm working on some linking related stuff now and will fold this in (if it's not already fixed -- it might be). Thanks for the nudge!

**Comment by chris-dura** [comment] 2020-11-23 22:35
Stumbled across this issue again, I'm sure there's a fix coming, but wanted to post the only workaround I have found for my set up, in case it helps someone else...
I basically had to use pure HTML instead of the Markdown syntax, and use `target="_blank"` :/

```mdx
import { Meta } from '@storybook/addon-docs/blocks';

<Meta title="Get Started/Introduction"/>

<!-- doesn't work -->
See our [live demo](/demo/).

<!-- sorta works -->
See our <a href="../demo/" target="_blank">live demo</a>.
```

**Comment by stefan-schweiger** [comment] 2021-07-02 12:10
Can we still expect this issue to get fixed? It's pretty annoying if you try to link to external documentation

**Comment by shilman** [comment] 2021-07-02 14:45
@stefan-schweiger Do you have a fix for this issue? PRs very welcome!

**Comment by stefan-schweiger** [comment] 2021-07-02 14:57
@shilman any pointers where this functionality is located in the code?

Btw the mentioned workaround with the anchor-tag only works for external URL like `https://github.com` but not for absolute URL like `/myapp/profile` this still gets converted to `http://<storybook url>/iframe.html?path=/myapp/profile`

**Comment by shilman** [comment] 2021-07-02 15:03
Not 100% sure but I'd check here first:

https://github.com/storybookjs/storybook/blob/next/addons/docs/src/blocks/mdx.tsx#L52

**Comment by stefan-schweiger** [comment] 2021-07-02 16:12
@shilman ok I've identified where this is happening, it's actually at this line where absolute links get identified as "storybookPinks" https://github.com/storybookjs/storybook/blob/643e7eb011a880e2b4b8d82ad360752aa9461dd6/lib/components/src/typography/DocumentFormatting.tsx#L74

Since this only matches absolute links I'm not 100% why this is done and if this is done on purpose. Do you maybe have any insight on this?

**Comment by stefan-schweiger** [comment] 2021-07-02 16:22
The mdx example has the following kinds of links:

```
[external link](https://hichroma.com)
[external link with title](https://hichroma.com 'Insert title!')
[link to in page anchor](#h1-heading)
[link to another story (docs)](?path=/docs/addons-docs-docs-only--page)
[link to another story (canvas)](?path=/story/addons-docs-buttongroup--basic)
[link to about page](?path=/settings/about)
[link to absolute local url](/absolute)
```

Except the absolute link none of those should be affected if we would remove the code mentioned before. And the absolute links would finally work correctly.

But this could still mean breaking changes if somebody relied on the "incorrect" implementation for absolute urls (even though I can't think of a use case for this right now).

**Comment by reno1979** [comment] 2021-07-09 08:08
Same problem here, then link inside our markdown file ` (typography)[?path=/story/foundation-typography--page]` 
will result in `http://localhost/iframe.html?path=/story/foundation-typography--page`

**Comment by stefan-schweiger** [comment] 2021-07-09 08:17
@reno1979 this shouldn't matter because as long as it stats with `?path=` storybook/the iframe will resolve it internally. Those kind of links work for me without a problem (test them in the examples).

**Comment by reno1979** [comment] 2021-07-09 08:31
@stefan-schweiger  For us the created links do not work. 

Removing the iframe.html part from the url is a valid path that works. 

Where are working with storybook 6.2.9

**Comment by stefan-schweiger** [comment] 2021-07-09 08:45
@reno1979 do the links in this example work for you? https://storybookjs.netlify.app/official-storybook/?path=/story/addons-docs-markdown-docs--page

**Comment by reno1979** [comment] 2021-07-09 08:53
@stefan-schweiger  The example works. Our Storybook opens the story as if its a single page (no storybook logo, menu etc) 
And the url ends with &viewMode=story

Perhaps a configuration I should change.

**Comment by reno1979** [comment] 2021-07-09 09:05
ok this is what happens: 

`[Typography](?path=/story/foundation-typography--page)`

becomes: 

`http://localhost/iframe.html?path=/story/foundation-typography--page`

and after loading the link, the new url is: 

`http://localhost/iframe.html?id=foundation-typography--page&viewMode=story`

**Comment by alee8** [comment] 2022-01-12 05:05
I am curious about the status of this issue.  Are there plans to address this?
I am running 6.4.12 and still annoyed that the only way is to right-click the link so that I can open it in another tab.  Not something our users naturally think of doing.

**Comment by archfisv** [comment] 2022-03-23 08:56
Same after bumping to 6.5.0-alpha.49

**Comment by rolaru** [comment] 2022-03-30 10:01
Tried with Storybook 6.5.0-alpha.50 and this issue still reproduces. It's quite challenging because we have to write links in .mdx files using HTML syntax and character escaping for them to work properly (e.g.: `<a target="_blank" href="https://www.somelink.com">https&#58;//www&#46;somelink.com</a>`).

**Comment by archasek** [comment] 2022-03-30 10:02
It's also a problem for me. I had to refactor all links, as they stopped working.

**Comment by shilman** [comment] 2023-06-08 04:14
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

**Closed by shilman** 2023-06-08 04:14 UTC
Labels: bug, has workaround, todo, addon: docs
