### ISSUE TITLE
Can't register <font-awesome-icon> as a Vue component in Storybook

### ISSUE THREAD

**Issue by RCVarley** [storybookjs/storybook#12432] opened 2020-09-09 14:15 UTC
**Describe the bug**
In my project I use the `<font-awesome-icon>` (from `@fortawesome/vue-fontawesome`) element to load icons on the vue front end.  Unfortunately, this doesn't work in my stories.  Instead I get the following error:

```
[Vue warn]: Unknown custom element: <font-awesome-icon> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <GridItemPlaceholder> at src/components/GridItemPlaceholder.vue
       <Anonymous>
         <Root>
```

Does anyone know how to run `library.add(fasPlusSquare, farPlusSquare)` and `Vue.component('font-awesome-icon', FontAwesomeIcon)` in a way that they apply to the Storybook environment?

**To Reproduce**
generally:
1. `vue create app-name`
2. `vue add storybook`
3. `npm i @fortawesome/fontawesome-svg-core`
4. `npm i @fortawesome/free-regular-svg-icons`
5. `npm i @fortawesome/free-solid-svg-icons`
6. `npm i @fortawesome/vue-fontawesome`
7. Register the `font-awesome-icon` component in `main.js`
8. Add any icons to the library in `main.js`
9. Use `font-awesome-icon` in a component

In my repo (https://github.com/RCVarley/Storybook-fontawesome-vue-Issue):
1. npm run serve
2. Go to `localhost:8080` and see that the icons are showing
3. npm run storybook:serve
4. Go to `localhost:6006`
5. Open the GridItemPlaceholder story and see that the icons are missing

**Expected behavior**
The fontawesome icons should show up in the front end, same as the back end.

**Screenshots**
`localhost:8080` (lol at my lack of styling)
![image](https://user-images.githubusercontent.com/20630026/92607901-a4b76300-f2ac-11ea-956f-d203f7b77781.png)

`localhost:6006`
![image](https://user-images.githubusercontent.com/20630026/92608068-cd3f5d00-f2ac-11ea-955e-9c2edf38dd1f.png)

**Code snippets**
**My example repo**: https://github.com/RCVarley/Storybook-fontawesome-vue-Issue

Added the component and populated the library globally in `main.js`.
```
import Vue from 'vue';
import { library } from '@fortawesome/fontawesome-svg-core';
import { faPlusSquare as fasPlusSquare } from '@fortawesome/free-solid-svg-icons';
import { faPlusSquare as farPlusSquare } from '@fortawesome/free-regular-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import App from './App.vue';

library.add(fasPlusSquare, farPlusSquare);

Vue.component('font-awesome-icon', FontAwesomeIcon);
...
```

Then I added I used the `<font-awesome-icon>` component in `GridItemPlaceholder.vue`.
```
<font-awesome-icon
  v-if="hover === true"
  :icon="['fas', 'plus-square']">
</font-awesome-icon>
<font-awesome-icon
  v-else
  :icon="['far', 'plus-square']">
</font-awesome-icon>
```

**System:**
```
Environment Info:
  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  Binaries:
    Node: 14.8.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 85.0.4183.83
    Edge: Spartan (44.19041.423.0), Chromium (85.0.564.44)
  npmPackages:
    @storybook/addon-actions: >=6.0.21 => 6.0.21
    @storybook/addon-backgrounds: ^6.0.21 => 6.0.21
    @storybook/addon-docs: >=6.0.21 => 6.0.21
    @storybook/addon-essentials: ^6.0.21 => 6.0.21
    @storybook/addon-knobs: >=6.0.21 => 6.0.21
    @storybook/addon-links: >=6.0.21 => 6.0.21
    @storybook/vue: >=6.0.21 => 6.0.21
```

**Additional context**
I've also asked for assistance on https://github.com/FortAwesome/vue-fontawesome/issues/254, in case anyone there has figured this one out.

**Comment by rochabianca** [comment] 2020-09-11 18:19
same problem here with Bootstrap Vue. I just can't find a way to import global components and libraries into storybook

**Comment by iHearty** [comment] 2020-09-22 06:05
This problem trouble me also, i need to add global components to Vue, and tried to use Vue.use(xxx) in main.js, preview.js, not working~

**Comment by johnwebbcole** [comment] 2020-10-27 12:14
Has anyone had any luck with this?  I have a few libraries that `Vue.use` and I'm a little confused as to how to accomplish this.  Some are putting that code in `main.js` others in `preview.js`, neither of which works for me.

**Comment by mlukasz7** [comment] 2020-10-29 10:13
You can add FontAwesome and setup it with Vue in `App.vue` file. In `.storybook/preview.js` import App component and by this you can use FontAwesome in Storybook :)

**Comment by jonalexander** [comment] 2021-01-08 22:01
@mlukasz7 can you provide an example? thank you.

**Comment by mlukasz7** [comment] 2021-01-10 13:59
@jonalexander First import FontAwesome in `App.vue` [example](https://github.com/mlukasz7/vue-poke-info/blob/master/src/App.vue) and later import App component in `.storybook/preview.js` file [example](https://github.com/mlukasz7/vue-poke-info/blob/master/.storybook/preview.js) 

You can check in my repo from example links, there FontAwesome works with storybook :)

**Comment by Joe-Moran** [comment] 2021-02-24 20:08
Hey! Just had to figure this out myself. I added the following code to my `.storybook/preview.js` file:
``` js
import Vue from 'vue';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
Vue.component('font-awesome-icon', FontAwesomeIcon);
```

**Comment by jonalexander** [comment] 2021-02-24 20:09
@Joe-Moran @mlukasz7 This is also what I ended up doing and it worked for me.

**Comment by davpascoal** [comment] 2021-03-17 22:33
@Joe-Moran Do you know how does it work for Vue3? 
Tried the following and it didn't work.
`createApp().component('font-awesome-icon')`

**Comment by iKnowMagic** [comment] 2021-04-13 22:35
```
Vue 3:
import {app} from '@storybook/vue3';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
app.component('font-awesome-icon', FontAwesomeIcon);
```

@davpascoal

**Comment by jonniebigodes** [comment] 2022-02-07 16:04
Closing this issue as the documentation is adjusted to include examples and explain what needs to change in terms of configuration.

Let us know if the issue is still present, and I'll gladly re-open it. We can continue to work on this and update the documentation based on the findings.

Stay safe

**Closed by jonniebigodes** 2022-02-07 16:04 UTC
Labels: question / support, compatibility with other tools, app: vue

**Comment by Twoody** [comment] 2023-05-09 05:45
@jonniebigodes  I have everything up and running with storybook _besides_ Font Awesome not loading. I do believe this is solvable from the readme/docs _somewhere_ .... For those who land here in the future, it will be helpful to have a link or "answer". I am currently feeling stuck, while picking apart the documentation.

**Comment by Twoody** [comment] 2023-05-09 05:56
storybook `7.0.2` has API changes. Current work around is the following:

```
import { setup } from '@storybook/vue3'                                       // Use to be app

import { faStar } from "@fortawesome/free-solid-svg-icons"
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome"
import { library } from "@fortawesome/fontawesome-svg-core"

// Font awesome
library.add(faStar)
...

/** THE MAIN CHANGE */
setup((app) => {
  app.component('font-awesome-icon', FontAwesomeIcon);
})
```
