### ISSUE TITLE
[Feature Request]: Make ServerChannelURL configurable 🙏

### ISSUE THREAD

**Issue by keoz-did** [storybookjs/storybook#21386] opened 2023-03-03 15:22 UTC
### Is your feature request related to a problem? Please describe

Problem: 
Added ddev config to our storybook 6.5 / Vue 3 Project and can't get Websocket connection because it's hardcoded to `localhost`.

### Describe the solution you'd like

It would be awesome if we can configure the ServerChannelURL for WS/WSS.

### Are you able to assist to bring the feature to reality?

no

**Comment by bordeo** [comment] 2023-03-09 15:51
Duplicate of #20068

**Closed** 2023-03-10 06:23 UTC
Labels: feature request, duplicate, needs triage
