### ISSUE TITLE
Upgrade Storybook manager to React 18

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#20378] opened 2022-12-22 10:56 UTC
### Is your feature request related to a problem? Please describe

Storybook's own "manager UI" is currently using React 16, which is not the latest.

### Describe the solution you'd like

 We should upgrade to React 18 and do the minimum to get the UI working again.

Note that this means that addons "manager entries" will also run in React 18, so it's a breaking change that will affect our addon ecosystem.

After the upgrade we should re-enable React strict mode, reversing https://github.com/storybookjs/storybook/pull/20345

Also, when upgrading we should upgrade the addon API to support the most recent React 18 hooks, as described in https://github.com/storybookjs/storybook/issues/21034

### Are you able to assist to bring the feature to reality?

no

**Comment by thebuilder** [comment] 2022-12-22 16:06
You should be able to revert #20345 when #20368 is merged.

**Comment by eddilou** [comment] 2022-12-23 10:29
It would also be nice to update all dependencies.

**Comment by dohooo** [comment] 2022-12-26 04:54
Oh, Can not wait more. 🤯

**Comment by shogohida** [comment] 2022-12-27 02:34
Hi @shilman can I work on this?

**Comment by shilman** [comment] 2022-12-27 02:36
@shogohida That would be amazing! 🙏  Please check out [how to contribute](https://storybook.js.org/docs/7.0/react/contribute/how-to-contribute) in our docs and feel free to ask questions in `#contributing` in [our Discord](https://discord.gg/storybook).

**Comment by shogohida** [comment] 2022-12-27 02:44
@shilman 
Thanks for your comment! I will need some help since this is the first issue of Storybook for me to deal with. I will ask questions in Discord when I need help

**Comment by shogohida** [comment] 2023-01-12 23:17
Hi @macck7, I'm still working on this issue even though it's taking time 🙏

**Comment by iamkelv** [comment] 2023-01-25 15:40
hi, @shilman , I think if the React version is to be upgraded t Ract 18  then some of the packages may also need an update else react18 may not be compatible with some older packages. 

or if the issue is only focused on Upgrade then I will like to work on it.

**Comment by BradMcGonigle** [comment] 2023-03-23 15:12
Related to https://github.com/storybookjs/storybook/issues/21034, is there a known workaround for using new React 18 hooks like `useId` in components (which we have stories for)?

I understand not being able to use the new hooks in addons but should this prevent something like `useId` from being used in our React 18 compatible component library?

**Comment by agriffis** [comment] 2023-03-24 13:26
> I understand not being able to use the new hooks in addons but should this prevent something like `useId` from being used in our React 18 compatible component library?

This shouldn't be a problem. (I do it all the time.) I suggest opening a separate issue if it's not working for you.

**Comment by vanessayuenn** [comment] 2023-12-11 13:24
Closed by #24514

**Closed by vanessayuenn** 2023-12-11 13:24 UTC
Labels: ui, maintenance
