### ISSUE TITLE
[Feature Request]: @storybook/angular-vite

### ISSUE THREAD

**Issue by nstuyvesant** [storybookjs/storybook#23062] opened 2023-06-14 04:09 UTC
### Is your feature request related to a problem? Please describe

The package @angular-devkit/build-angular 16 and up includes vite and esbuild-wasm. Is there a plan to have a @storybook/angular-vite like the other frameworks? Would love to have a consistent builder across all the frameworks I am using.

### Describe the solution you'd like

Ability to use vite instead of webpack for Angular Storybook.

### Are you able to assist to bring the feature to reality?

no

**Comment by valentinpalkovic** [comment] 2023-06-16 09:03
Duplicate of https://github.com/storybookjs/storybook/issues/22544

**Closed by valentinpalkovic** 2023-06-16 09:03 UTC
Labels: feature request, needs triage
