### ISSUE TITLE
[6.2.7] Cannot create a Story without a component set in export default

### ISSUE THREAD

**Issue by kanidjar** [storybookjs/storybook#14575] opened 2021-04-13 09:13 UTC
**Describe the bug**

An error is thrown when trying to display a story not having a component set in "export default".

![](https://user-images.githubusercontent.com/12607242/114527573-6de16b00-9c48-11eb-932e-55bb95720d02.png)

**To Reproduce**

```javascript
import { Meta, Story } from '@storybook/angular';

export default {
    title: 'HTML Elements/Buttons'
} as Meta;

export const Base: Story = args => ({
    props: args,
    template: '<button>{{content}}</button>'
});

Base.args = {
    content: 'Primary button'
};

```

**Expected behavior**

The HTML element "button" should appear on the page without any error.

**System**

```bash
  System:
    OS: macOS 11.0.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Chrome: 89.0.4389.114
    Safari: 14.0.1
  npmPackages:
    @storybook/addon-essentials: ^6.2.1 => 6.2.7 
    @storybook/angular: ^6.2.1 => 6.2.7 
```

**Workaround**

Pass any component in "export default"

![](https://user-images.githubusercontent.com/12607242/114528307-2f987b80-9c49-11eb-93b4-d8065d2a0952.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231368/1200188831650109) by [Unito](https://www.unito.io/learn-more)

**Comment by shilman** [comment] 2021-04-13 11:51
@ThibaudAV is this required now? I think we are supporting the old format until 7.0?

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-angular-story-component

**Comment by ThibaudAV** [comment] 2021-04-13 12:18
normally not 🤔  yes that's what the code should do, I'll go look

**Comment by ThibaudAV** [comment] 2021-04-13 12:27
🤔  I just tested with 6.2.7. and the example code I have no error :sad:

@kanidjar can you give a repo with the error reproduction?

**Comment by kanidjar** [comment] 2021-04-13 13:33
sure @ThibaudAV , you will get it by the end of the day

**Comment by kanidjar** [comment] 2021-04-13 15:33
@ThibaudAV : https://github.com/kanidjar/storybook 

You will find the example story in apps/extranet/src/app

```bash
nx run extranet:storybook
```

**Comment by ThibaudAV** [comment] 2021-04-13 19:06
Perfect it reproduces well the problem

Well it seems to be linked to `ngcc` if not executed it works perfectly ^^
Storybook does not use ivy yet but should be compatible with a workspace using it

It will be necessary to add this change earlier than expected
https://github.com/storybookjs/storybook/pull/11157/files#diff-70601b7629ca05a548de90f4bd456a56cbd6494c5bb3028f0942267ba1a8167fR45

@shilman I'll propose a PR and check that it fixes the bug

**Comment by shilman** [comment] 2021-04-14 02:32
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.7 containing PR #14586 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2021-04-14 02:32 UTC
Labels: P1, app: angular, bug, needs reproduction

**Comment by shilman** [comment] 2021-04-23 03:19
Hurrah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.9 containing PR #14586 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```
