### ISSUE TITLE
Latest `@mdx-js/mdx` breaks `@storybook/addon-docs`

### ISSUE THREAD

**Issue by dustinsavery** [storybookjs/storybook#11589] opened 2020-07-16 22:46 UTC
**Describe the bug**
`@mdx-js/mdx` released version `1.6.8` today, which has a [breaking change](https://github.com/mdx-js/mdx/pull/1126) as part of a patch version 🤦 

**To Reproduce**
1. Fresh install of packages, start storybook

**Expected behavior**
Storybook should launch with no errors

**Screenshots**
![image](https://user-images.githubusercontent.com/2447456/87729882-39a15280-c77b-11ea-8795-3e379c4f2f51.png)

**System:**
Environment Info:

  System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
    Yarn: 1.22.4 - ~/src/kaizen-ui/node_modules/.bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v14.4.0/bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Safari: 13.1.1
  npmPackages:
    @storybook/addon-actions: 5.3.15 => 5.3.15 
    @storybook/addon-docs: 5.3.15 => 5.3.15 
    @storybook/addon-info: 5.3.15 => 5.3.15 
    @storybook/addon-knobs: 5.3.15 => 5.3.15 
    @storybook/addon-links: 5.3.15 => 5.3.15 
    @storybook/addon-storyshots: 5.3.15 => 5.3.15 
    @storybook/addon-storyshots-puppeteer: 5.3.15 => 5.3.15 
    @storybook/addon-storysource: 5.3.15 => 5.3.15 
    @storybook/addons: 5.3.15 => 5.3.15 
    @storybook/react: 5.3.15 => 5.3.15 

**Additional context**
Temporarily, I would recommend pinning the version of `@mdx-js/mdx` to `1.6.7` (confirmed this version works), or if the fix isn't too intense, patching it.

**Comment by alvarezmario** [comment] 2020-07-16 23:00
I'm getting the same error. Luckily I found this issue confirming it, because I'm currently learning storybook (awesome project) and using the docs addon was getting crazy with this error. 😄

**Comment by alvarezmario** [comment] 2020-07-16 23:01
They reported an issue as well: https://github.com/mdx-js/mdx/issues/1153

**Comment by dustinsavery** [comment] 2020-07-16 23:21
Tested on `1.6.9` that they pushed to patch, doesn't seem to fix it.

**Comment by squarebraket** [comment] 2020-07-17 01:21
I'm having the same issue. 

`TypeError: Cannot read property 'path' of undefined`

I'm trying to use `addon-docs` to write our documentation but can't move forward until this is resolved.

**Comment by shilman** [comment] 2020-07-17 01:58
@squarebraket can you pin the MDX dependency to an older version until this gets resolved?

**Comment by squarebraket** [comment] 2020-07-17 02:58
@shilman I'll try to do that. I looked thru the dependencies for `@storubook/addon-docs` and the `package.json` for this lib reports the following:
` 
    "@mdx-js/loader": "^1.5.1",
    "@mdx-js/mdx": "^1.5.1",
    "@mdx-js/react": "^1.5.1",
`
I'm not sure why it doesn't work given the fact that it's an older version.

I also try installing (in my project)@mdx-js/mdx@1.6.10, which is the version that suppose to fix the issue but that didn't work either.

**Comment by dustinsavery** [comment] 2020-07-17 03:49
@squarebraket It's semver. `^1.5.1` (specifically the `^`) means anything short of `2.0.0` will automatically install the latest.

**Comment by squarebraket** [comment] 2020-07-17 05:13
Yep, you’re right, I missed the “^” altogether.


Pedro

**Comment by squarebraket** [comment] 2020-07-17 13:16
I was able to make it work by "pinning" `@mdx-js/mdx` to version 1.5.1. @shilman thanks for the suggestion

**Comment by pvds** [comment] 2020-07-17 13:53
`@mds-js/mdx` just released [version `1.6.11`](https://github.com/mdx-js/mdx/tree/v1.6.11) to [fix the breaking change](https://github.com/mdx-js/mdx/issues/1153#issuecomment-660108205).

Just tested it my `5.3.19` Storybook install and I can confirm the issue is resolved!

**Comment by pvds** [comment] 2020-07-17 13:56
@silvenon does mention that [`toJSX` is (currently) internal API](https://github.com/mdx-js/mdx/issues/1153#issuecomment-660117384)

**Comment by shilman** [comment] 2020-07-17 14:09
Thanks @pvds!! 🙏  Closing this and plan to update the Storybook side when MDX 2.0 is released unless there's urgency to do it sooner.

**Closed** 2020-07-17 17:17 UTC
Labels: bug, dependencies, mdx, tracked
