### ISSUE TITLE
addon-docs: Props doesn't work when using React.memo.

### ISSUE THREAD

**Issue by sinkz** [storybookjs/storybook#9586] opened 2020-01-21 13:52 UTC
**Describe the bug**
I trying show the props in docs page using `<Props of={Component}/>` in .mdx file. But i receive this message **"No props found for this component"**

**To Reproduce**
1. Create Component in React and wrapped this with React.memo
2. Run Storybook and open docs tab
3. The prop table does not appear

**Screenshots**
![ex1](https://user-images.githubusercontent.com/12355312/72809905-5da43100-3c3b-11ea-8480-045dbe77befa.png)

**Code snippets**

**Button.js**

```
function Button({ label, onClick }) {
  return (
    <ButtonContainer onClick={onClick}>
      <Label> {label} </Label>
    </ButtonContainer>
  );
}

Button.propTypes = {
  label: PropTypes.string.isRequired,
  onClick: PropTypes.func.isRequired,
};

export default React.memo(Button);
```

**button.stories.mdx**

```
# Button

Exemplo do **botão** padrão.

<Preview withToolbar>
  <Story name="Default" height="100px" parameters={{ decorators: [withKnobs] }}>
    <Button 
      labelColor={text("Label Color", theme.colors.white)}
      onClick={() => alert("Button Click")} />
  </Story>
</Preview>

## Props

<Props of={Button} />
```

**System:**
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 72.0.1
  npmPackages:
    @storybook/addon-actions: 5.3.7 => 5.3.7 
    @storybook/addon-backgrounds: 5.3.7 => 5.3.7 
    @storybook/addon-centered: 5.3.7 => 5.3.7 
    @storybook/addon-docs: 5.3.7 => 5.3.7 
    @storybook/addon-knobs: 5.3.7 => 5.3.7 
    @storybook/addon-storysource: 5.3.7 => 5.3.7 
    @storybook/addon-viewport: 5.3.7 => 5.3.7 
    @storybook/core: 5.3.7 => 5.3.7 
    @storybook/react: 5.3.7 => 5.3.7 
    @storybook/theming: 5.3.7 => 5.3.7 
  npmGlobalPackages:
    @storybook/cli: 5.3.4

**Comment by shilman** [comment] 2020-01-21 14:04
Unsatisfying workaround is to also export your pure component and use that for documentation purposes

**Comment by 779g** [comment] 2020-01-21 23:30
I ran into the same problem and found a solution some time ago: add the proptypes to the memo'ed component and you will be fine. Also I believe this has less to do than storybook than with the way the PropTypes work.

**Comment by shilman** [comment] 2020-02-14 16:46
Repro: https://github.com/storybookjs/storybook/commit/ee4144a0c517179e02b06c2cc230587161a11245

**Comment by breytex** [comment] 2020-03-16 14:46
Sorry for the shameless bump, but is this scheduled to be fixed in an upcoming release? :)

**Comment by shilman** [comment] 2020-03-16 23:19
@breytex we've consolidated on `react-docgen` for prop table generation, and according to my repro above it appears to be working fine. Can you try upgrading and let me know if it's working for you?

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#react-prop-tables-with-typescript

**Comment by Vanuan** [comment] 2020-03-31 20:05
@shilman Is it available in 5.3.x? What should be changed here:
```
    webpackFinal: async config => {
      config.module.rules.push({
        test: /\.(ts|tsx)$/,
        use: [
          {
            loader: require.resolve('ts-loader'),
            options: {
              configFile: path.resolve(__dirname, './tsconfig.json'),
              transpileOnly: true,
            },
          },
          // Automatics props
          {
            loader: require.resolve('react-docgen-typescript-loader'),
          },
        ],
      });
      config.resolve.extensions.push('.ts', '.tsx');
      return config;
    },
  };
```

**Comment by shilman** [comment] 2020-04-01 00:48
@Vanuan Yeah, it should be available in 5.3.x. You can should be able to add `preset-typescript@3.0.0` and get the new config.

**Comment by mkinfrared** [comment] 2020-04-05 07:24
Still not working if I use default export. 
`No props found for this component`

**Comment by mkinfrared** [comment] 2020-04-05 08:51
What I also noticed is when I use named export, which is currently a working solution rignt now, docs doesn't read the children prop, even if I specifically declare that in my interface.

**Comment by shilman** [comment] 2020-04-06 00:40
@mkinfrared are you using `babel-plugin-react-docgen` or `react-docgen-typescript-loader`?

**Comment by mkinfrared** [comment] 2020-04-06 11:30
@shilman I'm using `react-docgen-typescript-loader`
I can push my test project to github if it can help you somehow

**Comment by shilman** [comment] 2020-04-07 00:28
@mkinfrared it's a known issue in RDTL that's fixed in `react-docgen`. currently both solutions leave a lot to be desired.

https://github.com/storybookjs/storybook/issues/9556

**Comment by hipstersmoothie** [comment] 2020-04-27 20:15
@mkinfrared if you submit a pr to `react-docgen-typescript-loader` with just a test case I will try to fix it

**Comment by igloude** [comment] 2020-04-28 22:56
FWIW I discovered that `<Props of={MemoizedComponent.type} />` will correctly render a props table. No idea what's going on under the hood there, lol

**Comment by shilman** [comment] 2020-08-23 23:24
@SomilKumar what happens when you set:

```
export default {
  title: '...',
  component: MyComponent.type,
}
```

**Comment by GGAGloria** [comment] 2020-08-24 12:33
> @SomilKumar what happens when you set:
> 
> ```
> export default {
>   title: '...',
>   component: MyComponent.type,
> }
> ```

Hi I am using forwardRef in my components and met the same problem, I tried your solution like 
```react
export default {
    title: 'Input',
    component: Input.type,
    parameters: {
        docs: { page: docs }
  }, 
}
```
When I wrote this in my Input.stories, the props is not loaded, I even could not see the box with 'No props found for this component'. 

I am on `"@storybook/react": "^5.3.19"`.

**Comment by SomilKumar** [comment] 2020-08-24 16:33
@shilman it doesn't render the story altogether. Both for memoized component and normal functional component.

**Comment by hipstersmoothie** [comment] 2020-08-24 17:31
@shilman Open PR to `react-docgen-typescript` to fix the `React.memo` behavior

https://github.com/styleguidist/react-docgen-typescript/pull/288

**Comment by tm1000** [comment] 2020-09-04 18:29
Thanks @hipstersmoothie !

Merged 11 days ago and released in v1.20.4 of react-docgen-typescript. I can confirm my deps went from `react-docgen-typescript@1.20.2` to `react-docgen-typescript@1.20.4`

Unfortunately I still have to unwrap memo from my components or export them separately for documentation as even with your updates there is no documentation from when wrapped in memo

**Comment by hipstersmoothie** [comment] 2020-09-04 18:30
if you get a sample repo up I can take a look

**Comment by tm1000** [comment] 2020-09-04 18:46
@hipstersmoothie thanks Andrew! (I am also an Andrew!)

Here's the requested repo for you! https://github.com/tm1000/storybook-repro

Look in the stories folder. I commented by providing two examples. One with the direct export (which works) and one with the wrapped export (using memo, does not work)

**Comment by hipstersmoothie** [comment] 2020-09-04 18:55
Thanks!

**Comment by SomilKumar** [comment] 2020-09-12 20:03
I am not sure if this is resolved, but I am still facing the same issue, where controls ( props )  are not getting generated automatically if I wrap my components using React.memo 
    "@storybook/addon-essentials": "^6.0.21",
    "@storybook/react": "^6.0.21",
 "react-docgen-typescript@1.20.4",

**Comment by BhanuSanghi-Dev** [comment] 2020-09-18 12:26
> type

Oh god this solved the same problem I was facing.
Can we please add this as a note in documentation somewhere, I had wasted 2 days just to understand that it is not working because of me using memo. It would have never occurred to me that it was the problem. I had to do hundreds of trial and error to just understand this.

**Comment by BhanuSanghi-Dev** [comment] 2020-09-18 12:27
> @SomilKumar what happens when you set:
> 
> ```
> export default {
>   title: '...',
>   component: MyComponent.type,
> }
> ```
Oh god this solved the same problem I was facing.
Can we please add this as a note in documentation somewhere, I had wasted 2 days just to understand that it is not working because of me using memo. It would have never occurred to me that it was the problem. I had to do hundreds of trial and error to just understand this.

**Comment by tm1000** [comment] 2020-09-22 20:26
@BhanuSanghi-Dev well... it *should* be fixed looking at the code changes on `react-docgen-typescript@1.20.4`. So I think the intent of the developers is this is fixed so no note needs to be made. At this point it's more of a bug than anything else. Hopefully the provided repo can help out.

**Comment by shilman** [comment] 2020-10-05 07:07
@andezzat this is the issue i was mentioning. i'm thinking maybe your "exotic component logic" from #12638 can fix this problem if applied here:

https://github.com/storybookjs/storybook/blob/next/addons/docs/src/frameworks/react/extractProps.ts#L31-L34

**Comment by lwaghorn** [comment] 2020-10-06 21:22
I was able to resolve this by chaning my component from 

```
const myComponent = memo(()=><div>...</div>)
export default myComponent
```
to 
```
const myComponent = ()=><div>...</div>
export default memo(myComponent)
```
and then in storybook doing the
```
export default {
  title: 'myComponent',
  component: myComponent.type,
  decorators: [withKnobs],
};
```

**Comment by andezzat** [comment] 2020-10-07 06:02
@lwaghorn 

Actually, the exported component is the same in both cases.
It's passing storybook the component as `myComponent.type` that worked!

My PR should make this unnecessary 👍

**Closed** 2020-10-08 01:45 UTC
Labels: P2, addon: docs, app: react, block: props, bug, has workaround, todo

**Comment by shilman** [comment] 2020-10-08 15:32
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-alpha.21 containing PR #12686 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by lukemorales** [comment] 2020-12-16 00:40
Came to this Issue while searching for a similar problem.
Right know, props table are being generated correctly when using React.memo, however, the default value is not being filled.

**Comment by shilman** [comment] 2020-12-16 01:17
@andezzat is default value something you can look into?

**Comment by iwan-uschka** [comment] 2023-04-21 16:34
https://github.com/storybookjs/storybook/issues/18136

**Comment by SalahAdDin** [comment] 2025-11-13 01:41
It is failing in the latest version.
