### ISSUE TITLE
[Bug]: Still happening in Storybook 7.4.0: "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'count')"

### ISSUE THREAD

**Issue by jasosims** [storybookjs/storybook#23999] opened 2023-08-30 04:21 UTC
### Describe the bug

This bug (previously reported in #23787) was marked as fixed, but is still happening in Storybook 7.4.0.

### To Reproduce

1. Go to any story for a component with an `on[Something]` handler that's tracked by the Actions addon.
2. Reload the page.
3. Perform an action (for example, if the component has an `onClick` prop, click it).

Same error as before. Not fixed. This has been happening since Storybook 7.2.0. The only workaround is to downgrade to Storybook 7.1.1.

**Comment by vanessayuenn** [comment] 2023-08-30 08:21
@jasosims are you able to share a repro in 7.4? I can reproduce the issue easily with 7.2.1 and confirm upgrading to 7.4.0 made it work again. 

If you haven't yet, could you also try clearing `node_modules` and reinstall?

**Comment by daniilgri** [comment] 2023-09-04 17:08
I have the same issue after upgrading storybook to 7.4.0

**Comment by vanessayuenn** [comment] 2023-09-05 06:13
@daniilgri do you have a reproduction repo you can share? If not, can you create one (see [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce)). We prioritize bug reports that have reproduction. Thank you! 🙏

**Comment by kasperpeulen** [comment] 2023-09-11 13:22
cc @ndelangen

**Comment by larrygotto** [comment] 2023-09-12 21:55
Same here.
I just found out that if you reload the page, go to another story and perform an action, the bug don't exists anymore, until you reload the page again.

**Comment by dylannnn** [comment] 2023-09-17 09:08
Same issue here with version 7.4.1

**Comment by literalpie** [comment] 2023-09-17 12:44
@jasosims I tried making a reproduction repo, but I'm not seeing this issue in a new project like your reproduction steps say.

**Comment by kasperpeulen** [comment] 2023-09-18 08:44
@literalpie We can not reproduce this issue as well.

@dylannnn What happens if you remove your lock file and node_modules, does the error still appear?

**Comment by dylannnn** [comment] 2023-09-18 11:14
Hi @kasperpeulen , after delete the node_modules folder and package-lock.json, run the non install and start the storybook again, the issue is still present. Now the version is 7.4.2. Let me know if you need a stackblitz project to show you the setup.

**Comment by IanVS** [comment] 2023-09-18 11:41
This looks like a duplicate of https://github.com/storybookjs/storybook/issues/23787.  I've added some reproduction notes and a stackblitz there.

**Closed by IanVS** 2023-09-18 11:41 UTC
Labels: bug, needs reproduction, sev:S2
