### ISSUE TITLE
[Bug]: Vite HMR Issue

### ISSUE THREAD

**Issue by telam** [storybookjs/storybook#26985] opened 2024-04-29 15:34 UTC
### Describe the bug

Storybook doesn't seem to be updating properly with Vite HMR.

https://github.com/storybookjs/storybook/discussions/26984

### To Reproduce

https://stackblitz.com/edit/github-tgehw4?file=src%2Fstories%2FExample.tsx

### System

```bash
Storybook Environment Info:
  System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 21.7.1 - ~/.nvm/versions/node/v21.7.1/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v21.7.1/bin/npm <----- active
```

### Additional context

Additional contexts can be found in [this](https://github.com/storybookjs/storybook/discussions/26984) discussion

**Comment by vanessayuenn** [comment] 2024-05-21 12:33
I suspect this might be a dupe of #26881. @telam can you try if [this workaround](https://github.com/storybookjs/storybook/issues/26881#issuecomment-2065637192) fixes your problem?

**Comment by valentinpalkovic** [comment] 2024-05-23 13:15
You are having issues with the fast-refresh implementation, which is baked into `@vite/plugin-react.` Fast refresh allows the persistent state of React components and only swaps out code, which changes without needing to remount a component. This also means that React components (or, in your case, decorators) higher up the render tree are not re-executed.

We honestly can't do much about it. The first thing that came to my mind was deactivating fast refresh. Unfortunately, it is impossible to do this in newer versions of `@vite/plugin-react. ' You could run the Storybook dev server in production mode, though, which would disable fast refresh, but potentially also some other dev-related settings and optimizations:

```
NODE_ENV=production npm run storybook
```

I hope this workaround helps. Since we can't do much about it, I will close this ticket.

**Closed by valentinpalkovic** 2024-05-23 13:15 UTC
Labels: bug, needs more info

**Comment by telam** [comment] 2024-10-23 19:30
> You are having issues with the fast-refresh implementation, which is baked into `@vite/plugin-react.` Fast refresh allows the persistent state of React components and only swaps out code, which changes without needing to remount a component. This also means that React components (or, in your case, decorators) higher up the render tree are not re-executed.
> 
> We honestly can't do much about it. The first thing that came to my mind was deactivating fast refresh. Unfortunately, it is impossible to do this in newer versions of `@vite/plugin-react. ' You could run the Storybook dev server in production mode, though, which would disable fast refresh, but potentially also some other dev-related settings and optimizations:
> 
> ```
> NODE_ENV=production npm run storybook
> ```
> 
> I hope this workaround helps. Since we can't do much about it, I will close this ticket.

@valentinpalkovic Thank you for the reply to this issue, sorry for not getting back to you I must have missed the notification. The workaround you suggested does in fact work however it is terribly slow when modifying things like the args to the Story. Maybe in the future, there could be some work done here or maybe I can open up an issue with the @vite/plugin-react library and see if they can do anything about it. Thanks again!
