### ISSUE TITLE
[Storybook 6] The "zero-config" TypeScript config doesn't work on our project

### ISSUE THREAD

**Issue by Jack-Works** [storybookjs/storybook#12479] opened 2020-09-15 08:36 UTC
**Describe the bug**  

Build error for 2 syntaxes:

1. const enum
2. `declare` class fields

```
ERROR in ./src/plugins/FileService/constants.ts
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /home/jack/workspace/maskbook/src/plugins/FileService/constants.ts: 'const' enums are not supported.
   9 | export const signing = 'https://service.maskbook.com/arweave-remote-signing'
  10 | 
> 11 | export const enum FileRouter {
     |        ^
  12 |     upload = '/upload',
  13 |     uploading = '/uploading',
  14 |     uploaded = '/uploaded',

ERROR in ./src/utils/ObservableMapSet.ts
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /home/jack/workspace/maskbook/src/utils/ObservableMapSet.ts: TypeScript 'declare' fields must first be transformed by @babel/plugin-transform-typescript.
If you have already enabled that plugin (or '@babel/preset-typescript'), make sure that it runs before any plugin related to additional class features:
 - @babel/plugin-proposal-class-properties
 - @babel/plugin-proposal-private-methods
 - @babel/plugin-proposal-decorators
  2 | // Consider switch to libraries like Mobx if this file become too complex.
  3 | export class ObservableWeakMap<K extends object, V> extends WeakMap<K, V> {
> 4 |     declare __brand: 'Map'
    |     ^^^^^^^^^^^^^^^^^^^^^^
  5 | 
  6 |     event = new Emitter<{ delete: [K]; set: [K, V] }>()
  7 |     delete(key: K) {
```

**To Reproduce**  

Reproduction: https://github.com/DimensionDev/Maskbook/pull/1568

**Expected behavior**  Build successfully

**System:**  
Please paste the results of `npx sb@next info` here.

```
Environment Info:

  System:
    OS: Linux 5.8 Arch Linux
  Binaries:
    Node: 14.10.0 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.7 - /usr/bin/npm
  npmPackages:
    @storybook/addon-actions: ^6.0.21 => 6.0.21
    @storybook/addon-docs: ^6.0.21 => 6.0.21
    @storybook/addon-info: ^5.3.21 => 5.3.21
    @storybook/addon-knobs: ^6.0.21 => 6.0.21
    @storybook/addon-links: ^6.0.21 => 6.0.21
    @storybook/addon-viewport: ^6.0.21 => 6.0.21
    @storybook/addons: ^6.0.21 => 6.0.21
    @storybook/react: ^6.0.21 => 6.0.21
```

**Additional context**

**Comment by molebox** [comment] 2020-09-15 08:51
Hey! I just came across this very same probelm with regards to the const enum. Not sure what your setup is but just installing this babel plugin solved that one for me: [babel-plugin-const-enum](https://www.npmjs.com/package/babel-plugin-const-enum)

**Comment by Jack-Works** [comment] 2020-09-15 09:17
But our main project is using typescript to compile, not babel. I don't like to include babel* as a direct dependency

**Comment by shilman** [comment] 2020-09-15 10:46
Storybook's built in typescript support is based on babel, not typescript.

**Comment by Jack-Works** [comment] 2020-09-15 11:18
Yeah I know it's based on babel, can the storybook built-in support handle this two things correctly?

**Comment by Jack-Works** [comment] 2020-10-12 01:10
Bump🤔

**Comment by shilman** [comment] 2020-10-12 05:09
@mrmckeb can you take a look at the babel plugin above and weigh in on the typescript q?

**Comment by machinek56** [comment] 2020-10-14 07:39
Had the same issue with const-enum, patched webpack config such as
 ```
// const isLoader = ruleSetUse => typeof ruleSetUse === 'object';

webpackFinal: async config => {
    config.module.rules = config.module.rules.map(rule => {
      // Find the rule containing 'babel-loader'
      const isBabelRule = Array.isArray(rule.use) && rule.use.find(use => isLoader(use) && use.loader.includes('babel-loader'));
      if (isBabelRule) {
        const { presets } = rule.use[0].options;
        // NOTE: need to add `const-enum` for support const enum transpilation.
        // see https://github.com/dosentmatter/babel-preset-const-enum#usage
        if (!presets.includes('const-enum')) {
          rule.use[0].options.presets = [...presets, 'const-enum'];
        }
        return rule;
      }
      return rule;
    });
    ...
```

Just installing *babel-plugin-const-enum* not helped.

**Comment by Tedko** [comment] 2020-10-16 19:53
Bump

**Comment by shilman** [comment] 2020-10-18 09:48
If you want this fixed, please upvote by adding a 👍 to the issue description. We use this to help prioritize!

**Comment by ccocoual** [comment] 2020-10-20 13:54
Had the same issue and was able to fix it by adding `babel-plugin-const-enum` and a **.babelrc** file in my **.storybook** folder as below.

```
{
  "plugins": ["const-enum", "@babel/transform-typescript"]
}

```

**Comment by Jack-Works** [comment] 2020-12-26 03:19
still watching

**Comment by marcusnewton** [comment] 2021-02-19 03:11
bump

**Comment by magic-akari** [comment] 2021-03-11 09:07
bump

**Comment by zaqqaz** [comment] 2021-03-29 17:36
up

**Comment by stevenbriscoeca** [comment] 2021-03-31 19:51
The solution of adding in a .babelrc file

```
{
  "plugins": ["const-enum", "@babel/transform-typescript"]
}
```

Does not work if you have a mix of mdx file and tsx files for me getting this error : 
![image](https://user-images.githubusercontent.com/3018441/113202603-f0c1f900-9238-11eb-9fcf-148f64f5d69b.png)

**Comment by ccocoual** [comment] 2021-03-31 20:20
It seems that you can make it work by using those babel presets: [babel-preset-const-enum](https://github.com/dosentmatter/babel-preset-const-enum#usage) and [babel-preset-typescript](https://babeljs.io/docs/en/babel-preset-typescript).

Then in your **.babelrc** file, you can add:

```
"presets": [
    "@babel/typescript",
    [
      "const-enum",
      {
        "transform": "removeConst"
      }
    ]
  ]
```

It allows you to have a mix of stories written in **.mdx** and **.tsx**.

If you have an error mentionning `isLeaf`, it certainly mean that you have stories with same titles and it should be fixed by having different titles.

**Comment by spjtls9** [comment] 2021-05-26 19:29
Similar to other solutions, but this one worked for my project

in `main.js`

```
module.exports = {
    stories: ["../**/*.stories.(ts|tsx)"],
    addons: ["@storybook/addon-links", "@storybook/addon-essentials", "@storybook/addon-a11y"],
    webpackFinal: async (config, { configType }) => {
        // `configType` has a value of 'DEVELOPMENT' or 'PRODUCTION'
        // You can change the configuration based on that.
        // 'PRODUCTION' is used when building the static version of storybook.

        // Return the altered config
        return config;
    },
    babel: async ({ plugins, ...rest }) => ({
        ...rest,
        // any extra options you want to set
        plugins: ["const-enum", ...plugins],
    }),
};
```

**Comment by leevigraham** [comment] 2021-08-10 23:55
@Jack-Works Did you manage to solve the "declare class fields" issue?

**Comment by Jack-Works** [comment] 2021-08-13 15:13
> @Jack-Works Did you manage to solve the "declare class fields" issue?

No. We split our project into multiple sub-repos and remove the storybook from the main repo. Now our new repos work well with storybook.

**Comment by leevigraham** [comment] 2021-08-15 22:22
@Jack-Works This is likely the issue: https://github.com/storybookjs/storybook/issues/15840

**Comment by viditganpi** [comment] 2021-12-08 06:43
Anyway to resolve this without adding a `.babelrc`? Currently I don't have one for my project, and not sure about how to add one that should work with all the packages, in the project. 
@spjtls9 mentioned modifying the babel config under main, anyway to do this with the old configuration setup, with `config` and `preset`.

**Comment by marcusnewton** [comment] 2022-01-09 05:29
Bump

**Comment by marcusnewton** [comment] 2022-01-09 05:30
Relax stalebot...wow

**Comment by prafulprakash** [comment] 2022-03-08 15:01
> Had the same issue and was able to fix it by adding `babel-plugin-const-enum` and a **.babelrc** file in my **.storybook** folder as below.
> 
> ```
> {
>   "plugins": ["const-enum", "@babel/transform-typescript"]
> }
> ```

This solution is not working on Angular 10 +Version and typescript with webpack. Can anyone help?

**Comment by thibaudcolas** [comment] 2023-02-15 04:42
For anyone running into an issue with `declare` class fields, here is what worked for me:

```js
// Redefine Babel config to allow TypeScript class fields `declare`. Works around issue with stock Storybook configuration.
// See https://github.com/storybookjs/storybook/issues/12479.
babel: async (options) => ({
    ...options,
    plugins: [],
    presets: [
      ['@babel/preset-typescript', { allowDeclareFields: true }],
      ['@babel/preset-react', { runtime: 'automatic' }],
    ],
  }),
```

I wish I’d be able to preserve more of Storybook’s configuration as-is but turning on `allowDeclareFields` isn’t enough. This transform also has to be applied before the other conflicting plugins.

---

I’m surprised this is labeled a "question / support" issue and not bug, considering the two issues reported here literally mean there isn’t "zero configuration needed" for TypeScript projects. I can appreciate there might be more urgent things to fix but surely it wouldn’t take that much effort to amend this documentation with reference to unsupported TypeScript syntax until the issue is fixed.

**Comment by shilman** [comment] 2024-07-13 15:40
Closing this as fixed, since I haven't heard of any typescript issues in years. If you have specific typescript config issues, please file them individually with a reproduction. Thank you!

**Closed by shilman** 2024-07-13 15:40 UTC
Labels: question / support, configuration babel / webpack, has workaround, typescript
