### ISSUE TITLE
[Bug]: Boolean control is not persistent

### ISSUE THREAD

**Issue by Spielboerg** [storybookjs/storybook#22679] opened 2023-05-22 13:13 UTC
### Describe the bug

As the title suggests, boolean controls are not persistent when the page is reloaded. On the one hand, it logs unnecessarily many warnings and on the other hand, direct links to stories with control values in it cannot be sent to someone else.

See the Reproduction section for more information.

### To Reproduce

https://stackblitz.com/edit/github-fbee7n?file=src%2Fstories%2FButton.stories.js

**Preparation:** Do not use the inline preview but open the preview in a new tab (button on the upper right). Only in this way it is possible for you to see the changes in the URL.

**Successful case:**
1. Go to the `Button/Primary` story
2. Clear the logs in the browser dev tools
3. Click on the `primary` control to change it to `false`.
    - Notice that `&args=primary:!false` is added to the URL
    - Notice this warning in the logs:
      ```
      Omitted potentially unsafe URL args.

      More info: https://storybook.js.org/docs/react/writing-stories/args#setting-args-through-the-url
      ```
4. Reload the page
    - Notice the `&args=primary:!false` is still in the URL and the `primary` control is set to `false`
    - Notice that the warning from 3. above is logged again.

**Failing case:**
1. Go to the `Button/Secondary` story
2. Clear the logs in the browser dev tools
3. Click on the `primary` control to change it to `true`.
    - Notice that `&args=primary:!true` is added to the URL
    - Notice this warning in the logs:
      ```
      Omitted potentially unsafe URL args.

      More info: https://storybook.js.org/docs/react/writing-stories/args#setting-args-through-the-url
      ```
4. Reload the page
    - Notice the `&args=primary:!true` is no longer in the URL and the `primary` control is set to `false`
    - Notice that the warning from 3. above is logged again.

**Comment by shilman** [comment] 2023-06-06 03:00
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.1.0-alpha.28 containing PR #22807 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

**Comment by demeshkin** [comment] 2023-09-28 02:41
@shilman I don't think the issue is fixed. When passing `!true` arguments in URL `&args=primary:!true` it's changes to false in the control.

**Comment by NiklasPor** [comment] 2023-10-04 10:15
We're using `buildArgsParam` inside some tests which run against our Storybook and it includes the same issue. For now we're required to do some search & replace to remove the `!` before `true` and `false` which keep storybook from interpreting them correctly.

**Comment by MichaelAllenWarner** [comment] 2023-10-18 12:41
Yes, I see this behavior in my projects as well. The exclamation mark is getting wrongly added to boolean args set from the Controls.

**Comment by RJesusTVD** [comment] 2024-01-10 09:46
Hello,

Any updates on this bug?

Thanks

**Comment by Nicolas-Menettrier** [comment] 2024-01-11 05:11
Same behavior on my project too, I used @NiklasPor suggestion as a quick fix. Does the job

**Comment by shilman** [comment] 2024-01-11 16:35
closing as duplicate to #25035

**Closed by shilman** 2024-01-11 16:35 UTC
Labels: bug, addon: controls, duplicate
