### ISSUE TITLE
[Bug]: Does not work in a a project using yarn but not a git/subversion, or a git worktree

### ISSUE THREAD

**Issue by dobesv** [storybookjs/storybook#20314] opened 2022-12-16 22:57 UTC
### Describe the bug

Currently in https://github.com/storybookjs/storybook/blob/next/code/lib/core-common/src/utils/paths.ts it attempts to calculate the root of the project by looking for a `.git` folder, a `.svn` folder, or a `node_modules` folder.  This is used to set the base path that babel should process files in.

If your project is using yarn and doesn't have a `.git` or `.svn` folder, the project root calculation is way off because it ends up looking for `node_modules` and yarn creates a `node_modules` folder for every dependency inside of that dependency's own folder but does not store dependencies inside a `node_modules` folder in the project root.

In my case I was using `git worktree` where it creates `.git` as a file instead of a folder, so the search for a `.git` folder was not successful.

This resulted in a completely wrong project root calculation and resulted in some hours of debugging to figure out what's going on.

It seems like this method of detecting the project root is kind of a hack and probably should be removed.  I don't think other tools are using this weird technique.  I think these days it is OK to assume the tool is run from the project root, and if it isn't the user must provide the project root as a command-line parameter or environment variable.

If completely removing this logic is not to your tastes, it would be nice to provide an alternative mechanism, for example supporting a `.yarn` folder as an alternative to the `node_modules` logic, or search upwards for a `.storybook` folder, or check for an environment variables like `STORYBOOK_PROJECT_ROOT` ?

### Workaround

If you run into this problem, you can create a folder named `.svn` in your project to trick storybook into using that to detect the project root.

### To Reproduce

```shell
Use yarn and storybook together but not git or subversion.
```

**Comment by shilman** [comment] 2022-12-19 03:41
Related #20211

**Comment by shilman** [comment] 2023-01-20 10:55
Closing as duplicate of #14042

**Closed by shilman** 2023-01-20 10:55 UTC
Labels: bug, duplicate, needs triage
