### ISSUE TITLE
Addons-links with MDX

### ISSUE THREAD

**Issue by ok2ju** [storybookjs/storybook#10846] opened 2020-05-20 13:46 UTC
Hello, I tried to use `addon-links` with MDX (`addon-docs`) and I wondered why `story` property of `LinkTo` (from `react` package) is required? I have several doc pages without `Story` at all and I want to navigate such pages using `LinkTo`. Btw, it works but annoying error drops in the console.

```
Cannot read property 'toLowerCase' of null
```

The error comes from `sanitize` [method](https://github.com/storybookjs/csf/blob/next/src/index.ts#L10) of `storybookjs/csf` package. `hrefTo` [method](https://github.com/storybookjs/storybook/blob/7c706b56acf7bb4c87722c445b7daed23029daf4/addons/links/src/preview.ts#L77) trying to generate url but fails when calling method `toId`

**Expected behavior**
There are no errors in the console.

**Code snippets**
```jsx
<LinkTo kind="MyDoc" />
```

**Comment by shilman** [comment] 2020-05-20 22:36
Parent issue #6700

**Comment by blaine-stripe** [comment] 2020-07-21 23:28
I also ran into this while investigating https://github.com/storybookjs/storybook/issues/11590 - is there a workaround for now?

**Comment by ndelangen** [comment] 2020-07-24 15:55
edited a mdx story:
<img width="966" alt="Screenshot 2020-07-24 at 17 53 27" src="https://user-images.githubusercontent.com/3070389/88410373-9a153d00-cdd6-11ea-968b-675083aea3c8.png">

but it's not showing up:
<img width="504" alt="Screenshot 2020-07-24 at 17 53 46" src="https://user-images.githubusercontent.com/3070389/88410530-cc269f00-cdd6-11ea-8ebe-98c8fda6f2a1.png">
<img width="590" alt="Screenshot 2020-07-24 at 17 53 57" src="https://user-images.githubusercontent.com/3070389/88410537-cd57cc00-cdd6-11ea-8160-b998472e6922.png">
<img width="442" alt="Screenshot 2020-07-24 at 17 54 16" src="https://user-images.githubusercontent.com/3070389/88410544-ce88f900-cdd6-11ea-958e-02426abdfe03.png">

**Comment by ndelangen** [comment] 2020-07-24 15:55
I'm not sure if this was ever intended to work..

**Comment by blaine-stripe** [comment] 2020-07-27 17:40
@ndelangen Hmm, it works in the code I'm looking at. Maybe it is because you have text on the same line? Can you try it with the LinkTo on it's own line?

**Comment by elektronik2k5** [comment] 2020-07-27 20:28
I didn't check what happens when `LinkTo` is on it's own line, but can definitely confirm the issue when it isn't, cause all of our links are inline and the bug is consistently reproducible.

**Comment by ndelangen** [comment] 2020-07-28 08:31
This seems to work:
```js
import LinkTo from '@storybook/addon-links/react';

<Meta title="About/Intro" />

# Official-storybook

Welcome to `official-storybook`, a collection of test cases and demos for `@storybook/react` and all its addons.

Should be a link here >>> <LinkTo kind="test" story="index">Go to index</LinkTo> <<< Should be a link here
```

**Comment by blaine-stripe** [comment] 2020-07-28 17:53
Yeah, but if you have a "kind" without a "story", the component throws because of some internals.

**Comment by ndelangen** [comment] 2020-07-29 09:41
aha

**Comment by ndelangen** [comment] 2020-08-03 11:57
This is fixed in 6.0.0

I verified using:
```mdx
import LinkTo from '@storybook/addon-links/react';

<Meta title="About/Intro" />

# Official-storybook

Welcome to `official-storybook`, a collection of test cases and demos for `@storybook/react` and all its addons.

Should be a link here >>> <LinkTo kind="Core/Args">Go to index</LinkTo> <<< Should be a link here
```

**Comment by isellsoap** [comment] 2020-08-11 09:29
I’m still getting the error. I’m on the freshly released `6.0.0` version.

**Comment by shilman** [comment] 2020-08-11 09:57
Do you have a repro?

**Comment by isellsoap** [comment] 2020-08-11 10:57
@shilman Thanks for the follow-up! I created a minimal reproduction case: https://github.com/isellsoap/storybook-issue-10846

**Comment by ndelangen** [comment] 2020-08-17 09:52
Thanks for the repro, hopefully we'll be able to take a look quickly!

**Comment by isellsoap** [comment] 2020-09-07 14:23
As far as I know this is still an issue.

**Comment by shilman** [comment] 2020-09-25 09:01
@isellsoap I think it should be `<LinkTo kind="Example/Button">`. Does that work?

**Comment by isellsoap** [comment] 2020-09-28 09:45
@shilman I just tried it, using `Example/Button` produces the same error in the console.

**Comment by unematiii** [comment] 2020-09-29 23:59
I'm also getting the same error, however when I also specify `story`, the error vanishes.

`<LinkTo kind="base/atoms/misc/Component">Component</LinkTo>`, works, but produces error. 
`<LinkTo kind="base/atoms/misc/Component"  story="as-a-tag">Component</LinkTo>` or ,`<LinkTo kind="base/atoms/misc/Component"  story="As `a` tag">Component</LinkTo>` works without errors.

**Comment by isellsoap** [comment] 2020-10-07 07:38
@unematiii True, the the errors don’t appear with `story="as-a-tag"`. But the links themselves don’t work after applying the attribute. Do the links take you to the destination when clicking on them?

**Comment by unematiii** [comment] 2020-10-07 09:18
@isellsoap Yeah, it works for me.

package.json:
```
"@storybook/addon-links": ">=6.0.25",
```

SomeComponent.stories.mdx:
```mdx
import LinkTo from '@storybook/addon-links/react';

Uses <LinkTo kind="base/atoms/misc/Component" story="as-a-tag">Component</LinkTo> to provide corresponding slots.
```

base/atoms/misc/Component/Component.stories.mdx:
```mdx
## As `a` tag

<Story name="As `a` tag">{Template.bind({})}</Story>
```

**Comment by empressmoon** [comment] 2020-10-14 11:59
hi, I'm having the same issue:
I need to add links between docs in storybook, like so:

`<LinkTo kind="Docs/Getting started">Getting started</LinkTo>`

Links work fine, but I'm still getting the console error:

<img width="264" alt="Zrzut ekranu 2020-10-14 o 12 58 04" src="https://user-images.githubusercontent.com/26803656/95985776-ea6fca00-0e1c-11eb-8382-dece6ebd98de.png">


Anyone can help?

**Comment by unematiii** [comment] 2020-10-14 19:36
I think [this](https://github.com/ComponentDriven/csf/blob/8af8a4ecfdf3e3f276830c27127e5c74d40762c0/src/index.ts#L31) function really needs a `null` check for `name` argument.

**Comment by empressmoon** [comment] 2020-10-15 07:57
thanks @unematiii :) Looking at [this](https://github.com/ComponentDriven/csf/blob/8af8a4ecfdf3e3f276830c27127e5c74d40762c0/src/index.ts#L31) I got rid of the problem by adding `story="page"` to the `LinkTo`:

`<LinkTo kind="Docs/Getting started" story="page">Getting started</LinkTo>`

It's maybe a bit hacky but it works for now.

**Comment by unematiii** [comment] 2020-10-15 13:56
@empressmoon Hmm, well it works without errors if you add a `story`, bot produces an error without this. If you don't have a story named `page`, the link doesn't work at all. Not sure if this is a workaround.

**Comment by tklives** [comment] 2021-05-18 15:56
Hello y'all!  

I'm still running into this on v6.2.7 and am wondering if there is any timeline on resolution for allowing you to only supply a `kind` to a `<LinkTo>`, or if I shouldn't wait for that and instead just go add the `story` attribute to all of my links to sidestep those errors?

Thanks!

**Comment by shilman** [comment] 2021-08-31 12:24
@devintyler any chance you can create a PR with those changes?

**Comment by unematiii** [comment] 2021-08-31 13:08
@shilman The routine in question is part of [CSF](https://github.com/ComponentDriven/csf). I've submitted a [PR](https://github.com/ComponentDriven/csf/pull/17/) quite some time ago.

**Comment by shilman** [comment] 2021-08-31 13:11
@unematiii thanks for bringing it to my attention! Will discuss with @tmeasday and figure out the right way forward. 🙏

**Comment by blowsie** [comment] 2022-08-23 14:47
Is there a solution for Vue + MDX?

**Comment by TheColorRed** [comment] 2022-11-22 16:13
I still cannot get this working in MDX `v6.5.12` so I just created my own component with the `linkTo` function.

```javascript
import { linkTo } from '@storybook/addon-links';
import React from 'react';

export class Link extends React.Component {
  constructor(props) {
    super(props);
    this.title = props.title;
    this.story = props.story;
    this.children = props.children;
  }

  render() {
    let style = { color: 'rgb(30, 167, 253)', textDecoration: 'none', cursor: 'pointer' };
    return (
      <a style={style} onClick={linkTo(this.title, this.story)}>
        {this.children}
      </a>
    );
  }
}
```

**Comment by ndelangen** [comment] 2023-01-31 10:32
I'm fairly sure this is no longer a problem in Storybook 7.0 beta. If someone could verify this, and report if it's still an issue?
A reproduction would be useful. 🙏

**Closed by ndelangen** 2023-01-31 10:32 UTC
Labels: question / support, has workaround, addon: links, todo, addon: docs, PN
