### ISSUE TITLE
TSX not supported in config with CRA

### ISSUE THREAD

**Issue by Kamahl19** [storybookjs/storybook#7563] opened 2019-07-25 15:22 UTC
**Describe the bug**
TSX is not supported inside of the .storybook folder.

**To Reproduce**
1. Install create-react-app with typescript
2. Install Storybook
3. create .storybook/config.tsx 

**Expected behavior**
TSX will be supported inside the .storybook folder.

**System:**
All

**Additional context**
The problem is that `cra-config.js` assumes that CRA only has 1 rule targeting TSX https://github.com/storybookjs/storybook/blob/7cd50cd65196499cc176fa0f7ad3e768e1959df2/app/react/src/server/cra-config.ts#L99 

It's not true since CRA 3.0.1, they added eslint formatter which is a first rule https://github.com/facebook/create-react-app/commit/eee8491d57d67dd76f0806a7512eaba2ce9c36f0#diff-dc0c4e7c623b73660da1809fc60cf6ba . Therefor `babel-loader` is not including .storybook folder, but eslint formatter is

**Comment by Kamahl19** [comment] 2019-07-25 15:46
Dumb workaround until it's properly fixed

webpack.config.js
```js
module.exports = ({ config }) => {
  const babelLoader = config.module.rules.find(
    rule => rule.loader && rule.loader.includes('babel')
  );

  babelLoader.include = [babelLoader.include, __dirname];

  return config;
};
```

**Comment by mrmckeb** [comment] 2019-07-28 13:48
I'll close this off as a duplicate of #7201.

**Closed by mrmckeb** 2019-07-28 13:48 UTC
Labels: compatibility with other tools, cra, has workaround
