### ISSUE TITLE
Error: Unsupported framework: react - v7.0.0-alpha.26

### ISSUE THREAD

**Issue by humarkx** [storybookjs/storybook#19034] opened 2022-08-26 18:44 UTC
**When initializing storybook on a vite react app**

`npx storybook@v7.0.0-alpha.26 init`

![image](https://user-images.githubusercontent.com/13049940/186971194-437ca28c-398a-4ad4-8483-0a1f31657ecb.png)

**Comment by zhyd1997** [comment] 2022-08-27 02:28
It works with `storybook@v7.0.0-alpha.16` but not later versions (start from`storybook@v7.0.0-alpha.17`) for me.

**Comment by yogarasu** [comment] 2022-09-02 14:06
same for storybook@v7.0.0-alpha.28

**Comment by IanVS** [comment] 2022-09-05 01:21
Please try running `npx sb@future automigrate`.  There have been changes to how frameworks are structured, which you can read about in https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#framework-field-mandatory.  I suggest reading the other sections of the migration document as well, there have been a number of changes.

**Comment by IanVS** [comment] 2022-09-22 01:16
Closing, let us know if you still have trouble.

**Closed by IanVS** 2022-09-22 01:16 UTC
Labels: bug, needs triage

**Comment by yogarasu** [comment] 2022-09-22 02:11
@IanVS

Thank you, when I tried it with 7.0.0-alpha.33, the command worked, so there seems to be no problem.
The transition to CSF3 was also perfect.

```
npx sb init
npx sb@next migrate csf-2-to-3 --glob="**/*.stories.tsx"
```

**Comment by yogarasu** [comment] 2022-09-22 02:20
@IanVS 

sorry i was looking at the wrong file
I confirmed the phenomenon that Value is mixed with migrate command of csf-2-to-3.

If there are no duplicate issues, I make issue.

<img width="584" alt="スクリーンショット 2022-09-22 11 16 00" src="https://user-images.githubusercontent.com/68766032/191643709-e6e81f77-a146-4196-8b1b-e63b305e702c.png">

**Comment by IanVS** [comment] 2022-09-22 02:34
I don't see an issue for that, and I haven't heard of it before, so yes, please do open an issue, ideally with some steps to reproduce it, if possible.  Thanks!

**Comment by yogarasu** [comment] 2022-09-22 17:35
@IanVS 
Prittier plugin seems to interfere.
I don't know the detailed cause, but I created an issue #19234 just in case.
