### ISSUE TITLE
React 18 createRoot supports

### ISSUE THREAD

**Issue by sivaraj-v** [storybookjs/storybook#18045] opened 2022-04-25 06:41 UTC
Feature looking for React 18 createRoot in storybook

https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis

I'm getting warning as follow, 

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/6199252/165033765-fb7803e2-762c-4218-b774-47875be63ef2.png">

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/6199252/165033848-80121f13-f80c-4f48-9c6a-fc388753e81d.png">

Currently I'm using following version, 

```
"@storybook/addon-a11y": "6.4.22",
"@storybook/addon-actions": "6.4.22",
 "@storybook/addon-jest": "6.4.22",
"@storybook/addon-viewport": "6.4.22",
"@storybook/builder-webpack5": "6.4.22",
"@storybook/manager-webpack5": "6.4.22",
 "@storybook/react": "6.4.22",
 
 ```

**Comment by Stunext** [comment] 2022-04-25 12:31
You need to wait for version ^6.5 or use some of the alpha or beta versions. Keep in mind that as an "alpha/beta" version not all bugs are fixed.

**Comment by sivaraj-v** [comment] 2022-04-26 06:22
Thanks @shilman and @Stunext

**Comment by latata** [comment] 2022-06-29 17:42
It looks like in the latest version of storybook (6.5.9) still uses old ReactDOM.render method instead of createRoot. Are there plans to change it?

**Comment by shilman** [comment] 2022-06-30 03:11
@latata do you have a reproduction of this? it should use the new root API if you're using react18 in your project. More info here: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#react18-new-root-api

**Comment by fullhdpixel** [comment] 2022-07-05 09:31
Same issue with these versions: 
`
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "@storybook/react": "6.5.9",
`

**Comment by bstaruk** [comment] 2022-07-05 11:46
@shilman Here is a repo which has just 2 commits (CRA init, then storybook init), which reproduces the issue:

https://github.com/bstaruk/storybook-18045

![Screen Shot 2022-07-05 at 7 44 26 AM](https://user-images.githubusercontent.com/1264040/177320319-f8faef34-17d2-4025-bd21-e537208ba0b0.png)

**Comment by niug** [comment] 2022-07-22 12:14
I have the same problem. Do you know how to solve it, even if it is a temporary solution?

**Comment by Semigradsky** [comment] 2022-07-22 14:31
Temporary solution - just ignore it. It is warning in Storybook UI, not in your components.

**Comment by niug** [comment] 2022-07-26 05:56
Hi @Semigradsky, but my components don't loading correctly, are always in an inifinite loading loop:

![image](https://user-images.githubusercontent.com/1314754/180933530-4dde5764-a788-4fb5-8a10-fc64b75dd392.png)

**Comment by Semigradsky** [comment] 2022-07-26 06:38
@niug  I don't think that this is related to warning. Latest stable storybook (6.5.9) works great with React 18 for me.

**Comment by niug** [comment] 2022-07-26 09:46
ok @Semigradsky, I'm using this version, here it's my package.json:

![image](https://user-images.githubusercontent.com/1314754/180976947-bd41690b-35e8-4740-ae6f-374906198bac.png)

Some idea why don't load the component page? Thanks.

**Comment by Semigradsky** [comment] 2022-07-26 11:15
@niug I have no idea. Create a new issue with a link to a reproducible demo

**Comment by vladgorbachev** [comment] 2022-09-11 01:59
![image](https://user-images.githubusercontent.com/32522459/189508558-f2564e36-3f1e-4a68-9b40-90320d3b0286.png)
![image](https://user-images.githubusercontent.com/32522459/189508567-1c507c03-9343-46dd-a543-df02ee6c5661.png)
I'm not sure correctness of result but twice result the same

**Comment by vladgorbachev** [comment] 2022-09-11 02:01
I saw comment from @shilman how to fix but doesn't work

**Comment by Semigradsky** [comment] 2022-09-11 23:43
@vladgorbachev why did you write it here? It is totally different issue, open your own.

Also, you use `7.x` version - it has break changes, read the migration guide at first (MIGRATION.md).

**Comment by thebinaryfelix** [comment] 2022-10-30 07:20
I'm having the same problem as @sivaraj-v and I'm trying to debug but it's gone beyond my capabilities for now.

This is what I've discovered so far:

The error only appears when this function gets called:
`require$$2.render(React$2.createElement(Root,{key:"root",provider:provider}),domNode)` inside `@storybook/ui/dist/esm/index.js`. Which I assume it's the [renderStorybookUI](https://github.com/storybookjs/storybook/blob/7a86f0363ef184a80437b7abf98e98d86e821f75/code/ui/manager/src/index.tsx#L87).

Details:

I'm using @storybook 6.5.13 with Next.js 13 and React 18. I've started a project today so it's a fresh install.

```
"dependencies": {
  "next": "^13.0.0",
  "react": "^18.2.0",
  "react-dom": "^18.2.0"
},
"devDependencies": {
  "@storybook/addon-actions": "^6.5.13",
  "@storybook/addon-essentials": "^6.5.13",
  "@storybook/addon-interactions": "^6.5.13",
  "@storybook/addon-links": "^6.5.13",
  "@storybook/builder-webpack5": "^6.5.13",
  "@storybook/manager-webpack5": "^6.5.13",
  "@storybook/react": "^6.5.13",
  "@storybook/testing-library": "^0.0.13",
  "@storybook/testing-react": "^1.3.0",
  ...
}
```

This is my `main.js`

```
module.exports = {
  stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  staticDirs: ['../public'], // Added this line
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
  ],
  framework: '@storybook/react',
  core: {
    builder: 'webpack5', // it came with @storybook/builder-webpack5 and I've change it later
  },
}
```

Now comes the strange part.

The error for `ReactDOM.render` appears IF:
- the three addons are present;
- I remove the `@storybook/addon-links` but keep the other two;
- only the `@storybook/addon-interactions` is present;
- only the `"@storybook/addon-essentials` is present.

Hope this helps anyone keep debugging.

**Comment by shilman** [comment] 2022-10-30 09:12
Closing this as fixed by https://github.com/storybookjs/storybook/pull/17215

**Closed** 2022-10-30 09:12 UTC
Labels: feature request, needs triage
