### ISSUE TITLE
"npx -p @storybook/cli sb init --type react" => error "Cannot create property 'dependencies' on boolean 'false'"

### ISSUE THREAD

**Issue by stephane-klein** [storybookjs/storybook#9161] opened 2019-12-16 11:29 UTC
On OSX:

```
$ node --version
v13.3.0
$ npx --version
6.13.2
```

If I follow [this doc](https://storybook.js.org/docs/guides/guide-react/#automatic-setup), I have this error:

```
$ npx -p @storybook/cli sb init --type react

 sb init - the simplest way to add a storybook to your project.

 • Installing Storybook for user specified project type. ✓
 • Adding storybook support to your "React" app
     TypeError: Cannot create property 'dependencies' on boolean 'false'
    at default (/Users/stephane/.npm/_npx/9990/lib/node_modules/@storybook/cli/generators/REACT/index.js:24:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Best regards,
Stéphane

**Comment by pocka** [comment] 2019-12-27 13:27
Duplicate of #6002 

That issue is still opened but I think it's already fixed in v5.3.0-rc. (#8205 )

**Closed by pocka** 2019-12-27 13:27 UTC
Labels: bug, cli
