### ISSUE TITLE
start-storybook peocess exit

### ISSUE THREAD

**Issue by deyinliu** [storybookjs/storybook#18654] opened 2022-07-07 07:47 UTC
**Describe the bug**
 start-storybook, i do nothing, but after a minutes, the process will exit with error
```
node:internal/event_target:912
  process.nextTick(() => { throw err; });
                           ^
Error: EAGAIN
    at new Worker (node:internal/worker:259:19)
    at startWorkerThread (/Users/username/workspace/web-app-sdk/demo/node_modules/synckit/lib/index.cjs:108:18)
    at createSyncFn (/Users/username/workspace/web-app-sdk/demo/node_modules/synckit/lib/index.cjs:60:18)
    at Object.<anonymous> (/Users/username/workspace/web-app-sdk/demo/node_modules/eslint-mdx/lib/helpers.js:195:54)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
Emitted 'error' event on Worker instance at:
    at Worker.[kOnErrorMessage] (node:internal/worker:289:10)
    at Worker.[kOnMessage] (node:internal/worker:300:37)
    at MessagePort.<anonymous> (node:internal/worker:201:57)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:643:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28) {
  code: 'ERR_WORKER_INIT_FAILED'
}
```

**System**
Storybook 6.5.9 for React started
node v16.15.1
npm 8.6.0
macOS 12.4

other info is same as https://github.com/storybookjs/storybook/issues/18653

**Comment by JounQin** [comment] 2022-07-22 10:36
This should have been fixed by https://github.com/mdx-js/eslint-mdx/pull/412 and waiting for a release. It's not related to `storybook` here.

**Comment by shilman** [comment] 2023-06-09 02:10
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

**Closed by shilman** 2023-06-09 02:10 UTC
Labels: bug, cli, mdx
