### ISSUE TITLE
[Bug]: [7.0.0-beta.17] Cycling page reload on docs pages

### ISSUE THREAD

**Issue by 7rulnik** [storybookjs/storybook#20448] opened 2022-12-30 16:21 UTC
### Describe the bug

I'm trying migrate from storybook 6.5.12 to 7.0.0-beta.17, but when I open docs pages it starts cyclic page reload. I have `autodocs` enabled. I checked stacktrace and looks like this is the reason for it, but it's not clear why it happens and it's a bit hard to debug because files are minimized.

https://github.com/storybookjs/storybook/blob/a8617fd870d5c645b9239ccdfe8c6c89bf83ae09/code/lib/preview-api/src/modules/preview-web/render/StoryRender.ts#L292

Whole stack trace looks like that:

```
teardown (runtime.mjs:67)
await in teardown (async)
teardownRender (runtime.mjs:84)
(anonymous) (runtime.mjs:73)
eval (index.mjs:112)
safelyCallDestroy (react-dom.development.js:22927)
commitHookEffectListUnmount (react-dom.development.js:23095)
commitPassiveUnmountOnFiber (react-dom.development.js:25026)
commitPassiveUnmountEffects_complete (react-dom.development.js:25002)
commitPassiveUnmountEffects_begin (react-dom.development.js:24991)
commitPassiveUnmountEffects (react-dom.development.js:24936)
flushPassiveEffectsImpl (react-dom.development.js:27033)
flushPassiveEffects (react-dom.development.js:26979)
performSyncWorkOnRoot (react-dom.development.js:26071)
flushSyncCallbacks (react-dom.development.js:12042)
flushSyncCallbacksOnlyInLegacyMode (react-dom.development.js:12021)
scheduleUpdateOnFiber (react-dom.development.js:25536)
dispatchSetState (react-dom.development.js:17527)
eval (index.mjs:108)
await in eval (async)
eval (index.mjs:108)
commitHookEffectListMount (react-dom.development.js:23145)
commitPassiveMountOnFiber (react-dom.development.js:24921)
commitPassiveMountEffects_complete (react-dom.development.js:24886)
commitPassiveMountEffects_begin (react-dom.development.js:24873)
commitPassiveMountEffects (react-dom.development.js:24861)
flushPassiveEffectsImpl (react-dom.development.js:27034)
flushPassiveEffects (react-dom.development.js:26979)
eval (react-dom.development.js:26764)
workLoop (scheduler.development.js:266)
flushWork (scheduler.development.js:239)
performWorkUntilDeadline (scheduler.development.js:533)
postMessage (async)
schedulePerformWorkUntilDeadline (scheduler.development.js:574)
requestHostCallback (scheduler.development.js:588)
unstable_scheduleCallback (scheduler.development.js:441)
scheduleCallback$1 (react-dom.development.js:27532)
commitRootImpl (react-dom.development.js:26763)
commitRoot (react-dom.development.js:26677)
performSyncWorkOnRoot (react-dom.development.js:26112)
flushSyncCallbacks (react-dom.development.js:12042)
flushSync (react-dom.development.js:26196)
legacyCreateRootFromDOMContainer (react-dom.development.js:29570)
legacyRenderSubtreeIntoContainer (react-dom.development.js:29596)
render (react-dom.development.js:29680)
eval (preview.js:1)
Promise.then (async)
DocsRenderer.render (preview.js:1)
(anonymous) (runtime.mjs:75)
renderDocs (runtime.mjs:75)
renderToElement (runtime.mjs:75)
await in renderToElement (async)
renderSelection (runtime.mjs:84)
await in renderSelection (async)
selectSpecifiedStory (runtime.mjs:84)
(anonymous) (runtime.mjs:75)
(anonymous) (runtime.mjs:4)
_runResolutions (runtime.mjs:4)
then (runtime.mjs:4)
initializeWithStoryIndex (runtime.mjs:75)
(anonymous) (runtime.mjs:73)
Promise.then (async)
initializeWithProjectAnnotations (runtime.mjs:73)
initializeWithProjectAnnotations (runtime.mjs:75)
(anonymous) (runtime.mjs:67)
(anonymous) (runtime.mjs:4)
_runResolutions (runtime.mjs:4)
then (runtime.mjs:4)
initialize (runtime.mjs:67)
eval (storybook-config-entry.js:40)
./storybook-config-entry.js (main.iframe.bundle.js:42459)
__webpack_require__ (main.iframe.bundle.js:43885)
(anonymous) (main.iframe.bundle.js:44250)
(anonymous) (main.iframe.bundle.js:44252)
```

### To Reproduce

```shell
I can't share repro because it's private project.

1. Set autodocs to true


module.exports = {
  docs: {
    autodoc: true,
  },
};


2. Open docs page
3. It will launch cyclic page reload
```

### System

```shell
Environment Info:

  System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 18.12.0 - /private/var/folders/m3/p021stgs37n2zg2h6zd3mh8w0000gn/T/xfs-e42eed7f/node
    Yarn: 3.1.0 - /private/var/folders/m3/p021stgs37n2zg2h6zd3mh8w0000gn/T/xfs-e42eed7f/yarn
    npm: 8.19.2 - ~/Library/Caches/fnm_multishells/20977_1672414598102/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 107.0.1
    Safari: 16.1
  npmPackages:
    @storybook/addon-actions: 7.0.0-beta.17 => 7.0.0-beta.17
    @storybook/addon-docs: 7.0.0-beta.17 => 7.0.0-beta.17
    @storybook/addon-essentials: 7.0.0-beta.17 => 7.0.0-beta.17
    @storybook/addon-viewport: 7.0.0-beta.17 => 7.0.0-beta.17
    @storybook/react: 7.0.0-beta.17 => 7.0.0-beta.17
    @storybook/react-webpack5: 7.0.0-beta.17 => 7.0.0-beta.17
```

### Additional context

I will try to make repro a bit later but maybe you can guide me to things that I need to check?

**Comment by 7rulnik** [comment] 2022-12-30 18:45
Okay, looks like I found the reason for it.

We have a custom container for docs where we detected dark mode and pass it as story context. So we overwrite storyById and add a suitable theme in the result. But looks like something changed and if we return a new object in storyById it leads to story reload. So I fixed it like that.

```patch
diff --git a/.storybook/docs-container.js b/.storybook/docs-container.js
index 6737e5b80edb15552a75b9aa5b31ca6f4d9e5216..6fc5e64dc95920a4657e3e57fbc50a063f75f76a 100644
--- a/.storybook/docs-container.js
+++ b/.storybook/docs-container.js
@@ -1,30 +1,17 @@
 import React from 'react';
-import { DocsContainer as BaseContainer } from '@storybook/addon-docs/blocks';
+import { DocsContainer as BaseContainer } from '@storybook/blocks';
 import { useDarkMode } from 'storybook-dark-mode';
 import { themes } from '@storybook/theming';
 
-export const DocsContainer = ({ children, context }) => {
+export const DocsContainer = ({ children, context, ...rest }) => {
   const dark = useDarkMode();
 
   return React.createElement(
     BaseContainer,
     {
-      context: {
-        ...context,
-        storyById: (id) => {
-          const storyContext = context.storyById(id);
-          return {
-            ...storyContext,
-            parameters: {
-              ...storyContext?.parameters,
-              docs: {
-                ...storyContext?.parameters?.docs,
-                theme: dark ? themes.dark : themes.light,
-              },
-            },
-          };
-        },
-      },
+      ...rest,
+      context,
+      theme: dark ? themes.dark : themes.light,
     },
     children,
   );

```

So obviously something changed in how DocsContainer works. But if you think this is the expected result so feel free to close issue.

**Comment by tmeasday** [comment] 2023-01-02 20:59
@7rulnik I don't think the page reload is expected, so there is some kind of bug here, if you can put together a reproduction, I'd like to take a look.

As for the diff about I guess I'd say a couple things:
1. Previously you weren't passing `...rest` into `BaseContainer` which I think would cause a bug as there's another prop `theme` (as you are setting now) -- was this code you were migrating from 6.5? Maybe we need a note in `MIGRATION.md` about this, WDYT @shilman?
2. I think the way you are overriding the theme here is correct, and the way you were doing it before was... I'm not sure, but best avoided now.

**Comment by 7rulnik** [comment] 2023-01-03 02:03
@tmeasday thanks for your response.
I am on vacation right now so I will try to make reproduction after 9th of January

**Comment by shilman** [comment] 2023-01-03 08:13
@tmeasday Migration update SGTM though this is pretty niche.

**Comment by will-stone** [comment] 2023-01-16 17:05
Weirdly, I've found the polling happens in all stories at different rates depending on the browser. In Chrome it can take minutes, whereas in Firefox it's about every 20 seconds.

**Comment by tmeasday** [comment] 2023-02-22 02:37
@7rulnik have you seen this one again?

**Comment by tmeasday** [comment] 2023-02-22 02:38
@will-stone -- I'm not sure you are describing the same problem; it sounds like for @7rulnik it happens pretty quicky, not on an interval of 20+ seconds.. I'm not aware of anything in SB that is on that kind of timer, could it be something in your own code that is causing the refresh?

**Comment by joriswitteman** [comment] 2023-04-24 14:59
I'm having this problem after having migrated to v7. What can I do to diagnose?

**Comment by tmeasday** [comment] 2023-04-26 02:46
@joriswitteman are you using `parameters.docs.story.inline = false`? (i.e are your stories inside iframes there?)

Are you using addon links or something that would change the selected story when a story renders?

**Comment by spicattutti** [comment] 2023-04-26 06:01
I observed the cyclic loading of the Iframe when I
- upgrated SB to v7 via the provided codemods
- not yet upgraded the configuration of https://github.com/stevensacks/storybook-react-intl (see [instructions](https://github.com/stevensacks/storybook-react-intl))

So updating that config fixed the problem.

**Comment by tmeasday** [comment] 2023-05-03 05:21
Going to close this as I think it's due to a general version mismatch, probably solvable via `npx storybook@latest upgrade`.

If people are still seeing it and we can get a reproduction we can re-open or make a new issue.

**Closed by tmeasday** 2023-05-03 05:21 UTC
Labels: bug, needs reproduction, addon: docs

**Comment by NawfelBengherbiaSfeir** [comment] 2024-04-03 16:33
> I'm having this problem after having migrated to v7. What can I do to diagnose?
> 
> First the reload cycle:
> Screen.Recording.2023-04-24.at.17.25.31.mov
> 
> Then this error:
> 
> ![image](https://user-images.githubusercontent.com/99750097/234043295-3a4576c0-60be-4433-b0b6-215965e36b4a.png)

I got a similar reloading issue with Storybook 8.0.5 . I had to disable autodocs in `.storybook/main.js`
