### ISSUE TITLE
"Show code" shows the code in wrong mode

### ISSUE THREAD

**Issue by lana-k** [storybookjs/storybook#18491] opened 2022-06-16 13:31 UTC
**Describe the bug**
After update from 6.4.x to 6.5.x "Show code" shows the code in "code" mode instead of "auto". If click "reset controls" or change any value in controls then the source is shown in "auto" mode.

**To Reproduce**
-  open story -> Docs
-  click "Show code"

**Result** - "code":

```
(args, { argTypes }) => ({
    props: Object.keys(argTypes),
    components: { badge: BadgeComponent },
    template: '<badge v-bind="$props">Text example</badge>',
})
``` 

**Expected result** - "auto":

```
<template><badge>Text example</badge></template>
```
- Click "reset controls"

**Result** - source is changed to correct mode:
```
<template><badge>Text example</badge></template>
```

**Additional context**
        "@storybook/addon-a11y": "^6.5.9",
        "@storybook/addon-actions": "^6.5.9",
        "@storybook/addon-essentials": "^6.5.9",
        "@storybook/addon-links": "^6.5.9",
        "@storybook/addon-postcss": "^2.0.0",
        "@storybook/builder-webpack5": "^6.5.9",
        "@storybook/manager-webpack5": "^6.5.9",
        "@storybook/vue": "^6.5.9",

**Comment by mokone91** [comment] 2022-06-21 13:05
Same problem after upgrading. any solution?

**Comment by mokone91** [comment] 2022-08-18 07:10
any updates?

**Comment by captainspring** [comment] 2022-09-15 10:12
I have the same problem as well, also vue + storybook@6.5.9. :(

**Comment by patrick-pf** [comment] 2022-09-16 13:07
Same problem 6.5.10

**Comment by jevgenigavrilov** [comment] 2022-12-05 08:10
yes, same here (vue2). Did you guys manage to find a workaround?

**Comment by Hanawa02** [comment] 2022-12-12 12:30
Same here:
vue-2
storybook/vue: 6.5.14

![image](https://user-images.githubusercontent.com/11237366/207045615-63fcbd57-4791-4f37-8e92-e7f659d730e1.png)

**Comment by jevgenigavrilov** [comment] 2022-12-12 15:11
@Hanawa02 I am also using bootstrap-vue and have the same issue. One thing I noticed is that when passing `auto` to `docs.source.type` storybook previews the code as rendered output
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/39730167/207080949-5733fe3e-2393-47ba-975d-248951d1e86e.png">

**Comment by Hanawa02** [comment] 2023-02-06 12:45
@jevgenigavrilov Thanks for pointing that out!

Sadly this is not working when I try to set it globally, only when I do it for individual stories, and that is not scalable 😢 

Do you know if there is any trick to applying this to all stories?

I tried adding it to `parameters` and also to `decorators` in `preview.js`

**Comment by oemer-sellwerk** [comment] 2023-02-15 08:22
> @jevgenigavrilov Thanks for pointing that out!
> 
> Sadly this is not working when I try to set it globally, only when I do it for individual stories, and that is not scalable 😢
> 
> Do you know if there is any trick to applying this to all stories?
> 
> I tried adding it to `parameters` and also to `decorators` in `preview.js`

Yes, this doesn't even work on story-file-level `parameters` definition:
```js
export default {
  title: "Stories/SomeComponent",
  component: SomeComponent, 
  parameters: {
    docs: {
      type: "auto", 
    }
  },
}
// ...
export const FirstStory = Template.bind({}) // doesn't inherit parameters definition
export const SecondStory = Template.bind({}) // doesn't inherit parameters definition
```

It only works on the individual story:
```js
FirstStory.parameters = {
  docs: {
    type: "auto", // works
  },
}

SecondStory.parameters = {
  docs: {
    type: "auto", // works
  },
}
```

I will revert to `6.4.22` (latest `6.4.*` release)  until this is resolved.
```json
"@storybook/addon-a11y": "6.4.22",
"@storybook/addon-essentials": "6.4.22",
"@storybook/addon-links": "6.4.22",
"@storybook/vue": "6.4.22",
```

**Comment by Hanawa02** [comment] 2023-02-15 08:48
> > @jevgenigavrilov Thanks for pointing that out!
> > Sadly this is not working when I try to set it globally, only when I do it for individual stories, and that is not scalable 😢
> > Do you know if there is any trick to applying this to all stories?
> > I tried adding it to `parameters` and also to `decorators` in `preview.js`
> 
> Yes, this doesn't even work on story-file-level `parameters` definition:
> 
> ```js
> export default {
>   title: "Stories/SomeComponent",
>   component: SomeComponent, 
>   parameters: {
>     docs: {
>       type: "auto", 
>     }
>   },
> }
> // ...
> export const FirstStory = Template.bind({}) // doesn't inherit parameters definition
> export const SecondStory = Template.bind({}) // doesn't inherit parameters definition
> ```
> 
> It only works on the individual story:
> 
> ```js
> FirstStory.parameters = {
>   docs: {
>     type: "auto", // works
>   },
> }
> 
> SecondStory.parameters = {
>   docs: {
>     type: "auto", // works
>   },
> }
> ```
> 
> I will revert to `6.4.22` (latest `6.4.*` release) until this is resolved.
> 
> ```json
> "@storybook/addon-a11y": "6.4.22",
> "@storybook/addon-essentials": "6.4.22",
> "@storybook/addon-links": "6.4.22",
> "@storybook/vue": "6.4.22",
> ```

@oemer-sellwerk you're missing the `source` in your story-file-level parameters:
<img width="306" alt="image" src="https://user-images.githubusercontent.com/11237366/218978408-46702dac-87a0-4f3e-b5f5-9f2fd2aaec12.png">

**Comment by shilman** [comment] 2023-02-15 09:18
We've updated the Vue source handling in 7.0. Has anybody tried upgrading to the latest prerelease?

Migration guide: https://storybook.js.org/migration-guides/7.0

**Comment by Hanawa02** [comment] 2023-03-10 09:27
Hi @shilman, we didn't update to Storybook 7 yet, I'll schedule to try to update hopefully next week.

**Comment by paulgv** [comment] 2023-04-26 18:05
We're seeing this with Storybook 7.0.7: https://gitlab-org.gitlab.io/gitlab-ui/?path=/docs/base-accordion--docs. Here's our config: https://gitlab.com/gitlab-org/gitlab-ui/-/blob/c53747427f99d8bf7fe7af4bf5e0e2a124115fc7/.storybook/main.js.

**Comment by Hanawa02** [comment] 2023-06-02 11:31
@shilman After updating to Storybook 7, the issue was fixed. ✅

**Comment by Hanawa02** [comment] 2023-06-02 11:33
@paulgv I'm not sure if you already updated, but looking at your story it all seems to be working fine:
![image](https://github.com/storybookjs/storybook/assets/11237366/dfdf3b96-4a5d-4b87-9764-0ed1a438c7cf)
I did notice that the code styles are not the most readable tho.

**Comment by shilman** [comment] 2023-06-02 22:57
Thanks for the heads up @Hanawa02! Closing this for now. Please let me know if there's more to be done here!

**Closed** 2023-06-02 22:57 UTC
Labels: bug, vue, block: source

**Comment by paulgv** [comment] 2023-06-13 11:54
@Hanawa02 Ah, it looks like I was referring to a slightly different issue. You're right, the code does render properly initially. The issue we had was that the Vue template was replaced with the story code whenever we changed a control below the default story. In recent Storybook versions, the issue is slightly different: the code block doesn't seem to react to controls changes at all. This is somewhat better, but it'd be really great if the code block could reflect selected controls. This used to work, I can't remember in what version, but it did, so hopefully we can bring this back 🤞

**Comment by Hanawa02** [comment] 2023-06-13 12:10
@paulgv indeed I think it's a slightly different issue. I also checked on our stories and we have the same issue. @shilman should we open another issue for this other issue?

In resume: code snippet is not updated when component arguments are changed.

**Comment by paulgv** [comment] 2023-06-19 11:30
@Hanawa02 Created a new issue over here: https://github.com/storybookjs/storybook/issues/23132
