### ISSUE TITLE
Displaying imported HTML in Storysource

### ISSUE THREAD

**Issue by danhead** [storybookjs/storybook#8297] opened 2019-10-04 19:44 UTC
### Support request summary

I would like to be able to display imported HTML in the Storysource panel, rather than the contents of the `.stories.js` file.

### Steps to reproduce

1. Create a new package and create/amend the two files below:

__html/button.html:__
```html
<button>Hello world</button>
```

__stories/index.stories.js:__
```js
import button from '../html/button.html';

export default {
  title: 'Demo',
};

export const Button = () => button;
```

2. Set up Storysource addon as per package [README](https://github.com/storybookjs/storybook/blob/next/addons/storysource/README.md)

__.storybook/addons.js__
```js
import '@storybook/addon-storysource/register';
```

__.storybook/webpack.config.js__
```js
module.exports = function({ config }) {
  config.module.rules.push({
    test: /\.stories\.jsx?$/,
    loaders: [require.resolve('@storybook/source-loader')],
    enforce: 'pre',
  });

  return config;
};
```

### Please specify which version of Storybook and optionally any affected addons that you're running

- @babel/core@7.6.2
- @storybook/addon-storysource@5.2.1
- @storybook/html@5.2.1
- babel-loader@8.0.6

### Expected result

I would like the Storysource panel to display the contents of `html/button.html`

### Actual result

Storysource panel shows contents of `stories/index.stories.js`

![image](https://user-images.githubusercontent.com/3179479/66234747-669de080-e6e6-11e9-89d0-14c708a0999a.png)

Any advice on how to achieve this is greatly appreciated.

Thanks!

**Comment by danhead** [comment] 2019-10-17 19:15
Just a quick follow up to this, in older versions of @storybook/html (v5.1.9) I used to do this with success:

**.storybook/config.js**
```js
import { withStorySource } from '@storybook/addon-storysource';
addDecorator((storyFn, context) => {
  const source = storyFn()
  return withStorySource(source)(storyFn, context)
})
```

However with @storybook/html@5.2.x upwards I get the following error with this technique:

```
storybook_ui_dll.js:2 TypeError: Cannot read property 'source' of undefined
    at StoryPanel._this.listener (main.8e749501743145db6330.bundle.js:9344)
    at storybook_ui_dll.js:2
    at Array.forEach (<anonymous>)
    at t.value (storybook_ui_dll.js:2)
    at PostmsgTransport.<anonymous> (storybook_ui_dll.js:2)
    at PostmsgTransport.handler (main.8e749501743145db6330.bundle.js:10423)
    at PostmsgTransport.handleEvent (main.8e749501743145db6330.bundle.js:1051
```

**Comment by danhead** [comment] 2019-10-17 20:05
I believe this is the change that has introduced the issue: https://github.com/storybookjs/storybook/pull/7272/files#diff-904dad7f92c7bbfac64aca74960bbf33

**Comment by shilman** [comment] 2019-10-18 00:34
@libetl do you have any time to look at @danhead 's example above?

> storybook_ui_dll.js:2 TypeError: Cannot read property 'source' of undefined
    at StoryPanel._this.listener (main.8e749501743145db6330.bundle.js:9344)
    at storybook_ui_dll.js:2
    at Array.forEach (<anonymous>)
    at t.value (storybook_ui_dll.js:2)
    at PostmsgTransport.<anonymous> (storybook_ui_dll.js:2)
    at PostmsgTransport.handler (main.8e749501743145db6330.bundle.js:10423)
    at PostmsgTransport.handleEvent (main.8e749501743145db6330.bundle.js:1051

**Comment by LeeBurton** [comment] 2020-01-16 15:34
@shilman You added a "TODO" label but didn't re-open the issue. It still appears to have problems, which appear to be related to the changes mentioned by @danhead:

https://github.com/storybookjs/storybook/pull/7272/files#diff-904dad7f92c7bbfac64aca74960bbf33

I am trying to use the following:

`.addDecorator(withStorySource('my test source'))`

but nothing changes in the Storysource panel.

I debugged the "storybook/source-loader/set" event parameters, and the source added by register has the following event parameters:

`edition: {source: '...', …}, story: {…}, location: {…}`

but the events triggered by "withStorysource" have the following event parameters:

`source: "my test source", currentLocation: undefined, locationsMap: {…}`

I guess that setStorySource() needs updating to work with the new format?

**Comment by LeeBurton** [comment] 2020-01-20 15:41
@shilman @igor-dv @libetl

I created a pull request with a fix for the issue I described above:

    https://github.com/storybookjs/storybook/pull/9561

If you try to use `withStorySource(source)` in `addDecorator`, and the '@storybook/source-loader' is added to the storybook webpack config, with "injectDecorator" set to true, the story decorators are executed first, then overwritten by the decorators injected by the webpack loader... is this expected behaviour? I would expect the injected decorator to load first, followed by the global stories decorator, followed by story-specific changes...

If this is the expected behaviour, how can I override it so that I can overwrite the storysource in specific stories?

**Comment by atanasster** [comment] 2020-01-20 16:55
@LeeBurton thanks for taking the time to file this pull request.

For 6+, storybook is moving away from addDecorator: https://github.com/storybookjs/storybook/issues/9506 and I just filed a refactor of source-loader here: https://github.com/storybookjs/storybook/pull/9547 

Would you like us to work together on adapting your use case to use parameters instead of addDecorator with the new code base? 

@shilman ?

**Comment by atanasster** [comment] 2020-01-20 18:19
An example of using storySource parameters: 
https://github.com/storybookjs/storybook/pull/9547/files#diff-f9e4c1787dc63502454a68f7ff88245c

**Comment by LeeBurton** [comment] 2020-01-20 20:30
We are using the HTML version to include web components, rather than React, so I guess that we are a little limited with what we can do in the stories.

It would be useful if I could somehow set a parameter within the stories, then access that parameter within a global decorator to emit an event to update the source panel.

Currently, the only solution I have found is to emit the event in the stories. This also solves the problem that the Webpack loader injected decorator story source is overwriting the story decorator source (but only with my pull request changes, otherwise the wrong parameters are provided to emit().

**Comment by LeeBurton** [comment] 2020-01-20 20:32
Plus, this should also be tagged as a bug, I guess.

**Comment by atanasster** [comment] 2020-01-20 20:57
@LeeBurton - did you check the example, it does not use events at all and this makes it to also work for the docs tab (the source-loader events were only working for the StorySource panel):

```
import button from './button.html';

 export default {
   title: 'Addons/Source loader',
 };

 export const Button = () => button;
 Button.story = {
   parameters: {
     storySource: {
       source: button,
     },
   },
 };
```

**Comment by LeeBurton** [comment] 2020-01-20 21:42
I’ll explain a little more about what I’m trying to achieve, as I’m not sure how this helps with my problem.

The story uses a template string with our custom elements, such as:

`<my-grid
    title=“my title”
    rows=3>
</my-grid>`

and I am then populating it with data by setting the “data” attribute.

So I need to document our grid component HTML code, but also the necessary code populating various attributes, including the example JSON data.

The grid component includes pagination. When a paging button is clicked, the next page of data is fetched from the backend API and used to update the “data” attribute. I need to show the developers how the data is changing when events such as paging occurs.

**Comment by atanasster** [comment] 2020-01-21 00:54
Thanks @LeeBurton I think we can have a 'dynamic' `storySource` parameter - ie a function that will be called at runtime, so you can entirely customize what source code to display for the developers. 

@shilman - any thoughts?

**Comment by shilman** [comment] 2020-01-21 01:17
@atanasster @LeeBurton Parameters cascade, so global parameters can be overridden at a story level, just as you have done in your comment above @atanasster . I don't think we need to do anything special to support user configuration. Maybe just better documentation on how to do it.

**Comment by LeeBurton** [comment] 2020-01-21 07:52
1. `withSource(...)` doesn’t work when the source loader is used in webpack. It injects a decorator which overwrites the value set by the `withSource` decorator. The same goes for `storySource` added to a story’s parameters...

2. How can parameters be updated dynamically within a story?

**Comment by shilman** [comment] 2020-01-21 10:04
you can create separate stories for each state that you want to show. in the future we may try to support more interaction scenarios, but we have our hands pretty full with doing a great job of simply showing every state. you can also link between stories with `addon-links` to fake interactivity.

**Comment by LeeBurton** [comment] 2020-01-21 10:30
I greatly appreciate the hard work you guys are doing, but any assistance in achieving my goals would be greatly appreciated. My client is a government department responsible for building web components that various other government departments can use, and we are trying to convince them that Storybook is the best choice for documenting their components for developers in the other departments. If we cannot make progress quickly, they may start looking at other options.

For this particular component, I have a story that uses knobs, and interactions.

I need to be able to show documentation for the current story HTML with the attributes set (which I could get from `storyFn()` in a decorator) and also include JavaScript code. I am also listening to events within the story, by getting the element in `useEffect()` using `document.querySelector()` and then adding event listeners. when the listeners fire, I want to be able to update the documentation. Although, it seems a bit messy having to implement it like this... Are there better ways without cluttering the stories?

Is it not currently possible to update a parameter in stories (that I can access in a decorator)?

**Comment by shilman** [comment] 2020-01-21 11:07
As far as I know it's not possible to update parameters dynamically this way.

@atanasster and @ndelangen have been working on powerful addon APIs (shared state hooks) that could make sharing state between stories & addons much easier. It might be fairly easy to implement your use case using that shared state hook, and not have to deal with the entirety of storysource for that purpose.

**Comment by atanasster** [comment] 2020-01-21 14:12
@LeeBurton as michael mentioned, its not possible to modify parameters dynamically. 
However we can add a dynamic property source that would allow you to do pretty much the same thing. The best thing would be if you can join and test the upcoming sb6 alphas and give us feedback on the discord channel until me make it work as best as we can for your use case.

**Comment by LeeBurton** [comment] 2020-01-21 15:28
Okay, thanks. Unfortunately, I’m too much under pressure with my client’s project at the moment. If I have more time later, I’d love to help. When is v.6.0 release planned?

When will my bug fix pull request likely be merged to fix the storySource event parameters to the correct format? Currently my workaround won’t work without these changes merged...

**Comment by LeeBurton** [comment] 2020-01-22 10:16
> @LeeBurton - did you check the example, it does not use events at all and this makes it to also work for the docs tab (the source-loader events were only working for the StorySource panel):
> 
> ```
> import button from './button.html';
> 
>  export default {
>    title: 'Addons/Source loader',
>  };
> 
>  export const Button = () => button;
>  Button.story = {
>    parameters: {
>      storySource: {
>        source: button,
>      },
>    },
>  };
> ```

@atanasster When I set the `storySource.source` parameter, it does nothing. It just says “Loading source...” 😳

**Comment by atanasster** [comment] 2020-01-22 10:21
@LeeBurton - are you trying the PR, its not yet merged.

If yes, please try the html-kitchen sink example https://github.com/storybookjs/storybook/pull/9547/files#diff-f9e4c1787dc63502454a68f7ff88245c

**Comment by LeeBurton** [comment] 2020-01-22 15:22
@atanasster I don’t understand what you mean by “are you trying the PR”... which PR?

And still no response regarding `withSource` not working and being overwritten by the Webpack-injected decorator. From what I understand, the injected one should execute and set the parameter first, and `withSource` overwrite it...?

**Comment by atanasster** [comment] 2020-01-22 18:12
@LeeBurton - yes i meant the listed PR from above.

That PR is meant for 6.0 and @shilman would know about the merging, but i think he is currently very busy with the 5.3 updates.

**Comment by shilman** [comment] 2020-01-23 01:39
I can probably merge/release an alpha today, but I want to do another review & test it first. Juggling a lot.

**Comment by lmcmill** [comment] 2020-01-28 11:53
`storySource.source` - still seems to have no effect, when can we expect this to work?

**Comment by shilman** [comment] 2020-01-29 05:37
Will release this in 6.0-alpha on Thu at earliest, Sat at latest. Currently in a remote area with poor network connection, and unfortunately the release process requires a good connection. Thanks for your patience.

**Comment by juniovitorino** [comment] 2020-06-13 17:23
> @LeeBurton - did you check the example, it does not use events at all and this makes it to also work for the docs tab (the source-loader events were only working for the StorySource panel):
> 
> ```
> import button from './button.html';
> 
>  export default {
>    title: 'Addons/Source loader',
>  };
> 
>  export const Button = () => button;
>  Button.story = {
>    parameters: {
>      storySource: {
>        source: button,
>      },
>    },
>  };
> ```

This works great, now could someone say how write a storydocs for a example like that?

**Comment by shilman** [comment] 2020-06-14 00:12
@juniovitorino like this?

> import button from './button.html';

 export default {
   title: 'Addons/Source loader',
 };

 export const Button = () => button;
 Button.story = {
   parameters: {
     storyDescription: 'some description here',
     storySource: {
       source: button,
     },
   },
 };

**Comment by radum** [comment] 2020-08-26 16:13
@shilman Am I right that the correct format now is

```js
import button from './button.html';

 export default {
   title: 'Addons/Source loader',
 };

 export const Button = () => button;
 Button.parameters = {
   storyDescription: 'some description here',
   storySource: {
     source: button,
   },
};
```

**Comment by shilman** [comment] 2023-06-08 02:29
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

**Closed by shilman** 2023-06-08 02:29 UTC
Labels: feature request, question / support, todo, addon: storysource
