### ISSUE TITLE
Storybook hooks broken in `next`

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#12977] opened 2020-11-02 02:47 UTC
Getting this Storybook hooks-related error:

<img width="840" alt="Addons___A11y___BaseButton_-_Default_⋅_Storybook" src="https://user-images.githubusercontent.com/488689/97825055-8e4fe580-1cf8-11eb-86d3-d2b7938c49b7.png">

This occurred somewhere between the `6.1-alpha.32` and `6.1-alpha.33` releases.

**Comment by tmeasday** [comment] 2020-11-02 03:15
Changing the decorator in `preview.js` to call `StoryFn()` rather than `<StoryFn/>` "solves" the problem.

The root problem is likely due to this though:


```
yarn why react                                                                       SIGINT(2) ↵  10308  14:10:21
yarn why v1.16.0
[1/4] 🤔  Why do we have the module "react"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "react@16.13.1"
info Has been hoisted to "react"
info Reasons this module exists
   - "workspace-aggregator-b24fde1d-a57f-4f79-975d-5ebe97a4487b" depends on it
   - Specified in "devDependencies"
   - Hoisted from "_project_#react"
   - Hoisted from "_project_#@storybook#react#react"
   - Hoisted from "_project_#@storybook#addon-parameter#react"
   - Hoisted from "_project_#@storybook#addon-preview-wrapper#react"
   - Hoisted from "_project_#@storybook#addon-roundtrip#react"
   - Hoisted from "_project_#cra-kitchen-sink#react"
   - Hoisted from "_project_#cra-ts-essentials#react"
   - Hoisted from "_project_#cra-ts-kitchen-sink#react"
   - Hoisted from "_project_#@storybook#example-devkits#react"
   - Hoisted from "_project_#official-storybook#react"
   - Hoisted from "_project_#@storybook#example-react-ts#react"
   - Hoisted from "_project_#standalone-preview#react"
   - Hoisted from "_project_#@storybook#addon-a11y#react"
   - Hoisted from "_project_#@storybook#addon-actions#react"
   - Hoisted from "_project_#@storybook#addon-backgrounds#react"
   - Hoisted from "_project_#@storybook#addon-controls#react"
   - Hoisted from "_project_#@storybook#addon-cssresources#react"
   - Hoisted from "_project_#@storybook#addon-design-assets#react"
   - Hoisted from "_project_#@storybook#addon-docs#react"
   - Hoisted from "_project_#@storybook#addon-essentials#react"
   - Hoisted from "_project_#@storybook#addon-events#react"
   - Hoisted from "_project_#@storybook#addon-google-analytics#react"
   - Hoisted from "_project_#@storybook#addon-graphql#react"
   - Hoisted from "_project_#@storybook#addon-jest#react"
   - Hoisted from "_project_#@storybook#addon-knobs#react"
   - Hoisted from "_project_#@storybook#addon-links#react"
   - Hoisted from "_project_#@storybook#addon-queryparams#react"
   - Hoisted from "_project_#@storybook#addon-toolbars#react"
   - Hoisted from "_project_#@storybook#addon-viewport#react"
   - Hoisted from "_project_#@storybook#addon-storyshots#react"
   - Hoisted from "_project_#@storybook#addons#react"
   - Hoisted from "_project_#@storybook#api#react"
   - Hoisted from "_project_#@storybook#client-api#react"
   - Hoisted from "_project_#@storybook#components#react"
   - Hoisted from "_project_#@storybook#core#react"
   - Hoisted from "_project_#@storybook#router#react"
   - Hoisted from "_project_#@storybook#source-loader#react"
   - Hoisted from "_project_#@storybook#theming#react"
   - Hoisted from "_project_#@storybook#ui#react"
   - Hoisted from "_project_#@storybook#addon-storysource#react"
info Disk size without dependencies: "244KB"
info Disk size with unique dependencies: "432KB"
info Disk size with transitive dependencies: "512KB"
info Number of shared dependencies: 5
=> Found "cra-react15#react@15.6.2"
info This module exists because "_project_#cra-react15" depends on it.
info Disk size without dependencies: "708KB"
info Disk size with unique dependencies: "6.31MB"
info Disk size with transitive dependencies: "14.52MB"
info Number of shared dependencies: 13
✨  Done in 2.32s.
```

```
yarn why react-dom                                                                             ✔  10309  14:10:24
yarn why v1.16.0
[1/4] 🤔  Why do we have the module "react-dom"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "react-dom@17.0.1"
info Has been hoisted to "react-dom"
info Reasons this module exists
   - "workspace-aggregator-3d2de3da-4486-436f-8ca6-027e8260c16b" depends on it
   - Specified in "devDependencies"
   - Hoisted from "_project_#react-dom"
   - Hoisted from "_project_#@storybook#addon-a11y#react-dom"
   - Hoisted from "_project_#@storybook#addon-actions#react-dom"
   - Hoisted from "_project_#@storybook#addon-backgrounds#react-dom"
   - Hoisted from "_project_#@storybook#addon-controls#react-dom"
   - Hoisted from "_project_#@storybook#addon-cssresources#react-dom"
   - Hoisted from "_project_#@storybook#addon-design-assets#react-dom"
   - Hoisted from "_project_#@storybook#addon-docs#react-dom"
   - Hoisted from "_project_#@storybook#addon-essentials#react-dom"
   - Hoisted from "_project_#@storybook#addon-events#react-dom"
   - Hoisted from "_project_#@storybook#addon-google-analytics#react-dom"
   - Hoisted from "_project_#@storybook#addon-graphql#react-dom"
   - Hoisted from "_project_#@storybook#addon-jest#react-dom"
   - Hoisted from "_project_#@storybook#addon-knobs#react-dom"
   - Hoisted from "_project_#@storybook#addon-links#react-dom"
   - Hoisted from "_project_#@storybook#addon-queryparams#react-dom"
   - Hoisted from "_project_#@storybook#addon-storysource#react-dom"
   - Hoisted from "_project_#@storybook#addon-toolbars#react-dom"
   - Hoisted from "_project_#@storybook#addon-viewport#react-dom"
   - Hoisted from "_project_#@storybook#addon-storyshots#react-dom"
   - Hoisted from "_project_#@storybook#react#react-dom"
   - Hoisted from "_project_#cra-kitchen-sink#react-dom"
   - Hoisted from "_project_#cra-ts-essentials#react-dom"
   - Hoisted from "_project_#cra-ts-kitchen-sink#react-dom"
   - Hoisted from "_project_#@storybook#example-devkits#react-dom"
   - Hoisted from "_project_#official-storybook#react-dom"
   - Hoisted from "_project_#@storybook#example-react-ts#react-dom"
   - Hoisted from "_project_#standalone-preview#react-dom"
   - Hoisted from "_project_#@storybook#addons#react-dom"
   - Hoisted from "_project_#@storybook#api#react-dom"
   - Hoisted from "_project_#@storybook#client-api#react-dom"
   - Hoisted from "_project_#@storybook#components#react-dom"
   - Hoisted from "_project_#@storybook#core#react-dom"
   - Hoisted from "_project_#@storybook#router#react-dom"
   - Hoisted from "_project_#@storybook#source-loader#react-dom"
   - Hoisted from "_project_#@storybook#theming#react-dom"
   - Hoisted from "_project_#@storybook#ui#react-dom"
info Disk size without dependencies: "3.15MB"
info Disk size with unique dependencies: "3.39MB"
info Disk size with transitive dependencies: "3.42MB"
info Number of shared dependencies: 4
=> Found "cra-react15#react-dom@15.6.2"
info This module exists because "_project_#cra-react15" depends on it.
info Disk size without dependencies: "2.5MB"
info Disk size with unique dependencies: "8.02MB"
info Disk size with transitive dependencies: "16.23MB"
info Number of shared dependencies: 12
✨  Done in 4.44s.
```

**Comment by shilman** [comment] 2020-11-02 06:14
@tmeasday I fixed the react version in #12978 but it did not fix the problem

**Comment by shilman** [comment] 2020-11-02 18:41
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-beta.0 containing PR #12988 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment] 2020-11-02 18:42
still broken

**Comment by KevinGhadyani-minted** [comment] 2021-01-08 23:52
With `decorators` defined in `preview.js`, I commented out `@storybook/addon-essentials` and the hooks messages went away:

![image](https://user-images.githubusercontent.com/45860344/104075990-3511a000-51da-11eb-82ca-eaa58febcd85.png)

**Comment by KevinGhadyani-minted** [comment] 2021-01-08 23:59
```js
  addons: [
    {
      name: '@storybook/addon-essentials',
      options: {
        actions: true,
        backgrounds: false,
        controls: true,
        docs: true,
        toolbars: true,
        viewport: true,
      },
    },
    '@storybook/addon-links',
  ],
```

More-specifically, it's the `backgrounds` option that causes this issue.

**Comment by shilman** [comment] 2021-02-25 09:34
cc @yannbf

**Comment by yannbf** [comment] 2021-02-25 09:40
Thanks for pinging me @shilman !

So the problem could be related to useMemo [here](https://github.com/storybookjs/storybook/blob/bc90fab5180daf55d7a10a5c72e8d9392e4c0361/addons/backgrounds/src/decorators/withBackground.ts#L11) (and other places, also in the withGrid decorator).. although I thought that was the correct way to use, coming from @storybook/addons.. @ndelangen any thoughts on this?

**Comment by KevinGhadyani-minted** [comment] 2021-03-01 18:24
Along with what @tmeasday is saying, is it possible `withBackground` is applied and then not applied conditionally?

https://github.com/storybookjs/storybook/blob/bc90fab5180daf55d7a10a5c72e8d9392e4c0361/addons/backgrounds/src/preset/addDecorator.tsx

Looking at this file, it looks like it's exported and wrapped around components when `decorators` is defined. I don't know what function uses that data, but maybe it's there?

**Comment by jagregory** [comment] 2021-04-01 01:29
I'm seeing this issue too ever since upgrading to 6. Disabling the background addon fixes it.

**Comment by KevinGhadyani-minted** [comment] 2021-04-01 02:47
On a fresh install in 2 completely greenfield projects, I haven't noticed this. Is it fixed?

**Comment by shilman** [comment] 2021-04-01 03:14
we didn't do anything to fix it. i think it's some corner case that arises from cross-package interactions -- i've certainly never seen this problem myself

**Comment by KevinGhadyani-minted** [comment] 2021-04-01 05:16
That would make more sense. The other projects where I've seen it are existing projects with their own dependencies that were later upgraded to Storybook 6.1.

**Comment by jagregory** [comment] 2021-04-02 23:32
I managed to do a bit more investigation and it seems to be some combination of the background addon and **storybook-addon-apollo-client** for me. If I have that addon last in the list (which their docs example shows) then I get the hooks error, but if I move it to before the essentials addon then everything works as expected.

**Comment by shilman** [comment] 2021-04-03 00:50
cc @yannbf @lifeiscontent ☝️

**Comment by lifeiscontent** [comment] 2021-04-03 02:30
@shilman this is the issue I mentioned to you earlier. It seems like there might be more than one reason for this error. One of the reasons this can happen is due to having multiple versions of Apollo installed so when the addon tries to register it uses a different version than the one expected. I generally fix this using the yarn resolutions feature in the package.json but there could be another issue in the code of the Apollo addon and I'd love to get a review from someone more knowledgeable about the storybook hooks so we could potentially uncover it.

**Comment by lifeiscontent** [comment] 2021-04-03 02:32
If anyone can put together a reproduction that would be very helpful. If anyone does manage to track it down feel free to open an issue on the Apollo addon GitHub. I'd love to fix it, but I need more context on the problem in order to make a proper change.

**Comment by shilman** [comment] 2021-04-05 03:34
@yannbf Feels like this is an `addon-backgrounds` issue: #14469

**Comment by gpolanco** [comment] 2021-04-08 14:16
This problem is solved in the latest update?

I have version 6.2.4, and I have this same error

**Comment by yannbf** [comment] 2021-04-08 20:17
Hey @gpolanco could you please paste here your main.js file? the addons section of it

**Comment by valentinpalkovic** [comment] 2024-02-19 22:53
Since we don't have any reaction on this issue for over 2 1/2 years, I will close it. Please let us know if the issue still exists on the latest version of Storybook.

**Closed by valentinpalkovic** 2024-02-19 22:53 UTC
Labels: bug, has workaround, addon: backgrounds
