### ISSUE TITLE
Update Storybook 6.2 :  TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by patou** [storybookjs/storybook#14631] opened 2021-04-16 11:17 UTC
**Describe the bug**
I try migrate my angular application to storybook 6.2 from 6.1.
Stories component not display, we have instead a black background with a red border (screenshot below) and we have a javscript error : TypeError: Cannot convert undefined or null to object

**Javascript Error**

```
vendors~main.iframe.bundle.js:144634 TypeError: Cannot convert undefined or null to object
    at getPrototypeOf (<anonymous>)
    at r.parse (vendors~main.iframe.bundle.js:207406)
    at Object.t.parse (vendors~main.iframe.bundle.js:207430)
    at Mn (vendors~main.iframe.bundle.js:207472)
    at Un (vendors~main.iframe.bundle.js:207661)
    at Object.parse (vendors~main.iframe.bundle.js:207707)
    at Object.parse (vendors~main.iframe.bundle.js:207776)
    at ts (vendors~main.iframe.bundle.js:207776)
    at us (vendors~main.iframe.bundle.js:207776)
    at vendors~main.iframe.bundle.js:207806
```

**Screenshots**
![image](https://user-images.githubusercontent.com/841858/115016143-fc5a2480-9eb4-11eb-9c89-d872cd17fba0.png)

**Test**
Remove storybook from the project, and add a new storybook with : `npx sb init`

If I create a new angular lib, and init storybook, it's works, but not with my project.

**System**
```
Environment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
  Binaries:
    Node: 12.11.1 - C:\PBapps\ctlm-myeclipse\nvm-1.1.7\nodejs\node.EXE
    npm: 6.13.6 - C:\PBapps\ctlm-myeclipse\nvm-1.1.7\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    @storybook/addon-actions: ^6.2.8 => 6.2.8
    @storybook/addon-essentials: ^6.2.8 => 6.2.8
    @storybook/addon-links: ^6.2.8 => 6.2.8
    @storybook/angular: ^6.2.8 => 6.2.8

C:\PBapps\ctlm-myeclipse\nvm-1.1.7\v12.11.1\node_modules\npm\node_modules\rimraf\rimraf.js:313
        throw er
        ^

Error: ENOTEMPTY: directory not empty, rmdir 'c:\Temp\npm-cache\_npx\20104\node_modules\sb\node_modules\rxjs\src\internal'
    at Object.rmdirSync (fs.js:763:3)
    at rmkidsSync (C:\PBapps\ctlm-myeclipse\nvm-1.1.7\v12.11.1\node_modules\npm\node_modules\rimraf\rimraf.js:356:25)
    at rmdirSync (C:\PBapps\ctlm-myeclipse\nvm-1.1.7\v12.11.1\node_modules\npm\node_modules\rimraf\rimraf.js:334:7)
    at rimrafSync (C:\PBapps\ctlm-myeclipse\nvm-1.1.7\v12.11.1\node_modules\npm\node_modules\rimraf\rimraf.js:304:9)
    at C:\PBapps\ctlm-myeclipse\nvm-1.1.7\v12.11.1\node_modules\npm\node_modules\rimraf\rimraf.js:342:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\PBapps\ctlm-myeclipse\nvm-1.1.7\v12.11.1\node_modules\npm\node_modules\rimraf\rimraf.js:341:26)
    at rmdirSync (C:\PBapps\ctlm-myeclipse\nvm-1.1.7\v12.11.1\node_modules\npm\node_modules\rimraf\rimraf.js:334:7)
    at rimrafSync (C:\PBapps\ctlm-myeclipse\nvm-1.1.7\v12.11.1\node_modules\npm\node_modules\rimraf\rimraf.js:304:9)
    at C:\PBapps\ctlm-myeclipse\nvm-1.1.7\v12.11.1\node_modules\npm\node_modules\rimraf\rimraf.js:342:5 {
  errno: -4051,
  syscall: 'rmdir',
  code: 'ENOTEMPTY',
  path: 'c:\\Temp\\npm-cache\\_npx\\20104\\node_modules\\sb\\node_modules\\rxjs\\src\\internal'
}
```

**Comment by shilman** [comment] 2021-04-16 14:40
Did you try removing `node_modules` and/or lockfiles and reinstalling?

**Comment by patou** [comment] 2021-04-17 12:37
> Did you try removing `node_modules` and/or lockfiles and reinstalling?

Yes, I remove all many time and reinstalling.

**Comment by shilman** [comment] 2021-04-17 12:45
Try running with `--no-manager-cache`

**Comment by dee103** [comment] 2021-04-18 22:30
I get a similar error after installing Storybook for the first time - into an existing Angular project:

![image](https://user-images.githubusercontent.com/4279721/115162882-f83d2b00-a09d-11eb-9af9-2507ede629a1.png)

Screenshot:
![image](https://user-images.githubusercontent.com/4279721/115162900-0be89180-a09e-11eb-8dc2-502bf8a96f08.png)

I have tried the suggestions above with no luck.

**Comment by certainlyakey** [comment] 2021-04-21 16:34
Same here. In my case, removing @addon-docs helped.

**Comment by kyro38** [comment] 2021-04-22 09:09
Per #14262, removing `prettier` from the regex in `node_modules\@storybook\core-common\dist\cjs\utils\es6Transpiler.js`, solves the problem. 

But that's not an acceptable workaround for me.

**Comment by igodorogea** [comment] 2021-04-22 12:43
As @certainlyakey wrote - removing `@storybook/addon-docs` solves this issue.

**Comment by kyro38** [comment] 2021-04-22 12:58
Ok to me, it meant removing `@storybook/addon-essentials` which imports addon-docs

**Comment by patou** [comment] 2021-04-22 15:28
I resolve the issus, but I not know how.
I clear cache of node, remove node module, add --no-manager-cache, add @babel/plugin-proposal-class-properties dependencies, ...

Now, I have this error :
`Type UserAccountComponent is part of the declarations of 2 modules: `

It's display the component one time, and the second view there are an error.

**Comment by certainlyakey** [comment] 2021-04-22 19:47
> Per #14262, removing `prettier` from the regex in `node_modules\@storybook\core-common\dist\cjs\utils\es6Transpiler.js`, solves the problem.
> 
> But that's not an acceptable workaround for me.

For me it's acceptable, at least until an official fix is out. I've managed to resolve the issue with both `@addon-docs` and `@whitespace/storybook-addon-html` by removing this `|prettier` string from `@storybook/core-common` and applying a patch with [patch-package](https://github.com/ds300/patch-package).

**Comment by daan93** [comment] 2021-04-23 11:11
I solved this following these steps:
1. Update @babel packages
2. Remove node_modules
3. Remove package-lock.json
4. Run npm install

Removing the |prettifier from the regex in node_modules worked too, but I didn't want to go through writing a fix in main.js. 

However now I have a different error for stories using ngmodel, like #14643

**Comment by kyro38** [comment] 2021-04-23 11:34
I went with the workaround with [patch-package](https://github.com/ds300/patch-package). 
Really simple solution 👍

**Comment by trytuna** [comment] 2021-04-26 11:45
I solved it by disabling the docs addon with still benefiting from `@storybook/addon-essentials`. Just adjust your `main.js` file like follows:

```
{
  // ...
  "addons": [
    "@storybook/addon-links",
    {
      name: '@storybook/addon-essentials',
      options: {
        docs: false,
      }
    }
  ]
}
```

**Comment by catrope** [comment] 2021-04-27 21:44
Upgrading to Storybook v6.2.9 fixed this issue for me, since it pulls in a recent enough version of Babel where the underlying bug is fixed.

**Comment by ThibaudAV** [comment] 2021-04-27 21:52
yes its a pb with Babel i think 

already fixed here
https://github.com/storybookjs/storybook/issues/14262#issuecomment-812122426
or https://github.com/storybookjs/storybook/issues/14197

**Comment by kyro38** [comment] 2021-04-28 09:15
2.6.9 fixed noting for me. 

addons-docs still pulls @babel/core 7.12.10
I was fixed in 7.12.13 per [#14262 (comment)](https://github.com/storybookjs/storybook/issues/14262#issuecomment-812122426)

**Comment by kroeder** [comment] 2021-04-28 14:04
I updated `@babel/core` to the latest version as well as `babel-loader` removed my `package-lock.json` as well as removed all `node_modules`

Reinstalling everything worked for me

**Comment by de-don** [comment] 2021-04-29 10:29
The same issue, https://github.com/storybookjs/storybook/issues/14631#issuecomment-825138535 works for me.

**Comment by alexiadorneles** [comment] 2021-06-17 12:28
I'm facing the same issue after upgrading storybook. https://github.com/storybookjs/storybook/issues/14631#issuecomment-824675245 solved for me but it is not something I can adopt in my project, can't tell every developer to install and then directly changes the `node_modules` every time we install things again.

Tried https://github.com/storybookjs/storybook/issues/14631#issuecomment-828483482 approach but unfortunately it did not work for me.

Also tried to use prerelease mentioned on https://github.com/storybookjs/storybook/issues/14752#issuecomment-843086339 and it didn't work.

Looking forward to a bugfix of this issue so I can safely upgrade it to the new version.

**Comment by pertrai1** [comment] 2021-06-26 15:07
@kyro38 what was the patch-package command you ran to patch this change?

**Comment by rickhopkins** [comment] 2021-07-16 20:07
Is this being worked on by chance? I am running into this when upgrading our storybook to 6.3.4. Hacking the node_modules file /node_modules/@storybook/core-common/dist/cjs/utils/es6Transpiler.js like was suggested above works to fix, but that's a pretty sucky hack.

**Comment by kaaku** [comment] 2021-09-30 14:16
FWIW, simply upgrading `@babel/core` and `babel-loader` (to latest) wasn't enough for me, since `yarn.lock` still contained multiple versions of said packages (and e.g. many babel plugins), which caused the problem to persist. Deleting the lockfile would've been a bit too radical for our project, but removing the duplicate babel packages was enough to fix the problem. I used [yarn-deduplicate](https://github.com/atlassian/yarn-deduplicate) like this:

```
npx yarn-deduplicate --scopes '@babel'
npx yarn-deduplicate --packages 'babel-loader'
```

So this wasn't really a problem in Storybook, but simply poorly managed dependencies.

**Comment by adimit** [comment] 2022-04-26 20:32
Here's a minimal config that gets me this error. Removing `prettier` from `es6Transpile` as stated [earlier](https://github.com/storybookjs/storybook/issues/14631#issuecomment-824675245) does not solve it. I'm using this config to start a new repository from scratch, so no re-installation or anything nor are there any interactions (ha) between storybook addons, as I'm not using any beyond `@storybook/addons-interaction`; this is a clean reproduction on my system (yarn 1.22.5, node v16.14.2)

(For convenience, I've created a [repository](https://github.com/adimit/repro-storybook-14631). Feel free to check it out.)

`package.json`:
```json
{
  "scripts": {
    "storybook": "start-storybook -p 9001 -c .storybook"
  },
  "dependencies": {
    "react": "^17.0.2",
    "react-dom": "17.0.2"
  },
  "devDependencies": {
    "@storybook/addon-interactions": "^6.3.12",
    "@storybook/react": "6.3.12",
    "@types/react": "^17.0.37",
    "@types/react-dom": "^17.0.11",
    "react-scripts": "^4.0.3",
    "typescript": "4.6.3"
  }
}
```

`.storybook/main.js`
```js
module.exports = {
  stories: ["../src/*.stories.tsx"],
  addons: ["@storybook/addon-interactions"],
};
```

And a couple of test files:

`src/Test.tsx`
```typescript
import * as React from "react";

export const Component: React.FC = () => {
  return <span>I am a test</span>;
};
```

`src/Test.stories.tsx`
```typescript
import * as React from "react";
import { Component } from "./Test";

export default {
  title: "test",
  component: Component,
};

export const Test = () => <Component />;
```

**Comment by shilman** [comment] 2023-06-08 02:55
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

**Closed by shilman** 2023-06-08 02:55 UTC
Labels: question / support, has workaround, angular
