### ISSUE TITLE
Storybook setup with Tailwind and Emotion

### ISSUE THREAD

**Issue by WebTerminator** [storybookjs/storybook#12114] opened 2020-08-18 15:21 UTC
**Describe the bug**
When setting up Emotion with Tailwind I get the following error: `Module not found: Error: Can't resolve '@emotion/styled/base'`

**Expected behavior**
Should be able to use Emotion with Tailwind

**Screenshots**
![image](https://user-images.githubusercontent.com/4947347/90532231-e4d46b80-e16e-11ea-874e-b815ce5687e9.png)

**Additional context**
my package.json file:

  "dependencies": {
    "@babel/core": "^7.8.4",
    "@emotion/babel-plugin": "^11.0.0-next.13",
    "@emotion/core": "^10.0.27",
    "@emotion/css": "^11.0.0-next.12",
    "@emotion/react": "^11.0.0-next.15",
    "@emotion/server": "^11.0.0-next.14",
    "@emotion/styled": "^11.0.0-next.15",
    "@material-ui/core": "^4.9.1",
    "@storybook/addon-actions": "^6.0.12",
    "@storybook/addon-knobs": "^6.0.12",
    "@storybook/addon-notes": "^5.3.19",
    "@storybook/addons": "^6.0.1",
    "@storybook/react": "^6.0.1",
    "@tailwindcss/ui": "^0.5.0",
    "@tailwindcssinjs/macro": "^0.7.2",
    ...

**Comment by shilman** [comment] 2020-10-16 11:18
Try running Storybook with the `--no-dll` flag?

**Comment by mverissimo** [comment] 2020-11-13 14:37
The same problem here using emotion 11, I try this flag but this doesn't work. I'm trying to find some solution, but nothing at moment.

**Comment by shilman** [comment] 2020-11-13 23:44
@mverissimo did you try 6.1?

```
npx sb upgrade --prerelease
```

**Comment by mverissimo** [comment] 2020-11-16 12:54
@shilman Yes, but don`t work! And have another problem #10231 

I will try to find a solution, thanks!

**Comment by Keysox** [comment] 2020-11-24 20:19
I just ran into this and resolved it by switching `@emotion/styled` to `@storybook/theming`, which forces emotion to use a single version. This was caused by one of our dependencies relying on version 10 while we were trying to upgrade to 11.

**Comment by pgrekovich** [comment] 2020-11-26 09:12
@WebTerminator try to disable @emotion/babel-plugin

**Comment by mverissimo** [comment] 2020-11-26 11:33
Hi, @pgrekovich I solved this with [this approach](https://github.com/storybookjs/storybook/issues/10231#issuecomment-728038867) the difference is that I add `@emotion/styled` on an alias too.

**Comment by pgrekovich** [comment] 2020-11-26 13:59
`babel-preset-css-prop` insted of `@emotion/babel-plugin` fixed the problem

**Comment by mj12albert** [comment] 2020-12-10 10:37
> Hi, @pgrekovich I solved this with [this approach](https://github.com/storybookjs/storybook/issues/10231#issuecomment-728038867) the difference is that I add `@emotion/styled` on an alias too.

How did you alias `@emotion/styled` ? I tried but still getting stuck at `Can't resolve '@emotion/styled/base'`

**Comment by mavlikwowa** [comment] 2020-12-25 12:01
I changed webpack.config in Storybook and it helped!
`const path = require("path")

const toPath = (_path) => path.join(process.cwd(), _path)

module.exports = {
  stories: ['../stories/**/*.stories.@(ts|tsx|js|jsx)'],
  addons: ['@storybook/addon-links', '@storybook/addon-essentials'],
  // https://storybook.js.org/docs/react/configure/typescript#mainjs-configuration
  typescript: {
    check: true, // type-check stories during Storybook build
  },
  webpackFinal: async (config) => {
    return {
      ...config,
      resolve: {
        ...config.resolve,
        alias: {
          ...config.resolve.alias,
          "@emotion/core": toPath("node_modules/@emotion/react"),
          // You should add this row
          "@emotion/styled": toPath("node_modules/@emotion/styled"),
          "emotion-theming": toPath("node_modules/@emotion/react"),
        },
      },
    }
  },
};
`

**Comment by valentinpalkovic** [comment] 2024-02-19 22:59
Please use the following addon to setup Emotion and Tailwind with Storybook: https://github.com/storybookjs/addon-styling-webpack

I am closing this for now. Please let us know if this is still an issue.

**Closed by valentinpalkovic** 2024-02-19 22:59 UTC
Labels: question / support, compatibility with other tools, react, has workaround, tailwind
