### ISSUE TITLE
@storybook/api raising typescript TS2411 - incorrect use of indexed property

### ISSUE THREAD

**Issue by rosskevin** [storybookjs/storybook#7069] opened 2019-06-12 19:43 UTC
**Describe the bug**
Incorrect use of indexed properties resulting in TS2411 downstream when included by tsc.

Trying to upgrade to 5.1.3 and my typescript based monorepo fails on definitions produced by @storybook/api, specifically ts(2411):

```
$ /Users/kross/projects/js/node_modules/.bin/tsc -b
../../node_modules/@storybook/api/dist/modules/versions.d.ts:12:9 - error TS2411: Property 'latest' of type 'Version | undefined' is not assignable to string index type '{ [key: string]: any; }'.

12         latest?: Version;
           ~~~~~~

../../node_modules/@storybook/api/dist/modules/versions.d.ts:13:9 - error TS2411: Property 'next' of type 'Version | undefined' is not assignable to string index type '{ [key: string]: any; }'.

13         next?: Version;
           ~~~~

../../node_modules/@storybook/api/dist/modules/versions.d.ts:14:9 - error TS2411: Property 'current' of type 'Version | undefined' is not assignable to string index type '{ [key: string]: any; }'.

14         current?: Version;
           ~~~~~~~

../../node_modules/@storybook/api/dist/index.d.ts:61:13 - error TS2411: Property 'latest' of type 'Version | undefined' is not assignable to string index type '{ [key: string]: any; }'.

61             latest?: import("./modules/versions").Version;
               ~~~~~~

../../node_modules/@storybook/api/dist/index.d.ts:62:13 - error TS2411: Property 'next' of type 'Version | undefined' is not assignable to string index type '{ [key: string]: any; }'.

62             next?: import("./modules/versions").Version;
               ~~~~

../../node_modules/@storybook/api/dist/index.d.ts:63:13 - error TS2411: Property 'current' of type 'Version | undefined' is not assignable to string index type '{ [key: string]: any; }'.

63             current?: import("./modules/versions").Version;
```

**To Reproduce**
1. create a typescript project
2. `yarn add @storybook#addon-actions` which will transitively give you `@storybook/api`
3. `tsc -b`

**Expected behavior**
No typescript errors from published files

**Screenshots**
![versions_d_ts_—_js](https://user-images.githubusercontent.com/136564/59380510-e579a280-8d1e-11e9-959f-f28cd79fe984.gif)

**Code snippets**
n/a

**System:**
 - OS: osx
 - Framework: react
 - Version: 5.1.3

**Additional context**
typescript@3.5.1

Specifically, `Version` is not the same type as the indexer.

- https://github.com/Microsoft/TypeScript/issues/10042
- https://stackoverflow.com/a/33818404/2363935
- https://stackoverflow.com/a/45261035/2363935

**Comment by gaetanmaisse** [comment] 2019-06-25 07:37
@rosskevin can you share your `tsconfig.json`? because I can't reproduce your pb on my company big front monorepo.

**Comment by rosskevin** [comment] 2019-06-25 14:22
@gaetanmaisse here is our base config:

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2015",
    "jsx": "react",
    "lib": ["es2017", "esnext.asynciterable", "dom"],

    "allowSyntheticDefaultImports": true,
    "declaration": true,
    "declarationMap": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": false,
    "moduleResolution": "node",
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "noEmitOnError": true,
    "noUnusedLocals": false,
    "strict": true,
    "sourceMap": true,
    "suppressImplicitAnyIndexErrors": true
  }
}
```

**Comment by n3utrino** [comment] 2019-07-09 14:20
As a workaround, add 

`"skipLibCheck": true`

to your `compilerOptions`

**Comment by shilman** [comment] 2019-07-10 13:24
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-alpha.40 containing PR #7072 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2019-07-10 13:24 UTC
Labels: bug, has workaround, typescript
