### ISSUE TITLE
[Bug]: [Angular] Controls not working when encapsulating component

### ISSUE THREAD

**Issue by Robouste** [storybookjs/storybook#24439] opened 2023-10-11 12:21 UTC
### Describe the bug

I'm trying to create a story book for [MatButtonToggle](https://material.angular.io/components/button-toggle/examples). Since the HTML is "complexe", I cannot use it directly and I have to use a component wrapper:

```typescript
@Component({
  template: `
    <mat-button-toggle-group [multiple]="multipleSelection">
      <mat-button-toggle>
        <fa-icon *ngIf="compType === 'icon'" [icon]="icons.one" />
        {{ compType === 'text' ? 'Left' : '' }}
      </mat-button-toggle>
      <mat-button-toggle>
        <fa-icon *ngIf="compType === 'icon'" [icon]="icons.two" />
        {{ compType === 'text' ? 'Middle' : '' }}
      </mat-button-toggle>
      <mat-button-toggle>
        <fa-icon *ngIf="compType === 'icon'" [icon]="icons.three" />
        {{ compType === 'text' ? 'Right' : '' }}
      </mat-button-toggle>
    </mat-button-toggle-group>
  `,
  standalone: true,
  imports: [MatButtonToggleModule, FontAwesomeModule, NgIf],
})
export class ButtonToggleComponent {
  @Input() compType: 'text' | 'icon' = 'text';
  @Input() multipleSelection = false;

  protected icons = {
    one: faRaygun,
    two: faGhost,
    three: faGamepad,
  };
}
```

I configured the story like this:

```typescript
import {Meta, StoryObj} from '@storybook/angular';
import {ButtonToggleComponent} from './button-toggle.component';

const meta: Meta<ButtonToggleComponent> = {
  title: 'button toggle',
  component: ButtonToggleComponent,
};

export default meta;

type Story = StoryObj<ButtonToggleComponent>;

export const ButtonToggle: Story = {
  args: {
    multipleSelection: false,
    compType: 'text',
  },
  argTypes: {
    compType: {
      options: ['text', 'icon'],
      control: {type: 'radio'},
    },
  },
};
```

The control panel is displayed below the story, it properly displays the control, but they are not doing anything.

### System

```bash
System:
  OS: Windows 10 10.0.19045
  CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
Binaries:
  Node: 16.14.2 - ~\AppData\Local\Volta\tools\image\node\16.14.2\node.EXE
  npm: 8.5.4 - ~\AppData\Local\Volta\tools\image\npm\8.5.4\bin\npm.CMD
Browsers:
  Edge: Spartan (44.19041.3570.0), Chromium (117.0.2045.60)
npmPackages:
  @storybook/addon-essentials: 7.0.21 => 7.0.21
  @storybook/addon-interactions: 7.0.21 => 7.0.21
  @storybook/angular: 7.0.21 => 7.0.21
  @storybook/core-common: ^7.0.21 => 7.2.1
  @storybook/core-server: 7.0.21 => 7.0.21
  @storybook/jest: ^0.2.2 => 0.2.2
  @storybook/test-runner: ^0.10.0 => 0.10.0
  @storybook/testing-library: ^0.2.1 => 0.2.1
```

### Additional context

It works fine when testing a material component directly:

```typescript
import {MatSlideToggle} from '@angular/material/slide-toggle';
import {Meta, StoryObj} from '@storybook/angular';

const meta: Meta<MatSlideToggle> = {
  title: 'slide-toggle',
  component: MatSlideToggle,
};

export default meta;

type Story = StoryObj<MatSlideToggle>;

export const Toggle: Story = {
  args: {
    color: 'primary',
    checked: true,
  },
  argTypes: {
    color: {
      options: ['primary', 'accent', 'warn'],
      control: {type: 'radio'},
    },
  },
};
```

Also, I tried to add `ngOnChanges` and it never gets trigger. I have also tried to use `ChangeDetectionStrategy.OnPush`

**Comment by Marklb** [comment] 2023-10-11 23:47
I put the snippet in a stackblitz. @Robouste can you check that I recreated your issue correctly. https://stackblitz.com/edit/github-ijkqqq

The problem is that the current implementation only supports automatically adding bindings in a generated template, that has a selector. Your example would generate:
```html
<ng-container *ngComponentOutlet="ButtonToggleComponent"></ng-container>
```
I have never tried it, but Angular seems to have added support for inputs, with NgComponentOutlet, in version `16.2`. I don't see where outputs can be added. So, without emulating input/output bindings, I think we can fix adding inputs this way.

For now, you can add a selector to your component and it will generate the input/output bindings.

**Comment by Robouste** [comment] 2023-10-12 07:07
Thanks a lot for looking into it. It was indeed an issue with the selector :)

Thank you again! 

PS: I had to hard refresh to make it work on my side after adding the selector.

**Comment by valentinpalkovic** [comment] 2023-10-14 17:16
Thank you @Marklb!

Can we close the issue @Robouste? Or is something still unclear?

**Comment by Robouste** [comment] 2023-10-14 17:17
Sure, go ahead. Thanks again for the assistance.

**Closed** 2023-10-14 17:17 UTC
Labels: bug, angular, needs triage
