### ISSUE TITLE
Svelte component doesn't displayed

### ISSUE THREAD

**Issue by PritulaRoman** [storybookjs/storybook#8384] opened 2019-10-11 09:33 UTC
**Describe the bug**
Using Centered addon in Svelte stories leads to an empty screen. No component displayed.

**To Reproduce**
 _devDependencies_
```
}
  "svelte": "^3.12.1",
  "@storybook/svelte": "^5.2.1",
  "@storybook/addon-centered": "^5.2.3"
}
```
You can see the issue on the Live Examples [Svelte page](https://storybookjs.now.sh/svelte-kitchen-sink/?path=/story/addon-centered--rounded)

**Screenshots**
![image](https://user-images.githubusercontent.com/16545426/66641251-0c8ba680-ec23-11e9-957d-61da27cc9393.png)

**Comment by jerriclynsjohn** [comment] 2019-10-13 10:42
I'm facing the exact same issue too.

**Comment by aromanarguello** [comment] 2019-11-07 02:03
Hi, is there anyone working on this? I Would like to see if I can contribute? It would be my first contribution to Open source.

**Comment by shilman** [comment] 2019-11-07 02:12
@aromanarguello AFAIK nobody's working on this. please hop on our discord if you need any help getting started! https://discord.gg/UUt2PJb

**Comment by alexdilley** [comment] 2019-11-18 13:17
This is presumably because Svelte storybooks don't currently support using templates in a story (i.e. via slots), and this addon wraps the original component via a `slot`.

**Comment by aromanarguello** [comment] 2019-11-18 14:15
@alexdilley Hey! I was trying to investigate this and that is what I found as well, that the problem is that the component data is not being slotted into the wrapper. I'm not an expert as svelte, do you have any alternative ideas to fix this?

**Comment by alexdilley** [comment] 2019-11-18 14:50
I guess either wait for support to be added to Storybook or perhaps style the root element (ofc this is global to all stories though):

```css
#root {
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  display: flex;
  align-items: center;
  justify-content: center;
}
```

There's [theming](https://storybook.js.org/docs/configurations/theming/) support but it doesn't seem to extend to adding arbitrary styles to the main frame.

**Comment by tonai** [comment] 2020-02-03 15:14
I also face the same issue and here my investigations:

The centered addon decorator is set up using the `Wrapper` option [here](https://github.com/storybookjs/storybook/blob/next/addons/centered/src/svelte.ts#L30)

Then this `Wrapper` option is converted to a Svelte component [here](https://github.com/storybookjs/storybook/blob/next/app/svelte/src/client/preview/render.ts#L24)

And the problem is that it uses a `slots` option to pass down the story component that will be wrapped by the centered decorator. This option is not documented anywhere in the [Svelte docs](https://svelte.dev/docs#Creating_a_component)

This option seems to exist in svelte 2 but was removed in Svelte 3.
There is an [issue](https://github.com/sveltejs/svelte/issues/2588) about this problem on the Svelte repo and there is also a [PR](https://github.com/sveltejs/svelte/pull/2684) created on May the 5th 2019.
This has still not been merged but in the original [issue](https://github.com/sveltejs/svelte/issues/2588) someone proposed a workaround that seems to work.

Maybe we should make use of that workaround.

**Comment by shilman** [comment] 2020-02-04 09:03
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.5 containing PR #9724 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2020-02-04 09:03 UTC
Labels: addon: centered, app: svelte, bug, good first issue, help wanted

**Comment by shilman** [comment] 2020-02-04 16:25
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.11 containing PR #9724 that references this issue. Upgrade today to try it out!
