### ISSUE TITLE
[Bug]: digital envelope routines - won't run with Svelte projects

### ISSUE THREAD

**Issue by octoxan** [storybookjs/storybook#19984] opened 2022-11-28 14:50 UTC
### Describe the bug

Ran `npx sb init` in the root of my Svelte project, and it complained that I'm using too modern of dependencies and asked me if I wanted to run the npm7 migration, which I answered yes to. 

After this, `npm run storybook` and `npm run storybook --legacy-peer-deps=true` throw the same error:

```
info @storybook/svelte v6.5.13
info 
info => Loading presets
ℹ ｢wdm｣: wait until bundle finished: 
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/embold/code/handshaked/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/embold/code/handshaked/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/embold/code/handshaked/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/embold/code/handshaked/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/embold/code/handshaked/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/embold/code/handshaked/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/embold/code/handshaked/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/embold/code/handshaked/node_modules/loader-runner/lib/LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.9.0
```

### System

```shell
System:
    OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (6) x64 Intel(R) Xeon(R) CPU @ 2.20GHz
  Binaries:
    Node: 18.9.0 - ~/.local/state/fnm_multishells/1908_1669643822650/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.1.2 - ~/.local/state/fnm_multishells/1908_1669643822650/bin/npm
  npmPackages:
    @storybook/addon-actions: ^6.5.13 => 6.5.13 
    @storybook/addon-essentials: ^6.5.13 => 6.5.13 
    @storybook/addon-interactions: ^6.5.13 => 6.5.13 
    @storybook/addon-links: ^6.5.13 => 6.5.13 
    @storybook/builder-vite: ^0.2.5 => 0.2.5 
    @storybook/svelte: ^6.5.13 => 6.5.13 
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

### Additional context

This is just with all the defaults of a Svelte <-> Inertia.js <-> Laravel install.

**Comment by glrodasz** [comment] 2022-11-28 18:43
I'm having exactly the same error with a freshly created react project.

**Comment by dopry** [comment] 2022-12-14 14:31
Duplicate of #16555

**Comment by shilman** [comment] 2022-12-14 18:15
Closing as duplicate of #16555

**Closed** 2022-12-14 18:15 UTC
Labels: bug, duplicate, needs triage
