### ISSUE TITLE
[Bug]: Applying csf-2-to-3: 103 files - No files selected, nothing to do.

### ISSUE THREAD

**Issue by smcgillrw** [storybookjs/storybook#25527] opened 2024-01-09 16:15 UTC
### Describe the bug

Running into an issue attempting to migrate storybook in an Nx monorepo project from version 6.x -> 7.x.  Can't find much information on this and it's not super descriptive however when we run the migrate command on our project it seems to indicate it found stories to upgrade - but then says nothing was 'selected' (does this mean via our path filter?)

npx storybook@latest migrate csf-2-to-3 --glob="**/*.stories.ts"

Need to install the following packages:
storybook@7.6.7
Ok to proceed? (y)
=> Applying csf-2-to-3: 103 files
No files selected, nothing to do. 
All done.
Results:
0 errors
0 unmodified
0 skipped
0 ok
Time elapsed: 0.002seconds

Little confused as to why it's saying 'Applying csf-2-to-3: 103 files' but then says 'No files selected, nothing to do.' and can't find anything on this behavior in general... so looking for some help as to what may be going on here if this is a bug, or just a generally expected behavior?  thanks!

### To Reproduce

Our specific case is literally just running the update on an Nx project, have tried a number of variations to the path in the glob parameter path to no avail

npx storybook@latest migrate csf-2-to-3 --glob="**/*.stories.ts"

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.2.1
    CPU: (12) arm64 Apple M2 Max
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm <----- active
  Browsers:
    Chrome: 120.0.6099.199
    Edge: 120.0.2210.121
    Safari: 17.2.1
  npmPackages:
    @storybook/addon-a11y: ^7.4.1 => 7.4.2
    @storybook/addon-designs: ^7.0.5 => 7.0.5
    @storybook/addon-essentials: 7.4.1 => 7.4.1
    @storybook/addon-interactions: ^7.4.1 => 7.4.2
    @storybook/addon-links: ^7.4.1 => 7.4.2
    @storybook/angular: 7.4.1 => 7.4.1
    @storybook/core-common: ^7.4.1 => 7.4.2
    @storybook/core-server: 7.4.1 => 7.4.1
    @storybook/jest: ^0.2.2 => 0.2.2
    @storybook/test-runner: ^0.13.0 => 0.13.0
    @storybook/testing-library: ^0.2.0 => 0.2.1
    eslint-plugin-storybook: ^0.6.13 => 0.6.13
    storybook: ^7.4.1 => 7.4.2
    storybook-addon-pseudo-states: ^2.1.1 => 2.1.1
```

### Additional context

We're using storybook in a Nx monorepo with many libraries and apps

**Comment by valentinpalkovic** [comment] 2024-01-10 18:33
Duplicate of https://github.com/storybookjs/storybook/issues/25226

**Closed by valentinpalkovic** 2024-01-10 18:33 UTC
Labels: bug, cli, codemods, sev:S2
