### ISSUE TITLE
[Bug]: Module not found: Error: Can't resolve 'react/jsx-runtime'

### ISSUE THREAD

**Issue by jpzwarte** [storybookjs/storybook#20160] opened 2022-12-08 13:24 UTC
### Describe the bug

`storybook build` fails with:

```
ERR! => Failed to build the preview
[26](https://github.com/sanomalearning/design-system/actions/runs/3647986313/jobs/6160864416#step:6:27)
ERR! Module not found: Error: Can't resolve 'react/jsx-runtime' in '/home/runner/work/design-system/design-system/docs/storybook/stories'
```

See https://github.com/sanomalearning/design-system/actions/runs/3647986313/jobs/6160864416 for the full build output (build is parallelized,so log messages are mixed). 

### To Reproduce

Happens with `@storybook/web-components@7.0.0-beta.0` (web pack builder); did not happen with `7.0.0-alpha.58`.

**Comment by IanVS** [comment] 2022-12-08 13:33
I talked to @jpzwarte and he does not have react/react-dom installed in his project.

I think this is going to be confusing to many people.  We may consider adding a runtime check to confirm that react + react-dom are installed, and explain to the user why they are needed, and how they can remove docs if they do not want that feature.

**Comment by shilman** [comment] 2022-12-08 14:15
@jpzwarte did you run 

```
npx sb@next upgrade --prerelease
```

It should prompt you to add `react`/`react-dom` as devDependencies

**Comment by jpzwarte** [comment] 2022-12-08 14:21
@shilman no, not between upgrading alpha's (or from alpha.58 to beta.0).

**Comment by jpzwarte** [comment] 2022-12-08 14:21
I just update the versions in `package.json` and run `yarn` again.

**Comment by jpzwarte** [comment] 2022-12-08 15:00
@shilman Fair enough. I'll remember to use the upgrade script :)

**Comment by jpzwarte** [comment] 2022-12-09 07:51
@IanVS ok to close this one or should I leave it open still?

**Comment by jpzwarte** [comment] 2022-12-09 10:34
@shilman What if you have a yarn 3 monorepo and use workspaces? Does `npx sb@next upgrade --prerelease` support that scenario?

**Comment by jpzwarte** [comment] 2022-12-12 08:32
@shilman I tried it; it outputted lots of stuff etc, but in the end no files were changed. What I did:

- From the root of the monorepo: `npx sb@next upgrade --prerelease`
- It asked to install beta.3; I said yes
- It asked to run `mdx1to2`, I said yes
- yarn ran
- After it finished: `git status` -> "nothing to commit, working tree clean"

To be clear: the root `package.json` has no storybook dependencies. Those only exist in the workspaces.

**Comment by jpzwarte** [comment] 2022-12-12 08:34
Forgot to mention: the nested `package.json` files still have version `beta.2` of storybook.

**Comment by valentinpalkovic** [comment] 2022-12-13 08:27
I will close this issue. Marking it as a duplicate of https://github.com/storybookjs/storybook/issues/20203

> @shilman What if you have a yarn 3 monorepo and use workspaces? Does npx sb@next upgrade --prerelease support that scenario?

@jpzwarte  If this is still an issue, could you please create another issue ticket? Thank you :)

**Closed by valentinpalkovic** 2022-12-13 08:27 UTC
Labels: bug, dependencies, linear
