### ISSUE TITLE
Error "Singleton client API not yet initialized, cannot call addParameters"

### ISSUE THREAD

**Issue by deej-split** [storybookjs/storybook#16097] opened 2021-09-18 01:45 UTC
**Describe the bug**
We upgraded from 6.3.7 to 6.3.8, and when storybook opens in the browser, we are presented with an infinitely spinning spinner.  In the browser console, it reports 

```
Uncaught Error: Singleton client API not yet initialized, cannot call addParameters
    at addParameters (vendors~main.iframe.bundle.js:47554)
    at vendors~main.iframe.bundle.js:23209
    at Array.forEach (<anonymous>)
    at Module../node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-other-entry.js (vendors~main.iframe.bundle.js:23183)
    at __webpack_require__ (runtime~main.iframe.bundle.js:854)
    at fn (runtime~main.iframe.bundle.js:151)
    at Object.0 (main.iframe.bundle.js:92004)
    at __webpack_require__ (runtime~main.iframe.bundle.js:854)
    at checkDeferredModules (runtime~main.iframe.bundle.js:46)
    at Array.webpackJsonpCallback [as push] (runtime~main.iframe.bundle.js:33)
```

I see from this migration guide ( https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-addparameters-and-adddecorator ) that our `.storybook/preview.js` should contain `export const parameters = {` and `export const decorators = [` which it does.

I'm unsure how to debug this further, as I see nothing in the stack trace that easily directs me where to go next, nor do I know what the "Singleton API" is.

(We made no changes to our `.storybook/main.js` or `.storybook/preview.js` files as part of this upgrade)

**To Reproduce**
Would love to create a reproducible case, as I know that would be helpful.  At the moment, sb is so intertangled with webpack and thus babel and typescript that it takes an extremely large amount of time to set this up.  (I tried)

**System**
```
  System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    npm: 7.23.0 - ~/.nvm/versions/node/v14.17.6/bin/npm
  Browsers:
    Chrome: 93.0.4577.82
    Edge: 93.0.961.52
    Firefox: 89.0
    Safari: 14.1.2
  npmPackages:
    @storybook/addon-actions: 6.3.8 => 6.3.8 
    @storybook/addon-docs: 6.3.8 => 6.3.8 
    @storybook/addon-essentials: 6.3.8 => 6.3.8 
    @storybook/addon-links: 6.3.8 => 6.3.8 
    @storybook/addon-postcss: 2.0.0 => 2.0.0 
    @storybook/addons: 6.3.8 => 6.3.8 
    @storybook/react: 6.3.8 => 6.3.8 
    @storybook/theming: 6.3.8 => 6.3.8 
```

**Additional context**

This is a list of the packages we upgraded (I tried `npx sb@latest upgrade`, but it crashed.

```
     "@sentry/cli": "1.68.0",
-    "@storybook/addon-actions": "6.3.7",
-    "@storybook/addon-docs": "6.3.7",
-    "@storybook/addon-essentials": "6.3.7",
-    "@storybook/addon-links": "6.3.7",
+    "@storybook/addon-actions": "6.3.8",
+    "@storybook/addon-docs": "6.3.8",
+    "@storybook/addon-essentials": "6.3.8",
+    "@storybook/addon-links": "6.3.8",
     "@storybook/addon-postcss": "2.0.0",
-    "@storybook/addons": "6.3.7",
-    "@storybook/react": "6.3.7",
-    "@storybook/theming": "6.3.7",
+    "@storybook/addons": "6.3.8",
+    "@storybook/react": "6.3.8",
+    "@storybook/theming": "6.3.8",
     "@testing-library/jest-dom": "5.14.1",
     "@testing-library/react": "12.1.0",
     "@types/classnames": "2.3.1",
@@ -142,7 +142,7 @@
     "react-select-event": "5.3.0",
     "react-test-renderer": "16.13.1",
     "redux-mock-store": "1.5.4",
-    "storybook-addon-designs": "6.0.1",
+    "storybook-addon-designs": "6.1.0",
     "style-loader": "2.0.0",
```

**Comment by shilman** [comment] 2021-09-18 08:24
Did you try removing `node_modules` and/or lockfiles and reinstalling?

If that doesn't work, do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce).

**Comment by deej-split** [comment] 2021-09-18 17:19
Yes, removed the lock file and node modules.

I'm sorry to say, setting up a reproducible repo is non-trivial and out of scope for what I have time for at the moment.

As noted, if you can tell me what the Singleton API is or give some guesses of what might be going wrong, I may be able to debug further on my own.

**Comment by shilman** [comment] 2021-09-18 18:37
Here's the code

https://github.com/storybookjs/storybook/blob/main/lib/client-api/src/client_api.ts#L20-L37

The ClientAPI singleton is an object that holds all the story state and renders your stories. I don't know under what conditions it would be undefined -- maybe some kind of webpack configuration error?

Closing this until there's a reproduction.

**Closed by shilman** 2021-09-18 18:37 UTC
Labels: bug, needs reproduction, needs triage

**Comment by penx** [comment] 2021-09-30 16:10
I see this on our project, govuk-react, upgrading to 6.3.8.

Sorry I don't have a minimal reproduction, but if you want to recreate on our project:

(1)
```
git clone https://github.com/govuk-react/govuk-react.git
cd govuk-react
git checkout 8283b50ed6f2f134ae2688b0875d4a8f2c16c00b
nvm use # switch to node 16.10
npm i
```

(2) 

update in /package.json

```
    "@storybook/addon-actions": "6.3.8",
    "@storybook/addon-controls": "6.3.8",
    "@storybook/addon-docs": "6.3.8",
    "@storybook/addon-storyshots": "6.3.8",
    "@storybook/addons": "6.3.8",
    "@storybook/react": "6.3.8",
```

update in /packages/storybook/package.json

```
    "@storybook/addon-actions": "6.3.8",
    "@storybook/addon-controls": "6.3.8",
    "@storybook/addon-docs": "6.3.8",
    "@storybook/addon-links": "6.3.8",
    "@storybook/addons": "6.3.8",
    "@storybook/react": "6.3.8",
```

(3)

```sh
npm i --force # there are conflicts if you don't do this, which you don't get in older versions of npm, and could be the issue
npm start
```

**Comment by penx** [comment] 2021-10-01 10:44
update on the above:

- the dependency issue above was due to addon-links, which I realised I'm no longer using so was able to remove it and no longer need to do `npm i --force`
- the issue is still present when I update to 6.3.8
- if I upgrade everything other than `@storybook/react` to 6.3.8, and keep `@storybook/react` on 6.3.7, I don't see the issue. Then when I upgrade `@storybook/react`, the issue comes back.

To recreate:

- follow steps above but with `git checkout 13f2c4f3fd4627657f3f4d2dbfcd42ee38ab91ef`
- `npm i && npm start`, note issue is not present, storybook loads ok
- upgrade `@storybook/react` to 6.3.8 in package.json and packages/storybook/package.json
- `npm i && npm start`, note issue is present, storybook doesn't fully load

@shilman Please let me know if there's anything else you want me to look in to!

**Comment by penx** [comment] 2021-10-01 10:46
Also this stack trace may help as it's not pointing to the bundled line numbers:


```
Uncaught Error: Singleton client API not yet initialized, cannot call addParameters
    at addParameters (client_api.js:55)
    at config.js-generated-other-entry.js:37
    at Array.forEach (<anonymous>)
    at Module.../../node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-other-entry.js (config.js-generated-other-entry.js:11)
```

**Comment by shilman** [comment] 2021-10-02 14:39
@penx this is pretty strange. the changes in 6.3.8 are quite minor:

https://github.com/storybookjs/storybook/pull/15889/files

did you upgrade anything else, e.g. the version of node you're using?

**Comment by penx** [comment] 2021-10-02 16:47
@shilman I recently upgraded to node v16.10.0 (npm v7.24.0), but I can recreate this issue following the steps above by staying on the same version before + after.

I guess it has something to do with the `@discoveryjs/json-ext` dependency, will take a quick look at the resulting package lock changes and see if there's anything obvious.

**Comment by penx** [comment] 2021-10-02 17:00
I was on @discoveryjs/json-ext 0.5.5 both before and after so I don't think it's that directly, but perhaps a sub dependency.

If I upgrade to 6.3.8 and then downgrade to 6.3.7 again (just @storybook/react, everything else kept at 6.3.8) then the issue remains, so it seems it's a dependency issue. Which one though I'm not sure, there's a lot changed in the package lock, will try see if I can figure it out.

**Comment by shilman** [comment] 2021-10-03 14:00
@penx That's weird because AFAICT `@discoveryjs/json-ext` doesn't have any dependencies:

https://www.npmjs.com/package/@discoveryjs/json-ext

I already checked the commit history and I'm pretty sure that the rest of the changes in that release are documentation-only changes. I wonder why there are lots of changes in your lockfile... 🤔

**Comment by mjchang** [comment] 2021-10-03 17:46
If it's any help, I encountered this issue yesterday. I upgraded my storybook dependencies from 6.3.8 -> 6.3.9 but accidentally forgot to upgrade `@storybook/react`. After resetting and upgrading them all at once, it worked.

**Comment by ming8525** [comment] 2021-11-17 07:33
I have the same problem when I upgrade from  `6.3.7` to  `6.3.11`.
![image](https://user-images.githubusercontent.com/16754309/142155594-8502fb52-e68b-45d7-86b9-d2fc12c6e943.png)

Here is my package-lock:
![image](https://user-images.githubusercontent.com/16754309/142155642-76a6906d-5189-42ff-9180-1ba0aeb8a605.png)

**Comment by ming8525** [comment] 2021-11-17 07:43
> I have the same problem when I upgrade from `6.3.7` to `6.3.11`. ![image](https://user-images.githubusercontent.com/16754309/142155594-8502fb52-e68b-45d7-86b9-d2fc12c6e943.png)
> 
> Here is my package-lock: ![image](https://user-images.githubusercontent.com/16754309/142155642-76a6906d-5189-42ff-9180-1ba0aeb8a605.png)

It works well in `6.3.12`.
