### ISSUE TITLE
Storybook is not calling Angular 13 component's event handler

### ISSUE THREAD

**Issue by frankfajardo** [storybookjs/storybook#16916] opened 2021-12-06 05:53 UTC
**Describe the bug**

- Storybook does not call the component's event handler

**To Reproduce**

- Created a new Angular 13 app: `ng new angular13`
- Created a component that has a clickable button which triggers a method within the component to be run. The method changes the state of the UI.
- Initialized repo with Storybook: `npx sb@next init`
- Added Storybook builder in `angular.json`:
```
"storybook": {
  "builder": "@storybook/angular:start-storybook",
  "options": {
    "tsConfig": ".storybook/tsconfig.json",
    "browserTarget": "angular13:build",
    "compodoc": false,
    "port": 6008
  }
}
```
- Added script to `package.json` to run Storybook builder
```
"sb": "npm run docs:json && ng run angular13:storybook"
```
- Started Storybook: `npm run sb`
- Test the component with clickable button. When clicking the component's button on Storybook, it does not trigger the component method which is supposed to change the UI. If I try to add a breakpoint at the very beginning to the component method using my browser's Developer Tools, the breakpoint never gets hit. Or if I try to add a `console.log(...)` line at the very beginning of the method, that never shows up on the console. (But there is no problem using the component within the Angular 13 app; the user clicking the component's button triggers the component method without any issues.) 

**Link to Repro Repo on Github**
https://github.com/frankfajardo/angular13-with-sb6.4.7

The repo has 2 components: Checkbox and Quantity Input.
- Clicking the checkbox or its label should uncheck/check the checkbox.
- Clicking the "+" or "-" on the Quantity Input should increase or decrease the quantity shown.

**System**
```
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.17.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (96.0.1054.43)
  npmPackages:
    @storybook/addon-actions: ^6.4.7 => 6.4.7
    @storybook/addon-essentials: ^6.4.7 => 6.4.7
    @storybook/addon-links: ^6.4.7 => 6.4.7
    @storybook/angular: ^6.4.7 => 6.4.7
    @storybook/builder-webpack5: ^6.4.7 => 6.4.7
    @storybook/manager-webpack5: ^6.4.7 => 6.4.7
```

**Additional context**
- Angular 13
- Using Storybook builder

**Comment by fairmutex** [comment] 2021-12-07 22:20
Until this is fixed. You may use.

Angular legacy rendering and moduleMetadata decorator.

.storybook.preview.js
```
export const parameters = {
  angularLegacyRendering: true,
};
```


checkbox.stories.ts
```
export default {
  title: 'Controls/Checkbox',
  component: CheckboxComponent,
  decorators: [
    moduleMetadata({
      declarations: [ CheckboxComponent ]
    }),
  ],
} as Meta;
```

quantity-input.stories.ts
```
export default {
  title: 'Controls/Quantity Input',
  component: QuantityInputComponent,
  decorators: [
    moduleMetadata({
      declarations: [ QuantityInputComponent ]
    }),
  ],
} as Meta;
```

**Comment by frankfajardo** [comment] 2021-12-07 23:31
Thanks @fairmutex . Now, we could progress with our Angular 13 upgrade.

**Comment by MarioSchy** [comment] 2021-12-14 17:36
@shilman 
Will this be fixed in Storybook 6.5.x, so that "angularLegacyRendering" will not be necessary anymmora?

**Comment by shilman** [comment] 2021-12-15 09:32
@MarioSchy All of our Angular maintenance is done by volunteers, so I can't commit to it, but I certainly hope we can get this figured out by the next release.

**Comment by m4tuna** [comment] 2021-12-22 15:51
I too am experiencing this same issue with v6.4.7 and Angular v12.2.

**Comment by aaronjones1** [comment] 2021-12-22 18:54
I'm having this issue with Angular CDK DragDropModule (v12.3.13) and Storybook v6.4.8.

**Comment by Mellofant** [comment] 2022-03-25 13:52
For us the problem was the line `actions: { argTypesRegex: '^on[A-Z].*' },` in `.storybook/preview.js`. In our components we had some methods such as `onItemClicked()` (starting with "on") that were called on different events (e.g. click) to do some logic and then emit custom events on their own EventEmitters. Due to the argTypes Regex in the `preview.js` Storybook somehow used the called event handlers as the event displayed in the "Actions" tab and therefore prevented the actual method from being executed. After removing the line with the RegEx definition from our `preview.js` everything worked like it did before (v6.3.4) - our event handlers were executed correctly and just the custom events were logged in the "Actions" tab. 

The workaround to activate "angularLegacyRendering" did fix that specific problem as well for us, but was not usable, because it lead to the error "NgModule already destroyed" whenever we navigated from the "Canvas" tab to the "Docs" tab and back which could then only be fixed by refreshing the whole page.

**Comment by aaronjones1** [comment] 2022-04-21 20:52
Still seeing this issue with:
- Storybook v6.4.19
- Angular CDK v13.2.5

Adding `angularLegacyRendering: true` to `.storybook/preview.js` resolved the issue, but now Actions are not working.

**Comment by aaronjones1** [comment] 2022-08-09 18:12
I just found out that removing the type definition from my `@Output()` declarations and adding an explicit return type to my event handlers got the Actions working again in SB:

```ts
// ✅
@Output() selected = new EventEmitter<number>();

/**
   * Emits the selected event.
   */
  onSelected(): void {
    console.debug('onSelected()');
    this.selected.emit(this.id);
  }
```

This is what I had before.  This does not work:
```ts
// ❌
@Output() selected: EventEmitter<number> = new EventEmitter<number>(); // 👈

/**
   * Emits the selected event.
   */
  onSelected() { // 👈
    console.debug('onSelected()');
    this.selected.emit(this.id);
  }
```

I still have legacy rendering turned on and I'm using Angular `v14.1.1`, SB `v6.5.10`, and SB Actions `v6.5.10`.

**Comment by shilman** [comment] 2023-06-09 03:13
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

**Closed by shilman** 2023-06-09 03:13 UTC
Labels: bug, has workaround, angular
