### ISSUE TITLE
[storybook/angular] storybook fails because of missing "node-sass", for Angular v8.0 when `defaultProject` is a library project

### ISSUE THREAD

**Issue by lacolaco** [storybookjs/storybook#6978] opened 2019-06-05 07:35 UTC
**Describe the bug**

This is a bit complex bug. 
This bug is based on the following conditions;

- Storybook v5
- Angular v8.0.0
  - `node-sass` doesn't exist in `package.json`
- In `angular.json`, `defaultProject` is set to a project which has `projectType: library`.
- A component (used in a story) has `styleUrls` and it refers external `.scss` files which contains `@import "..."`.

Running `yarn storybook`, it fails with log like the below;

```
ERROR in ./projects/sample-lib/src/lib/sample-lib.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.sassLoader (/Users/laco/Works/storybook-ngv8-lib/node_modules/sass-loader/lib/loader.js:46:72)
 @ ./projects/sample-lib/src/lib/sample-lib.component.ts 15:17-55
 @ ./src/stories/index.stories.ts
 @ ./src/stories sync \.stories\.ts$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js ./node_modules/webpack-hot-middleware/client.js?reload=true
```

**To Reproduce**
1. `ng new some-repo --create-application false
2. `ng generate library sample-lib`
3. `yarn add @storybook/cli`
4. `yarn sb init`
5 Create `sample-lib.component.scss` file and add it to `SampleLibComponent`'s `styleUrls`
6. Create `foo.scss` and import it from `sample-lib.component.scss`
7. Create a new story for `SampleLibComponent`
8. `yarn storybook`

Repro: https://github.com/lacolaco/ngv8lib-storybook-repro

**Expected behavior**

Even if the `defaultProject` is a library, storybook should work. 

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2018
 - Framework: angular
 - Version: [5.0]

**Additional context**

The problem is here;

https://github.com/storybookjs/storybook/blob/master/app/angular/src/server/angular-cli_config.js#L92

With a library project, `cliParts` will be `null` because of `getAngularCliParts`. Internally, it uses this function:
https://github.com/storybookjs/storybook/blob/master/app/angular/src/server/angular-cli_utils.js#L53-L65

It depends on `@angular_devkit/build-angular` but the `cliWebpackConfigOptions ` is defined for `@angular_devkit/build_ng_packagr`. It makes schema mismatching.

I think storybook should have its own default `cliWebpackConfigOptions ` which will be used when it's `projectType` is not `application`. 

```ts
export function getAngularCliParts(cliWebpackConfigOptions) {
  // eslint-disable-next-line global-require, import/no-extraneous-dependencies
  const ngCliConfigFactory = require('@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs');

  if (cliWebpackConfigOptions.projectType !== "application") {
    cliWebpackConfigOptions = defaultCliWebpackConfigOption; // use default
  }

  try {
    return {
      cliCommonConfig: ngCliConfigFactory.getCommonConfig(cliWebpackConfigOptions),
      cliStyleConfig: ngCliConfigFactory.getStylesConfig(cliWebpackConfigOptions),
    };
  } catch (e) {
    return null;
  }
}
```

**Comment by dankrieger** [comment] 2019-06-06 18:37
I had a similar problem where my storybook configuration was different than the default project even when it wasn't a lib.  There's a fix in 5.1 that will prefer a project named "storybook" to pull the build config from rather than relying on the defaultProject.  Try adding a config for a project named "storybook" to angular.json

**Comment by alexan** [comment] 2019-06-07 11:12
Today I generated a new angular 8 project with angular cli. To get storybook running I had to manualy install `babel-loader`and `@babel/core`. This was not a library project.

**Comment by androdel** [comment] 2019-06-13 11:47
I fixed it by just adding node-sass to my devDependencies

**Comment by shilman** [comment] 2019-08-05 03:19
@kroeder is this also a problem with `examples/angular-kitchen-sink` in the monorepo?

**Comment by nategreen** [comment] 2019-08-20 16:34
I just encountered this error also, when attempting to switch from `node-sass` to `sass` (Dart Sass).

**Comment by shilman** [comment] 2019-08-22 02:09
@kroeder @MaximSagan @CodeByAlex I'm seeing this when trying to run `examples/angular-cli` in our monorepo. Any chance one of the angular maintainers can prioritize this?

**Comment by owen26** [comment] 2019-10-15 10:18
As a workaround, what you can do is:

Create a new project entry in `angular.json` called "storybook",

angular.json
```json
{
  "projects": {
    "your-app": {...},
    "your-lib": {...},
    "storybook": {
      "root": "copy-from-your-app",
      "sourceRoot": "copy-from-your-app",
      "architect": {
        "build": {
          "options": { ...copy from your-app }
        }
      }
    }
  },
  "defaultProject": "your-lib"
}
```

With this change, you basically tell storybook what's your intended project in your nx multi-projects monorepo to let storybook start/build.

**Comment by valentinpalkovic** [comment] 2023-05-08 14:46
Please create a reproduction on Stackblitz (https://storybook.new) for Storybook 7. I will close this in the meantime. Please feel free to reopen the issue, if it is still reproducible in SB 7.

**Closed by valentinpalkovic** 2023-05-08 14:46 UTC
Labels: bug, has workaround, angular, todo
