### ISSUE TITLE
storybook cli doesn't add @babel/typescript when scaffolding preact project

### ISSUE THREAD

**Issue by matthewharwood** [storybookjs/storybook#15531] opened 2021-07-09 05:17 UTC
**Describe the bug**
Babel config for typescrit should come included when scaffolding a preact project

**To Reproduce**
Add Storybook to an existing project of tsx preact. With writing your first story you'll get an error
`h is not defined`
Adding babel config to main.js will correct error
```
  babel: async options => ({
    ...options,
    presets: [["@babel/typescript", { jsxPragma: "h" }]],
  }),
```

**System**
Environment Info:

  System:
    OS: Windows 10 10.0.19041
    CPU: (32) x64 AMD Ryzen 9 3950X 16-Core Processor
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 2.4.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 91.0.4472.124
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.67)
  npmPackages:
    @storybook/addon-actions: ^6.3.4 => 6.3.4
    @storybook/addon-docs: ^6.3.4 => 6.3.4
    @storybook/addon-essentials: ^6.3.4 => 6.3.4
    @storybook/addon-links: ^6.3.4 => 6.3.4
    @storybook/addon-postcss: ^2.0.0 => 2.0.0
    @storybook/preact: ^6.3.4 => 6.3.4

**Additional context**
I found the solution from this dev.to article: https://dev.to/sadnessojisan/storybook-with-preact-ts-goober-4ghk
Otherwise I would have been totally lost

**Comment by shilman** [comment] 2021-07-09 06:38
@KrofDrakula is this something you can take a look at?

**Comment by KrofDrakula** [comment] 2021-07-11 07:33
@shilman Sure, will take a look.

**Comment by KrofDrakula** [comment] 2021-07-11 08:46
I've tried reproducing this problem locally using these steps (accepting all default options):

- `npx preact-cli create default my-project && cd my-project`
- `npx sb init`
- `$(npm run)/start-storybook -p 6006 --debug-webpack`

I wrote a new Preact component and created a story for it:

```tsx
const TestComponent = () => <div>This component should render OK.</div>;
export default TestComponent;
```

```tsx
import TestComponent from ".";
export default {
  title: "Test/Preact Component",
};
export const Default = () => <TestComponent />;
```

Viewing the component story results in the error described above. Interestingly, the Storybook preact preset does seem to be loading the React JSX plugin:

```
[
  '.../node_modules/@babel/plugin-transform-react-jsx/lib/index.js',
  { pragma: 'h' },
  'preset'
]
```

The problem is resolved by adding the `@jsx h` pragma and an explicit `h` import in the component:

```tsx
/** @jsx h */
import { h } from "preact";
const TestComponent = () => <div>This component should render OK.</div>;
export default TestComponent;
```

@shilman What's your stance on making `h` imports implicit? Should the Preact preset automatically import `h` for you and set the pragma? Otherwise, stories will require both the pragma header and an explicit `h` import.

For comparison, `preact-cli` defaults to enforcing component authors to import `h` explicitly, but doesn't require setting the pragma, which is implied to be `h`.

**Comment by KrofDrakula** [comment] 2021-07-11 08:48
Also, there is a separate niggle I noticed — Storybook only configured the JSX pragma, not the Fragment. I think we should add that too when solving this problem.

**Comment by shilman** [comment] 2021-07-11 11:12
@KrofDrakula thanks so much for looking into this! i don't know the preact community well enough to answer your question. if `preact-cli` is what most people use, my suggestion would be to make it consistent with that. if it's more fragmented and the implicit version will still accept an explicit import, we could do that instead. your call! most important is that whatever we do shouldn't be a breaking change if it's going into a minor release.

**Closed** 2022-07-27 11:52 UTC
Labels: bug, cli, has workaround, typescript, app: preact, P2, needs triage
