### ISSUE TITLE
Error: CSF: missing default export

### ISSUE THREAD

**Issue by seanmcintyre** [storybookjs/storybook#16598] opened 2021-11-04 20:36 UTC
Using `6.4.0-beta.27`.

This may not be a bug? Writing stories in separate files and re-exporting them from a single file yields the error:

`Error: CSF: missing default export`

<hr />

**To Reproduce**

Re-export stories from a single file. Example:
```
import { Panel } from '../Panel';

export default {
  title: 'components/Panel/props',
  component: Panel,
};

export { Active } from './active.story';
export { Attach } from './attach.story';
export { Resizable } from './resizable.story';
```

<hr />

**System**
```
  System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.3/bin/npm
  Browsers:
    Chrome: 95.0.4638.69
    Firefox: 93.0
    Safari: 15.0
  npmPackages:
    @storybook/addon-a11y: 6.4.0-beta.27 => 6.4.0-beta.27 
    @storybook/addon-essentials: 6.4.0-beta.27 => 6.4.0-beta.27 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/addon-storysource: 6.4.0-beta.27 => 6.4.0-beta.27 
    @storybook/builder-webpack5: 6.4.0-beta.27 => 6.4.0-beta.27 
    @storybook/components: 6.4.0-beta.27 => 6.4.0-beta.27 
    @storybook/manager-webpack5: 6.4.0-beta.27 => 6.4.0-beta.27 
    @storybook/react: 6.4.0-beta.27 => 6.4.0-beta.27 
    @storybook/theming: 6.4.0-beta.27 => 6.4.0-beta.27 
```

**Comment by shilman** [comment] 2021-11-05 01:19
hi @seanmcintyre! Thanks for filing this. Can you share your `main.js` config as well (specifically the `features` field)?

Starting in 6.4 we're statically analyzing the structure of CSF and this structure is not currently supported by the analysis. I need to think about whether/how to support it--it's technically possible, but may have some limitations. And if we choose not to support it, we should have a lot clearer error message.

**Comment by shilman** [comment] 2021-11-05 18:28
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-beta.29 containing PR #16607 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2021-11-05 18:28 UTC
Labels: bug, csf, needs triage

**Comment by seanmcintyre** [comment] 2021-11-08 19:45
https://github.com/vimeo/iris/blob/refactor/.storybook/main.js

```
module.exports = {
  core: {
    builder: 'webpack5',
  },
  typescript: {
    check: true,
    checkOptions: {},
  },
  features: {
    postcss: false,
    previewCsfV3: false,
    buildStoriesJson: true,
    storyStoreV7: false,
  },
  reactOptions: {
    fastRefresh: true,
    strictMode: true,
  },
  stories: ['../src/**/*.story.tsx'],
  addons: [
    '@storybook/addon-essentials',
    '@storybook/addon-a11y',
    '@storybook/addon-storysource',
    './addons/themes/register',
  ],
  webpackFinal: (config) => {
    config.module.rules.push(storySource);
    return config;
  },
};

const storySource = {
  test: /\.(stories|story)\.[tj]sx?$/,
  loader: require.resolve('@storybook/source-loader'),
  exclude: [/node_modules/],
  enforce: 'pre',
};
```

**Comment by shilman** [comment] 2021-11-09 14:38
@seanmcintyre does `beta.29` or higher fix the problem for you?

**Comment by nagromLobo** [comment] 2022-04-19 18:25
@shilman are you suggesting that CSF is not based on ES modules exporting objects with a particular API, but instead some static object structure? I must have misunderstood the docs if that's the case

**Comment by shilman** [comment] 2022-04-20 15:12
@nagromLobo CSF is based on ES modules exporting objects with a particular API

That said, there are limitations. Due to implementation details, there are certain things we don't support. For example, the following is valid ESM:

```js
const bar = 'bar';
export default { title: `foo/${bar}` }
```

However, we can't statically analyze that. So instead, you'd need to write it as:

```js
export default { title: "foo/bar" }
```

We've tried to encode some of these constraints into linting rules: https://github.com/storybookjs/eslint-plugin-storybook

**Comment by nagromLobo** [comment] 2022-04-20 15:36
To get storybook to play nice with typescript and our components we wrote some utils to generate the default export / individual stories. This suggests to me that that wouldn't be recommended. Practically I'm not seeing any problems (v6.4.21), though this makes me think that our storybook could run into issues in the future because we implemented this under the assumption that storybook was consuming runtime ES modules.

**Comment by shilman** [comment] 2022-04-20 15:40
@nagromLobo yes I'd recommend against it. try setting `features.breakingChangesV7:  true` in `main.js` to see why.

**Comment by nagromLobo** [comment] 2022-04-20 15:43
Is there a recommended way to get types tied to meta/stroies so that we could be confident that if a component's props changed we wouldn't be breaking any meta/stroies that reference it?

**Comment by shilman** [comment] 2022-04-20 16:24
WIP here https://github.com/storybookjs/storybook/issues/13747

**Comment by nagromLobo** [comment] 2022-04-20 17:01
Thanks for the quick responses and for pointing me to the right place!

**Comment by NiklasPor** [comment] 2022-04-29 11:42
> To get storybook to play nice with typescript and our components we wrote some utils to generate the default export / individual stories. This suggests to me that that wouldn't be recommended. Practically I'm not seeing any problems (v6.4.21), though this makes me think that our storybook could run into issues in the future because we implemented this under the assumption that storybook was consuming runtime ES modules.

We did exactly the same as you did @nagromLobo,  we have custom helper functions that wrap the CSF syntax and have additional requirements (`zeplinUrl`) which need to be provided. 

I guess the implementations based on runtime interpretation will break in V7?

**Comment by shilman** [comment] 2022-04-29 12:10
@NiklasPor We'll have a legacy mode so you can still use old code in V7. However, we're seeing dramatic performance improvements coming from the on-demand store + lazy compilation in webpack5, so in order to benefit from those you'll need to update your code.

**Comment by NiklasPor** [comment] 2022-04-29 12:20
@shilman Ok, that sounds great 🚀

**Comment by GideonMax** [comment] 2022-12-05 09:49
I am getting the same problem in v6.5.14.
I have a function `makeFormComponentMeta` which transforms a meta.
I could use global args, argtypes and decorators, except that I want to apply this function only to some components.
Is there some way to apply args and such to some stories, given some sort of glob pattern or regex?
Are there any plans to change this system in v7?
I think it's very counter-intuitive to have a configuration that's written in code but isn't actually code

**Comment by GideonMax** [comment] 2022-12-05 10:05
I had the same problem, took me a while to realize I had to set `storyStoreV7: false`
I think the storybook docs should elaborate on this, as the current description for the `storyStoreV7` flag is
"Configures Storybook to load stories [on demand](https://storybook.js.org/docs/react/configure/overview#on-demand-story-loading), rather than during boot up."
which doesn't really mention this problem.
Also, reading further into the article, it very vaguely mentions limitations in csf.

**Comment by KevinMind** [comment] 2023-03-13 17:02
@shilman  Is it not possible to evaluate the default export while statically analyzing the CSF module? We get dramatic DX imporvements by using this tiny helper for defining type safe meta/stories.

```tsx
import {ComponentProps, JSXElementConstructor} from 'react';
import {Meta, StoryObj} from '@storybook/react';

export function storyFactory<
  C extends keyof JSX.IntrinsicElements | JSXElementConstructor<any> = never,
>(Component: C, metaPrams: Omit<Meta<C>, 'component'>) {
  return {
    meta: {
      ...(metaPrams ?? {}),
      component: Component,
    },
    story: (args: StoryObj<ComponentProps<typeof Component>>) => args,
  };
}
```

example usage:

```tsx
import {storyFactory} from 'storybook-utils';

import {MyComponent} from './MyComponent';

const {meta, story} = storyFactory(MyComponent, {
  // define component level meta properties
  decorators: [],
  args: {}
});

// type safe stories
export const Default = story({
  args: {
    allConnectionsAssigned: false,
  },
});

export default meta;
```

Is there a reason why this should not be supported? As long as a function returns an object with valid meta properties, who cares how it is defined?

**Comment by AndrewBogdanovTSS** [comment] 2023-03-23 13:15
The issue is still present in version v7.0.0-rc.7 though I'm actually using default export in the component
```
export default {
  title: 'Components/Tabs/Static',
  component: VfTabs,
  args: {
    tabs: ['tab 1', 'tab 2', 'tab 3']
  },
  argTypes: {
    variant: {
      control: false
    },
    default: {
      control: false,
      description: 'Default slot for sections of tabs'
    }
  }
} as unknown as Meta
```

**Comment by jeshio** [comment] 2023-04-26 09:42
It's work only like this:

```typescript
export default { ...dynamicMeta, title: 'Buttons/TextButton' }
```

**Comment by koranke** [comment] 2024-03-10 23:09
I'm new to Storybook and was following the tutorial for Angular (https://storybook.js.org/tutorials/intro-to-storybook/angular/en/simple-component/).  At the step after updating config and restarting StoryBook, I get a similar error.

Unable to index ./src/app/components/task.stories.ts:
WARN   NoMetaError: CSF: missing default export /home/gcaccia/taskbox/src/app/components/task.stories.ts (line 1, col 0)

Is the tutorial invalid with the latest version of StoryBook or does the error mean I've done something wrong?

 Storybook 7.6.6 for angular started

**Comment by axedre** [comment] 2024-05-08 08:56
We're in a very similar situation as the one described by @KevinMind in [his comment](https://github.com/storybookjs/storybook/issues/16598#issuecomment-1466539165).
Is there still no update or timeline on when (or whether) such a syntax will ever be supported? For the record, our desired setup is quite similar:

**definition:**
```typescript
export const storyFactory = (
  Component: React.ComponentType
): {
  meta: Meta<React.ComponentType>;
  story: StoryObj<React.ComponentType>;
} => ({
  meta: {
    component: Component,
    decorators: [/*...*/],
    parameters: {/*...*/}
  },
  story: {
    render: () => {
      // stuff

      return (
        <>
          {/* stuff */}
          <Component />
        </>
      );
    }
  }
});
```
**usage:**
```typescript
const { meta, story } = storyFactory(() => (
  <MyComponent {...props} />
));

export { story };
export default meta;
```
which sadly yields:
```
CSF: missing default export
```

**Comment by shilman** [comment] 2024-05-08 10:55
@axedre that's a pretty lousy error message for your situation, but it is an error.

We're looking into adding an optional factory wrapper to CSF for better typescript support and that could land late this year. When it does, you might be able to hack it in limited ways.

But supporting arbitrary user defined functions is not on the roadmap and I don't see it ever being added to Storybook

**Comment by shilman** [comment] 2024-05-09 19:24
@axedre we are statically analyzing the code, i.e. parsing the content of it without ever executing the code. We do this for performance reasons so that we can quickly generate the sidebar content without bundling all of your stories and the components etc that they depend on. This isn't possible when the contents of meta is the result of some arbitrary black box function

**Comment by domastic-nate** [comment] 2024-05-26 01:10
agree that this is a big oversight @shilman.

is the maybe a thought for an annotation/hint that helps the static analyzer include other files?

**Comment by shilman** [comment] 2024-05-26 21:23
@domastic-nate  the plan is those factory functions would be provided by Storybook so that we know what's happening inside the black box and can provide the correct types

**Comment by woahitsjc** [comment] 2024-06-05 11:16
> @domastic-nate the plan is those factory functions would be provided by Storybook so that we know what's happening inside the black box and can provide the correct types

Would love this change. Is there another issue that is opened for this plan?
