### ISSUE TITLE
DefaultProps: display string when the defaultProps type is node

### ISSUE THREAD

**Issue by wupengfei1** [storybookjs/storybook#12098] opened 2020-08-18 05:44 UTC
**Describe the bug**
When my props has a node type, it will be render as a string type

**To Reproduce**

1.  npx create-react-app sb-app
2. npx sb init
3. Write a button component

**Expected behavior**
When prop is of node type, it is rendered as react node

**Code snippets**
MyButton.js

```js
export const MyButton = ({ children}) => {
  return (<button>{children}</button>);
};

MyButton.defaultProps = {
  children: <img src="https://randomuser.me/api/portraits/men/46.jpg" />
}

MyButton.propTypes = {
  children: PropTypes.node
}

```

MyButton.stories

```js
const Template = args => <MyButton {...args} />
export const Default = Template.bind({});
```

**Screenshots**
<img width="1067" alt="story2" src="https://user-images.githubusercontent.com/61856939/90474671-666ccf00-e158-11ea-9ce2-a865af677e73.png">

**System:**
```
    "@babel/core": "^7.11.1",
    "@storybook/addon-actions": "^6.0.12",
    "@storybook/addon-essentials": "^6.0.12",
    "@storybook/addon-links": "^6.0.12",
    "@storybook/node-logger": "^6.0.12",
    "@storybook/preset-create-react-app": "^3.1.4",
    "@storybook/react": "^6.0.12",
    "babel-loader": "^8.1.0",
    "prop-types": "^15.7.2",
    "react-is": "^16.13.1"
```

**Comment by shilman** [comment] 2020-08-18 08:45
Closing as dupe to #11429

**Comment by petmat** [comment] 2020-11-10 18:05
I don't think this is a dupe of #11429. As you can see in the screenshot the problem is not only that the control is a textbox but that the `<img>` tag is not rendered as an image but as text inside the button.

I had this happen to me as well with default values set in TypeScript.

```typescript
// Foo.tsx
export const Foo = ({ nodeProp = <Bar /> }: { nodeProp: React.ReactNode }) => <Baz theProp={nodeProp} />;

// Foo.stories.tsx
export const DefaultStory = () => <Foo />
// Renders <Baz theProp="<Bar />" /> 
```

**Comment by Pearce-Ropion** [comment] 2020-12-31 19:59
I agree that this isn't really a dupe of #11429 since this directly affects the preview of the story and not just the controls.

Here is my temporary workaround. Essentially I am updating the args with the component's default props on preview render. You could alternatively do this in any story's individual decorators. I am applying this change globally in `preview.js`.
```javascript
// preview.js

import { useArgs } from "@storybook/client-api";
export const decorators = [
    (Story, context) => {
        const { component } = parameters;
        if (component.defaultProps) {
            const [args, updateArgs] = useArgs();

            const storyArgKeys = Object.keys(context.parameters.args); // args that have been specifically set for the current story
            Object.entries(component.defaultProps).forEach(([propName, prop]) => {
                if (args[propName] === prop) { // prevent an infinite update loop
                    return;
                }

                if (!storyArgKeys.includes(propName)) {
                    const argType = context.argTypes[propName];
                    if (argType) {
                        const propType = argType.type.value;
                        if (propType === "node") {
                            updateArgs({
                                [propName]: prop,
                            });
                        }
                    }
                }
            });
        }

        return <Story />
    }
]
```

**Comment by JiniHendrix** [comment] 2021-01-11 18:29
I am also having this problem. when I return jsx in a function in a defaultProp the function itself turns into a string

**Comment by JiniHendrix** [comment] 2021-01-11 18:30
ie: renderThis: (value) => <span>value</span> becomes renderThis: "(value) => <span>value</span>"

**Comment by loganripplinger** [comment] 2021-01-11 18:56
The problem seems to lie at https://github.com/storybookjs/storybook/blob/4f5ab9fe9e590da7b841ec37cb1bed8d6327ea4b/addons/docs/src/frameworks/react/extractArgTypes.ts#L14

Seems to be running an `eval` against the defaultProp and React is not in scope so it cannot compile the JSX. I tried this with `React.createElement('span', {}, 'value')` and even that doesn't work.

**Comment by Pearce-Ropion** [comment] 2021-01-11 19:01
> I got around this by setting the default value in the component itself.
> 
> 
> 
> ```javascript
> 
> const MyComponent = ({
> 
>   renderValue,
> 
> }) => {
> 
>   if (!renderValue) {
> 
>     renderValue = (value) => <span>value</span>
> 
>     };
> 
>   }
> 
> }
> 
> ```

This is a bit of an anti pattern though. Although this is a lot of work if you have a lot of components that have this issue.

**Comment by KaiVandivier** [comment] 2021-02-18 23:14
I've found a bit of an easy work around for this issue: https://github.com/storybookjs/storybook/issues/12455#issuecomment-781695689

**Comment by JiniHendrix** [comment] 2021-02-24 20:56
@KaiVandivier that works perfectly, thanks

**Comment by kg-currenxie** [comment] 2021-03-03 03:18
@shilman @Pearce-Ropion ye i dont think this is a dupe either. This is about `defaultProps` becoming stringified..
We don't wanna do the workaround and changing dossens of components..

**Comment by Cnordbo** [comment] 2021-03-26 14:36
I did not get the workaround that @KaiVandivier suggested, to work. 
Could be a different issue tho? Trying to render a default component sent is as a parameter.  

```tsx
const Dropdown: React.FC<DropdownProps> = ({
    disabled = false,
    text = 'I am a dropdown',
    Icon = <KeyboardArrowDown />,
...
```
When trying to render that with default values, it just shows up as `<KeyboardArrowDown />` string. 

![image](https://user-images.githubusercontent.com/385693/112647565-f5f20300-8e48-11eb-99de-9484334a1e2e.png)

**Comment by shilman** [comment] 2023-06-07 12:17
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

**Closed by shilman** 2023-06-07 12:17 UTC
Labels: bug, react, addon: controls
