### ISSUE TITLE
[Bug]: [vite] Internal server error: Missing "./preview.js" specifier in "@storybook/react" package

### ISSUE THREAD

**Issue by kamiljurek** [storybookjs/storybook#23338] opened 2023-07-06 12:21 UTC
### Describe the bug

I am experiencing this error.

Using NX 16.5.0, storybook 7.0.26
commands done:
1. npm install -D @nx/storybook
2. nx g @nx/storybook:configuration {project_name}
3. nx storybook {project_name}

in the network tab in developer console I see the call:
http://localhost:4400/virtual:/@storybook/builder-vite/vite-app.js which returns 404
added test component is listed on the left side but endless loading circle is showed in the center:
<img width="863" alt="image" src="https://github.com/storybookjs/storybook/assets/2589325/a78ec1d8-034c-498a-babf-236c0ec55451">

component doesn't render at all.

any hints?

### System

logs:
`2:20:07 PM [vite] Internal server error: Missing "./preview.js" specifier in "@storybook/react" package
  Plugin: vite:import-analysis
  File: /virtual:/@storybook/builder-vite/vite-app.js
      at e (file:///Users/kajurek/repo/bdb/frontend/bdb-monorepo/node_modules/vite/dist/node/chunks/dep-1d3a4915.js:21424:25)
      at n (file:///Users/kajurek/repo/bdb/frontend/bdb-monorepo/node_modules/vite/dist/node/chunks/dep-1d3a4915.js:21424:627)
      at o (file:///Users/kajurek/repo/bdb/frontend/bdb-monorepo/node_modules/vite/dist/node/chunks/dep-1d3a4915.js:21424:1297)
      at resolveExportsOrImports (file:///Users/kajurek/repo/bdb/frontend/bdb-monorepo/node_modules/vite/dist/node/chunks/dep-1d3a4915.js:28705:20)
      at resolveDeepImport (file:///Users/kajurek/repo/bdb/frontend/bdb-monorepo/node_modules/vite/dist/node/chunks/dep-1d3a4915.js:28724:31)
      at tryNodeResolve (file:///Users/kajurek/repo/bdb/frontend/bdb-monorepo/node_modules/vite/dist/node/chunks/dep-1d3a4915.js:28415:20)
      at Context.resolveId (file:///Users/kajurek/repo/bdb/frontend/bdb-monorepo/node_modules/vite/dist/node/chunks/dep-1d3a4915.js:28176:28)
      at async Object.resolveId (file:///Users/kajurek/repo/bdb/frontend/bdb-monorepo/node_modules/vite/dist/node/chunks/dep-1d3a4915.js:44099:32)
      at async ModuleGraph._resolveUrl (file:///Users/kajurek/repo/bdb/frontend/bdb-monorepo/node_modules/vite/dist/node/chunks/dep-1d3a4915.js:64784:46)
      at async file:///Users/kajurek/repo/bdb/frontend/bdb-monorepo/node_modules/vite/dist/node/chunks/dep-1d3a4915.js:64702:45
      at async Promise.all (index 1)
      at async ModuleGraph.updateModuleInfo (file:///Users/kajurek/repo/bdb/frontend/bdb-monorepo/node_modules/vite/dist/node/chunks/dep-1d3a4915.js:64678:13)
      at async TransformContext.transform (file:///Users/kajurek/repo/bdb/frontend/bdb-monorepo/node_modules/vite/dist/node/chunks/dep-1d3a4915.js:42016:39)
      at async Object.transform (file:///Users/kajurek/repo/bdb/frontend/bdb-monorepo/node_modules/vite/dist/node/chunks/dep-1d3a4915.js:44175:30)
      at async loadAndTransform (file:///Users/kajurek/repo/bdb/frontend/bdb-monorepo/node_modules/vite/dist/node/chunks/dep-1d3a4915.js:54810:29)
^C%                                             `

**Comment by marcovanharten-cpi** [comment] 2023-07-06 12:33
@kamiljurek . We are running into the same issue

**Comment by silltho** [comment] 2023-07-06 13:27
Can confirm having the same issue. Downgrading storybook and addons to 7.0.25 does not work. We are also using nx but just for task execution, but i'm also facing the error when executing "storybook dev -p 6006" from npm scripts.

Example Config:

```  
import { StorybookConfig } from '@storybook/react-vite'
import { mergeConfig } from 'vite'

const config: StorybookConfig = {
  framework: {
    name: '@storybook/react-vite',
    options: {},
  },
  stories: ['../src/**/*.stories.@(tsx|mdx)'],
  addons: [
    '@storybook/addon-docs',
    '@storybook/addon-actions',
    '@storybook/addon-controls',
    '@storybook/addon-viewport',
    '@storybook/addon-backgrounds',
  ],
  async viteFinal(config) {
    const mergedConfig = mergeConfig(config, {
      build: {
        sourcemap: false, // prevent node out of memory error
      },
    })
    return mergedConfig
  },
}

export default config

```

**Comment by marcovanharten-cpi** [comment] 2023-07-06 13:30
Our team confirmed the issue is something with our vite version. Downgrading to `"vite": "~4.3.9"` patched up the issue for now... (not the greatest solution ofcourse)

**Comment by Mahonism** [comment] 2023-07-06 13:32
Just wanted to add the same answer as marcovanharten-cpi. We have the same issue and vite 4.3.9 is working with that issue. so we can confirm the workaround

**Comment by silltho** [comment] 2023-07-06 13:48
> Our team confirmed the issue is something with our vite version. Downgrading to `"vite": "~4.3.9"` patched up the issue for now... (not the greatest solution ofcourse)

Thx vite downgrade to 4.3 is solving the issue for now. ❤️

**Comment by TessavWalstijn** [comment] 2023-07-06 14:13
I have been pulling my hear for almost 5 hours >..<

Locking Vite on 3.9 fixed it!

**Comment by patak-dev** [comment] 2023-07-06 15:51
This issue should be fixed in vite@4.4.1

**Closed** 2023-07-06 18:25 UTC
Labels: bug, needs triage, builder-vite

**Comment by maaaathis** [comment] 2023-12-01 09:06
This error occurs again with storybook v7.6.2, nx v17.1.3 & vite 5.0.0.

**Comment by ant-dep** [comment] 2023-12-14 16:30
having the same with vite 5.0.9 and Storybook 7.6.4

**Comment by ant-dep** [comment] 2023-12-29 08:44
> having with vite 5.0.9 and Storybook 7.6.4
> 
> ```
> => Failed to build the preview
> Error: Missing "./preview" specifier in "@storybook/react" package  with vite 5.0.9 and Storybook 7.6.4
> ```
> 
> edit (29/12/23): same with 5.0.10 and Storybook 7.6.6

I fixed it by removing ViteFinal optmize deps from .storybook/main.ts

```
  viteFinal: async (config) => {
    config.optimizeDeps = {
      ...config.optimizeDeps,
      include: [
        '@bbbtech/storybook-formik',
        '@storybook/react/preview',
        '@storybook/addon-docs/preview',
        '@storybook/addon-essentials/backgrounds/preview',
        '@storybook/addon-essentials/measure/preview',
        '@storybook/addon-essentials/outline/preview',
        '@storybook/addon-essentials/highlight/preview',
        '@storybook/addon-actions/preview',
        'storybook-addon-pseudo-states/preview'
      ]
    };

    return config;
  }
```

**Comment by Sinakhx** [comment] 2024-01-06 10:11
removing node_modules & .lock files & re-installing the packages fixed the issue for me.

**Comment by ant-dep** [comment] 2024-01-06 10:50
Storybook 7.6.7 fixes this :)

**Comment by Darkspice** [comment] 2024-01-17 14:08
Update package @storybook/react to 7.6.9 helped fix this issue.

**Comment by enix79** [comment] 2024-01-23 21:29
I was able to fix this issue by running "npx storybook automigrate" and realizing, that my storybook deps are note deduped:
![image](https://github.com/storybookjs/storybook/assets/39030503/dade69fd-0d20-4df8-b6f2-a1a0c2df335e)

After I have run "npm dedupe", that error has gone.

I had issues with both react and react-vite packages:
![image](https://github.com/storybookjs/storybook/assets/39030503/4ab07e12-a15e-4d9b-b1c6-202e1af1b174)

**Comment by silouanwright** [comment] 2025-02-21 01:18
If anyone comes across this issue, look very carefully at your storybook main.js file. You may have added some level of configuration that was necessary for older Storybook versions, but not for the latest ones.
