### ISSUE TITLE
Uncaught DOMException: Blocked a frame with origin "http://localhost:9009" from accessing a cross-origin frame.

### ISSUE THREAD

**Issue by kon-rad** [storybookjs/storybook#7215] opened 2019-06-27 01:54 UTC
**Describe the bug**
After updated storybook 3 to 5 the 'actions addon' throws CORS error when an action is performed. Figured out that setting the 'depth' option to 2 or less is a work around and no error appears. Posting bug report hoping any better solution may be found. 

**To Reproduce**
1. Initiate any action on storybook 5. CORS error appears in console.

**Expected behavior**
Actions should be performed.

**Screenshots**
N/A

**Code snippets**
I traced the bug to the following line:
```
      var data = (0, _telejson.stringify)({
        key: KEY,
        event: event
      }, {
        maxDepth: depth
      }); // TODO: investigate http://blog.teamtreehouse.com/cross-domain-messaging-with-postmessage
      // might replace '*' with document.location ?

      iframeWindow.postMessage(data, '*');
      return Promise.resolve(null);
```
This configuration fixes the issue. But it would be great to have this resolved and allow for display of action with greater depth of the object. 
```
configureActions({
  depth: 2 // anything higher than 2 causes CORS error in iframe postMessage method
});
```

**System:**
 - OS:  MacOS
 - Device: Macbook Pro 2018
 - Browser: chrome
 - Framework: react
 - Addons: actions
 - Version:  5.1.9

**Additional context**
This happened after upgrading from 3 to 5. Default webpack config is used. Babel was also upgraded to 7.

**Comment by dancrumb** [comment] 2019-10-25 20:46
This is still not resolved; should we re-open this or open a new issue?

**Comment by StJohn3D** [comment] 2019-11-11 21:36
Clicked actions like in the documentation are working in Chrome but not in firefox.
Currently seeing this DOMException in FireFox
`SecurityError: Permission denied to access property "toJSON" on cross-origin object`

**Comment by ndelangen** [comment] 2019-11-25 10:36
I opened a fix PR in telejson!

**Comment by shilman** [comment] 2019-11-26 01:10
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-beta.8 containing PR #8940 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by zeorin** [comment] 2020-01-28 16:32
`v5.3.0-beta.8` still has the Firefox bug for me. Version `v5.3.9` also has the bug.
Version `v6.0.0-alpha.1` also has the bug.

**Comment by ndelangen** [comment] 2020-01-28 18:01
@zeorin could you check to see if the `telejson` dependency is actually updated in `node_modules` after installing?

**Comment by sgtdck** [comment] 2020-01-30 04:28
@ndelangen it is for me:

```
npm ls telejson
planner@0.1.0 /Users/dick/Workspace/planner
└─┬ @storybook/react@6.0.0-alpha.1
  ├─┬ @storybook/addons@6.0.0-alpha.1
  │ └─┬ @storybook/api@6.0.0-alpha.1
  │   └── telejson@3.3.0 
  └─┬ @storybook/core@6.0.0-alpha.1
    ├─┬ @storybook/channel-postmessage@6.0.0-alpha.1
    │ └── telejson@3.3.0  deduped
    └─┬ @storybook/ui@6.0.0-alpha.1
      └── telejson@3.3.0  deduped
```

**Comment by ndelangen** [comment] 2020-01-30 08:50
Thank you for checking.

Will put this back on my todo list

**Comment by ndelangen** [comment] 2020-05-18 12:05
Could you please upgrade to the latest version and tell me if this is still a problem, and if it is give me a reproduction repo? 👏

**Comment by StJohn3D** [comment] 2020-05-18 13:47
@ndelangen this looks related to my issue #8768 which already includes steps to reproduce.

**Comment by estevaolucas** [comment] 2020-05-20 15:57
I some the same issue happening for me, on my server (locally it was fine), but I didn't need to update the storybook to fix it. 

It was just a matter of setting the appropriate Content Security Policy header, changing `X-Frame-Options: "DENY"` to `X-Frame-Options: "SAMEORIGIN"`.

**Comment by ndelangen** [comment] 2020-05-21 14:35
@StJohn3D I think all of the core addons have stopped doing this in 6.0.0 beta

**Comment by sami616** [comment] 2020-07-22 10:18
Im seeing this issue with the SB6 rc

**Comment by rey-wright** [comment] 2020-08-05 13:57
I'm seeing this issue as well.

**Comment by rey-wright** [comment] 2020-08-05 18:13
One important note of context for me: I'm trying to access the storybook production build directly by opening the `index.html` file. `^5.3.19` is the last version I tested where I was very easily able to do this. Any versions thereafter I've sort of had issues and get this cross-origin issue. If I run a server and load storybook, it works. Ideally storybook works "statically" without a server as well, but in any case this is how I'm triggering this issue. I don't know if this is the same ticket or another ticket but I'm happy to create an additional issue if it is.

**Comment by michaelbayday** [comment] 2020-08-13 17:40
I am also seeing this issue right now with 6.0.2

**Comment by ndelangen** [comment] 2020-08-17 10:16
@michaelbayday could you supply a reproduction repo perhaps?

**Comment by michaelbayday** [comment] 2020-08-17 14:34
Let me see if I can get a boiler plate going or what I have in my repo

**Comment by hinok** [comment] 2020-08-27 16:15
I have the same problem locally.
I created a codesandbox that demonstrates this problem:

**CodeSandbox**
https://codesandbox.io/s/mystifying-mendeleev-zoxtz?file=/src/stories/button.story.tsx

**Fullscreen**
https://zoxtz.sse.codesandbox.io/?path=/story/button--button-story

**Reported error after clicking on button**

```python
Uncaught DOMException: Blocked a frame with origin "https://zoxtz.sse.codesandbox.io" from accessing a cross-origin frame.
    at JSON.stringify (<anonymous>)
    at stringify (https://zoxtz.sse.codesandbox.io/vendors~main.b4ad10535b4fddcf135c.bundle.js:69661:15)
    at PostmsgTransport.send (https://zoxtz.sse.codesandbox.io/vendors~main.b4ad10535b4fddcf135c.bundle.js:2172:42)
    at handler (https://zoxtz.sse.codesandbox.io/vendors~main.b4ad10535b4fddcf135c.bundle.js:2505:28)
    at Channel.emit (https://zoxtz.sse.codesandbox.io/vendors~main.b4ad10535b4fddcf135c.bundle.js:2515:9)
    at actionHandler (https://zoxtz.sse.codesandbox.io/vendors~main.b4ad10535b4fddcf135c.bundle.js:512:13)
    at HTMLUnknownElement.callCallback (https://zoxtz.sse.codesandbox.io/vendors~main.b4ad10535b4fddcf135c.bundle.js:36255:14)
    at Object.invokeGuardedCallbackDev (https://zoxtz.sse.codesandbox.io/vendors~main.b4ad10535b4fddcf135c.bundle.js:36304:16)
    at invokeGuardedCallback (https://zoxtz.sse.codesandbox.io/vendors~main.b4ad10535b4fddcf135c.bundle.js:36359:31)
    at invokeGuardedCallbackAndCatchFirstError (https://zoxtz.sse.codesandbox.io/vendors~main.b4ad10535b4fddcf135c.bundle.js:36373:25)
```

**Comment by ndelangen** [comment] 2020-09-01 07:59
confirmed.. It seems the stringification of the event fails

<img width="606" alt="Screenshot 2020-09-01 at 09 58 53" src="https://user-images.githubusercontent.com/3070389/91823610-c58f1100-ec39-11ea-949d-686ee1d1ba15.png">

**Comment by inspiratweb** [comment] 2020-09-09 23:27
Same problem here in 6.0.21

**Comment by brycesnyder** [comment] 2020-09-10 02:28
I'm getting this when attempting to build my local by running `yarn build-storybook` and then opening the `index.html` within the `storybook-static` repo...

**Comment by sami616** [comment] 2020-09-10 05:53
Is this issue related to sb core or a specific add on?

**Comment by michaelbayday** [comment] 2020-09-10 05:56
are others using JSON.stringify in their stories?

**Comment by sami616** [comment] 2020-09-10 07:50
> are others using JSON.stringify in their stories?
> […](#)
> On Sep 9, 2020, at 10:53 PM, Sami Resua ***@***.***> wrote: ﻿ Is this issue related to sb core or a specific add on? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Not me.

**Comment by ldeveber** [comment] 2020-10-16 14:40
I'm seeing this in 6.0.26.

**Comment by asherccohen** [comment] 2020-10-26 14:44
Hi everyone. Is this an issue in storybook@6.0.27? I am getting cors errors fetching stories.json.
I am serving storybook instances locally (npx serve) and I cannot get my main Storybook to fetch stories from other instances running.

**Comment by ndelangen** [comment] 2020-10-26 15:49
Does `npx serve` serve with CORS headers enabled?

**Comment by shilman** [comment] 2020-11-04 02:18
Can you try `npx http-server`? we've had problems with `serve`

**Comment by ndelangen** [comment] 2020-11-11 14:48
I'm trying to reproduce this error again with the repro on codesandbox by @hinok 

But I'm able to use that link now, where before I was indeed seeing the problem, it seems to work now:
![Uploading Screenshot 2020-11-11 at 15.47.07.png…]()

**Comment by hinok** [comment] 2020-11-13 22:08
@ndelangen I checked it and it still throws the error 😞

![Zrzut ekranu 2020-11-13 o 23 07 08](https://user-images.githubusercontent.com/1313605/99125774-1097ae00-2605-11eb-93d7-03be89ebed40.png)

**Comment by itsderek23** [comment] 2020-11-18 18:19
I'm seeing this with the [Storybook Design System](github.com/storybookjs/design-system) when trying to access `index.html` after running `yarn run build-storybook`. The non-static version (`yarn storybook start`) runs fine.

The project is running storybook 6.1.0-rc.3.

![image](https://user-images.githubusercontent.com/7880/99570938-e7be4280-298f-11eb-832c-395e4a1bda2d.png)

**Comment by shilman** [comment] 2020-11-18 18:44
@itsderek23 I don't think it works with file URLs. you need to run a web server like `npx http-server`. works fine when served: https://storybook-design-system.netlify.app/

**Comment by itsderek23** [comment] 2020-11-18 18:48
Head slap! Yes - that is it. For clarity, this works just fine:

```
 npx http-server storybook-static/
```

**Comment by reywright** [comment] 2020-11-18 20:42
@shilman is that known? I ask because that was not always the case before v6, you could easily build an instance, compress it and share it with others. I feel like it's possible that a lot of people in this thread are running into this because it's not being run on a local server for whatever reason.

**Comment by shilman** [comment] 2020-11-19 01:06
@reywright This issue is still open, isn't it? 😉 I think we were looking for a repro and the repro is to open built storybook from a file URL @ndelangen

**Comment by anicholls** [comment] 2020-11-26 00:04
I am also seeing this when trying to use Storybook Composition. It works fine within the original storybook, but I get the same error (`Uncaught DOMException: Blocked a frame with origin from accessing a cross-origin frame.`) at the [same line](https://github.com/storybookjs/telejson/blob/master/src/index.ts#L352) whenever trying to load a story from the lower level "composed" storybook in the higher level "composing" storybook. Both storybook instances on 6.1.5, using basically stock webpack configs. Anyone have ideas for a solution or workaround?

**Comment by webholics** [comment] 2020-12-10 09:46
I'm also having this issue. Our current workaround which worked is to disable the actions addon.

**Comment by Blizard** [comment] 2021-01-11 09:30
As @anicholls mentioned edit. Same for me. I fixed this issue when i disabled docs addon for particular stories or for all stories.

**Comment by anicholls** [comment] 2021-01-11 21:09
Another update: I think I've tracked down the issue with the Docs addon and I've opened a separate issue for it here: https://github.com/storybookjs/storybook/issues/13608.

Unfortunately the args (and their defaults) are extracted for all stories regardless of which ones have docs disabled so the only option to get composition to work is to disable the docs addon entirely.

**Comment by ghlai9665** [comment] 2021-03-10 11:09
I solved this by opening storybook in an incognito window. It's possible that Chrome plugins are messing with the browser.

**Comment by ndelangen** [comment] 2021-03-17 13:22
I think we can close this issue now, https://github.com/storybookjs/storybook/issues/13608 was the fix.

**Closed by ndelangen** 2021-03-17 13:22 UTC
Labels: P0, addon: actions, bug, composition, tracked

**Comment by abbudao** [comment] 2021-03-27 11:35
I believe I'm having this same issue on `6.2.0-rc.10`. The problem is unique to Firefox (tested on 87, incognito off and on), as all examples worked just fine on Chromium 89.
![Screenshot-2021-03-27T05:13:19-03:00](https://user-images.githubusercontent.com/4575197/112719097-ba514a80-8ed5-11eb-9b4b-8c4aac429a91.png)
Repro:
1. Create a fresh project with Create React App and Storybook CLI :
```sh
npx create-react-app bug-repro --template typescript && cd bug-repro && npx sb init && sed -i 's/"^6.1.*"/"6.2.0-rc.10"/' package.json && yarn && yarn run storybook
```
2. Open Firefox and click on Header > Logged In component
3. Click on the `Log out` button

Let me know if I can be of any help 😉

**Comment by nickofthyme** [comment] 2021-07-29 21:33
I am still seeing this issue having a similar case to @itsderek23.

I recently upgrade storybook from `^5.3.19` to `^6.3.4` with no major changes to our component src code.

### What works?
- Running storybook via `storybook-start` ✅ 
- Building storybook via `storybook-build` and hosting the build via `npx http-server <output>` ✅ 

### What does NOT work?
- Opening the output `index.html` in Chrome directly from file path, also not working in incognito. This worked in `5.3.19` ❌ 
- Building and deploying storybook to gh-pages. This worked in `5.3.19` ❌ 

Both cases above throw the following errors in the console.

```
vendors~main.a4359a8c7927629868c8.manager.bundle.js:2 DOMException: Blocked a frame with origin "null" from accessing a cross-origin frame.
    at file:///Users/elon/storybook-output/main.241a4736bb305c4597a6.manager.bundle.js:1:13628
    at Ii (file:///Users/elon/storybook-output/vendors~main.a4359a8c7927629868c8.manager.bundle.js:2:1615635)
    at Vj (file:///Users/elon/storybook-output/vendors~main.a4359a8c7927629868c8.manager.bundle.js:2:1634368)
    at exports.unstable_runWithPriority (file:///Users/elon/storybook-output/vendors~main.a4359a8c7927629868c8.manager.bundle.js:2:1652922)
    at cg (file:///Users/elon/storybook-output/vendors~main.a4359a8c7927629868c8.manager.bundle.js:2:1577591)
    at Dj (file:///Users/elon/storybook-output/vendors~main.a4359a8c7927629868c8.manager.bundle.js:2:1634130)
    at yj (file:///Users/elon/storybook-output/vendors~main.a4359a8c7927629868c8.manager.bundle.js:2:1625989)
    at file:///Users/elon/storybook-output/vendors~main.a4359a8c7927629868c8.manager.bundle.js:2:1577882
    at exports.unstable_runWithPriority (file:///Users/elon/storybook-output/vendors~main.a4359a8c7927629868c8.manager.bundle.js:2:1652922)
    at cg (file:///Users/elon/storybook-output/vendors~main.a4359a8c7927629868c8.manager.bundle.js:2:1577591)
Ci @ vendors~main.a4359a8c7927629868c8.manager.bundle.js:2
vendors~main.a4359a8c7927629868c8.manager.bundle.js:2 Uncaught DOMException: Blocked a frame with origin "null" from accessing a cross-origin frame.
    at file:///Users/elon/storybook-output/main.241a4736bb305c4597a6.manager.bundle.js:1:13628
    at Ii (file:///Users/elon/storybook-output/vendors~main.a4359a8c7927629868c8.manager.bundle.js:2:1615635)
    at Vj (file:///Users/elon/storybook-output/vendors~main.a4359a8c7927629868c8.manager.bundle.js:2:1634368)
    at exports.unstable_runWithPriority (file:///Users/elon/storybook-output/vendors~main.a4359a8c7927629868c8.manager.bundle.js:2:1652922)
    at cg (file:///Users/elon/storybook-output/vendors~main.a4359a8c7927629868c8.manager.bundle.js:2:1577591)
    at Dj (file:///Users/elon/storybook-output/vendors~main.a4359a8c7927629868c8.manager.bundle.js:2:1634130)
    at yj (file:///Users/elon/storybook-output/vendors~main.a4359a8c7927629868c8.manager.bundle.js:2:1625989)
    at file:///Users/elon/storybook-output/vendors~main.a4359a8c7927629868c8.manager.bundle.js:2:1577882
    at exports.unstable_runWithPriority (file:///Users/elon/storybook-output/vendors~main.a4359a8c7927629868c8.manager.bundle.js:2:1652922)
    at cg (file:///Users/elon/storybook-output/vendors~main.a4359a8c7927629868c8.manager.bundle.js:2:1577591)
vendors~main.a4359a8c7927629868c8.manager.bundle.js:2  manager  received storybookjs/knobs/set-options but was unable to determine the source of the event
error @ vendors~main.a4359a8c7927629868c8.manager.bundle.js:2
vendors~main.a4359a8c7927629868c8.manager.bundle.js:2  manager  received storyRendered
```

I also have the docs addon disabled so I'm not sure how https://github.com/storybookjs/storybook/issues/7215#issuecomment-801076069 is the fix to this issue.

Am I missing something here?

**Comment by markov00** [comment] 2021-07-30 10:02
I'd also like to link a similar case here with GitHub Pages https://github.com/storybookjs/storybook-deployer/issues/97

**Comment by nickofthyme** [comment] 2021-07-30 19:00
After removing [`storybook-addon-themes`](https://github.com/tonai/storybook-addon-themes) accessing via `output/index.html` works fine.

**Comment by b0o** [comment] 2021-11-16 09:05
I was having this issue and it turned out one of my Firefox extensions (Surfingkeys) was triggering it to happen. The question is why was this happening?

**Comment by nickofthyme** [comment] 2021-11-16 14:38
In the case of [`storybook-addon-themes`](https://github.com/tonai/storybook-addon-themes), they are attempting to access the story preview iframe via it's id ([`'storybook-preview-iframe'`](https://github.com/tonai/storybook-addon-themes/blob/a1941f1f096c0504e1cad3a671dc2b1a035a99f0/src/manager/ThemeSelector.tsx#L16)). They do this to pass styles to be set on elements within the iframe but a better way is to use globals to pass the context down. Doing this causes no issues when run on a local http server but DOES throw the above error when accessing the statically built site.

I'm not sure if this is the same cause for `Surfingkeys`.
