### ISSUE TITLE
Controls Addon - Ability to reset attributes of a story component

### ISSUE THREAD

**Issue by akhilesh85** [storybookjs/storybook#11509] opened 2020-07-11 13:17 UTC
**Is your feature request related to a problem? Please describe.**
While using Controls Addon like "select" we often choose an option from a dropdown and there is no way to select the initial state of the control. The scenario is explained in the gif screenshot shared. The only way to set to the initial state is t refresh the browser page.

**Describe the solution you'd like**
An ability to reset the component state without the need to refresh the browser.

**Describe alternatives you've considered**
The only way right now to rest an attribute, I have to implement ngOnchnages and add an extra parameter to my options collection as "Reset". When we have more than one attributes it becomes a lot of work and we have t add specific codes to make storybook controls compatible.

**Are you able to assist bring the feature to reality?**
Yes

**Additional context**

![Storybook_Addon_Control_Reset](https://user-images.githubusercontent.com/67741191/87224928-c0d97980-c3bb-11ea-8587-bceba258112d.gif)

**Comment by BPScott** [comment] 2020-07-11 21:30
Duplicate of / highly related to #11487?

**Comment by shilman** [comment] 2020-07-12 05:17
Yup closing as dupe

**Closed** 2020-07-12 05:17 UTC
Labels: addon: controls, feature request

**Comment by akhilesh85** [comment] 2020-07-12 05:19
Noted, Thanks. I will look forward for the feature to be available in the upcoming releases. 😊
