### ISSUE TITLE
Storybook + Angular + Inputs / Controls doesn't work with Compodoc 1.1.12

### ISSUE THREAD

**Issue by JustDoItSascha** [storybookjs/storybook#15537] opened 2021-07-09 12:01 UTC
For reproduction:

I created a new angular project with the cli (v 12.1.1) and added storybook (v 6.3.4). Compodoc 1.1.12 has been installed. Now if I add a @Input() to one of my components and create a story for that component with default args, I got no controls rendered.

If I switch back to Compodoc 1.1.11 everything works. The difference between 1.1.11 and 1.1.12 is, that properties marked with an @Input() are listed under inputsClass AND propertiesClass in the documentation.json. In 1.1.11 it's only listed under 1.1.11.

**Comment by daeteck** [comment] 2021-07-10 01:10
Yes, same issue here.

With the Compodoc version 1.1.12 and 1.1.13 (that it's the latest) some @Input() stoped working. Only if the type it is explicitly specified in the argTypes it seems to works. It is like Storybook is not inferring the type of the @Input since Compodoc 1.1.12.

**Comment by dexster** [comment] 2021-07-11 08:47
I fixed this in Storybook addon docs but it seems very hacky so I've since raised a bug with compodocs asking if this is intended behaviour. Let's wait for a reply. If it is intended then I'll submit my fix.

[https://github.com/compodoc/compodoc/issues/1095](https://github.com/compodoc/compodoc/issues/1095)

In the meantime I suggest you pin compodocs to v1.1.11

**Comment by shilman** [comment] 2021-07-13 15:42
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-alpha.16 containing PR #15563 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2021-07-13 15:42 UTC
Labels: P1, addon: docs, app: angular, block: argstable, bug, good first issue, help wanted

**Comment by dexster** [comment] 2021-07-13 19:37
@shilman This particular issue has been fixed by the compodoc author and will be in the next release. No changes to storybook required for this issue.
