### ISSUE TITLE
HMR doesn't work after Storybook v6.1.14

### ISSUE THREAD

**Issue by Morgan-jarry** [storybookjs/storybook#13914] opened 2021-02-15 14:53 UTC
**Describe the bug**
When I update a component or a stylesheet link to it, the hot module reload is not triggered.

**To Reproduce**
Update a component by updating a prop, adding a classname, or whatever.

**Expected behavior**
HMR should be trigger on every component update.

**System**
```
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 14.15.3 - ~/.asdf/installs/nodejs/14.15.3/bin/node
    Yarn: 1.22.10 - ~/.asdf/shims/yarn
    npm: 6.14.9 - ~/.asdf/installs/nodejs/14.15.3/bin/npm
  Browsers:
    Chrome: 88.0.4324.150
    Firefox: 84.0.2
    Safari: 14.0.1
  npmPackages:
    @storybook/addon-a11y: 6.1.18 => 6.1.18
    @storybook/addon-actions: 6.1.18 => 6.1.18
    @storybook/addon-docs: 6.1.18 => 6.1.18
    @storybook/addon-essentials: 6.1.18 => 6.1.18
    @storybook/addon-links: 6.1.18 => 6.1.18
    @storybook/addons: 6.1.18 => 6.1.18
    @storybook/react: 6.1.18 => 6.1.18
    @storybook/theming: 6.1.18 => 6.1.18
  ```

**Comment by shilman** [comment] 2021-02-15 15:24
What version were you updating from?

**Comment by Morgan-jarry** [comment] 2021-02-15 15:27
Sorry it was on the title. I was using Storybook 6.1.14

**Comment by shilman** [comment] 2021-02-15 16:51
Did you try removing `node_modules` and/or lockfiles and reinstalling? I'm not seeing anything in the changelog related to this.

**Comment by Morgan-jarry** [comment] 2021-02-15 17:03
Yes every time.

**Comment by shilman** [comment] 2021-02-15 17:10
Do you have a repro repo you can share?

**Comment by Morgan-jarry** [comment] 2021-02-16 14:49
unfortunately, I can't share the repo, but, I've found that the rerendering works very slowly as you can see below :
![image](https://user-images.githubusercontent.com/523306/108078893-7d8c6b00-706e-11eb-8073-8b8a7edb9781.png)

**Comment by lucascurti** [comment] 2021-03-12 10:37
Deleting `node_modules/.cache` and restarting temporary fix it. In my case it breaks when saving multiple files. Once it breaks, it doesn't matter if I restart storybook, it will still be broken and deleting the cache is the only way to fix it.

**Comment by krishn-kk** [comment] 2021-04-26 13:58
Hi, have we identified any issues regarding this? Or is it already fixed in the latest updates? Cause I was using Storybook v6.1.21 and facing the exact same issue.

**Comment by reno1979** [comment] 2021-07-15 11:58
same problem here (6.3.0 -> 6.3.4)      It keeps building and is very very slow.
The project has only 10 stories

**Comment by shilman** [comment] 2023-06-08 03:01
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

**Closed by shilman** 2023-06-08 03:01 UTC
Labels: question / support, react, has workaround
