### ISSUE TITLE
Storybook + Chakra UI V1 not displaying styles

### ISSUE THREAD

**Issue by MariuzM** [storybookjs/storybook#13114] opened 2020-11-14 08:46 UTC
**Describe the bug**
With the new version of Chakra UI v1 storybook has stoped displaying styles, when doing `yarn storybook` it loads the page but does not display the styles.

Old version:
![Screen Shot 2020-11-14 at 08 42 09](https://user-images.githubusercontent.com/36937039/99143490-cab70600-2655-11eb-90ff-25e5aa59eb9b.png)
![Screen Shot 2020-11-14 at 08 41 04](https://user-images.githubusercontent.com/36937039/99143491-cb4f9c80-2655-11eb-9385-5965f4d14dd1.png)

New version
![Screen Shot 2020-11-14 at 08 42 00](https://user-images.githubusercontent.com/36937039/99143499-cf7bba00-2655-11eb-8580-b27e678c2d31.png)
![Screen Shot 2020-11-14 at 08 43 46](https://user-images.githubusercontent.com/36937039/99143502-cf7bba00-2655-11eb-8193-aba561e61bbf.png)
![Screen Shot 2020-11-14 at 08 44 26](https://user-images.githubusercontent.com/36937039/99143503-d0145080-2655-11eb-86ad-89dafba3101d.png)

Component
![Screen Shot 2020-11-14 at 08 41 12](https://user-images.githubusercontent.com/36937039/99143540-26818f00-2656-11eb-9dd9-a99794e24009.png)

**Comment by shilman** [comment] 2020-11-15 00:56
Do you have a repro repo you can share?

**Comment by MariuzM** [comment] 2020-11-15 08:16
Here you go, it's all standard install https://github.com/MariuzM/bug_testing

**Comment by ivan-dalmet** [comment] 2020-11-15 14:48
Same problem here (https://github.com/ivan-dalmet/start-ui)
I think it's the emotion 11. But no idea how to fixed it :/

**Comment by taponidhitulsi** [comment] 2020-11-16 07:29
Same problem in a project with **NextJS + Typescript + Chakra UI + Storybook**.

**Comment by khanhleemtp** [comment] 2020-11-16 14:56
Same problem

**Comment by lee-reinhardt** [comment] 2020-11-16 16:04
I was able to work around this by implementing a custom `webpackFinal` config:
https://github.com/chakra-ui/chakra-ui/issues/2527#issuecomment-728134371

**Comment by MariuzM** [comment] 2020-11-20 19:36
Any updates on getting this fixed?

**Comment by shilman** [comment] 2020-11-21 05:20
@MariuzM PRs welcome!

**Comment by cloud-walker** [comment] 2020-11-21 09:28
The fix should be to upgrade emotion to v11?

https://github.com/storybookjs/storybook/blob/a5bd17f2625a03b42f8159ad6c811e6639a04c88/lib/ui/package.json#L30

**Comment by SyedUmerHasan** [comment] 2021-05-13 09:24
This issue is also happening with other libraries as well.
Can someone mention its root cause?

**Comment by florianmartens** [comment] 2021-05-20 21:38
Same here.

**Comment by Cretezy** [comment] 2021-05-22 21:14
Here is the solution that worked for me:

```js
module.exports = {
  stories: ["../src/**/*.stories.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
  addons: ["@storybook/addon-links", "@storybook/addon-essentials"],
  webpackFinal: async (config) => {
    return {
      ...config,
      resolve: {
        ...config.resolve,
        alias: {
          ...config.resolve.alias,
          "@emotion/core": "@emotion/react",
          "emotion-theming": "@emotion/react",
        },
      },
    };
  },
};
```

**Comment by lakshmimani** [comment] 2021-05-24 15:28
> Here is the solution that worked for me:
> 
> ```js
> module.exports = {
>   stories: ["../src/**/*.stories.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
>   addons: ["@storybook/addon-links", "@storybook/addon-essentials"],
>   webpackFinal: async (config) => {
>     return {
>       ...config,
>       resolve: {
>         ...config.resolve,
>         alias: {
>           ...config.resolve.alias,
>           "@emotion/core": "@emotion/react",
>           "emotion-theming": "@emotion/react",
>         },
>       },
>     };
>   },
> };
> ```

This worked for me

**Comment by agamm** [comment] 2021-08-28 01:00
> 
> 
> Here is the solution that worked for me:
> 
> ```js
> module.exports = {
>   stories: ["../src/**/*.stories.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
>   addons: ["@storybook/addon-links", "@storybook/addon-essentials"],
>   webpackFinal: async (config) => {
>     return {
>       ...config,
>       resolve: {
>         ...config.resolve,
>         alias: {
>           ...config.resolve.alias,
>           "@emotion/core": "@emotion/react",
>           "emotion-theming": "@emotion/react",
>         },
>       },
>     };
>   },
> };
> ```

Maybe `npx sb init` can check for chakraui and add this (working) fix automatically?

**Comment by rrsai** [comment] 2021-12-03 14:54
After much debugging of the clash between versions of emotion used in storybook and in app, and for those who come after me, I found that storybook has now provided a feature flag to avoid clashing with later versions of emotion: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#emotion11-quasi-compatibility

**Comment by MariuzM** [comment] 2021-12-03 15:26
I think web is going to start moving to https://stitches.dev/ :D

**Comment by shilman** [comment] 2022-02-01 12:56
FYI, we'll hopefully have a fix out this week

**Comment by shilman** [comment] 2022-02-01 13:35
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.31 containing PR #17000 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2022-02-01 13:35 UTC
Labels: question / support, compatibility with other tools, has workaround, theming, P1
