### ISSUE TITLE
Problems with create-react app

### ISSUE THREAD

**Issue by Pablo-Codeiro-Peya** [storybookjs/storybook#17332] opened 2022-01-25 17:58 UTC
**Describe the bug**
After using create-react-app, when I execute `npm run storybook` it throws an error.

**To Reproduce**

```bash
$ nvm use v14.18.2
$ npx create-react-app some-project-name
$ cd some-project-name
$ npx sb init
$ npm run storybook
```

STDOUT:

```
$ npm run storybook

> some-project-name@0.1.0 storybook /Users/myusername/work/my-testing-folder/some-project-name
> start-storybook -p 6006 -s public

info @storybook/react v6.4.14
info
(node:33173) DeprecationWarning: --static-dir CLI flag is deprecated, see:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated---static-dir-cli-flag
(Use `node --trace-deprecation ...` to show where the warning was created)
info => Loading presets
info => Serving static files from ./public at /
info => Loading Webpack configuration from `node_modules/react-scripts`
info => Removing existing JavaScript and TypeScript rules.
info => Modifying Create React App rules.
info => Using default Webpack5 setup
<i> [webpack-dev-middleware] wait until bundle finished
10% building 0/1 entries 0/0 dependencies 0/0 modulesinfo => Using prebuilt manager
99% done plugins webpack-hot-middlewarewebpack built preview 62da20d9ab2024218a05 in 9051ms
ModuleNotFoundError: Module not found: Error: Can't resolve './diff' in '/Users/myusername/work/my-testing-folder/some-project-name/node_modules/deep-object-diff/mjs'
Did you mean 'diff.js'?
BREAKING CHANGE: The request './diff' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/Compilation.js:2013:28
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:795:13
    at eval (eval at create (/Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:431:22
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:124:11
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:667:25
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:852:8
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:972:5
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/neo-async/async.js:6883:13
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:889:17
    at finishResolved (/Users/myusername/work/my-testing-folder/some-project-name/node_modules/enhanced-resolve/lib/Resolver.js:278:11)
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/enhanced-resolve/lib/Resolver.js:342:25
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/enhanced-resolve/lib/Resolver.js:409:24
    at eval (eval at create (/Users/myusername/work/my-testing-folder/some-project-name/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
resolve './diff' in '/Users/myusername/work/my-testing-folder/some-project-name/node_modules/deep-object-diff/mjs'
  using description file: /Users/myusername/work/my-testing-folder/some-project-name/node_modules/deep-object-diff/mjs/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /Users/myusername/work/my-testing-folder/some-project-name/node_modules/deep-object-diff/mjs/package.json (relative path: ./diff)
      Field 'browser' doesn't contain a valid alias configuration
      /Users/myusername/work/my-testing-folder/some-project-name/node_modules/deep-object-diff/mjs/diff doesn't exist
ModuleNotFoundError: Module not found: Error: Can't resolve './added' in '/Users/myusername/work/my-testing-folder/some-project-name/node_modules/deep-object-diff/mjs'
Did you mean 'added.js'?
BREAKING CHANGE: The request './added' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/Compilation.js:2013:28
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:795:13
    at eval (eval at create (/Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:431:22
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:124:11
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:667:25
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:852:8
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:972:5
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/neo-async/async.js:6883:13
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:889:17
    at finishResolved (/Users/myusername/work/my-testing-folder/some-project-name/node_modules/enhanced-resolve/lib/Resolver.js:278:11)
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/enhanced-resolve/lib/Resolver.js:342:25
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/enhanced-resolve/lib/Resolver.js:409:24
    at eval (eval at create (/Users/myusername/work/my-testing-folder/some-project-name/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
resolve './added' in '/Users/myusername/work/my-testing-folder/some-project-name/node_modules/deep-object-diff/mjs'
  using description file: /Users/myusername/work/my-testing-folder/some-project-name/node_modules/deep-object-diff/mjs/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /Users/myusername/work/my-testing-folder/some-project-name/node_modules/deep-object-diff/mjs/package.json (relative path: ./added)
      Field 'browser' doesn't contain a valid alias configuration
      /Users/myusername/work/my-testing-folder/some-project-name/node_modules/deep-object-diff/mjs/added doesn't exist
ModuleNotFoundError: Module not found: Error: Can't resolve './deleted' in '/Users/myusername/work/my-testing-folder/some-project-name/node_modules/deep-object-diff/mjs'
Did you mean 'deleted.js'?
BREAKING CHANGE: The request './deleted' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/Compilation.js:2013:28
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:795:13
    at eval (eval at create (/Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:431:22
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:124:11
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:667:25
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:852:8
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:972:5
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/neo-async/async.js:6883:13
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:889:17
    at finishResolved (/Users/myusername/work/my-testing-folder/some-project-name/node_modules/enhanced-resolve/lib/Resolver.js:278:11)
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/enhanced-resolve/lib/Resolver.js:342:25
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/enhanced-resolve/lib/Resolver.js:409:24
    at eval (eval at create (/Users/myusername/work/my-testing-folder/some-project-name/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
resolve './deleted' in '/Users/myusername/work/my-testing-folder/some-project-name/node_modules/deep-object-diff/mjs'
  using description file: /Users/myusername/work/my-testing-folder/some-project-name/node_modules/deep-object-diff/mjs/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /Users/myusername/work/my-testing-folder/some-project-name/node_modules/deep-object-diff/mjs/package.json (relative path: ./deleted)
      Field 'browser' doesn't contain a valid alias configuration
      /Users/myusername/work/my-testing-folder/some-project-name/node_modules/deep-object-diff/mjs/deleted doesn't exist
ModuleNotFoundError: Module not found: Error: Can't resolve './updated' in '/Users/myusername/work/my-testing-folder/some-project-name/node_modules/deep-object-diff/mjs'
Did you mean 'updated.js'?
BREAKING CHANGE: The request './updated' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/Compilation.js:2013:28
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:795:13
    at eval (eval at create (/Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:431:22
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:124:11
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:667:25
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:852:8
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:972:5
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/neo-async/async.js:6883:13
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:889:17
    at finishResolved (/Users/myusername/work/my-testing-folder/some-project-name/node_modules/enhanced-resolve/lib/Resolver.js:278:11)
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/enhanced-resolve/lib/Resolver.js:342:25
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/enhanced-resolve/lib/Resolver.js:409:24
    at eval (eval at create (/Users/myusername/work/my-testing-folder/some-project-name/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
resolve './updated' in '/Users/myusername/work/my-testing-folder/some-project-name/node_modules/deep-object-diff/mjs'
  using description file: /Users/myusername/work/my-testing-folder/some-project-name/node_modules/deep-object-diff/mjs/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /Users/myusername/work/my-testing-folder/some-project-name/node_modules/deep-object-diff/mjs/package.json (relative path: ./updated)
      Field 'browser' doesn't contain a valid alias configuration
      /Users/myusername/work/my-testing-folder/some-project-name/node_modules/deep-object-diff/mjs/updated doesn't exist
ModuleNotFoundError: Module not found: Error: Can't resolve './detailed' in '/Users/myusername/work/my-testing-folder/some-project-name/node_modules/deep-object-diff/mjs'
Did you mean 'detailed.js'?
BREAKING CHANGE: The request './detailed' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/Compilation.js:2013:28
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:795:13
    at eval (eval at create (/Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:431:22
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:124:11
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:667:25
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:852:8
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:972:5
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/neo-async/async.js:6883:13
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/webpack/lib/NormalModuleFactory.js:889:17
    at finishResolved (/Users/myusername/work/my-testing-folder/some-project-name/node_modules/enhanced-resolve/lib/Resolver.js:278:11)
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/enhanced-resolve/lib/Resolver.js:342:25
    at /Users/myusername/work/my-testing-folder/some-project-name/node_modules/enhanced-resolve/lib/Resolver.js:409:24
    at eval (eval at create (/Users/myusername/work/my-testing-folder/some-project-name/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
resolve './detailed' in '/Users/myusername/work/my-testing-folder/some-project-name/node_modules/deep-object-diff/mjs'
  using description file: /Users/myusername/work/my-testing-folder/some-project-name/node_modules/deep-object-diff/mjs/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /Users/myusername/work/my-testing-folder/some-project-name/node_modules/deep-object-diff/mjs/package.json (relative path: ./detailed)
      Field 'browser' doesn't contain a valid alias configuration
      /Users/myusername/work/my-testing-folder/some-project-name/node_modules/deep-object-diff/mjs/detailed doesn't exist

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! some-project-name@0.1.0 storybook: `start-storybook -p 6006 -s public`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the some-project-name@0.1.0 storybook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**System**
Please paste the results of `npx sb@next info` here.

Environment Info:

```
  System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.18.2/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.2/bin/npm
  Browsers:
    Chrome: 97.0.4692.99
    Safari: 14.1.2
  npmPackages:
    @storybook/addon-actions: ^6.4.14 => 6.4.14 
    @storybook/addon-essentials: ^6.4.14 => 6.4.14 
    @storybook/addon-links: ^6.4.14 => 6.4.14 
    @storybook/builder-webpack5: ^6.4.14 => 6.4.14 
    @storybook/manager-webpack5: ^6.4.14 => 6.4.14 
    @storybook/node-logger: ^6.4.14 => 6.4.14 
    @storybook/preset-create-react-app: ^4.0.0 => 4.0.0 
    @storybook/react: ^6.4.14 => 6.4.14 
```

**Comment by planetzarg** [comment] 2022-01-25 18:04
This is also happening for me on Windows with a brand new project; tried updating to latest Node LTS. Get pretty much exactly the same error.

**Comment by koooge** [comment] 2022-01-25 18:21
I encountered the same issue on `build-storybook` command in non react project 10 minutes ago. But it seems it is solved now.

**Comment by mattphillips** [comment] 2022-01-25 23:28
Hi @Pablo-Codeiro-Peya @planetzarg @koooge 

Sorry, It would seems this issue was my fault I published a bad patch earlier for https://www.npmjs.com/package/deep-object-diff as part of adding ES Module support. I've since published a working patch and would expect this issue to be resolved.

I've just ran @Pablo-Codeiro-Peya's reproduction steps locally and it's all working for me now.

If you could try again and see if it is working that would be great. Do feel free to ping me if the issue persists 🙏

**Comment by planetzarg** [comment] 2022-01-26 04:46
Hi Matt, this is working for me now on Windows with a fresh project and Node on LTS 16.13.2. Thank you for resolving this so quickly and for all your hard work, much appreciated.

**Comment by shilman** [comment] 2023-06-08 03:43
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

**Closed by shilman** 2023-06-08 03:43 UTC
Labels: bug, needs triage
