### ISSUE TITLE
npx sb init does not work with CRA

### ISSUE THREAD

**Issue by alaboudi** [storybookjs/storybook#13593] opened 2021-01-09 20:06 UTC
**Describe the bug**
I get an error `ERR! Error: Cannot find module 'babel-loader` after installing storybook on a fresh CRA project. Although my issue occurred on a typescript project, the same issue occurs with a Javascript project

**To Reproduce**

1. `npx create-react-app my-app --template typescript`
2. `npx sb init`
3. `yarn storybook`

**Expected behavior**
it should work

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
Environment Info:
  System:
    OS: macOS 11.0.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v14.4.0/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.4.0/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 76.0
    Safari: 14.0.1
  npmPackages:
    @storybook/addon-actions: ^6.1.11 => 6.1.11 
    @storybook/addon-essentials: ^6.1.11 => 6.1.11 
    @storybook/addon-links: ^6.1.11 => 6.1.11 
    @storybook/node-logger: ^6.1.11 => 6.1.11 
    @storybook/preset-create-react-app: ^3.1.5 => 3.1.5 
    @storybook/react: ^6.1.11 => 6.1.11

**Comment by alaboudi** [comment] 2021-01-09 22:01
So I have a solution to this problem for all the people that are also experiencing this issue.

I visited the `package.json` in my `/node_modules/react_scripts` and took note of my `webpack`, `babel-loader` and `@babel/core` versions and installed those as dev dependencies. In addition, I removed the `@storybook/preset-create-react-app` from my project's `package.json`'s dev dependency list. I did a clean install by deleting `node_modules` and current `yarn.lock` file and running `yarn install` again. Solved my problem.

**Comment by jasonsturges** [comment] 2021-01-10 06:54
Using `npx sb init` with Create React App seems completely broken.

```bash
npx create-react-app my-app
cd my-app
npx sb init
```

Results in:

> Error: Cannot find module 'babel-loader'

Adding:

```bash
yarn add babel-loader
```

Results in:

> ERROR in ./.storybook/storybook-init-framework-entry.js
> Module not found: Error: You attempted to import .../my-app/node_modules/@pmmmwh/react-refresh-webpack-plugin/lib/runtime/RefreshUtils.js which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
> You can either move it inside src/, or add a symlink to it from project's node_modules/.

```bash
yarn remove @storybook/preset-create-react-app
```

If the CRA present is removed, Storybook will actually run with `yarn storybook`, but warns:

> info => Loading presets
> ERR! Addon value should end in /register OR it should be a valid preset https://storybook.js.org/docs/presets/introduction/
> ERR! @storybook/preset-create-react-app
> info => Loading 1 config file in "./.storybook"
> info => Loading 7 other files in "./.storybook"
> info => Adding stories defined in ".storybook/main.js"
> WARN Storybook support for Create React App is now a separate preset.
> WARN To use the new preset, install `@storybook/preset-create-react-app` and add it to the list of `addons` in your `.storybook/main.js` config file.
> WARN The built-in preset has been disabled in Storybook 6.0.

This was so simple and elegant in past projects, but is a complete nightmare to detangle now.

System:
OS: macOS Catalina 10.15.7
CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz

Binaries:
Node: v15.3.0
npm: 7.0.14
Yarn: 1.15..2

NPM Packages:
```json
"@storybook/addon-actions": "^6.1.11",
"@storybook/addon-essentials": "^6.1.11",
"@storybook/addon-links": "^6.1.11",
"@storybook/node-logger": "^6.1.11",
"@storybook/react": "^6.1.11"
"babel-loader": "^8.2.2",
"react": "^17.0.1",
"react-dom": "^17.0.1",
"react-scripts": "4.0.1",
```

**Comment by alaboudi** [comment] 2021-01-10 15:54
@jasonsturges You're right. It's unfortunate. This really needs to get fixed ASAP

**Comment by shilman** [comment] 2021-01-11 03:58
I've confirmed that recent changes in CRA have broken the Storybook install.

Will discuss with @mrmckeb when he comes online and hopefully we can get out a fix in the next day or so. Thanks for your patience!

**Comment by shilman** [comment] 2021-01-11 14:13
**UPDATE 4:** @sokra has graciously released `4.46.0` which resolves the second half of this issue. for now you still need to install `babel-loader` as a dev dependency, and I'm working with @mrmckeb to track down this side of things.

**Comment by shilman** [comment] 2021-01-11 18:58
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.12 containing PR #13607 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2021-01-11 18:58 UTC
Labels: P0, bug, cli, cra, has workaround

**Comment by shilman** [comment] 2021-01-11 18:59
**UPDATE 5:** I've released a fix on a pre-release. Please try it out and let me know with 👍 or 👎  if it solved things for you, and after I get a little feedback I'll patch it over to the `6.1.x` release. Thanks for your help and patience!

**Comment by jonniebigodes** [comment] 2021-01-11 21:09
@shilman i've setup a repo [here](https://github.com/jonniebigodes/storybook-react-for-issue-13593) and used a couple of components and stories from the LearnStorybook tutorial and so far so good. Testing was done with npm as opposed to yarn and both development and production versions are now working.

**Comment by shilman** [comment] 2021-01-11 22:42
@jonniebigodes i wouldn't expect the `latest` release to work on a fresh install of CRA. can you double check? since this appears to be a `yarn` bug, reusing the same project for different variations isn't enough -- pretty sure it needs to be a fresh install to really test it.

**Comment by jonniebigodes** [comment] 2021-01-11 23:00
Let me run it again with yarn and see how it fares.

**Comment by shilman** [comment] 2021-01-11 23:46
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.12 containing PR #13607 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

**Comment by jonniebigodes** [comment] 2021-01-12 00:09
For the repo mentioned above what was done was the following:
```shell
#bootstrap a new cra project
npx create-react-app storybook-react-for-issue-13593
cd storybook-react-for-issue-13593
# Adds the pre-release version with npm
npx sb@next init --use-npm
```
Copied over the fonts/styles from the tutorial and adjusted the files accordingly, turning `.storybook/main.js` into:
```js
module.exports ={
stories: ['../src/components/**/*.stories.js'],
// same as the boilerplate config generated during the installation process
}

```
```js
// .storybook/preview.js
import '../src/index.css';
// same as the boilerplate config generated during the installation process
```


Created couple of components and stories based of the tutorial:
```js
//src/components/Task.js

import React from 'react';
import PropTypes from 'prop-types';
export default function Task({ task: { id, title, state }, onArchiveTask, onPinTask }) {
  return (
    <div className={`list-item ${state}`}>
      <label className="checkbox">
        <input
          type="checkbox"
          defaultChecked={state === 'TASK_ARCHIVED'}
          disabled={true}
          name="checked"
        />
        <span className="checkbox-custom" onClick={() => onArchiveTask(id)} />
      </label>
      <div className="title">
        <input type="text" value={title} readOnly={true} placeholder="Input title" />
      </div>

      <div className="actions" onClick={event => event.stopPropagation()}>
        {state !== 'TASK_ARCHIVED' && (
          // eslint-disable-next-line jsx-a11y/anchor-is-valid
          <a onClick={() => onPinTask(id)}>
            <span className={`icon-star`} />
          </a>
        )}
      </div>
    </div>
  );
}
Task.propTypes = {
    /** Composition of the task */
    task: PropTypes.shape({
      /** Id of the task */
      id: PropTypes.string.isRequired,
      /** Title of the task */
      title: PropTypes.string.isRequired,
      /** Current state of the task */
      state: PropTypes.string.isRequired,
    }),
    /** Event to change the task to archived */
    onArchiveTask: PropTypes.func,
    /** Event to change the task to pinned */
    onPinTask: PropTypes.func,
  };
```
And associated story file:
```js
// src/components/Task.stories.js

import React from 'react';

import Task from './Task';

export default {
  component: Task,
  title: 'Task',
};

const Template = args => <Task {...args} />;

export const Default = Template.bind({});
Default.args = {
  task: {
    id: '1',
    title: 'Test Task',
    state: 'TASK_INBOX',
    updatedAt: new Date(2018, 0, 1, 9, 0),
  },
};

export const Pinned = Template.bind({});
Pinned.args = {
  task: {
    ...Default.args.task,
    state: 'TASK_PINNED',
  },
};

export const Archived = Template.bind({});
Archived.args = {
  task: {
    ...Default.args.task,
    state: 'TASK_ARCHIVED',
  },
};
```
And included the `src/components/TaskList.js` and `src/components/TaskList.stories.js` as documented in the tutorial.

Running `npm run storybook` shows me the following:

![storybook-issue-with-npm_2](https://user-images.githubusercontent.com/22988955/104251927-bd0cd980-5468-11eb-812f-fea16810f866.png)
![storybook-issue-with-npm_1](https://user-images.githubusercontent.com/22988955/104251933-bf6f3380-5468-11eb-9764-5ce99c13312f.png)

Added `http-server` and ran `npm run build-storybook && npx http-server storybook-static` no issues whatsoever, production build was generated and served.

As per your comment i've switched to yarn and ran the following:
```shell
yarn create react-app cra-test cra-test-issue13593
cd cra-test-issue13593
npx sb@next init
```
Did the same as above with styling, fonts and the components/stories. Issued `yarn storybook` and i'm presented with the following:
![yarn-issue-cra](https://user-images.githubusercontent.com/22988955/104252534-2f31ee00-546a-11eb-89b9-a55fc4deeaf1.png)

Just leaving out browser window for brevity. Ran the same for generating a production build as mentioned above and once again no issues.

**Comment by amcsi** [comment] 2021-01-12 17:06
I'm having the same issue as in #13585, but with CRA v3 and Storybook v5. I'm sad to see that the fix made apparently only applies to Storybook v6.

**Comment by emmadal** [comment] 2022-02-17 00:35
Please follow this step:
```sh
npm i @storybook/react
npx sb init 
```
