### ISSUE TITLE
In angular 13 projects "can't resolve @workspace/my-lib" when using path in tsconfig

### ISSUE THREAD

**Issue by literalpie** [storybookjs/storybook#16759] opened 2021-11-22 19:51 UTC
**Describe the bug**
When a path is set in "compilerOptions.paths", the path does not work as expected when building a storybook with Angular 13. When storybook is run, the following error is logged:
> ModuleNotFoundError: Module not found: Error: Can't resolve '@literalpie/test-lib' in '/Users/path/to/code'

In my testing, this error happens when updating to Angular 13 in projects where Angular 11/12 was working fine. 
**To Reproduce**
I have two reproductions. [here is a branch](https://github.com/literalpie/sb-ng-performance/tree/tsconfig-path) where I set the configuration myself. Trying to run storybook causes the error mentioned above.

Because I didn't trust my own configuration, I also tried with a simple NX project that includes a library and an app with storybook. It has the same error. [here is that project](https://github.com/literalpie/storybook-ng13-tsconfig-paths)

In both places, you can revert to a previous commit to see everything working with a lower Angular version.

**System**
  System:
    OS: macOS 11.6.1
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
  Binaries:
    Node: 16.11.1 - ~/.nvm/versions/node/v16.11.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.24.2 - ~/.nvm/versions/node/v16.11.1/bin/npm
  Browsers:
    Chrome: 96.0.4664.45
    Firefox: 94.0.1
    Safari: 15.1
  npmPackages:
    @storybook/addon-essentials: 6.4.0-rc.3 => 6.4.0-rc.3 
    @storybook/angular: 6.4.0-rc.3 => 6.4.0-rc.3 
    @storybook/builder-webpack5: 6.4.0-rc.3 => 6.4.0-rc.3 
    @storybook/manager-webpack5: 6.4.0-rc.3 => 6.4.0-rc.3 

**Additional context**
I think this will be an issue for a lot of people using Angular in a monorepo. This is an issue in the default configuration of storybook and Angular (besides the path setting in tsconfig).

**Comment by criskrzysiu** [comment] 2021-11-24 06:42
I can confirm, we have same exact problem on nx monorepo as well, also using paths

**Comment by shilman** [comment] 2021-11-24 17:32
@literalpie any idea what the problem might be?

**Comment by literalpie** [comment] 2021-11-24 17:53
@shilman sorry, no I haven't been able to dig into it and I don't have any hunches.

**Comment by yannbf** [comment] 2021-11-24 19:14
Hey @literalpie I just wanted to say thank you for being so swift with reporting these issues and providing repros. We greatly appreciate all the help you've been giving 🙏

**Comment by criskrzysiu** [comment] 2021-11-27 16:22
Ok, I managed to get my project working by adding manually aliases to my libs.

So in ```tsconfig.base.json``` I have 
```
paths: [
'@my-domain/utils: ['libs/utils/src/index.ts']
]
```

and in ```main.js``` I add

```
 webpackFinal: async (config, { configType }) => {
    // apply any global webpack configs that might have been specified in .storybook/main.js
    if (rootMain.webpackFinal) {
      config = await rootMain.webpackFinal(config, { configType });
    }

    console.log('Now: ', config);

    config.resolve.alias = {
                           ...config.resolve.alias,
                           '@my-domain/utils' :  path.join(__dirname, '../../', '/utils/src/index.ts')
                            };

    console.log('Now2: ', config.resolve.alias);


    return config;
  },
```

my initial webpack config from ```console.log('Now: ', config);```

```
 {
  name: 'preview',
  mode: 'development',
  bail: false,
  devtool: 'cheap-module-source-map',
  entry: [
    'C:\\repos\\my-project\\Frontend\\node_modules\\@storybook\\core-client\\dist\\esm\\globals\\polyfills.js',
    'C:\\repos\\my-project\\Frontend\\node_modules\\@storybook\\core-client\\dist\\esm\\globals\\globals.js',
    'C:\\repos\\my-project\\Frontend\\node_modules\\webpack-hot-middleware\\client.js?reload=true&quiet=false&noInfo=true',
    'C:\\repos\\my-project\\Frontend\\storybook-init-framework-entry.js',
    'C:\\repos\\my-project\\Frontend\\node_modules\\@storybook\\angular\\dist\\ts3.9\\client\\preview\\config.js-generated-config-entry.js',
    'C:\\repos\\my-project\\Frontend\\libs\\ui\\.storybook\\preview.js-generated-config-entry.js',
    'C:\\repos\\my-project\\Frontend\\generated-stories-entry.js',
    'C:\\repos\\my-project\\Frontend\\node_modules\\normalize.css\\normalize.css',
    'C:\\repos\\my-project\\Frontend\\libs\\ui\\styles\\styles.scss',
    'C:\\repos\\my-project\\Frontend\\apps\\myapp\\src\\styles.scss',
    'C:\\repos\\my-project\\Frontend\\apps\\myapp\\src\\polyfills.ts',
    'core-js/proposals/reflect-metadata'
  ],
  output: {
    path: 'C:\\repos\\my-project\\Frontend\\node_modules\\.cache\\storybook\\public',
    filename: '[name].iframe.bundle.js',
    publicPath: ''
  },
  stats: { preset: 'none', logging: 'error' },
  watchOptions: { ignored: /node_modules/ },
  ignoreWarnings: [ { message: /export '\S+' was not found in 'global'/ } ],
  plugins: [
    DedupeModuleResolvePlugin { options: [Object], modules: Map(0) {} },
    CopyPlugin { patterns: [Array], options: {} },
    LicenseWebpackPlugin { pluginOptions: [Object] },
    AnyComponentStyleBudgetChecker { budgets: [] },
    { apply: [Function: apply] },
    MiniCssExtractPlugin {
      _sortedModulesCache: [WeakMap],
      options: [Object],
      runtimeOptions: [Object]
    },
    SuppressExtractedTextChunksWebpackPlugin {},
    VirtualModulesPlugin {
      _compiler: null,
      _watcher: null,
      _staticModules: [Object]
    },
    HtmlWebpackPlugin { userOptions: [Object], version: 5 },
    DefinePlugin { definitions: [Object] },
    ProvidePlugin { definitions: [Object] },
    WatchMissingNodeModulesPlugin {
      nodeModulesPath: 'C:\\repos\\my-project\\Frontend\\node_modules'
    },
    HotModuleReplacementPlugin { options: {} },
    CaseSensitivePathsPlugin {
      options: {},
      logger: [Object [console]],
      pathCache: Map(0) {},
      fsOperations: 0,
      primed: false
    },
    ContextReplacementPlugin {
      resourceRegExp: /@angular(\\|\/)core(\\|\/)(fesm5|bundles)/,
      newContentResource: 'C:\\repos\\my-project\\Frontend\\node_modules\\@storybook\\angular\\dist\\ts3.9',
      newContentRecursive: undefined,
      newContentRegExp: undefined
    },
    ForkTsCheckerWebpackPlugin {
      eslint: false,
      eslintOptions: {},
      tsconfigPath: undefined,
      compiler: undefined,
      started: undefined,
      elapsed: undefined,
      cancellationToken: undefined,
      isWatching: false,
      checkDone: false,
      compilationDone: false,
      diagnostics: [],
      lints: [],
      eslintVersion: undefined,
      startAt: 0,
      nodeArgs: [],
      options: [Object],
      ignoreDiagnostics: [],
      ignoreLints: [],
      ignoreLintWarnings: false,
      reportFiles: [],
      logger: [Object [console]],
      silent: false,
      async: false,
      checkSyntacticErrors: false,
      resolveModuleNameModule: undefined,
      resolveTypeReferenceDirectiveModule: undefined,
      memoryLimit: 2048,
      formatter: [Function: defaultFormatter],
      rawFormatter: [Function: rawFormatter],
      emitCallback: [Function: noopEmitCallback],
      doneCallback: [Function: doneCallback],
      typescript: [Object],
      typescriptPath: 'C:\\repos\\my-project\\Frontend\\node_modules\\typescript\\lib\\typescript.js',
      typescriptVersion: '4.4.4',
      tsconfig: 'C:\\repos\\my-project\\Frontend\\libs\\ui\\.storybook\\tsconfig.json',
      compilerOptions: {},
      vue: [Object],
      useTypescriptIncrementalApi: true,
      measureTime: false
    }
  ],
  module: {
    rules: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ]
  },
  resolve: {
    extensions: [
      '.mjs', '.js',
      '.jsx', '.ts',
      '.tsx', '.json',
      '.cjs'
    ],
    modules: [ 'node_modules', 'C:/repos/my-project/Frontend' ],
    mainFields: [
      'es2015_ivy_ngcc',
      'module_ivy_ngcc',
      'main_ivy_ngcc',
      'es2015',
      'browser',
      'module',
      'main'
    ],
    alias: {
      '@emotion/core': 'C:\\repos\\my-project\\Frontend\\node_modules\\@emotion\\core',
      '@emotion/styled': 'C:\\repos\\my-project\\Frontend\\node_modules\\@emotion\\styled',
      'emotion-theming': 'C:\\repos\\my-project\\Frontend\\node_modules\\emotion-theming',
      '@storybook/addons': 'C:\\repos\\my-project\\Frontend\\node_modules\\@storybook\\builder-webpack5\\node_modules\\@storybook\\addons',
      '@storybook/api': 'C:\\repos\\my-project\\Frontend\\node_modules\\@storybook\\builder-webpack5\\node_modules\\@storybook\\api',
      '@storybook/channels': 'C:\\repos\\my-project\\Frontend\\node_modules\\@storybook\\builder-webpack5\\node_modules\\@storybook\\channels',
      '@storybook/channel-postmessage': 'C:\\repos\\my-project\\Frontend\\node_modules\\@storybook\\channel-postmessage',
      '@storybook/components': 'C:\\repos\\my-project\\Frontend\\node_modules\\@storybook\\builder-webpack5\\node_modules\\@storybook\\components',
      '@storybook/core-events': 'C:\\repos\\my-project\\Frontend\\node_modules\\@storybook\\builder-webpack5\\node_modules\\@storybook\\core-events',
      '@storybook/router': 'C:\\repos\\my-project\\Frontend\\node_modules\\@storybook\\builder-webpack5\\node_modules\\@storybook\\router',
      '@storybook/theming': 'C:\\repos\\my-project\\Frontend\\node_modules\\@storybook\\builder-webpack5\\node_modules\\@storybook\\theming',
      '@storybook/semver': 'C:\\repos\\my-project\\Frontend\\node_modules\\@storybook\\builder-webpack5\\node_modules\\@storybook\\semver',
      '@storybook/client-api': 'C:\\repos\\my-project\\Frontend\\node_modules\\@storybook\\client-api',
      '@storybook/client-logger': 'C:\\repos\\my-project\\Frontend\\node_modules\\@storybook\\builder-webpack5\\node_modules\\@storybook\\client-logger',
      react: 'C:\\repos\\my-project\\Frontend\\node_modules\\react',
      'react-dom': 'C:\\repos\\my-project\\Frontend\\node_modules\\react-dom'
    },
    fallback: { path: false, crypto: false, assert: false }
  },
  optimization: {
    splitChunks: { chunks: 'all' },
    runtimeChunk: true,
    sideEffects: true,
    usedExports: true,
    moduleIds: 'named',
    minimizer: []
  },
  performance: { hints: false },
  resolveLoader: { symlinks: true }
}
```

as You see its lacking ``` '@my-domain/utils': 'C:\\repos\\my-project\\Frontend\\libs\\utils\\src\\index.ts'``` entry in ```alias``` 


hope it will help at least a few of You as a workaround for now

**Comment by kroeder** [comment] 2021-11-29 11:04
Can confirm the workaround works quite well! But I wonder why this happens now 🤔 Is reading all the tsconfig paths and writing them to `config.resolve.alias` within `@storybook/angular` a fix or a workaround is the question

**Comment by juristr** [comment] 2021-11-29 11:06
No I don't think so. There has been a change in the latest storybook release (6.4) related to how the webpack config is read for Angular projects. It looks like the tsconfig inheritance is not taken into account properly any more (like it did before).

Needs some digging..

**Comment by leon** [comment] 2021-11-29 14:28
In an NX workspace you can add this to add all the paths.

```ts
// .storybook/main.js in lib
webpackFinal: async (config, { configType }) => {
    // apply any global webpack configs that might have been specified in .storybook/main.js
    if (rootMain.webpackFinal) {
      config = await rootMain.webpackFinal(config, { configType })
    }

    const tsConfig = require('../../tsconfig.base.json') // find the root config file, you might have to change how many ../
    const pathConfigs = tsConfig.compilerOptions.paths
    for (const key of Object.keys(pathConfigs)) {
      config.resolve.alias[key] = pathConfigs[key][0]
    }

    // add your own webpack tweaks if needed
    return config
  },

```

**Comment by literalpie** [comment] 2021-11-29 15:19
I did a little digging. I found some interesting things, but I wasn't able to fix it.
It seems like the only difference between the angular 12.x and angular 13.x webpack files is the use of [`getTypescriptWorkerPlugin`](https://github.com/storybookjs/storybook/blob/next/app/angular/src/server/angular-cli-webpack-13.x.x.js#L43) rather than `getTypescriptConfig`. Notice that storybook only passes one parameter into the function, but [looking at the angular code](https://github.com/angular/angular-cli/blob/13.0.x/packages/angular_devkit/build_angular/src/webpack/configs/typescript.ts#L115) it expects a tsconfig path as the second parameter. (this is a little strange since the path should be included in the WCO, but okay 🤷🏼 ).

I was sure adding the path would fix the issue, but I don't see any difference :-( . I don't think I'll be able to look more, but maybe this will help someone on the right path.

**Comment by Marklb** [comment] 2021-12-02 08:36
I can submit a PR tomorrow, if no one else gets to it before I get a chance tomorrow and if this actually is the problem.

I thought the Webpack config returned by the functions called in Angular added the tsconfig paths, but it seems Storybook's Angular <12.2 Webpack config adds the TsconfigPathsPlugin. The new config for >= 12.2 does not add it. I added it then used an Angular13 project with paths defined in the `tsconfig.json` and they resolved, but I didn't get a chance to thoroughly test the change with various differently configured Angular projects, yet.

Angular <12.2: https://github.com/storybookjs/storybook/blob/next/app/angular/src/server/angular-cli-webpack-older.ts#L130
Angular 12.2: https://github.com/storybookjs/storybook/blob/next/app/angular/src/server/angular-cli-webpack-12.2.x.js#L65
Angular 13: https://github.com/storybookjs/storybook/blob/next/app/angular/src/server/angular-cli-webpack-13.x.x.js#L65

**Comment by shilman** [comment] 2021-12-03 08:20
Hurrah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.5 containing PR #16882 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2021-12-03 08:20 UTC
Labels: bug, has workaround, app: angular, nx, needs triage, linear

**Comment by shilman** [comment] 2021-12-09 02:48
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.2 containing PR #16882 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```
