### ISSUE TITLE
Storybook failed to run when update @storybook/react and addons from 6.4.22 to 6.5.0

### ISSUE THREAD

**Issue by vozni4iy** [storybookjs/storybook#18265] opened 2022-05-19 12:14 UTC
**Describe the bug**
"@storybook/addon-actions": "6.4.22",
    "@storybook/addon-docs": "6.4.22",
    "@storybook/addon-essentials": "6.4.22",
    "@storybook/addon-links": "6.4.22",
    "@storybook/builder-webpack5": "6.4.22",
    "@storybook/manager-webpack5": "6.4.22",
    "@storybook/react": "6.4.22",

seems to be valid configuration.
If any of those dependencies are updated to 6.5.0 it leads to an error

Error: NormalModuleFactory.beforeResolve (IgnorePlugin) is no longer a waterfall hook, but a bailing hook instead. Do not return the passed object, but modify it instead. Returning false will ignore the request and results in no module created.

**System**
System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Edge: 101.0.1210.47
    Firefox: 100.0.1
    Safari: 14.1.1

**Additional context**

**Comment by shilman** [comment] 2022-05-19 17:07
@vozni4iy Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

Note: if you upgrade any one of those packages to 6.5.0, you should upgrade all of them to 6.5.0

**Comment by shilman** [comment] 2022-05-20 02:46
thanks @suhomozgy-andrey !!

closing this as dupe to #18276

**Closed by shilman** 2022-05-20 02:46 UTC
Labels: bug, needs reproduction, webpack5
