### ISSUE TITLE
[Bug]: TS2786 error when updating Storybook to v7.4.0.

### ISSUE THREAD

**Issue by Karibash** [storybookjs/storybook#24011] opened 2023-08-30 10:55 UTC
### Describe the bug

Updating Storybook to v7.4.0 causes TS2786 error.
This is due to a type mismatch caused by multiple versions of @types/react being installed.
It should be possible to solve this problem by revert the following commit.

https://github.com/storybookjs/storybook/commit/8ceec7d72828b16db4bf3a77dc9aace1a4bcf648

**Comment by wand2016** [comment] 2023-08-31 02:29
I think this kind of deps should be in peerDependencies.

**Comment by sebil** [comment] 2023-09-01 12:11
Make sure you also add `"@storybook/types": "^7.4.0",` to your package.json to dedupe all addons types packages.
Fixed it for me.

I think this is caused by `@storybook/addon-styling`, it's the only package on my project that still uses `@storybook/types@7.1.1`
Just use `npm ls --depth=1 @storybook/types` to see which package might not using the new 7.4.0 types on your project.

I recommend to always use `npx storybook@latest upgrade` to update your storybook versions, it's really comfortable and shows hints for possible issues.

**Comment by JReinhold** [comment] 2023-09-01 21:48
We've released [v7.5.0-alpha.0](https://github.com/storybookjs/storybook/releases/tag/v7.5.0-alpha.0) that _might_ contain a fix for this (https://github.com/storybookjs/storybook/pull/24042). Could you try it out and tell us if it fixes the issue? If it does, we'll release it in a patch.

`npx storybook@next upgrade --prerelease`

**Comment by Methuselah96** [comment] 2023-09-04 02:55
The alpha fixed the issue for me, looking forward to it being released in a 7.4 patch!

**Closed** 2023-11-18 23:28 UTC
Labels: bug, sev:S2, upgrade:7.4
