### ISSUE TITLE
Storybook 6.3.12 build-storybook fails ERR! EEXIST: file already exists, mkdir '/storybook-static/favicon.ico'

### ISSUE THREAD

**Issue by dickerstu** [storybookjs/storybook#16732] opened 2021-11-19 19:55 UTC
**Describe the bug**

**To Reproduce**
Running Angular 10 and Storybook 6.3.12 with Webpack4 build. 
Whenever I try and run build-storybook, the build fails (updated my personal directories with "..."):

> build-storybook

info @storybook/angular v6.3.12
info 
info => Cleaning outputDir: /.../storybook-static
info => Loading presets
ERR! Addon value should end in /register OR it should be a valid preset https://storybook.js.org/docs/react/addons/writing-presets/
ERR! @storybook/addon-actions
info => Compiling manager..
info => Compiling preview..
info => Loading 1 config file in "/.../.storybook"
info => Loading 3 other files in "/.../.storybook"
WARN Expected '@storybook/addon-docs' to be listed before '@storybook/addon-controls' (or '@storybook/addon-essentials'). Check your main.js?
WARN If addon-docs or addon-essentials is included by another addon/preset you can safely ignore this warning.
WARN 
WARN https://github.com/storybookjs/storybook/issues/11442
info => Adding stories defined in "/.../.storybook/main.js"
info => Found custom tsconfig.json
Warning: Entry point '@auth0/angular-jwt' contains deep imports into '/.../node_modules/rxjs/internal/Observable'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
Warning: Entry point '@w11k/angular-sticky-things' contains deep imports into '/.../node_modules/rxjs/internal/scheduler/animationFrame'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
Warning: Entry point 'angular2-text-mask' contains deep imports into '/.../node_modules/text-mask-core/dist/textMaskCore'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
info => Using implicit CSS loaders
info => Loading angular-cli config
info => Using angular project "LicensingManager:build" for configuring Storybook
info => Using angular-cli webpack config
info => Using default Webpack4 setup
Starting type checking service...
10% building 1/1 modules 0 active(node:15793) DeprecationWarning: Default PostCSS plugins are deprecated. When switching to '@storybook/addon-postcss',
you will need to add your own plugins, such as 'postcss-flexbugs-fixes' and 'autoprefixer'.

See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-default-postcss-plugins for details.
(Use `node --trace-deprecation ...` to show where the warning was created)
92% chunk asset optimization TerserPlugininfo => Manager built (18 s)
95% emitting fork-ts-checker-webpack-pluginERR! => Failed to build the preview
ERR! EEXIST: file already exists, mkdir '/.../storybook-static/favicon.ico'
ERR! Error: EEXIST: file already exists, mkdir '/.../storybook-static/favicon.ico'
ERR!  [Error: EEXIST: file already exists, mkdir '/.../storybook-static/favicon.ico'] {
ERR!   errno: -17,
ERR!   code: 'EEXIST',
ERR!   syscall: 'mkdir',
ERR!   path: '/.../storybook-static/favicon.ico'
ERR! }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! licensing-manager@0.0.0 build-storybook: `build-storybook`
npm ERR! Exit status 1

**System**
    "@angular/cli": "^10.2.3",
    "@angular/compiler-cli": "^10.2.5",
    "@angular/language-service": "^10.2.5",
    "@storybook/addon-backgrounds": "^6.3.12",
    "@storybook/addon-controls": "^6.3.12",
    "@storybook/addon-info": "^5.3.21",
    "@storybook/addon-knobs": "^6.3.1",
    "@storybook/addon-viewport": "^6.3.12",
    "@storybook/angular": "^6.3.12",

**Additional context**
I did try setting core builder to Webpack5 but that caused other issues.

**Comment by dickerstu** [comment] 2021-11-19 21:29
I discovered the issue. In the angular.json build section I have:
            "assets": [
              "src/favicon.ico",
 
The static folder gets created when I initially start build-storybook. It creates a folder named favicon.ico to include this asset. Then later when build-story writes it's content to the static folder it fails when it tries to copy the Storybook favicon.ico. That results in the error.
 
IMO, this is a bug and should cause a failure.

**Comment by shilman** [comment] 2021-11-20 03:00
@dickerstu so what would the desired behavior be exactly?

**Comment by Marklb** [comment] 2021-11-20 12:24
@dickerstu Does the path you omitted happen to have a `)` character anywhere in it?

I created a new project in my junk `tmp` folder, to tryout a PR, and got an error on saying that the `C:\Users\Mark\dev_home\tmp\New folder (12)\New folder (6)\example-current\node_modules\@storybook\core-server\dist\cjs\public\favicon.ico` file didn't exist. At the time I just ignored it, because I was just in a throw away project and not really testing `build-storybook` anyway. This issue made me go back and take a look at the error I got.

If you don't think the following is related to this issue then can you provide some more information, such as maybe your OS, full path to project, and maybe a repro.

Using Angular `10.2.4` and `12.2.0` and various Storybook versions from `6.3.12` to `6.4.0-rc.5`, I got the following error. It is about a `favicon.ico`, but the error isn't the same, so I don't know if it is a coincidence that both errors deal with a `favicon.ico` or if they are related.
```sh
info => Cleaning outputDir: C:\Users\Mark\dev_home\tmp\New folder (12)\New folder (6)\example-current\storybook-static
ERR! NestedError: Cannot copy `C:\Users\Mark\dev_home\tmp\New folder (12)\New folder (6)\example-current\node_modules\@storybook\core-server\dist\cjs\public\favicon.ico`: the file doesn't exist
ERR!     at C:\Users\Mark\dev_home\tmp\New folder (12)\New folder (6)\example-current\node_modules\cpy\index.js:96:10
ERR!     at processTicksAndRejections (internal/process/task_queues.js:95:5)
ERR!     at async buildStaticStandalone (C:\Users\Mark\dev_home\tmp\New folder (12)\New folder (6)\example-current\node_modules\@storybook\core-server\dist\cjs\build-static.js:94:3)
ERR!     at async Object.buildStatic (C:\Users\Mark\dev_home\tmp\New folder (12)\New folder (6)\example-current\node_modules\@storybook\core-server\dist\cjs\build-static.js:195:5)
ERR!  NestedError: Cannot copy `C:\Users\Mark\dev_home\tmp\New folder (12)\New folder (6)\example-current\node_modules\@storybook\core-server\dist\cjs\public\favicon.ico`: the file doesn't exist
ERR!     at C:\Users\Mark\dev_home\tmp\New folder (12)\New folder (6)\example-current\node_modules\cpy\index.js:96:10
ERR!     at processTicksAndRejections (internal/process/task_queues.js:95:5)
ERR!     at async Object.buildStatic (C:\Users\Mark\dev_home\tmp\New folder (12)\New folder (6)\example-current\node_modules\@storybook\core-server\dist\cjs\build-static.js:195:5) {
ERR!   nested: undefined,
ERR!   name: 'CpyError'
ERR! }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! example-current@0.0.0 build-storybook: `npm run docs:json && build-storybook`
npm ERR! Exit status 1
```

I think I narrowed my problem down to `cpy` not recognizing files if there is a `)` anywhere in the source path. The following stackblitz shows my current progress tracking down the problem. Tomorrow I may dig deeper and see if the problem is with `cpy` or one of it's dependencies.
https://stackblitz.com/edit/node-raizyx?file=package.json

**Comment by dickerstu** [comment] 2021-11-22 13:34
@Marklb The path didn't have a ) in the source path.

**Comment by dickerstu** [comment] 2021-11-22 13:40
@shilman The favicon.ico file is a non-essential file. If Storybook's favicon.ico file required by Storybook for the static build, then I would expect 1) Storybook to overwrite any file or folder named the same and put a warning in the log or 2) ignore and continue. Since this issue isn't breaking the build to run storybook then it shouldn't break the static build.

**Comment by Marklb** [comment] 2021-11-22 16:30
@dickerstu Do you have a repo that reproduces the problem that you can share? In my projects, there is no problem with the static build, other than my different previously commented problem, and I also still have "src/favicon.ico" in my assets.

**Comment by dickerstu** [comment] 2021-11-22 18:51
@Marklb Sorry, this is my company's app so I won't be able to share it. When you start the build do you not see it immediately being copied into storybook-static?

**Comment by Marklb** [comment] 2021-11-22 23:10
@dickerstu Yes, the Storybook `favicon.ico` gets copied to the folder and it gets replaced by the one defined in my `angular.json` "assets" when it's done building.

> It creates a folder named favicon.ico to include this asset. 
I just noticed that you said it creates a folder named "favicon.ico". Do you mean that it creates the "favicon.ico" file in the created "storybook-static" folder?

> Then later when build-story writes it's content to the static folder it fails when it tries to copy the Storybook favicon.ico. That results in the error.
Are you sure it fails when copying the Storybook "favicon.ico" or your Angular app's "favicon.ico"?

Are you passing any arguments to "build-storybook"?

Do you have a custom webpack config or customize in the config with `webpackFinal` in `.storybook/main.(js|ts)`?

Do you use Nx or just Angular's cli?

Can you provide the OS and maybe if you have anything open at the time of building that may have any interaction with that folder? This may not matter, but on Windows if I have a project open in VSCode when a script tries to delete a file then I sometimes get an error that the file can't be deleted. Your error is different, but just trying to narrow it down in some way, until the problem can be reproduced.

**Comment by dickerstu** [comment] 2021-11-23 13:01
If fails when copying the Storybook "favicon.ico". 
The build actually created a folder named favicon.ico and placed a copy of the Angular asset favicon.ico within it.
I am not passing any arguments.
No changes to the webpack.config.
I am using Angular's CI.
This is running on Ubuntu-20-04.

**Comment by Marklb** [comment] 2021-11-23 19:07
@dickerstu I assumed the "src/favicon.ico" in your "assets" was a file, like it is by default in a newly generated Angular CLI project, but is it a folder in your project? When I replaced "src/favicon.ico" file with a folder then I got your error, because Angular ran into a conflict trying to overwrite Storybook's "favicon.ico" file with the "favicon.ico" folder defined in the `angular.json` "assets".

If this is your problem, then I guess this is potentially a Storybook bug, not an Angular bug. I am not sure how best to solve that. I am not sure what the correct solution would be. Normally I assume "favicon.ico" should be a file in the root, but it doesn't have to be, so maybe Storybook should account for that. Someone more familiar with the build process may can answer better, but I am not sure if there is currently a framework independent way to add the favicon after the framework build finishes and write it to an alternate location/name or if that is even a good idea.

**Comment by dickerstu** [comment] 2021-11-23 19:10
@Marklb favicon.ico is a non-essential file. If the cpy fails then just ignore and write a warning. Failure to copy it shouldn't break the build (again, IMO).

**Comment by Marklb** [comment] 2021-11-23 19:39
@dickerstu I think it is Angular's code throwing the error, not Storybook. From my understanding, Storybook makes the output folder and copies the "favicon.ico" file into that folder then passes the building off to the framework specific builder. From Angular's builder's perspective I would expect an error, because you defined an asset folder that can't be created if there is a file with the same name. Storybook may be able to make the favicon copy after the framework build is completed, but I am not sure if that would be simple with how it currently works.

In my opinion, it would be nice if there error was more obvious, but I don't know about it being a warning. If my expected favicon didn't get copied into the build then I would not want that build to get published, because user's browser may cache the wrong favicon if they access the site at that time. *Of course there are ways to fix the caching problem, but it is up to the browser to respect those cache busting rules.* Maybe making Storybook's default favicon path configurable would be a solution.

@shilman Do you know who would be best to ask about changes to the core-server static build?

**Comment by shilman** [comment] 2021-11-24 00:07
Perhaps @ndelangen has some ideas? ☝️

**Comment by ndelangen** [comment] 2021-11-24 11:17
Storybook copies the folders into the output dir here:
https://github.com/storybookjs/storybook/blob/43f9f14114e0033affbdf6126e2711cffe7223d3/lib/core-server/src/build-static.ts#L87-L89

Before we have a special case for the favicon here:
https://github.com/storybookjs/storybook/blob/43f9f14114e0033affbdf6126e2711cffe7223d3/lib/core-server/src/build-static.ts#L59

Would it help to move that favicon line to a later stage?
And check if the file already exists?

@Marklb @dickerstu

**Comment by dickerstu** [comment] 2021-11-24 15:59
@ndelangen @Marklb That sounds like a good approach if it keeps the build from failing. If found log a warning.

**Comment by Marklb** [comment] 2021-11-24 21:00
@ndelangen I think moving the favicon line to a later stage and checking if it already exists should work.

By moving it after the framework builder has copied it's assets, there probably doesn't need to be a warning if it already exists. I think it is expected for the project's assets to contain their favicon and use Storybook's if one isn't provided. If there was a config for where Storybook's favicon gets copied, then a warning would be expected, but I don't think there is. So, it would essentially become a fallback for projects that don't provide their own.

**Comment by ndelangen** [comment] 2021-11-29 12:28
@dickerstu or @Marklb would either of you be able to create a PR to change this?

**Comment by admir86** [comment] 2021-12-20 16:23
same or similar problem

```
info => Cleaning outputDir: /_work/2/s/dist/storybook
info => Loading presets
info Found existing addon "@storybook/addon-docs", skipping.
info => Copying static files: /_work/2/s/libs/common/src at /_work/2/s/dist/storybook/
info => Copying static files: /_work/2/s/libs/desktop/src at /_work/2/s/dist/storybook/
info => Copying static files: /_work/2/s/libs/basiskomponenten/src at /_work/2/s/dist/storybook/
info => Loading custom manager config
info => Compiling manager..
info => Compiling preview..
info => Found custom tsconfig.json
info => Using implicit CSS loaders
info => Loading angular-cli config for angular >= 13.0.0
info => Using angular project with "tsConfig:/_work/2/s/.storybook/tsconfig.json"
info => Using angular project "user-app:build" for configuring Storybook
info => Loading custom manager config
(node:31178) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/_work/2/s/dist/storybook/translations'
```

I think the problem is that each of my static files sources contains the folder `translations`. After copying the first source, the second fails because the directory already exists.
I think there should be a check and if directory already exists it should be used as target and not tried to recreate it

**Comment by ndelangen** [comment] 2022-01-05 13:11
@admir86 I agree, I'd welcome a PR very much!

**Comment by admir86** [comment] 2022-01-10 10:16
I have just checked the [copy-all-static-files](https://github.com/storybookjs/storybook/blob/b1d9b8b71ea6b1c12e636a971cadf3bb6099a3d0/lib/core-server/src/utils/copy-all-static-files.ts) part. 
This [copy](https://github.com/storybookjs/storybook/blob/b1d9b8b71ea6b1c12e636a971cadf3bb6099a3d0/lib/core-server/src/utils/copy-all-static-files.ts#L19) function should overwrite existing items. The [overwrite](https://github.com/jprichardson/node-fs-extra/blob/master/docs/copy.md) option is not set and default is true (at least if we can trust the docs).

any idea where else the error might be coming from?

**Comment by iMarv** [comment] 2022-03-01 09:58
Got the same issue running node v16
downgrading to v14 "does the trick" but is not what I desire

**Comment by adrivelasco** [comment] 2022-04-22 13:33
same issue here, any solution? 🙏

**Comment by iMarv** [comment] 2022-04-23 10:12
Found a workaround for my issue, don't know what changed with node 16, but we were copying a static asset folder during the build (with the option in the storybook config), which was also (apparently) included in the angular buildstep. Removing it from storybook config fixed the issue for me, the problem might actually be coming from angular rather than storybook.

**Comment by kroeder** [comment] 2022-08-30 18:23
> I have just checked the [copy-all-static-files](https://github.com/storybookjs/storybook/blob/b1d9b8b71ea6b1c12e636a971cadf3bb6099a3d0/lib/core-server/src/utils/copy-all-static-files.ts) part. This [copy](https://github.com/storybookjs/storybook/blob/b1d9b8b71ea6b1c12e636a971cadf3bb6099a3d0/lib/core-server/src/utils/copy-all-static-files.ts#L19) function should overwrite existing items. The [overwrite](https://github.com/jprichardson/node-fs-extra/blob/master/docs/copy.md) option is not set and default is true (at least if we can trust the docs).
> 
> any idea where else the error might be coming from?

I did some research and narrowed it down to this line 

https://github.com/storybookjs/storybook/blob/7035ea7389393da041985ebc491ee58dedb50d06/code/lib/core-server/src/utils/copy-all-static-files.ts#L55

I double checked it by step-debugging through it and modifying the node_modules code 

```javascript
    await _fsExtra.default.copy(from, targetPath, {
      dereference: true,
      preserveTimestamps: true,
      filter: function (_, dest) {
        return !skipPaths.includes(dest);
      }
    }, function(err) {
        var foo = err;
        console.log(foo);
    });
```

What confuses me is that "overwrite" does not have an effect. It should default to true but even if I set it "true" it does not overwrite it. I can set `errorOnExist: false` (https://github.com/jprichardson/node-fs-extra/blob/master/docs/copy.md#copysrc-dest-options-callback) and this actually is applied to copy. It errors that "file already exists" but proceeds with the build 

I'm on windows so this might be an OS issue, what OS are you on?
I try it on my MacBook soon and double check that as well

**Comment by kroeder** [comment] 2022-08-30 19:06
I tried to use the latest version of fs-extra without success.

The error gets thrown here in fs-extra copy https://github.com/jprichardson/node-fs-extra/blob/9.1.0/lib/copy/copy.js#L154

Still investigating why

**Closed** 2022-09-08 15:12 UTC
Labels: bug, has workaround, app: angular, core, needs triage, linear

**Comment by shilman** [comment] 2022-09-13 11:14
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.33 containing PR #19064 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

**Comment by kenfdev** [comment] 2022-10-06 07:12
@shilman 
Are there any plans on releasing this fix for v6?? I'm facing the same problem on Storybook v6.5.12 and am thinking about how I can fix this 🤔 The directory names can't be renamed because it's used in production.
Thanks in advance!

**Comment by asvishnyakov** [comment] 2023-10-04 17:32
I see exactly the same error when building >= 7.2

**Comment by KonstantinSimeonov** [comment] 2025-10-22 23:17
For anyone having trouble with v6, you can unset the `staticDirs` property in your `.storybook/main.js` file and then copy over the public files manually with `cp -r`.
