### ISSUE TITLE
Restore focus after specific interaction events

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#16139] opened 2021-09-23 13:32 UTC
> As a user I want to be able to navigate through stories by keyboard (without the keyboard losing focus), so that I can quickly browse through a Storybook.

Patch certain methods that we know grab focus to transfer focus back to the previous location upon completion.

- [ ] `userEvent.type`
- [ ] ... more TBD

NOTE: Also possibly an a11y issue

**Comment by vanessayuenn** [comment] 2024-10-31 12:47
Dupe of #16143 ?

**Closed by vanessayuenn** 2024-10-31 12:47 UTC
Labels: bug, addon: interactions
