### ISSUE TITLE
Integration with Nrwl: TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by vic-lee** [storybookjs/storybook#13576] opened 2021-01-07 22:35 UTC
**Describe the bug**

When adding storybook to a nrwl repository, I'm seeing the following error:

```
ERR! TypeError: Object(...) is not a function
ERR!     at Module../node_modules/@storybook/theming/node_modules/@emotion/core/dist/emotion-element-57a3a7a3.browser.esm.js (http://localhost:4400/vendors~main.ae85b3bef025104a23e9.bundle.js:33755:99)
ERR!     at __webpack_require__ (http://localhost:4400/runtime~main.99691078705b39185f99.bundle.js:80:30)
ERR!     at Module../node_modules/@storybook/theming/node_modules/@emotion/core/dist/core.browser.esm.js (http://localhost:4400/vendors~main.ae85b3bef025104a23e9.bundle.js:33461:98)
ERR!     at __webpack_require__ (http://localhost:4400/runtime~main.99691078705b39185f99.bundle.js:80:30)
ERR!     at Module../node_modules/@emotion/styled-base/dist/styled-base.browser.esm.js (http://localhost:4400/vendors~main.ae85b3bef025104a23e9.bundle.js:2036:71)
ERR!     at __webpack_require__ (http://localhost:4400/runtime~main.99691078705b39185f99.bundle.js:80:30)
ERR!     at Module../node_modules/@emotion/styled/dist/styled.browser.esm.js (http://localhost:4400/vendors~main.ae85b3bef025104a23e9.bundle.js:2216:78)
ERR!     at __webpack_require__ (http://localhost:4400/runtime~main.99691078705b39185f99.bundle.js:80:30)
ERR!     at Object../node_modules/@storybook/theming/dist/index.js (http://localhost:4400/vendors~main.ae85b3bef025104a23e9.bundle.js:32871:39)
ERR!     at __webpack_require__ (http://localhost:4400/runtime~main.99691078705b39185f99.bundle.js:80:30)
```

**To Reproduce**

1. `git clone https://github.com/nrwl/nx-examples`
2. `yarn add --dev @nrwl/storybook`                                        // add nrwl's storybook plugin
3. `nx g @nrwl/angular:storybook-configuration products`    // add storybook for the 'products' app in the monorepo
4. `nx run products:storybook`                                                 // launch the 'products' app's storybook dashboard

**Expected behavior**

User should see the storybook dashboard.

**System**

  System:
    OS: macOS 11.1
    CPU: (8) x64 Apple M1
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Safari: 14.0.2
  npmPackages:
    @storybook/addon-knobs: ^6.1.11 => 6.1.11 
    @storybook/angular: ^6.1.11 => 6.1.11

**Comment by schickling** [comment] 2021-01-12 17:58
Seeing the same with v6.2-alpha

**Comment by jonniebigodes** [comment] 2021-01-12 21:20
@vic-lee i've done some testing based on your description and it seems that there's more to it. This is what i've done:
- Cloned the repo you've mentioned.
- Installed the dependencies.
- Issued `yarn add --dev @nrwl/storybook` as you've mentioned and documented [here](https://nx.dev/latest/angular/plugins/storybook/overview).
- Issued `yarn nx g @nrwl/angular:storybook-configuration products` (subtle change here is that i don't have the cli installed globally).
- Issued `yarn nx run products:storybook` and i'm presented with the following:
```shell
Unable to resolve @nrwl/storybook:storybook.
Cannot find module '@storybook/core/dist/server/build-dev'
Require stack:
- /Users/MyUser/Myfolder/nx-examples/node_modules/@nrwl/storybook/src/builders/storybook/storybook.impl.js
- /Users/MyUser/Myfolder/nx-examples/node_modules/@nrwl/tao/src/shared/workspace.js
- /Users/MyUser/Myfolder/nx-examples/node_modules/@nrwl/tao/src/commands/run.js
- /Users/MyUser/Myfolder/nx-examples/node_modules/@nrwl/tao/index.js
- /Users/MyUser/Myfolder/nx-examples/node_modules/@nrwl/cli/lib/run-cli.js
```

Seems a bit reasonable to let the maintainers over at nrwl be aware that there are some issues with the integration. I'm going to continue doing some more testing on this and see how it fares. 

@schickling v6.2 is a pre-release version so some issues are bound to occur. If you could provide a bit more context on what framework (React/Angular/Vue...) your using it will help triaging better.

Stay safe both of you

**Comment by vic-lee** [comment] 2021-01-13 06:53
@jonniebigodes Thanks for your help!

I'm also seeing the same error as yours after re-cloning and repeating the steps above. The error for this PR still exists in the private repository that I'm working on, but unfortunately I'm not able to share that repo here.

For reference, I have opened another issue on NX: https://github.com/nrwl/nx/issues/4516

**Comment by jonniebigodes** [comment] 2021-07-30 21:00
@vic-lee closing this issue if you don't mind, I re-ran the steps you've mentioned within your issue description and wasn't able to reproduce them. Looks like the issue is fixed upstream.


Stay safe

**Closed by jonniebigodes** 2021-07-30 21:00 UTC
Labels: PN, compatibility with other tools, question / support
