### ISSUE TITLE
Hiding canvas tab can result in nothing being rendered

### ISSUE THREAD

**Issue by hipstersmoothie** [storybookjs/storybook#10592] opened 2020-04-29 19:57 UTC
**Describe the bug**

When I have a story that hides a tab `storybook` can get into a state where nothing is rendered

**To Reproduce**

1. Install `addon-docs`
2. Create a 2 stories like

```ts
import React from 'react';
import mdx from './Docs.mdx';

// Shows only docs
export const one = () => <div />

one.story =  {
  parameters: {
    docs: {
      page: mdx,
    },
    previewTabs: { 
        // one hides the canvas
        canvas: { hidden: true },
      },
  },
};

// Shows canvas and docs
export const two = () => <div />
```

3. Navigate to `one` => docs are displayed
4. Navigate to `two` => canvas is displayed
4. Navigate to `one` => nothing is displayed

**Expected behavior**

Should display the docs tab

**System:**

```
  System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 12.16.3 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 74.0
    Safari: 13.0.5
  npmPackages:
    @storybook/addon-docs: 6.0.0-beta.0 => 6.0.0-beta.0
    @storybook/addon-google-analytics: 6.0.0-beta.0 => 6.0.0-beta.0
    @storybook/addon-links: 6.0.0-beta.0 => 6.0.0-beta.0
```

**Additional context**

So what I'm trying to do is have 1 top level stories that lists all the other stories in the `kind`.

![Screen Shot 2020-04-29 at 12 48 30 PM](https://user-images.githubusercontent.com/1192452/80640066-c3147480-8a17-11ea-96e4-3a30342ae45d.png)

I know the docs page can do this but all our designers want an `All` story in the sidebar. So to get around this I create an `all` story that renders nothing with an mdx file the actually renders all the stories

**component.stories.tsx**

```tsx
  import mdx from './component.mdx';

  /** A dummy story the renders a docs page for all components in the kind */
  const All = () => <div />;

  All.story = {
    parameters: {
      docs: {
        // Renders just this
        page: mdx,
      },
      previewTabs: {
        // don't show the story
        canvas: { hidden: true },
      },
    },
  };

  return All;
```

**component.mdx**

```mdx
import { Stories, Title } from '@storybook/addon-docs/blocks';

<Title />
<br /> 

<Stories />
```

The only part of this that doesn't work is switching between view modes.

![Screen Recording 2020-04-29 at 12 54 05 PM](https://user-images.githubusercontent.com/1192452/80640917-f1468400-8a18-11ea-9621-1c01e8f864a9.gif)

**Comment by hipstersmoothie** [comment] 2020-04-29 20:07
The same thing happens if I hide the docs tab and navigate through canvas

**Comment by shilman** [comment] 2020-04-30 02:11
cc @ndelangen

**Comment by ndelangen** [comment] 2020-04-30 12:02
I opened a PR with a fix

**Comment by ndelangen** [comment] 2020-05-04 07:39
I need more explanation then..

You say "nothing is rendered", but your story is literally an empty div..

I don't know how to reproduce this.

Looking at the video, it seems like storybook is working as intended?

> Navigate to one => nothing is displayed

it's an empty div? even if you're hiding the canvas tab it's still active..

**Comment by shilman** [comment] 2020-05-04 08:05
Does he need to set `viewMode` to `docs`? Should `viewMode` be set to `docs` automagically when the the canvas tab is hidden?

**Comment by ndelangen** [comment] 2020-05-04 08:19
Please let's not! there's a separate parameter for forcing viewMode changes, this code is already WAY to complicated as is.

**Comment by shilman** [comment] 2020-05-04 08:51
@hipstersmoothie if you set `viewMode: 'docs'`, does that solve your problem?

**Comment by ndelangen** [comment] 2020-05-04 08:56
That SHOULD change the viewMode when navigating to the story.

**Comment by hipstersmoothie** [comment] 2020-05-04 17:14
The problem is (and I know i'm getting into edge case territory) I really don't want to force my storybook into another viewMode.

Right now our storybook serves 2 consumers: designer and developer

Designers main look browse the docs with viewMode set to docs. Developers browse mainly though looking at stories + addons. Both experiences are configured to bet suit the consumer. 

I recently added and `Overview` mdx only story that serves as the introduction to the component (combining docs for the two consumers to a degree). What is super cool is that we can link each consumer to a tab (canvas or docs) and then as they browse the get the viewMode attached to the tab.

ex: Link a dev to the mdx only story in canvas mode => then the browse everything in canvas
ex: Link a designer to the mdx only story in docs mode => then the browse everything in docs

Where this breaks down is that another thing people want is an `All` story that contains all the stories for a `kind`. What I found though is it isn't all that easy to create an MDX only story that shows all the stories of another kind

ex: I want and mdx only story to display all the button stories (seperate from actual docs)

To do this I found a way to get the `All` story to basically do what I want. The only drawback is that the `canvas` tab is still showing. I saw the new tab hiding option so I thought, "oh, I'll just hide the canvas tab on this special story". But when I did that I encountered the bug described above.  Which is basically:

1. have a story that hide the canvas tab
2. go to that page in viewMode === 'docs' => shows docs hides canvas (good)
3. go to that page in viewMode === 'canvas' => shows nothing (bad. it's only showing the docs tab so show that)

I'll get a reproduction up for you.

**Comment by hipstersmoothie** [comment] 2020-05-04 18:34
> it's an empty div? even if you're hiding the canvas tab it's still active..

I would expect storybook to not show a hidden tab. It should only display non-hidden tabs.

I know you can force the viewMode to avoid this. But then it forces the viewmode for every story, which I would really like to not happen.


Reproduction: https://github.com/hipstersmoothie/storybook/commit/e552e7ad64259152ad3a98e2be1603ce8680f888

**Comment by shilman** [comment] 2020-05-26 08:12
Possible direction: https://github.com/storybookjs/storybook/issues/10921

**Comment by shilman** [comment] 2020-06-11 13:07
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.24 containing PR #10599 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2020-06-11 13:07 UTC
Labels: bug, ui
