### ISSUE TITLE
[Bug]: Sidebar doesn't wrap which hides the "Run tests" and "Settings" buttons

### ISSUE THREAD

**Issue by domyen** [storybookjs/storybook#27206] opened 2024-05-20 15:08 UTC
### Describe the bug

The sidebar isn’t allowing the items within it to wrap. When I shrink the sidebar width, at a certain point the items no longer wrap and their right hand side gets cutoff. 

This is a problem because:
1. You can't see settings or run tests button
2. You can't see story status badges

Repro from [Chromatic’s own Storybook today](https://59c59bd0183bd100364e1d57-xclhbxlsoy.chromatic.com/).

![2024-05-16 16 58 09](https://github.com/storybookjs/storybook/assets/263385/b0927306-82e8-47fe-b6ee-02240c3b030f)

### Reproduction link

https://59c59bd0183bd100364e1d57-xclhbxlsoy.chromatic.com/

### Reproduction steps

1. Drag the sidebar left and right and see that the items don't wrap correctly

### System

```bash
This is reproducible using a published Storybook in your browser
```

**Comment by H0onnn** [comment] 2024-05-21 00:27
@domyen @vanessayuenn Hello ! I would like to solve this problem. Can you assign it to me ?

**Comment by vanessayuenn** [comment] 2024-05-21 12:10
@H0onnn we don't reserve "good first issues", so feel free to just open a PR for this issue. Be sure to check the [contribution guide](https://storybook.js.org/docs/react/contribute/how-to-contribute) and hop onto the [Storybook Discord](https://discord.gg/storybook) if you need any help getting started. Looking forward to your contribution! ✨

**Comment by H0onnn** [comment] 2024-05-22 03:04
Hello ! I'd like to get some help on this issue. I don't have this problem in my local dev environment and in the Storybook environment deployed with chromatic. Where can I find the problem?

**Comment by vanessayuenn** [comment] 2024-05-22 10:38
@H0onnn This seems to only happen when there are [composed Storybooks](https://storybook.js.org/docs/sharing/storybook-composition). Made you a new repro: https://stackblitz.com/edit/github-qngcps?file=README.md!

**Comment by ShreySinha02** [comment] 2024-09-04 20:35
@domyen @vanessayuenn hii can you please assign me this issue

**Comment by ShreySinha02** [comment] 2024-09-04 20:36
[Screencast from 04-09-24 11:18:29 PM IST.webm](https://github.com/user-attachments/assets/3264787b-110a-45fa-93ef-9a668b715b70)
I found the same problem in my local

**Comment by ShreySinha02** [comment] 2024-09-04 21:31
@domyen @domyen please review this [PR #29049](https://github.com/storybookjs/storybook/pull/29049)

**Comment by H0onnn** [comment] 2024-09-05 05:14
@ShreySinha02 There is already a PR I posted

**Comment by ShreySinha02** [comment] 2024-09-05 06:25
@H0onnn still facing the issue that's why i raised pr

**Comment by domyen** [comment] 2024-09-05 14:18
@ShreySinha02 thanks for submitting the PR. The underlying issue is caused by the heading of composed Storybooks horizontally extending in a way that affects scroll position.

@H0onnn thanks for the [exquisite detail in your PR](https://github.com/storybookjs/storybook/pull/27234). Much appreciated. I'm going to loop in @JReinhold who built the sidebar to confirm.

**Comment by JReinhold** [comment] 2024-09-05 19:16
@H0onnn and @ShreySinha02, thank you very much for your detailed insights into the issue. I did some research into your investigations and discovered that the root cause was actually fixed upstream in Radix some time ago. So I think the proper fix is just to upgrade the library.

I'm closing your PRs in favor of that change instead.

**Closed** 2024-09-06 10:23 UTC
Labels: bug, good first issue, help wanted, ui, sev:S3
