### ISSUE TITLE
Typescript typings for controls args

### ISSUE THREAD

**Issue by petermikitsh** [storybookjs/storybook#11916] opened 2020-08-12 05:22 UTC
**Describe the bug**

Suppose I'm using Storybook 6 with `@storybook/addon-controls` with React and TypeScript.

Per the [medium article](https://medium.com/storybookjs/storybook-controls-ce82af93e430), basic usage of control values like so:

```js
export const Basic = (args) => <Button {...args} />;
Basic.args = { label: 'hello button' };
```

Suppose the Button has these props:

```ts
interface ButtonProps {
  label?: string;
}
```

If I ever mutate the interface, there is no type interference for `<storyName>.args`.

There's value in having the component's types percolate through the system and apply to args: (1) Validating my stories conform to the component's interface, and (2) if I mutate the interface, I can easily update my stories accordingly. 

In TypeScript, if I want typings, for every story in my project I must write:

```tsx
interface Story {
  (): any;
  args?: ButtonProps; // Optional since args is defined after function declaration
}

export const Basic: Story = (args) => <Button {...args} />;
Basic.args = { label: 'hello button' };

```

**To Reproduce**

See above code samples.

**Expected behavior**

It seems verbose and overly ceremonious to have to define a new type for my stories. Is there a better way? Maybe storybook could ship an interface, so I could do something like this:

```tsx
import { Story } from '@storybook/...';

export const Basic: Story<ButtonProps> = (args) => <Button {...args} />;
Basic.args = { label: 'hello button' };
```

where Story is

```tsx
interface Story<T> {
  (): any;
  args?: T;
}
```

**Comment by shilman** [comment] 2020-08-12 06:08
We introduced typescript types in 6.0: https://github.com/storybookjs/storybook/blob/next/docs/snippets/react/page-story.ts.mdx

**Comment by rabelloo** [comment] 2020-08-13 17:51
Here are the types I'm currently using, better `argTypes`, hope it helps
https://gist.github.com/rabelloo/bae0397d6a331d939eacdb3e8849220f

**Comment by petermikitsh** [comment] 2020-08-19 16:09
It appears using `Template.bind({})` results in type `any`. To have each story's args typechecked, you must manually specify the type.

<img width="818" alt="Screen Shot 2020-08-19 at 9 07 36 AM" src="https://user-images.githubusercontent.com/1571918/90660941-74276080-e1fb-11ea-8882-dc2fa8c499d4.png">

<img width="830" alt="Screen Shot 2020-08-19 at 9 04 23 AM" src="https://user-images.githubusercontent.com/1571918/90660614-03804400-e1fb-11ea-999d-1f8cf89e84e2.png">

**Comment by torkelrogstad** [comment] 2020-09-10 12:56
@petermikitsh `.bind({})` should return the type of the function you're binding. See [TypeScript playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gMyUgXPABSwDmhKArgLYBGIMAlPALwB88mMAliqQFDJ0WWrFY48AOlq9gRAN4BfZvCA) example. 

I think the reason you're seeing this is because you haven't enabled `strictBindCallApply` in your TS config.

**Comment by jamiehaywood** [comment] 2020-09-29 10:24
@torkelrogstad I'm running into the same problem as @petermikitsh and I've got `strictBindCallApply: true` in my `tsconfig.json`

**Comment by torkelrogstad** [comment] 2020-09-29 13:00
I'd suggest to create a minimal reproduction in the TypeScript playground.

**Comment by jpcmf** [comment] 2020-11-27 16:05
Any way to fix this?

```
Failed to compile.

/Users/joaopaulofricks/www/xxx-Design-System/src/stories/components/Button.stories.tsx
TypeScript error in /Users/joaopaulofricks/www/xxx-Design-System/src/stories/components/Button.stories.tsx(8,20):
Parameter 'args' implicitly has an 'any' type.  TS7006

     6 | storiesOf('Atoms/Button', module)
     7 |   .addDecorator(withKnobs)
  >  8 |   .add('Default', (args) => <Button {...args}>Default</Button>, {
       |                    ^
     9 |     component: Button,
    10 |   })
    11 |   .add(
```

**Comment by shilman** [comment] 2020-11-27 16:36
Workaround:

>  8 |   .add('Default', (args: any) => <Button {...args}>Default</Button>, {

**Comment by jpcmf** [comment] 2020-11-30 17:10
@shilman I have problems with `any` in my application. The better approach is to pass the props to the element... I'll try out, thank you :)

**Comment by andrewbusch7** [comment] 2020-12-11 09:20
@jpcmf I've made a helper function in my project so that it's fully typed whilst having minimal boilerplate for each component.

**helpers.tsx:**

```ts
import * as React from 'react';
import { Story } from '@storybook/react';
import { StoryFnReactReturnType } from '@storybook/react/dist/client/preview/types';

export const templateForComponent = <P,>(Component: (props: P) => StoryFnReactReturnType) => (
    props: P
): Story<P> => {
    const template: Story<P> = (args) => {
        return <Component {...args} />;
    };
    const story = template.bind({});
    story.args = props;
    return story;
};
```

**Input.stories.tsx:**

```ts
import { Meta } from '@storybook/react';
import { templateForComponent } from '../helpers';
import Input from '../../ui-web-library/Form/Input';

const template = templateForComponent(Input);

const meta: Meta = {
    title: 'Form/Input',
    component: Input,
};
export default meta;

export const Currency = template({
    type: 'currency',
    fieldName: 'income',
});
```

It also slims down the code in comparison to using .bind() and .args for each story. Hope that helps!

**Comment by shilman** [comment] 2020-12-13 11:02
@andrewbusch7 we plan to introduce a more streamlined format in a future version of Storybook (6.3?). we'll provide codemods to upgrade from existing args stories to the new format, but those codemods won't work with helper functions like you've defined. so i'd probably recommend against that approach, though of course you're welcome to do what you like!

**Comment by andrewbusch7** [comment] 2020-12-16 03:10
@shilman ok great. Is there an issue or PR I can follow with the proposed design of that? Hoping I can regex find & replace when the time comes.

In terms of ETA, I'm guessing half a year or so before 6.3 comes out based off past releases?

**Comment by shilman** [comment] 2020-12-16 03:24
@andrewbusch7 Here's the issue: https://github.com/storybookjs/storybook/issues/12654

We don't have an ETA, but I don't think we'll get it into 6.2, which is targeting mid-Feb. 6.3 (or 7.0 if there's no 6.3) would then be around June.

Looking at your code, I suppose it wouldn't be hard to simply tweak your definition of `template` for the new format.

That said, in general we are moving towards more AST analysis in Storybook and the surrounding ecosystem, and that will fail with random user-defined functions, so my recommendation stands. Thanks for your patience and input to help make Storybook better!

**Comment by andrewbusch7** [comment] 2020-12-16 04:45
@shilman thanks! I'll give that a read through when I can. The main requirement I'm chasing is having Typescript safety & refactoring on the props I'm defining in my stories. I'll have to see whether or not that proposal fulfills that elegantly.

**Comment by sevfurneaux** [comment] 2021-01-04 22:25
@shilman Thanks so much for adding types 💪.

One issue I have, which is quite an edge case is when I need a a story to be called "Default"by assigning `defaultStory.story = { name: 'Default' };`.

For example:

```
const Template: Story<ButtonProps> = (args) => <Button {...args} />;

export const defaultStory = Template.bind({});

defaultStory.story = { name: 'Default' };
defaultStory.args = {
  children: 'Hello button',
};
```

However I get the Typescript error:

`Property 'story' does not exist on type 'Story<ButtonProps>'.`

For now, I can always rename `defaultStory`, but might be something to consider.

**Comment by shilman** [comment] 2021-01-04 22:37
@sevfurneaux https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#hoisted-csf-annotations

**Comment by yannbf** [comment] 2021-01-04 22:42
@sevfurneaux I believe you can write stories with name default, just don't use it lowercase. Still, if you want to set the name via the property, the types actually refer to the standard shape defined when the annotations were hoisted back in 6.0 beta, so instead of Default.story.name, you do Default.storyName:

```tsx
const Template: Story<ButtonProps> = (args) => <Button {...args} />;

// should work fine
export const Default = Template.bind({});

// should work with typescript as long as you have either `strict` or `strictBindCallApply` set to true
defaultStory.storyName: 'Default';
defaultStory.args = {
  children: 'Hello button',
};
```

**Comment by MickL** [comment] 2021-02-01 15:22
Could you update the docs please? Took me a while to get here!

https://storybook.js.org/docs/angular/writing-stories/introduction

This: 

```
const Template = (args: Button) => ({
  component: Button,
  props: args,
});
```

Should be:

```
const Template: Story<Button> = (args) => ({
  component: Button,
  props: args,
});
```

**Comment by jonniebigodes** [comment] 2021-02-01 15:41
@MickL the angular snippets are being adjusted already. There's some tweaks here and there that are required and they should be merged pretty soon.

**Comment by MickL** [comment] 2021-02-01 15:43
Is there a branch where I can see the changes? I just worked myself through it.

**Comment by Tymek** [comment] 2021-03-10 12:29
In case someone find this issue searching for "why argTypes from TS aren't working": Check **`tsconfig.json`**. In my case adjusting something to be in line with [`/examples/cra-ts-kitchen-sink/tsconfig.json`](https://github.com/storybookjs/storybook/blob/65c8ca746f441464a095d623117af3f89ac4d803/examples/cra-ts-kitchen-sink/tsconfig.json) fixed this issue.

**Comment by eric-burel** [comment] 2021-04-23 14:27
> @petermikitsh `.bind({})` should return the type of the function you're binding. See [TypeScript playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gMyUgXPABSwDmhKArgLYBGIMAlPALwB88mMAliqQFDJ0WWrFY48AOlq9gRAN4BfZvCA) example.
> 
> I think the reason you're seeing this is because you haven't enabled `strictBindCallApply` in your TS config.

This seems to make the required fields optional though

**Comment by shilman** [comment] 2021-04-23 14:51
@eric-burel discussion here:

https://github.com/storybookjs/storybook/pull/14550

**Comment by yannbf** [comment] 2021-04-23 17:48
@shilman is there a reason this issue is still open? We do have support for the types. Maybe documentation can be improved, but the feature is already implemented

**Closed** 2021-04-23 21:20 UTC
Labels: args, question / support, typescript

**Comment by eric-burel** [comment] 2021-06-14 10:13
Just a note on this, there seems to be bugs from time to time when using `strictBindCallApply`. I am not sure yet of the cause, it's probably not Storybook's fault since the other typings are perfectly ok. I suspect VS Code sometimes is not applying `strictBindCallApply`, or type checking failing somehow, in some setups.

**Comment by jasmo2** [comment] 2022-08-11 16:51
> **Describe the bug**
> 
> Suppose I'm using Storybook 6 with `@storybook/addon-controls` with React and TypeScript.
> 
> Per the [medium article](https://medium.com/storybookjs/storybook-controls-ce82af93e430), basic usage of control values like so:
> 
> ```js
> export const Basic = (args) => <Button {...args} />;
> Basic.args = { label: 'hello button' };
> ```
> 
> Suppose the Button has these props:
> 
> ```ts
> interface ButtonProps {
>   label?: string;
> }
> ```
> 
> If I ever mutate the interface, there is no type interference for `<storyName>.args`.
> 
> There's value in having the component's types percolate through the system and apply to args: (1) Validating my stories conform to the component's interface, and (2) if I mutate the interface, I can easily update my stories accordingly.
> 
> In TypeScript, if I want typings, for every story in my project I must write:
> 
> ```tsx
> interface Story {
>   (): any;
>   args?: ButtonProps; // Optional since args is defined after function declaration
> }
> 
> export const Basic: Story = (args) => <Button {...args} />;
> Basic.args = { label: 'hello button' };
> ```
> 
> **To Reproduce**
> 
> See above code samples.
> 
> **Expected behavior**
> 
> It seems verbose and overly ceremonious to have to define a new type for my stories. Is there a better way? Maybe storybook could ship an interface, so I could do something like this:
> 
> ```tsx
> import { Story } from '@storybook/...';
> 
> export const Basic: Story<ButtonProps> = (args) => <Button {...args} />;
> Basic.args = { label: 'hello button' };
> ```
> 
> where Story is
> 
> ```tsx
> interface Story<T> {
>   (): any;
>   args?: T;
> }
> ```

Here is un updated version for this one:

```tsx
import { ComponentStory, Story } from '@storybook/react';
import React, { FC } from 'react';

export const templateForComponent =
  <P extends {}>(Component: FC<P>) =>
    (props: P): Story<P> => {
      const template: ComponentStory<typeof Component> = (args) => (
        <Component {...args} />
      );

      const story = template.bind({});
      story.args = props;
      return story;
    };
```



And if you add a wrapper to further style here is the snippet:
```tsx
import { ComponentStory, Story } from '@storybook/react';
import React, { FC } from 'react';
import styled, { FlattenSimpleInterpolation } from 'styled-components';

type WrapperProps = {
  customeCss?: FlattenSimpleInterpolation;
  children?: React.ReactNode;
};

const Wrapper = styled.section<WrapperProps>`
  ${({ customeCss }) => customeCss && customeCss}
`;

export const templateForComponent =
  <P extends {}>(Component: FC<P & WrapperProps>) =>
  (props: P & WrapperProps): Story<P> => {
    const template: ComponentStory<typeof Component> = ({
      customeCss,
      ...args
    }) => (
      <Wrapper customeCss={customeCss}>
        <Component {...(args as P)} />
      </Wrapper>
    );

    const story = template.bind({});
    story.args = props;
    return story;
  };

```

**Comment by henryobiaraije** [comment] 2022-11-12 12:05
> strictBindCallApply

Yea. Turning `strictBindCallApply` on in tsconfig works.

**Comment by regnou** [comment] 2023-06-05 18:09
hi, I am using svelte, I have the same error, Turning ON strict... does not work for me

Property 'args' does not exist on type '(args: any) => { Component: typeof PureTaskList__SvelteComponent_; props: any; on: { onPinTask: HandlerFunction; onArchiveTask: HandlerFunction; }; }'.ts(2339)
