### ISSUE TITLE
Component defaultProps are not displayed in Storybook

### ISSUE THREAD

**Issue by sforehand** [storybookjs/storybook#15420] opened 2021-06-29 15:09 UTC
**Describe the bug**
In our React components, we define our component properties using prop-types like this:

`ComponentName.propTypes = { size: PropTypes.oneOf(["small", "medium", "large"])}`

Then, we regularly define defaults for these props immediately following our property types like this:

`ComponentName.defaultProps = {size: "small"}`

However, since our last update from Storybook 6.2.9 to 6.3.1, our Stories do not render the default properties.  Instead we see something like:

<img width="1385" alt="Screen Shot 2021-06-29 at 10 51 05 AM" src="https://user-images.githubusercontent.com/25122876/123821828-badcf100-d8c9-11eb-9fbd-a29119ad75dc.png">

**Comment by shilman** [comment] 2021-06-30 02:48
This is the [intended behavior as of 6.3](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-argtypedefaultvalue).

@domyen @tmeasday we're getting a lot of confusion about the new behavior. My recommendation, as before, is to use the "set value" button across the board to indicate that no value is set. Or maybe we need to improve the docs? Or maybe this is only an issue for users upgrading from previous versions that are used to the old behavior? At any rate, it appears buggy as is.

**Comment by tmeasday** [comment] 2021-06-30 03:52
I can get behind the "set value" in all undefined cases idea.

**Comment by Naoto-Ida** [comment] 2021-07-02 10:33
@sforehand 

May I suggest reading an issue I started regarding the same change.

https://github.com/storybookjs/storybook/issues/15378

**Comment by ndelangen** [comment] 2023-01-31 10:41
This has been fixed in Storybook 7.0 beta!

**Closed by ndelangen** 2023-01-31 10:41 UTC
Labels: discussion, question / support, ui, addon: controls

**Comment by lucapollani** [comment] 2023-07-19 08:03
Should defaultProps be displayed in Storybook 7 then?

I made a little repo here: https://stackblitz.com/edit/storybook-react-template-wlwehw-zkxi2a

I expected that Heading.defaultProps were used in Storybook controls section for "text" prop, instead it shows the "Set string" button causing the clearance of the value.

**Comment by tmeasday** [comment] 2023-07-19 08:26
The default value is displayed in a dedicated column. If you want to override it you can use the control.

**Comment by tmeasday** [comment] 2023-07-20 01:57
Oh, the controls addon doesn't show the default value column by default. You can expand the table with I think `parameters.controls.expanded = true`

**Comment by lucapollani** [comment] 2023-07-20 06:26
That could be enough, I've added the property in my _preview.js_, thanks for the tip @tmeasday! 😄
