### ISSUE TITLE
`build-storybook --docs` has no effect

### ISSUE THREAD

**Issue by kylegach** [storybookjs/storybook#15933] opened 2021-08-27 16:14 UTC
**Describe the bug**

The `--docs` flag to the `build-storybook` CLI has no discernible effect ([see docs](https://storybook.js.org/docs/react/writing-docs/build-documentation#preview-storybooks-documentation)). The flag (when combined with `--no-manager-cache`) _does_ work with `start-storybook`. Confirmed on 6.3.7 and 6.4.0-alpha.32.

**To Reproduce**

Repro repo: https://github.com/kylegach/build-storybook-docs-mode

_I also published the build result to GH Pages: https://kylegach.github.io/build-storybook-docs-mode/_

1. Add `"build-storybook:docs": "build-storybook -s public -o docs --docs"` to `package.json`'s `"scripts"`
1. (Literally no other changes)
1. Run `yarn build-storybook:docs`
1. Confirm that the result is the same as `yarn build-storybook`

**System**

<details>
<summary>Environment Info</summary>

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 3.0.1 - ~/.yarn/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Browsers:
    Chrome: 89.0.4389.128
    Firefox: 88.0.1
    Safari: 14.1.1
  npmPackages:
    @storybook/addon-actions: ^6.4.0-alpha.32 => 6.4.0-alpha.32
    @storybook/addon-docs: ^6.4.0-alpha.32 => 6.4.0-alpha.32
    @storybook/addon-essentials: ^6.4.0-alpha.32 => 6.4.0-alpha.32
    @storybook/addon-links: ^6.4.0-alpha.32 => 6.4.0-alpha.32
    @storybook/node-logger: ^6.4.0-alpha.32 => 6.4.0-alpha.32
    @storybook/preset-create-react-app: ^3.2.0 => 3.2.0
    @storybook/react: ^6.4.0-alpha.32 => 6.4.0-alpha.32
```
</details>

**Additional context**

<details>
<summary><code>npx sb@next repro</code></summary>

```
✔ 🌈 Select the repro framework › react
✔ 📝 Select the repro base template › cra
✔ Enter the output directory … build-storybook-docs-mode
🏃 Running cra into /Users/kg666261/projects/build-storybook-docs-mode

🏃 Starting for cra latest

{
  name: 'cra',
  version: 'latest',
  appName: 'build-storybook-docs-mode',
  creationPath: '/Users/kg666261/projects',
  cwd: '/Users/kg666261/projects/build-storybook-docs-mode',
  e2e: false,
  pnp: false,
  framework: 'react',
  generator: 'npx create-react-app@{{version}} {{appName}} --use-npm && cd {{appName}} && echo "FAST_REFRESH=true" > .env && echo "SKIP_PREFLIGHT_CHECK=true" > .env'
}
```
</details>

**Comment by shilman** [comment] 2021-08-31 15:14
@kylegach looks like you didn't check in the `.yarn` directory? or perhaps it's a problem with the repro script?

**Comment by kylegach** [comment] 2021-08-31 17:28
TIL: https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored

I was globally ignoring the entire `.yarn` directory (we still use yarn v1 for our projects 😅 ). I updated my config per the link above and started a fresh repro using the exact same steps as before, then I force-pushed to the repo. Same issue.

**Comment by kylegach** [comment] 2021-09-02 17:09
Hmm... last week, I was trying a simple POC, so I started from a fresh `sb init`, encountered the problem, reproduced with `sb@next repo`, and so I then reported this issue.

But it actually works in my _much_ more complex SB setup of my real project. Honestly, I was baffled at this issue, as I know many teams depend on the feature for their production docs. 🤷‍♂️ 

Feel free to close this, unless you feel it's a legitimate issue with the repro script.

**Comment by kylegach** [comment] 2021-09-02 17:15
Hmm... last week, I was trying a simple POC, so I started from a fresh `sb init`, encountered the problem, reproduced with `sb@next repro`, and so I then reported this issue.

But it actually functions correctly in the _much_ more complex SB setup of my real project. Honestly, I was baffled at this issue, as I know many teams depend on the feature for their production docs. 🤷‍♂️

Feel free to close this, unless you feel it's a legitimate issue with the repro script.

**Comment by BodaThomas** [comment] 2021-09-09 19:57
I exactly have the same error than you in my project. I'm trying to build the Storybook doc only with the `build-storybook --docs` command, but the output looks exactly the same than the `build-storybook -s public` command.
I'm using the 6.3.8 version of Storybook React.
You can find the preview of my build here: https://quizzical-davinci-04e4f0.netlify.app/

**Comment by kylemh** [comment] 2022-01-04 00:10
Docs mode doesn't work for me on fresh projects.

```sh
# 1
npx create-react-app test

# 2
npx sb init

# 3
# Add `--docs` to added `build-storybook` script in `package.json`

# 4
npm run build-storybook

# 5
open storybook-static/index.html
```

<img width="1725" alt="Screen Shot 2022-01-04 at 7 08 40 AM" src="https://user-images.githubusercontent.com/9523719/147993508-dc35a561-7b61-419b-a6f5-1c637b39f80a.png">

**Comment by shilman** [comment] 2022-01-04 03:21
@kylemh i just tried your repro. if you run a server it works:

```
npx http-server storybook-static
```

**Comment by kylemh** [comment] 2022-01-04 03:24
Should it not work as a static deployment? Needing to run Storybook with a server to get access to Docs mode seems like a negative requirement, and one that's not documented.

**Comment by kylemh** [comment] 2022-01-06 14:42
Also, any idea how I'd run this thru Vercel?

**Comment by shilman** [comment] 2022-01-07 07:51
@kylemh Strangely, when I tried it again today it reproduces per your instructions 🤔

**Comment by shilman** [comment] 2022-01-20 10:47
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.22 containing PR #17300 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2022-01-20 10:47 UTC
Labels: bug, addon: docs, build-storybook, linear

**Comment by shilman** [comment] 2022-01-20 10:49
This fix in #17300 is a workaround, but I am going to close this anyway. I think the way we handle manager caching will change as part of 7.0

**Comment by kylemh** [comment] 2022-01-20 10:58
do you want me to open a PR to recommend this flag if using `--docs`?

**Comment by shilman** [comment] 2022-01-21 10:11
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.14 containing PR #17300 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

**Comment by kylemh** [comment] 2022-03-22 04:23
Coming back to this one @shilman 

It seems like the only way I'm able to dev and ship _only_ docs mode is to use the `--no-manager-cache`, but this hurts performance. Do I have any alternative course of action?
