### ISSUE TITLE
[Storybook 6.4] HMR is ignored when making changes in preview.js

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#17767] opened 2022-03-20 17:11 UTC
**Describe the bug**

Title is descriptive, and here's a video for more context:

https://user-images.githubusercontent.com/1671563/159174085-20904e10-6f70-4041-bbfb-b21ce59512db.mp4

This is the error:
![image](https://user-images.githubusercontent.com/1671563/159174103-d7a537a4-5116-49d3-9db9-328793fc2f10.png)

**To Reproduce**
1 - sb repro for CRA or any other
2 - run Storybook
3 - make changes in preview.js

**Comment by tmeasday** [comment] 2022-03-21 00:24
@yannbf in SSv6, we do force a full reload when you make a change to `preview.js`. 

In official Storybook, I see:

![image](https://user-images.githubusercontent.com/132554/159192424-6c9e7856-cc5a-4cff-9d17-d5e0afa1df78.png)

and the page reloads. That looks like that's not what's happening here?

**Comment by tmeasday** [comment] 2022-03-21 00:30
Looks like this is an issue with webpack 5, not sure there's much we can do (beyond push people to ssv7): https://github.com/webpack-contrib/webpack-hot-middleware/issues/390

@yannbf to confirm this was a WP5 project?

**Comment by rikkit** [comment] 2022-03-23 15:59
I am also experiencing this issue, non-CRA app, plain Storybook with Yarn 2 Pnp and Webpack 5. I think it's fair to say hot reload is pretty core to the Storybook dev experience so any alternative setups are welcome...

@tmeasday What's ssv7?

**Comment by tmeasday** [comment] 2022-03-24 01:15
@rikkit, sorry, the `storyStoreV7` feature. 

> Edit: using the resolution specified here helps a bit - the preview reloads on change, which is not so bad for now. https://github.com/webpack-contrib/webpack-hot-middleware/issues/390#issuecomment-758540604

That's the correct behaviour in the v6 version of the story store. For various boring technical reasons we need to reload the browser if you change `preview.js`; this is a limitation we removed in the v7 store.

**Comment by jrmyio** [comment] 2022-05-06 13:55
I get the same issue with `@storybook/builder-vite` and `storyStoreV7` enabled. Vite starts refetching (instead of HMR) all dependencies when any of the dependencies that are used in preview.tsx are edited.

For example, when using a StyledComponents theme (provided by `ThemeProvider` inside the `preview.tsx`), the entire preview refreshes when I change the provided theme.

**Comment by tmeasday** [comment] 2022-05-09 00:12
@jrmyio I'm not totally sure about the Vite builder. @IanVS - is it expected to do a full refresh on `preview.tsx` changes (even with Story Store v7`)?

**Comment by IanVS** [comment] 2022-05-09 01:55
I do see that as well, now that I look.  I've been fiddling with it a bit, and I can get HMR to work, but I'm not happy with the solution so far.  I'll put up a PR in the next day or two and see if I can get some help from @joshwooding.

**Comment by codebutler** [comment] 2023-03-30 18:10
I'm also using the vite builder, storyStoreV7, and have to manually refresh the browser after changing the theme (in my case using chakra-ui).

@IanVS Can you please share your workaround for this issue? Thanks.

**Comment by tmeasday** [comment] 2023-04-03 00:10
@codebutler this issue is fixed in SB7.

**Comment by IanVS** [comment] 2023-04-03 13:28
I've closed this because I believe the issue is fixed in both webpack and vite in Storybook 7.  If someone is still having problems with the latest version of Storybook, please let us know.

**Closed** 2023-04-03 13:27 UTC
Labels: bug, core
