### ISSUE TITLE
[Bug]: Tailwind CSS not working in Next.js project with Storybook

### ISSUE THREAD

**Issue by jferrettiboke** [storybookjs/storybook#27118] opened 2024-05-14 08:31 UTC
### Describe the bug

When setting up a default Next.js project and following the official documentation to add Storybook, Tailwind CSS classes do not work. The issue seems to be related to the configuration file name for PostCSS. Renaming `postcss.config.mjs` to `postcss.config.js` resolves the issue.

### To Reproduce

1. Set up a default Next.js project using the command:
   ```sh
   pnpm dlx create-next-app@latest
   ```
2. Add Storybook to the project using the command:
   ```sh
   pnpm dlx storybook@latest init
   ```
3. Attempt to use Tailwind CSS classes within Storybook.
4. Notice that Tailwind classes do not apply.
5. Rename `postcss.config.mjs` to `postcss.config.js`.
6. Observe that Tailwind classes now work as expected.

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.4.1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.1 - ~/.nvm/versions/node/v20.12.1/bin/node
    Yarn: 1.22.22 - ~/Library/pnpm/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.1/bin/npm
    pnpm: 9.1.1 - /usr/local/bin/pnpm <----- active
  Browsers:
    Chrome: 124.0.6367.202
    Edge: 124.0.2478.97
    Safari: 17.4.1
  npmPackages:
    @storybook/addon-essentials: ^8.0.10 => 8.0.10 
    @storybook/addon-interactions: ^8.0.10 => 8.0.10 
    @storybook/addon-links: ^8.0.10 => 8.0.10 
    @storybook/addon-onboarding: ^8.0.10 => 8.0.10 
    @storybook/blocks: ^8.0.10 => 8.0.10 
    @storybook/nextjs: ^8.0.10 => 8.0.10 
    @storybook/react: ^8.0.10 => 8.0.10 
    @storybook/test: ^8.0.10 => 8.0.10 
    eslint-plugin-storybook: ^0.8.0 => 0.8.0 
    storybook: ^8.0.10 => 8.0.10 
```

### Additional context

It might be worth mentioning this workaround in the documentation while a permanent fix is implemented.

**Comment by valentinpalkovic** [comment] 2024-05-14 10:07
Duplicate of https://github.com/storybookjs/storybook/issues/27118. The issue is resolved, and a fix was released with 8.1.0-alpha.6. The Storybook v8.1 will be released today.

**Closed by valentinpalkovic** 2024-05-14 10:07 UTC
Labels: bug, needs triage

**Comment by jferrettiboke** [comment] 2024-05-14 12:45
@valentinpalkovic I don't get it. The issue I opened is a duplicate of my own issue? 😅

Thanks for the update.

**Comment by valentinpalkovic** [comment] 2024-06-24 12:39
It is a duplicate of https://github.com/storybookjs/storybook/issues/26702. My bad
