### ISSUE TITLE
[Bug]: [ERR_PACKAGE_PATH_NOT_EXPORTED] using Vite and Svelte

### ISSUE THREAD

**Issue by johannes-luebke** [storybookjs/storybook#20461] opened 2022-12-30 23:48 UTC
### Describe the bug

**Issue**: Running `npm run storybook` fails on a fresh Svelte project.

My steps:

After creating a new project using `npm create vite@latest`, choosing **Svelte** and **Typescript** `npm run dev` is working as expected.

Now I run `npx storybook init --type svelte`.
During installation I get a few deprecation warnings but no errors.

Depending on the npm version used I get a message asking me to run npm with the `--legacy-peer-deps=true` flag set.

Now I try running `npm run storybook`.
Regardless of the npm version this always fails. But the messages can be a bit different.
The error code seems to be the same though [ERR_REQUIRE_ESM].
Using nodejs verision 14.21.2 I get a message describing a fix, but not with any higher version of nodejs:

> require() of D:\Development\reproduction\svelte.config.js from D:\Development\reproduction\.storybook\main.cjs is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename svelte.config.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from D:\Development\reproduction\package.json.

I tried 2 things. 1. I followed the instructions of the error message. 2. I followed the tips given in this issue #11587

In both cases the [ERR_REQUIRE_ESM] disappears. But now I get 'ERR_PACKAGE_PATH_NOT_EXPORTED'.
I've been trying to find a solution to this error message for a while now and couldn't find any direct information linking to my problem.
The only references to people having an issue with this error message were resolved by using a different version of nodejs.
So I tried the same steps using following versions of nodejs:
- 14.21.2
- 16.19.0
- 18.10.0
- 18.12.1
- 19.3.0

All resulted in the same error message. I'll dump it here:

> npm run storybook
> reproduction@0.0.0 storybook D:\Development\reproduction
> start-storybook -p 6006
> info @storybook/svelte v6.5.15
> info 
> info => Loading presets
> ERR! Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in D:\Development\reproduction\node_modules\@sveltejs\vite-plugin-svelte\package.json
> ERR!     at new NodeError (internal/errors.js:322:7)
> ERR!     at throwExportsNotFound (internal/modules/esm/resolve.js:332:9)
> ERR!     at packageExportsResolve (internal/modules/esm/resolve.js:523:7)
> ERR!     at resolveExports (internal/modules/cjs/loader.js:450:36)
> ERR!     at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
> ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
> ERR!     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
> ERR!     at Module.require (internal/modules/cjs/loader.js:974:19)
> ERR!     at require (internal/modules/cjs/helpers.js:101:18)
> ERR!     at pluginConfig (D:\Development\reproduction\node_modules\@storybook\builder-vite\dist\vite-config.js:161:34)
> ERR!  Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in D:\Development\reproduction\node_modules\@sveltejs\vite-plugin-svelte\package.json
> ERR!     at new NodeError (internal/errors.js:322:7)
> ERR!     at throwExportsNotFound (internal/modules/esm/resolve.js:332:9)
> ERR!     at packageExportsResolve (internal/modules/esm/resolve.js:523:7)
> ERR!     at resolveExports (internal/modules/cjs/loader.js:450:36)
> ERR!     at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
> ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
> ERR!     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
> ERR!     at Module.require (internal/modules/cjs/loader.js:974:19)
> ERR!     at require (internal/modules/cjs/helpers.js:101:18)
> ERR!     at pluginConfig (D:\Development\reproduction\node_modules\@storybook\builder-vite\dist\vite-config.js:161:34) {
> ERR!   code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
> ERR! }
> 
> WARN Broken build, fix the error above.
> WARN You may need to refresh the browser.
> 
> info => Loading presets
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! reproduction@0.0.0 storybook: `start-storybook -p 6006`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the reproduction@0.0.0 storybook script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\<username>\scoop\persist\nodejs\cache\_logs\2022-12-30T22_51_03_239Z-debug.log

### To Reproduce

```shell
Unfortunately running `npx sb@next repro` results in an error:
> An error occurred while executing: `yarn set version berry && yarn config set enableGlobalCache true && yarn config set nodeLinker node-modules`
```

### System

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
  Binaries:
    Node: 14.21.2 - ~\scoop\apps\nodejs\current\node.EXE
    npm: 6.14.17 - ~\scoop\apps\nodejs\current\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.963.0), Chromium (108.0.1462.54)
  npmPackages:
    @storybook/addon-actions: ^6.5.15 => 6.5.15
    @storybook/addon-essentials: ^6.5.15 => 6.5.15
    @storybook/addon-interactions: ^6.5.15 => 6.5.15
    @storybook/addon-links: ^6.5.15 => 6.5.15
    @storybook/builder-vite: ^0.2.6 => 0.2.6
    @storybook/svelte: ^6.5.15 => 6.5.15
    @storybook/testing-library: 0.0.13 => 0.0.13
```

**Comment by evangelos-ch** [comment] 2023-01-06 09:33
I ran into the same thing trying to play around with SvelteKit (which also uses Svelte and Vite) and Storybook, I found that using the Storybook 7 beta (`npx sb@next init`) worked pretty much out the box.

**Comment by ryu-man** [comment] 2023-01-07 20:09
I am also facing this issue, any workaround?

**Comment by gyenabubakar** [comment] 2023-01-07 20:16
Here's what worked for me:

1. Run `npm update && npm audit fix --force` after already running `npm i`.
2. Remove `node_modules` and `package-lock.json`.
3. Run `npm i`.

When I did this, one `@storybook/*` package's version downgraded. Be sure to change it back to match the others.

**Comment by Thiteago** [comment] 2023-01-09 15:04
I have the same problem here in my svelte application, i tried the steps of #11587 issue too, but i can't fix it, somebody managed to fix that ?

**Comment by KieranP** [comment] 2023-01-15 22:46
Am experiencing the same issue using latest vite, svelte, and storybook V7 prerelease

```
ERR! Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /Work/node_modules/@sveltejs/vite-plugin-svelte/package.json
ERR!     at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
ERR!     at new NodeError (node:internal/errors:371:5)
ERR!     at throwExportsNotFound (node:internal/modules/esm/resolve:440:9)
ERR!     at packageExportsResolve (node:internal/modules/esm/resolve:645:7)
ERR!     at resolveExports (node:internal/modules/cjs/loader:482:36)
ERR!     at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
ERR!     at Function.Module._resolveFilename (/Work/node_modules/esbuild-register/dist/node.js:4768:36)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at Object.<anonymous> (/Work/vite.config.ts:3:24)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14)
ERR!     at Module._compile (/Work/node_modules/esbuild-register/dist/node.js:2258:26)
ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
ERR!     at Object.newLoader [as .ts] (/Work/node_modules/esbuild-register/dist/node.js:2262:9)
ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at Object.<anonymous> (/Work/.storybook/main.ts:1:24)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14)
ERR!     at Module._compile (/Work/node_modules/esbuild-register/dist/node.js:2258:26)
ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
ERR!     at Object.newLoader [as .ts] (/Work/node_modules/esbuild-register/dist/node.js:2262:9)
ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at interopRequireDefault (/Work/node_modules/@storybook/core-common/dist/index.js:6:21)
ERR!     at serverRequire (/Work/node_modules/@storybook/core-common/dist/index.js:6:373)
ERR!     at loadMainConfig (/Work/node_modules/@storybook/core-common/dist/index.js:16:5697)
ERR!     at buildDevStandalone (/Work/node_modules/@storybook/core-server/dist/index.js:33:1332)
ERR!     at async withTelemetry (/Work/node_modules/@storybook/core-server/dist/index.js:33:5544)
ERR!     at async dev (/Work/node_modules/@storybook/cli/dist/generate.js:444:3268)
```

**Comment by vekunz** [comment] 2023-01-20 10:19
A while ago I created a bug for @storybook/builder-vite with the exact same error. There I also created a reproduction repo. https://github.com/storybookjs/builder-vite/issues/532

**Comment by shilman** [comment] 2023-01-23 06:11
Please try using 7.0 prerelease instead:

```
npx sb@next init
```

We've revamped Svelte/SvelteKit support in 7.0

**Comment by vekunz** [comment] 2023-01-23 10:51
With 7.0 prerelease it seems to work.

**Comment by gyenabubakar** [comment] 2023-01-23 10:52
Good to know. I'll wait for the stable version.

**Comment by ryu-man** [comment] 2023-01-23 12:58
@vekunz if you are using `ts` or want to use `ts` in your stories it will not work with 7.0 [https://github.com/storybookjs/addon-svelte-csf/issues/88](url)

**Comment by benmccann** [comment] 2023-02-07 21:17
I'm going to close this since it works in Storybook 7. Storybook for Svelte is so much improved in Svelte 7 it's hard to recommend Storybook 6 as this point

**Closed by benmccann** 2023-02-07 21:17 UTC
Labels: bug, svelte

**Comment by cybrowl** [comment] 2023-05-07 06:44
I encountered the same issue as well. Trying to migrate from 6 but after fixing a many issues along the way this one stopped me from moving forward. 

`ERR! Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports"` when importing the following line:
https://github.com/cybrowl/dsign-components-v2/blob/bugfix/tailwind-breaking-responsive-tags/.storybook/main.js#L2
 
This is the branch to repro issue: https://github.com/cybrowl/dsign-components-v2/tree/bugfix/tailwind-breaking-responsive-tags

The original problem I was trying to solve was: 
```
11:34:40 PM [vite] Internal server error: /src/lib/components/cards/ProjectCard.svelte:194:10 Semicolon or block is expected
  Plugin: vite-plugin-svelte
  File: /src/lib/components/cards/ProjectCard.svelte:194:10
   192 |    .projectCard {
   193 |      @apply relative font-sans cursor-pointer grid grid-cols-2 grid-rows-2 gap-1 text-slate-300
   194 |          lg:h-64 lg:max-h-64 2xl:h-96 2xl:max-h-96;
                    ^
   195 |    }
   196 |
```

After getting svelte, tailwindcss and other things working it seems like the issue around understanding `lg:` in tailwindcss. 

GTP suggested doing something like: 
```
import { svelte } from '@sveltejs/vite-plugin-svelte';
import postcss from 'vite-plugin-postcss';

export default {
  plugins: [
    svelte(),
    postcss({
      include: /\/src\//,
      postcssOptions: {
        plugins: [require('tailwindcss'), require('autoprefixer')],
      },
    }),
  ],
};
```
However I don't think `vite-plugin-postcss';` exists. 

My current setup with webpack works fine: https://github.com/cybrowl/dsign-components

**Comment by benmccann** [comment] 2023-05-07 12:35
You can use svelte-add to setup tailwind or PostCSS. Here's the one for tailwind: https://github.com/svelte-add/tailwindcss
