### ISSUE TITLE
Storybook 6.0 children args break if value is empty

### ISSUE THREAD

**Issue by lifeiscontent** [storybookjs/storybook#10856] opened 2020-05-21 06:33 UTC
**Describe the bug**
if I set my `children` arg to no value, the entire story breaks.

<img width="1170" alt="Screen Shot 2020-05-20 at 11 34 18 PM" src="https://user-images.githubusercontent.com/180963/82530586-7ee63280-9af2-11ea-97e6-0fa6096e2439.png">

**Comment by lifeiscontent** [comment] 2020-06-21 08:36
@shilman did this get fixed?

**Comment by shilman** [comment] 2020-06-21 23:11
Not explicitly. But maybe ... there have been lots of improvements since this was filed. Can you provide a repro in `official-storybook` for me to look at?

**Comment by cabello** [comment] 2020-09-24 13:18
Hi,

Not sure if related but I saw the following issue.

The following **works** and renders well:

```jsx
Card.args = {
  children: 'Hello',
};
```

The following **breaks**:
```jsx
Card.args = {
  children: <Paragraph>Hello</Paragraph>,
};
```

Results in:

```
Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at mapValues (webpack://storybook_docs_dll//Users/shilman/projects/baseline/storybook/node_modules/lodash/mapValues.js?:34:19)
    at inferType (http://localhost:6006/vendors~main.3ac77e73d8b04b576592.bundle.js:53680:48)
    at http://localhost:6006/vendors~main.3ac77e73d8b04b576592.bundle.js:53681:14
    at eval (webpack://storybook_docs_dll//Users/shilman/projects/baseline/storybook/node_modules/lodash/mapValues.js?:38:34)
    at eval (webpack://storybook_docs_dll//Users/shilman/projects/baseline/storybook/node_modules/lodash/_createBaseFor.js?:18:11)
    at baseForOwn (webpack://storybook_docs_dll//Users/shilman/projects/baseline/storybook/node_modules/lodash/_baseForOwn.js?:14:20)
    at mapValues (webpack://storybook_docs_dll//Users/shilman/projects/baseline/storybook/node_modules/lodash/mapValues.js?:37:3)
    at inferType (http://localhost:6006/vendors~main.3ac77e73d8b04b576592.bundle.js:53680:48)
    at http://localhost:6006/vendors~main.3ac77e73d8b04b576592.bundle.js:53681:14
    at eval (webpack://storybook_docs_dll//Users/shilman/projects/baseline/storybook/node_modules/lodash/mapValues.js?:38:34)
```

`Paragraph` in this case is a styled component:

```javascript
import styled from '@emotion/styled';

export const Paragraph = styled.p``
```

Does that help with reproduction?

🙇

**Comment by shilman** [comment] 2020-09-25 03:18
@cabello currently all arg values must be JSON-serializable values

Related: #11429 

@jonniebigodes i wonder whether there's a good documentation fix for this short term

**Comment by maxzirps** [comment] 2020-11-05 09:41
Though this works in React, this fails in Preact

```jsx
export const Multi = ({hint}) => <div>{hint}</div>

export const Template = (args) => (
  <Multi
    hint={args.hint}
  />
);

<Canvas>
  <Story name="MultiBoy" args={{ hint: <div>hello</div> }}>
    {Template.bind({})}
  </Story>
</Canvas>
```

```
RangeError: Maximum call stack size exceeded
    at http://localhost:4400/vendors~main.6a07754c95c36a1d2035.bundle.js:139985:18
    at baseForOwn (http://localhost:4400/vendors~main.6a07754c95c36a1d2035.bundle.js:137923:20)
    at mapValues (http://localhost:4400/vendors~main.6a07754c95c36a1d2035.bundle.js:144489:3)
    at inferType (http://localhost:4400/vendors~main.6a07754c95c36a1d2035.bundle.js:26122:48)
    at http://localhost:4400/vendors~main.6a07754c95c36a1d2035.bundle.js:26123:14
    at http://localhost:4400/vendors~main.6a07754c95c36a1d2035.bundle.js:144490:34
    at http://localhost:4400/vendors~main.6a07754c95c36a1d2035.bundle.js:139993:11
    at baseForOwn (http://localhost:4400/vendors~main.6a07754c95c36a1d2035.bundle.js:137923:20)
    at mapValues (http://localhost:4400/vendors~main.6a07754c95c36a1d2035.bundle.js:144489:3)
    at inferType (http://localhost:4400/vendors~main.6a07754c95c36a1d2035.bundle.js:26122:48)
```

**Comment by shilman** [comment] 2020-11-06 00:02
Arg values should be JSON serializable (ish) @maxzirps

**Comment by ghengeveld** [comment] 2021-03-18 09:24
Closing this for lack of a reproduction. I wasn't able to break Storybook by nullifying a required arg.

JSX is not supported as arg value. Use a [`mapping`](https://github.com/storybookjs/storybook/blob/next/docs/writing-stories/args.md#mapping-to-complex-arg-values) instead.

**Closed** 2021-03-18 09:24 UTC
Labels: addon: controls, app: react, args, bug, documentation, needs reproduction
