### ISSUE TITLE
Essentials: 6.3.x breaks the browser HTML inspector usage

### ISSUE THREAD

**Issue by GuillaumeAmat** [storybookjs/storybook#15426] opened 2021-06-29 19:48 UTC
**Describe the bug**

With `@storybook/addon-essentials` v6.3.x (up to v6.3.1 for now), I can't use the native HTML inspector of my browser (reproductible in Firefox and Chrome at least).

Using the contextual menu "inspect" option, or the inspector button at the top left of the dev tools, the result is always the same, it briefly selects the right element and then "goes back" to the `<div id="root">` element.

**To Reproduce**

1. `Install @storybook/addon-essentials@6.3.1`
2. Enable it in the Storybook main configuration
3. Start Storybook
4. Go to any story
5. Right click on an element and select the "Inspect" menu item

The selected element in the HTML dev tool is always `<div id="root">`

**System**

```
Environment Info:

  System:
    OS: Linux 5.12 Fedora 34 (Workstation Edition) 34 (Workstation Edition)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 14.17.1 - ~/.nvm/versions/node/v14.17.1/bin/node
    Yarn: 2.4.2 - /usr/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.1/bin/npm
  Browsers:
    Firefox: 89.0.2
  npmPackages:
    @storybook/addon-essentials: 6.2.9 => 6.2.9 
```

**Comment by shilman** [comment] 2021-06-30 02:52
Can you record a screen capture of the problem? I'm not able to reproduce

**Comment by bummzack** [comment] 2021-06-30 06:55
Similar behavior here. Whenever I open the inspector and click an element to inspect, the component gets reloaded. Not sure if it's related to my setup, which is using (among others):

- `@storybook/svelte 6.3.1`
- `@storybook/addon-svelte-csf 1.1.0`
- `@storybook/addon-essentials 6.3.1`
- `storybook-builder-vite 0.0.10`

**Comment by bummzack** [comment] 2021-06-30 08:56
Here's a screen-recording:

https://user-images.githubusercontent.com/1006185/123932313-9ba99680-d991-11eb-825f-c2d9df60b95f.mov

In the component there's a `console.log("Navigation component init");` right at the start and you can see that it gets called with almost every interaction with the inspector.

**Comment by GuillaumeAmat** [comment] 2021-06-30 09:43
Same behavior here, thanks for the screen recording @bummzack :pray: 

For the record, I'm on the React Storybook + TS

**Comment by shilman** [comment] 2021-06-30 11:16
Can you try upgrading to the latest prerelease:

```
npx sb@next upgrade --prerelease
```

Does that fix it?

**Comment by bummzack** [comment] 2021-06-30 11:32
@shilman Thanks for that! That does indeed fix the issue 🤩
I got some warnings about outdated packages in the upgrade process, but I guess these will be updated soon?

**Comment by shilman** [comment] 2021-06-30 11:50
Thanks for testing! I released the fix on `6.3.2` (or what I think is the fix). Closing this for now!

**Closed by shilman** 2021-06-30 11:50 UTC
Labels: bug, needs reproduction, needs triage

**Comment by bummzack** [comment] 2021-06-30 12:15
Can confirm that 6.3.2 also fixes the issue. Thanks a lot @shilman

**Comment by GuillaumeAmat** [comment] 2021-07-01 17:56
I confirm the fix is working too :heart: 

Thank you very much @shilman!
