### ISSUE TITLE
Document ArgsTable category/subcategory options

### ISSUE THREAD

**Issue by AndrewLeedham** [storybookjs/storybook#12710] opened 2020-10-08 20:21 UTC
**Is your feature request related to a problem? Please describe**
The category/subcategory fields for the args table are not documented.

**Describe the solution you'd like**
Documentation for the category/subcategory fields for the args table.

**Are you able to assist to bring the feature to reality?**
no

**Additional context**
The `ArgsTable` component can have sections and subsections https://storybookjs.netlify.app/official-storybook/?path=/docs/docs-argstable--sections-compact#sections-and-subsections. This can be achieved by passing an object like
```
{
  argTypes: {
  {
    someProp: {
      table: {
        category: "Section"
      }
    },
    someProp: {
      table: {
        subcategory: "Subsection"
      }
    }
  }
}
```
when creating stories. The documentation at https://storybook.js.org/docs/react/writing-docs/doc-blocks#argstable however does not show this.

**Comment by AndrewLeedham** [comment] 2020-10-08 20:23
CC: @jonniebigodes

**Comment by jonniebigodes** [comment] 2020-10-29 18:09
@AndrewLeedham thank you for bringing this to our attention. I've added a pull request to better document this feature. Hopefully it will be merged soon.

Stay safe

**Comment by jonniebigodes** [comment] 2020-12-05 16:25
Closing this as the pull request was merged and the issue is fixed. @AndrewLeedham once again thanks for bringing this to our attention. 

Stay safe

**Closed by jonniebigodes** 2020-12-05 16:25 UTC
Labels: documentation, patch
