### ISSUE TITLE
@storybook/theming brandImage 404 using manager.js

### ISSUE THREAD

**Issue by ericberens** [storybookjs/storybook#10055] opened 2020-03-05 01:13 UTC
**Describe the bug**

`brandImage` results in `GET https://localhost:8009/static/media/logo.63592a43.png 404 (Not Found)` using a `manager.js` config.

**To Reproduce**
1. Run storybook (using `start-storybook -c .storybook -p 8009`)
2. See `brandImage` not rendered properly and a 404 in the Network panel

**Expected behavior**

The `brandImage` should load and render properly when using a `manager.js` config file and a custom theme.

**Screenshots**

![Screen Shot 2020-03-04 at 7 48 09 PM](https://user-images.githubusercontent.com/612154/75936801-343d0e80-5e51-11ea-8a8c-a8abe60ae703.png)

**Code snippets**

```
import logo from './static/images/logo.png';
import { addons } from "@storybook/addons";
import { create } from "@storybook/theming/create";

addons.setConfig({
  theme: create({
    // Base theme
    base: 'light',

    // Custom branding
    brandImage: logo,
    brandTitle: 'BRAND TITLE,
    brandUrl: undefined
  })
});
```

**System:**

```
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.17.3 - ~/Projects/web/node_modules/.bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
  Browsers:
    Chrome: 80.0.3987.122
    Firefox: 72.0.1
    Safari: 13.0.5
  npmPackages:
    @storybook/addon-a11y: 5.3.14 => 5.3.14 
    @storybook/addon-actions: 5.3.14 => 5.3.14 
    @storybook/addon-backgrounds: 5.3.14 => 5.3.14 
    @storybook/addon-events: 5.3.14 => 5.3.14 
    @storybook/addon-info: 5.3.14 => 5.3.14 
    @storybook/addon-knobs: 5.3.14 => 5.3.14 
    @storybook/addon-links: 5.3.14 => 5.3.14 
    @storybook/addon-notes: 5.3.14 => 5.3.14 
    @storybook/addon-viewport: 5.3.14 => 5.3.14 
    @storybook/addons: 5.3.14 => 5.3.14 
    @storybook/client-logger: 5.3.14 => 5.3.14 
    @storybook/core: 5.3.14 => 5.3.14 
    @storybook/core-events: 5.3.14 => 5.3.14 
    @storybook/react: 5.3.14 => 5.3.14 
    @storybook/theming: 5.3.14 => 5.3.14 
```

**Additional context**

The same package and theme setup using a `config.js` works as expected.

Additionally, I've seen https://github.com/storybookjs/storybook/issues/5878 but I am not using an SVG. Using a hosted image (e.g. `https://placehold.it/350x150`) works as expected.

**Comment by ericberens** [comment] 2020-03-05 01:20
Possibly a duplicate of https://github.com/storybookjs/storybook/issues/9443

**Comment by shilman** [comment] 2020-03-05 07:37
Yeah, looks like a duplicate of #9443. Can you try upgrading to 6.0.0-alpha and verify that it's fixed for you?

**Closed** 2020-03-05 07:37 UTC
Labels: bug, configuration
