### ISSUE TITLE
Incorrect warning "no files matching any of the following globs"

### ISSUE THREAD

**Issue by graup** [storybookjs/storybook#10822] opened 2020-05-18 15:42 UTC
**Describe the bug**

When running storybook build, this warning is printed:

```
WARN We found no files matching any of the following globs:
WARN
WARN ../src/stories/**/*.stories.(js|mdx)
```

However, everything works! Stories are loaded properly. So, it seems the warning is just incorrect.

**To Reproduce**

Version: next @ 4b7c1a4

1. `cd examples/vue-kitchen-sink`
2. `yarn storybook`

**Comment by ksaturnius** [comment] 2020-05-19 01:59
When testing the migration of a Vue-based monorepo (Yarn/Lerna) project based on feedback in #10817, I am also running into this same warning:
```
WARN We found no files matching any of the following globs:
WARN
WARN ../components/**/*.stories.(js|mdx)
WARN ../lib/**/*.stories.mdx
```

However, none of my stories are loading :/

**Comment by ndelangen** [comment] 2020-05-19 15:17
I think @yannbf was working on a fix for this?

**Comment by yannbf** [comment] 2020-05-21 15:52
Hey everyone, this is a duplicate of #10772. A fix is on the way, it just needs to be further discussed! 🙆‍♀️

**Closed** 2020-05-22 00:57 UTC
Labels: bug, core
