### ISSUE TITLE
[Bug]: Tables not working in MDX2

### ISSUE THREAD

**Issue by jwerre** [storybookjs/storybook#20334] opened 2022-12-19 22:14 UTC
### Describe the bug

In Storybook 7 I've installed `remarkGfm` and added it to my `addons` in `.storybook/main.js` then added some table markdown to the main documentation MDX for my stories. The table is not parsed correctly.

### To Reproduce

```shell
https://github.com/jwerre/sb-table-issue
```

### System

```shell
Environment Info:

  System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    npm: 8.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 107.0
    Safari: 16.1
  npmPackages:
    @storybook/addon-docs: ^7.0.0-beta.12 => 7.0.0-beta.12 
    @storybook/addon-essentials: ^7.0.0-beta.12 => 7.0.0-beta.12 
    @storybook/addon-interactions: ^7.0.0-beta.12 => 7.0.0-beta.12 
    @storybook/addon-links: ^7.0.0-beta.12 => 7.0.0-beta.12 
    @storybook/blocks: ^7.0.0-beta.12 => 7.0.0-beta.12 
    @storybook/svelte: ^7.0.0-beta.12 => 7.0.0-beta.12 
    @storybook/sveltekit: ^7.0.0-beta.12 => 7.0.0-beta.12 
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

**Comment by joshwooding** [comment] 2023-01-03 16:12
Hey, thanks for the report. This should be fixed when https://github.com/storybookjs/storybook/pull/20116 is compled

**Comment by shilman** [comment] 2023-01-20 11:30
Will be fixed by https://github.com/storybookjs/storybook/issues/20091

**Comment by ndelangen** [comment] 2023-01-24 14:26
I'll close this issue, as a duplicate of the one @shilman mentioned https://github.com/storybookjs/storybook/issues/20091

**Closed by ndelangen** 2023-01-24 14:26 UTC
Labels: bug, mdx, vite
