### ISSUE TITLE
The api setQueryParams not working

### ISSUE THREAD

**Issue by echoulen** [storybookjs/storybook#8600] opened 2019-10-29 04:01 UTC
**Describe the bug**
The method `api.setQueryParams` not working

**To Reproduce**
```
addons.register("storybook/something", (api) => {
  api.setQueryParams({abc: "hello"});
});
```

**Expected behavior**
expect api.getQueryParam("abc") to be "hello"

**Screenshots**
![Screen Shot 2019-10-29 at 11 58 34 AM](https://user-images.githubusercontent.com/6993621/67736695-80131d80-fa43-11e9-8414-14ce0a37f3b6.png)

**Code snippets**
![Screen Shot 2019-10-29 at 11 57 30 AM](https://user-images.githubusercontent.com/6993621/67736688-7b4e6980-fa43-11e9-99fc-ded4cd675938.png)

**System:**
```
"@storybook/addons": "^5.2.0",
"@storybook/react": "^5.2.0",
```

**Additional context**
The addon was not working with `api.setQueryParams` and `api.getQueryParam` any more
https://github.com/echoulen/storybook-addon-styled-component-theme

**Comment by GeorgeTaveras1231** [comment] 2019-12-16 14:08
This is a duplicate of

#5533

**Comment by alexreardon** [comment] 2020-04-02 00:28
I can confirm that this API is not working

**Comment by alexreardon** [comment] 2020-04-02 00:28
```
"@storybook/react": "6.0.0-alpha.30"
```

**Comment by alexreardon** [comment] 2020-04-02 00:38
This line is clearing the query string: https://github.com/storybookjs/storybook/blob/b6136e1539c85d253504391a7d3f65e2c1239143/lib/api/src/modules/url.ts#L93

**Comment by ndelangen** [comment] 2020-04-02 12:31
The queryParam is for the preview, not the manager.

`storybook/lib/api` is code that only runs on the manager.

**Comment by alexreardon** [comment] 2020-04-02 21:21
So is there a way from my addon panel to set something in the query string? I am using the API in the same way as it is being used in the docs: https://storybook.js.org/docs/addons/api/#apisetqueryparams

**Comment by ndelangen** [comment] 2020-04-03 08:14
Why would you need to set something on the query of storybook's manager?

**Comment by echoulen** [comment] 2020-04-03 15:32
Hi @ndelangen 
For my example, I have to set the active tab in my addon form query params if the user refresh the page

**Comment by ndelangen** [comment] 2020-04-03 17:27
For refreshes you could use the localStorage instead?

**Comment by echoulen** [comment] 2020-04-04 02:33
the route trigger enable tab is more make sense, I had used this API a long time ago, it's was broken after I upgrade the storybook, so that's why I report the issue.

**Comment by ndelangen** [comment] 2020-04-06 08:45
@echoulen you're 100% correct. The API used to set queries on the manager as well, but when we changed to use a router we removed this behavior so we could have clearer/readable URLs that wouldn't grow to be too long.

**Comment by alexreardon** [comment] 2020-04-06 08:48
I would like to be able to set the URL for sharing purposes. Right now I am unable to do anything to the URL as an addon as it is always cleared

**Comment by ndelangen** [comment] 2020-04-06 08:51
I agree that'd be useful

**Comment by echoulen** [comment] 2020-04-06 11:11
@ndelangen I see

**Comment by ndelangen** [comment] 2023-01-17 16:47
I think this problem has in essence been resolved by making globals persist on the URL:
https://storybook.js.org/docs/react/essentials/toolbars-and-globals#globals

**Closed by ndelangen** 2023-01-17 16:47 UTC
Labels: question / support, api: addons, todo
