### ISSUE TITLE
[Bug]: Brand new SvelteKit setup does not work

### ISSUE THREAD

**Issue by fkrauthan** [storybookjs/storybook#20193] opened 2022-12-10 07:23 UTC
### Describe the bug

I've created a brand new svelte kit project and then added the latest storybook beta (`7.0.0-beta.3`) to the project. The generated `main.cjs` looks like this:

```
const path = require('path');
module.exports = {
  "stories": [
    "../src/**/*.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions"
  ],
  "framework": {
    "name": "@storybook/sveltekit",
    "options": {}
  },
  "docs": {
    "docsPage": true
  }
}
```

But when running storybook and trying to access the example Button story I get the following error:

```
/src/stories/Button.svelte:28:1 The keyword 'let' is reserved
11:16:50 p.m. [vite] Internal server error: /src/stories/Button.svelte:28:1 The keyword 'let' is reserved
  Plugin: vite-plugin-svelte
  File: /src/stories/Button.svelte:28:1
   26 |
   27 |  function create_fragment(ctx) {
   28 |    let button;
           ^
   29 |    let t;
   30 |    let button_class_value;
```

### To Reproduce

```shell
Create a new svelte kit project and then add the latest sb beta to the project.

1. `pnpm create svelte@latest my-app`
2. `cd ./my-app`
3. `pnpm dlx sb@next init`

Then when starting storybook open the example `Button` story and you get the compile error.
```

### System

```shell
Environment Info:

  System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
  Binaries:
    Node: 18.12.1 - ~\AppData\Local\Volta\tools\image\node\18.12.1\node.EXE
    Yarn: 1.22.18 - ~\AppData\Local\Volta\tools\image\yarn\1.22.18\bin\yarn.CMD
    npm: 8.19.2 - ~\AppData\Local\Volta\tools\image\node\18.12.1\npm.CMD
  Browsers:
    Chrome: 108.0.5359.99
    Edge: Spartan (44.22621.819.0), Chromium (108.0.1462.42)
```
```


### Additional context

_No response_

**Comment by JReinhold** [comment] 2022-12-10 21:59
I can reproduce this.

I've narrowed it down to the bug being caused by the changes in [`@sveltejs/kit@1.0.0-next.576`](https://github.com/sveltejs/kit/releases/tag/%40sveltejs%2Fkit%401.0.0-next.576), which changed SvelteKit's plugins to being async.

This means that when `@storybook/svelte-vite` checks for the existence of `vite-plugin-svelte` [here](https://github.com/storybookjs/storybook/blob/next/code/frameworks/svelte-vite/src/preset.ts#L21) it won't find it because it doesn't look for async plugins, and so `vite-plugin-svelte` will be added twice.

I've confirmed that it works again when removing the second `vite-plugin-svelte` manually via `viteFinal` in `main.cjs`:

```ts
viteFinal: async (config) => {
	// 10th plugin is Svelte from @storybook/sveltekit
	config.plugins.splice(9, 1);
	return config;
},
```

**Comment by shilman** [comment] 2022-12-13 15:32
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.5 containing PR #20194 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2022-12-13 15:32 UTC
Labels: bug, app: svelte, linear
