### ISSUE TITLE
Angular component without selector breaks story

### ISSUE THREAD

**Issue by literalpie** [storybookjs/storybook#13769] opened 2021-01-29 17:51 UTC
**Describe the bug**
Attempting to use storybook with an Angular component that does not have a selector results in the following error
```
'undefined' is not a known element:
1. If 'undefined' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (\"[ERROR ->]<undefined [primary]=\"primary\" [size]=\"size\" [label]=\"label\" (onClick)=\"onClick($event)\"></undefined>\"): ng:///StorybookModule/StorybookWrapperComponent.html@0:0"
```

**To Reproduce**

1. In any Angular Storybook project, create documentation that uses an angular component without a selector. Like [this example project](https://github.com/literalpie/storybook-angular-no-selector-bug/blob/master/src/stories/button.component.ts#L5)
2. Serve the storybook documentation, navigate to the component without a selector
4. Notice the story does not load, and see error in browser console

**Expected behavior**
The story should load :-) in sb 6.1.X, things work fine. This is only a problem in 6.2.0-alpha.X

**Code snippets**
```
@Component({
  // uncomment this to fix error:
  // selector: 'storybook-button',
  template: ` <button>
    {{ label }}
  </button>`,
})
export default class ButtonComponent { }
```

This is not an issue if you include the selector or create the story like this:
```
export const button: Story = (args) => ({
  template: `
    <button>
    {{ label }}
  </button>`,
});
```
**System**
Environment Info:
  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
  Browsers:
    Chrome: 88.0.4324.96
    Firefox: 84.0.1
    Safari: 14.0.2
  npmPackages:
    @storybook/addon-actions: ^6.2.0-alpha.19 => 6.2.0-alpha.19 
    @storybook/addon-essentials: ^6.2.0-alpha.19 => 6.2.0-alpha.19 
    @storybook/addon-links: ^6.2.0-alpha.19 => 6.2.0-alpha.19 
    @storybook/angular: ^6.2.0-alpha.19 => 6.2.0-alpha.19 
  npmGlobalPackages:
    @storybook/cli: 3.4.10

**Additional context**
[This code](https://github.com/storybookjs/storybook/blob/e9cb0441174291c631e13ba8acc687524aac62e8/app/angular/src/client/preview/angular-beta/ComputesTemplateFromComponent.ts#L53) is probably the culprit

**Comment by zbream** [comment] 2021-01-29 19:20
It's worth noting that components without selectors typically render as `ng-component` ([as seen in this example](https://stackblitz.com/edit/angular-no-selectors?file=src/app/app.component.html)), and Storybook's previous Angular renderer took care of this.

**Comment by shilman** [comment] 2021-02-01 02:45
Looks like this is an issue with the new renderer @ThibaudAV. Can you take a look?

**Comment by ThibaudAV** [comment] 2021-02-01 20:21
hum yes exactly it is a regression compared to 6.1

for the moment you can go back to the rendering engine using in 6.1 with: 
```js
button.parameters = { angularLegacyRendering: true };
```

but we need to fix this in the new angular renderer

**Comment by ThibaudAV** [comment] 2021-02-13 10:02
@literalpie @zbream Can you describe to me more precisely your use case ? (to make stories for these components without selector?) 🙏 

More precisely how do you send dynamic data to these stories? with a provider? 
Input Output is not possible, it seems to me?

do you use story `props` to override the properties of these components? 

I currently have a patch that allows storybook to simulate the use of this component with an `*ngComponentOutlet`.
but I need to clarify if the props need to modify the internal properties of the component. :/
In my opinion this is not a good practice.
And it would be better for the user to make a component that wraps this kind of component. In the same way that it will be used at the end 🤔

**Comment by literalpie** [comment] 2021-02-15 17:31
I think the most relevant use-case we have is components that involve multiple pieces, nested inside each other (similar to the [material input/form field](https://material.angular.io/components/form-field/examples)). These components do have inputs (like the disabled input in the form field) which we set using `props`. Using the `template` value would work, but in multiple places, we do this using a component without a selector. I think this is similar to what you mean by "make a component that wraps this kind of component...".

We also have some other stories with components that include multiple copies of the component being demoed. We're trying to move away from this pattern, but these contributed to the number of story components we have without selectors. None of these use props.

In all, we had about 30 story components that needed to have a selector added to work with the alpha. I think about 1/3 of them make use of props.

**Comment by ThibaudAV** [comment] 2021-02-17 15:56
@literalpie can you 👀  this PR https://github.com/storybookjs/storybook/pull/13939 ? would this correspond to your use case?

**Comment by shilman** [comment] 2021-02-20 13:55
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.31 containing PR #13939 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2021-02-20 13:55 UTC
Labels: app: angular, bug, has workaround
