### ISSUE TITLE
[Bug]: Compatibility with NEXTJS 15

### ISSUE THREAD

**Issue by DanielGBullido** [storybookjs/storybook#29554] opened 2024-11-06 08:25 UTC
### Describe the bug

When try to install or update storybook using NEXTJS 15 obtain this error:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: svd-website@undefined
npm ERR! Found: next@15.0.2
npm ERR! node_modules/next
npm ERR!   next@"15.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^13.5.0 || ^14.0.0" from @storybook/nextjs@8.4.2
npm ERR! node_modules/@storybook/nextjs
npm ERR!   dev @storybook/nextjs@"^8.4.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/****/.npm/_logs/2024-11-06T07_54_08_371Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/***/.npm/_logs/2024-11-06T07_54_08_371Z-debug-0.log

### Reproduction link

https://storybook.js.org/docs/get-started/frameworks/nextjs?renderer=react

### Reproduction steps

create a project on nextjs 15 and run npx storybook@latest init or npx storybook@latest upgrade on existing project

### System

Storybook Environment Info:

  System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M2
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - /usr/local/bin/node
    npm: 10.2.4 - /usr/local/bin/npm <----- active
  Browsers:
    Safari: 17.5
  npmPackages:
    @storybook/addon-actions: 8.4.2 => 8.4.2 
    @storybook/addon-controls: 8.4.2 => 8.4.2 
    @storybook/addon-docs: 8.4.2 => 8.4.2 
    @storybook/addon-mdx-gfm: 8.4.2 => 8.4.2 
    @storybook/addon-postcss: 2.0.0 => 2.0.0 
    @storybook/addon-viewport: 8.4.2 => 8.4.2 
    @storybook/addon-webpack5-compiler-swc: 1.0.5 => 1.0.5 
    @storybook/react: 8.4.2 => 8.4.2 
    eslint-plugin-storybook: 0.11.0 => 0.11.0 
    storybook-react-intl: 3.1.1 => 3.1.1

**Comment by valentinpalkovic** [comment] 2024-11-06 12:13
Duplicate of https://github.com/storybookjs/storybook/issues/29421

**Closed by valentinpalkovic** 2024-11-06 12:13 UTC
Labels: bug, needs triage
