### ISSUE TITLE
Uncaught Error: Singleton client API not yet initialized, cannot call `addParameters`.

### ISSUE THREAD

**Issue by suhaotian** [storybookjs/storybook#16914] opened 2021-12-06 05:07 UTC
**Describe the bug**
![2021-12-06 at 12 59 PM](https://user-images.githubusercontent.com/6512574/144789902-33121432-d801-46ee-8c54-23f7a6036aec.png)

**To Reproduce**

Repo: https://github.com/suhaotian/storybook-rnw-monorepo/

```bash
# clone and checkout 
git clone https://github.com/suhaotian/storybook-rnw-monorepo.git
git checkout reproduce
# install use yarn
yarn
# run storybook
yarn dev:storybook:react
```

then open developer console: 

```
Uncaught Error: Singleton client API not yet initialized, cannot call `addParameters`.
```

**System**
```
Environment Info:

  System:
    OS: macOS 11.4
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 96.0.4664.55
    Safari: 14.1.1
```

**Comment by shilman** [comment] 2021-12-06 10:33
I think it's coming from a mixture of Storybook versions 6.3 and 6.4. You should use one or the other. cc @dannyhw 

```
@shilman ➜ /workspaces/storybook-rnw-monorepo (reproduce ✗) $ yarn list | grep storybook
├─ @expo-next-monorepo-example/storybook-react-native@1.0.0
│  ├─ @storybook/addon-actions@^6.3.12
│  ├─ @storybook/addon-controls@^6.3.12
│  ├─ @storybook/addon-ondevice-actions@^6.0.1-alpha.6
│  ├─ @storybook/addon-ondevice-backgrounds@^6.0.1-alpha.6
│  ├─ @storybook/addon-ondevice-controls@^6.0.1-alpha.6
│  ├─ @storybook/addon-ondevice-notes@^6.0.1-alpha.6
│  ├─ @storybook/react-native@^6.0.1-alpha.6
├─ @expo-next-monorepo-example/storybook-react@1.0.0
│  ├─ @storybook/addon-actions@^6.4.7
│  ├─ @storybook/addon-essentials@^6.4.7
│  ├─ @storybook/addon-links@^6.4.7
│  ├─ @storybook/addon-react-native-web@0.0.14
│  ├─ @storybook/builder-webpack5@^6.4.7
│  ├─ @storybook/manager-webpack5@^6.4.7
│  ├─ @storybook/react@^6.4.7
```

**Comment by dannyhw** [comment] 2021-12-06 10:53
Yeah seems likely due to the client api and store changes.

Also currently storybook/react-native is not compatible with 6.4 so you will need to use 6.3 if you need to use the ondevice storybook.
@storybook/react-native@^6.0.1-alpha.6

**Comment by suhaotian** [comment] 2021-12-06 12:08
Hi, I didn't try the storybook with react-native on the device. I try this monorepo: 

![2021-12-06 at 8 07 PM](https://user-images.githubusercontent.com/6512574/144843436-3942a5d4-4e0a-402a-a60e-1086a62d221f.png)

it's use the `react-native-web`

**Comment by suhaotian** [comment] 2021-12-06 12:16
And even I downgrade `react-native` in the `expo` and `storybook-react-native` version to 0.63, still same error

**Comment by dannyhw** [comment] 2021-12-06 12:23
Yes I understand, it was just a note because I noticed it in the Repo.

The problem is that in a monorepo like this having multiple versions of storybook can cause yarn to resolve incorrect versions in the workspace.

Not sure if that is the problem but If it's causing issues you might need to use nohoist in the react native part or just remove it.

**Comment by suhaotian** [comment] 2021-12-06 13:32
I follow this issue, https://github.com/storybookjs/storybook/issues/16097

I downgrade to `6.3.12` it works now.

![2021-12-06 at 9 30 PM](https://user-images.githubusercontent.com/6512574/144854708-386fd10f-54d4-43b1-8278-ce6eb9ee81e0.png)

![2021-12-06 at 9 31 PM](https://user-images.githubusercontent.com/6512574/144854806-9d00deb9-dd01-44d1-a166-0080cbf1273b.png)

**Comment by suhaotian** [comment] 2021-12-06 13:32
Don't know what happend with the latest version

**Comment by dannyhw** [comment] 2021-12-06 14:51
> Don't know what happend with the latest version

From what @shilman said it looks like some of your add-ons were being installed with 6.3 instead of 6.4.

They most likely won't work like that since a lot changed between 6.3 and 6.4 in terms of the internal APIs.

**Comment by francoisromain** [comment] 2022-03-09 08:14
same error here with the following: 

```
    "@storybook/addon-docs": "^6.5.0-alpha.46",
    "@storybook/addon-essentials": "^6.5.0-alpha.46",
    "@storybook/addon-links": "^6.5.0-alpha.46",
    "@storybook/addon-svelte-csf": "^1.1.0",
    "@storybook/svelte": "^6.5.0-alpha.46",
    "storybook-builder-vite": "^0.1.18",
```

**Comment by dennisat** [comment] 2022-03-11 14:50
Same with latest official
```
    "@storybook/addon-controls": "^6.4.19",
    "@storybook/addon-essentials": "^6.4.19",
    "@storybook/addon-knobs": "^6.3.1",
    "@storybook/react": "^6.4.19",
```

**Comment by dannyhw** [comment] 2022-03-11 14:55
@dennisat this issue refers to using mismatched versions breaking functionality. So upgrading to newer versions won't fix it. The only way to fix this is to either update every package to 6.4+ or downgrade everything to 6.3. In your case you are using knobs ^6.3. There is a 6.4 version of knobs so you could try upgrading to that.

**Comment by dennisat** [comment] 2022-03-14 10:30
Thanks for your reply @dannyhw.

Tried to bump the knobs as well and still get this error.

Versions:
```
    "@storybook/addon-controls": "^6.4.19",
    "@storybook/addon-essentials": "^6.4.19",
    "@storybook/addon-knobs": "^6.4.0",
    "@storybook/react": "^6.4.19",
```

**Comment by dannyhw** [comment] 2022-03-14 10:33
If you are able to provide a public repo with a reproduction of the problem I'd be happy to debug it. Though in general I think this problem only occurs due to some mismatch in versions unless your error is a different one.

**Comment by dennisat** [comment] 2022-03-14 13:12
In a clean repo, it works.
Also, something that I noticed is that this error occurred even if there are no stories at all.

**Comment by IanVS** [comment] 2022-03-14 15:17
@dennisat if you're still having issues in your original repo, try removing your yarn.lock or package-lock.json file, or remove the carets to force all `@storybook/*` packages to be the exact same version.

```
    "@storybook/addon-controls": "6.4.19",
    "@storybook/addon-essentials": "6.4.19",
    "@storybook/addon-knobs": "6.4.19",
    "@storybook/react": "6.4.19",
```

**Comment by dennisat** [comment] 2022-03-21 11:57
@IanVS the latest of the `@storybook/addon-knobs` is `6.4.0` and still has the same runtime issue.
_I have removed the carets_

This is what I have 
```
    "@storybook/addon-controls": "6.4.19",
    "@storybook/addon-essentials": "6.4.19",
    "@storybook/addon-knobs": "^6.4.0",
    "@storybook/react": "6.4.19",
```

**Comment by IanVS** [comment] 2022-03-21 12:57
Ah, then if you want to use `addon-knobs` (which is deprecated, controls are the new way to accomplish the same thing), you'd need to pin all the rest of your storybook versions to `6.4.0` as well.  See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-addon-knobs for the migration guide for knobs -> controls.

**Comment by mokone91** [comment] 2022-07-22 10:11
Hi! faced with the same error when migrated repository to pnpm.
npm + lerna bootrarap -> pnpm only

```
bootstrap:27 Uncaught Error: Singleton client API not yet initialized, cannot call `addParameters`.
    at checkMethod (ClientApi.js:89:1)
    at addParameters (ClientApi.js:104:1)
    at config-generated-config-entry.js:40:1
    at Array.forEach (<anonymous>)
    at ../../node_modules/.pnpm/@storybook+vue@6.5.9_456i7442nvtdpmjd35ogmb6aje/node_modules/@storybook/vue/dist/esm/client/preview/config-generated-config-entry.js (config-generated-config-entry.js:10:1)
    at __webpack_require__ (bootstrap:24:1)
    at __webpack_exec__ (generated-stories-entry.cjs:6:1)
    at generated-stories-entry.cjs:6:1
    at __webpack_require__.O (chunk loaded:23:1)
    at generated-stories-entry.cjs:6:1
```
Storybook 6.5.9

**Comment by targeral** [comment] 2022-07-27 15:22
I'm having this problem too, but I found it when adding `sideEffects` to package.json.Remove the `sideEffect` and it will work again.

**package.json**
``` json
{
    "sideEffects": []
}
```

I found this problem while researching [storybook-module-federation](https://github.com/robdonn/storybook-module-federation). If you want to reproduce the problem, you can try it in the examples directory under this repository.

[storybook-module-federation examples](https://github.com/robdonn/storybook-module-federation/tree/main/examples)

I wish I knew why this was happening. @shilman

**Comment by seekersIsMe** [comment] 2022-08-18 02:23
> 你好！将存储库迁移到 pnpm 时遇到相同的错误。 npm + lerna bootstrap -> 仅 pnpm
> 
> ```
> bootstrap:27 Uncaught Error: Singleton client API not yet initialized, cannot call `addParameters`.
>     at checkMethod (ClientApi.js:89:1)
>     at addParameters (ClientApi.js:104:1)
>     at config-generated-config-entry.js:40:1
>     at Array.forEach (<anonymous>)
>     at ../../node_modules/.pnpm/@storybook+vue@6.5.9_456i7442nvtdpmjd35ogmb6aje/node_modules/@storybook/vue/dist/esm/client/preview/config-generated-config-entry.js (config-generated-config-entry.js:10:1)
>     at __webpack_require__ (bootstrap:24:1)
>     at __webpack_exec__ (generated-stories-entry.cjs:6:1)
>     at generated-stories-entry.cjs:6:1
>     at __webpack_require__.O (chunk loaded:23:1)
>     at generated-stories-entry.cjs:6:1
> ```
> 
> 故事书 6.5.9 <img alt="图片" width="478" src="https://user-images.githubusercontent.com/2384641/180418504-d9bc4e47-cd45-416b-a5cd-d07eaf6fe8bd.png">



> Hi! faced with the same error when migrated repository to pnpm. npm + lerna bootstrap -> pnpm only
> 
> ```
> bootstrap:27 Uncaught Error: Singleton client API not yet initialized, cannot call `addParameters`.
>     at checkMethod (ClientApi.js:89:1)
>     at addParameters (ClientApi.js:104:1)
>     at config-generated-config-entry.js:40:1
>     at Array.forEach (<anonymous>)
>     at ../../node_modules/.pnpm/@storybook+vue@6.5.9_456i7442nvtdpmjd35ogmb6aje/node_modules/@storybook/vue/dist/esm/client/preview/config-generated-config-entry.js (config-generated-config-entry.js:10:1)
>     at __webpack_require__ (bootstrap:24:1)
>     at __webpack_exec__ (generated-stories-entry.cjs:6:1)
>     at generated-stories-entry.cjs:6:1
>     at __webpack_require__.O (chunk loaded:23:1)
>     at generated-stories-entry.cjs:6:1
> ```
> 
> Storybook 6.5.9 <img alt="image" width="478" src="https://user-images.githubusercontent.com/2384641/180418504-d9bc4e47-cd45-416b-a5cd-d07eaf6fe8bd.png">



> Hi! faced with the same error when migrated repository to pnpm. npm + lerna bootstrap -> pnpm only
> 
> ```
> bootstrap:27 Uncaught Error: Singleton client API not yet initialized, cannot call `addParameters`.
>     at checkMethod (ClientApi.js:89:1)
>     at addParameters (ClientApi.js:104:1)
>     at config-generated-config-entry.js:40:1
>     at Array.forEach (<anonymous>)
>     at ../../node_modules/.pnpm/@storybook+vue@6.5.9_456i7442nvtdpmjd35ogmb6aje/node_modules/@storybook/vue/dist/esm/client/preview/config-generated-config-entry.js (config-generated-config-entry.js:10:1)
>     at __webpack_require__ (bootstrap:24:1)
>     at __webpack_exec__ (generated-stories-entry.cjs:6:1)
>     at generated-stories-entry.cjs:6:1
>     at __webpack_require__.O (chunk loaded:23:1)
>     at generated-stories-entry.cjs:6:1
> ```
> 
> Storybook 6.5.9 <img alt="image" width="478" src="https://user-images.githubusercontent.com/2384641/180418504-d9bc4e47-cd45-416b-a5cd-d07eaf6fe8bd.png">

me too!  version is 6.5.10 or 6.5.9, But there's still this problem.

**Comment by tbtommyb** [comment] 2022-10-07 14:53
I have encountered this bug on several different versions (6.3.12, 6.5.10, 6.5.12 all with versions matching across storybook versions).

From debugging, what happens in my case is that `dist/cjs/ClientApi.js` runs, sets up the singleton etc. Then when I see the same exception as above, it's in `dist/esm/ClientApi.js`. The ESM file does not run the `ClientApi` constructor and so the singleton is uninitialised in that file.

Is it normal/supported that both `cjs` and `esm` files are used, or is there a problem in my Webpack config? My project uses ESM so I would prefer to have everything use ESM if possible.

**Comment by IanVS** [comment] 2022-10-07 15:01
@tbtommyb I'd suggest trying to delete your node_modules and lock file (`yarn.lock` or `package-lock.json`), and re-installing.  Sometimes a storybook version can get out-of-date and reinstalling fresh can fix it.

As for ESM vs CJS, storybook runs in two contexts: node and the browser.  Some packages only run in one or the other, and so the files can point to cjs for node and esm for browser.

**Comment by tbtommyb** [comment] 2022-10-07 15:38
Hi @IanVS thank you for the suggestion, though I have tried that a few times with no luck. The fact that it's persisted across different versions makes me think it is related to webpack.

So if I want Storybook to run in the browser, should it be ok that the`start-storybook` script runs as CJS module and then ESM later runs? Or should I be trying to force `main.ts` to be an ESM module?

**Comment by IanVS** [comment] 2022-10-07 15:44
`main.ts` is run in node, before storybook starts up the browser.  I'm not super familiar with webpack anymore (I help to maintain the vite integration for storybook), so I'm not sure the best way to be sure that the ESM code is being used when appropriate.

**Comment by tbtommyb** [comment] 2022-10-07 19:38
I found the problem and am leaving this note in case it helps anyone in future. In my case, I was trying to combine the Storybook webpack config with my own. My webpack config used `ts-loader` to handle the Typescript. I removed that plugin and relied on Storybook's built-in `babel-loader`.

I'm not sure why using `ts-loader` caused the problem, but it was obviously wasteful to use two loaders anyway. If you have this problem, my advice would be to start with the config you get from `webpackFinal`, verify that the introduction page loads and then gradually add in the webpack configuration fields you need.

I also found that sometimes Storybook did not pick up changes to my configuration (e.g. after reverting a change that broke the build, my build was still broken). If you are working on the configuration, I recommend clearing `node_modules/.cache/storybook` after every change to make sure you're seeing fresh builds.

**Comment by IanVS** [comment] 2022-12-30 04:23
This issue can happen due to misconfigurations or mismatches between storybook versions in your node_modules.  If you encounter this issue, check through the comments above, and try regenerating your lock file.  If you think you've found a bug in storybook itself after trying all this, please open a new issue with all the details you can, along with a reproduction.

**Closed by IanVS** 2022-12-30 04:23 UTC
Labels: question / support, has workaround
