### ISSUE TITLE
Addon Controls Date Picker Fails If Currrent Day Is Not Available In Month

### ISSUE THREAD

**Issue by kev-hoang** [storybookjs/storybook#13771] opened 2021-01-29 19:34 UTC
**Describe the bug**
If the current day of the month the user is in is not available in the target month in the controls date picker, then it would not allow you to select the month. I noticed that the date picker was working fine yesterday (1/28) when I need to select 2/5 for the view and then today (1/29) when I try to select 2/5 it would automatically switch to 3/5.

**To Reproduce**

1. Add date picker control
2. Go to ui with date picker
3. Select a month where the current day of the month is not available. So if day of month is 30, try to select a date in February. If day of month is 31, try to select any month that only has 30 days.
4. It will automatically change the month to the next month. i.e. February -> March

**Expected behavior**
To be able to select the date you want regardless of the day of the month you are using Storybook.

**Screenshots**

When changing the month from January to February, input is already on March 28th,
<img width="508" alt="Screen Shot 2021-01-29 at 2 29 12 PM" src="https://user-images.githubusercontent.com/12387616/106318853-88599a00-623e-11eb-8ca0-6dd9972a72ec.png">

After trying to select February 11th and seeing March 11th. I clicked into the calendar again and went to February 11th.
<img width="551" alt="Screen Shot 2021-01-29 at 2 29 32 PM" src="https://user-images.githubusercontent.com/12387616/106319076-e1c1c900-623e-11eb-8b3f-4881dfe7655d.png">

Now that the input has changed, I thought it would work, but the args.date that is received is still March 11th.
<img width="479" alt="Screen Shot 2021-01-29 at 2 29 49 PM" src="https://user-images.githubusercontent.com/12387616/106319152-faca7a00-623e-11eb-96b2-e9b59cb16dfd.png">

**Comment by rajanlagah** [comment] 2021-02-02 14:11
Can we reproduce this on any date or we have to wait for almost 2 months ?

**Comment by kev-hoang** [comment] 2021-02-04 18:31
You'd have to wait until the next 30th day of the calendar month at least, unless you can spoof your browser date.

**Comment by pahan35** [comment] 2021-11-30 16:24
Is this issue fixed by #14348 ?

**Comment by shilman** [comment] 2021-11-30 16:35
@pahan35 looks like it! closing this for now -- please let me know if it's still broken in 6.3 or higher

**Closed by shilman** 2021-11-30 16:35 UTC
Labels: bug, good first issue, help wanted, addon: controls, P3
