### ISSUE TITLE
Make PropTypes.oneOf work with dynamic values in controls

### ISSUE THREAD

**Issue by EloB** [storybookjs/storybook#12798] opened 2020-10-16 17:31 UTC
**Is your feature request related to a problem? Please describe**
Right now select elements shows wrong options for me in controls when using `PropTypes.oneOf` combined with `Object.keys(something)`. See image in bottom of the page.

**Describe the solution you'd like**
I saw that it wasn't easy to get the values from `prop-types`. I provided a hacky way todo it. I don't think it's possible without this kind of hack. I think this could be integrated into controls. As I understand is that you guys read the file as text to extract prop types? I haven't read your codebase but some really weird things were showing while I tried different things.

```js
import PropTypes from 'prop-types';

const escapeRegExp = string => string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

const extractOneOf = propType => {
  const { error } = console;
  const isOwnProperty = Object.prototype.hasOwnProperty.call(console, 'error');
  const [prop, component, value] = Array.from({ length: 3 }, () =>
    escapeRegExp(`${Math.random()}`),
  );
  const check = `Warning: Failed ${prop} type: Invalid ${prop} \`${prop}\` of value \`${value}\` supplied to \`${component}\`, expected one of `;
  let result;
  console.error = (...args) => {
    const [message] = args;
    if (message.startsWith(check)) {
      try {
        result = JSON.parse(message.slice(check.length - 1, -1));
      } catch (e) {
        // Continue
      }
    }
  };
  PropTypes.checkPropTypes({ [prop]: propType }, { [prop]: value }, prop, component);
  
  // restore console.error
  if (isOwnProperty) {
    console.error = error;
  } else {
    delete console.error;
  }
  return result;
};

console.log(extractOneOf(MyComponent.propTypes.color));
```

**Are you able to assist to bring the feature to reality?**
Yes, see my code above.

**Additional context**
```js
MyComponent.propTypes = {
  color: PropTypes.oneOf(Object.keys(defaultTheme)),
};
```
![image](https://user-images.githubusercontent.com/476567/96288595-f35ec800-0fe3-11eb-8ece-63e027a97c6d.png)

**Comment by anthonybennett** [comment] 2020-11-03 13:30
We were trying to use a Map to drive the values and were disappointed that we had to create an array for it to work.

**Comment by shilman** [comment] 2020-11-04 04:03
@anthonybennett can you provide more details?

**Comment by anthonybennett** [comment] 2020-11-04 13:17
@shilman Sure thing! Here are some screenshots of what we're getting versus what we expect:

**Actual**
<img width="1194" alt="Current behavior" src="https://user-images.githubusercontent.com/3524895/98115915-88334380-1e75-11eb-89d9-2d40f2e35990.png">

**Expected**
<img width="1191" alt="Expected behavior" src="https://user-images.githubusercontent.com/3524895/98115916-88cbda00-1e75-11eb-8507-c4601d06e3d0.png">

And here's some sample code:

**index.js**
```javascript
// Libraries.

import PropTypes from 'prop-types';
import React from 'react';

// Constants.

export const DEFAULT_VARIANT = 'primary';

export const VARIANTS_MAP = new Map([
  ['primary', 'primary-button'],
  ['secondary', 'secondary-button'],
  ['outlined', 'outlined-button'],
  ['plain', 'plain-button'],
]);

// Need Array as Storybook Controls is unable to generate valid controls when Map is used.
export const VARIANTS_ARRAY = ['primary', 'secondary', 'outlined', 'plain'];

// Public.

const Button = (props) => {
  const { children, variant } = props;

  return (
    <button type="button" className={VARIANTS_MAP.get(variant)}>
      {children}
    </button>
  );
};

Button.defaultProps = {
  variant: DEFAULT_VARIANT,
};

Button.propTypes = {
  children: PropTypes.oneOfType([PropTypes.arrayOf(PropTypes.node), PropTypes.node]),
  // variant: PropTypes.oneOf([...VARIANTS_MAP.keys()]),        <-----  ** Controls don't generate as expected. **
  variant: PropTypes.oneOf(Array.from(VARIANTS_MAP.keys())), // <-----  ** Controls don't generate as expected. **
  // variant: PropTypes.oneOf(VARIANTS_ARRAY),  <----- Using this as a workaround.
};

export default Button;
```

**index.stories.js**
```javascript
// Libraries.

import React from 'react';

// Dependencies.

import Button from '.';

// Private.

const Template = (args) => <Button {...args} />;

// Public.

export default {
  component: Button,
  title: 'Test/Button',
  argTypes: {
    children: {
      control: 'text',
    },
  },
};

export const Default = Template.bind({});
Default.args = {
  children: 'This is an Example.',
};
```

**Comment by as-zlynn-philipps** [comment] 2021-01-08 21:58
Hello yes I am still interested in this please don't go stale.

**Comment by hieucchu** [comment] 2021-01-09 19:56
Still an ongoing issue

**Comment by darkowic** [comment] 2021-01-11 08:28
A similar issue is that if the default value have to be computed like this:
```tsx
MyComponent.defaultProps = {
        handleTooltip: HANDLE_TOOLTIP_VISIBILITY[0],
    };
```
it's actually not resolved:
![Screenshot 2021-01-11 at 09 28 29](https://user-images.githubusercontent.com/11510581/104159296-60210d00-53ef-11eb-961a-c09b3597f92c.png)

**Comment by as-zlynn-philipps** [comment] 2021-01-11 15:17
@darkowic ^ that seems like it has nothing to do with Storybook (just PropTypes)

**Comment by darkowic** [comment] 2021-01-11 20:24
@as-zlynn-philipps well, the storybook here takes literary `'HANDLE_TOOLTIP_VISIBILITY[0]'` as the default value instead of the first element of the `HANDLE_TOOLTIP_VISIBILITY` array.

**Comment by Sm1t** [comment] 2021-02-02 21:53
Anyone working on this? Need help?

**Comment by Sm1t** [comment] 2021-02-02 22:23
If I understand correctly, the problem is related to react-docgen, and now the solution to this problem is in alpha https://github.com/reactjs/react-docgen/pull/464

**Comment by keyserfaty** [comment] 2021-02-13 17:18
Same issue here. Proptypes are not shown not even in the example provided by Storybook:

``` jsx
import React from 'react';
import PropTypes from 'prop-types';
import './button.css';

/**
 * Primary UI component for user interaction
 */
export const Button = ({ primary, backgroundColor, size, label, ...props }) => {
  const mode = primary ? 'storybook-button--primary' : 'storybook-button--secondary';
  return (
    <button
      type="button"
      className={['storybook-button', `storybook-button--${size}`, mode].join(' ')}
      style={backgroundColor && { backgroundColor }}
      {...props}
    >
      {label}
    </button>
  );
};

Button.propTypes = {
  /**
   * Is this the principal call to action on the page?
   */
  primary: PropTypes.bool,
  /**
   * What background color to use
   */
  backgroundColor: PropTypes.string,
  /**
   * How large should the button be?
   */
  size: PropTypes.oneOf(['small', 'medium', 'large']),
  /**
   * Button contents
   */
  label: PropTypes.string.isRequired,
  /**
   * Optional click handler
   */
  onClick: PropTypes.func,
};

Button.defaultProps = {
  backgroundColor: null,
  primary: false,
  size: 'medium',
  onClick: undefined,
};

```

Docs:
<img width="1065" alt="Screen Shot 2021-02-13 at 14 17 25" src="https://user-images.githubusercontent.com/4960753/107856331-33a14c00-6e06-11eb-831d-186633b5526d.png">


Versions:
```
    "@storybook/addon-actions": "^6.1.17",
    "@storybook/addon-essentials": "^6.1.17",
    "@storybook/addon-links": "^6.1.17",
    "@storybook/node-logger": "^6.1.17",
    "@storybook/preset-create-react-app": "^3.1.5",
    "@storybook/react": "^6.1.17",
    "react": "^16.13.1",
```

**Comment by Potseluiko** [comment] 2021-03-01 08:59
I have exactly the same problem.

Everything works correctly for such values:
```
const propTypes = {
    timeUnit: PropTypes.oneOf(**["Hours", "Days", "Months"]**)
}
```

But problem for such values:
```
const propTypes = {
    timeUnit: PropTypes.oneOf(**Object.values(TIME_UNITS)**)
}
```

**P.S.** In the first and in the second case the arrays are the same.

**Comment by Sm1t** [comment] 2021-03-01 13:56
@shilman please tell us about the current status of this issue

**Comment by shilman** [comment] 2021-03-02 02:57
I've documented the solution in #14092 and am closing this as a duplicate

**Closed by shilman** 2021-03-02 02:57 UTC
Labels: P2, addon: controls, app: react, args, block: argstable, feature request

**Comment by Potseluiko** [comment] 2021-03-02 09:12
@shilman Thanks for the answer!
