### ISSUE TITLE
[Bug]: Storybook 8 babel code generator takes forever to start up with material ui components and runs out of memory when trying to build

### ISSUE THREAD

**Issue by KevinVandy** [storybookjs/storybook#26543] opened 2024-03-17 16:57 UTC
### Describe the bug

After upgrading to storybook v8.0.0, the stories in the storybook take about 2 minutes to load at startup after running `npm run storybook`. In v7, this took about 1 second.

The console prints out tons of `[BABEL] Note: The code generator has deoptimised the styling of [pathname] as it exceeds the max of 500KB.` messages. Each of them taking a couple seconds to print.

What is the way around this? I'm assuming this is just because I'm using components that use a lot a Material UI v5 components?

I have confirmed that no other extensions are responsible for this. I uninstalled storybook and re-installed from the cli.

Also, running `storybook:build` causes a heap memory allocation error.

```bash
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x100d566e4 node::Abort() [/usr/local/bin/node]
...
```

Here's what fully what it prints while taking 2 minutes to start up:

```bash
> storybook dev -p 6006

@storybook/cli v8.0.0

info => Starting manager..
WARN No story files found for the specified pattern: stories/**/*.mdx
info => Starting preview..
info Using tsconfig paths for react-docgen
╭────────────────────────────────────────────────────╮
│                                                    │
│   Storybook 8.0.0 for react-vite started           │
│   388 ms for manager and 383 ms for preview        │
│                                                    │
│    Local:            http://localhost:6006/        │
│    On your network:  http://192.168.1.247:6006/    │
│                                                    │
╰────────────────────────────────────────────────────╯
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/body/MRT_TableBody.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/body/MRT_TableBodyCell.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/body/MRT_TableBodyRow.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/body/MRT_TableBodyRowGrabHandle.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/body/MRT_TableBodyRowPinButton.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/body/MRT_TableDetailPanel.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/buttons/MRT_ColumnPinningButtons.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/buttons/MRT_ExpandAllButton.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/buttons/MRT_GrabHandleButton.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/buttons/MRT_CopyButton.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/buttons/MRT_EditActionButtons.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/buttons/MRT_ExpandButton.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/buttons/MRT_RowPinButton.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/buttons/MRT_ShowHideColumnsButton.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/buttons/MRT_ToggleFullScreenButton.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/buttons/MRT_ToggleGlobalFilterButton.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/buttons/MRT_ToggleFiltersButton.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/buttons/MRT_ToggleRowActionMenuButton.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/footer/MRT_TableFooter.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/footer/MRT_TableFooterCell.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/footer/MRT_TableFooterRow.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/head/MRT_TableHead.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/buttons/MRT_ToggleDensePaddingButton.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/head/MRT_TableHeadCellColumnActionsButton.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/head/MRT_TableHeadCellFilterContainer.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/head/MRT_TableHeadCell.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/head/MRT_TableHeadCellGrabHandle.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/head/MRT_TableHeadCellFilterLabel.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/head/MRT_TableHeadCellResizeHandle.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/head/MRT_TableHeadRow.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/head/MRT_TableHeadCellSortLabel.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/inputs/MRT_FilterCheckbox.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/inputs/MRT_FilterRangeFields.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/inputs/MRT_FilterRangeSlider.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/inputs/MRT_FilterTextField.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/menus/MRT_ActionMenuItem.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/inputs/MRT_SelectCheckbox.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/inputs/MRT_GlobalFilterTextField.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/menus/MRT_ColumnActionMenu.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/menus/MRT_FilterOptionMenu.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/menus/MRT_RowActionMenu.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/menus/MRT_ShowHideColumnsMenu.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/inputs/MRT_EditCellTextField.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/modals/MRT_EditRowModal.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/menus/MRT_ShowHideColumnsMenuItems.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/table/MRT_Table.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/table/MRT_TableContainer.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/table/MRT_TableLoadingOverlay.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/toolbar/MRT_BottomToolbar.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/table/MRT_TablePaper.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/toolbar/MRT_TablePagination.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/toolbar/MRT_LinearProgressBar.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/toolbar/MRT_ToolbarAlertBanner.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/toolbar/MRT_ToolbarDropZone.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/toolbar/MRT_ToolbarInternalButtons.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/toolbar/MRT_TopToolbar.tsx as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/username/Documents/material-react-table/packages/material-react-table/src/components/menus/MRT_CellActionMenu.tsx as it exceeds the max of 500KB.
```

### To Reproduce

GitHub Repo (and branch): https://github.com/KevinVandy/material-react-table/tree/storybook-8-upgrade/packages/material-react-table

Here's a full devDep list of this project

```json
  "devDependencies": {
    "@chromatic-com/storybook": "^1.2.22",
    "@emotion/react": "^11.11.4",
    "@emotion/styled": "^11.11.0",
    "@faker-js/faker": "^8.4.1",
    "@mui/icons-material": "^5.15.13",
    "@mui/material": "^5.15.13",
    "@mui/x-date-pickers": "^6.19.7",
    "@rollup/plugin-typescript": "^11.1.6",
    "@size-limit/preset-small-lib": "^11.1.1",
    "@storybook/addon-a11y": "^8.0.0",
    "@storybook/addon-essentials": "^8.0.0",
    "@storybook/addon-interactions": "^8.0.0",
    "@storybook/addon-links": "^8.0.0",
    "@storybook/addon-onboarding": "^8.0.0",
    "@storybook/addon-storysource": "^8.0.0",
    "@storybook/blocks": "^8.0.0",
    "@storybook/preview-api": "^8.0.0",
    "@storybook/react": "^8.0.0",
    "@storybook/react-vite": "^8.0.0",
    "@storybook/test": "^8.0.0",
    "@types/node": "^20.11.28",
    "@types/react": "^18.2.66",
    "@types/react-dom": "^18.2.22",
    "@typescript-eslint/eslint-plugin": "^7.2.0",
    "@typescript-eslint/parser": "^7.2.0",
    "@vitejs/plugin-react": "^4.2.1",
    "eslint": "^8.57.0",
    "eslint-plugin-mui-path-imports": "^0.0.15",
    "eslint-plugin-perfectionist": "^2.7.0",
    "eslint-plugin-storybook": "^0.8.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-is": "^18.2.0",
    "rollup": "^2.79.1",
    "rollup-plugin-copy": "^3.5.0",
    "rollup-plugin-delete": "^2.0.0",
    "rollup-plugin-dts": "^6.1.0",
    "rollup-plugin-peer-deps-external": "^2.2.4",
    "size-limit": "^11.1.1",
    "storybook": "^8.0.0",
    "storybook-dark-mode": "^4.0.0",
    "tslib": "^2.6.2",
    "typescript": "^5.4.2",
    "vite": "^5.1.6"
  },
```

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.3.1
    CPU: (10) arm64 Apple M1 Pro
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 18.17.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.7 - /usr/local/bin/npm
    pnpm: 8.14.0 - /usr/local/bin/pnpm <----- active
  Browsers:
    Chrome: 122.0.6261.129
    Safari: 17.3.1
  npmPackages:
    @storybook/addon-a11y: ^8.0.0 => 8.0.0 
    @storybook/addon-essentials: ^8.0.0 => 8.0.0 
    @storybook/addon-interactions: ^8.0.0 => 8.0.0 
    @storybook/addon-links: ^8.0.0 => 8.0.0 
    @storybook/addon-onboarding: ^8.0.0 => 8.0.0 
    @storybook/addon-storysource: ^8.0.0 => 8.0.0 
    @storybook/blocks: ^8.0.0 => 8.0.0 
    @storybook/preview-api: ^8.0.0 => 8.0.0 
    @storybook/react: ^8.0.0 => 8.0.0 
    @storybook/react-vite: ^8.0.0 => 8.0.0 
    @storybook/test: ^8.0.0 => 8.0.0 
    eslint-plugin-storybook: ^0.8.0 => 0.8.0 
    storybook: ^8.0.0 => 8.0.0 
    storybook-dark-mode: ^4.0.0 => 4.0.0
```

### Additional context

<img width="1687" alt="image" src="https://github.com/storybookjs/storybook/assets/28243511/354979fc-1b94-4f83-b2bc-8b66b741aacb">

**Comment by valentinpalkovic** [comment] 2024-03-18 12:31
In Storybook 8.0, `react-docgen` is the default for component analysis in React projects. Compared to `react-docgen-typescript`, `react-docgen` will try to discover the types of your component's properties without booting up a TypeScript server, but rather via AST analysis.

It seems that the AST method via Babel takes too long in your special case. I would suggest switching back to `react-docgen-typescript,` which was the default in Storybook 7.x:

```tsx
// .storybook/main.js|ts
export default {
  typescript: {
    reactDocgen: "react-docgen-typescript",
  },
};
```

You can find more information in our migration docs:
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#react-docgen-component-analysis-by-default

It seems that in particular scenarios, where type inference might rely on a bunch of types, unions, and intersections and the number of scannable files is enormous (because of, for example, barrel files in between), it is a more performant choice to use `react-doc gen-typescript.` You can report this issue [here](https://github.com/reactjs/react-docgen) if you think it should be fixed by `react-docgen`, but I don't think Storybook can do much about it.

I will close this issue for now. Let me know if I should reopen it and if you think that the issue is actually solvable by Storybook.

just fyi: cc @shilman

**Closed** 2024-03-18 12:31 UTC
Labels: bug, performance issue, sev:S2
