### ISSUE TITLE
isFullscreen: false option not working

### ISSUE THREAD

**Issue by lancevalour** [storybookjs/storybook#8541] opened 2019-10-23 20:33 UTC
**Describe the bug**
In the config.js `addParameters` function, if I set `isFullscreen: true` and open the webpage, it is fullscreen on startup. But if I set `isFullscreen: false` and open the webpage again, it is still full-screen on startup.

**To Reproduce**
1. Set `isFullscreen: true`, open the webpage, 
2. Close the webpage or stop the server
3. Set `isFullscreen: false`, open the webpage

**Expected behavior**
I should see storybook not in full-screen mode

**System:**
```
Environment Info:

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
```

**Comment by shuklajay117** [comment] 2019-11-05 07:06
I can work on this issue. Can anyone guide me please?
I'm going to contribute here first time.

**Comment by hobroker** [comment] 2019-11-10 00:42
@shilman, that's related to https://github.com/storybookjs/storybook/issues/5857, isn't it?

**Comment by ahmedkhan1** [comment] 2020-04-20 20:43
Is this issue this open?

**Comment by shilman** [comment] 2020-04-20 21:08
@ahmedkhan1 yes please!

**Comment by aditya237** [comment] 2020-05-09 04:56
I'm a first timer wanna contribute is it still available
i'll do my best to remove the bug

**Comment by zootechdrum** [comment] 2020-05-27 02:10
Hello, is anyone working on this?

**Comment by shilman** [comment] 2020-05-27 02:22
not that i know of

**Comment by zootechdrum** [comment] 2020-05-27 04:25
Great, I will take this on. I have downloaded storybook now and messing around with the features. I will try and reproduce the error on my machine. I am running on a mac, hopefully this isn't just a windows thing.

**Comment by zootechdrum** [comment] 2020-05-27 04:44
Interesting, I can't reproduce this error. I am running on a Mac. When I add the manager.js file and go from true to false after closing the window I see the that side nav is visible. When set to true the side panel is not visible. 
<img width="1440" alt="Screen Shot 2020-05-26 at 9 42 59 PM" src="https://user-images.githubusercontent.com/28512399/82978668-f9eb9500-9f99-11ea-8274-29ace2d850bc.png">
<img width="1440" alt="Screen Shot 2020-05-26 at 9 43 17 PM" src="https://user-images.githubusercontent.com/28512399/82978678-fd7f1c00-9f99-11ea-86f8-70018429f818.png">

**Comment by kunal13053** [comment] 2020-06-24 15:21
Hello, Is anyone working on this issue?
Can I work on this?

**Comment by ManuelPortero** [comment] 2020-06-29 13:48
Hi ! Can I work on this issue ? Is anybody work on this ?

**Comment by almogbhl** [comment] 2020-11-03 19:22
Hi, is it still relevant? 
I can't reproduce this, it works just fine.

@shilman WDYT?

**Comment by shilman** [comment] 2020-11-04 04:30
Thanks @almogbhl Closing this until somebody provides a repro

**Closed by shilman** 2020-11-04 04:30 UTC
Labels: bug, good first issue, help wanted, ui
