### ISSUE TITLE
[Bug]: `%` in `mdxSource` prop on Canvas fails with `URI error decodeURI@[native code]`

### ISSUE THREAD

**Issue by nstuyvesant** [storybookjs/storybook#21802] opened 2023-03-28 19:25 UTC
### Describe the bug

Have an MDX that displays a simple React component.  The size property can be a number or string. From an MDX, if I pass a string, I get the following error. If I pass a number, it works.
```
URI error
decodeURI@[native code]
useDeprecatedPreviewProps@http://localhost:9006/node_modules/.cache/.vite-storybook/deps/chunk-JA6Y2RSH.js?v=4144b0a3:1499:321
Canvas@http://localhost:9006/node_modules/.cache/.vite-storybook/deps/chunk-JA6Y2RSH.js?v=4144b0a3:1516:62
renderWithHooks@http://localhost:9006/node_modules/.cache/.vite-storybook/deps/chunk-6ZDUWZXD.js?v=4144b0a3:12171:35
mountIndeterminateComponent@http://localhost:9006/node_modules/.cache/.vite-storybook/deps/chunk-6ZDUWZXD.js?v=4144b0a3:14921:36
beginWork$1@http://localhost:9006/node_modules/.cache/.vite-storybook/deps/chunk-6ZDUWZXD.js?v=4144b0a3:19749:31
performUnitOfWork@http://localhost:9006/node_modules/.cache/.vite-storybook/deps/chunk-6ZDUWZXD.js?v=4144b0a3:19194:31
workLoopSync@http://localhost:9006/node_modules/.cache/.vite-storybook/deps/chunk-6ZDUWZXD.js?v=4144b0a3:19133:30
renderRootSync@http://localhost:9006/node_modules/.cache/.vite-storybook/deps/chunk-6ZDUWZXD.js?v=4144b0a3:19112:27
recoverFromConcurrentError@http://localhost:9006/node_modules/.cache/.vite-storybook/deps/chunk-6ZDUWZXD.js?v=4144b0a3:18732:42
performConcurrentWorkOnRoot@http://localhost:9006/node_modules/.cache/.vite-storybook/deps/chunk-6ZDUWZXD.js?v=4144b0a3:18680:56
performConcurrentWorkOnRoot@[native code]
workLoop@http://localhost:9006/node_modules/.cache/.vite-storybook/deps/chunk-6ZDUWZXD.js?v=4144b0a3:197:50
flushWork@http://localhost:9006/node_modules/.cache/.vite-storybook/deps/chunk-6ZDUWZXD.js?v=4144b0a3:176:30
performWorkUntilDeadline@http://localhost:9006/node_modules/.cache/.vite-storybook/deps/chunk-6ZDUWZXD.js?v=4144b0a3:384:50
```

```ts
// .storybook/main.ts
import type { StorybookConfig } from '@storybook/react-vite'

const config: StorybookConfig = {
	stories: [
		'../src/**/*.mdx',
		'../src/**/*.stories.@(js|jsx|ts|tsx)'
	],
	addons: [
		{
			name: '@storybook/addon-essentials',
			options: {
				actions: false
			}
		}
	],
	framework: {
		name: '@storybook/react-vite',
		options: {}
	},
	docs: {
		autodocs: 'tag'
	},
	features: {
		storyStoreV7: false
	}
}
export default config
```

Here's the use of the component in the MDX...
```mdx
import { Canvas } from '@storybook/addon-docs'
import ShapeNode from './ShapeNode'

<Canvas style={{ background: '#fff' }}>
  <div style={{ height: 64, width: 64 }}>
    <ShapeNode title={'Title'} size={'100%'}  />
  </div>
</Canvas>
```

Here is ShapeNode component...
```
import React from 'react'

type ShapeNodeProps = {
  title?: string
  size?: string | number
}

const ShapeNode: React.FC<ShapeNodeProps & React.HTMLAttributes<HTMLDivElement>> = ({
  title = 'Title',  size = 48,  ...rest
}) => {

  return (
    <div {...rest} style={{ height: size, width: size }}>{title}</div>
  )
}

export default ShapeNode
```

### To Reproduce

See code above.

### System

```shell
Environment Info:

  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.15.0 - /opt/homebrew/bin/node
    Yarn: 3.5.0 - /opt/homebrew/bin/yarn
    npm: 9.6.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 111.0.5563.110
    Firefox: 111.0.1
    Safari: 16.3
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-0 => 7.0.0-rc.8 
    @storybook/addon-interactions: ^7.0.0-0 => 7.0.0-rc.8 
    @storybook/addon-links: ^7.0.0-0 => 7.0.0-rc.8 
    @storybook/blocks: ^7.0.0-0 => 7.0.0-rc.8 
    @storybook/manager-api: ^7.0.0-0 => 7.0.0-rc.8 
    @storybook/react: ^7.0.0-0 => 7.0.0-rc.8 
    @storybook/react-vite: ^7.0.0-0 => 7.0.0-rc.8 
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1 
    @storybook/theming: ^7.0.0-0 => 7.0.0-rc.8
```

### Additional context

We have to have features.storyStoreV7 set to false because we still have dozens stories based on storiesOf().

**Comment by nstuyvesant** [comment] 2023-03-28 19:29
I should add that this problem is not occurring in the storiesOf() version - only in the MDX.
```
stories.add(
	'Inherited dimensions',
	() => (
		<div style={{ height: 64, width: 64, position: 'relative' }}>
			<ShapeNode title={'Title'} size={'100%'} />
		</div>
	),
	{
		controls: {
			hideNoControlsWarning: true
		}
	}
)
```

**Comment by shilman** [comment] 2023-03-29 12:37
@JReinhold any idea what's going on here?

**Comment by JReinhold** [comment] 2023-03-29 14:05
I've managed to reproduce this minimally here: https://stackblitz.com/edit/github-rwuep4?file=src/stories/reproduction.stories.mdx

It's actually not related to string vs number props at all, it's about having source that includes the `%` character. During rendering of `Canvas` we do `decodeURI(mdxSource)`, which fails if `mdxSource` contains `%`. `decodeURI` is a browser API, the breakage is not related to Storybook.

This only fails in `.stories.mdx` files and not `.mdx` files, [because `@storybook/mdx2-csf` automatically generates the `mdxSource` prop from the Canvas children](https://github.com/storybookjs/mdx2-csf/blob/051f37c627fb8f219d3328a3deb0cfd28ddfc2cc/src/index.ts#L32-L36), which doesn't happen in plain `.mdx` files.
This is also evident in my reproduction, where I explicitly set the `mdxSource` prop in a `.mdx` file and it still breaks.

I'm not sure why we run `decodeURI` on `mdxSource`, but we've done it since the very beginning https://github.com/storybookjs/storybook/pull/7966

**Comment by nstuyvesant** [comment] 2023-03-29 19:21
Nice catch!

**Comment by foerstj-dv** [comment] 2023-08-10 11:14
Issue is still present. Please fix, I'd like to use a percent character ;)

**Comment by rajatmehra-kunai** [comment] 2023-10-06 10:57
The problem continues to exist in the newest Storybook release. Though I don't have any hardcore necessity in my project, but I'd like a fix for this! :)

**Comment by flippidippi** [comment] 2023-12-08 21:13
Is there any way around this? We need to be able to put `%` signs in docs...

**Comment by JReinhold** [comment] 2024-01-31 23:32
Closing this as Storybook 8 is dropping support for Stories MDX and this problem only occurs in that scenario.

**Closed by JReinhold** 2024-01-31 23:32 UTC
Labels: bug, help wanted, mdx, block: other, sev:S3
