### ISSUE TITLE
Controls not detecting our component props from propTypes or JSDoc (typescript) types

### ISSUE THREAD

**Issue by haszari** [storybookjs/storybook#12292] opened 2020-08-28 03:12 UTC
**Describe the bug**
Hi there, sorry for the vague bug!

We've recently upgrade to Storybook 6.0 and we're keen to migrate our stories from `Knobs` to `Controls` addon, and the other cool stuff in essentials [based on the `args` pattern](https://storybook.js.org/docs/react/writing-stories/args), e.g. automatic docs.

Our project uses React, so we're using Storybook-react. The project is [WooCommerce Blocks](https://github.com/woocommerce/woocommerce-gutenberg-products-block), and there's an open PR dedicated to this: https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3046

Our components include PropTypes declarations. Example component: https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/51137ecb81da55c98cfc7bc5ed3dcd4e2aa75a8b/assets/js/base/components/quantity-selector/index.js

Note - we're planning on migrating to JSDoc typescript declarations (in our JS files - we're not using TypeScript lang). So if this is supported by Storybook we can switch to that. So far I can't get either option to work - the controls don't show up in Storybook unless I manually specify them via story.args prop.

<img width="746" alt="Screen Shot 2020-08-28 at 3 07 01 PM" src="https://user-images.githubusercontent.com/4167300/91516661-27046680-e940-11ea-8844-5cd02ff0e564.png">

Our project is quite complex and we have a custom webpack config. In the related branch / PR the webpack config is overridden using `webpackFinal` config prop. 

With `--debug-webpack` I've confirmed that the react-docgen plugin is in the config:

```js
  overrides: [
        {
          test: /\.(mjs|jsx?)$/,
          plugins: [
            [
              '/Users/haszari/_automattic/merch-repos/woocommerce-blocks/node_modules/babel-plugin-react-docgen/lib/index.js',
              {
                DOC_GEN_COLLECTION_NAME: 'STORYBOOK_REACT_CLASSES'
              }
            ]
``` 

How can I debug where it's going wrong, or ensure it has access to our prop declarations?

**To Reproduce**
Sorry – I don't have a minimal reproduce repo. 

**Expected behavior**
Hoping to get this working, again apologies for the open-ended bug report. 

Ideally we can nail down the flow of data into react-docgen and document exactly what's expected here, and how to diagnose problems.

**System:**
Please paste the results of `npx sb@next info` here.

```
Environment Info:

  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    npm: 6.14.8 - ~/.nvm/versions/node/v12.18.3/bin/npm
  Browsers:
    Chrome: 84.0.4147.135
    Firefox: 79.0
    Safari: 13.1.2
  npmPackages:
    @storybook/addon-a11y: 6.0.20 => 6.0.20 
    @storybook/addon-essentials: 6.0.20 => 6.0.20 
    @storybook/addon-knobs: 6.0.20 => 6.0.20 
    @storybook/addon-links: 6.0.20 => 6.0.20 
    @storybook/addon-storysource: 6.0.20 => 6.0.20 
    @storybook/addons: 6.0.20 => 6.0.20 
    @storybook/react: 6.0.20 => 6.0.20 
```

**Additional context**

**Comment by haszari** [comment] 2020-08-28 03:13
Here's a trimmed-down example component and story.

```js
// index.js
/**
 * @typedef QuantitySelector
 *
 * @param {Object} props Component props.
 * @param {string} props.className CSS class(es).
 * @param {number} props.quantity Value to display.
 * @param {number} props.minimum Minimum value.
 * @param {number} props.maximum Maximum value.
 * @param {Function} props.onChange Called when the value changes.
 * @param {string} props.itemName The item/value (e.g. product) that the quantity applies to - used for an accessibility message.
 * @param {boolean} props.disabled Render the component as disabled and prevent user input.
 * @return {*} QuantitySelector component markup.
 */
const QuantitySelector = ( {
  className,
  quantity = 1,
  minimum = 1,
  maximum,
  onChange = () => null,
  itemName = '',
  disabled,
} ) => {
  // .. component implementation 
};

// stories/index.js
import QuantitySelector from '../';

export default {
  title: 'WooCommerce Blocks/@base-components/QuantitySelector',
  component: QuantitySelector,
};

const Template = ( args ) => <QuantitySelector { ...args } />;

export const Primary = Template.bind( {} );
// Primary.args = {
//  disabled: false,
//  quantity: 1,
//  itemName: 'widgets',
// };
```

**Comment by haszari** [comment] 2020-08-28 03:44
Update – I've pasted in a 100% TypeScript `Button` example (from [Storybook examples](https://github.com/storybookjs/storybook/tree/next/examples/react-ts/src)) and it works correctly. 

Code here: https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3046/commits/2a35668aeaf007c7c9eeefb3b936a979639ff5ea

🎉 screenshot of args working: (!)

<img width="571" alt="Screen Shot 2020-08-28 at 3 41 23 PM" src="https://user-images.githubusercontent.com/4167300/91518675-ef4bed80-e944-11ea-9808-d85fc574ad6c.png">

This is using the same webpack and other config, so I think the problem is with our JavaScript components, and how we can export the PropTypes & descriptions so `args` can find them (or maybe a problem with the story js not importing the proptypes).

Is there a way to use `args` with JavaScript components and stories? I'm keen to see a canonical example.

Just confirming - `args` doesn't require TypeScript?

**Comment by shilman** [comment] 2020-08-28 05:21
@haszari we use args with PropTypes all the time and there are numerous examples in the monorepo and probably in the Storybook design system. It's definitely an issue with your webpack config.

**Comment by haszari** [comment] 2020-08-28 06:39
> It's definitely an issue with your custom webpack config.

Highly likely! I'll keep digging, I'm guessing there's some interaction with other plugins/steps in the webpack config. I can try disabling various plugins and ensure everything's up to date. 🤞

**Comment by imeredith** [comment] 2020-08-31 05:19
I'm not sure if im having the same issue as you, but it sounds the same. 

My ___docgenInfo is populated and I just tried the following which works...

```
MyComponentStory.argTypes = MyComponent.___docgenInfo.props
```

I thought it was a webpack issue but I don't think so now

**Comment by shilman** [comment] 2020-08-31 10:45
@imeredith different issue. happy to help diagnose if you open a separate issue.

**Comment by reywright** [comment] 2020-09-01 00:21
I'm also running into this issue and I can confirm the following:

- This isn't related to custom webpack config. I deleted all my stories, my custom webpack config, and then made a simple story and it still didn't work.
- I can confirm that when making a brand new create-react-app and installing storybook, I do see the generated proptypes.

Given both of those statements it's not clear to me what the actual issue is here, only that it's hard to recreate, it's not webpack, and it's not babel config (as storybook 6 ignores that). It would be great to get some general direction so I could assist debugging in my local env.

**Comment by shilman** [comment] 2020-09-01 01:03
@reywright if you have a simple repro, i'd love to take a look at it.

**Comment by reywright** [comment] 2020-09-01 01:10
It's 100% the babel config file for me, FYI. Nuking that file makes everything work fine.

I can "try" to put together a simple repro... it's difficult because babel configuration can get complex sometimes?

**Comment by yairEO** [comment] 2021-06-02 07:01
I might have a similar problem. After spending a full day researching and trying different things, nothing works and the automatic args table is not showing my components proptypes definitions.

I've put the whole code online (based on my client's complex Stroybook config), with just a little bit of cleanup, and left only one story

https://github.com/yairEO/sb-args-table-not-showing

## Files of interest:
* [The `Alert` Component](https://github.com/yairEO/sb-args-table-not-showing/blob/master/src/Alert/Alert.js)
* [Alert Story](https://github.com/yairEO/sb-args-table-not-showing/blob/master/src/Alert/Alert.stories.js)
* [babel config](https://github.com/yairEO/sb-args-table-not-showing/blob/master/.babelrc.js) where I've disabled everything which is enabled in the "real" client's code
* [storybook `main.js`](https://github.com/yairEO/sb-args-table-not-showing/blob/master/.storybook/main.js)

Thanks to whoever shed light onto this mystery

**Comment by mbustosp** [comment] 2021-08-29 20:25
> I might have a similar problem. After spending a full day researching and trying different things, nothing works and the automatic args table is not showing my components proptypes definitions.
> 
> I was mainly following these instructions: https://storybook.js.org/docs/ember/writing-docs/doc-blocks
> 
> I've put the whole code online (based on my client's complex Stroybook config), with just a little bit of cleanup, and left only one story
> 
> https://github.com/yairEO/sb-args-table-not-showing
> 
> ## Files of interest:
> * [The `Alert` Component](https://github.com/yairEO/sb-args-table-not-showing/blob/master/src/Alert/Alert.js)
> * [Alert Story](https://github.com/yairEO/sb-args-table-not-showing/blob/master/src/Alert/Alert.stories.js)
> * [babel config](https://github.com/yairEO/sb-args-table-not-showing/blob/master/.babelrc.js) where I've disabled everything which is enabled in the "real" client's code
> * [storybook `main.js`](https://github.com/yairEO/sb-args-table-not-showing/blob/master/.storybook/main.js)
> 
> Thanks to whoever shed light onto this mystery

I faced the same issue when I added a custom babel configuration in my application. After some debugging I realized storybook could not fetch the components' _proptypes_ because of this evaluation:

https://github.com/storybookjs/storybook/blob/7064642e1aee7786c77fe735c064c0c29dbcee01/addons/docs/src/lib/docgen/utils/docgenInfo.ts#L15

That means `component.__docgenInfo` is undefined or null.

How did I solve it?

Adding the following dependencies

- "react-docgen"
- "storybook-addon-react-docgen"
- "babel-plugin-react-docgen"

Adding the following addon in your storybook's main.js

- 'storybook-addon-react-docgen'

Adding the following plugin in your .babelrc

- ["react-docgen"]

Now I haven't completely understood why storybook drops react-docgen when using a custom babel configuration file.

I hope to have shed some light ;)

**Comment by shilman** [comment] 2021-08-31 03:54
@mbustosp potentially addressed here https://github.com/storybookjs/storybook/pull/15928

**Comment by shilman** [comment] 2021-08-31 17:16
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-alpha.33 containing PR #15928 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2021-08-31 17:16 UTC
Labels: question / support, babel / webpack, args
