### ISSUE TITLE
[Bug]: Preview always has a white background

### ISSUE THREAD

**Issue by Jasperrr91** [storybookjs/storybook#22029] opened 2023-04-11 15:01 UTC
### Describe the bug

Hi there, this recent pull request: https://github.com/storybookjs/storybook/pull/21593 seems to have broken `@storybook/theming`. Looking at the PR description the change was verified with the default backgrounds addon but it looks like `@storybook/theming` slipped through. This package is used by many addons to customise the styling, for instance https://www.npmjs.com/package/storybook-dark-mode with 190k weekly downloads.

We used to be able to set the Preview background with `appContentBg`. This is then converted to `theme.background.content` by: https://github.com/storybookjs/storybook/blob/latest-release/code/lib/theming/src/convert.ts#L117

It is then applied to the iFrame wrapper `<div id="storybook-preview-wrapper">` at:
https://github.com/storybookjs/storybook/blob/next/code/ui/manager/src/components/preview/utils/components.ts

However, the underlying iFrame `storybook-preview-iframe` now has this newly introduced `backgroundColor: white` which renders the customised `appContentBg` useless:
https://github.com/storybookjs/storybook/blob/next/code/ui/manager/src/components/preview/iframe.tsx

I'm not entirely sure about the problem that @JReinhold tried to solve (maybe you could elaborate more Jeppe) but it was desired behaviour to be able to set the background color. Maybe a change caused the `appContentBg` to unexpectedly be overwritten in dark mode. In that case we should probably look over there to solve that bug.

Optionally, the `backgroundColor: white` could also be replaced by a `backgroundColor: theme.background.content` but this seems like it won't solve your bug as the iFrame wrapper already had that color applied to it.

### To Reproduce

1. Setup a default instance of Storybook
2. Overwrite `appContentBg` with `@storybook/theming`, for example with storybook-dark-mode
3. Load any story to see that preview always remains white

### System

```shell
Environment Info:

  System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.49
    Firefox: 111.0.1
    Safari: 15.6.1
```

**Comment by probablyup** [comment] 2023-04-14 10:52
It’s this issue https://github.com/storybookjs/storybook/issues/21798

**Comment by jaggerstar** [comment] 2023-04-17 05:26
I think here is the root cause: https://github.com/storybookjs/storybook/commit/9148c6601d347a88a35cb6e0dd89658890beceef

**Comment by sekeidesign** [comment] 2023-05-19 16:03
Any updates on this? It doesn't look like it's just a background colour issue on our end, but like the preview ignores the theming entirely: text colour, font, background colour, none of them have any effect on the look of the preview which makes it really difficult to use for an app like ours that only has dark mode

**Comment by BnAmN** [comment] 2023-05-19 22:11
I‘m using the following workaround (for now):

```html
<!-- .storybook/manager-head.html -->
<style>
  #storybook-preview-iframe {
    background-color: transparent !important;
  }
</style>
```

Tested with `storybook-dark-mode` which seems to be working again using this workaround.

Maybe this helps someone else too until the issue got addressed.

**Comment by sekeidesign** [comment] 2023-05-24 18:38
> I‘m using the following workaround (for now):
> 
> ```
> 
> <style>
>   #storybook-preview-iframe {
>     background-color: transparent !important;
>   }
> </style>
> ```
> 
> Tested with `storybook-dark-mode` which seems to be working again using this workaround.
> 
> Maybe this helps someone else too until the issue got addressed.

Unfortunately this doesn't work for me (might just be a product of our setup).
Adding some similar css to our `base.css` does work, but we need to write custom css for everything since just updating the background colour only solves one of the issues with dark mode, but not everything else 😢 

<img width="768" alt="CleanShot 2023-05-24 at 14 35 33@2x" src="https://github.com/storybookjs/storybook/assets/59372630/f992baef-e779-4fb1-9248-8c9670a563a8">

**Comment by BnAmN** [comment] 2023-05-24 22:59
> > I‘m using the following workaround (for now):
> > ```
> > 
> > <style>
> >   #storybook-preview-iframe {
> >     background-color: transparent !important;
> >   }
> > </style>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Tested with `storybook-dark-mode` which seems to be working again using this workaround.
> > Maybe this helps someone else too until the issue got addressed.
> 
> Unfortunately this doesn't work for me (might just be a product of our setup). Adding some similar css to our `base.css` does work, but we need to write custom css for everything since just updating the background colour only solves one of the issues with dark mode, but not everything else 😢
> <img alt="CleanShot 2023-05-24 at 14 35 33@2x" width="768" src="https://user-images.githubusercontent.com/59372630/240710043-f992baef-e779-4fb1-9248-8c9670a563a8.png">

Well for the Docs view you can simply create your own `DocsContainer` to get the docs affected by `storybook-dark-mode`:

```tsx
/* .storybook/preview.tsx */
import {themes} from '@storybook/theming';
import {DocsContainer} from './DocsContainer';

/* (...) */

export const parameters = {
  /* (...) */
  darkMode: {
    dark: {...themes.dark},
    light: {...themes.light},
    stylePreview: true,
    darkClass: 'dark'
  },
  docs: {
    container: DocsContainer
  }
};
```

```tsx
/* .storybook/DocsContainer.tsx */
import React, {PropsWithChildren} from 'react';
import {DocsContainer as BaseContainer, DocsContainerProps as BaseContainerProps} from '@storybook/blocks';
import {themes} from '@storybook/theming';
import {useDarkMode} from 'storybook-dark-mode';

export const DocsContainer = (
  props: PropsWithChildren<BaseContainerProps>
) => {
  const dark = useDarkMode();
  return (
    <BaseContainer
      context={props.context}
      theme={dark ? themes.dark : themes.light}
    >
      {props.children}
    </BaseContainer>
  );
};
```

**Comment by TristanBrotherton** [comment] 2023-06-22 19:18
Just stumbled into this as well. Is there a workaround? First class dark mode support is crucial for components.

**Comment by JReinhold** [comment] 2023-10-25 11:32
The solution we're proposing to this in #24575 is to introduce a new separate theming variable, `appPreviewBg` to set the preview background in your theme, with `storybook-dark-mode` or by other means.

The PR is released as canary version `[0.0.0-pr-24575-sha-3de4e9e0](https://npmjs.com/package/@storybook/cli/v/0.0.0-pr-24575-sha-3de4e9e0)` so you can install that to try it out.

There's also a StackBlitz that demonstrates how it behaves with/without `storybook-dark-mode` and `@storybook/addon-themes`: [stackblitz.com/edit/github-u7boko?file=.storybook%2Fpreview.ts](https://stackblitz.com/edit/github-u7boko?file=.storybook%2Fpreview.ts)

Let me know what you think @Jasperrr91 @sekeidesign

**Closed** 2023-10-31 12:01 UTC
Labels: bug, ui, sev:S2

**Comment by HugoRamonPereira** [comment] 2024-10-18 14:10
I am still experiencing it, I tried many workarounds, downloaded storybook-dark-mode, followed the steps, tweaked a lot of files and nothing... just gonna leave it all white...

**Comment by DonnyVerduijn** [comment] 2024-10-20 11:41
This might help:
```ts
import * as React from 'react';
import {
  DocsContainer as BaseContainer,
  DocsContainerProps,
} from '@storybook/blocks';
import { addons } from '@storybook/preview-api';
import { themes } from '@storybook/theming';
import { DARK_MODE_EVENT_NAME } from 'storybook-dark-mode';

const channel = addons.getChannel();

export const DocsContainer: React.FC<
  React.PropsWithChildren<DocsContainerProps>
> = ({ children, context }) => {
  const [isDark, setDark] = React.useState(() => {
    const channel = addons.getChannel();
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-expect-error data is private
    // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
    return (channel.data?.DARK_MODE?.[0] as boolean | undefined) ?? false;
  });

  const theme = React.useMemo(
    () => ({
      ...(isDark ? themes.dark : themes.light),
      fontBase: 'Proxima Nova',
    }),
    [isDark]
  );

  React.useEffect(() => {
    channel.on(DARK_MODE_EVENT_NAME, setDark);
    return () => channel.off(DARK_MODE_EVENT_NAME, setDark);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [channel]);

  return (
    <BaseContainer
      context={context}
      theme={theme}
    >
      {children}
    </BaseContainer>
  );
};
```

**Comment by beetol** [comment] 2024-11-29 22:53
> I am still experiencing it, I tried many workarounds, downloaded storybook-dark-mode, followed the steps, tweaked a lot of files and nothing... just gonna leave it all white...

I fixed it by adding appPreviewBg (from the [Storybook 7.6 release](https://storybook.js.org/blog/storybook-7-6/))

```
const preview = {
  parameters: {
    darkMode: {
      dark: {
        ...themes.dark,
        appBg: 'black',
        appPreviewBg: "gray", // set appPreviewBg
      },
    },
};
```

**Comment by jasperdunn** [comment] 2025-05-19 06:21
I think there's still an issue here, I'm on the latest version, this is what worked for me.

```ts
// .storybook/preview.tsx

import "./storybook.css";
```

```css
// .storybook/storybook.css

body.sb-show-main {
  background: transparent !important;
}
```
