### ISSUE TITLE
Docs tab (@storybook/addon-docs): canvas' content copying doesn't work

### ISSUE THREAD

**Issue by jphawk** [storybookjs/storybook#18443] opened 2022-06-09 10:48 UTC
**Describe the bug**
Nothing can be copied from the canvas preview (`.sbdocs-preview `container) in the Docs tab (@storybook/addon-docs). The bug disappears if Storybook settings in `preview.js` has `inlineStories: false` in docs parameters. The content of the canvas can be copied. 

**To Reproduce**
1. Navigate to Docs tab in a Story
2. Copy some text from there, try to paste it to somewhere

**System**
System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.17.3 - /usr/local/bin/node
    npm: 8.12.0 
  Browsers:
    Chrome: 102.0.5005.61
    Edge: 102.0.1245.33
    Firefox: 95.0
    Safari: 15.5
  npmPackages:
    @storybook/addon-a11y: 6.4.22 => 6.4.22 
    @storybook/addon-docs: 6.5.3 => 6.5.3 
    @storybook/addon-essentials: 6.4.22 => 6.4.22 
    @storybook/addon-jest: 6.4.22 => 6.4.22 
    @storybook/addon-storysource: 6.4.22 => 6.4.22 
    @storybook/addons: 6.4.22 => 6.4.22 
    @storybook/builder-webpack5: 6.4.22 => 6.4.22 
    @storybook/manager-webpack5: 6.4.22 => 6.4.22 
    @storybook/preset-create-react-app: 4.1.0 => 4.1.0 
    @storybook/react: 6.4.22 => 6.4.22 
    @storybook/theming: 6.4.22 => 6.4.22

**Comment by pocka** [comment] 2022-08-08 13:36
Duplicate of #18611

**Closed by pocka** 2022-08-08 13:36 UTC
Labels: bug, needs triage
