### ISSUE TITLE
[Bug]: docs.source.format doesn't accept "typescript" as a parser

### ISSUE THREAD

**Issue by emily-haynes** [storybookjs/storybook#21891] opened 2023-04-03 17:25 UTC
### Describe the bug

When setting `docs.source.format: "typescript"`, the following error gets thrown:

```
Couldn't resolve parser "typescript". Parsers must be explicitly added to the standalone bundle.
```

From the discussion [here](https://discord.com/channels/486522875931656193/1088110671901769788/1090394117781082123), my understanding is that this is due to the `prettierTypescript` plugin not being loaded.

As a workaround, we're using `transformSource` (soon to be updated to `transform`) to pull in the parser manually:
```
import prettier from "prettier/standalone";
import prettierTypescript from "prettier/parser-typescript";

export const parameters = {
  docs: {
    source: {
      transformSource: (src: string) => 
        prettier.format(src, {
          parser: "typescript",
          plugins: [prettierTypescript]
        }),
      },
    },
};
```

**Comment by jeremydrichardson** [comment] 2024-06-21 18:24
Even with this workaround I still get:
```
Couldn't resolve parser "typescript". Plugins must be explicitly added to the standalone bundle.
```
Any thoughts?

**Comment by JReinhold** [comment] 2024-09-27 12:00
Closing this as duplicate of https://github.com/storybookjs/storybook/issues/25821 - simply because that has slightly more info

**Closed by JReinhold** 2024-09-27 12:00 UTC
Labels: bug, question / support, help wanted, has workaround, block: source, sev:S3
