### ISSUE TITLE
Control addon warning on fully configured story

### ISSUE THREAD

**Issue by Spy-Seth** [storybookjs/storybook#11769] opened 2020-08-03 09:49 UTC
**Describe the bug**
The "_This story is not configured to handle controls._" warning is show on a story with no controls but only actions:

**Expected behavior**
The warning should not be shown as all props are being handled by the control addons

**Screenshots**
![image](https://user-images.githubusercontent.com/95120/89169378-72646880-d57e-11ea-9e63-bb9d5bd6afdc.png)

**Code snippets**
The component:

```tsx
import React from "react";

export interface TestButtonProps {
  onFoo: (something: string) => void;
}

export const TestButton = ({
  onFoo,
}: TestButtonProps) => (
  <button onClick={() => onFoo("pwouet")}>
    TODO
  </button>
);
```

The story:

```tsx
import React from "react";
import { TestButton, TestButtonProps } from "./TestButton";

export default {
  title: "Components / TestButton",
  component: TestButton,
};

export const Preview = (args: TestButtonProps) => <TestButton {...args} />;
```

I have configure the action addons globally in the `preview.js` file:

```js
// ...
export const parameters = {
  actions: {
    argTypesRegex: "^on.*",
  },
  // ...
};
```

**System:**
```
Environment Info:

  System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  Binaries:
    Node: 14.4.0 - /home/linuxbrew/.linuxbrew/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.4 - /home/linuxbrew/.linuxbrew/bin/npm
  Browsers:
    Chrome: 84.0.4147.105
    Firefox: 79.0
  npmPackages:
    @storybook/addon-actions: ^6.0.0-rc.23 => 6.0.0-rc.23 
    @storybook/addon-backgrounds: ^6.0.0-rc.23 => 6.0.0-rc.23 
    @storybook/addon-controls: ^6.0.0-rc.23 => 6.0.0-rc.23 
    @storybook/addon-docs: ^6.0.0-rc.23 => 6.0.0-rc.23 
    @storybook/addon-knobs: ^6.0.0-rc.23 => 6.0.0-rc.23 
    @storybook/addon-storysource: ^6.0.0-rc.23 => 6.0.0-rc.23 
    @storybook/addon-viewport: ^6.0.0-rc.23 => 6.0.0-rc.23 
    @storybook/addons: ^6.0.0-rc.23 => 6.0.0-rc.23 
    @storybook/react: ^6.0.0-rc.23 => 6.0.0-rc.23
```

**Comment by shilman** [comment] 2020-08-13 01:39
Do you have a repro I can look at?

**Comment by angrycat9000** [comment] 2020-08-19 19:05
I'm seeing the same error message when I am trying to set up a basic web components story.  It also isn't showing a control to adjust the value.  

![image](https://user-images.githubusercontent.com/48362463/90678459-b74df780-e22c-11ea-8df1-6570b30b2f25.png)

**Story**

```javascript
export const test = (args) => {
    return `
        <input type="number" value="${args.value}">`;
};
test.args = {
    value: 5
};
```


**System:**
```
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    npm: 6.13.7 - /usr/local/bin/npm
  Browsers:
    Chrome: 84.0.4147.135
    Firefox: 79.0
    Safari: 13.1.2
  npmPackages:
    @storybook/addon-controls: ^6.0.13 => 6.0.13 
    @storybook/addon-knobs: ^6.0.13 => 6.0.13 
    @storybook/web-components: ^6.0.13 => 6.0.13 
```

**Comment by tknickman** [comment] 2020-08-19 19:45
I'm seeing the same thing (control labels are there, but no values or options to change the values). 

It's working again if I downgrade back to 6.0.7 (possibly later as well but I haven't had time to check, we were on 6.0.7 when it was working last so I just reverted the update).

**Comment by tknickman** [comment] 2020-08-19 20:07
Ok did a little more testing. All is good for using `6.0.9`, but breaks at `6.0.10`

**Comment by angrycat9000** [comment] 2020-08-19 20:19
> Ok did a little more testing. All is good using `6.0.9`, but breaks at `6.0.10`

Thanks for the insight about the versions.  I just tested in my environment and can confirm the same behavior.

**Comment by tknickman** [comment] 2020-08-19 20:40
Yea seems to be caused by this, definitely related code here. I just don't know enough about the internals to through up a PR yet 😄 

https://github.com/storybookjs/storybook/pull/12048

**Comment by jwoo0122** [comment] 2020-08-24 13:11
I entered same issue, and this is my solution.
```tsx
import { Button } from './Buttons'

export default {
  title: 'Button',
  component: Button,
  argTypes: {
    disabled: { control: { type: 'boolean' } },
  },
}

const Template = (args) => <Button {...args} />

export const Primary = Template.bind({})
Primary.args = { disabled: false }
```

Still this solution makes controls work, but I didn't figured out what's the problem.

**Comment by jwoo0122** [comment] 2020-08-26 08:38
For me this was resolved by update to 6.0.18
```shell
npx sb@next upgrade
```

**Comment by shilman** [comment] 2020-08-26 09:02
I think this was fixed in #12230 and released in 6.0.18, so i'm going to close this. please let me know if the latest release doesn't fix it for you.

**Closed by shilman** 2020-08-26 09:02 UTC
Labels: addon: controls, bug, needs reproduction, tracked

**Comment by rwwagner90** [comment] 2021-07-01 11:07
This doesn't seem to work for Vue. The only way to get controls is to manually define everything in `argTypes`. Should it be working for Vue?

**Comment by shilman** [comment] 2021-07-02 08:47
@rwwagner90 this should work for vue. there are a lot of different ways to write vue components (SFC, jsx, etc.) but the common ones should be supported. if you want to open a new issue with a repro from `npx sb@next repro` I'd be happy to take a look.
