### ISSUE TITLE
[addon:google-analytics] throws "path is required in .pageview()" error

### ISSUE THREAD

**Issue by thundermiracle** [storybookjs/storybook#6012] opened 2019-03-11 06:23 UTC
**Describe the bug**
throws `[react-ga] path is required in .pageview()` when upgrade to storybook 5.0.x

**To Reproduce**
1. add addon-google-analytics
1. select another story after page loaded

**Expected behavior**
No error throws.

**Screenshots**
https://thundermiracle.github.io/storybook-loader/?path=/story/documentation-basic--description
then open the debug console and change to another story

**Code snippets**
```js
import '@storybook/addon-google-analytics/register';
window.STORYBOOK_GA_ID = 'UA-119418003-1';
```

**System:**
 - OS: Windows10
 - Device: PC
 - Browser: chrome
 - Framework: react
 - Addons: google-analytics
 - Version: 5.0.0 (same in 5.0.1)

**Additional context**
api.getUrlState() returns { url: undefined } instead of { url: '/xxx/xxxx' } after upgrade to 5.0.x.
Is there something missing in core/context.js?

**Comment by jholt1** [comment] 2019-04-29 15:02
@shilman @thundermiracle Should this issue be closed? I don't see that it has been fixed in Storybook.

**Comment by happinessEngineer** [comment] 2019-06-19 20:28
I am seeing the same issue with the latest version of the addon and storybook/react (both v5.1.8).

**Comment by ndelangen** [comment] 2019-07-13 10:00
I cannot reproduce, using the @thundermiracle steps to reproduce, this https://thundermiracle.github.io/storybook-loader/?path=/story/documentation-basic--description seems to not log errors for me.

What am I doing wrong, or has this been fixed?

**Comment by thundermiracle** [comment] 2019-07-13 13:18
@ndelangen Sorry, I fixed it by [customizing google-analytics](https://github.com/thundermiracle/storybook-loader/pull/19/files) addon, so the steps to reproduce is wrong.

**Comment by soundasleep** [comment] 2019-10-18 02:14
This behaviour is still broken in 5.1.11.

```
[react-ga] path is required in .pageview()
```

**Comment by shilman** [comment] 2019-11-30 13:26
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.7 containing PR #8468 that references this issue. Upgrade today to try it out!

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2019-11-30 13:26 UTC
Labels: addon: analytics, bug
