### ISSUE TITLE
Maximum call stack size exceeded in react app

### ISSUE THREAD

**Issue by fikyair** [storybookjs/storybook#15593] opened 2021-07-15 03:48 UTC
**Describe the bug**
```
export const Tree: FC<TreeProps> = (props) => { 
  const keyToNodeMap = useRef<KeyToNodeMap>({})
  const [data, setData] = useState<TreeSource>(props.treeData)
  const doTranslate = useCallback((children: Array<TreeSource>, parent: TreeSource)=>{
    children.forEach((item: TreeSource) => {
      item.parent = parent
      keyToNodeMap.current[item.key] = item
      if(item.children && item.children.length > 0) {
        doTranslate(item.children, item)
      }
    })
  }, [])

  useEffect(() => {
    keyToNodeMap.current[data.key] = data
    if(data.children && data.children.length > 0) {
      // doTranslate(data.children, data)        **open this will report the bug** 
    }
  }, [data, doTranslate])

  return (
    <div className={sc('tree')}> 
      <div className={sc('tree-nodes')}>
        <TreeNode
          data={data}
          onCollapse={onCollapse}
          onCheck={onCheck}
        />
      </div>
    </div>
  )
}
export default Tree;
```

When the page is loaded for the first time, it is fine, but when I switch the sidebar, an error will be reported
![image](https://user-images.githubusercontent.com/18121040/125729257-2ee3c8a1-d456-4257-b260-8f569496a96a.png)

```
    "@storybook/addon-a11y": "^6.3.2",
    "@storybook/addon-actions": "6.3.2",
    "@storybook/addon-docs": "^6.3.2",
    "@storybook/addon-essentials": "^6.3.2",
```

**To Reproduce**

My Project:

https://github.com/ChocolateUI/chocolate-ui/blob/8f30fc55be25ce49cef938fd0427d5759d74077b/src/components/Tree/tree.tsx#L72

**System**
macOS 11.2.3
chrome 91.0.4472.114

**Additional context**

**Comment by marko-hologram** [comment] 2021-07-15 11:09
"Maximum call stack size exceeded" is usually an indication you are having an infinite loop in your code. I doesn't look like a problem with Storybook itself. I see that `doTranslate` function is being called recursively so that's the first place you are supposed to look. Your code potentially just has some logic bug.

**Comment by fikyair** [comment] 2021-07-16 00:08
> "Maximum call stack size exceeded" is usually an indication you are having an infinite loop in your code. I doesn't look like a problem with Storybook itself. I see that `doTranslate` function is being called recursively so that's the first place you are supposed to look. Your code potentially just has some logic bug.

After debugging, I found that the doTranslate function was not started at all when switching the sidebar, and the useEffect was not even executed. Did storybook make some internal caching which caused memory overflow?

**Comment by marko-hologram** [comment] 2021-07-17 09:41
> 
> 
> > "Maximum call stack size exceeded" is usually an indication you are having an infinite loop in your code. I doesn't look like a problem with Storybook itself. I see that `doTranslate` function is being called recursively so that's the first place you are supposed to look. Your code potentially just has some logic bug.
> 
> After debugging, I found that the `doTranslate` function was not started at all when switching the sidebar, and the `useEffect` was not even executed. Did `storybook` make some internal caching which caused memory overflow?
> Looking forward to your answer

Oh sorry, I'm not a Storybook maintainer or anything. I just noticed this error message which is usually tied to infinite loops in code. I just noticed you have a recursive function and thought that would be a good place to start looking. Hopefully someone else might help you more.

**Comment by alk-mandrianarijaona** [comment] 2021-07-21 15:17
hello @fikyair, do you have a repository we can check to reproduce this? I tend to share @marko-hologram's idea but seeing the project altogether can be really helpful

**Comment by fikyair** [comment] 2021-07-23 04:09
> reproduce



> hello @fikyair, do you have a repository we can check to reproduce this? I tend to share @marko-hologram's idea but seeing the project altogether can be really helpful

https://github.com/ChocolateUI/chocolate-ui/blob/8f30fc55be25ce49cef938fd0427d5759d74077b/src/components/Tree/tree.tsx#L72




> hello @fikyair, do you have a repository we can check to reproduce this? I tend to share @marko-hologram's idea but seeing the project altogether can be really helpful

https://github.com/ChocolateUI/chocolate-ui/blob/8f30fc55be25ce49cef938fd0427d5759d74077b/src/components/Tree/tree.tsx#L72

I found out that `item.parent = parent` in `doTranslate` triggered the circular reference

**Comment by fikyair** [comment] 2021-07-23 04:10
> hello @fikyair, do you have a repository we can check to reproduce this? I tend to share @marko-hologram's idea but seeing the project altogether can be really helpful

https://github.com/ChocolateUI/chocolate-ui/blob/8f30fc55be25ce49cef938fd0427d5759d74077b/src/components/Tree/tree.tsx#L72

I found out that `item.parent = parent` in `doTranslate` triggered the circular reference

**Comment by marko-hologram** [comment] 2021-07-23 07:43
> 
> 
> > hello @fikyair, do you have a repository we can check to reproduce this? I tend to share @marko-hologram's idea but seeing the project altogether can be really helpful
> 
> https://github.com/ChocolateUI/chocolate-ui/blob/8f30fc55be25ce49cef938fd0427d5759d74077b/src/components/Tree/tree.tsx#L72
> 
> I found out that `item.parent = parent` in `doTranslate` triggered the circular reference

Great that you found the issue! I guess you can close this GitHub issue now since everything is resolved?

**Comment by fikyair** [comment] 2021-07-23 08:14
> > > hello @fikyair, do you have a repository we can check to reproduce this? I tend to share @marko-hologram's idea but seeing the project altogether can be really helpful
> > 
> > 
> > https://github.com/ChocolateUI/chocolate-ui/blob/8f30fc55be25ce49cef938fd0427d5759d74077b/src/components/Tree/tree.tsx#L72
> > I found out that `item.parent = parent` in `doTranslate` triggered the circular reference
> 
> Great that you found the issue! I guess you can close this GitHub issue now since everything is resolved?

I will refactor the code and give you a reply，thank you

**Closed** 2021-07-27 06:28 UTC
Labels: needs triage, question / support

**Comment by fikyair** [comment] 2021-07-27 06:30
This part of the reconstruction has been completed, it is a problem with my code, thank you all
