### ISSUE TITLE
Experiencing some CORS issue in `v6.0.0` while using storybook composition feature.

### ISSUE THREAD

**Issue by rannyeli** [storybookjs/storybook#11892] opened 2020-08-11 10:52 UTC
Experiencing some CORS issue in `v6.0.0` while using storybook composition feature.
I'm adding a ref for a local storybook:
```
refs: {
    react_components: { 
      title: "React Components", 
      url: "http://localhost:9010"
    },
```
The local storybook works well on port 9010, but not loaded from the combined storybook 
![image](https://user-images.githubusercontent.com/42379604/89799674-74a66400-db36-11ea-8a7a-7253be8dfab3.png)

dev-tools output:
![image](https://user-images.githubusercontent.com/42379604/89800579-a9ff8180-db37-11ea-9b9c-dfd0914ccf24.png)

```
node - v14.5.0
react - v16.13.1
```
In addition, I would like to know if there is an option to give a path of the storybook build directory as a url of ref?

_Originally posted by @rannyeli in https://github.com/storybookjs/storybook/issues/9311#issuecomment-671426067_

**Comment by tmeasday** [comment] 2020-08-11 14:47
@rannyeli -- can you check the network tab -- there should be a "no cors" fetch request to `http://localhost:9010/iframe.html` also -- is that failing also?

**Comment by rannyeli** [comment] 2020-08-11 15:42
@tmeasday `http://localhost:9010/iframe.html` works and returns 200.

**Comment by tmeasday** [comment] 2020-08-12 01:54
@rannyeli -- to be clear -- do you mean that you yourself browsed there, or that the request that SB makes in the background worked?

**Comment by tmeasday** [comment] 2020-08-12 06:15
OK, I reproduced this. @ndelangen the bug here is the assumption encoded in this test:

https://github.com/storybookjs/storybook/blob/824fe5402f9e6f63c5a4b3474ee247ab69bb86c1/lib/api/src/tests/refs.test.js#L601:L601

and in these lines: 

https://github.com/storybookjs/storybook/blob/824fe5402f9e6f63c5a4b3474ee247ab69bb86c1/lib/api/src/modules/refs.ts#L68-L71

When you do a `no-cors` fetch, even if it works, `ok` is `false` it seems:

<img width="593" alt="image" src="https://user-images.githubusercontent.com/132554/89981312-01782b80-dcb7-11ea-92e8-7029fc05eafb.png">

**Comment by tmeasday** [comment] 2020-08-12 06:26
@ndelangen there is an issue here because there is no way to tell if a `mode: 'no-cors'` request 404s or otherwise. We need to go over this again.

**Comment by tmeasday** [comment] 2020-08-12 10:44
I suspect the obvious solution is to add CORS headers to the dev server.

**Comment by TechieQian** [comment] 2020-08-15 15:11
I built storybook static and served the assets from a cors enabled python http server. 

I was able to get the right response headers (Access-Control-Allow-Origin: *). 

But I was still getting a cors issue for `stories.json`. I actually don't see any `stories.json` being generated. Is this a different issue? Also, do all versions of storybook within the composition need to be version >6 ? Or just the "frame" ?

**Comment by TechieQian** [comment] 2020-08-15 22:25
Thanks it works now! I think it would be beneficial to add `npx sb extract` to composition documentations. I've never used chromatic so `stories.json` is new to me.

**Comment by ndelangen** [comment] 2020-08-17 06:43
> there is no way to tell if a mode: 'no-cors' request 404s or otherwise. We need to go over this again.

if there's no method to determine if a `no-cors` request succeeded of failed to can remove that check entirely, but we're left with a bug where if the composed storybook 404's it will just be in a pending state forever.

**Comment by basher** [comment] 2020-08-17 08:06
I get the same CORS error while trying out composition for the first time. 

I'm using `@storybook/html": "^6.0.4"`.

I get `200 OK response` for both `stories.json` and `iframe.html`.

Here's a screenshot of my response:

![storybook-composition-response-payload](https://user-images.githubusercontent.com/452809/90372158-dc453d80-e067-11ea-9046-200e3700af1c.jpg)

I've highlighted the empty HTML storybook in the left menu, and the response which shows what should be displayed in the story iframe.

------------------

Question:
Before trying composition, I was using standalone Storybook to preview my HTML stories, because I use Parcel bundler rather than Webpack.

i.e. I ran `npm run storybook -- --preview-url=http://localhost:1337/iframe.html` to view my HTML (with Parcel) stories.

**Is Storybook composition a replacement for standalone?**

**Comment by ndelangen** [comment] 2020-08-17 09:05
related:
https://github.com/storybookjs/storybook/pull/11783

**Comment by ndelangen** [comment] 2020-08-17 09:16
> I suspect the obvious solution is to add CORS headers to the dev server.
Should be easy enough to do!

**Comment by tmeasday** [comment] 2020-08-17 11:09
| **Mode**                | **stories.json w/ credentials** | **stories.json no credentials** | **iframe.html no cors** | **iframe.html w/ credentials** | **iframe.html no credentials** | **iframe.html from node** |
| ----------------------- | ------------------------------- | ------------------------------- | ----------------------- | ------------------------------ | ------------------------------ | ------------------------- |
| Chromatic(public)       | ✅                               | ✅                               | ❌                       | ✅                              | ✅                              | ✅                         |
| Chromatic (private)     | ✅                               | ✅                               | ❌                       | ✅                              | ✅                              | 403                       |
| Netlify                 | ❌                               | 404                             | ❌                       | ❌                              | ✅                              | ✅                         |
| Netlify w/ stories.json | ❌                               | ✅                               | ❌                       | ❌                              | ✅                              | ✅                         |
| SB6 dev mode            | 404                             | 404                             | ❌                       | ✅                              | ✅                              | ✅                         |
| SB5 dev mode            | ❌                               | ❌                               | ❌                       | ❌                              | ❌                              | ✅                         |
| Broken ref              | ❌                               | ❌                               | ❌                       | ❌                              | ❌                              | 404                       |

**Comment by ndelangen** [comment] 2020-08-18 12:35
PR is open, with a fix

**Comment by shilman** [comment] 2020-08-20 08:19
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.14 containing PR #12085 that references this issue. Upgrade today to try it out!

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2020-08-20 08:19 UTC
Labels: composition, question / support, tracked
