### ISSUE TITLE
[addon-docs] Linking to sections.

### ISSUE THREAD

**Issue by ellisio** [storybookjs/storybook#8184] opened 2019-09-24 21:50 UTC
I am using `@storybook/addon-docs@5.2.1`. Is it possible to link to a header further in the document? We have sections that are quite long and would love to link between parts of the page.

GitHub Wiki markdown would be something like this:

```md
<Meta title="Design System|Some Page" />

## Foo

Hey, check out [Bar][#Bar]

// Imagine several hundreds of lines of markdown here.

## Bar

This is Bar! Way below the page fold.
```

I know there is `@storybook/addon-links`, but I'm not sure that works in the MDX stories from what I've gathered poking through the GitHub issues here.

**Comment by shilman** [comment] 2019-09-24 22:27
I'm not sure! MDX support is still early and we might need to add this in 5.3!

**Comment by kamranayub** [comment] 2019-10-04 15:53
Additionally, perhaps a separate issue, but `docs` ingests the JSDoc on a component, and in a large component library it'd be awesome to easily link between components. For example, this would be a common case of composed components:

```js
/**
 * A higher-level component that does a thing. Use the `isOpen` 
 * prop to control the internal [[BuildingBlock]] component.
 */
const Composition = ({ isOpen }) => (
  <BuildingBlock isOpen={isOpen} />
);
```

## Prior Art

In [TypeDoc](https://typedoc.org/guides/doccomments/#symbol-references) for example the `[[symbol|display text]]` syntax denotes an internal symbol link, making it real easy to link between API symbols. Perhaps in `docs`, it could look at the `component` parameter for stories to link between known components.

```
[[BuildingBlock]] => http://localhost:9009/?path=/docs/building-block--primary
[[BuildingBlock#story]] => http://localhost:9009/?path=/docs/building-block--story
```

Alternatively, both TypeDoc and [TSDoc](https://github.com/microsoft/tsdoc) uses JSDoc `@link path | title` syntax.

**Comment by Fleuv** [comment] 2019-11-15 10:33
It's possible to do something like this:

```
## Foo

Hey, check out [Bar][#Bar]

// Imagine several hundreds of lines of markdown here.

## Bar <a id="Bar" />

This is Bar! Way below the page fold.
```

# Some tests on Firefox v70

The `href` of the first anchor will be `#Bar` as expected, although for some reason after clicking the URL ends up using the `iframe.html` page:

```
http://localhost:6006/iframe.html?id=foo--bar&viewMode=docs#Bar
```

While I expected it to use the default index:

```
http://localhost:6006/?path=/docs/foo--bar#Bar
```

Also I noticed that neither the `iframe.html` as the default index page was capable of scrolling down to the target anchor on initial load. However at the `iframe.html` page I was able to scroll down to the target anchor by clicking the anchor with the href. This didn't work for the default index page after changing the href to the absolute url mentioned above.

**Comment by shilman** [comment] 2019-11-15 22:04
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.46 containing PR #8132 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by robbeman** [comment] 2019-11-20 09:32
> Using `LinkTo` as mention in #8618 doesn't work at all.

The question there was to link to another story, not to link to a page anchor. In my case it did work to link to other stories. I did not test anchors, so I'm sorry if I caused confusion on that part.

**Comment by shilman** [comment] 2019-12-04 04:16
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-beta.15 containing PR #9051 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2019-12-04 04:16 UTC
Labels: addon: docs, feature request, todo

**Comment by nik72619c** [comment] 2020-06-12 13:48
Hi, could someone please link me to the sample code snippet to test it out ?

**Comment by lisamartin00** [comment] 2020-07-22 04:14
@nik72619c you should get anchors on headers for free on .mdx files.  So for example, I can link to the props section of this story:
https://storybookjs.netlify.app/official-storybook/?path=/docs/addons-docs-mdx-id--hello-story#props

Or here's a way to add them globally based off of [this example](https://github.com/storybookjs/storybook/blob/master/addons/docs/docs/recipes.md#csf-stories-with-arbitrary-mdx) (although I'm super new to `addon-docs`, so maybe there's a better way):

`preview.js`
```
import { DocsContainer } from '@storybook/addon-docs/blocks';
import { addParameters } from "@storybook/react";
import DocsPageTemplate from '../src/DocsPageTemplate.mdx';

addParameters({
  docs: {
    container: DocsContainer,
    page: DocsPageTemplate,
  },
});
```

`DocsPageTemplate.mdx`
```
import {
  Title,
  Subtitle,
  Description,
  Primary,
  Props,
  Stories,
} from '@storybook/addon-docs/blocks';

<Title />

Hey there, [Props](#props) are below

<Subtitle />
<Description />
<Primary />

## Props
<Props />

<Stories />
```

**Comment by cgreene-st** [comment] 2021-12-06 21:25
@lisamartin00 I'm not seeing it work the way I'd expect. Not sure if somethings changed since then, but If I go to click on `## Welcome` it's stripping out the `?path` part in the URL and brining me to an empty page. 

I might create a ticket with a minimum reproducible bug because I don't think this is working as intended  

![image](https://user-images.githubusercontent.com/91043238/144924777-7eef548d-7dc6-4f71-9ea1-2271a8774a23.png)
![image](https://user-images.githubusercontent.com/91043238/144924601-93605098-8b96-4189-8b29-c641ac73c8b4.png)

**Comment by lisamartin00** [comment] 2021-12-07 17:01
@cgreene-st  yes I agree - that is easily reproducible on their site, so it's probably either a regression or anchors in are handled differently now since it's been over a year.  sounds like it's worth filing a separate ticket 👍

**Comment by cgreene-st** [comment] 2021-12-07 20:14
For anyone that finds themselves here, the bug is being tracked here #16918
