### ISSUE TITLE
Compilation fails with error TS2305: Module '"parse5"' has no exported member 'ElementLocation'.

### ISSUE THREAD

**Issue by mvaljento** [storybookjs/storybook#19793] opened 2022-11-09 20:46 UTC
I followed this tutorial to install Storybook into my new NX monorepo with an Angular app and libraries:

https://nx.dev/recipes/storybook/one-storybook-for-all

Up to that point everything compiled and the Storybook page opened saying I have no stories. I then created a simple button component with a few inputs and outputs and ran "nx generate @nrwl/angular:stories" for the component. So far so good, no errors. However, when now trying to run Storybook with "nx storybook stories" ("stories" being the name of my Storybook host library as described in the tutorial), I get a huge list of errors and the compilation fails. 

For example:

Error: node_modules/@types/jsdom/base.d.ts:5:10 - error TS2305: Module '"parse5"' has no exported member 'ElementLocation'.

Error: node_modules/@types/webpack/index.d.ts:32:3 - error TS2305: Module '"tapable"' has no exported member 'Tapable'.

Error: node_modules/@types/webpack/index.d.ts:1083:28 - error TS2707: Generic type 'AsyncSeriesWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.

Etc.

What am I doing wrong and is the tutorial missing something.

Relevant (?) library versions (in dev dependencies):

"@nrwl/angular": "14.8.4",
"@nrwl/cli": "14.8.4",
"@storybook/addon-essentials": "~6.5.9",
"@storybook/angular": "~6.5.9",
"@storybook/builder-webpack5": "~6.5.9",
"@storybook/core-server": "~6.5.9",
"@storybook/manager-webpack5": "~6.5.9",
"@types/node": "16.11.7",
"ts-node": "10.9.1",
"typescript": "~4.8.2",
"webpack": "^5.64.0",
"@nrwl/storybook": "^15.0.13"

I have attached some relevant codes (mostly based on the tutorial).

```
const rootMain = require('../../../.storybook/main');

module.exports = {
  ...rootMain,

  core: { ...rootMain.core, builder: 'webpack5' },

  stories: [
    ...rootMain.stories,
    '../../**/*.stories.mdx',
    '../../**/*.stories.@(js|jsx|ts|tsx)',
  ],
  addons: [...rootMain.addons],
  webpackFinal: async (config, { configType }) => {
    // apply any global webpack configs that might have been specified in .storybook/main.js
    if (rootMain.webpackFinal) {
      config = await rootMain.webpackFinal(config, { configType });
    }

    // add your own webpack tweaks if needed

    return config;
  },
};

```
_libs/stories/.storybook/main.js_

```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "emitDecoratorMetadata": true
  },

  "exclude": ["../**/*.spec.ts"],
  "include": [
    "../../**/*.stories.ts",
    "../../**/*.stories.js",
    "../../**/*.stories.jsx",
    "../../**/*.stories.tsx",
    "../../**/*.stories.mdx",
    "*.js"
  ]
}

```
_libs/stories/.storybook/tsconfig.json_

```
import { moduleMetadata, Story, Meta } from "@storybook/angular";
import { ButtonComponent } from "./button.component";

export default {
  title: "ButtonComponent",
  component: ButtonComponent,
  decorators: [
    moduleMetadata({
      imports: []
    })
  ]
} as Meta<ButtonComponent>;

const Template: Story<ButtonComponent> = (args: ButtonComponent) => ({
  props: args
});

export const Primary = Template.bind({});
Primary.args = {
  label: "",
  icon: "",
  disabled: false
};

```
_button.component.stories.ts_

**Comment by shilman** [comment] 2022-11-10 03:01
What package manager/version are you using? Looks like it might be a hoisting issue. Maybe somebody from Nx can chime in here? cc @mandarini

**Comment by mvaljento** [comment] 2022-11-10 07:48
@shilman Thanks for the quick response. I'm running npm 8.18.0 with node v16.15.0.

**Comment by mandarini** [comment] 2022-11-10 10:38
I'll look into it! @mvaljento the tutorial has a repo attached. Can you see lots of differences between your code and the repo? Does the example repo work on your machine?

**Comment by mvaljento** [comment] 2022-11-10 15:31
@mandarini Yes, the repo works. I didn't find much difference to my code except course my app is based on Angular and the tutorial is React, but also my code base contains a lot of project specific stuff. However, there are only story files in the simple button component I added. Also in the repo there's a .storybook folder under a button library, but that does not seem to be used as the story code (as in my example) references the "'../../../../../.storybook/main" file.

Other than that there were only minor differences in the .storybook/main.js which I replaced with the one from the repo, but that had no effect. Also the tutorial repo contained some React specific configurations in Storybook tsconfig:

```
"files": [
    "../../../node_modules/@nrwl/react/typings/styled-jsx.d.ts",
    "../../../node_modules/@nrwl/react/typings/cssmodule.d.ts",
    "../../../node_modules/@nrwl/react/typings/image.d.ts"
  ],
```

**Comment by mvaljento** [comment] 2022-11-10 19:27
@mandarini I tried removing all the unnecessary code etc. and still got the same errors. I have now shared my code in a public repo here, if you want to give running it a shot.

https://github.com/mvaljento/monorepo

**Comment by mandarini** [comment] 2022-11-10 21:16
Hi there @mvaljento ! Thanks for taking the time to put this together. I'll try to take a look at it tomorrow!

**Comment by mandarini** [comment] 2022-11-11 09:07
Hello @mvaljento ! I just cloned your repo, ran `yarn` and then ran `nx storybook stories` and it works just fine. Here's the log: https://app.warp.dev/block/Q37r5KntUXnGpwZNmqPy0h

And here's a screenshot of Storybook running
<img width="1167" alt="Screenshot 2022-11-11 at 11 06 48 AM" src="https://user-images.githubusercontent.com/6603745/201305757-87b0dcdd-d0ba-4c3d-8bb3-49270f973e56.png">

Can you try deleting your node_modules and installing again?

Here's what I get when I run `nx report` in your repo:

```
nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.13.0
   OS   : darwin x64
   yarn : 1.22.17

   nx : 14.8.4
   @nrwl/angular : 14.8.3
   @nrwl/cypress : 14.8.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.8.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 14.8.4
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.8.4
   @nrwl/js : 14.8.3
   @nrwl/linter : 14.8.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.7.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 999.9.1
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.13
   @nrwl/web : 999.9.1
   @nrwl/webpack : 14.8.3
   @nrwl/workspace : 14.8.4
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @ngrx/effects: 14.3.2
   	 @ngrx/entity: 14.3.2
   	 @ngrx/router-store: 14.3.2
   	 @ngrx/schematics: 14.3.2
   	 @ngrx/store: 14.3.2
   	 @ngrx/store-devtools: 14.3.2
   	 @storybook/angular: 6.5.13

```

**Comment by mvaljento** [comment] 2022-11-12 14:27
@mandarini Thanks very much for testing it. Indeed, I can get it working if I install the packages with yarn! However if I use npm (which I normally do) I still get the same errors even with the freshly pulled test repo. I tried upgrading to the latest npm 9, but it didn't help. 

I can keep using yarn, since it seems to work, however would be useful and interesting to understand the reason. I'm not very savvy with different package managers and their differences, however, so I'm clueless why npm fails to work. Maybe it installs slightly different versions?

**Comment by mandarini** [comment] 2022-11-14 10:05
Intersting. I'll test with `npm` and let you know!

**Comment by mandarini** [comment] 2022-11-14 11:09
So, the thing is, in YOUR repository, I CAN reproduce the error using `npm`. If I create a new repository, either using Nx 14.8.4 (which you are using), either using the latest version of Nx, with `npm`, I cannot reproduce the error. Everything runs smoothly.

**Comment by mandarini** [comment] 2022-11-14 11:21
OOoooookkk!!!! Here are the changes I did to your `tsconfig.base.json` and got it to work!!!!! :D

![Screenshot 2022-11-14 at 1 21 06 PM](https://user-images.githubusercontent.com/6603745/201647621-1841622f-6a14-4edf-97a6-48b59a5c616b.png)

**Comment by mandarini** [comment] 2022-11-14 11:28
Let me know when you get it to work, and I'll close the issue!

**Comment by mvaljento** [comment] 2022-11-14 14:39
@mandarini Yes, it works now also with npm when I added the compiler options! Thanks!

**Closed** 2022-11-14 14:40 UTC
Labels: bug, app: angular, nx
