### ISSUE TITLE
[Bug]: JsDocs descriptions do not work in storybook.new stackblitz

### ISSUE THREAD

**Issue by miszol1** [storybookjs/storybook#25972] opened 2024-02-09 09:16 UTC
### Describe the bug

Descriptions in Docs tab in stackblitz from storybook.new - angular cli, are not displayed.

### To Reproduce

https://stackblitz.com/github/storybookjs/sandboxes/tree/next/angular-cli/default-ts/after-storybook?file=src%2Fstories%2Fbutton.stories.ts&preset=node

Or go to storybook.new > angular CLI > Buttons > Docs page

**Comment by jonniebigodes** [comment] 2024-02-09 16:39
@miszol1, thanks for taking the time to reach out to us and let us know of this situation. We appreciate it 🙏 ! I was able to confirm this, and it seems that it goes back to the `8.0.0-beta.0`. I tested it locally on some reproductions, and it seems that this is happening not only in Angular but also in:
- Web components (JS/TS)
- Solid.js (JS/TS)
- Preact (JS/TS)

Here's a small recording showcasing the issue

https://github.com/storybookjs/storybook/assets/22988955/18d5b17f-49cb-4c2f-9d23-ae36a415663b


cc @valentinpalkovic, @kasperpeulen, @JReinhold

**Comment by valentinpalkovic** [comment] 2024-03-13 14:18
The issue is fixed for Angular. Investigating Web components, Solid.js and Preact

**Comment by valentinpalkovic** [comment] 2024-03-13 15:02
@jonniebigodes 

So, for web components, there is a way to set up component analysis, but it is not set up by default when Storybook is initialized. Therefore, it doesn't appear in stackblitz. For Preact, there is an open issue with a huge PR to introduce component analysis for it, but it's not merged yet. 

Same for Solid.js: There isn't any component analysis. Closing this issue.

**Closed by valentinpalkovic** 2024-03-13 15:02 UTC
Labels: bug, angular, preact, web-components, argtypes, solid, sev:S2

**Comment by jonniebigodes** [comment] 2024-03-13 15:46
@valentinpalkovic, I appreciate you following up with me on this. Thanks for the heads up. I'll adjust accordingly.
