### ISSUE TITLE
[Bug]: migration of .eslintrc.json is generating an erroneous value for `extends`

### ISSUE THREAD

**Issue by rodrigc** [storybookjs/storybook#23178] opened 2023-06-21 14:27 UTC
### Describe the bug

While running migrations in NX, I ran into this problem: https://github.com/nrwl/nx/issues/17659 
which is called by a migration in storybook.

Before the migration, I had an `.eslintrc.json` that looked like:

```
{
  "root": true,
  "ignorePatterns": ["**/*"],
  "plugins": ["@nrwl/nx"],
  "overrides": [
    {
      "files": ["*.ts", "*.tsx", "*.js", "*.jsx"],
      "rules": {
        "@nrwl/nx/enforce-module-boundaries": [
          "error",
          {
            "allow": ["^@qi/.*$", "^@qn/.*$"],
            "enforceBuildableLibDependency": true,
            "depConstraints": [
              {
                "sourceTag": "*",
                "onlyDependOnLibsWithTags": ["*"]
              }
            ]
          }
        ]
      }
    },
    {
      "files": ["*.ts", "*.tsx"],
      "extends": ["plugin:@nrwl/nx/typescript"],
      "rules": {
        "@typescript-eslint/ban-ts-comment": 0,
        "@typescript-eslint/no-empty-function": 0,
        "@typescript-eslint/no-var-requires": 0,
        "@typescript-eslint/no-explicit-any": 0,
        "@typescript-eslint/no-unused-vars": [
          1,
          {
            "argsIgnorePattern": "^_"
          }
        ]
      }
    },
    {
      "files": ["*.js", "*.jsx"],
      "extends": ["plugin:@nrwl/nx/javascript"],
      "rules": {}
    }
  ]
}
```

After the migration it looked like this:

```
{
  "root": true,
  "ignorePatterns": ["**/*"],
  "plugins": ["@nx"],
  "overrides": [
    {
      "files": ["*.ts", "*.tsx", "*.js", "*.jsx"],
      "rules": {
        "@nx/enforce-module-boundaries": [
          "error",
          {
            "allow": ["^@qi/.*$", "^@qn/.*$"],
            "enforceBuildableLibDependency": true,
            "depConstraints": [
              {
                "sourceTag": "*",
                "onlyDependOnLibsWithTags": ["*"]
              }
            ]
          }
        ]
      }
    },
    {
      "files": ["*.ts", "*.tsx"],
      "extends": ["plugin:@nx/typescript"],
      "rules": {
        "@typescript-eslint/ban-ts-comment": 0,
        "@typescript-eslint/no-empty-function": 0,
        "@typescript-eslint/no-var-requires": 0,
        "@typescript-eslint/no-explicit-any": 0,
        "@typescript-eslint/no-unused-vars": [
          1,
          {
            "argsIgnorePattern": "^_"
          }
        ]
      }
    },
    {
      "files": ["*.js", "*.jsx"],
      "extends": ["plugin:@nx/javascript"],
      "rules": {}
    }
  ],
  "extends": [null, "plugin:storybook/recommended"]
}
```

This line is invalid:

```
  "extends": [null, "plugin:storybook/recommended"]
```

### To Reproduce

Take an .eslintrc.json that does not have an `extends` variable, and then run the storybook migrations on it.

For example:

```
{
  "root": true,
  "ignorePatterns": ["**/*"],
  "plugins": ["@nrwl/nx"],
  "overrides": [
    {
      "files": ["*.ts", "*.tsx", "*.js", "*.jsx"],
      "rules": {
        "@nrwl/nx/enforce-module-boundaries": [
          "error",
          {
            "allow": ["^@qi/.*$", "^@qn/.*$"],
            "enforceBuildableLibDependency": true,
            "depConstraints": [
              {
                "sourceTag": "*",
                "onlyDependOnLibsWithTags": ["*"]
              }
            ]
          }
        ]
      }
    },
    {
      "files": ["*.ts", "*.tsx"],
      "extends": ["plugin:@nrwl/nx/typescript"],
      "rules": {
        "@typescript-eslint/ban-ts-comment": 0,
        "@typescript-eslint/no-empty-function": 0,
        "@typescript-eslint/no-var-requires": 0,
        "@typescript-eslint/no-explicit-any": 0,
        "@typescript-eslint/no-unused-vars": [
          1,
          {
            "argsIgnorePattern": "^_"
          }
        ]
      }
    },
    {
      "files": ["*.js", "*.jsx"],
      "extends": ["plugin:@nrwl/nx/javascript"],
      "rules": {}
    }
  ]
}
```

### System

```shell
command: npx storybook@latest info

Environment Info:

  System:
    OS: macOS 13.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 20.2.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.6 - /usr/local/bin/npm
  Browsers:
    Safari: 16.5
  npmPackages:
    @storybook/addon-a11y: ^7.0.21 => 7.0.21
    @storybook/addon-actions: ^7.0.21 => 7.0.21
    @storybook/addon-essentials: 7.0.21 => 7.0.21
    @storybook/addon-info: ^5.3.21 => 5.3.21
    @storybook/addon-interactions: ^7.0.21 => 7.0.21
    @storybook/addon-links: ^7.0.21 => 7.0.21
    @storybook/addon-mdx-gfm: ^7.0.21 => 7.0.21
    @storybook/addon-storyshots: ^7.0.21 => 7.0.21
    @storybook/addons: ^7.0.21 => 7.0.21
    @storybook/core-server: 7.0.21 => 7.0.21
    @storybook/nextjs: ^7.0.21 => 7.0.21
    @storybook/react: 7.0.21 => 7.0.21
    @storybook/react-webpack5: ^7.0.21 => 7.0.21
    @storybook/testing-library: ^0.1.0 => 0.1.0
    @storybook/theming: ^7.0.21 => 7.0.21
```
```


### Additional context

I believe that the source of the problem is coming from:

https://github.com/storybookjs/storybook/blob/v7.0.21/code/lib/cli/src/automigrate/helpers/eslintPlugin.ts?rgh-link-date=2023-06-17T02%3A40%3A07Z#L55

if `.eslintrc.json` does not contain an `extends` variable, the migration will still generate something that looks like:

```
"extends": [null, "plugin:storybook/recommended"]
```

**Comment by rodrigc** [comment] 2023-06-21 17:07
My guess is that the problem is coming from here:

https://github.com/storybookjs/storybook/blob/v7.0.21/code/lib/cli/src/automigrate/helpers/eslintPlugin.ts?rgh-link-date=2023-06-17T02%3A40%3A07Z#L55

That code is not properly dealing with the case where `extends` is not not defined in the existing JSON config file for .eslintrc.json

**Comment by rodrigc** [comment] 2023-06-23 10:22
@kylegach I took a whack at fixing the migration here: https://github.com/storybookjs/storybook/pull/23192

**Comment by yannbf** [comment] 2023-08-14 15:33
Hey @rodrigc thank you so much for opening this issue and issuing a PR, and sorry it wasn't taken care of so far.

The current logic in the storybook automigration already takes into account when users do not have the `extends` field in their eslint config. The issue was actually caused by an NX automigration script and got fixed here: https://github.com/nrwl/nx/pull/17750

So I'll be closing this issue and its connecting PR. Thanks once again!

**Closed by yannbf** 2023-08-14 15:33 UTC
Labels: bug, nx, automigrations
