### ISSUE TITLE
CSF stories does not work correctly with addon-storyshots multiSnapshotWithOptions option

### ISSUE THREAD

**Issue by jrsearles** [storybookjs/storybook#7697] opened 2019-08-06 13:41 UTC
**Describe the bug**
I am trying out the beta for 5.2 and have converted several stories over to CSF. What i've found is that when running storyshots, all of the stories in the CSF style end up using the generic snapshot path/file instead of creating the snapshots adjacent to the stories.

**To Reproduce**
1. Run `jest` with the storyshots add on enabled and the "--ci" flag
2. Tests will fail because the snapshots are not in the expected location so are being considered new

**Expected behavior**
The story should use the same location as before to store snapshots.

**Code snippets**
```typescript
// story-snapshots.test.ts
import initStoryshots, { multiSnapshotWithOptions } from "@storybook/addon-storyshots";

initStoryshots({
  test: multiSnapshotWithOptions({})
});
```

**System:**
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.10.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    @storybook/addon-actions: 5.2.0-beta.23 => 5.2.0-beta.23
    @storybook/addon-contexts: 5.2.0-beta.23 => 5.2.0-beta.23
    @storybook/addon-docs: 5.2.0-beta.23 => 5.2.0-beta.23
    @storybook/addon-knobs: 5.2.0-beta.23 => 5.2.0-beta.23
    @storybook/addon-storyshots: 5.2.0-beta.23 => 5.2.0-beta.23
    @storybook/addon-storyshots-puppeteer: 5.2.0-beta.23 => 5.2.0-beta.23
    @storybook/addon-viewport: 5.2.0-beta.23 => 5.2.0-beta.23
    @storybook/addons: 5.2.0-beta.23 => 5.2.0-beta.23
    @storybook/preset-scss: ^1.0.2 => 1.0.2
    @storybook/react: 5.2.0-beta.23 => 5.2.0-beta.23
    @storybook/source-loader: 5.2.0-beta.23 => 5.2.0-beta.23
    @storybook/theming: 5.2.0-beta.23 => 5.2.0-beta.23

**Additional context**
I did some tracing and the problem appears to be the the filename for the story is undefined when the snapshot is being validated. I've traced where the filename is being determined:

https://github.com/storybookjs/storybook/blob/0083afde5fee9e7bedb8a8c565f8a72251247b6a/lib/client-api/src/client_api.ts#L187

For CSF stories `m` is `true` here instead of an object. I believe the source may be this line here:

https://github.com/storybookjs/storybook/blob/b6282a8281de8320753054ea56860726a13c5043/lib/core/src/client/preview/start.js#L374

**Comment by shilman** [comment] 2019-08-07 02:45
@jrsearles Good catch cc @tmeasday

**Comment by tmeasday** [comment] 2019-08-07 03:22
🤔 I think CSF opens up the potential for refactoring how storyshots works in a much cleaner way (match on `*.stories.js`, write a Jest loader to map CSF => a test file).

In the short term is there an easy fix to this problem? I don't think we actually know the file name any more -- we could add an optional `module` to the default "component" export and pass that into `storiesOf` if it is there (that would change HMR behaviour, so we'd have to test that)

**Comment by tmeasday** [comment] 2019-08-07 03:22
Or maybe we do know the filename from the req?

**Comment by shilman** [comment] 2019-08-07 03:35
I think we can get the filename from the req as a workaround.

**Comment by jrsearles** [comment] 2019-08-31 00:38
I can contribute with some guidance. This bug will prevent us from switching to CSF format.

**Comment by shilman** [comment] 2019-08-31 04:43
Related: https://github.com/storybookjs/storybook/pull/7330

**Comment by Hypnosphi** [comment] 2019-09-04 23:25
> get the filename from the req

Unfortunately, it's possible only if first argument to `configure` is `req` or `Array<req>`, not `() => Array<exports>`.

**Comment by Hypnosphi** [comment] 2019-09-05 01:00
Workaround: add `{fileName: __filename}` parameters to you CSF stories:

```
export default {
  title: 'My Stories',
  parameters: {fileName: __filename}
}
```

**Comment by shilman** [comment] 2019-10-05 00:40
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.10 containing PR #8000 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2019-10-05 00:40 UTC
Labels: addon: storyshots, bug, csf, has workaround, todo

**Comment by shilman** [comment] 2019-10-07 10:14
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.2 containing PR #8000 that references this issue. Upgrade today to try it out!

**Comment by mazikwyry** [comment] 2019-10-09 09:18
@shilman @Hypnosphi I updated to 5.2.3 added: `'^.+\\.stories\\.jsx?$': '@storybook/addon-storyshots/injectFileName',` to jest.config.js and this is what I get:

`Module @storybook/addon-storyshots/injectFileName in the transform option was not found.`.

Looks like the file is not included in the `@storybook/addon-storyshots` package.

![image](https://user-images.githubusercontent.com/1079965/66468471-7de22280-ea86-11e9-8273-214726d3511f.png)

**Comment by shilman** [comment] 2019-10-09 09:52
@mazikwyry Ugh, this file got filtered out of the publish. I've fixed it here and will re-publish once it's merged: https://github.com/storybookjs/storybook/pull/8354

**Comment by shilman** [comment] 2019-10-10 05:04
@mazikwyry Can you try `5.3.0-alpha.17`? I'l patch it over to 5.2.x at the end of the week.

**Comment by mazikwyry** [comment] 2019-10-11 04:56
@shilman 

I updated to `5.3.0-alpha.17` added: '^.+\\.stories\\.jsx?$': '@storybook/addon-storyshots/injectFileName', to jest.config.js and this is what I get:

![image](https://user-images.githubusercontent.com/1079965/66624814-03ceac80-ebf2-11e9-889a-7e38385b5c22.png)

It also doesn't work when I use a workaround `"^.+\\.stories\\.js$": "./injectFileName",` which works in `5.2.x`.

**Comment by Hypnosphi** [comment] 2019-10-11 08:20
@mazikwyry do you also have `"^.+\\.js$": "babel-jest"` entry?

**Comment by mazikwyry** [comment] 2019-10-11 08:44
Yes I do

```js
  // jest.config.js
  ...
  transform: {
     "^.+\.stories\.jsx?$": "@storybook/addon-storyshots/injectFileName",
    "^.+\\.js$": "babel-jest",
  },
  ...
```

```
    "babel-jest": "^24.5.0",
    "jest": "^24.7.0",
    "jest-haste-map": "^24.7.1",
    "jest-resolve": "^24.7.1",
```

Maybe there is something that I should change additionally for `5.3`?

**Comment by Hypnosphi** [comment] 2019-10-11 11:24
@mazikwyry Can you please create a GitHub repo with minimal reproduction of your issue?
