### ISSUE TITLE
Escaped Pipe creates new table cell

### ISSUE THREAD

**Issue by de-dan** [storybookjs/storybook#6869] opened 2019-05-23 09:15 UTC
**Describe the bug**
**In Storybook-Addon-Notes**: I'm using markdown-files with tables. Inside a table-cell I use escaped pipes. These pipes are creating new cells

**To Reproduce**
1. Create a story
2. Use addon notes
3. Create a markdown file with this table:

```
| Attribute    | Type                  |
| ------------ | --------------------- |
| `position`   | `"left" \| "right"`   |
```
Which should render this:

| Attribute    | Type                  |
| ------------ | --------------------- |
| `position`   | `"left" \| "right"`   |

But it actually renders like this:

| Attribute    | Type     |            |
| ------------ | ---------| ---------- |
| `position`   | `"left"` | `"right"`  |

**Expected behavior**
Do not ignore escaped pipes. Do not create new table cells.

**Screenshots**
![table](https://user-images.githubusercontent.com/13744542/58240736-e20c8000-7d4b-11e9-9873-2b86fb97ba24.png)

**System:**
 - OS: Windows7
 - Browser: Chrome
 - Addons: Notes
 - Version: 5.0.11

**Comment by robaxelsen** [comment] 2019-07-03 11:50
Same issue here, unfortunately.

I wanted to try and find the root cause, and checked the markdown-to-jsx library for clues, but no similar issue reported there. Anyone have any insights into what part of the code or library is parsing this wrong?

**Comment by robaxelsen** [comment] 2019-07-25 11:10
> I wanted to try and find the root cause, and checked the markdown-to-jsx library for clues, but no similar issue reported there. Anyone have any insights into what part of the code or library is parsing this wrong?

I could investigate this further, and maybe attempt a fix, but would be helpful with some pointers on where in the code to look - or if it's entirely a markdown-to-jsx issue. Pinging some recently active contributors @Gongreg @tmeasday @ndelangen @danielduan.

**Comment by Gongreg** [comment] 2019-07-25 11:13
Hey,

```
  <Markdown>{textAfterFormatted}</Markdown>
```

this is all ondevice-notes addon is doing.
So I assume the issue is in markdown-to-jsx lib

**Comment by robaxelsen** [comment] 2019-07-25 11:16
@Gongreg Thanks! I will try to reproduce with plain markdown-to-jsx, and report any findings to their project. Propose to keep this open for now, for visibility.

**Comment by robaxelsen** [comment] 2019-08-06 07:14
This has now been[ fixed in latest markdown-to-jsx release](https://github.com/probablyup/markdown-to-jsx/releases), `6.10.3`. Huge thanks to @ariabuckles in the underlying simple-markdown for providing a fix and submitting it downstream as well.

Submitted a PR to upgrade the `markdown-to-jsx` version for notes addon.

**Closed** 2019-08-06 10:35 UTC
Labels: addon: notes, bug

**Comment by shilman** [comment] 2019-08-07 03:30
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.24 containing PR #7694 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
