### ISSUE TITLE
Hash removed from url, causing anchor scrolling to break for on page load event

### ISSUE THREAD

**Issue by lisamartin00** [storybookjs/storybook#11677] opened 2020-07-24 06:35 UTC
**Describe the bug**
I believe this is possibly a regression.

**To Reproduce**
1. Go to https://storybookjs.netlify.app/official-storybook/?path=/docs/addons-docs-markdown-docs--page#emphasis
2. Note that you are scrolled down to the `emphasis` section
3. Compare with the next build of storybook: https://next--storybookjs.netlify.app/official-storybook/?path=/story/addons-docs-markdown-docs--page#emphasis
4. Note that you are _not_ scrolled down to the `emphasis` section.  Furthermore, the hash in the URL has been removed.

**Expected behavior**
A user can visit a URL with an anchor that will scroll them to the related content, as shown in steps 1 and 2 above.

**Comment by shilman** [comment] 2020-08-03 13:42
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.24 containing PR #11767 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2020-08-03 13:42 UTC
Labels: addon: docs, bug, tracked

**Comment by irudoy** [comment] 2020-10-13 12:36
I have another case, possibly related to this. Hash also removed from the iframe URL, when I use «Open canvas in new tab». Should I create a new issue, @shilman ?

**Comment by robksawyer** [comment] 2021-08-10 04:08
This seems to still be an issue in `Storybook 6.3.7`.

**Comment by shilman** [comment] 2021-08-10 12:07
@robksawyer When I click on the link in the comment above, it seems to be doing the right thing. Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce).
