### ISSUE TITLE
Vue devtools

### ISSUE THREAD

**Issue by miljan-aleksic** [storybookjs/storybook#1708] opened 2017-08-22 09:52 UTC
Similar to the React devtools [issue](102) with iframes Vue devtools doesn't recognize the Storybooks components. Seems the solution is also similar using the `__VUE_DEVTOOLS_GLOBAL_HOOK__`, although I'm actually not sure if that's up to date.

Anyhow, if finally Vue devtools is not compatible with Storybooks there should be a BIG warning about that.

**Comment by miljan-aleksic** [comment] 2017-08-22 10:01
Ok, I just saw it is already like that in the Vue [iframe file](https://github.com/storybooks/storybook/blob/master/app/vue/src/server/iframe.html.js), but is not working for me.

Checking why...

**Comment by miljan-aleksic** [comment] 2017-08-22 10:28
Ok, I see Events are getting registered, but no components. Can somebody confirm this or say it does work for him?

**Comment by kazupon** [comment] 2017-08-22 14:48
related:
https://github.com/storybooks/storybook/pull/1376
https://github.com/vuejs/vue-devtools/pull/361

**Comment by ndelangen** [comment] 2017-08-25 21:23
So to answer here, Currently this does not work, 

It's a remote issue being addressed inside the vue-devtools. There's progress being made to resolve the issue.

The reason it's not working, is because the preview and vue binding is happening in an iframe.

**Comment by davidm-public** [comment] 2018-01-22 03:38
any updates on this ?

**Comment by davidm-public** [comment] 2018-01-24 21:39
curiously, vue-devtools works fine with vue-play, which also uses an iframe:
https://github.com/vue-play/vue-play

**Comment by ndelangen** [comment] 2018-01-24 22:24
Wow, that IS curious! @kazupon any idea how that'd work?

@davidm-public are you able to view the components inside the iframe? because vue-play's manager UI is written in Vue, maybe that's what's being picked up? Debugging that isn't too valuable for developers I imagen.. But if they indeed are somehow able to pull off letting vue devtools connect to the vue instance inside the iFrame, we'd really like to know how to do that in storybook too.

**Comment by miljan-aleksic** [comment] 2018-01-25 00:55
@davidm-public, @ndelangen assumption is correct, vue-devtools is picking up the VuePlay app and totally ignoring the components from the stories, which are inside an iFrame.

**Comment by cmrd-senya** [comment] 2018-03-05 16:59
That might be useful to note that one is able to use devtools if they take the iframe link from the DOM and open it in a separate tab

**Comment by zephraph** [comment] 2018-03-07 23:48
That's a stopgap solution, but it's pretty cumbersome. 

https://github.com/storybooks/storybook/pull/1376 added the hook to be able to support switching the default iframe. https://github.com/vuejs/vue-devtools/pull/361 is opened and labeled as a discussion of how to handle iframe switching, but if that PR was merged as is it would at least have this functionality working. Please drop by that issue and pitch in to the discussion or give your support if it's something you're interested in.

**Comment by ynk** [comment] 2018-05-21 02:50
still no update on that issue ? is there a way to make it work temporarly ?

**Comment by zephraph** [comment] 2018-05-21 12:15
@ynk The issue from vue-devtools side hasn't been merged yet. I pinged one of the maintainers... hopefully it'll get merged. 🤞

**Comment by davidmoshal** [comment] 2018-05-21 19:28
Try https://github.com/asvae/vue-component-tree

It's excellent

**Comment by davidm-public** [comment] 2018-08-28 17:26
@igor-dv vue-component-tree has been renamed vue-book:
https://github.com/asvae/vue-book
it's pure Vue, no need to run Vue inside react.

**Comment by y-nk** [comment] 2018-09-04 05:52
@zephraph shouldn't it be like vue-devtools should add a manual "please select an iframe to inspect" kindof feature ?

**Comment by zephraph** [comment] 2018-09-05 15:46
That's a possibility. https://github.com/vuejs/vue-devtools/pull/361 really already does everything that's needed though. Sure, if they wanted, they could actually support it in the UI. Ultimately this would be enough... unfortunately, it doesn't look like there's any movement from that side.

**Comment by y-nk** [comment] 2018-09-06 09:54
@zephraph i'll try my luck and ask ; in the meantime, what are the possibilities to fix this issue on storybook side ?

**Comment by ndelangen** [comment] 2018-09-06 10:46
@y-nk In the next version I'll introduce an eject button to 'eject' the iframe from the manager.

This will give the dev tools direct access there.

Hope that helps.

**Comment by y-nk** [comment] 2018-09-06 17:58
@ndelangen I kinda made the devtools work with iframe, at least in the dev environment. I commented my progress here : https://github.com/vuejs/vue-devtools/pull/361

My goal is to try to build this devtools version to make it testable with storybook.
Let's see how it goes !

**Comment by ndelangen** [comment] 2018-09-06 18:06
@y-nk that is freaking awesome!

**Comment by igor-dv** [comment] 2018-10-08 11:56
@ndelangen, maybe it worth fixing it for the v4?

**Comment by y-nk** [comment] 2018-10-09 06:00
@ndelangen sadly the Vue team doesn't seem to respond, i wonder if they have seen the post.

**Comment by ndelangen** [comment] 2018-10-10 12:12
@kazupon Do you think you could help us out here? if @y-nk can help getting this feature working that'd be amazing for vue users!

**Comment by gapipro** [comment] 2018-10-19 13:40
Current solution is to use this: https://github.com/vuejs/vue-devtools/blob/master/shells/electron/README.md

And inject script tag into iframe using https://storybook.js.org/configurations/add-custom-head-tags/

**Comment by jackkoppa** [comment] 2018-11-07 14:06
Can confirm the above solution worked well as a stopgap for me, thanks a lot @gapipro. Though it seems we only have the option to install the devtools package globally (rather than as a project dependency), so as to still be able to inject the script into the iframe. And it's not immediately obvious how to strip out the Storybook `<script>` tag when deploying Storybook to a live environment.

Any efforts from the Storybook team on this would be very much appreciated.

**Comment by y-nk** [comment] 2018-11-08 07:53
@jackkoppa this doesn't solve the bug on the Vue.js part, rather fixing it for storybook only... the problem is the lack of choice of frame in the devtools, which would solve storybook _and_ all the other environments using iframes, without having to force people to use the electron app. I've added a quick and dirty fix months ago but no-one seems to care.

**Comment by ndelangen** [comment] 2018-11-08 09:58
@y-nk (over at storybook) We **do** care, I think at the devTools people care too, but are likely overloaded with work.

Did anyone reply to your POC?

What are the steps to take this POC to a real production worthy solution?
Perhaps the reason you're not getting any feedback is that a POC implies it still needs a lot of work from current maintainers to get right.

If we can minimize the amount of work **they** need to do to get this released, I think we have a better chance of it getting out there.

I'm super appreciative of your efforts.

**Comment by jake-harris** [comment] 2018-11-09 17:46
Thanks for the workaround, @gapipro.

Just a note for any copy-paste warriors like myself, don't forget to restart storybook once the config file has been created if using the standalone dev tools instance as described above.

**Comment by y-nk** [comment] 2018-11-10 13:09
@ndelangen i've been submitting to them a workable fork, that you can checkout and build properly to test the feature rather than a PR. I made a pretty long post on the most active discussion about iframe support in their repo about it, to make sure I'd get attention.

I decided to go this way because I believe that the current architecture of vue-devtools is honestly not ideal and i really don't want to contribute to add more spaghetti code than there already is.

I provided a POC on purpose, but I'm also trying to find time at home to restructure it totally without any breaking changes (quite a challenge), for which i will probably submit a PR around Christmas. I hope it will be appreciated, but I have a feeling it will probably get rejected as it looks a lot like the project has been almost rewritten from scratch...

The current state of this POC only lacks of styling for now, which i honestly didn't code bc/ i wanted to go as fast as possible with the most minimal impact.

The only process you need to do to appreciate the work would be to clone the fork and build the electron app. Then, to evaluate the code, only a diff of my commits from the latest "not my commit" state. There are approximately... 50 lines of dirty javascript as is so i don't think it's such an effort but I would understand they have better target with Vue3 than maintaining such a mess – for which, I would love to do (if any Vue people read this...)

Sorry it went off topic a bit, and thanks a lot for your support. It means to me :)

**Comment by lfkwtz** [comment] 2019-01-15 18:30
@jackkoppa global install isn't required, running fine here on a dev dependency

**Comment by fgm** [comment] 2019-12-04 16:30
In the meantime, zero-code/zero-conf hack: inspect the iframe in devtools, and right-click on "Open in new tab" on its "src" attribute, and you get the inspected component with the working devtools. Of course, you'll need to do it again every time you want to inspect another component.

**Comment by blocka** [comment] 2019-12-04 16:31
the latest versions of storybook have a "pop out" mode, which basically
does this for you

**Comment by fgm** [comment] 2019-12-04 18:18
That's what I thought, and was my first idea, but it doesn't actually enable the Vue devtools, for some reason I couldn't guess.

**Comment by blocka** [comment] 2019-12-04 18:19
it does...it opens up the iframe in a new window.

**Comment by fgm** [comment] 2019-12-04 18:35
It looks like it should but it does not. Here are two screenshots, one with the popout mode:

![Capture d'écran 2019-12-04 19 32 52](https://user-images.githubusercontent.com/143311/70170410-ecc9a980-16cc-11ea-99ab-94a0f1507949.png)

...which doesn't enable the tools, and the other one with the manual open which enables the Vue tools
![Capture d'écran 2019-12-04 19 34 23](https://user-images.githubusercontent.com/143311/70170526-1d114800-16cd-11ea-98d7-f78dbe63d322.png)

**Comment by niedzielski** [comment] 2020-05-18 15:34
> the latest versions of storybook have a "pop out" mode, which basically does this for you

I was scouring the internet for "pop out mode" and didn't find anything :laughing: I happened upon this mode today though! It's the button second from the right:

![image](https://user-images.githubusercontent.com/1071806/82231668-b2ef0700-98ea-11ea-807c-66c5e33e9e3a.png)

**Comment by ricardok1** [comment] 2020-06-22 15:58
Is this still open?

**Comment by jackkoppa** [comment] 2020-06-22 16:26
I'd be OK closing, after we can update the docs section here to explain the "Pop Out" mode, which does indeed solve the problems described here much more simply than enabling a local dev tools, for example

https://github.com/storybookjs/storybook/blob/next/docs/src/pages/guides/guide-vue/index.md

**Comment by blocka** [comment] 2020-06-22 16:33
it's still annoying to have to go into popout mode. Is it not possible to
do at all when it's in an iframe? Do react dev tools have the same issue in
storybook?

**Comment by shilman** [comment] 2020-06-23 12:32
@blocka i think react devtools works using this hook:

https://github.com/storybookjs/storybook/blob/master/lib/core/src/server/templates/base-preview-head.html#L71-L73

somebody also added a hook for Vue devtools, but I guess Vue doesn't support it

**Comment by blocka** [comment] 2020-06-23 12:37
So something has to be done in vue devtools for this to work?

**Comment by shilman** [comment] 2020-06-23 12:49
I'm not familiar with Vue devtools, but that's my guess. I believe the way we support React devtools is through an API that they provide and we write to, since there is no general way to solve this iframe issue without security implications.

**Comment by braddialpad** [comment] 2021-05-12 23:49
> I'd be OK closing, after we can update the docs section here to explain the "Pop Out" mode, which does indeed solve the problems described here much more simply than enabling a local dev tools, for example
> 
> https://github.com/storybookjs/storybook/blob/next/docs/src/pages/guides/guide-vue/index.md

Link seems to be broken now, what is this "Pop Out" mode mentioned?

**Comment by unr** [comment] 2021-05-31 14:16
@braddialpad I eventually found it through several other discussions on the same thing. They meant "pop out" the iframe, as in view the iframe source directly.
![image](https://user-images.githubusercontent.com/317957/120206515-4a26b400-c1f9-11eb-88a8-f2102f35906d.png)

This will let you use vue dev tools.

**Comment by yannbf** [comment] 2021-05-31 18:52
@braddialpad @unr
There is a button on top right that opens the story in its own url:

![image](https://user-images.githubusercontent.com/1671563/120231460-be8d4180-c251-11eb-8239-e8f1dc8f269e.png)


@domyen I feel like this feature should have a proper name to avoid confusion. WDYT? Currently it says "open canvas in a new tab", some people say "pop out", others say "eject"...

**Comment by ndelangen** [comment] 2021-06-03 14:09
Yann is correct, that button is for this purpose exactly. Storybook will make sure all args and globals will be set correctly.

**Comment by 3nuc** [comment] 2021-06-09 17:00
**Good news**

If you [download the latest beta of Vue devtools](https://github.com/vuejs/vue-devtools/releases/tag/v6.0.0-beta.14) and open the storybook main page you'll see this:
![image](https://user-images.githubusercontent.com/5359825/121397723-e583fb80-c954-11eb-8a2f-0b33d57b5a4d.png)

As you can see that's the main storybook page, not the bare iframe view.

This works for both Vue 2/3-based storybooks

**Comment by shilman** [comment] 2021-06-10 05:05
Awesome. Going to close this issue! Thanks for the heads up @3nuc !!!

**Closed by shilman** 2021-06-10 05:05 UTC
Labels: app: vue, compatibility with other tools, in progress

**Comment by magersoft** [comment] 2022-09-15 13:06
I have devtools version 6.2.1, vue 3 and @storybook/vue3: ^6.5.12
for me not working, Vue.js not detected. How to fix it?
