### ISSUE TITLE
Keeping the path for the static directory in building

### ISSUE THREAD

**Issue by hansthinhle** [storybookjs/storybook#714] opened 2017-03-07 09:36 UTC
In my root directory, I have a static folder names `public` which is served as `/public/...` path from my node server. That means the images and CSS files are served with that `/public/` prefix.

But when I use StoryBook with the command: `start-storybook -p 6006 -s ./public`
The path with `/public/` is no longer available.
So I changed the command to `start-storybook -p 6006 -s ./` to serve the root directory, and everything is ok.

But when I build my storybook with the command `build-storybook -s ./` the script will copy all files in the root directory to the `storybook-static`.
And if I change the command to `build-storybook -s ./public`, the path with `/public/` prefix will not be available anymore.

Is there a way to specify the path for the static directory?

**Comment by ndelangen** [comment] 2017-03-28 21:30
Hmm so this problem is about `build-storybook` that's something I'd need to look into how that works.

You could give custom middleware a try?, I'm not sure it will work, but it might.
https://github.com/storybooks/react-storybook/pull/435#issuecomment-264813688
https://github.com/storybooks/react-storybook/blob/master/src/server/middleware.js#L35

**Comment by patrickgordon** [comment] 2017-05-22 04:27
:+1: This is an issue - not for building storybook but just using for dev.

Here's how I got it to work with middleware:
```
const express = require('express');
const path = require('path');
const paths = require("../config/paths");

const expressMiddleWare = (router) => {
	console.log(path.join(__dirname), paths.appPublic);
	router.use('/public', express.static(paths.appPublic))
};

module.exports = expressMiddleWare;
```

**Comment by ndelangen** [comment] 2017-05-22 22:44
Thank you for sharing your solution! ❤️

**Comment by aviramga** [comment] 2018-02-09 08:09
Hi! @ndelangen @hansthinhle @patrickgordon 

Im facing the exact same issue. Was this ever solved?

Thanks!

**Comment by patrickgordon** [comment] 2018-02-13 00:57
hi @aviramga - my solution that I posted a few up resolved it for us. I never got around doing a PR to resolve it.

Might still do that actually now that my memory has been jogged :)

**Comment by aviramga** [comment] 2018-02-13 07:12
Hi @patrickgordon. Sadly my issue is only with build-storybook :/

I'm using it with a tool called Percy to find ui issues in my app. 

Did you manage to find a solution for the build?

**Comment by Hypnosphi** [comment] 2018-02-13 13:15
Looks like you can work around this using symlinks:

Add a directory with an arbitrary name (e.g. `static-link`, and put there a file called `public` (without any extension) with following contents:
```
../public
```

Then you should be able to achieve what you need with `-s static-link`

**Comment by aviramga** [comment] 2018-02-18 13:02
@Hypnosphi thanks for the tip! this doesnt seem to work though.
Can you please explain how it works?

All my static files are under a static directory (not public).
I tried to ways that didn't work:
1. Create an arbitrary directory with a file named "static" and ../static in it - cased build error when I ran build-storybook
2. Same as a above but with a  file named "public"  - still don't see any images

Any advice?

Thanks

**Comment by Hypnosphi** [comment] 2018-02-18 13:06
Which OS are you using?
https://en.wikipedia.org/wiki/Symbolic_link#Overview

**Comment by aviramga** [comment] 2018-02-18 13:07
Mac high sierra

**Comment by Hypnosphi** [comment] 2018-02-18 13:14
OK looks like my instruction for creating symlink was wrong. The correct way is this:

```
mkdir static-link
ln -s static static-link/static
```

It will create a "file" in static-link directory that can be shared in git

**Comment by aviramga** [comment] 2018-02-18 13:16
@Hypnosphi I will give it a shot. but does it mean I have to run it every time I ran build-storybook?

**Comment by Hypnosphi** [comment] 2018-02-18 13:49
No, it should be persistent

**Comment by aviramga** [comment] 2018-02-18 14:16
@Hypnosphi nope, still not working. While building I get a log that says:
cp: no such file or directory: static-link/static

I followed your instructions above. So I have an empty directory called static-link with a symlink from static to static-link/static

What am I doing wrong?

Really appreciate you taking the time to help out :)

**Comment by Hypnosphi** [comment] 2018-02-18 14:25
And you use `-s static/link` option, right?

**Comment by aviramga** [comment] 2018-02-18 14:28
@Hypnosphi you mean build-storybook -c .storybook **-s static-link** ?

**Comment by Hypnosphi** [comment] 2018-02-18 14:29
Yes

**Comment by aviramga** [comment] 2018-02-18 14:30
I do

**Comment by Hypnosphi** [comment] 2018-02-18 14:36
Sorry, I mistyped:
```
ln -s ../static static-link/static
```

**Comment by aviramga** [comment] 2018-02-18 15:18
@Hypnosphi 
why ../static?

Am I correct that the static-link directory is empty?
Maybe you want to try to move to a private conversation and publish here our final results? I feel like we are very close and its just miscommunication :)

**Comment by Hypnosphi** [comment] 2018-02-18 16:01
It's the relative path from link location to link target

**Comment by aviramga** [comment] 2018-02-18 16:07
@Hypnosphi I was able to make it work with using absolute path..... but I do need to make it work with relative path as I will want to implement the same logic in semaphore

**Comment by aviramga** [comment] 2018-02-18 16:36
@Hypnosphi found a workaround. Thank you so much for all your help, you're a life saver!!

**Comment by Kikobeats** [comment] 2018-03-09 09:36
any tip for resolving that?

**Comment by aviramga** [comment] 2018-03-09 09:40
Yes, just run the solution suggested above. Work with a symlink
ln -s /<absolute-path-your-static-directory> storybook-static-symlink/static

**Comment by BradMcGonigle** [comment] 2018-09-27 18:59
@aviramga is this method still working for you?  I'm not having any luck using a symlink.
 
My folder structure
```
|- docs
  |- folders-with-images
|- sandbox (holds my storybook files)
|- src
  |- README.md with image paths `/docs/folder/image.png`
```

I can get this working when serving storybook `start-storybook -c sandbox -s sandbox,docs -p 6006` using a middleware file:
```
const express = require('express');
const path = require('path');

module.exports = router => {
  router.use('/docs', express.static(path.join(__dirname, '..', 'docs')));
}
```
But adding a symlink using `ln -s /docs sandbox/docs` and running `build-storybook -c sandbox -s sandbox,docs -o storybook` still does not work.

The folders in `docs` are copied over but since the file path I need is `/docs/folder/image.png` the images 404.

**Comment by osphost** [comment] 2018-10-25 14:46
Also managed to use a static-link to solve this:

package.json:
```
"scripts": {
  "storybook": "(mkdir ./src/static-link || true) && (ln -s ../static ./src/static-link/static || true) && start-storybook -p 6006 -s ./src/static-link"
}
```

**Comment by eddybrando** [comment] 2019-02-12 12:52
I would advise against creating the symlink via the package.json script for compatibility reasons, in case not every developer uses the same OS.

As an alternative I suggest using the [copy-webpack-plugin](https://github.com/webpack-contrib/copy-webpack-plugin) in the **.storybook/webpack.config.js** file, like this:

```
const path = require('path');
const CopyWebpackPlugin = require('copy-webpack-plugin');

module.exports = config => {
  function resolve(dir) {
    return path.join(__dirname, '..', dir);
  }

  // Other configuration properties

  config.plugins.push(
    new CopyWebpackPlugin([
      {
        from: path.resolve(__dirname, 'static-foo'),
        to: '.'
      },
      {
        from: path.resolve(__dirname, '../static-bar'),
        to: './bar'
      }
    ])
  );

  return config;
}
```

This for example would mount the contents of the directory `.storybook/static-foo` to `http://localhost:6006/` and the contents of `static-bar` to `http://localhost:6006/bar/`.

Also note the use of `push` to add to the `plugins` array to avoid overwriting other plugins, which could break you Storybook Webpack configuration.

**Comment by graphographer** [comment] 2019-05-14 17:00
For future reference, symlinks are perfectly fine to use. If you want/need to use them with relative paths, then you simply use the -r switch like so: ln -rs <dir1> <dir2>

I personally think that if storybook sees fit to *copy* an entire static directory, this should be clearly stated in the documentation. Otherwise, this behavior should be switched out for one that creates the appropriate symlinks instead. I found out about the copying thing because it was crashing my server through excessively disk space usage!

**Comment by mtrabelsi** [comment] 2019-06-09 15:03
So basically there is no official built in solution and all the "solutions" are just random crappy hacks :)

**Comment by mtrabelsi** [comment] 2019-06-09 15:12
> I would advise against creating the symlink via the package.json script for compatibility reasons, in case not every developer uses the same OS.
> 
> As an alternative I suggest using the [copy-webpack-plugin](https://github.com/webpack-contrib/copy-webpack-plugin) in the **.storybook/webpack.config.js** file, like this:
> 
> ```
> const path = require('path');
> const CopyWebpackPlugin = require('copy-webpack-plugin');
> 
> module.exports = config => {
>   function resolve(dir) {
>     return path.join(__dirname, '..', dir);
>   }
> 
>   // Other configuration properties
> 
>   config.plugins.push(
>     new CopyWebpackPlugin([
>       {
>         from: path.resolve(__dirname, 'static-foo'),
>         to: '.'
>       },
>       {
>         from: path.resolve(__dirname, '../static-bar'),
>         to: './bar'
>       }
>     ])
>   );
> 
>   return config;
> }
> ```
> 
> This for example would mount the contents of the directory `.storybook/static-foo` to `http://localhost:6006/` and the contents of `static-bar` to `http://localhost:6006/bar/`.
> 
> Also note the use of `push` to add to the `plugins` array to avoid overwriting other plugins, which could break you Storybook Webpack configuration.

this doesn't work ;)

**Comment by BiosBoy** [comment] 2019-08-20 17:03
@mtrabelsi doesn't work for me for some reasons...

**Comment by mtrabelsi** [comment] 2019-08-20 17:50
@BiosBoy to avoid any confusion here quickly an idea about my project structure ( only what you need to know ):

> My_sweet_projet_ROOT_DIR/components/.storybook/webpack.config.js
> My_sweet_projet_ROOT_DIR/static

I also use next.js as the main application where it consumes react components from components folder.

Here my setup ( you could reproduce it on your side - I trust you :D )

> My_sweet_projet_ROOT_DIR/package.json 

```
{
  "name": "sweet_like_butter",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@zeit/next-css": "^1.0.1",
    "next": "^8.1.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "styled-components": "^4.2.0"
  },
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "devDependencies": {
    "babel-plugin-styled-components": "^1.10.0"
  }
}

```

My_sweet_projet_ROOT_DIR/next.config.js

```
const withCSS = require('@zeit/next-css')
module.exports = withCSS()
```

**Comment by MazinZ** [comment] 2019-08-29 06:20
I was able to get around a similar issue by using a base tag:

1. create a `manager-head.html` file in your .storybook directory. https://storybook.js.org/docs/configurations/add-custom-head-tags/
2. add `<base href="/storybook-static/">`.

files in index.html are now retrieved with the specified prefix

of course this potentially breaks the static version locally but that was ok in my case because I only use `build-storybook` to build a static version for remote deploys.

**Comment by adirn15** [comment] 2019-08-29 08:34
I'm experiencing a similar issue. 
the middleware.js solution works only if I run `start-storybook -c .storybook` .
but when I run my jest tests with initStoryShots (using addon-storyshots-puppeteer) the image snapshots are created without static assets 

any idea how this can be fixed?

**Comment by eckmLJE** [comment] 2019-10-08 12:44
Shouldn't this behavior be built into Storybook, where if you flag `-s ./static` then your paths will work the same way in Storybook as they would in production? Seems nonsensical that when I tell Storybook that my static directory is `./static`, that my relative paths e.g. `./static/image.png` have to instead be `./image.png` or use some goofy symlink 🤔

**Comment by MazinZ** [comment] 2019-10-09 01:42
@eckmLJE If you use the snippet that I posted above that should work without any additional webpack configuration or a symlink. We could look into outputting this automatically as part of the build process though.

**Comment by vcastro45** [comment] 2020-05-26 08:43
I still facing the problem in 2020...
My case is very simple: my `package.json` has this script: `"storybook": "start-storybook -s ./dist/img -p 8888"`

So when I run `npm run storybook`, it displays `info => Loading static files from: /home/vagrant/projects/MySuperProject/web/themes/ofb/ofb_ui/dist/img .`

but when I try to access to a file in the `dist/img` directory from the browser with this URL, it does not work: `http://localhost:8888/myImage.png`...

So guys, is it a bug or am I doing something wrong ?

**Comment by shilman** [comment] 2020-05-27 19:06
@ndelangen do you think we can fit this into 6.0 breaking changes? i think it would be a great fix, but a breaking one.

**Comment by saschahofmann** [comment] 2020-05-29 10:02
Seems like `CopyWepbackPlugin`'s api has changed and you need to add a `pattern` key to @mtrabelsi solution like that:
```javascript
const path = require('path');
const CopyWebpackPlugin = require('copy-webpack-plugin');

module.exports = async ({ config }) => {
  config.plugins.push(
    new CopyWebpackPlugin({
  patter: [
      {
        from: path.resolve(__dirname, '../../static'),
        to: './static'
      }
    ]})
  );

  return config;
}
```

**Comment by bgaynor78** [comment] 2020-06-08 19:03
I'll add my two cents related to this issue. Though I think it's closely related, my solution differs from @mtrabelsi in that I found that simply copying my assets into the ./static directory that is a result of the `build-storybook` command wasn't enough. Specifically if I am deploying the static app to a Tomcat server that serves the static app from `http://example.com/docs`, where docs is a directory located in the Tomcat webapps/ on the server. 

Because of the subpath, none of the files outside of the /css directory in the /static directory were getting loaded. I **am** using relative paths for images and fonts (these were the static assets that were failing to load on the deployed version). So requests like `https://example.com/img/path/to/my/image` failed, when it should have been adding /static, ie. `https://example.com/static/img/path/to/my/image` My solutions, as I said, is very close to @mtrabelsi but I just drop the two directorys if fonts and img into the root of the output:

``` javascript
const path = require('path');
const CopyWebpackPlugin = require('copy-webpack-plugin');

module.exports = async ({ config }) => {

  function resolve(dir) {
    return path.join(__dirname, '..', dir);
  }

  // Other configuration properties

  config.plugins.push(
    new CopyWebpackPlugin({
      pattern: [
        {
          from: path.resolve(__dirname, './_assets'), // My static font and images are located in the .storybook dir
          to: './' // Drop both the fonts/ and img/ directory into the root of the build output.
        }
      ]
    })
  );

  return config;
}
```

After this, the images and fonts were loaded appropriately.

**Comment by shilman** [comment] 2020-06-12 08:23
@tmeasday suggests: why can't we make this a `main.js` option so that it appears in both `start-storybook` and `build-storybook`

**Comment by ndelangen** [comment] 2020-06-16 13:11
@vcastro45 I've tested this for both start-storybook & build-storybook, and it seems to work (tested on the `next` branch).

Could you create a reproduction repo for me?

**Comment by ndelangen** [comment] 2020-06-16 13:21
@shilman It's possible, but we'd have to hoist the preset setup up from 
https://github.com/storybookjs/storybook/blob/9ea455a1746c489b7364448212663f2445af8a8b/lib/core/src/server/manager/manager-config.js#L101-L102

to before here:
https://github.com/storybookjs/storybook/blob/19c2420db80fcb3b89b34cdbbe03bf9010b0b3b2/lib/core/src/server/build-static.js#L190-L191

And then pass it down to all lower functions in the build / dev chain.
It's quite a refactor, not something I can do in 1 day.

It'd also be another moment we'd really want to migrate it all to TS. Since we'd be touching 50% of lib/core's files anyway.

**Comment by shilman** [comment] 2020-06-16 13:25
@ndelangen OOF, let's not do that now then 🙈

**Comment by ndelangen** [comment] 2020-06-22 09:40
Yeah we'll do it some day

**Comment by shilman** [comment] 2020-07-01 02:30
@ndelangen I've documented the workaround per discussion with @tmeasday. Propose that we move this config to `main.js` and add an option to support this use case in 6.x as a feature not a breaking change.

**Comment by nfroidure** [comment] 2020-07-21 08:03
Do you think a solution like `start-storybook -p 6006 -s "./public:/static"` to serve static files from `./public` on the `/static` path be implemented? It would lead to extremely flexible uses and fit the Docker's conventions of path mapping that lots of us are already familiar with.

**Comment by ndelangen** [comment] 2020-08-17 12:08
@nfroidure that is an interesting idea for sure!

**Comment by nfroidure** [comment] 2020-08-20 07:07
@ndelangen I can give a try to it with a PR if you wish. Any chance it gets merged?

**Comment by ndelangen** [comment] 2020-08-24 12:33
@nfroidure would be doable:
Here is where the code would go:
https://github.com/storybookjs/storybook/blob/9182d9f5ddbe136e9cd5fc9f11fa962a3cfe08f1/lib/core/src/server/build-dev.js#L77-L93

**Comment by nfroidure** [comment] 2020-08-25 08:09
Well I have something here : https://github.com/storybookjs/storybook/pull/12222

Some tests are failing but I cannot see any link between those failures and my changes.

LMKWYT ;)

**Comment by ndelangen** [comment] 2020-08-31 12:14
Thank you for this PR @nfroidure !

I'll look at it this week!

**Comment by shilman** [comment] 2020-09-10 00:50
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-alpha.6 containing PR #12222 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2020-09-10 00:50 UTC
Labels: feature request, has workaround, help wanted

**Comment by SpicyPete** [comment] 2020-11-23 22:44
Is there an example of how to use this new feature?

**Comment by iaremarkus** [comment] 2021-02-04 11:20
Fun fact I stumbled on today, that might be related to the above:

`npm run build-storybook -s ./src,./public`
does NOT copy those folders into `storybook-static`
 
`yarn build-storybook -s ./src,./public`
does

🤷

**Comment by RoamingAnt** [comment] 2021-02-10 00:46
For anyone wondering how to use the feature for mapping the static file directory. You can map the local path to a remote one using the CLI parameter like so `-s <local path>:<remote path>`

As an example, taking the original question it would work like so:
`start-storybook -p 6006 -s ./public:/public`

**Comment by sid-the** [comment] 2022-10-31 16:00
None of the images were loading within my pipeline but worked fine locally, ended up being because the components were fetching images using a relative path `<img src="/my-image" />` which apparently is not allowed using the[ file protocol](https://stackoverflow.com/questions/7857416/file-uri-scheme-and-relative-files).

I ended up doing 2 things:

1. Updating the static dirs directory to use the root  
javascript ```
// 
```

**Comment by Sid-Turner-Ellis** [comment] 2022-10-31 16:05
None of the images were loading within my pipeline but worked fine locally, ended up being because the components were fetching images using a relative path `<img src="/my-image" />` which apparently is not allowed using the[ file protocol](https://stackoverflow.com/questions/7857416/file-uri-scheme-and-relative-files).

I ended up doing 2 things:

1. Updating the static dirs directory to use the root  by updating the main.js file in storybook 
`
module.exports = {
 staticDirs: [{ from: '../static', to: '/' }],
}
`

2. Added a script to remove the leading slash of images in the preview-head.html file from storybook 
`
<script>
  document.addEventListener('DOMContentLoaded', () => {
      Array.from(document.querySelectorAll('img')).forEach((img) => {
        const original = img.getAttribute('src');
        img.setAttribute('src', original.replace('/', ''));
      });
  });
</script>
`
