### ISSUE TITLE
`npx sb init` and `npm run storybook` does not work with storybook 6.3.12 for Angular 13 workspace with a library and an application

### ISSUE THREAD

**Issue by mohaiminalaoun** [storybookjs/storybook#16661] opened 2021-11-10 16:44 UTC
**Describe the bug**
`npx storybook init` and `npm run storybook fails with the following log:

```
info @storybook/angular v6.3.12
info
info => Loading presets
WARN   Failed to load preset: "D:\\Non CB Projects\\library-storybook\\node_modules\\@storybook\\angular\\dist\\ts3.9\\server\\framework-preset-angular-ivy.js"
ERR! Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: D:\Non CB Projects\library-storybook\node_modules\@angular\compiler-cli\bundles\ngcc\index.js
ERR! require() of ES modules is not supported.
ERR! require() of D:\Non CB Projects\library-storybook\node_modules\@angular\compiler-cli\bundles\ngcc\index.js from D:\Non CB Projects\library-storybook\node_modules
\@storybook\angular\dist\ts3.9\server\framework-preset-angular-ivy.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "mod
ule" which defines all .js files in that package scope as ES modules.
ERR! Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from D:\Non CB Projects\library-storybook\node_modu
les\@angular\compiler-cli\package.json.
ERR!
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
ERR!     at Module.load (internal/modules/cjs/loader.js:928:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
ERR!     at Module.require (internal/modules/cjs/loader.js:952:19)
ERR!     at require (internal/modules/cjs/helpers.js:88:18)
ERR!     at Object.<anonymous> (D:\Non CB Projects\library-storybook\node_modules\@storybook\angular\dist\ts3.9\server\framework-preset-angular-ivy.js:70:14)
ERR!     at Module._compile (internal/modules/cjs/loader.js:1063:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:928:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
ERR!     at Module.require (internal/modules/cjs/loader.js:952:19)
ERR!     at require (internal/modules/cjs/helpers.js:88:18)
ERR!     at interopRequireDefault (D:\Non CB Projects\library-storybook\node_modules\@storybook\core-common\dist\cjs\presets.js:159:16)
ERR!     at getContent (D:\Non CB Projects\library-storybook\node_modules\@storybook\core-common\dist\cjs\presets.js:175:10)
ERR!     at loadPreset (D:\Non CB Projects\library-storybook\node_modules\@storybook\core-common\dist\cjs\presets.js:184:20)
ERR!     at D:\Non CB Projects\library-storybook\node_modules\@storybook\core-common\dist\cjs\presets.js:236:18
ERR!  Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: D:\Non CB Projects\library-storybook\node_modules\@angular\compiler-cli\bundles\ngcc\index.js
ERR! require() of ES modules is not supported.
ERR! require() of D:\Non CB Projects\library-storybook\node_modules\@angular\compiler-cli\bundles\ngcc\index.js from D:\Non CB Projects\library-storybook\node_modules
\@storybook\angular\dist\ts3.9\server\framework-preset-angular-ivy.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "mod
ule" which defines all .js files in that package scope as ES modules.
ERR! Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from D:\Non CB Projects\library-storybook\node_modu
les\@angular\compiler-cli\package.json.
ERR!
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
ERR!     at Module.load (internal/modules/cjs/loader.js:928:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
ERR!     at Module.require (internal/modules/cjs/loader.js:952:19)
ERR!     at require (internal/modules/cjs/helpers.js:88:18)
ERR!     at Object.<anonymous> (D:\Non CB Projects\library-storybook\node_modules\@storybook\angular\dist\ts3.9\server\framework-preset-angular-ivy.js:70:14)
ERR!     at Module._compile (internal/modules/cjs/loader.js:1063:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:928:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
ERR!     at Module.require (internal/modules/cjs/loader.js:952:19)
ERR!     at require (internal/modules/cjs/helpers.js:88:18)
ERR!     at interopRequireDefault (D:\Non CB Projects\library-storybook\node_modules\@storybook\core-common\dist\cjs\presets.js:159:16)
ERR!     at getContent (D:\Non CB Projects\library-storybook\node_modules\@storybook\core-common\dist\cjs\presets.js:175:10)
ERR!     at loadPreset (D:\Non CB Projects\library-storybook\node_modules\@storybook\core-common\dist\cjs\presets.js:184:20)
ERR!     at D:\Non CB Projects\library-storybook\node_modules\@storybook\core-common\dist\cjs\presets.js:236:18 {
ERR!   code: 'ERR_REQUIRE_ESM'
ERR! }
info => Loading 1 config file in "D:\Non CB Projects\library-storybook\.storybook"
info => Loading 9 other files in "D:\Non CB Projects\library-storybook\.storybook"
info => Adding stories defined in "D:\Non CB Projects\library-storybook\.storybook\main.js"
info => Using prebuilt manager
info => Found custom tsconfig.json
info => Using implicit CSS loaders
info => Loading angular-cli config
info => Using angular project "demo:build" for configuring Storybook
ERR! => Could not get angular cli webpack config
ERR! TypeError: Cannot read property 'target' of undefined
ERR!     at D:\Non CB Projects\library-storybook\node_modules\@storybook\angular\dist\ts3.9\server\angular-devkit-build-webpack.js:145:49
ERR!     at step (D:\Non CB Projects\library-storybook\node_modules\@storybook\angular\dist\ts3.9\server\angular-devkit-build-webpack.js:69:23)
ERR!     at Object.next (D:\Non CB Projects\library-storybook\node_modules\@storybook\angular\dist\ts3.9\server\angular-devkit-build-webpack.js:50:53)
ERR!     at fulfilled (D:\Non CB Projects\library-storybook\node_modules\@storybook\angular\dist\ts3.9\server\angular-devkit-build-webpack.js:41:58)
ERR!  TypeError: Cannot read property 'target' of undefined
ERR!     at D:\Non CB Projects\library-storybook\node_modules\@storybook\angular\dist\ts3.9\server\angular-devkit-build-webpack.js:145:49
ERR!     at step (D:\Non CB Projects\library-storybook\node_modules\@storybook\angular\dist\ts3.9\server\angular-devkit-build-webpack.js:69:23)
ERR!     at Object.next (D:\Non CB Projects\library-storybook\node_modules\@storybook\angular\dist\ts3.9\server\angular-devkit-build-webpack.js:50:53)
ERR!     at fulfilled (D:\Non CB Projects\library-storybook\node_modules\@storybook\angular\dist\ts3.9\server\angular-devkit-build-webpack.js:41:58)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! library-storybook@0.0.0 storybook: `npm run docs:json && start-storybook -p 6006`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the library-storybook@0.0.0 storybook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mohaimin.alaoun\AppData\Roaming\npm-cache\_logs\2021-11-10T15_38_08_949Z-debug.log


```

**To Reproduce**

In a folder, open terminal and run the following
`npx @angular/cli@latest new library-storybook --create-application=false`
`cd library-storybook`
`ng g library components-lib`
'ng g application demo`
`ng build components-lib --prod`
`npx sb init`
`npm run storybook`

**System**
Please paste the results of `npx sb@next info` here.

**Additional context**
The log above is the result. I don't know if this should happen for a new workspace.

**Comment by xXCalleManXx** [comment] 2021-11-10 17:14
I have the same issue.
I did following to reproduce error:
```
$ ng new test-angular-storybook
$ cd test-angular-storybook
$ npx sb init
$ npm run storybook
```

Angular CLI version: 13.0.1
Node version: 16.13.0
NPM version: 8.1.0

I tried running `npx sb@next init` and gave same error. The version installed in package.json was `6.4.0.beta-31`

**Comment by shilman** [comment] 2021-11-10 17:29
closing as dupe to #16355

**Closed by shilman** 2021-11-10 17:29 UTC
Labels: bug, app: angular, duplicate, needs triage
