### ISSUE TITLE
[Bug]: Support for Angular Library Projects

### ISSUE THREAD

**Issue by fireflysemantics** [storybookjs/storybook#21657] opened 2023-03-17 19:06 UTC
### Describe the bug

When generating an Angular workspace and a corresponding library and playground projects storybook fails to initialize because `.storybook/tsconfig.json` it configured with `extends` like this:
```
   "extends": "../false"
```

And it should be:
```
"extends": "../tsconfig.json".
```

There is a Stackoverflow detailing the description here:
https://stackoverflow.com/questions/75123232/running-storybook-on-an-angular-library-project/75711766#75711766

### To Reproduce

Please see:
https://stackoverflow.com/questions/75123232/running-storybook-on-an-angular-library-project/75711766#75711766

### System

```shell
System:
    OS: macOS 13.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 111.0
    Safari: 16.3
  npmPackages:
    @storybook/addon-actions: ^6.5.15 => 6.5.15 
    @storybook/addon-essentials: ^6.5.15 => 6.5.15 
    @storybook/addon-interactions: ^6.5.15 => 6.5.15 
    @storybook/addon-links: ^6.5.15 => 6.5.15 
    @storybook/angular: ^6.5.15 => 6.5.15 
    @storybook/builder-webpack5: ^6.5.15 => 6.5.15 
    @storybook/manager-webpack5: ^6.5.15 => 6.5.15 
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

**Comment by shilman** [comment] 2023-03-19 01:06
Possible duplicate https://github.com/storybookjs/storybook/issues/21672

cc @valentinpalkovic @sheriffMoose

**Comment by sheriffMoose** [comment] 2023-03-19 02:38
Closing this as duplicate of #21672

**Closed by sheriffMoose** 2023-03-19 02:38 UTC
Labels: bug, angular

**Comment by shilman** [comment] 2023-03-20 09:38
Yay!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-rc.5 containing PR #21675 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
