### ISSUE TITLE
[Bug]: Fail when starting project. Error: It looks like you are having a known issue with package hoisting.

### ISSUE THREAD

**Issue by VallisOctopus** [storybookjs/storybook#24318] opened 2023-09-27 15:43 UTC
### Describe the bug

Error running Storybook

To fix this I normally have to remove the node_module folder and reinstall and then it works locally. However my Git actions fails with the below message.

```
yarn run v1.22.19
$ storybook build --output-dir /tmp/chromatic--1998-1coCAwPCf1iT
🔴 Error: It looks like you are having a known issue with package hoisting.
Please check the following issue for details and solutions: https://github.com/storybookjs/storybook/issues/22431#issuecomment-1630086092
/home/runner/work/deep-sea-components/deep-sea-components/node_modules/cli-table3/src/utils.js:1
const stringWidth = require('string-width');
                    ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/deep-sea-components/deep-sea-components/node_modules/string-width/index.js from /home/runner/work/deep-sea-components/deep-sea-components/node_modules/cli-table3/src/utils.js not supported.
Instead change the require of index.js in /home/runner/work/deep-sea-components/deep-sea-components/node_modules/cli-table3/src/utils.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/runner/work/deep-sea-components/deep-sea-components/node_modules/cli-table3/src/utils.js:1:21)
    at Object.<anonymous> (/home/runner/work/deep-sea-components/deep-sea-components/node_modules/cli-table3/src/table.js:2:15)
    at Object.<anonymous> (/home/runner/work/deep-sea-components/deep-sea-components/node_modules/cli-table3/index.js:1:18)
    at Object.<anonymous> (/home/runner/work/deep-sea-components/deep-sea-components/node_modules/@storybook/core-server/dist/index.js:101:8716)
    at Object.<anonymous> (/home/runner/work/deep-sea-components/deep-sea-components/node_modules/@storybook/cli/dist/generate.js:11:4[49](https://github.com/octopus-investments/deep-sea-components/actions/runs/6328180004/job/17185737636?pr=220#step:4:50)4)
    at Object.<anonymous> (/home/runner/work/deep-sea-components/deep-sea-components/node_modules/@storybook/cli/bin/index.js:26:1)
    at Object.<anonymous> (/home/runner/work/deep-sea-components/deep-sea-components/node_modules/storybook/index.js:3:1) {
  code: 'ERR_REQUIRE_ESM'
}
Node.js v18.18.0
```

**Comment by pa-bouly** [comment] 2023-10-10 08:40
Hi, i think it is a duplicate of  [22431](https://github.com/storybookjs/storybook/issues/22431). Please take a look at the following comment/workaround: https://github.com/storybookjs/storybook/issues/22431#issuecomment-1630086092

**Closed** 2023-10-23 17:45 UTC
Labels: bug, needs triage
