### ISSUE TITLE
Storybook crashes - TypeError: Cannot read property 'isLeaf' of undefined

### ISSUE THREAD

**Issue by Rafsonic** [storybookjs/storybook#13687] opened 2021-01-21 09:21 UTC
The storybook crashes after we updated it to the **latest versions**. But if we removed all **MDX documents** then the storybook runs correctly as expected. If we have a least one MDX document then the StoryBook crashes again. 

![image](https://user-images.githubusercontent.com/15655808/105329299-ac333500-5bd9-11eb-9ebb-c5a9c62fc94a.png)

![image](https://user-images.githubusercontent.com/15655808/105329748-29f74080-5bda-11eb-8feb-1df2d9b2d455.png)

**Versions:**
    "react": "^17.0.1",
    "@storybook/addon-actions": "6.1.14",
    "@storybook/addon-docs": "6.1.14",
    "@storybook/addon-knobs": "6.1.14",
    "@storybook/addon-links": "6.1.14",
    "@storybook/addon-viewport": "6.1.14",
    "@storybook/react": "6.1.14",

**Environment Info:**

  System:
    OS: macOS 11.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.15.2 - ~/.nvm/versions/node/v14.15.2/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.9 - ~/.nvm/versions/node/v14.15.2/bin/npm
  Browsers:
    Chrome: 87.0.4280.141
    Safari: 14.0.2

![image](https://user-images.githubusercontent.com/15655808/105330060-835f6f80-5bda-11eb-8ebf-da8a8e3afe6d.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231368/1200161693571361) by [Unito](https://www.unito.io/learn-more)

**Comment by ethancrook99** [comment] 2021-01-21 19:53
I've run into this as well, but only if I have a `*.stories.mdx` file. If I just use a regular `*.mdx` file for documentation, it works as normal.

**Comment by flammangj** [comment] 2021-02-01 12:48
Happens to me as well when using  *.stories.mdx alongside *.stories.tsx and assign the same title on both.


**button.stories.tsx**
`export default {
  title: 'Button',
  component: ButtonComponent,
} as Meta;`


**button.stories.mdx**
This works:
`<Meta title="Button/Documentation"/>`

This will break:
`<Meta title="Button"/>`

**Comment by Weffe** [comment] 2021-03-02 00:15
I've experienced the same bug on the latest stable version, v6.1.20.

What's weird in my case is I have a folder with both an `*.stories.js` and `*.stories.mdx` and the same `title` that seems to be working just fine. But creating the same set up in another folder for a new component I built will fail with the error message like OP's error message.


I can confirm flammangj's comment about changing the title for either the mdx or js file will fix the issue for me.

**Comment by shilman** [comment] 2021-03-02 03:17
This sounds like a bug with the new sidebar implementation introduced in 6.1. Does anybody have a repro repo they can share?

**Comment by YozhEzhi** [comment] 2021-03-17 19:59
@shilman I'll make demo repo tomorrow.

**Comment by YozhEzhi** [comment] 2021-03-17 20:25
https://github.com/YozhEzhi/storybook-6-crash-demo

Steps to reproduce:
- yarn
- yarn start
- [all is fine]
- remove `/DELETE_ME_AND_I_WILL_CRASH_STORYBOOK` in `packages/button/stories/readme.stories.mdx`
- [app crashed]

**Comment by gregStevenard** [comment] 2021-04-06 16:16
Does anyone know if this has been fixed yet ? What is the way around it ?

**Comment by shilman** [comment] 2021-04-07 03:50
If you inspect your browser console, you should see this warning:

```
Duplicate title used in multiple files; use unique titles or a primary file for a component with re-exported stories.
```

So the workaround is to follow the instructions: this isn't intended to work in Storybook.

That said, Storybook shouldn't crash in this state, so we'll fix the bug in the next week or two.

**Comment by ghengeveld** [comment] 2021-04-07 11:51
☝️ This should fix it.

**Comment by shilman** [comment] 2021-04-09 02:31
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.6 containing PR #14502 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2021-04-09 02:31 UTC
Labels: P1, bug, has workaround, ui
