### ISSUE TITLE
[Bug]: Dev server does not update page on story create / edit / delete

### ISSUE THREAD

**Issue by alvarlagerlof** [storybookjs/storybook#22883] opened 2023-06-01 23:04 UTC
### Describe the bug

I've got a monorepo where one package has the storybook setup, and stories are spread out in different packages to be used by my storybook package. It's like: https://storybook.js.org/docs/react/configure/overview#with-a-configuration-object

The issue I'm having is that the stories in the sidebar and the UI do not update when changed. Only the code inside of them updates. So editing a story name / adding a story / deleting a story does not cause the localhost site to update. A forced reload doesn't help either..

### To Reproduce

https://github.com/alvarlagerlof/storybook-repro

### System

```shell
Environment Info:

  System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M2
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 3.6.0 - ~/.nvm/versions/node/v16.17.1/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
```

### Additional context

I'm using the Vite builder with React.

**Comment by oztune** [comment] 2023-06-28 18:53
I can confirm this is happening as well. Any thoughts?

**Comment by alvarlagerlof** [comment] 2024-03-25 14:54
No longer having this issue in Storybook 8, but we switched to the Vite builder.

**Comment by valentinpalkovic** [comment] 2024-04-04 16:23
Investigations:
The configuration object pattern defining the `stories` in the `.storybook/main.js` file causes this issue. As soon as the config pattern is used described [here](https://storybook.js.org/docs/api/main-config-stories#with-a-configuration-object), HMR is indeed broken. When defining stories with a glob of arrays, the HMR issue disappears.

**Comment by fernandojbf** [comment] 2024-04-08 15:37
Using react with Vite, i can reproduce the HMR issue. 

@valentinpalkovic using either the object or glob array the HMR is not working properly

**Comment by yannbf** [comment] 2024-05-06 08:51
Hey everyone, based on the reproduction, I believe I found the issue.
The glob is incorrect, which causes confusion in the Storybook indexer:

```
const config = {
  stories: [
    {
      directory: "../../test2/**", // 👈 This should be "../../test2" instead
      titlePrefix: "test2",
      files: "*.@(mdx|stories.@(mdx|tsx|ts|jsx|js))",
    },
  ],
```

The `directory` property should point to a single directory. Because it wasn't, HMR wasn't working correctly.
Changing it from `"../../test2/**` to `"../../test2/` fixes the issue.

@vanessayuenn there might be an opportunity here to do something internally and detect when users do this, and either throw an error or automatically remove `**` from the path. If you feel like we should do that, I can create an issue for it.

I'll be closing this one, but if anyone who stumbles upon this has similar issues in a different scenario, please let us know with a proper reproduction link so we can take a look into it (let us know @fernandojbf). Thanks!

**Closed by yannbf** 2024-05-06 08:51 UTC
Labels: bug, builder-vite, hmr

**Comment by mcmxcdev** [comment] 2024-05-06 21:51
Changing `'../stories/**'` to `'../stories'` gives me "Oh no! Your Storybook is empty."

In our case, we have nested folders, we need `'../stories/**'` so that a path like `stories/Button/Button.stories.svelte` can be resolved.

Note that we are using Storybook v7 stiill.

**Comment by yannbf** [comment] 2024-05-15 13:02
> Changing `'../stories/**'` to `'../stories'` gives me "Oh no! Your Storybook is empty."
> 
> In our case, we have nested folders, we need `'../stories/**'` so that a path like `stories/Button/Button.stories.svelte` can be resolved.
> 
> Note that we are using Storybook v7 stiill.

I see. Please upgrade to Storybook 8 (it should be straightforward with `npx storybook@latest upgrade`) and let us know again. If there is an issue, please provide a reproduction so we can use it to fix it. Thanks!
