### ISSUE TITLE
play function does not work after React 18

### ISSUE THREAD

**Issue by reinertisa** [storybookjs/storybook#18258] opened 2022-05-19 00:00 UTC
<img width="435" alt="Screen Shot 2022-05-18 at 6 54 57 PM" src="https://user-images.githubusercontent.com/71358643/169187178-06151fe0-65e3-4140-9e71-15e60b001c5b.png">
**Describe the bug**
I created stories for react-hook-form validation and used play function. It worked well React 17. After I updated React from 17 to 18, play function does not trigger validation. Do I miss something? @yannbf 

```
export const ValidationErrors = {
  render: (args) => (
    <>
      <h4>Superstruct validation</h4>
      <Form
        defaultValues={{
          radioField1: null,
        }}
        resolver={superstructResolver(RadioGroupStruct)}
        onSubmit={action('Superstruct submit')}
        mode="onSubmit"
      >
        <FormRadioGroup
          name="radioField1"
          label="Trigger validation"
          options={['One', 'Two', 'Three', 'Four']}
          {...args}
        />
        <FormSubmit>Save</FormSubmit>
      </Form>
      
      <h4 className="mt-4">RHF validation</h4>
      <Form
        defaultValues={{
          radioField1: null,
        }}
        onSubmit={action('RHF submit')}
        mode="onSubmit"
      >
        <FormRadioGroup
          name="radioField1"
          label="Trigger validation"
          options={['One', 'Two', 'Three', 'Four']}
          {...args}
          validation={{validate: atLeastOne}}
        />
        <FormSubmit>Save</FormSubmit>
      </Form>
    </>

  ),
  args: {
    readOnly: false,
    disabled: false,
    help: 'help text here',
  },
  play: async ({canvasElement}) => {
    const btnElems = within(canvasElement).getAllByRole('button', {name: /Save/i});

    // Superstruct validation: trigger radio group
    await userEvent.click(btnElems[0]);

    // RHF validation: trigger radio group
    await userEvent.click(btnElems[1]);
  },
};

```
**Expected output**
<img width="450" alt="Screen Shot 2022-05-18 at 6 57 47 PM" src="https://user-images.githubusercontent.com/71358643/169187573-765a790b-caf9-4379-a5dd-4de89e9d7edc.png">

**Comment by reinertisa** [comment] 2022-06-23 18:37
@shilman and @yannbf Sorry for the delay. I created repo and story is under src directory. App.stories.js -> https://github.com/reinertisa/my-example-reproduction

Thank you for your help.

**Comment by reinertisa** [comment] 2022-06-23 19:06
@shilman and @yannbf I converted React version from 18 to 17.0.2 and I run storybook and validation works with play function great but with version 18, it does not work. If you need another repo for 17.0.2, I can create it if you want.

**Comment by shilman** [comment] 2022-06-25 00:00
HI @reinertisa !! Thanks so much for creating a reproduction. However, I'm seeing the same behavior when I run your repro in both React 17 and 18:

<img width="890" alt="image" src="https://user-images.githubusercontent.com/488689/175749721-0290ad93-bf83-4153-b8bb-ee6e6edfc91f.png">

Can you please help clarify what I'm supposed to see differently? Also can you share the output of `npx storybook info` for me on your dev machine?

**Comment by reinertisa** [comment] 2022-06-25 00:52
Hi @shilman I see your screenshot for React 18 but When I use React 17. I see this screenshot. 
<img width="1255" alt="Screen Shot 2022-06-24 at 5 51 32 PM" src="https://user-images.githubusercontent.com/71358643/175751872-4be411b7-b064-44df-aaf0-dcb07c0005fe.png">

**Comment by reinertisa** [comment] 2022-06-25 01:08
@shilman this is output for my dev machine. Thank you for your help.
Environment Info:

  System:
    OS: macOS 12.4
    CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 3.2.1 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 103.0.5060.53
    Firefox: 94.0.2
    Safari: 15.5
  npmPackages:
    @storybook/addon-actions: ^6.5.9 => 6.5.9 
    @storybook/addon-docs: ^6.5.9 => 6.5.9 
    @storybook/addon-essentials: ^6.5.9 => 6.5.9 
    @storybook/addon-interactions: ^6.5.9 => 6.5.9 
    @storybook/addon-links: ^6.5.9 => 6.5.9 
    @storybook/builder-webpack4: ^6.5.9 => 6.5.9 
    @storybook/manager-webpack4: ^6.5.9 => 6.5.9 
    @storybook/react: ^6.5.9 => 6.5.9 
    @storybook/testing-library: ^0.0.13 => 0.0.13

**Comment by shilman** [comment] 2022-06-25 01:22
@reinertisa Clearly I need more coffee this morning! ☕ 

Ok, I'm able to reproduce the issue now (though intermittently -- sometimes I see the validation error in React18 also!)

Can you please update your story code like this and verify that the problem goes away? 

```js
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

export const Default = {
  render: (args) => <App {...args} />,
  play: async ({ canvasElement }) => {
    await sleep(0);
    await userEvent.click(within(canvasElement).getByRole('button', { name: /Submit/i }));
  },
};
```

It's not a proper fix, but if it works for you that will help us diagnose the problem and work towards a proper solution. Thanks!

**Comment by reinertisa** [comment] 2022-06-25 01:44
@shilman Thank you for information but I used sleep function after we updated React 18 to see validation errors and it worked but after that out chromatic build failed. We are not sure this sleep function caused that problem. I hope you can find proper solution for it. I am looking forward to it.

**Comment by reinertisa** [comment] 2022-06-25 06:18
@shilman maybe you need to see chromatic failure link for your reference. When I use sleep function, it works locally but fails in chromatic. I can provide link to failure for your reference. https://www.chromatic.com/test?appId=5eeab205fdb1e500227646e6&id=62b0bbe8c5862a6e55a3e9d8
If you need anything else from me, please let me know. Thank you so much.

**Comment by shilman** [comment] 2022-06-25 07:40
Thanks so much @reinertisa. No idea what the problem is yet, but this is a great starting point!

**Comment by IanVS** [comment] 2022-09-20 19:39
I can also confirm I'm experiencing this (or a very similar) issue after updating to react 18 (and storybook 7-alpha.33).  I have the validation error problem as shown above, but also the first character is sometimes lost from `await userEvent.type();`.  For instance:

```js
await userEvent.type(input, '1234');
```

Results in `234` in the field.  But if I add a 1ms sleep, then it's fine, and the whole thing is typed correctly.

**Comment by brycnguyen** [comment] 2022-10-13 17:36
> @reinertisa Clearly I need more coffee this morning! ☕
> 
> Ok, I'm able to reproduce the issue now (though intermittently -- sometimes I see the validation error in React18 also!)
> 
> Can you please update your story code like this and verify that the problem goes away?
> 
> ```js
> const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
> 
> export const Default = {
>   render: (args) => <App {...args} />,
>   play: async ({ canvasElement }) => {
>     await sleep(0);
>     await userEvent.click(within(canvasElement).getByRole('button', { name: /Submit/i }));
>   },
> };
> ```
> 
> It's not a proper fix, but if it works for you that will help us diagnose the problem and work towards a proper solution. Thanks!

This saved me today. Thanks! I'm also seeing this on my copy using react 18.

**Comment by sballesteros** [comment] 2022-10-13 18:45
I think that I have noticed smtg similar with the latest preact as well. I think Preact changed some of the internal (maybe related to 10.10). I will try to create a repro later when I have time (I am kind of lazily hoping that a preact update fixes it).

**Comment by gkadillak-lyra** [comment] 2022-11-29 17:23
@shilman is there a timeline for this fix? The workaround does help, but we've had to use `sleep(1000)` to get the tests to reliably run and this time is starting to stack up.

**Comment by IanVS** [comment] 2022-11-29 17:54
I see that @yannbf is assigned to this ticket, I think he might be the best to discuss the plans for it.  I do hope it can be fixed soon, since it's essentially blocking my upgrade to react 18 right now.

**Comment by yannbf** [comment] 2022-11-30 17:08
@tmeasday I thought #18737 and #19125 fixed that issue, but I see they got released before alpha.33 and the issue is still happening 🤔

**Comment by reinertisa** [comment] 2022-11-30 21:05
@yannbf I tried with "6.5.13" storybook version and still it does not work.

**Comment by tmeasday** [comment] 2022-12-01 01:23
Two things:

1. It doesn't seem like the changes from the two PRs (https://github.com/storybookjs/storybook/pull/18737, https://github.com/storybookjs/storybook/pull/19125) have been backported to 6.5 even though they have the `patch` label, is that right @shilman ?

2. I upgraded the repro to 7.x and the issue still occurs (https://github.com/tmeasday/my-example-reproduction). However, I'm not really understanding why. The play function runs after the `useLayoutEffect` call I added to your `App` component @reinertisa. 
![image](https://user-images.githubusercontent.com/132554/204943096-9093b940-396b-4255-85ea-25f8e8f412d7.png)

The form library seems to run the `onSubmit` function fine, set the error, but the component doesn't re-render with the new `errors`. I wonder if you could debug from here? I don't really know this library `react-hook-form`. LMK if you get stuck and I can dig further.

If others are seeing issues with 7.x a simpler repro that doesn't rely on an external library would help!

**Comment by shilman** [comment] 2022-12-01 02:01
@tmeasday The first PR has the `picked` label and the second one does not. That means that it didn't cherry-pick cleanly back to 6.5. I'll see if I can get it merged back today, possibly with your help.

**Comment by tmeasday** [comment] 2022-12-01 02:21
Ok, checked again and the behaviour is the same in 6.5.13 as in 7.x

**Comment by IanVS** [comment] 2022-12-01 02:23
I will work on a reproduction that doesn't use react-hook-form.  I've been seeing the behavior when simply filling out inputs using testing-library methods, so hopefully it will not be hard to reproduce.

**Comment by tmeasday** [comment] 2022-12-01 03:05
Perhaps the issue is that we are using [`useLayoutEffect`](https://github.com/storybookjs/storybook/blob/deee81fcd312386c1db57edfe5c7b8cdd8a8f2f2/code/renderers/react/src/render.tsx#L41) rather than `useEffect`. I used that [as suggested here](https://github.com/storybookjs/storybook/blob/deee81fcd312386c1db57edfe5c7b8cdd8a8f2f2/code/renderers/react/src/render.tsx#L41), but it might be worth trying changing to `useEffect` and seeing if it helps @IanVS.

**Comment by IanVS** [comment] 2022-12-01 03:26
Unfortunately that didn't help.  The reproduction isn't as easy as I hoped, normal inputs work fine.  I do have another component that uses a different library that's also failing, but it might be a somewhat simpler case than react-hook-form, so I'll try to put something together still.

**Comment by IanVS** [comment] 2022-12-01 04:09
@tmeasday it's not pretty, and I'm sorry the component is still a little complex, but here's a reproduction that does not use react-hook-form (though it does use downshift).  https://github.com/IanVS/storybook-react-18-issue-reproduction

The single story in that repo clicks on an input and a menu should appear.  That's indeed what happens if you install react 17 in the project.   But with react 18 installed, the menu does not open when the story loads.  Hopefully this helps a little.

**Comment by tmeasday** [comment] 2022-12-01 05:08
@IanVS hmm, that repro seems a bit odd. Even if I put in a 1s delay before doing anything in the `play` function, it still doesn't work here.

**Comment by IanVS** [comment] 2022-12-01 12:25
Rats, okay that sounds like it's a different problem then.  So the timing issue really does come down to something in react-hook-form.  I'll try opening an issue over there to see if they have any thoughts.  Thanks.

**Comment by tmeasday** [comment] 2022-12-01 23:08
I guess a reproduction that doesn't involve SB would be simply something that calls `handleSubmit` in a `useLayoutEffect` block.

**Comment by IanVS** [comment] 2022-12-29 03:38
@bluebill1049, do you have any ideas why this might be happening when we use react-hook-form with react 18 and submit the form in a `useLayoutEffect` or `useEffect`?  I'll try to put together a reproduction when I have some time, but maybe you have a thought about why this could be happening?

**Comment by IanVS** [comment] 2022-12-29 03:55
@bluebill1049 can you think of any reason why it might be a problem to submit a react-hook-form immediately upon rendering with react 18?  I'll try to put together a reproduction when I get a chance, but maybe you know offhand why this might happen?

**Comment by bluebill1049** [comment] 2022-12-29 04:03
Hey @IanVS, I have a feeling this is due to an async callback with `handleSubmit`. 

Could we try it without `handleSubmit` as below?

```tsx
<form onSubmit={(e) => e.preventDefault()}>
  <input {...register('input')} />
  <button>Send</button>
</form>
```

To verify if this issue can be omitted without the `handleSubmit`. if that's the case we can work from there and see if we can work together to resolve this issue.

**Comment by bluebill1049** [comment] 2022-12-29 04:30
another quick thought, could we try the following as well? In case it's related to `preventDefault`

```tsx
<form onSubmit={() => handleSubmit(callback)()}>
  <input {...register('input')} />
  <button>Send</button>
</form>
```

**Comment by IanVS** [comment] 2022-12-31 04:33
@bluebill1049 thanks for the ideas.  I tried them, but unsuccessfully.  If I don't call `handleSubmit()`, then react-hook-form doesn't set the validation errors, and if I don't prevent default, the page changes out from under me.  

I modified the reproduction above slightly, to show the same form two different ways, once using react-hook-form, and once with a standard react state triggered by submission.  It is at https://github.com/IanVS/react-hook-form-storybook-reproduction.  

Any other ideas to try would be much appreciated, or if you're able to take a look at the reproduction and have questions, please let me know.  It just seems like somehow the `handleSubmit()` can't be called in the same tick that the form is rendered.

**Comment by bluebill1049** [comment] 2022-12-31 04:58
@IanVS thanks for the repo, however, I am keep getting this error with node 17 and 18

```tsx
:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
```

I have also tried by execute `handleSubmit` at `useEffect` and `useLayoutEffect`, and none of them reproduce the issue above.

**Comment by IanVS** [comment] 2022-12-31 14:36
Doh!  I didn't notice the reproduction was using an old version of storybook.  I've updated it so that it will work in node 18 now.  Sorry for the trouble, and thanks again so much for taking a look.

**Comment by bluebill1049** [comment] 2023-01-10 23:52
@IanVS Did you have any update on this issue?

**Comment by IanVS** [comment] 2023-01-11 01:05
Thanks for the ping, @bluebill1049. I did update the reproduction to use the latest Storybook, which works correctly with node 18, since I think that was the problem you hit last time you took a look.  I'll be honest that I'm not sure what else to look into right now.  I'm hoping that you might have an idea what could be happening.  :- /

**Comment by bluebill1049** [comment] 2023-01-11 01:12
thanks, @IanVS I did a pull and re-run of your repo, and it still has the same issue as the last time I have run it (with node 18.5), could you be able to get it running in a code sandbox? I can take a look at it there.

**Comment by IanVS** [comment] 2023-01-11 01:25
Yes I'll try that, thanks.  Just to double-check for now, are you performing a fresh `yarn install`?  I'll let you know when I have a stackblitz working, though.

**Comment by bluebill1049** [comment] 2023-01-11 01:27
> Yes I'll try that, thanks. Just to double-check for now, are you performing a fresh `yarn install`? I'll let you know when I have a stackblitz working, though.

yes, i can confirm that. `rm -rf` the entire node_module and fresh `yarn`

**Comment by IanVS** [comment] 2023-01-11 01:27
Ah bugs upon bugs.  Such is the fun with beta software.  😬

**Comment by IanVS** [comment] 2023-01-11 01:57
OK, I put together a Stackblitz that shows the behavior.  Thanks for your patience.  https://stackblitz.com/edit/github-z8cetq?file=src/reacthookform.jsx.

**Comment by bluebill1049** [comment] 2023-01-11 02:11
It's actually working in the Stackbliz?

https://user-images.githubusercontent.com/10513364/211701685-9859621c-b34b-43b4-8aee-03e652185346.mov

**Comment by bluebill1049** [comment] 2023-01-11 02:33
I did change the code to just use `handleSubmit` without `e.preventDefault`

![Screenshot 2023-01-11 at 1 33 10 pm](https://user-images.githubusercontent.com/10513364/211704556-1dea159b-9a08-4098-be1a-bc00b6e43b5c.png)

**Comment by IanVS** [comment] 2023-01-11 02:46
I see, thanks.  If I make the callback to `handleSubmit` async, then I seem to have a race condition where sometimes after a refresh the test will pass, and sometimes it will fail...

**Comment by bluebill1049** [comment] 2023-01-11 03:12
Do we have something like `waitFor` in action play?

**Comment by IanVS** [comment] 2023-01-11 03:38
Yes we can use that.  Do you know what we could potentially trigger off of, though?

**Comment by bluebill1049** [comment] 2023-01-11 03:40
`handleSubmit` is async by default, because it allows the user to do async action inside and also means there will be running micro task running inside the function itself, which may result in the issue itself.

**Comment by sw-tracker** [comment] 2023-04-14 11:25
Any updates on this? We just upgraded to react 18 and we are encountering this issue. We have a sleep(1000) for now, but it would be nice to have a proper fix.

**Comment by IanVS** [comment] 2023-04-14 11:44
@sw-tracker if you have to sleep that long, it may be a different issue.  I've found that sleeping for 1 ms is usually enough for this particular issue.  I still haven't gotten to the root cause, and have resorting to sprinkling a few `sleep(1)` here and there.  :(

**Comment by sw-tracker** [comment] 2023-04-14 11:46
@IanVS sorry yes, `sleep(1)` makes it work locally on my MacBook. I had to increase it to sleep(1000) because the Jenkins where I work is slow and 1ms doesnt suffice sometimes.

**Comment by yannbf** [comment] 2023-04-21 21:50
Can someone provide a simple reproduction with the latest Storybook 7? Thank you so much <3

**Comment by IanVS** [comment] 2023-04-21 22:15
@yannbf I updated my reproduction above to 7.0.6: [stackblitz.com/edit/github-z8cetq?file=src/reacthookform.jsx](https://stackblitz.com/edit/github-z8cetq?file=src/reacthookform.jsx).

**Comment by tmeasday** [comment] 2023-05-04 00:35
@IanVS interestingly that reproduction itself is very intermittent--basically doesn't happen for me apart from the very first render.

Would it be useful to put together a non-SB reproduction @bluebill1049? Have you tried that @IanVS?

**Comment by tmeasday** [comment] 2023-06-06 05:36
@IanVS do you know what the status is on this one? I'm wondering if we should close this issue as ultimately it doesn't seem like an issue with SB itself.

**Comment by IanVS** [comment] 2023-06-06 12:27
I've resorted to sprinkling `sleep(1)` throughout stories as needed.  I agree that it doesn't seem to be an issue in Storybook.  Storybook is just executing so fast that it's surfacing issues in react-hook-form, most likely.  Though I'm curious why that wouldn't also happen in other testing tools (presumably).

**Comment by tmeasday** [comment] 2023-06-07 03:45
Ok, I had a play around with the reproduction on this issue outside of SB.

I reproduced the behaviour with `@testing-library/user-event@13.x` (which is what `@storybook/testing-library` uses). Upgrading to `14.0.0` resolves the issue. I'm not sure what's changed (unclear from changelogs), but sounds like we should upgrade our deps to improve the situation:

https://codesandbox.io/s/dry-fire-bmoc2t?file=/src/App.js

**Comment by jtstothard** [comment] 2023-06-07 08:05
> Ok, I had a play around with the reproduction on this issue outside of SB.
> 
> I reproduced the behaviour with `@testing-library/user-event@13.x` (which is what `@storybook/testing-library` uses). Upgrading to `14.0.0` resolves the issue. I'm not sure what's changed (unclear from changelogs), but sounds like we should upgrade our deps to improve the situation:
> 
> https://codesandbox.io/s/dry-fire-bmoc2t?file=/src/App.js
> 
> cc @yannbf

This would be great but I think testing library user event 14 was tested and reverted because of incompatibility, it would be great if this is now possible though!

https://github.com/storybookjs/testing-library/pull/19

**Comment by tobeycodes** [comment] 2023-07-18 13:41
I have started to experience this after upgrading React 17 to 18. In our case we have a `useEffect` that runs to update state to hide the sidebar. 

```
const [isOpen, setIsOpen] = useState(false);

useEffect(() => {
  if(hasSomeCondition) {
    setIsOpen(false);
  }
}, [hasSomeCondition[)

```

Our test has the following which the element has `onClick={() => setIsOpen(true)}`

```
await waitFor(() => userEvent.click(canvas.getByTestId('navtoggle')));
```

What is happening for us is that the user click even is happening before the useEffect has run when the component renders. Adding a sleep above solves the problem as the click will run after the useEffect has run.

**Comment by reinertisa** [comment] 2023-08-30 08:08
@shilman hi, today I updated storybook/testing-library (0.0.13 -> 0.2.0(latest)) and removed sleep function from play and all interactions triggered react-hook-form validations as expected locally. By the way we are still using storybook(6.5.16). Did you have  any chance test this issue with latest storybook/testing-library(0.2.0) ? Maybe this is the solution. But when we tried to catch snapshot using chromatic, all snapshots are failed and this is the screenhot coming from chromatic build.
<img width="855" alt="Screenshot 2023-08-30 at 1 07 40 AM" src="https://github.com/storybookjs/storybook/assets/71358643/71b7297d-1b8b-4a76-9464-4ace09e1bb6a">

**Comment by yannbf** [comment] 2023-08-30 08:32
> @shilman hi, today I updated storybook/testing-library (0.0.13 -> 0.2.0(latest)) and removed sleep function from play and all interactions triggered react-hook-form validations as expected locally. By the way we are still using storybook(6.5.16). Did you have any chance test this issue with latest storybook/testing-library(0.2.0) ? Maybe this is the solution. But when we tried to catch snapshot using chromatic, all snapshots are failed and this is the screenhot coming from chromatic build. <img alt="Screenshot 2023-08-30 at 1 07 40 AM" width="855" src="https://user-images.githubusercontent.com/71358643/264274137-71b7297d-1b8b-4a76-9464-4ace09e1bb6a.png">

Hey there! As mentioned a few times in this thread, it seems like the issue is with `@testing-library/user-event` version 13.

I would highly recommend you to upgrade to Storybook 7 if you can, not only because Storybook 6 is about 3 years old by now, but also because there were many fixes regarding the interactions addon and its relation to `@storybook/testing-library`. Also, another side effect which might impact your project is that `@storybook/testing-library` v0.2.0 uses `@storybook/instrumenter` version 7, which should be used with Storybook 7.
 
Here's a video comparing two repros, one that fails and the other one that does not:
[Storybook 7 + @storybook/testing-library 0.0.14](https://stackblitz.com/edit/github-z8cetq?file=package.json) - fails
[Storybook 7 + @storybook/testing-library 0.2.0](https://stackblitz.com/edit/github-z8cetq-t5w7gz?file=package.json) - works

https://github.com/storybookjs/storybook/assets/1671563/7cc0ab30-c97c-434b-b592-4ebf00d66ae5

I also noticed that your error does not seem to be the same as the ones mentioned in the reproduction:

<img width="876" alt="image" src="https://github.com/storybookjs/storybook/assets/1671563/e0763b67-1f08-4d40-8bb6-803aebf866f6">

This error happens when people use `@testing-library/react` instead `@storybook/testing-library` in their story files. Is that a possibility in your project?

**Comment by reinertisa** [comment] 2023-08-30 09:39
@yannbf thank you for feedback. We want to update storybook but we have some problem about it and my teammate created an issue on storybook. Our story file config is like that. I do not import @testing-library/react in our story files. 

`import {userEvent, within} from '@storybook/testing-library';`
```
play: async ({canvasElement}) => {
    await userEvent.click(within(canvasElement).getByRole('button', {name: /save/i}));
}
```

**Comment by reinertisa** [comment] 2023-09-19 18:16
@yannbf I talked to Chromatic team and they shared me reference issue #19758 about _play function does not work in stories built for Production_ and when I read this issue a couple of reasons trigger this problem and for us, we changed our build commands and it worked and I will summarize it here for people who will have this problem in the future. 

1. using NODE_ENV=development yarn build-storybook  -  We tried this and it worked.(Chromatic team shared it with us)
2. use the latest storybook and matches all libraries version - We did not get latest one yet. Maybe this can be other solution.
3. testing-library/react and @storybook/testing-library create conflict but we do not import both library in our stories. I ignore it. - This is your solution but we do not import them together so if someone do it, they can solve this conflict. 

As a result, today we got our first successful chromatic build and play function trigger RHF(react-hook-form) validations without sleep fn. 

Thank you for helping to fix this issue. @shilman @tmeasday @IanVS @bluebill1049 @yannbf

**Comment by reinertisa** [comment] 2023-09-19 18:49
This solution is kind of hack so I will keep this issue open until we get latest storybook. 
`NODE_ENV=development yarn build-storybook` - We tried this and it worked.(Chromatic team shared it with us)

**Comment by IanVS** [comment] 2023-09-19 19:32
Personally, I found that updating to the latest `@storybook/testing-library` (which uses user-event@14) solved it for us.

**Comment by yannbf** [comment] 2023-09-22 11:47
Thank you so much @reinertisa for trying all this out and providing information here!
Given that the original error seems to be solved, I will be closing this issue. If you'd like you can write a new one discussing the `act` issue, which seems unrelated to React 18. Thank you!

**Closed by yannbf** 2023-09-22 11:47 UTC
Labels: bug, react, addon: interactions

**Comment by ekim49** [comment] 2024-07-01 23:17
For those of you who are struggling for this issue:
- install `@storybook/testing-library`
- use decorator to wrap the component with `FormProvider` (or make a component that returns FormProvider wrapping children and customize to pass schema as props)

This worked for me. `play` works just fine!
