### ISSUE TITLE
[addon-controls] How to migrate dynamic knobs to controls?

### ISSUE THREAD

**Issue by flo-sch** [storybookjs/storybook#11984] opened 2020-08-13 15:04 UTC
### Question summary

After migration to Storybook v6, I am trying to replace dynamic knobs by the new controls addon.

However I had some dynamic knobs providing options from e.g. a global parameter:

I have a global decorator wrapping stories with a <ThemeProvider />
The theme comes from a global (selection from the toolbar)

```jsx
// .storybook/decorators/withThemeProvider
import React from 'react';
import { ThemeProvider } from 'theme-ui'

import { getThemeByName } from '../../helpers/theme';

const withThemeProvider = (Story, context) => {
  const theme = getThemeByName(context.globals.theme || localStorage.getItem('current-theme'));

  return (
    <ThemeProvider theme={theme}>
      <Story {...context} />
    </ThemeProvider>
  );
};

export default withThemeProvider;
```

```jsx
// one of my stories - @storybook/addon-knobs
import React from 'react';
import { select, text } from '@storybook/addon-knobs';

// useTheme provides the theme from the ThemeProvider context
import { useTheme } from '../../hooks/useTheme';
import MyComponent from './MyComponent';

export const Default = () => {
  const theme = useTheme();

  return (
    <MyComponent variant={select('Variant', Object.keys(theme.myComponent || {}), 'primary')}>
      {text('content', 'documentation')}
    </MyComponent>
  );
};
```

Since controls seem to be statically provided, is it possible to migrate those, and how?

```jsx
// one of my stories - @storybook/addon-essentials
import React from 'react';

import MyComponent from './MyComponent';

export const Default = (args) => <MyComponent {...args} />;

Default.args = {
  variant: 'primary',
  children: 'documentation'
};

Default.argTypes = {
  variant: {
    control: {
      type: 'select',
      options: ['primary'] // how to provide dynamic options, since those depend on the theme currently selected?
    }
  },
  children: {
    control: {
      type: 'text'
    }
  }
};
```

I was thinking, maybe if argTypes options could be defined as a function (as an opt-in advanced feature) receiving the context as arguments, it might do the trick?

```js
Default.argTypes = {
  variant: {
    control: {
      type: 'select',
      options: (context) => {
        const theme = getThemeByName(context.globals.theme || localStorage.getItem('current-theme'));
        return Object.keys(theme.myComponent || {});
      }
    }
  },
};
```

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 6.0.5

**Comment by shilman** [comment] 2020-08-13 15:14
Unfortunately controls does not support anything equivalent to dynamic knobs. What's your use case?

**Comment by flo-sch** [comment] 2020-08-13 15:23
Theme UI (built on top of Styled System) allows to define specific variants for components:
https://theme-ui.com/theme-spec#variants

I would like to illustrate that, based on the theme, you can select different variants.
(My Storybook comes with 2/3 example themes selectable from the toolbar)

Would you recommend to stick to knobs then for that?

**Comment by shilman** [comment] 2020-08-13 16:31
Thanks for sharing that.

I think the workaround would be to have different stories for different themes, but if you want it fully dynamic, knobs is your best bet for now.

**Comment by flo-sch** [comment] 2020-08-13 16:51
Is it possible to load different stories based on a global arg?
(Curious about that)

**Comment by shilman** [comment] 2020-08-13 16:54
Not really, I don't think. It's easy to make a story render differently based on a global arg. But actually loading different stories I don't think so. @tmeasday might have ideas

**Comment by tmeasday** [comment] 2020-08-14 03:33
Hmm, yeah sorry @flo-sch, this is not something we considered in creating `argTypes`. They are statically defined and cannot change.

There are quite a few use cases that revolve around "implied" changes when you change theme (for instance wanting to change another set of globals -- e.g. backgrounds). It's pretty tricky to imagine how we could do this in a way that wouldn't be really complex.

I wonder to what degree this behaviour is unique to theme or if its something people would want for a variety of globals.

**Comment by tmeasday** [comment] 2020-08-14 03:36
One thought bubble: rather than changing the sets, we could instead disallow certain combinations of globals or globals + args. You could imagine something like:

```js
Default.argTypes = {
  variant: {
    disallow: (value, { globals: { theme } }) => theme === 'light' : !lightVariants.include(value) ? !darkVariants.include(value))
  }
}
```

**Comment by flo-sch** [comment] 2020-08-15 06:36
> Hmm, yeah sorry @flo-sch

Don't be, this is a question about an edge-case of this great OSS project :)

Thanks for the tips, that could be enough, and I will also try to re-think how to document those variants, maybe juste some MDX about it will cover it in the end.

Regarding dynamic use of globals, that is the only use-case I can think about right now, but others may have different ones?

Not sure if you want to keep this thread open for discussions, otherwise we can close it :)

Keep up the good work with SB and Chromatic, it's awesome!

**Comment by tmeasday** [comment] 2020-08-16 06:36
Maybe let's leave it open until the bot closes it and see what comes up.

As with any feature we probably just need to let it permeate through the ecosystem a bit and see what comes back before thinking about what's next ;)

**Comment by frimmy** [comment] 2020-08-27 22:04
In a somewhat similar vein with @flo-sch , I've got a set up where one knob (`numberOfSecretAgents`) determines the number of of items rendered by another knob (`secretAgentKnob`) that spits out editable objects.
```tsx
const secretAgentKnob = (
  num: number,
  label: string = 'Secret Agent',
  groupName: string = 'SecretAgents',
): AgentContact[] => {
  const secretAgentsArr: SecretAgentContact[] = [];
  for (let i = 0; i < num; i += 1) {
    const secretAgentNum = i + 1;
    secretAgentsArr.push({
        name: text(`${label} ${secretAgentNum} name`, `${label} ${secretAgentNum}`, groupName),
        company: text(`${label} ${secretAgentNum} company`, 'CIA', groupName),
        role: text(`${label} ${secretAgentNum} role`, 'Agent', groupName),
      });
  }
  return secretAgentsArr;
};
export const InquirySecretAgentDropdown = () => {
  const numberOfSecretAgents = number(
    'Number of Secret Agents',
    5,
    {
      range: true,
      min: 2,
      max: 10,
      step: 1,
    },
    'Number of Secret Agents',
  );
  return <SecretAgentDropdown secretAgents={secretAgentKnob(numberOfSecretAgents)} />;
};
```

Is there a way to do this with argTypes? I didn't see any documentation about it 😬 
```

[@storybook/react 6.0.5]

**Comment by shilman** [comment] 2020-08-27 22:52
Nope, not possible currently @frimmy

**Comment by SajPrad** [comment] 2020-09-11 20:41
What is considered a dynamic knob?
So there isn't a way to implement a previous knob in the new controls without completely reworking the knob?

**Comment by flo-sch** [comment] 2020-09-12 07:40
@SajPrad by dynamic I meant something that depends on the runtime: here, on the context of the given story.

Knobs are defined by a function, you can either define them statically before your story, or dynamically within your story (and as @frimmy mentioned, have dynamic options based on other knobs state for instance)

Controls however are static, defined at the moment the story is invoked, so for me at the moment controls are not always a replacement, it depends on your use-case

**Comment by SajPrad** [comment] 2020-09-14 00:37
@flo-sch I see, thanks for the clarification. Right now I want to see how much of previous knobs could be implemented using controls. From what it seems like, it depends on what the knob does and the data it has.

**Comment by agrohs** [comment] 2020-10-12 13:21
I am looking for the exact same functionality, have been searching all over for it since exploring the move to v6 to no avail.

**Comment by flo-sch** [comment] 2020-10-12 22:27
@agrohs it is still possible to use `@storybook/knobs` if you need something dynamic at the moment?
https://www.npmjs.com/package/@storybook/addon-knobs

(Not sure if they can be mixed together with controls though)

**Comment by agrohs** [comment] 2020-10-12 22:31
Yes, I know we can still use knobs but this seems like such a big design flaw for controls. Playing with some things now to use a custom `Page` and in there to look at context and then dynamically insert/adjust `argTypes` based on a value in there based on a value of `args` passed in - but its not ideal. It would be really nice to simply have `argsType` be equal to an object or a function that returns an object and have the function get called w the same `context` value as the story does.

**Comment by agrohs** [comment] 2020-10-12 22:32
This article (and 3rd party add-on) got my mind thinking to try the Page route: https://medium.com/@atanasstoyanov/custom-documentation-pages-for-storybookjs-13eb9637d6ab

**Comment by Quirksmode** [comment] 2020-11-25 20:36
I love that Controls syncs with your Types, but I am struggling to get toggle one of my props. It's a simple button component and one of it's props is 'icon' which is used to pass in an icon as a React Component (JSX). When I used Knobs I simply use this to toggle the icon on and off:

```icon={boolean('Show Icon', true) ? <IconTimeCalendar /> : ''}```

But when I try to do this in Controls I seem to only be able to pass in the component like this:

```icon: <IconTimeCalendar />```

Which when I run and view it in Storebook results in a text input showing some random code:

'{"key":null,"ref":null,"props":{},"_owner":null,"_store":{}}'

Is there a way to toggle this prop on and off?

**Comment by flo-sch** [comment] 2020-11-26 00:12
> ```icon={boolean('Show Icon', true) ? <IconTimeCalendar /> : ''}```

I may be missing something obvious, but it looks like a static control use-case to me?

```jsx
export const CalendarButtonStory = ({ showIcon, ...args }) => (
  <Button
    {...args}
    icon={showIcon ? <IconTimeCalendar /> : undefined}
  />
);

CalendarButtonStory.argTypes = {
  showIcon: {
    control: 'boolean'
  }
};

CalendarButtonStory.args = {
  showIcon: true
};
```

Or is the problem that controls also show a strange input for your `icon` prop automatically?

In that case you could either:

- override the argType for `icon`, for instance use a 'select' control to choose a known icon name and render its corresponding component
- disable controls for such a prop: https://storybook.js.org/docs/react/essentials/controls#disable-controls-for-specific-properties

**Comment by Quirksmode** [comment] 2020-11-26 10:42
@flo-sch Ah awesome, this did what I needed. The only issue now is that the docs page is showing this additional showIcon prop, but this isn't an actual prop used by the component.

Is there a way to show the control for showIcon, but hide from the docs table (and vice versa for the icon which I want to show on the docs page, but not in the controls)?

**Comment by flo-sch** [comment] 2020-11-26 12:24
Not that I know of, but perhaps @tmeasday could confirm that?

What I could think of, is instead of using a "storybook-specific argument" in such a case, is to use the `icon` prop instead, but allowing a blank option to have the icon optional?

(Disclaimer: non tested code)

```jsx
export const CalendarButtonStory = ({ icon, args }) => (
  <Button
    {...args}
    icon={{
      'TimeCalendar': <IconTimeCalendar />,
      'SomeOtherIconName': <OtherIconComponent />,
      // unknown names would result in icon being undefined, which should be fine for the Button?
    }[icon]}
  />
);

CalendarButtonStory.argTypes = {
  icon: {
    control: 'select',
    options: [
      'TimeCalendar',
      'SomeOtherIconName',
      //...
    ]
  }
};

CalendarButtonStory.args = {
  icon: 'TimeCalendar'
};
```

The caveat is what would be shown in the "source" part with such a conditional rendering, but there are probably ways to make that look better using React displayName or such?

**Comment by tmeasday** [comment] 2020-11-27 00:56
I think @shilman is the expert here.

If it isn't currently possible it definitely falls into the area of things we are looking at. We think  "synthetic" args like `showIcon` are the best way forward for allowing a level of dynamic args without complicating things too much. We should figure out a way to hide them where they don't make sense (e.g. docs table) for sure.

PS

```js
// If you have this
CalendarButtonStory.args = {
  showIcon: true
};

// We'll infer this automatically
CalendarButtonStory.argTypes = {
  showIcon: {
    control: 'boolean'
  }
};
```

**Comment by shilman** [comment] 2020-11-27 01:04
You can hide args from the table: 

```js
CalendarButtonStory.argTypes = {
  showIcon: {
    table: { disable: true }
  }
};
```

Arg values need to be JSON serializable (ish, we're using telejson), so the current way to do what you're trying to do is to use enum args and then map them to actual icon components in user-level code. 
Full examples: https://storybook.js.org/docs/react/essentials/controls#fully-custom-args

As for the dynamic part, it's still on deck. We just got a perf release out in 6.1 and I plan to circle back on args/controls improvements in 6.2. Not entirely sure sure whether this will make the cut this time around.

**Comment by Quirksmode** [comment] 2020-11-27 17:34
Hey guys, firstly thanks so much for getting back to me so fast, I know how busy you must be. I definitely think being able to add custom controls without affecting the components props will be a great feature to have going forward. 

I really love the direction Storybook is going in, and have been enjoying playing around with MDX. Sorry to spring another issue on you, but I think this one may actually be a bug. 

I was able to get this working using your dropdown idea (massive thanks for that!) and I have now converted everything to MDX as this seemed to be Storybooks recommended approach. 

The issue is that when you use Template.bind({}) it causes the 'Show Code' source for the component to output as <MDXCreateElement ... > instead of the actual component source.

One other issue is that the controls never show within the ArgsTable, assuming this may also be a bug?

Here's my code:

`<Meta
  title="Components/UI Elements/Button"
  component={UIButton}
/>

# UIButton
A simple UI Button with its variations.

export const Template = ({ icon, ...rest }) => {
  return <UIButton {...rest} icon={{
    'TimeCalendar': IconTimeCalendar
  }[icon]} />;
};

<Preview>
  <Story
    name="Primary"
    args={{
      children: 'Active',
      onClick: action('Button clicked'),
      buttonType: 'primary',
      buttonSize: 'large',
      isDisabled: false,
      isLoading: false,
      loadingText: 'Loading text',
      title: 'Button title',
      reverseOrder: false
    }}
    argTypes={{
      icon: {
        control: {
          type: 'select',
          options: [
            'No Icon',
            'TimeCalendar'
          ]
        }
      },
    }}
  >
    {Template.bind({})}
  </Story>
</Preview>

# Props
<ArgsTable of={UIButton} />`

**Comment by shilman** [comment] 2020-11-27 23:25
@Quirksmode please don't hijack the issue with unrelated issues. https://github.com/storybookjs/storybook/issues/13187 https://github.com/storybookjs/storybook/issues/11542

**Comment by Quirksmode** [comment] 2020-11-28 20:36
Apologies for that, thanks for all the help.

**Comment by yoavniran** [comment] 2020-12-06 09:12
Found this issue after trying to upgrade React-Uploady's storybook from knobs to controls.
All my stories share settings that depend on selection from one knob to determine show/hide of additional knobs.
Without this capability Im unable to upgrade 😞

**Comment by shilman** [comment] 2020-12-23 03:14
If you want this fixed, please upvote by adding a 👍 to the issue description. We use this to help prioritize! @yoavniran @Quirksmode

**Comment by mosherc** [comment] 2021-02-16 19:45
Will this feature be added before knobs deprecation for Storybook 7.0? The docs mention this is supposed to replace Knobs, but this seems like an important and wanted feature to remove via deprecation. I have used dynamic knobs for switching between a color picker and a list of selectable colors before, and I'm sure there are many other use cases as others have mentioned. It would also be nice if this missing feature were mentioned in the readme so people know to stay on Knobs for now. https://github.com/storybookjs/storybook/tree/next/addons/controls#how-will-this-replace-addon-knobs

**Comment by spacecakes** [comment] 2021-06-02 12:38
I've been trying to figure out why my `<TweeningNumber>` component doesn't actually tween when passed a new prop value, and the lifecycle hooks finally gave me the answer: the component is re-mounted whenever the controls change, making the range slider I set up to demo it in Storybook useless.

I'm using Vue, but my problem seems to do with the above mentioned issue?

**Comment by ridarf** [comment] 2021-07-28 20:42
Recreating this feature for Controls would be really valuable.

**Comment by flo-sch** [comment] 2021-08-05 14:13
Just wondering if this issue is already prioritized somehow in Storybook v6 / v7?
(Looks like [knobs are getting deprecated](https://github.com/storybookjs/storybook/discussions/15060) without a solution for that at the moment)

**Comment by shilman** [comment] 2021-08-05 14:16
This is not currently prioritized. I implemented a version of it [here](https://github.com/storybookjs/storybook/pull/13890) but we decided not to merge it until we understand the use cases for dynamic knobs better.

**Comment by flo-sch** [comment] 2021-08-05 14:30
Alright, is there any way we (community members) could help with that?

Like providing examples of use-cases, repos etc?

**Comment by shilman** [comment] 2021-08-05 14:40
Yes please! 🙏  Mostly use cases -- repos are useful for reference, but mostly just want to understand the desired UX and rationale behind it.

For context, we have also discussed alternative solutions, such as control groups that can be shown and hidden with a toggle (as opposed to based on the values of other controls). So as we look at the use cases we'll also be trying to evaluate whether a simpler construct would solve for the use case.

**Comment by elliotbonnevilleharrys** [comment] 2021-08-05 20:34
Actually just ran into this limitation today. I'm building out typography documentation for our design system, and I wanted to provide a typography playground.

In this playground, a user should first select the type scale (`header`, `body`, etc.), and then select a member of that type scale, where the available members of the type scale are dependent on which type scale was initially selected.

In my case, I have a `theme` object with typography data stored in it. The typography is stored in the theme as an object containing objects containing typeface information, e.g.:

```
{
  header: {
    l: {
      fontSize: 24,
      lineHeight: '130%',
    },
    xl: {
      fontSize: 36,
      lineHeight: '130%',
    },
  },
  body: {
    s: {
      fontSize: 16,
    },
    m: {
      fontSize: 18,
    },
  },
};
```

My initial approach was to provide an `argTypes` shaped like this:

```
{
    scale: {
      name: 'Font Scale',
      description: 'Scale to render this font from',
      options: Object.keys(theme.typography),
      table: {
        defaultValue: {
          summary: 'header',
        }
      },
      control: {
        type: 'select'
      }
    }
  }
```

But since `argTypes` isn't dynamic, I have no way of providing an `index` control where the options consist of `Object.keys(theme.typography[userSelectedScale])`.

In an ideal world, I would provide a dropdown for the typography `scale` control with a default value of, e.g. `'header'`, and then in the `index` control I would also have a default value, say `l`. Then, if a different type scale was selected, the `index` dropdown would automatically update to show the keys of the new type scale object.

Hopefully this helps, @shilman. Let me know if you need more context.

**Comment by Hassan-smaoui** [comment] 2021-08-08 14:18
I have been looking for a way to make the controls conditional:
Situation : Having 2 controls for a component, A and B, I want to set B disabled if A is false.
This makes it clear to the user that he can not use the control B if A is false, for example.
(Control A doesn't need to be boolean, it can be something else, but it is just an example.)

**Comment by jayarjo** [comment] 2021-08-13 11:16
Typical use case for dynamic controls would be dependent selects, so basically a select options of which depend on the value of another select value.

**Comment by erosenberg** [comment] 2021-09-03 15:03
+1 for dynamic args/controls. It would be immensely helpful if this were prioritized in controls. I really don't want to have to use a deprecated add-on.

**Comment by flo-sch** [comment] 2021-09-30 12:18
> @flo-sch - were you able to find a workaround in the meantime?

I still use knobs

**Comment by shpakkdv** [comment] 2021-11-05 07:27
+1
Extremely useful dynamic controls based on other controls values.
Especially, when it was previously (with knobs)

**Comment by kmurgic** [comment] 2022-01-31 14:47
+1 I have used dynamic knobs a lot - for example I had a button component that could use `component="link"` and if the component knob was set to link then I would show a knob for `href` that would otherwise be hidden.

I came across an example recently where I wanted dynamic controls. I have a color prop that can be "primary" "secondary" "gray" or any custom color. Ideally I would make this a select control with the options `primary` `secondary` `gray` and `custom`, and if `custom` is selected then show a control for the color picker. I know I can set preset colors, but `primary` and `secondary` change the hover colors for this component as well and passing a presetColor will not have the same effect in this case. My fallback right now is just to hardcode a couple options with other colors.

**Comment by stephen-risk-first** [comment] 2022-02-15 14:11
+1 at my company we have the exact same use case as @flo-sch. Enabling selection of variants from the currently active theme.

**Comment by mbazanowski-merixstudio** [comment] 2022-03-22 12:01
Just as an additional use-case for dynamic controls. IDK if it was already mentioned earlier.

In my projects I used to use dynamic knobs for arrays of items. 

Eg. For table storybook with 3 columns (name, age, favorite color) - I had a Select for number of rows (eg. 1-10) - and based on that selection there was 3-30 inputs - 3 for every row. 

It was very handy for A LOT of situations - e.g. graphs storybooks, form components, tables and others. 

Would be great to have same thing for Controls addon :+1:

**Comment by shilman** [comment] 2022-03-23 07:50
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.50 containing PR #17536 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2022-03-23 07:50 UTC
Labels: feature request, addon: controls, PN, linear

**Comment by shilman** [comment] 2022-03-23 07:51
I've released the first pass at dynamic controls for dynamic knobs users. Feedback welcome here!

**Comment by julrich** [comment] 2022-03-23 09:56
Nice! Will give that a spin on a feature-branch!

> > Other cases:
> > 
> > * hidden
> > * readonly
> 
> What about including/excluding when another arg is a certain value, e.g. only render `color` when `appearance = 'primary'` (where `appearance` has `options` defined)?
> 
> API idea:
> 
> ```js
> argTypes: {
>   appearance: {
>     options: ['primary', 'outline'],
>   },
>   color: { includeIf: ['appearance', 'primary'] } // enable when appearance = 'primary'
> }
> ```
https://github.com/storybookjs/storybook/pull/17536#issuecomment-1049073176

This thought was dropped for the first iteration, right? Just making sure... I guess the current comparison is a simple check for truthiness? Where a property having any value at all evaluates to `true`, while explicit boolean `false` and undefined / non-existing values evaluate to `false`? :thinking: At least the second example here seems to indicate that:
https://storybook.js.org/docs/6.5/react/essentials/controls#conditional-controls

Unfortunately that's really limiting, still. I think one of the main use-cases (at least that's the case for us) with this was reacting to the values of an `enum` (or more generally, connecting a comparison operator of some kind to the check against the value of the referenced field). A simple string comparison (on top of the existence-check) would go a long way here, I think! Any chance of including something like that? Or will that run into the same limitations that exist for having a dynamic function context, in regards to static analysis? (re: https://github.com/storybookjs/storybook/pull/17536#issuecomment-1065788411)

**Comment by AlanSl** [comment] 2022-03-23 10:01
Looks like a nice feature, checking I've understood correctly, it looks like it has these two limitations:

 1. It can only check the values of other controls (not globals)
 2. It can only check if the value is truthy (not match one (or more) values)

Is that correct? If it is, I'm sorry but it seems too narrow for I think all the use cases discussed in this thread, which all discuss either matching particular options or value types, or matching globals (like theme).

Is it not possible to do something like:

```js
// There's no control called theme, so it checks for a global called 'theme' and adds if its value === 'dark'
{ ..., addIf: ['theme', 'dark'] }
```

**Comment by kmurgic** [comment] 2022-03-23 14:01
Awesome to see some progress with this and a way to add some conditional controls! However, I agree with the comments above that this doesn't address a lot of use cases. I think we either need to open a new issue or leave this issue open.

One example of where this falls short would be a color prop that could be `'primary'`, `'secondary'`, or `'custom'` and you only wanted to show a color picker if the color was set to custom.
Maybe we can do something like this
`addIf: { if: 'color', is: 'custom' }`

And also a nice feature would be to be able for a control to be dependent on multiple controls. This is a bit of a contrived example, but if we only show a border if `showBorder` is true and `borderColor` is `'custom'`. Maybe in that case it could look something like this:
`addIf: ['showBorder', { if: 'borderColor', is: 'custom' }]`

**Comment by AlanSl** [comment] 2022-03-23 15:15
That's a good idea @kmurgic, using objects instead of tuples would be more extensible in future without breaking changes, and would make it really clean to detect if an array of conditions was passed in then recurse over them.

**Comment by shilman** [comment] 2022-04-05 06:43
@julrich @AlanSl @kmurgic I've redone this feature from scratch based on your comments. Feedback welcome!

https://github.com/storybookjs/storybook/pull/17883

**Comment by dartess** [comment] 2022-04-05 07:46
@[shilman](https://github.com/shilman) Looks good! The only thing that caught my eye was the lack of operators for numbers. Wouldn't it be a good idea to add "greater than" and "less than" operators?

**Comment by julrich** [comment] 2022-04-05 13:01
@shilman That looks great! :muscle:  We wouldn't (currently?) need something like gt, gte, lt, lte, but I see where @dartess is coming from. Not sure if / when that opens Pandoras Box, though, in regards to included complexity.

**Comment by shilman** [comment] 2022-04-05 16:29
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.56 containing PR #17883 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

**Comment by misuken-now** [comment] 2022-04-08 19:37
@shilman 
Sounds convenient. These aliases may be more useful.

```
{ arg: 'foo', "===": 'bar' }
{ arg: 'foo', "!==": 'bar' }
{ arg: 'foo', "==": 'bar' }
{ arg: 'foo', "!=": 'bar' }
{ arg: 'foo', "<": 10 }
{ arg: 'foo', ">": 10 }
{ arg: 'foo', "<=": 10 }
{ arg: 'foo', ">=": 10 }
```

**Comment by AlanSl** [comment] 2022-04-19 08:33
Looks great, thanks!

If you wanted to expand on the condition logic later, without inventing a potentially ever-expanding homespun syntax for serialising every comparison someone might use, you could use an existing schema-defining tool for setting validation criteria in a serialisable object, like jsonschema or AJV.

For example you could add one new key, `schema`, which takes an object that is simply passed to the schema library's validation function along with the value, and contains criteria according to that library's syntax. Looks like with AJV in particular you could get out of the box not only greater / lesser checks on numbers but also on dates, array lengths, complex object shapes...

In theory you could get an established, documented and tried-and-tested system for all sorts of tests with minimal new code and minimal new conventions to invent and document.

**Comment by leads** [comment] 2022-09-22 22:27
Hello. 

I'm hoping to pass a value into a story argTypes - is this the right chat for that?

It might look something like 
```
export default {
    title: 'Example/Footer',
    component: Footer,
    argTypes: {
      backgroundColor: {
        control: 'select', options: global.context.myListOfColors
      }
    }
  } as ComponentMeta<typeof Footer>;
```

And it would be created in preview.js?

**Comment by ryuran** [comment] 2022-11-02 14:19
Hello!

I have a complex storybook using conditional knobs to migrate to controls.

Some knobs are visible only in specific case. With complex condition.

like
```js
let extraKnob;
if (firstKnob && secondKnob) {
  extraKnob = boolean( 'optional knob only available when 2 others are specified', false);
}
```

It's currently not possible with controls: https://github.com/storybookjs/storybook/discussions/18542

**Comment by agrohs** [comment] 2023-03-21 12:39
Just want to make sure I'm not missing something (@shilman, @tmeasday), but I haven't found mention of a similar use case to below and wondering what the best suggestion might be in the new world of controls. Previous "dependent knob" code below:
```
  <Story name="ProvidersListItem">
    {() => {
      const isSelected = boolean('Selected', true, 'ProvidersListItem');
      const providersType = select('Provider Types', providerTypesSelectOptions, Object.values(providerTypesSelectOptions)[0], 'ProvidersListItem');
      const providers = ProvidersTypes[providersType];
      const providerNames = getProviderNames(providers);
      const providerName = select('Provider Name', providerNames, Object.values(providerNames)[0], 'ProvidersListItem');
      return (
        <ProvidersListItem
          providerName={providerName}
          provider={providers[providerName]}
          selected={isSelected}
        />
      )
    }}
  </Story>
```

**Comment by sumitshinde-84** [comment] 2023-04-11 20:21
Hey help I need to migrate knobs to control 

import React, { useEffect } from 'react';
import { text } from '@storybook/addon-knobs';
import { store, getNewState } from '../../../.storybook/preview';
import { suggestedAssets as mockSuggestedAssets } from '../../../.storybook/initial-states/approval-screens/add-suggested-token';
import { updateMetamaskState } from '../../store/actions';
import ConfirmAddSuggestedToken from '.';

export default {
  title: 'Pages/ConfirmAddSuggestedToken',

  argTypes: {
    tokens: {
      control: 'array',
      table: { category: 'Data' },
    },
    suggestedAssets: {
      control: 'array',
      table: { category: 'Data' },
    },
  },
};

const { metamask: state } = store.getState();

const PageSet = ({ children, suggestedAssets, tokens }) => {
  const symbol = text('symbol', 'META');
  const image = text('Icon URL', 'metamark.svg');

  useEffect(() => {
    if (!suggestedAssets?.length) {
      return;
    }

    suggestedAssets[0].asset.image = image;
    suggestedAssets[0].asset.symbol = symbol;

    store.dispatch(
      updateMetamaskState(
        getNewState(state, {
          suggestedAssets,
        }),
      ),
    );
  }, [image, suggestedAssets, symbol]);

  useEffect(() => {
    store.dispatch(
      updateMetamaskState(
        getNewState(state, {
          tokens,
        }),
      ),
    );
  }, [tokens]);

  return children;
};

export const DefaultStory = ({ suggestedAssets, tokens }) => {
  return (
    <PageSet suggestedAssets={suggestedAssets} tokens={tokens}>
      <ConfirmAddSuggestedToken />
    </PageSet>
  );
};
DefaultStory.storyName = 'Default';
DefaultStory.args = {
  suggestedAssets: [...mockSuggestedAssets],
  tokens: [],
};

export const WithDuplicateAddress = ({ suggestedAssets, tokens }) => {
  return (
    <PageSet suggestedAssets={suggestedAssets} tokens={tokens}>
      <ConfirmAddSuggestedToken />
    </PageSet>
  );
};
WithDuplicateAddress.args = {
  suggestedAssets: [...mockSuggestedAssets],
  tokens: [
    {
      ...mockSuggestedAssets[0].asset,
    },
  ],
};

export const WithDuplicateSymbolAndDifferentAddress = ({
  suggestedAssets,
  tokens,
}) => {
  return (
    <PageSet suggestedAssets={suggestedAssets} tokens={tokens}>
      <ConfirmAddSuggestedToken />
    </PageSet>
  );
};
WithDuplicateSymbolAndDifferentAddress.args = {
  suggestedAssets: [...mockSuggestedAssets],
  tokens: [
    {
      ...mockSuggestedAssets[0].asset,
      address: '0xNonSuggestedAddress',
    },
  ],
};
