### ISSUE TITLE
TypeError: (tag.text || "").trim is not a function

### ISSUE THREAD

**Issue by pixelass** [storybookjs/storybook#15067] opened 2021-05-27 13:58 UTC
**Describe the bug**
We cannot start storybook due to an error within `react-docgen-typescript`

**To Reproduce**
unclear

We completely removed docgen (rely on addon-essentials) and still got this issue

**System**
Please paste the results of `npx sb@next info` here.

```
  System:
    OS: macOS 11.2.3
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.2.0 - ~/.nvm/versions/node/v16.2.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.13.0 - ~/.nvm/versions/node/v16.2.0/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 88.0
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-actions: ^6.3.0-beta.2 => 6.3.0-beta.2 
    @storybook/addon-backgrounds: ^6.3.0-beta.2 => 6.3.0-beta.2 
    @storybook/addon-docs: ^6.3.0-beta.2 => 6.3.0-beta.2 
    @storybook/addon-essentials: ^6.3.0-beta.2 => 6.3.0-beta.2 
    @storybook/addon-links: ^6.3.0-beta.2 => 6.3.0-beta.2 
    @storybook/addon-viewport: ^6.3.0-beta.2 => 6.3.0-beta.2 
    @storybook/addons: ^6.3.0-beta.2 => 6.3.0-beta.2 
    @storybook/builder-webpack5: ^6.3.0-beta.2 => 6.3.0-beta.2 
    @storybook/cli: ^6.3.0-beta.2 => 6.3.0-beta.2 
    @storybook/manager-webpack5: ^6.3.0-beta.2 => 6.3.0-beta.2 
    @storybook/preset-typescript: ^3.0.0 => 3.0.0 
    @storybook/react: ^6.3.0-beta.2 => 6.3.0-beta.2 
    @storybook/theming: ^6.3.0-beta.2 => 6.3.0-beta.2 
```

Only using essentials:

```
  npmPackages:
    @storybook/addon-essentials: ^6.3.0-beta.2 => 6.3.0-beta.2 
    @storybook/addon-viewport: ^6.3.0-beta.2 => 6.3.0-beta.2 
    @storybook/addons: ^6.3.0-beta.2 => 6.3.0-beta.2 
    @storybook/builder-webpack5: ^6.3.0-beta.2 => 6.3.0-beta.2 
    @storybook/cli: ^6.3.0-beta.2 => 6.3.0-beta.2 
    @storybook/manager-webpack5: ^6.3.0-beta.2 => 6.3.0-beta.2 
    @storybook/preset-typescript: ^3.0.0 => 3.0.0 
    @storybook/react: ^6.3.0-beta.2 => 6.3.0-beta.2 
    @storybook/theming: ^6.3.0-beta.2 => 6.3.0-beta.2 

```

**Potential Workarounds**

> resetting typescript to `4.2.2`

https://github.com/styleguidist/react-docgen-typescript/issues/356#issuecomment-849406193

**Additional context**

```
<i> [webpack-dev-middleware] wait until bundle finished
70% sealing plugins DocGenPlugin<XXXXXX>/node_modules/react-docgen-typescript/lib/parser.js:475
            var trimmedText = (tag.text || '').trim();
                                               ^

TypeError: (tag.text || "").trim is not a function

```

related: https://github.com/styleguidist/react-docgen-typescript/issues/356

**Comment by pixelass** [comment] 2021-05-27 14:31
I tried "resetting typescript to 4.2.2" as suggested in the linked comment but experienced the same error

I also tired `"typescript": "^4.0.6"` without success

**Comment by danielcpereira11** [comment] 2021-05-27 15:22
I've also started experiencing this issue in builds today without bumping Storybook's version. 
I've tried bumping the version to the latest alpha or beta but the problem persists.

Here's my environment Info:

  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.14.0 - ~/projects/quantic-gatsby/node_modules/.bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 86.0.1
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-a11y: ^6.2.8 => 6.3.0-alpha.43 
    @storybook/addon-actions: ^6.2.7 => 6.3.0-alpha.43 
    @storybook/addon-essentials: ^6.2.7 => 6.3.0-alpha.43 
    @storybook/addon-links: ^6.2.7 => 6.3.0-alpha.43 
    @storybook/addon-viewport: ^6.2.7 => 6.3.0-alpha.43 
    @storybook/react: ^6.2.7 => 6.3.0-alpha.43

**Comment by pixelass** [comment] 2021-05-27 15:40
My bad. after pinning  `"typescript": "4.2.2"` I can confirm that this workaround works https://github.com/styleguidist/react-docgen-typescript/issues/356#issuecomment-849406193

**Comment by danielcpereira11** [comment] 2021-05-27 16:18
> My bad. after pinning `"typescript": "4.2.2"` I can confirm that this workaround works [styleguidist/react-docgen-typescript#356 (comment)](https://github.com/styleguidist/react-docgen-typescript/issues/356#issuecomment-849406193)

I can confirm that pinning typescript to 4.2.2 works as well. I was doing ^4.2.2 which didn't work.

**Comment by nightgrey** [comment] 2021-05-28 14:27
Can confirm. Upgrading from `typescript@4.2.4` to latest (`4.3.2`) is what broke it for me. Downgrading to `4.2.4` works!

**Comment by TomzBench** [comment] 2021-05-28 14:37
Is this issue referenced on typescript repo? Seems like typescript should allow the code in question to compile.

**Comment by StatikDeveloper** [comment] 2021-05-29 11:11
Thank you, guys! This solution is helped for me. @nightgrey @danielcpereira11

**Comment by LucasNeevs** [comment] 2021-05-29 12:27
I have here the same trouble here. To me, this works:

```typescript: {
    reactDocgen: 'none',
  }```
  
  For me, this is better than downgrade TS. And works well.

**Comment by LucasNeevs** [comment] 2021-05-29 12:28
I have here the same trouble here. To me, this works:
```
typescript: {
    reactDocgen: 'none',
}
```

 For me, this is better than downgrade TS. And works well.

**Comment by johnhunter** [comment] 2021-06-01 09:02
> I have the same trouble here. To me, this works:
> 
> ```
> typescript: {
>     reactDocgen: 'none',
> }
> ```
That's in `.storybook/main.js` in module.exports
https://github.com/styleguidist/react-docgen-typescript/issues/356#issuecomment-850400428

**Comment by joseguerrerov** [comment] 2021-06-05 02:42
Pinning to `"typescript": "4.2.2"` works.

**Comment by edalex-ian** [comment] 2021-06-08 01:27
I've just started work on a new project and am working on the first story. As a result, I was able to readily see a delta point of where things fail.

First, my story looked like this and all worked:

```typescript
import { KalturaUploader, KalturaUploaderProps } from "../src/KalturaUploader";
import { Meta, Story } from "@storybook/react";
import * as React from "react";

export default {
  title: "KalturaUploader",
  component: KalturaUploader,
} as Meta<KalturaUploaderProps>;

export const Init: Story<KalturaUploaderProps> = (args) => (
  <KalturaUploader {...args} />
);
```

But then once I attempted to specify some args, it broke with the `trim` `TypeError`:

```typescript
import { KalturaUploader, KalturaUploaderProps } from "../src/KalturaUploader";
import { Meta, Story } from "@storybook/react";
import * as React from "react";
import { kalturaSaasEndpoint } from "../src";

export default {
  title: "KalturaUploader",
  component: KalturaUploader,
} as Meta<KalturaUploaderProps>;

export const Init: Story<KalturaUploaderProps> = (args) => (
  <KalturaUploader {...args} />
);
Init.args = {
  endpoint: kalturaSaasEndpoint,
};
```

Being this is a new project, I obviously started with the latest Typescript version. And as a result I really don't want to start with an old version of TS, so I guess the only option is to turn off `reactDocgen` for now. :disappointed: 

Anyway, hope that helps whoever is working to fix this.

**Comment by yann-combarnous** [comment] 2021-06-09 22:11
PR was merged for react-docgen-typescript, but they bumped major version to 2.0.0 and storybook is using ^1.0.0.

**Comment by shilman** [comment] 2021-06-10 03:32
We'll try to get this sorted for 6.3

**Comment by Himself65** [comment] 2021-06-10 08:55
Upstream package has fixed this bug. When could this package use the correct version?

https://github.com/styleguidist/react-docgen-typescript/releases/tag/v2.0.0

**Comment by bebraw** [comment] 2021-06-10 08:57
@Himself65 There's a tiny regression in v2.0.0 that likely has to be fixed before the related webpack plugin can be updated as its test suite is failing with the fix. Here's more info: https://github.com/hipstersmoothie/react-docgen-typescript-plugin/issues/42#issuecomment-858433886 .

**Comment by bebraw** [comment] 2021-06-10 09:22
For reference, here's the issue related to the regression that's blocking react-docgen-typescript-plugin upgrade to v2: https://github.com/styleguidist/react-docgen-typescript/issues/366 .

**Comment by shilman** [comment] 2021-06-15 09:37
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-rc.7 containing PR #15247 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by jeffgaynorspok** [comment] 2021-06-15 14:56
@shilman `@next` is still set to `6.3.0-rc.5`. `6.3.0-rc.7` is not in the registry.

**Comment by shilman** [comment] 2021-06-15 18:49
@jeffgaynorspok that's a problem with the registry propagation and AFAIK not a problem with storybook

**Comment by pixelass** [comment] 2021-08-08 04:21
@shilman This issue still exists: `"typescript": "4.2.4",`

```
System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 16.3.0 - ~/.nvm/versions/node/v16.3.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.15.1 - ~/.nvm/versions/node/v16.3.0/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Firefox: 87.0
    Safari: 14.1.1
  npmPackages:
    @storybook/addon-a11y: ^6.3.6 => 6.3.6 
    @storybook/addon-actions: ^6.3.6 => 6.3.6 
    @storybook/addon-docs: ^6.3.6 => 6.3.6 
    @storybook/addon-essentials: ^6.3.6 => 6.3.6 
    @storybook/addon-links: ^6.3.6 => 6.3.6 
    @storybook/react: ^6.3.6 => 6.3.6 
```

```
06:11:07.634 | ERR! => Failed to build the preview
06:11:07.769 | ERR! ./atomic-design/atoms/avatar/src/avatar.tsx
06:11:07.769 | ERR! Module build failed (from ./node_modules/react-docgen-typescript-loader/dist/index.js):
06:11:07.769 | ERR! TypeError: (tag.text \|\| "").trim is not a function
```

**Comment by shilman** [comment] 2021-08-08 05:54
@pixelass Did you try removing `node_modules` and/or lockfiles and reinstalling?

**Comment by pixelass** [comment] 2021-08-08 06:06
Yes. 
This issue actually never resolved for me. I was pinning typescript 4.2.2. I am now on 4.2.4 which also works.

I noticed this during a fresh build on vercel when I upgraded to the latest typescript version (3.4.3).

**Comment by shilman** [comment] 2021-08-08 07:44
@pixelass Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). 🙏

**Comment by alexandreabeh** [comment] 2021-08-10 21:29
Fwiw, I was also getting this same error on Storybook 6.3.7 with typescript version 4.3.5, but found that when I removed the `react-docgen-typescript-loader` custom loader configuration from my `main.js`, the error went away. It also looks like `react-docgen-typescript-loader` has been archived in Github and might no longer be actively maintained.

**Comment by pixelass** [comment] 2021-08-11 06:43
@alexandreabeh thx for the info. 
The owner was looking for maintainers but nobody replied: https://github.com/strothj/react-docgen-typescript-loader/issues/96

I also removed it and can confirm that it works without that plugin. I also added the recommended ts configuration (via: https://storybook.js.org/docs/react/configure/typescript#default-configuration)

```js
// .storybook/main.js

module.exports = {
  typescript: {
    check: false,
    checkOptions: {},
    reactDocgen: 'react-docgen-typescript',
    reactDocgenTypescriptOptions: {
      shouldExtractLiteralValuesFromEnum: true,
      propFilter: (prop) => (prop.parent ? !/node_modules/.test(prop.parent.fileName) : true),
    },
  },
};
```

<details>
  <summary>Click to show additional info!</summary>

### I am not sure if this is related

I noticed that https://github.com/storybookjs/storybook/issues/14805 popped back up after the changes mentioned above (`node_modules` have been deleted and reinstalled after all changes)

```
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
        ["@babel/plugin-proposal-private-property-in-object", { "loose": true }]
to the "plugins" section of your Babel config.

```
  
Also the initial Page does not seem to work anymore.

<img width="1329" alt="Screen Shot 2021-08-11 at 08 16 22" src="https://user-images.githubusercontent.com/1148334/128978936-b10eef97-b491-4703-a7be-11239b0018f3.png">


```
No Preview
Sorry, but you either have no stories or none are selected somehow.

* Please check the Storybook config.
* Try reloading the page.

If the problem persists, check the browser console, or the terminal you've run Storybook from.
```

Reloading the page does not make a difference and there are no logs in the web-console.
When I manually select the docs or component stories from the sidebar they still work as intended.

**main.js > stories**

```
{
	stories: ["../atomic-design/**/*.stories.@(ts|tsx|mdx)"]
}
```
with this structure: 

<img width="262" alt="Screen Shot 2021-08-11 at 08 36 29" src="https://user-images.githubusercontent.com/1148334/128981123-6b876b61-a0c3-4fe4-9894-9c8ec43ecf44.png">

</details>
____

@shilman is the mentioned loader still required/suggested? (AFAIK it used to be documented)

It can still be found if you search (via: https://storybook.js.org/docs/react/get-started/introduction) but is not mentioned anywhere (maybe the search is not reflecting the newest state?)

**Screenshots:**

<img width="543" alt="Screen Shot 2021-08-11 at 08 00 15" src="https://user-images.githubusercontent.com/1148334/128977416-764d7060-843f-4de8-9121-657f74ec4049.png">

<img width="1240" alt="Screen Shot 2021-08-11 at 08 03 07" src="https://user-images.githubusercontent.com/1148334/128977622-9908b4e9-6e39-4d65-871e-2d03f3e2efdb.png">


> @pixelass Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). 🙏

I will open-source the repository where I noticed these issues in a few days, so hopefully that will help you. (it is currently still private)

**Comment by xavierstampslafont** [comment] 2021-09-29 22:03
I have this issue as well with these dependencies: 
- TypeScript 4.4.3
- StoryBook 6.3.8

I'm disabling docgen for now, but hoping for a fix soon! We love Storybook and rely on it 😄 Thank you!

**Comment by AndrewKiri** [comment] 2022-01-25 22:41
We also had this issue as well, with following deps:
- `"typescript": "^4.5.4"`
- `"@storybook/react": "^6.2.9",`

Running `npx sb@latest upgrade` helped resolve them without the need to pin TS version or any other hacks

Kudos to maintainers 🎉

**Comment by GarrisonD** [comment] 2022-07-27 07:23
Upgrading `@storybook/react` and `typescript` to the latest has helped me, but `addon-knobs` stopped working.

Decided to go with `typescript: { reactDocgen: false }` for now.

**Comment by ndelangen** [comment] 2023-01-18 00:06
Please migrate to use controls:
https://storybook.js.org/docs/react/essentials/controls#page-top

**Closed by ndelangen** 2023-01-18 00:06 UTC
Labels: bug, dependencies, app: react, has workaround, typescript

**Comment by lehighjcut** [comment] 2023-01-18 00:13
@ndelangen I'm a bit confused. Does that mean CSF in Typescript is not supported? If there are certain versions required then should we note that officially?

**Comment by ndelangen** [comment] 2023-01-18 00:18
CSF not supported in typescript? It sure is! @kasperpeulen has worked an tremendous amount to make it a super smooth experience! Using the new `satisfies` operator.

**Comment by douglasjunior** [comment] 2023-03-30 13:39
For those that are trying with React Native, fixing this version on my package.json solves the issue: https://github.com/styleguidist/react-docgen-typescript/issues/356#issuecomment-1032805986

```json
  "resolutions": {
    "react-docgen-typescript": "2.2.2"
  }
```
