### ISSUE TITLE
Webpack5 Builder - Stories cannot be explicitly sorted

### ISSUE THREAD

**Issue by sashafklein** [storybookjs/storybook#17665] opened 2022-03-09 00:09 UTC
**Describe the bug**

I just updated from the Webpack 4 Builder to Webpack 5, and my stories are suddenly sorted differently. Specifically, whereas they used to display in order of export, they now sort alphabetically. In other words, the below code would produce a storybook with `Later` showing up before `MeFirst`

```js
// This would show up first
export const MeFirst = ...
// This would show up later, even though L precedes M
export const Later = ...
```

Looked at the [sorting docs](https://storybook.js.org/docs/react/writing-stories/naming-components-and-hierarchy#sorting-stories), and the objects passed to the `storySort` option in `parameters`, but it appears the native export order is not given to this sorting function. Is there any way to have the order of the story exports determine their appearance?

**System**
```
  System:
    OS: macOS 12.0.1
    CPU: (10) x64 Apple M1 Pro
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    npm: 7.5.3 - ~/.nvm/versions/node/v12.13.0/bin/npm
  Browsers:
    Chrome: 99.0.4844.51
    Firefox: 96.0.2
    Safari: 15.1
  npmPackages:
    @storybook/addon-a11y: ^6.4.19 => 6.4.19 
    @storybook/addon-actions: ^6.4.19 => 6.4.19 
    @storybook/addon-essentials: ^6.4.19 => 6.4.19 
    @storybook/addon-links: ^6.4.19 => 6.4.19 
    @storybook/builder-webpack5: ^6.4.19 => 6.4.19 
    @storybook/manager-webpack5: ^6.4.19 => 6.4.19 
    @storybook/node-logger: ^6.4.19 => 6.4.19 
    @storybook/preset-create-react-app: ^4.0.1 => 4.0.1 
    @storybook/preset-scss: ^1.0.3 => 1.0.3 
    @storybook/react: ^6.4.19 => 6.4.19 
```

**Comment by kkakroo** [comment] 2022-03-16 11:47
I had been on webpack5 builder for a while but started seeing this issue after one of the recent updates.
However removing webpack5 builder fixed the issue for now, thanks.

**Comment by rdebeasi** [comment] 2022-04-01 14:01
Related: #17847

**Comment by rdebeasi** [comment] 2022-04-04 16:19
Here's a [repro using @storybook/angular 6.5.0-alpha.55](https://github.com/rdebeasi/storybook-sort-repro).

Thanks in advance for looking into this! 😄

**Comment by catdc2017** [comment] 2022-04-06 14:31
Just leaving a comment so I will be updated on any updates on this issue - suffering the same issue. Thx 😔

**Comment by rdebeasi** [comment] 2022-04-06 16:02
Thanks for your interest! In the future, you can receive updates by clicking the "subscribe" button on the right side of the page. 😄

**Comment by catdc2017** [comment] 2022-04-06 16:02
I found a work around for this issue.  The sort is occurring on the export const

```
export const A = () => {
    const labelText = text(LABEL, LABEL_DEFAULT, GENERAL);
    const helperText = text(HELPER_TEXT, HELPER_TEXT_DEFAULT, GENERAL);
    return {
        moduleMetadata: {
            imports: [AutocompleteReactiveModule],
        },
        component: AutocompleteReactiveComponent,
        props: {
            labelText,
            helperText,
        },
    };
};

A.storyName = 'Basic';
A.parameters = { docs: { page: AutocompleteReactiveMDX }, themes: getThemeConfig() };
```

So if you name the const alphabetically as you want them in your stories.ts it will work in production correctly 

**Example below sorts correctly in production**

A.storyName = 'Basic';
B.storyName = 'API';
C.storyName = 'Guidelines';

**Example below does not sort correctly in production**

Basic.storyName = 'Basic';
API.storyName = 'API';
Guidelines.storyName = 'Guidelines';

**Comment by catdc2017** [comment] 2022-04-06 16:04
Obviously I would be more interested in a correct fix of course rather than work around 😀

**Comment by brandonmcconnell** [comment] 2022-04-15 18:26
I've been noticing this lately as well. Even if alphabetical is the new default, there should be a way using [`storySort`](https://storybook.js.org/docs/react/writing-stories/naming-components-and-hierarchy#sorting-stories) to enforce intrinsic/export order.

This would be possible if the intrinsic order were included as an integer somewhere in the sort method's callback function, but it does not appear to be.

**Comment by shilman** [comment] 2022-04-17 18:28
closing as dupe to #15574

**Closed by shilman** 2022-04-17 18:28 UTC
Labels: bug, webpack5, needs triage

**Comment by symmetriq** [comment] 2022-05-25 06:50
This was fixed in 6.5, but is now broken again in 6.5.5.

**Comment by shilman** [comment] 2022-05-25 07:55
@symmetriq do you have a reproduction you can share? Or, specifically, can you share your `stories` glob from `.storybook/main.js`?

**Comment by symmetriq** [comment] 2022-05-25 11:04
@shilman

```js
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
```

**Comment by rshackleton** [comment] 2022-06-16 15:20
Also seeing this issue after switching to the webpack 5 builder.

```
stories: ['../src/stories/**/*.stories.mdx', '../src/stories/**/*.stories.@(js|jsx|ts|tsx)']
```

**Comment by siminino** [comment] 2022-06-22 09:43
Also seeing this issue after upgrading to 6.5.9, using builder webpack 5 and React.
Now, any story that alphabetically sorting comes before "Default" (ex: Bottom) becomes the default story. So, Default is not default anymore.

**Comment by symmetriq** [comment] 2022-06-22 10:26
For me, stories are sorted as expected (in `export` order, not alphabetical) as of Storybook 6.5.8. I'm now using 6.5.9 and it's still working correctly. There must be some other factor involved.

**Comment by siminino** [comment] 2022-06-22 10:57
You are totally right @symmetriq. I have just found the "other factor" involved.

We use the filename format `*.example.js` in our project. This is our storybook `main.js`:
```javascript
module.exports = {
  stories: ['../src/components/**/*.example.js'],
  framework: '@storybook/react',
  addons: [
    '@storybook/addon-actions',
    '@storybook/addon-viewport',
    '@storybook/addon-knobs',
    '@storybook/addon-docs',
    '@storybook/addon-controls',
    '@storybook/addon-measure',
    '@storybook/addon-outline',
  ],
  core: {
    builder: 'webpack5',
  },
}
```

After changing one story filename to `*.stories.js` and updating `main.js` to search for this pattern, it sorts as expected.

So, we have an issue where we must use the proposed stories filename format to make sorting works properly.

**Comment by siminino** [comment] 2022-06-22 11:25
I open i new ticket for it https://github.com/storybookjs/storybook/issues/18535
