### ISSUE TITLE
[Bug]: Vite builder for storybook fails to build in Vite + TS + React project in Node 18

### ISSUE THREAD

**Issue by erkinun** [storybookjs/storybook#20209] opened 2022-12-12 16:55 UTC
### Describe the bug

I create a new Vite project with React and Typescript enabled. I then add storybook to this project (using `npx storybook init`) and try to build the storybook. I get the following error (note: I'm using Node 18V LTS for this exercise which is `v18.12.1`). 

```
yarn run build-storybook
yarn run v1.22.19
$ build-storybook
info @storybook/react v6.5.14
info
info => Cleaning outputDir: /Users/erkinunlu/temp/vite-test/storybook-test/test-vite-builder-sb/storybook-static
info => Loading presets
info => Compiling manager..
(node:4698) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
vite v4.0.0 building for production...
transforming (1) iframe.htmlnode:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/erkinunlu/temp/vite-test/storybook-test/test-vite-builder-sb/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/erkinunlu/temp/vite-test/storybook-test/test-vite-builder-sb/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/erkinunlu/temp/vite-test/storybook-test/test-vite-builder-sb/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/erkinunlu/temp/vite-test/storybook-test/test-vite-builder-sb/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/erkinunlu/temp/vite-test/storybook-test/test-vite-builder-sb/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/erkinunlu/temp/vite-test/storybook-test/test-vite-builder-sb/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/erkinunlu/temp/vite-test/storybook-test/test-vite-builder-sb/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/erkinunlu/temp/vite-test/storybook-test/test-vite-builder-sb/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/erkinunlu/temp/vite-test/storybook-test/test-vite-builder-sb/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/erkinunlu/temp/vite-test/storybook-test/test-vite-builder-sb/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/erkinunlu/temp/vite-test/storybook-test/test-vite-builder-sb/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### To Reproduce

```shell
mkdir test-vite-sb
cd test-vite-sb
yarn create vite # leave project name empty, select React and Typescript
cd vite-project
npx storybook init
yarn run build-storybook
```

### System

```shell
Environment Info:

  System:
    OS: macOS 12.6.1
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 108.0.5359.98
    Firefox: 106.0.2
    Safari: 15.6.1
  npmPackages:
    @storybook/addon-actions: ^6.5.14 => 6.5.14
    @storybook/addon-essentials: ^6.5.14 => 6.5.14
    @storybook/addon-interactions: ^6.5.14 => 6.5.14
    @storybook/addon-links: ^6.5.14 => 6.5.14
    @storybook/builder-vite: ^0.2.5 => 0.2.5
    @storybook/react: ^6.5.14 => 6.5.14
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

**Comment by sumicet** [comment] 2022-12-13 16:37
I have the same project setup: react + vite + ts + node 18.12.0.

Also got this issue after running `npx storybook init` and installing `"html-webpack-plugin": "^5.5.0"` as suggested [here](https://github.com/storybookjs/storybook/issues/13332).

**Comment by dopry** [comment] 2022-12-14 14:31
Duplicate of #16555

**Comment by gaeundev** [comment] 2022-12-15 04:37
I solved it like this.

package.json

```
"scripts": {
//...
    "storybook": "NODE_OPTIONS=--openssl-legacy-provider start-storybook -p 6006",
//...
  },
```


reference : https://www.newline.co/@kchan/how-to-fix-the-error-errorerror0308010cdigital-envelope-routinesunsupported--0f8d3f17

**Comment by joshwooding** [comment] 2022-12-19 23:52
Closing as duplicate of https://github.com/storybookjs/storybook/issues/16555

**Closed by joshwooding** 2022-12-19 23:52 UTC
Labels: bug, needs triage

**Comment by mikedownesdev** [comment] 2023-03-08 22:33
Same, got me unstuck today! Thanks @gaeundev
