### ISSUE TITLE
[Bug]: Cannot destructure property 'preprocess' of 'svelteOptions' as it is undefined.

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#21415] opened 2023-03-06 09:19 UTC
### Describe the bug

Users reporting this error after upgrade using `svelte-vite` framework. This is probably due to this line:

https://github.com/storybookjs/storybook/blob/next/code/frameworks/svelte-vite/src/preset.ts#L25

**Comment by JReinhold** [comment] 2023-03-06 12:40
Are we sure this isn't already fixed by https://github.com/storybookjs/storybook/pull/21339 ?

**Comment by JReinhold** [comment] 2023-03-16 22:46
I'm pretty sure #21339 fixes this because:

- I cannot reproduce this in `rc.3`
- I cannot reproduce this in `beta.60`, where that fix was released
- I **can** reproduce this in `beta.59`, without that fix.

**Closed by JReinhold** 2023-03-16 22:46 UTC
Labels: bug, svelte, reported
