### ISSUE TITLE
Create storyshots migration guide

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#21071] opened 2023-02-13 14:03 UTC

**Comment by shilman** [comment] 2023-02-17 11:07
Follow up on [#21009](https://github.com/storybookjs/storybook/issues/21009) when ready

**Comment by aendra-rininsland** [comment] 2023-03-07 17:49
Until the migration guide is written, mind giving some clarity about what's happening with snapshot testing in Storybook? [This page](https://storybook.js.org/docs/7.0/react/writing-tests/snapshot-testing) in the 7.x docs still indicates Storyshots is supported, which contradicts what you say [in this issue](https://github.com/storybookjs/storybook/issues/12392#issuecomment-1398456543).

I've been really scratching my head the last hour trying to figure out what to do.

**Comment by shilman** [comment] 2023-04-21 03:26
Sorry for the slow reply here @aendra-rininsland 

Storyshots is still supported but we hope to deprecate it in the future.

The migration guide will provide recipes for transitioning to other snapshotting solutions such as
- [The test runner](https://storybook.js.org/docs/react/writing-tests/test-runner)
- [Chromatic](https://www.chromatic.com/)

**Comment by kylegach** [comment] 2023-05-03 20:32
Closing as a dupe of #22263

**Closed by kylegach** 2023-05-03 20:32 UTC
Labels: addon: storyshots, documentation, test-runner
