### ISSUE TITLE
Yarn 2: SB not working when using a .storybook/preview.js file

### ISSUE THREAD

**Issue by ChiefORZ** [storybookjs/storybook#10094] opened 2020-03-10 11:03 UTC
**Describe the bug**

We tried to migrate our package to yarn v2 with `@storybook/react v6.0.0-alpha.21`.
And it always fails with following error:

```sh
ERROR in ./.storybook/preview.js-generated-config-entry.js
Module not found: Error: Something that got detected as your top-level application (because it doesn't seem to belong to any package) tried to access a package that is not declared in your dependencies

Required package: @storybook/client-api (via "@storybook/client-api")
Required by: /Users/sschaffernak/dev/_yarnv2/react-toolbox/packages/react-components/.storybook/preview.js-generated-config-entry.js

 @ ./.storybook/preview.js-generated-config-entry.js 3:0-68 10:9-21 12:16-29
 @ multi /Users/sschaffernak/dev/_yarnv2/react-toolbox/.yarn/unplugged/@storybook-core-virtual-0fe8bf6b36/node_modules/@storybook/core/dist/server/common/polyfills.js /Users/sschaffernak/dev/_yarnv2/react-toolbox/.yarn/unplugged/@storybook-core-virtual-0fe8bf6b36/node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js /Users/sschaffernak/dev/_yarnv2/react-toolbox/.yarn/cache/webpack-hot-middleware-npm-2.25.0-b59f3763d7-2.zip/node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false
```

**Code snippets**
We have following config files:

```js
// .storybook/main.js
module.exports = {
  stories: ['../src/**/*.story.[tj]s'],
};
```

```js
// .storybook/preview.js
import { addDecorator } from '@storybook/react';
import { ThemeProvider } from '../src';
import Global from '../src/Global';

addDecorator(getStory => (
  <ThemeProvider theme={{ primaryColor: 'darkorange' }}>
    <Global>{getStory()}</Global>
  </ThemeProvider>
  )
);

```

**System:**

System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 2.0.0-rc.29 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
Browsers:
    Chrome: 80.0.3987.132
    Firefox: 72.0.2
    Safari: 13.0.5

**Comment by ChiefORZ** [comment] 2020-03-10 12:00
We think that it has to do with decorators, because when we remove the file `.storybook/preview.js` - it works like a charm

**Comment by gaetanmaisse** [comment] 2020-03-10 20:12
@ChiefORZ Thanks for reporting this issue, I will try to work on it soon. I added this to the Yarn 2 compatibility TODO list 😉 You can follow the WIP about Yarn 2 compatibility in this issue: #9527.

Note for future me: The problem is not the decorators directly but the `.storybook/preview.js` file, the error is thrown even with an empty file.

**Comment by GR34SE** [comment] 2020-03-19 14:48
I've got similar issue, but with running storyshots with jest. With preview.js it gives me:
`SyntaxError: Cannot use import statement outside a module`,
...and without preview.js it just works.

**Comment by shilman** [comment] 2020-03-21 03:57
Have you tried upgrading to 6.0 alpha? @gaetanmaisse has made a bunch of improvements to support Yarn 2 as part of #9527

**Comment by GR34SE** [comment] 2020-03-24 11:31
^Didn't solve the issue. Although rewriting my preview.js to common js helped

**Comment by shilman** [comment] 2020-03-25 00:23
@GR34SE "helped" as in fixed it? that's pretty weird.

**Comment by gaetanmaisse** [comment] 2020-04-07 10:15
@ChiefORZ this should be fixed in the next `alpha` release 😉

**Comment by shilman** [comment] 2020-04-07 10:31
Zoinks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.31 containing PR #10305 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by gaetanmaisse** [comment] 2020-04-07 13:26
😞 it looks like https://github.com/storybookjs/storybook/pull/10281 reintroduce the issue. I will 🔍 .

**Comment by tooppaaa** [comment] 2020-04-07 20:55
The code you changed is now going through babel. Happy to submit a new PR taking yours into account !

**Comment by gaetanmaisse** [comment] 2020-04-08 08:39
@tooppaaa you can take a look at https://github.com/storybookjs/storybook/pull/10342, in fact, it was an issue caused by `replace('{{xx}}', aStringWith$$InIt)` 🙃. I made a small refactoring in the last commit, feel free to give your feedback.

**Comment by DimitrK** [comment] 2020-04-15 12:19
I am getting a similar error on `6.0.0-alpha.34` 

```
ERROR in ./.storybook/config.js-generated-config-entry.js
Module not found: Error: Can't resolve '~/.yarn/$virtual/@storybook-client-api-virtual-90ce459e42/0/cache/@storybook-client-api-npm-6.0.0-alpha.34-34fd06ddf2-2.zip/node_modules/@storybook/client-api/dist/index.js' in '~/apps/acme/.storybook'
 @ ./.storybook/config.js-generated-config-entry.js 9:15-240
 @ multi ~/.yarn/$$virtual/@storybook-core-virtual-638b54729f/0/cache/@storybook-core-npm-6.0.0-alpha.34-1c64e1c5fb-2.zip/node_modules/@storybook/core/dist/server/common/polyfills.js ~/.yarn/$$virtual/@storybook-core-virtual-638b54729f/0/cache/@storybook-core-npm-6.0.0-alpha.34-1c64e1c5fb-2.zip/node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ./.storybook/config.js-generated-config-entry.js ~/.yarn/cache/webpack-hot-middleware-npm-2.25.0-b59f3763d7-2.zip/node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false
```

Adding `"@storybook/client-api": "^5.3.18"` as a dependency doesn't seem to work. Is there any workaround for that?

**Comment by shilman** [comment] 2020-04-15 16:23
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.35 containing PR #10342 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2020-04-15 16:23 UTC
Labels: compatibility with other tools, question / support, yarn / npm

**Comment by gaetanmaisse** [comment] 2020-04-15 16:57
@DimitrK Can you give it a try with `alpha.35`?

**Comment by DimitrK** [comment] 2020-04-15 18:44
@gaetanmaisse & @shilman  I can confirm `alpha.35` works. 🎉  Storybook starts normally now.

**Comment by shilman** [comment] 2020-04-15 23:19
@DimitrK all your `@storybook/*` should be the same version

**Comment by jasonwr** [comment] 2020-09-29 19:44
> We think that it has to do with decorators, because when we remove the file `.storybook/preview.js` - it works like a charm

I'm using Yarn 1.22 and this didn't do anything for me.

**Comment by Amay88** [comment] 2021-07-14 12:17
So I can confirm that this bug still exists in version **6.3.4** of StoryBook.  I'm using yarn **1.22.10**.

But now it seems that the root cause is quite different. 

At the beginning I had custom folder (`/config`) for configuration (by using **-c** parameter). Using `run start` cause the same issue:

`[./config/preview.js-generated-config-entry.js] 2.88 KiB {main} [built] [1 error]`

 When I moved `preview.js` (with other files, like `main,js`) to standard folder (`/.storybook`) everything started to work again.
