### ISSUE TITLE
Unable to load in IE11 with v6.1.0-beta.7

### ISSUE THREAD

**Issue by Niznikr** [storybookjs/storybook#13088] opened 2020-11-11 18:57 UTC
**Describe the bug**
Tried updating my web components Storybook from `6.0.25` (which works fine in IE11) to `v6.1.0-beta.7`. I get a blank Storybook with the attached console errors with opened in IE11. Seems to be something related to Storybook's Loader component?

**To Reproduce**

1. Update to `v6.1.0-beta.7`
2. Open up in IE11
3. Notice blank screen

**Expected behavior**
Works as expected in IE11 like it was before the upgrade.

**Screenshots**
![VirtualBox_WinDev1911Eval_11_11_2020_09_00_59](https://user-images.githubusercontent.com/2147624/98852181-4847ff80-2425-11eb-91b2-f4521a3393b8.png)

![VirtualBox_WinDev1911Eval_11_11_2020_09_01_12](https://user-images.githubusercontent.com/2147624/98852186-4da54a00-2425-11eb-94b0-59cea01ca1e4.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
Before the upgrade.

```
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 14.7.0 - ~/.nvm/versions/node/v14.7.0/bin/node
    Yarn: 1.22.5 - ~/.nvm/versions/node/v14.7.0/bin/yarn
    npm: 6.0.0 - ~/node_modules/.bin/npm
  Browsers:
    Chrome: 86.0.4240.193
    Edge: 86.0.622.63
    Firefox: 82.0.3
    Safari: 14.0
  npmPackages:
    @storybook/addon-a11y: ^6.0.25 => 6.0.25 
    @storybook/addon-actions: ^6.0.25 => 6.0.25 
    @storybook/addon-controls: ^6.0.25 => 6.0.25 
    @storybook/addon-docs: ^6.0.25 => 6.0.25 
    @storybook/addon-storysource: ^6.0.25 => 6.0.25 
    @storybook/addon-viewport: ^6.0.25 => 6.0.25 
    @storybook/addons: ^6.0.25 => 6.0.25 
    @storybook/react: ^6.0.25 => 6.0.25 
    @storybook/source-loader: ^6.0.25 => 6.0.25 
    @storybook/theming: ^6.0.25 => 6.0.25 
    @storybook/web-components: ^6.0.25 => 6.0.25 
```

**Additional context**

**Comment by stof** [comment] 2020-11-12 09:51
EventSource is not natively supported in IE 11: https://caniuse.com/eventsource
So this would require either making the feature relying on Server-Sent Events optional (disabling it when EventSource is not supported) or including the polyfill.

**Comment by shilman** [comment] 2020-11-12 09:54
@ghengeveld looks like a regression introduced by the loading UI?

**Comment by stof** [comment] 2020-11-12 10:14
The usage of EventSource was introduced in https://github.com/storybookjs/storybook/pull/12707

From my understanding, the usage of EventSource is only to show the build progress but things could work without it. So maybe disabling it in IE 11 would be enough.

**Comment by shilman** [comment] 2020-11-16 09:24
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-rc.3 containing PR #13123 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2020-11-16 09:24 UTC
Labels: bug, compatibility with other tools, ie11, ui
