### ISSUE TITLE
[Bug]: v4 links are broken

### ISSUE THREAD

**Issue by mahassan** [storybookjs/storybook#22137] opened 2023-04-18 07:52 UTC
### Describe the bug

While visiting the [page](https://github.com/storybookjs/storybook/tree/next/lib/codemod) while visiting [page](https://github.com/storybookjs/storybook/blob/master/lib/core/docs/storiesOf.md) link

### To Reproduce

visiting [page](https://github.com/storybookjs/storybook/blob/master/lib/core/docs/storiesOf.md) and click on links which are mostly brokem

**Comment by tauseefmohammed2** [comment] 2023-04-18 10:32
Hi!
I would love to contribute to the repo. I saw that the issue is labelled "first time", which is perfect for me as I am new to this project and eager to get started. Could you please assign this issue to me?

**Closed** 2023-04-24 11:22 UTC
Labels: good first issue, documentation
