### ISSUE TITLE
Storybook does not open in default browser

### ISSUE THREAD

**Issue by muster-mark** [storybookjs/storybook#15316] opened 2021-06-22 09:58 UTC
**Describe the bug**
My default browser is Firefox (if I type `open https://storybook.js.org/` in my console then it opens in Firefox. However when I run `npm run storybook` it opens in another browser I happen to have installed on my computer, called Google Chrome.

**To Reproduce**
Set Firefox as default Browser. In a Story book project, run `npm run storybook`

**System**
Environment Info:

  System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    npm: 6.14.11 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Edge: 91.0.864.54
    Firefox: 89.0.1
    Safari: 14.1.1

**Comment by shilman** [comment] 2021-06-22 10:37
FWWIW we use `better-opn` under the hood: https://www.npmjs.com/package/better-opn

**Comment by muster-mark** [comment] 2021-06-23 20:41
Well it should be possible to detect the default browser and only use better-opn if it is one of the Chromium browsers supported by better-opn. Far more annoying for it to open in a different browser than a different tab.

**Comment by shilman** [comment] 2021-06-23 23:18
@muster-mark PRs welcome!

**Comment by muster-mark** [comment] 2021-06-24 13:04
I think the issue is with better-opn to be honest, it's hardly "better" if it doesn't open in the user's preferred browser. You may wish to use open instead of better-opn, though it may annoy chrome users who enjoyed that functionality. I am satisfied by using the --ci option to prevent opening in a browser at all. I am of the opinion that not opening in a browser would be a better default anyway.

**Comment by pilar1347** [comment] 2021-06-27 00:31
You can also install `cross-env` and change the storybook command to:
`"storybook": "cross-env BROWSER=firefox start-storybook -p 6006 -s public"`
This worked for me.

**Comment by muster-mark** [comment] 2021-06-29 17:01
> You can also install `cross-env` and change the storybook command to:
> `"storybook": "cross-env BROWSER=firefox start-storybook -p 6006 -s public"`
> This worked for me.

Thanks for the idea @pilar1357 but this is a multi-dev project.

**Comment by Shofiya2003** [comment] 2021-08-23 20:43
Hello. I want to take up this issue. This would be my first open source project. Could you please furnish resources and information to get started with the project.

**Comment by shilman** [comment] 2021-08-24 00:57
Hi @Shofiya2003! Thank you for helping make Storybook better! 🙏  Please check out [how to contribute](https://storybook.js.org/docs/react/contribute/how-to-contribute) in our docs and feel free to ask questions in `#contributing` in [our Discord](https://discord.gg/storybook).

**Comment by eloisetaylor5693** [comment] 2021-11-22 16:08
This issue is still occurring :(

**Comment by richorrichard** [comment] 2021-11-22 16:34
Hi! I'm a new contributor looking for my first issue, and am interested in addressing this issue. I've  reviewed the how to contribute guide and I'm active in Discord, but I wanted to ask a question here to keep a paper trail.

What is the desired behavior? `better-opn` appears to favor chromium-based browsers over all other browsers by design. I've experimented in my own branch and it's not difficult to detect the system default browser using something like the `x-default-browser` npm package and provide a preferred browser based on system default. 

One minor consideration - the snippet used by `better-opn` handling browser opening preference is copied verbatim from `create-react-app` , so I could see a case for storybook to parallel CRA to maintain consistency for a segment of users, but I'd probably lean towards honoring the system default browser, even if it's not a Chromium-based browser.

**Comment by shilman** [comment] 2021-11-22 19:21
@richorrichard thanks for jumping in on this!! 🙏 

i think your proposal makes sense: SB should use `better-opn` only if the system default (or `BROWSER` env var?) is chromium-based, and fall back to something else otherwise.

cc @yannbf @ndelangen @MichaelArestad

**Comment by richorrichard** [comment] 2021-11-22 19:46
In that case, may I claim this issue? I'll get started on a PR with my proposed solution today too!

**Comment by ndelangen** [comment] 2021-11-22 19:57
yeah let's try to honour the system's default browser for sure!

**Comment by shilman** [comment] 2021-12-02 17:40
¡Ay Caramba!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.1 containing PR #16844 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2021-12-02 17:40 UTC
Labels: bug, good first issue, help wanted, cli, PN
