### ISSUE TITLE
Peer dependency warning for Storybook Angular.

### ISSUE THREAD

**Issue by codeNoobie** [storybookjs/storybook#4844] opened 2018-11-25 03:52 UTC
**Describe the bug**
Why do I get these warnings on Yarn install. I am trying to use storybook for angular app.

```
warning " > @storybook/addon-actions@4.0.8" has unmet peer dependency "react@*".
warning "@storybook/addon-actions > @emotion/core@0.13.1" has unmet peer dependency "react@>=16.3.0".
warning "@storybook/addon-actions > @emotion/provider@0.11.2" has unmet peer dependency "react@>=16.3.0".
warning "@storybook/addon-actions > @storybook/components@4.0.8" has unmet peer dependency "react@*".
warning "@storybook/addon-actions > @storybook/components@4.0.8" has unmet peer dependency "react-dom@*".
warning "@storybook/addon-actions > react-inspector@2.3.0" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@storybook/addon-actions > @emotion/styled > @emotion/styled-base@0.10.6" has unmet peer dependency "react@>=16.3.0".
warning "@storybook/addon-actions > @storybook/components > react-textarea-autosize@7.0.4" has unmet peer dependency "react@>=0.14.0 <17.0.0".
warning "@storybook/addon-actions > @storybook/components > render-fragment@0.1.1" has unmet peer dependency "react@^15.0.0 || ^16.0.0".
warning " > @storybook/addon-backgrounds@4.0.8" has unmet peer dependency "react@*".
warning " > @storybook/addon-jest@4.0.8" has unmet peer dependency "react@*".
warning " > @storybook/addon-knobs@4.0.8" has unmet peer dependency "react@*".
warning " > @storybook/addon-links@4.0.8" has unmet peer dependency "react@*".
warning " > @storybook/addon-notes@4.0.8" has unmet peer dependency "react@*".
warning " > @storybook/addon-options@4.0.8" has unmet peer dependency "react@*".
warning "@storybook/addon-storyshots > jest-specific-snapshot@1.0.0" has unmet peer dependency "jest@*".
warning " > @storybook/addon-storysource@4.0.8" has unmet peer dependency "react@*".
warning "@storybook/addon-storysource > react-syntax-highlighter@10.1.1" has unmet peer dependency "react@>= 0.14.0".
```

Do I need to provide react libs in my package.json?

**Comment by shilman** [comment] 2018-11-25 07:43
You shouldn't need to. Recent versions of `@storybook/angular` depends on `react@^16.6.0` and `react-dom@^16.6.0`, so it should just work. What version of Storybook are you using? And can you upgrade to the latest stable release if you're not already on it?

**Comment by codeNoobie** [comment] 2018-11-25 08:59
@shilman I am still seeing this with v4.0.8. I am using Yarn.

**Comment by codeNoobie** [comment] 2018-11-26 04:03
Yes. It does work. But the warnings are annoying. Adding a dev dependency on react in an Angular based repository could raise eyebrows as well. 

What's your recommendation? Keep the warnings or add react to dev dependency?

**Comment by igor-dv** [comment] 2018-11-26 06:35
I think you can keep warnings for now.

After https://github.com/storybooks/storybook/releases/tag/v4.1.0-alpha.4 we can just hide react dep in all the addons that are bundled to the manager. We need to make sure that the React in manager is our React though 🤔 Maybe with aliasing. CC: @ndelangen @shilman

**Comment by igor-dv** [comment] 2018-11-26 08:32
@codeNoobie , I would very like you to contribute =) also you can hang with us on Discord.

**Comment by codeNoobie** [comment] 2018-11-26 19:30
@igor-dv Thanks. Let's discuss this change soon. Please also move this issue to open state.

**Comment by igor-dv** [comment] 2018-11-26 21:01
Sure.

**Comment by codeNoobie** [comment] 2018-12-03 00:52
@igor-dv What if we replace peer dependency on react with optional dependency on react? We can put some fallback code in the manager to fail/ignore gracefully?

https://docs.npmjs.com/files/package.json#optionaldependencies

**Comment by igor-dv** [comment] 2018-12-03 22:40
The problem is that optional deps are like real deps, but when there is a problem with installing it, it won't fail the whole installation... I am not sure this fits the `react` pkg in our case...

**Comment by igor-dv** [comment] 2018-12-04 22:29
@codeNoobie , do you need help with this?

**Comment by michalsnik** [comment] 2019-07-23 14:03
Is it safe now to remove these peer dependencies?

**Comment by dbendaou** [comment] 2019-12-20 10:31
I'm having the same issue with Ember 
<img width="900" alt="Screenshot 2019-12-20 at 11 30 55" src="https://user-images.githubusercontent.com/15218861/71248853-34cb0c00-231c-11ea-81b9-cafd37645364.png">

**Comment by Roen00** [comment] 2020-01-20 13:05
What's the status this issue? Should we worry about these warnings?

**Comment by shilman** [comment] 2020-01-21 00:50
@Roen00 no need to worry about these issues. At some point we'll need to do a refactor to address this, but it's low on our priorities.

**Comment by memark** [comment] 2020-04-10 17:30
I get an equally large bunch of warnings on React/CRA.

![image](https://user-images.githubusercontent.com/318504/79010162-afd16000-7b61-11ea-8243-94a87a87c0bd.png)

@codeNoobie Are you still working on this? :)

**Comment by timtos** [comment] 2020-07-17 08:11
For me the same with the latest version:

![image](https://user-images.githubusercontent.com/2648014/87763790-9cdfc300-c815-11ea-8252-5fe8bedaa2c7.png)

Any updates on this?

**Comment by cguilhermef** [comment] 2020-10-22 14:07
There is a workaround to suppress this huge bunch of warnings? I'm working with Angular, in an NX workspace.

**Comment by david-shortman** [comment] 2021-04-01 19:12
^ In same situation as above, would be cool to resolve

**Comment by Frikki** [comment] 2021-06-07 13:51
This should be an easy fix to remove these warnings if they are redundant.

**Comment by Morglod** [comment] 2023-01-26 15:04
jesus just split this addons by frameworks

**Comment by valentinpalkovic** [comment] 2023-05-08 14:41
Almost all unmet peer dependency warnings don't occur in Storybook 7 anymore. Therefore closing this.

**Closed by valentinpalkovic** 2023-05-08 14:41 UTC
Labels: question / support, good first issue, angular
