### ISSUE TITLE
[Bug]: Module parse failed: Unexpected token (17:1) You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file

### ISSUE THREAD

**Issue by NTC-THSTO** [storybookjs/storybook#26576] opened 2024-03-20 08:30 UTC
### Describe the bug

when running yarn build-storybook or yarn storybook:

yarn build-storybook
@storybook/cli v7.6.17

info => Cleaning outputDir: \storybook-static
info => Loading presets
info => Building manager..
info => Manager built (382 ms)
info => Building preview..    
info => Copying static files: C:\work\repos\NCMCORE\src\react\storybook\node_modules\@storybook\manager\static at C:\work\repos\NCMCORE\src\react\storybook\storybook-static\sb-common-assets
WARN No story files found for the specified pattern: src\**\*.mdx
WARN Expected '@storybook/addon-actions' (or '@storybook/addon-essentials') to be listed before '@storybook/addon-interactions' in main Storybook config.
info Using Babel compiler
info Addon-docs: using MDX2
info => Using implicit CSS loaders
info => [@storybook/addon-styling-webpack] Applying custom Storybook webpack configuration styling.
info => Using default Webpack5 setup
Module parse failed: Unexpected token (17:1)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   icon,
|   ...props
> }: AlertMessageProps) => {
|   const currentTheme = useContext(ThemeContext);
|   return (
Module parse failed: Unexpected token (4:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import { LucideProps } from 'lucide-react';
| 
> export interface AlertMessageProps extends AlertStyledProps {
|   ptKey?: string;
|   prefixOverride?: string;
=> Failed to build the preview
SB_BUILDER-WEBPACK5_0003 (WebpackCompilationError): There were problems when compiling your code with Webpack.
Run Storybook with --debug-webpack for more information.
    at .\node_modules\@storybook\builder-webpack5\dist\index.js:1:10937
    at .\node_modules\webpack\lib\HookWebpackError.js:68:3
    at _done (eval at create (.\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:14:1)
    at eval (eval at create (.\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:44:22)

as soon as the story file which is based on an external component is deleted it builds fine without errors.

### To Reproduce

main.ts:
```
import type { StorybookConfig } from "@storybook/react-webpack5";
import TsconfigPathsPlugin from 'tsconfig-paths-webpack-plugin';
import { join, dirname } from "path";

/**
 * This function is used to resolve the absolute path of a package.
 * It is needed in projects that use Yarn PnP or are set up within a monorepo.
 */
function getAbsolutePath(value: string): any {
  return dirname(require.resolve(join(value, "package.json")));
}
const config: StorybookConfig = {
  stories: ["../src/**/*.mdx", "../src/**/*.stories.@(js|jsx|mjs|ts|tsx)"],
  addons: [
    getAbsolutePath("@storybook/addon-links"),
    getAbsolutePath("@storybook/addon-actions"),
    getAbsolutePath("@storybook/addon-essentials"),
    getAbsolutePath("@storybook/addon-onboarding"),
    getAbsolutePath("storybook-css-modules-preset"),
    getAbsolutePath("@storybook/addon-themes"),
    getAbsolutePath("@storybook/addon-viewport"),
    getAbsolutePath("@storybook/addon-controls"),
    getAbsolutePath("@storybook/addon-outline"),
    getAbsolutePath("@storybook/addon-styling-webpack"),
    getAbsolutePath("@storybook/addon-interactions"),
  ],
  framework: {
    name: getAbsolutePath("@storybook/react-webpack5"),
    options: {},
  },
  docs: {
    autodocs: "tag",
  },
  core: {
    builder: {
      name: '@storybook/builder-webpack5',
      options: {
        fsCache: true,
        lazyCompilation: true,
      },
    },
  },
  webpackFinal: async (config) => {
    if (config.resolve) {
      config.resolve.plugins = [
        ...(config.resolve.plugins || []),
        new TsconfigPathsPlugin({
          extensions: config.resolve.extensions,
        }),
      ];
    }
    return config;
  },
};
export default config;
```

webpack.config.ts
```
import { TsconfigPathsPlugin } from "tsconfig-paths-webpack-plugin";
import path from "path";

module.exports = {
    entry: './src/index.tsx',
    mode: 'development',
    output: {
        filename: 'bundle.js',
        path: path.resolve(__dirname, 'dist'),
    },
    resolve: {
        extensions: ['.ts', '.tsx', '.js', '.jsx'],
        modules: [path.resolve(__dirname, '../src'), 'node_modules'],
        plugins: [new TsconfigPathsPlugin({ configFile: './tsconfig.json' })],
    },
    module: {
        rules: [
            {
                test: /\.(ts|tsx)$/,
                use: [
                    {
                        loader: 'babel-loader',
                        options: {
                            presets: [
                                ['@babel/preset-env', { targets: 'defaults' }],
                                '@babel/preset-react',
                                '@babel/preset-typescript',
                            ],
                        },
                    },
                    {
                        loader: 'ts-loader',
                    },
                ],
            },
        ],
    },
};
```

preview.ts: 
```
import type { Preview } from "@storybook/react";

const preview: Preview = {
  parameters: {
    actions: { argTypesRegex: "^on[A-Z].*" },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/,
      },
    },
  },
};

export default preview;
```

the story in question:
```
import React from 'react';

import { Alert } from '@amplio/core/core/components/Alert/Alert';
import { AlertType } from '@amplio/core/core/components/Alert/types';

export default {
  component: Alert,
  title: 'Alert',
  tags: ['autodocs'],
};

const alertMessages = {
  Default: { type: AlertType.INFO, message: 'This is a default alert message.' },
  Warning: { type: AlertType.WARNING, message: 'This is a warning alert message.' },
  Error: { type: AlertType.ERROR, message: 'This is an error alert message.' },
  Reserved: { type: AlertType.RESERVED, message: 'This is a reserved alert message.' },
  Protected: { type: AlertType.PROTECTED, message: 'This is a protected alert message.' },
  Success: { type: AlertType.SUCCESS, message: 'This is a success alert message.' },
};

export const AlertStories = () => (
  <>
    {Object.entries(alertMessages).map(([key, { type, message }]) => (
      <Alert key={key} type={type} condition={true} message={message} />
    ))}
  </>
);

```

alert component: 
```
import { AlertMessageProps } from 'core/components/Alert/types';
import React, { useContext } from 'react';
import { ThemeContext } from 'styled-components';
import { Portaltext } from 'core/components/Portaltext/Portaltext';
import { AlertContent } from 'core/components/Alert/AlertContent';
import { StyledAlertMessage } from 'core/components/Alert/styles';

export const Alert = ({
  ptKey,
  prefixOverride,
  ptArgs,
  message,
  type,
  condition,
  icon,
  ...props
}: AlertMessageProps) => {
  const currentTheme = useContext(ThemeContext);
  return (
    <>
      {condition && (
        <StyledAlertMessage type={type} currentTheme={currentTheme} role="alert" {...props}>
          {ptKey != null ? (
            <AlertContent
              icon={icon}
              currentTheme={currentTheme}
              message={<Portaltext ptKey={ptKey} args={ptArgs} prefixOverride={prefixOverride} />}
            />
          ) : (
            message != null && <AlertContent message={message} icon={icon} />
          )}
        </StyledAlertMessage>
      )}
    </>
  );
};
```

we do make use of index exporters:
```
export { Alert } from 'core/components/Alert/Alert';
export { AlertType } from 'core/components/Alert/types';
export type {
  AlertContentProps,
  AlertMessageProps,
  AlertStyledProps,
  AlertCellProps,
} from 'core/components/Alert/types';
```

### System

```bash
Storybook Environment Info:

  System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 PRO 5850U with Radeon Graphics
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.6.3 - ~\AppData\Roaming\npm\yarn.CMD <----- active
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.92)
  npmPackages:
    @storybook/addon-actions: ^8.0.0 => 7.6.17
    @storybook/addon-controls: 7.6.17 => 7.6.17
    @storybook/addon-essentials: 7.6.17 => 7.6.17
    @storybook/addon-interactions: 7.6.17 => 7.6.17
    @storybook/addon-links: 7.6.17 => 7.6.17
    @storybook/addon-onboarding: 1.0.11 => 1.0.11
    @storybook/addon-styling-webpack: ^0.0.6 => 0.0.6
    @storybook/addon-themes: ^7.6.17 => 7.6.17
    @storybook/blocks: 7.6.17 => 7.6.17
    @storybook/components: ^8.0.1 => 8.0.1
    @storybook/react: 7.6.17 => 7.6.17
    @storybook/react-webpack5: 7.6.17 => 7.6.17
    @storybook/test: ^7.6.17 => 7.6.17
    @storybook/testing-library: 0.2.2 => 0.2.2
    eslint-plugin-storybook: ^0.7.0 => 0.7.0
    storybook: ^7.6.17 => 7.6.17
    storybook-css-modules-preset: ^1.1.1 => 1.1.1
```
```


### Additional context

_No response_

**Comment by kondo0602** [comment] 2024-03-28 05:54
In my case, [this addon](https://github.com/storybookjs/addon-webpack5-compiler-babel) solved the same error.

https://storybook.js.org/docs/builders/webpack#babel

**Comment by hamza14khan** [comment] 2024-04-09 15:52
> In my case, [this addon](https://github.com/storybookjs/addon-webpack5-compiler-babel) solved the same error.
> 
> https://storybook.js.org/docs/builders/webpack#babel

You are a legend man!

**Comment by valentinpalkovic** [comment] 2024-04-09 17:58
This is more or less a duplicate of https://github.com/storybookjs/storybook/issues/26439. The problem is elaborated [here](https://github.com/storybookjs/storybook/issues/26439#issuecomment-2033775338).

Closing this as duplicate.

**Closed by valentinpalkovic** 2024-04-09 17:58 UTC
Labels: bug, duplicate, needs triage

**Comment by Kasssiopea** [comment] 2024-07-22 12:30
```
/** @type { import('@storybook/nextjs').StorybookConfig } */
const config = {
  stories: ['../src/**/*.mdx', '../src/**/*.stories.@(js|jsx|mjs|ts|tsx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-onboarding',
    '@storybook/addon-interactions',
    '@storybook/addon-links',
  ],
  framework: {
    name: '@storybook/nextjs',
    options: {},
  },
  docs: {
    autodocs: 'tag',
  },
  features: {
    storyStoreV7: true,
  },
  core: {
    builder: {
      name: 'webpack5',
      options: {
        fsCache: true,
        lazyCompilation: true,
      },
    },
  },
  webpackFinal: async (config) => {
    config.module.rules.push({
      test: /\.(js|jsx)$/,
      include: /node_modules/,
      use: {
        loader: 'babel-loader',
        options: {
          presets: ['@babel/preset-env', '@babel/preset-react'],
        },
      },
    });

    config.resolve.extensions.push('.js', '.jsx');

    return config;
  },

};
export default config;
``` I also had this bug but here's how I fixed it
