### ISSUE TITLE
[Bug]: Inconsistent action log when action argument is falsy

### ISSUE THREAD

**Issue by skyh** [storybookjs/storybook#26927] opened 2024-04-23 14:14 UTC
### Describe the bug

The screenshot contains onClick action invoked with different arguments:

![image](https://github.com/storybookjs/storybook/assets/413429/adb6366c-9b47-4c82-a25a-6d26ec6272b4)

Single argument actions containing "falsy" values have different log format than other

### To Reproduce

```tsx
// demo.stories.tsx

import { action } from '@storybook/addon-actions'
import { useCallback } from '@storybook/client-api'
import { StoryFn } from '@storybook/react'

export default {
  component: () => null,
}

export const Demo: StoryFn = () => {
  const runTestActions = useCallback(() => {
    const onClickAction = action('onClick')

    onClickAction(3)
    onClickAction(2)
    onClickAction(1)
    onClickAction(0)
    onClickAction(true)
    onClickAction(false)
    onClickAction(null)
    onClickAction(undefined)
    onClickAction(undefined, undefined)
    onClickAction(undefined, undefined, undefined)
  }, [])

  return <button onClick={runTestActions}>Run test (result in addon-actions tab)</button>
}
```

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.4.1
    CPU: (12) arm64 Apple M2 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - /opt/homebrew/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.5.0 - /opt/homebrew/bin/npm
    pnpm: 9.0.5 - /opt/homebrew/bin/pnpm <----- active
  Browsers:
    Chrome: 124.0.6367.62
    Safari: 17.4.1
  npmPackages:
    @storybook/addon-actions: 7.6.17 => 7.6.17 
    @storybook/addon-essentials: 7.6.17 => 7.6.17 
    @storybook/addon-interactions: 7.6.17 => 7.6.17 
    @storybook/addon-links: 7.6.17 => 7.6.17 
    @storybook/blocks: 7.6.17 => 7.6.17 
    @storybook/client-api: 7.6.17 => 7.6.17 
    @storybook/react: 7.6.17 => 7.6.17 
    @storybook/react-webpack5: 7.6.17 => 7.6.17 
    @storybook/testing-library: ^0.2.2 => 0.2.2 
    storybook: 7.6.17 => 7.6.17
```

**Comment by Spielboerg** [comment] 2024-04-29 12:38
Duplicate of #22163

**Comment by shilman** [comment] 2024-05-25 03:34
If you try upgrading to the latest release that should fix it.

```
npx storybook@latest upgrade
```

Migration guide: https://storybook.js.org/docs/8.0/migration-guide

**Closed by shilman** 2024-05-25 03:34 UTC
Labels: bug, needs triage
