### ISSUE TITLE
[Bug]: Loki can't extract stories - Storybook 7

### ISSUE THREAD

**Issue by jfgreffier** [storybookjs/storybook#19543] opened 2022-10-19 15:57 UTC
### Describe the bug

Loki, a visual testing tool for Storybook, cannot extract stories when using Vite and Storybook 7. It is fine with Storybook 6.5.12 using Vue3 and Webpack, got similar issue with Storybook 6.5.12 and vite using

Error message is `Cannot call extract() unless you call cacheAllCSFFiles() first.`

### To Reproduce

Project to reproduce
https://github.com/jfgreffier/vite-sb7-loki-issue

Run storybook then Loki
```shell
npm install
npm run storybook
# In parallel, in another terminal
npx loki update
```

Issue:
The following error message is shown
```
loki update v0.30.3
 FAIL  chrome.docker
       Fetching stories
       Cannot call extract() unless you call cacheAllCSFFiles() first.
Some visual tests failed to run
```

### System

```shell
Environment Info:

  System:
    OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Firefox: 103.0
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-alpha.39 => 7.0.0-alpha.39
    @storybook/addon-interactions: ^7.0.0-alpha.39 => 7.0.0-alpha.39
    @storybook/addon-links: ^7.0.0-alpha.39 => 7.0.0-alpha.39
    @storybook/testing-library: ^0.0.13 => 0.0.13
    @storybook/vue3: ^7.0.0-alpha.39 => 7.0.0-alpha.39
    @storybook/vue3-vite: ^7.0.0-alpha.39 => 7.0.0-alpha.39
```

**Comment by canastro** [comment] 2023-01-17 14:42
Is there a way to call attention to this issue? Is this an issue with storybook or something that Loki should change on their end to be compatible with sb7?

This is the only blocker on an otherwise super smooth upgrade from sb6 to sb7.

**Comment by shilman** [comment] 2023-02-03 13:48
Is it also an issue in SB7 webpack?

**Comment by shilman** [comment] 2023-02-03 13:56
Looks like it might be a Loki thing. I googled the error and found the following fix for storycap, another Storybook-based testing toool:

https://github.com/reg-viz/storycap/pull/605

I didn't look into in detail, but my guess is that this is what's happening:
- SB7 uses a new data structure by default, called story store v7 (ssv7). It comes with a bunch of performance improvements and is "the way forward". Sounds like storycap made a fix for ssv7.
- SB7 also has a feature flag to opt out of ssv7. I suspect if you do this, it will fix Loki. Ideally Loki gets v7 compatibility, because this isn't a good fix. But perhaps it can get you unstuck in the short term:

```js
export default {
  features: { storyStoreV7: false }
}
```

If you try it out, please comment back whether or not it works. In the meantime, setting this to "has workaround" until I hear otherwise.

**Comment by ndelangen** [comment] 2023-02-06 15:18
If any Loki / reg-viz developer want to contact me to get some direct support to get it to support 7.0, please reach out to me directly:
https://calendly.com/chromaui

**Comment by HoneyQumo** [comment] 2023-04-21 11:34
Gentlemen, tell me, is there any change in this problem?

**Comment by ndelangen** [comment] 2023-04-28 14:13
I'm going to close this, as this ticket should exist on the loki repository, not here.

This is not a bug, but a breaking change in 7.0 that was intentional, keeping this open isn't helping anyone.
If you're experiencing this, please report it to the Loki maintainers or collaborate with them to find a way forwards.

**Closed by ndelangen** 2023-04-28 14:13 UTC
Labels: question / support, compatibility with other tools, has workaround
