### ISSUE TITLE
Addon-interactions: panel does not reset on HMR

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#17570] opened 2022-02-24 14:07 UTC
**Describe the bug**

https://user-images.githubusercontent.com/1671563/155538826-11c3f626-713d-4bb0-a76b-1f2c5fd6d728.mp4

**To Reproduce**
1 - Open a story with interactions
2 - Click on Go to start to keep the RUNS status
3 - Make code changes
4 - HMR should rerun the interaction but it does not

**Comment by lonyele** [comment] 2022-03-08 01:40
Q1. After step 3, I got an error like these. This doesn't happen to you? 
<img width="692" alt="스크린샷 2022-03-08 오전 10 30 44" src="https://user-images.githubusercontent.com/15892571/157147983-01ea93df-a8ca-422c-90b3-357b0dc502e4.png">
<img width="692" alt="스크린샷 2022-03-08 오전 10 29 16" src="https://user-images.githubusercontent.com/15892571/157147991-95a4a81d-e0b3-47af-9c1d-fd424612272f.png">
 
 Q2. When you click the `!!!hello`'s file line(`VM2051 main.~~~.js:126`), can you see the updated code `console.log('!!!hello world')` at the `Source` tab?
 
 Q3. Can you reproduce when you move `console.log(~)` to before the await code? 
Since the interaction state goes to the start, `console.log('!!!hello world')` shouldn't be logged? From my local, I could get the updated log if I move before any await
 
After I fix the above errors, I got to HMR working. But maybe, I'm the only one having these errors?

**Comment by shilman** [comment] 2022-05-20 11:03
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.4-alpha.0 containing PR #18284 that references this issue. Upgrade today to the `@prerelease` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Closed** 2022-06-21 15:40 UTC
Labels: bug, addon: interactions, linear
