### ISSUE TITLE
The documentation scrolls by itself

### ISSUE THREAD

**Issue by thany** [storybookjs/storybook#16273] opened 2021-10-07 13:49 UTC
**Describe the bug**
The documentation scrolls after... Something.

I cant quite put my finger on it, why or when this happens. But it's happened a few times now, that I'm just reading along on [the documentation on Controls](https://storybook.js.org/docs/react/essentials/controls) and while reading, the page scrolls away.

I have all forms of motion disabled (and I need to keep it that way) so I can't see what direction it's scrolling in. I just scroll up an down in frustration and confusion, trying to regain my bearings. And at "some point" later, it'll happen again.

**To Reproduce**
Go to https://storybook.js.org/docs/react/essentials/controls using the latest Firefox.

**System**
N/A

**Additional context**
Like I said, disable motion.

**Comment by jonniebigodes** [comment] 2021-10-07 20:28
Hi, @thany first and foremost thanks for reaching out to us with your issue. In order for this to be better triaged, could you provide some proof of the behavior? A video or something related. Also, can you check on your end if you don't have any addons/plugins that could affect the website rendering? I'm asking you this because I've actually checked with the latest Firefox release and I wasn't able to reproduce this both locally and the deployed version?

Have a great day!

Stay safe

**Comment by thany** [comment] 2021-10-14 21:55
I can record a video, sure, when I'm back at work. But will this really help you, or do you not believe me? I as a developer wouldn't know what I could do with a video, more than I could with an explanation. It just scrolls up after a while. What else can I say?..

I don't have addons/settings that interfere with scrolling behaviour, other than what I already mentioned. Of course I do have uBlock and Privacy Badger, but surely they don't cause a site to scroll. Surely the documentation site is not visually dependent on third party tracking pixels and whatnot.

**Comment by jonniebigodes** [comment] 2022-03-12 18:36
Closing this issue as I've been unable to replicate it. Tried in various environments and versions.

Hope you have a great weekend.

Stay safe

**Closed by jonniebigodes** 2022-03-12 18:36 UTC
Labels: documentation
