### ISSUE TITLE
[Feuture request] Custom control type

### ISSUE THREAD

**Issue by Gieted** [storybookjs/storybook#12362] opened 2020-09-02 21:17 UTC
#### Consider the following example:

We have a component that takes an object as its argument:
```jsx
function MyComponent(props) {
  const { text, ...restProps } = props.obj;
  doSomethingWithRestProps(restProps);
  
  return <div>{{ text }}</div>;
}
```
<br/>

Let's say that object that `MyComponent` takes as its argument has a lot of different properties:
```js
class VeryComplicatedObject {

  constructor(text) {
    this.text = text;
    this.one = 1;
    this.two = 2;
    this.three = 3;
    /* even more properties */
  }
}
```
<br/>

Now we want to create a story for `MyComponent`:
```jsx
export default {
  title: 'MyComponent',
  component: MyComponent
}

export Default = () => <MyComponent obj={new VeryComplicatedObject('my text')} />;
```
<br/>

Let's now see how our generated control looks like:
![obraz](https://user-images.githubusercontent.com/35242233/92028382-39c5d380-ed64-11ea-8f04-8bcd2f1c5246.png)

Although we really need to expose as control just a `text` property, we are exposing whole JSON representation of the object instead.

Only `text` property of this object affects how `MyComponent` looks and behaves, rest of them is used for something else, so we don't always need to edit the whole object. It would be convenient to be able to edit just this one `text` property and hide everything else from controls UI.

<br/>

#### Create "custom" control type.

You would use it like this:
```js
export default {
  title: 'MyComponent',
  component: MyComponent,
  argTypes: {
    obj: {
      control: {
        type: 'custom',
        subControls: {
          text: {
            type: 'text'
          }
        },
        resolve: ({text}) => new VeryComplicatedObject(text)
      }
    }
  }
}
```
Then it would be displayed in controls tab as:
![obraz](https://user-images.githubusercontent.com/35242233/92031156-70055200-ed68-11ea-829e-14500adb3d30.png)

<br/>

#### This solution would also allow to have multiple sub-controls, that resolve to a single argument:
```js
argTypes: {
  obj: {
    control: {
      type: 'custom',
      subControls: {
        text: {
          type: 'text'
        },
        todaysDate: {
          type: 'date'
        }
      },
      resolve: ({text, todaysDate}) => new VeryComplicatedObject(text + todaysDate)
    }
  }
}
```

Would be displayed as:
![obraz](https://user-images.githubusercontent.com/35242233/92034335-60d4d300-ed6d-11ea-800f-d8514e969394.png)

#### And also nesting:
```js
argTypes: {
  obj: {
    control: {
      type: 'custom',
      subControls: {
        text: {
          type: 'text'
        },
        sum: {
          type: 'custom',
          subControls: {
            numberOne: 'number',
            numberTwo: 'number'
          },
         resolve: ({numberOne, numberTwo}) => numberOne + numberTwo
        }
      },
      resolve: ({text, sum}) => new VeryComplicatedObject(text + sum)
    }
  }
}
```
![obraz](https://user-images.githubusercontent.com/35242233/92035148-9201d300-ed6e-11ea-8aaa-6d24637124d5.png)

#### This should also work not only for objects, but also for any argument type:
```js
export default {
  title: 'MyComponent',
  component: MyComponent,
  argTypes: {
    array: {
      control: {
        type: 'custom',
        subControls: {
          one: 'text',
          two: 'text',
          three: 'text'
        },
        resolve: ({one, two, three}) => [one, two, three]
      }
    }
  }
}
```

#### Type definitions:
```ts
type ControlType = 'array' | 'boolean' | 'number' | 'range' | 'object' | 'radio' | 'inline-radio' | 'check' | 'inline-check' | 'select' | 'multi-select' | 'text' | 'color' | 'date' | 'custom';

type SubControls = {[name: string]: Control};

type ResolveFn = (args: any) => any;

type Control = {type: ControlType, options?: string[], min?: number, max?: number, step?: number, subControls?: SubControls, resolve: ResolveFn} | ControlType;
```
#### This solution is great, because how flexible it is.

**Comment by shilman** [comment] 2020-09-02 23:38
@Gieted I agree this is a very interesting flexible solution, and it solves for both #12362 and #12078 

I'm closing this as duplicate to  #12362 and we can continue discussion there.

**Closed by shilman** 2020-09-02 23:38 UTC

**Comment by thomasaull** [comment] 2020-09-04 09:42
@shilman I think you closed this as a duplicate of itself 🙃

**Comment by shilman** [comment] 2020-09-05 01:04
My bad, fixed ☝️

**Comment by vladimircores** [comment] 2020-10-22 10:57
This is exactly what we need in our case where we feed our components with VOs wrapper around real data (JSON) with additional properties from other parts of the system of precomputed (so component won't know about the store or any data transformation logic):

So VO looks like this:

```
class OrganizationInfoVO {
  constructor(data, isDefaultOrganization, isCurrentUserOrganization) {
    this.data = data;
    this.isDefaultOrganization = isDefaultOrganization;
    this.isCurrentUserOrganization = isCurrentUserOrganization;
  }

  get id() { return this.data.id; }

  get name() { return this.data.name; }

  get country() { return this.data.country; }

  get picture() { return this.data.picture; }

  get count() { return this.data.count; }
}

export default OrganizationInfoVO;
```

And it would be great to have a way of changing properties or visualize them in storybook panels.

**Comment by vladimircores** [comment] 2020-10-22 11:02
I think having at least some kind of "update callback" from control which called before component re-render would be great.
