### ISSUE TITLE
[Bug]: Dependency resolution error when installing on Next.js 14 project

### ISSUE THREAD

**Issue by clearasvodka** [storybookjs/storybook#24605] opened 2023-10-28 20:46 UTC
### Describe the bug

Getting dependency resolution error while trying to install latest Storybook (7.5) to the latest Next.js project (14.0.0).

NPM error ERESOLVE - Dependency resolution error.

npm ERR! Found: next@14.0.0
npm ERR! node_modules/next
npm ERR!   next@"14.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^9.0.0 || ^10.0.0 || ^11.0.0 || ^12.0.0 || ^13.0.0" from @storybook/nextjs@7.5.1
npm ERR! node_modules/@storybook/nextjs
npm ERR!   dev @storybook/nextjs@"7.5.1" from the root project

### To Reproduce

1. Create Next.js 14 app (npx create-next-app@latest)
2. Try to install latest storybook 7.5 (npx storybook@latest init)

### System

```bash
System:
    OS: Windows 10 10.0.22621
    CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700HX
  Binaries:
    Node: 20.4.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.0 - C:\Program Files\nodejs\npm.CMD <----- active
  Browsers:
    Edge: Chromium (118.0.2088.69)
```

**Comment by valentinpalkovic** [comment] 2023-10-28 21:01
Duplicate of https://github.com/storybookjs/storybook/issues/24589

The fix will be released soon!

**Closed by valentinpalkovic** 2023-10-28 21:01 UTC
Labels: bug, duplicate, needs triage
