### ISSUE TITLE
[Bug]: stories glob does not work if project directory has parentheses

### ISSUE THREAD

**Issue by azhang** [storybookjs/storybook#28404] opened 2024-07-01 09:31 UTC
### Describe the bug

When running Storybook in a repo that has parens in the dir name, it is unable to install correct and unable to file story files.

```
WARN No story files found for the specified pattern: stories/**/*.mdx
WARN No story files found for the specified pattern: stories/**/*.stories.@(js|jsx|mjs|ts|tsx)
```

### Reproduction link

none

### Reproduction steps

Simplest reproduction is new next.js (all default settings), then installing storybook.
```
npx create-next-app@latest
npx storybook@latest init # This gets stuck with above error
npm run storybook # this shows errors with above error.
```

As soon as I remove parens from the dirname, it all works

### System

```bash
System:
    OS: macOS 14.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.2 - /usr/local/bin/node
    npm: 10.2.4 - /usr/local/bin/npm <----- active
    pnpm: 8.10.0 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 17.5
  npmPackages:
    @storybook/addon-essentials: ^8.1.11 => 8.1.11 
    @storybook/addon-interactions: ^8.1.11 => 8.1.11 
    @storybook/addon-links: ^8.1.11 => 8.1.11 
    @storybook/addon-onboarding: ^8.1.11 => 8.1.11 
    @storybook/blocks: ^8.1.11 => 8.1.11 
    @storybook/nextjs: ^8.1.11 => 8.1.11 
    @storybook/react: ^8.1.11 => 8.1.11 
    @storybook/test: ^8.1.11 => 8.1.11 
    eslint-plugin-storybook: ^0.8.0 => 0.8.0 
    storybook: ^8.1.11 => 8.1.11
```

**Comment by vanessayuenn** [comment] 2024-07-10 14:33
Hi, thanks for reporting this. do you have a reproduction repo you can share? If not, can you please create one via [storybook.new](https://new-storybook.netlify.app/)? We prioritize bug reports that have reproduction. Thank you! 🙏

**Comment by vanessayuenn** [comment] 2024-07-10 14:35
Actually, I believe this is a dupe of #25114.

**Closed by vanessayuenn** 2024-07-10 14:35 UTC
Labels: bug
