### ISSUE TITLE
Storybook (webpack 5) breaks images inline loaders

### ISSUE THREAD

**Issue by artaommahe** [storybookjs/storybook#15438] opened 2021-06-30 13:53 UTC
**Describe the bug**
Requiring an image (png/svg) with inline loaders provides wrong output that ignores these loaders.

```ts
testImage = require('!file-loader!./images/test-image.png').default;
testIcon = require('!html-loader!image-webpack-loader!./images/test-icon.svg');
```

**To Reproduce**

https://github.com/artaommahe/-storybook-webpack5-inline-loaders

* yarn install
* yarn storybook
* see wrong images urls and content in AppComponent's template (testImage's require here contains similar path as testIcon)

```html
image:

icon: "static/media/src/app/images/test-icon..svg"
```

* yarn start (to run angular dev server)
* see proper images urls and content in AppComponent's template

```html
image: "747f39b8dc75b31017d31bca80ccaf2e.png"

icon: { "default": "<svg ...</svg>" }
```

Same issue with `require.context` (uncomment it in AppComponent's OnInit method and comment out `require`s)

**System**

```
Environment Info:

  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 91.0.4472.124
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.59)
  npmPackages:
    @storybook/addon-actions: ^6.3.2 => 6.3.2
    @storybook/addon-essentials: ^6.3.2 => 6.3.2
    @storybook/addon-links: ^6.3.2 => 6.3.2
    @storybook/angular: ^6.3.2 => 6.3.2
    @storybook/builder-webpack5: ^6.3.2 => 6.3.2
    @storybook/manager-webpack5: ^6.3.2 => 6.3.2
```

**Additional context**
Worked fine with storybook 6.2.9

**Comment by bebraw** [comment] 2021-06-30 15:13
Starting from webpack 5, it's recommended to **not** use the inline syntax and use asset modules instead. See [here](https://webpack.js.org/guides/asset-modules/#replacing-inline-loader-syntax). I've also [written about the topic](https://survivejs.com/webpack/loading/images/) if you want to learn more.

To illustrate the usage against your project, I set up configuration as follows:

```js
const { merge } = require("webpack-merge");

module.exports = {
  stories: ["../src/**/*.stories.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
  addons: ["@storybook/addon-links", "@storybook/addon-essentials"],
  core: {
    builder: "webpack5",
  },
  webpackFinal: async (config) =>
    merge(config, {
      module: {
        rules: [
          {
            resourceQuery: /asset/,
            type: "asset",
          },
          {
            test: /\.svg$/,
            type: "asset",
            use: ["html-loader", "image-webpack-loader"],
          },
        ],
      },
    }),
};
```

I set up two examples. The first one lets you apply asset type based on `?asset` and the second one is matching automatically. In this project I might go with the second form for all unless you prefer more control in which the first type is more handy.

This relies on my tool [webpack-merge](https://www.npmjs.com/package/webpack-merge) for composition to keep things simple.

Then on app side I changed things as follows:

```js
  testImage = require('./images/test-image.png?asset');
  testIcon = require('./images/test-icon.svg');
```

This emits below:

<img width="730" alt="Screen Shot 2021-06-30 at 18 11 40" src="https://user-images.githubusercontent.com/166921/123986027-9fa7d980-d9ce-11eb-9866-165a618e4021.png">

I think there's some HTML work possibly missing but the output looks ok to me.

**Comment by artaommahe** [comment] 2021-06-30 15:23
@bebraw using custom webpack configuration looks much more complex than inline-loaders. We should use it with each storybook instance (monorepo with dozen projects and hundreds of libs) and also provide such custom configuration for each angular app to support such requires. I doesn't really look as better approach.

Also all these stuff works fine with webpack 5 (in angular app) and looks like something particular in storybook's configuration breaks inline loaders.

**Comment by bebraw** [comment] 2021-06-30 15:25
> Also all these stuff works fine with webpack 5 (in angular app) and looks like something particular in storybook's configuration breaks inline loaders.

Ah, I see. So it would be something to fix in the base config then.

Inline config will most likely disappear in webpack 6 so then you would be forced to change the usage to the new style, though.

**Comment by artaommahe** [comment] 2021-06-30 15:32
> Inline config will most likely disappear in webpack 6 so then you would be forced to change the usage to the new style, though.

hope angular/cli will provide something default for these cases at that time to avoid custom webpack configs usage...

**Comment by bebraw** [comment] 2021-06-30 16:01
Just to clarify, did you use webpack 4 or 5 with Storybook 6.2.9?

**Comment by artaommahe** [comment] 2021-06-30 16:57
Webpack 4

**Comment by bebraw** [comment] 2021-06-30 17:08
Does it work against webpack 4 in 6.3.2 or webpack 5 in 6.2.9?

**Comment by artaommahe** [comment] 2021-07-01 11:52
> webpack 5 in 6.2.9

dunno how to run storybook 6.2.9 with webpack5. There is no such versions for `@storybook/manager-webpack5`

> webpack 4 in 6.3.2

works fine, as expected
(after downgrading angular to 11.2.0 and html/image-webpack loaders to work with webpack 4)

**Comment by bebraw** [comment] 2021-07-01 12:00
> works fine, as expected
> (after downgrading angular to 11.2.0 and html/image-webpack loaders to work with webpack 4)

Ok, it sounds like there's something in base configuration that breaks between the two in 6.3.2 then. That's good info for debugging further.

**Comment by bebraw** [comment] 2021-07-01 12:23
I think I understand what’s going on now. There's:

```js
      {
        test: /\.(svg|ico|jpg|jpeg|png|apng|gif|eot|otf|webp|ttf|woff|woff2|cur|ani|pdf)(\?.*)?$/,
        type: 'asset/resource',
        generator: { filename: 'static/media/[path][name].[ext]' }
      }
```

In Storybook's configuration. With this config it supports image assets out of the box. Based on this, for me the simplest fix is to remove the inline loaders like this:

```
  testImage = require('./images/test-image.png');
  testIcon = require('./images/test-icon.svg');
```

In this case, it will return as asset path for both.

Can you try this and report if this is enough for a solution in your use case?

---

To explain the problem, what happened earlier is that it executed the loaders before deferring to Storybook's default behavior and that was breaking it.

At least until webpack 4, the tool supported `!!` syntax (i.e. `!!file-loader!./demo.png`) that **should** override any default configuration completely but in my test this didn't work for an unknown reason.

**Comment by artaommahe** [comment] 2021-07-01 12:31
> Can you try this and report if this is enough for a solution in your use case?

you cant do this cause angular-cli does not have such configurations and `require('./images/test-image.png')` will not work there.
Also this is a separate issue that storybook does not use angular-cli's configuration to build components but something local https://github.com/storybookjs/storybook/issues/11610. This produces wrong behavior due to different environment (webpack configuration) for the same code between framework (angular-cli or any other) and storybook.

> `!!` syntax

yep, it does not work..

**Comment by bebraw** [comment] 2021-07-01 12:36
> you cant do this cause angular-cli does not have such configurations and require('./images/test-image.png') will not work there.
> This is a separate issue that storybook does not use angular-cli's configuration to build components but something local #11610. This produces wrong behavior due to different environment (webpack configuration) for the same code between framework (angular-cli or any other) and storybook.

Ok, it's possible Storybook's default configuration is wrong then considering this use case. Maybe it cannot support images out of the box to be compliant? I don't understand Angular enough to say what's the right approach there.

Based on https://webpack.js.org/concepts/loaders/#inline, both `!!` and `-!` should still work but based on above (Angular compatibility), it doesn't sound like the right way even if it did work. I wonder if we hit some issue in webpack itself.

**Comment by artaommahe** [comment] 2021-07-01 12:43
> Maybe it cannot support images out of the box to be compliant? I don't understand Angular enough to say what's the right approach there

imho the righе approach is to reuse framework's webpack configuration without any changes or you always will face some divergences how code works in storybook and in plain framework

> I wonder if we hit some issue in webpack itself.

already trying to reproduce

**Comment by bebraw** [comment] 2021-07-01 12:48
> already trying to reproduce

Cool. The thing to prove is that `!` and `!!` work against webpack without Storybook. I imagine the next step is to strip almost everything from Storybook webpack config to a bare minimum. If vanilla webpack 5 works, then there's something in the configuration breaking the behavior for Storybook.

**Comment by artaommahe** [comment] 2021-07-01 12:54
omg.. it's an issue with webpack

https://github.com/artaommahe/webpack-5-inline-loaders

code https://github.com/artaommahe/webpack-5-inline-loaders/blob/main/src/index.js
webpack config https://github.com/artaommahe/webpack-5-inline-loaders/blob/main/webpack.config.js

- git clone
- yarn install
- yarn webpack
- open `dist/index.html`
- see undefined for images and this in console
  ```
  > testImage file:///D:/projects/tests/webpack-5-inline-loaders/dist/static/media/src/images/test-image..png
  > testIcon file:///D:/projects/tests/webpack-5-inline-loaders/dist/static/media/src/images/test-icon..svg
  ```

**Comment by bebraw** [comment] 2021-07-01 12:59
> omg.. it's an issue with webpack

Ok, thanks for confirming! If and when you find a related issue, please link here so we can track it. There's not much we can do in Storybook itself as it sounds like a regression in webpack itself based on your simple demonstration.

**Comment by artaommahe** [comment] 2021-07-01 13:02
https://github.com/webpack/webpack/issues/13683

**Comment by shilman** [comment] 2021-07-02 09:01
Doesn't seem like this is a webpack issue per se, but rather how the loaders are getting called. Can we figure out a proper solution here?

**Comment by bebraw** [comment] 2021-07-02 09:08
Would it make sense to allow the users to disable the default file loading behavior? Removing that entirely would break behavior for anyone relying on it.

Based on https://github.com/webpack/webpack/issues/13683 it's a wontfix on webpack side.

I know it's inconvenient for anyone relying on the inline behavior but I don't see any other way around it since it doesn't seem to be fixable on webpack side.

**Comment by artaommahe** [comment] 2021-07-02 09:47
Looks like assets modules always override inline loaders and it's by design.
Imho the issue here is that storybook adds additional loaders to default angular-cli's config and so changes some behavior. This wasn't a big issue until webpack 5 and assets modules/inline loaders conflict cause earlier you could just use inline loaders and they override storybook's rules. Mb storybook can somehow separate manager/iframe and real app's components builds and use clean angular-cli's config for the latter?

**Comment by shilman** [comment] 2021-07-02 09:59
> storybook adds additional loaders to default angular-cli's config 

AFAIK storybook doesn't use angular-cli's config at all

**Comment by artaommahe** [comment] 2021-07-02 10:01
it would be strange if storybook does not use some frameworks default webpack configuration. Rules difference can lead to a lot of issues with running same code with framework's cli and with storybook

**Comment by shilman** [comment] 2021-07-02 10:03
@artaommahe please try maintaining a tool that's used by tens of thousands of teams--each with their own peculiar frameworks and configurations--then tell me how strange it is :trollface:

**Comment by artaommahe** [comment] 2021-07-02 10:21
i understand the complexity of all this stuff, im just talking about ideal solution/changes direction )

**Comment by shilman** [comment] 2021-07-02 11:31
@artaommahe just venting a bit, thanks for being patient with us on this! 😄

**Comment by artaommahe** [comment] 2021-07-07 13:32
btw current workaround is to remove images loader in webpack config customisation
```ts
config.module.rules = config.module.rules.filter(rule => !rule.test || !rule.test.source.includes('png'));
```

**Closed** 2023-01-17 22:49 UTC
Labels: bug, help wanted, has workaround, webpack5, small
