### ISSUE TITLE
[Bug]: Getting warning from @storybook/components

### ISSUE THREAD

**Issue by nikhilsnayak** [storybookjs/storybook#25050] opened 2023-11-30 04:20 UTC
### Describe the bug

I am using next.js 14.0.1 and storybook 7.6.1 and getting these warnings on the console.

WARN export 'withReset' (imported as 'withReset') was not found in '@storybook/components' (possible exports: A, ActionBar, AddonPanel, ArgsTable, ArgsTableError, Badge, Bar, Blockquote, BooleanControl, Button, Code, ColorControl, ColorItem, ColorPalette, DL, DateControl, Description, Div, DocsContent, DocsPageWrapper, DocsWrapper, DocumentWrapper, FilesControl, FlexBar, Form, H1, H2, H3, H4, H5, H6, HR, IFrame, IconButton, IconGallery, IconItem, Icons, Img, LI, Link, Loader, NoControlsWarning, NumberControl, OL, ObjectControl, OptionsControl, P, Placeholder, Pre, Preview, PreviewSkeleton, RangeControl, ScrollArea, Separator, Source, SourceError, Spaced, Span, Story, StoryError, StorySkeleton, StorybookIcon, StorybookLogo, StyledSyntaxHighlighter, Subtitle, Symbols, SyntaxHighlighter, TT, TabBar, TabButton, TabWrapper, TabbedArgsTable, Table, TableWrapper, Tabs, TabsState, TextControl, Title, TooltipLinkList, TooltipMessage, TooltipNote, Typeset, UL, WithTooltip, WithTooltipPure, Zoom, argsTableLoadingData, components, format, formatDate, formatTime, getStoryHref, interleaveSeparators, nameSpaceClassNames, parse, parseDate, parseTime, resetComponents)

WARN export 'withReset' (imported as 'withReset') was not found in '@storybook/components' (possible exports: A, ActionBar, AddonPanel, ArgsTable, ArgsTableError, Badge, Bar, Blockquote, BooleanControl, Button, Code, ColorControl, ColorItem, ColorPalette, DL, DateControl, Description, Div, DocsContent, DocsPageWrapper, DocsWrapper, DocumentWrapper, FilesControl, FlexBar, Form, H1, H2, H3, H4, H5, H6, HR, IFrame, IconButton, IconGallery, IconItem, Icons, Img, LI, Link, Loader, NoControlsWarning, NumberControl, OL, ObjectControl, OptionsControl, P, Placeholder, Pre, Preview, PreviewSkeleton, RangeControl, ScrollArea, Separator, Source, SourceError, Spaced, Span, Story, StoryError, StorySkeleton, StorybookIcon, StorybookLogo, StyledSyntaxHighlighter, Subtitle, Symbols, SyntaxHighlighter, TT, TabBar, TabButton, TabWrapper, TabbedArgsTable, Table, TableWrapper, Tabs, TabsState, TextControl, Title, TooltipLinkList, TooltipMessage, TooltipNote, Typeset, UL, WithTooltip, WithTooltipPure, Zoom, argsTableLoadingData, components, format, formatDate, formatTime, getStoryHref, interleaveSeparators, nameSpaceClassNames, parse, parseDate, parseTime, resetComponents)

WARN export 'withReset' (imported as 'withReset') was not found in '@storybook/components' (possible exports: A, ActionBar, AddonPanel, ArgsTable, ArgsTableError, Badge, Bar, Blockquote, BooleanControl, Button, Code, ColorControl, ColorItem, ColorPalette, DL, DateControl, Description, Div, DocsContent, DocsPageWrapper, DocsWrapper, DocumentWrapper, FilesControl, FlexBar, Form, H1, H2, H3, H4, H5, H6, HR, IFrame, IconButton, IconGallery, IconItem, Icons, Img, LI, Link, Loader, NoControlsWarning, NumberControl, OL, ObjectControl, OptionsControl, P, Placeholder, Pre, Preview, PreviewSkeleton, RangeControl, ScrollArea, Separator, Source, SourceError, Spaced, Span, Story, StoryError, StorySkeleton, StorybookIcon, StorybookLogo, StyledSyntaxHighlighter, Subtitle, Symbols, SyntaxHighlighter, TT, TabBar, TabButton, TabWrapper, TabbedArgsTable, Table, TableWrapper, Tabs, TabsState, TextControl, Title, TooltipLinkList, TooltipMessage, TooltipNote, Typeset, UL, WithTooltip, WithTooltipPure, Zoom, argsTableLoadingData, components, format, formatDate, formatTime, getStoryHref, interleaveSeparators, nameSpaceClassNames, parse, parseDate, parseTime, resetComponents)

WARN export 'IconButtonSkeleton' (imported as 'IconButtonSkeleton') was not found in '@storybook/components' (possible exports: A, ActionBar, AddonPanel, ArgsTable, ArgsTableError, Badge, Bar, Blockquote, BooleanControl, Button, Code, ColorControl, ColorItem, ColorPalette, DL, DateControl, Description, Div, DocsContent, DocsPageWrapper, DocsWrapper, DocumentWrapper, FilesControl, FlexBar, Form, H1, H2, H3, H4, H5, H6, HR, IFrame, IconButton, IconGallery, IconItem, Icons, Img, LI, Link, Loader, NoControlsWarning, NumberControl, OL, ObjectControl, OptionsControl, P, Placeholder, Pre, Preview, PreviewSkeleton, RangeControl, ScrollArea, Separator, Source, SourceError, Spaced, Span, Story, StoryError, StorySkeleton, StorybookIcon, StorybookLogo, StyledSyntaxHighlighter, Subtitle, Symbols, SyntaxHighlighter, TT, TabBar, TabButton, TabWrapper, TabbedArgsTable, Table, TableWrapper, Tabs, TabsState, TextControl, Title, TooltipLinkList, TooltipMessage, TooltipNote, Typeset, UL, WithTooltip, WithTooltipPure, Zoom, argsTableLoadingData, components, format, formatDate, formatTime, getStoryHref, interleaveSeparators, nameSpaceClassNames, parse, parseDate, parseTime, resetComponents)

WARN export 'ErrorFormatter' (imported as 'ErrorFormatter') was not found in '@storybook/components' (possible exports: A, ActionBar, AddonPanel, ArgsTable, ArgsTableError, Badge, Bar, Blockquote, BooleanControl, Button, Code, ColorControl, ColorItem, ColorPalette, DL, DateControl, Description, Div, DocsContent, DocsPageWrapper, DocsWrapper, DocumentWrapper, FilesControl, FlexBar, Form, H1, H2, H3, H4, H5, H6, HR, IFrame, IconButton, IconGallery, IconItem, Icons, Img, LI, Link, Loader, NoControlsWarning, NumberControl, OL, ObjectControl, OptionsControl, P, Placeholder, Pre, Preview, PreviewSkeleton, RangeControl, ScrollArea, Separator, Source, SourceError, Spaced, Span, Story, StoryError, StorySkeleton, StorybookIcon, StorybookLogo, StyledSyntaxHighlighter, Subtitle, Symbols, SyntaxHighlighter, TT, TabBar, TabButton, TabWrapper, TabbedArgsTable, Table, TableWrapper, Tabs, TabsState, TextControl, Title, TooltipLinkList, TooltipMessage, TooltipNote, Typeset, UL, WithTooltip, WithTooltipPure, Zoom, argsTableLoadingData, components, format, formatDate, formatTime, getStoryHref, interleaveSeparators, nameSpaceClassNames, parse, parseDate, parseTime, resetComponents)

WARN export 'codeCommon' (imported as 'codeCommon') was not found in '@storybook/components' (possible exports: A, ActionBar, AddonPanel, ArgsTable, ArgsTableError, Badge, Bar, Blockquote, BooleanControl, Button, Code, ColorControl, ColorItem, ColorPalette, DL, DateControl, Description, Div, DocsContent, DocsPageWrapper, DocsWrapper, DocumentWrapper, FilesControl, FlexBar, Form, H1, H2, H3, H4, H5, H6, HR, IFrame, IconButton, IconGallery, IconItem, Icons, Img, LI, Link, Loader, NoControlsWarning, NumberControl, OL, ObjectControl, OptionsControl, P, Placeholder, Pre, Preview, PreviewSkeleton, RangeControl, ScrollArea, Separator, Source, SourceError, Spaced, Span, Story, StoryError, StorySkeleton, StorybookIcon, StorybookLogo, StyledSyntaxHighlighter, Subtitle, Symbols, SyntaxHighlighter, TT, TabBar, TabButton, TabWrapper, TabbedArgsTable, Table, TableWrapper, Tabs, TabsState, TextControl, Title, TooltipLinkList, TooltipMessage, TooltipNote, Typeset, UL, WithTooltip, WithTooltipPure, Zoom, argsTableLoadingData, components, format, formatDate, formatTime, getStoryHref, interleaveSeparators, nameSpaceClassNames, parse, parseDate, parseTime, resetComponents)

WARN export 'codeCommon' (imported as 'codeCommon') was not found in '@storybook/components' (possible exports: A, ActionBar, AddonPanel, ArgsTable, ArgsTableError, Badge, Bar, Blockquote, BooleanControl, Button, Code, ColorControl, ColorItem, ColorPalette, DL, DateControl, Description, Div, DocsContent, DocsPageWrapper, DocsWrapper, DocumentWrapper, FilesControl, FlexBar, Form, H1, H2, H3, H4, H5, H6, HR, IFrame, IconButton, IconGallery, IconItem, Icons, Img, LI, Link, Loader, NoControlsWarning, NumberControl, OL, ObjectControl, OptionsControl, P, Placeholder, Pre, Preview, PreviewSkeleton, RangeControl, ScrollArea, Separator, Source, SourceError, Spaced, Span, Story, StoryError, StorySkeleton, StorybookIcon, StorybookLogo, StyledSyntaxHighlighter, Subtitle, Symbols, SyntaxHighlighter, TT, TabBar, TabButton, TabWrapper, TabbedArgsTable, Table, TableWrapper, Tabs, TabsState, TextControl, Title, TooltipLinkList, TooltipMessage, TooltipNote, Typeset, UL, WithTooltip, WithTooltipPure, Zoom, argsTableLoadingData, components, format, formatDate, formatTime, getStoryHref, interleaveSeparators, nameSpaceClassNames, parse, parseDate, parseTime, resetComponents)

WARN export 'codeCommon' (imported as 'codeCommon') was not found in '@storybook/components' (possible exports: A, ActionBar, AddonPanel, ArgsTable, ArgsTableError, Badge, Bar, Blockquote, BooleanControl, Button, Code, ColorControl, ColorItem, ColorPalette, DL, DateControl, Description, Div, DocsContent, DocsPageWrapper, DocsWrapper, DocumentWrapper, FilesControl, FlexBar, Form, H1, H2, H3, H4, H5, H6, HR, IFrame, IconButton, IconGallery, IconItem, Icons, Img, LI, Link, Loader, NoControlsWarning, NumberControl, OL, ObjectControl, OptionsControl, P, Placeholder, Pre, Preview, PreviewSkeleton, RangeControl, ScrollArea, Separator, Source, SourceError, Spaced, Span, Story, StoryError, StorySkeleton, StorybookIcon, StorybookLogo, StyledSyntaxHighlighter, Subtitle, Symbols, SyntaxHighlighter, TT, TabBar, TabButton, TabWrapper, TabbedArgsTable, Table, TableWrapper, Tabs, TabsState, TextControl, Title, TooltipLinkList, TooltipMessage, TooltipNote, Typeset, UL, WithTooltip, WithTooltipPure, Zoom, argsTableLoadingData, components, format, formatDate, formatTime, getStoryHref, interleaveSeparators, nameSpaceClassNames, parse, parseDate, parseTime, resetComponents)

WARN export 'codeCommon' (imported as 'codeCommon') was not found in '@storybook/components' (possible exports: A, ActionBar, AddonPanel, ArgsTable, ArgsTableError, Badge, Bar, Blockquote, BooleanControl, Button, Code, ColorControl, ColorItem, ColorPalette, DL, DateControl, Description, Div, DocsContent, DocsPageWrapper, DocsWrapper, DocumentWrapper, FilesControl, FlexBar, Form, H1, H2, H3, H4, H5, H6, HR, IFrame, IconButton, IconGallery, IconItem, Icons, Img, LI, Link, Loader, NoControlsWarning, NumberControl, OL, ObjectControl, OptionsControl, P, Placeholder, Pre, Preview, PreviewSkeleton, RangeControl, ScrollArea, Separator, Source, SourceError, Spaced, Span, Story, StoryError, StorySkeleton, StorybookIcon, StorybookLogo, StyledSyntaxHighlighter, Subtitle, Symbols, SyntaxHighlighter, TT, TabBar, TabButton, TabWrapper, TabbedArgsTable, Table, TableWrapper, Tabs, TabsState, TextControl, Title, TooltipLinkList, TooltipMessage, TooltipNote, Typeset, UL, WithTooltip, WithTooltipPure, Zoom, argsTableLoadingData, components, format, formatDate, formatTime, getStoryHref, interleaveSeparators, nameSpaceClassNames, parse, parseDate, parseTime, resetComponents)

WARN export 'ResetWrapper' (imported as 'ResetWrapper') was not found in '@storybook/components' (possible exports: A, ActionBar, AddonPanel, ArgsTable, ArgsTableError, Badge, Bar, Blockquote, BooleanControl, Button, Code, ColorControl, ColorItem, ColorPalette, DL, DateControl, Description, Div, DocsContent, DocsPageWrapper, DocsWrapper, DocumentWrapper, FilesControl, FlexBar, Form, H1, H2, H3, H4, H5, H6, HR, IFrame, IconButton, IconGallery, IconItem, Icons, Img, LI, Link, Loader, NoControlsWarning, NumberControl, OL, ObjectControl, OptionsControl, P, Placeholder, Pre, Preview, PreviewSkeleton, RangeControl, ScrollArea, Separator, Source, SourceError, Spaced, Span, Story, StoryError, StorySkeleton, StorybookIcon, StorybookLogo, StyledSyntaxHighlighter, Subtitle, Symbols, SyntaxHighlighter, TT, TabBar, TabButton, TabWrapper, TabbedArgsTable, Table, TableWrapper, Tabs, TabsState, TextControl, Title, TooltipLinkList, TooltipMessage, TooltipNote, Typeset, UL, WithTooltip, WithTooltipPure, Zoom, argsTableLoadingData, components, format, formatDate, formatTime, getStoryHref, interleaveSeparators, nameSpaceClassNames, parse, parseDate, parseTime, resetComponents)

WARN export 'withReset' (imported as 'withReset') was not found in '@storybook/components' (possible exports: A, ActionBar, AddonPanel, ArgsTable, ArgsTableError, Badge, Bar, Blockquote, BooleanControl, Button, Code, ColorControl, ColorItem, ColorPalette, DL, DateControl, Description, Div, DocsContent, DocsPageWrapper, DocsWrapper, DocumentWrapper, FilesControl, FlexBar, Form, H1, H2, H3, H4, H5, H6, HR, IFrame, IconButton, IconGallery, IconItem, Icons, Img, LI, Link, Loader, NoControlsWarning, NumberControl, OL, ObjectControl, OptionsControl, P, Placeholder, Pre, Preview, PreviewSkeleton, RangeControl, ScrollArea, Separator, Source, SourceError, Spaced, Span, Story, StoryError, StorySkeleton, StorybookIcon, StorybookLogo, StyledSyntaxHighlighter, Subtitle, Symbols, SyntaxHighlighter, TT, TabBar, TabButton, TabWrapper, TabbedArgsTable, Table, TableWrapper, Tabs, TabsState, TextControl, Title, TooltipLinkList, TooltipMessage, TooltipNote, Typeset, UL, WithTooltip, WithTooltipPure, Zoom, argsTableLoadingData, components, format, formatDate, formatTime, getStoryHref, interleaveSeparators, nameSpaceClassNames, parse, parseDate, parseTime, resetComponents)

WARN export 'ResetWrapper' (imported as 'ResetWrapper') was not found in '@storybook/components' (possible exports: A, ActionBar, AddonPanel, ArgsTable, ArgsTableError, Badge, Bar, Blockquote, BooleanControl, Button, Code, ColorControl, ColorItem, ColorPalette, DL, DateControl, Description, Div, DocsContent, DocsPageWrapper, DocsWrapper, DocumentWrapper, FilesControl, FlexBar, Form, H1, H2, H3, H4, H5, H6, HR, IFrame, IconButton, IconGallery, IconItem, Icons, Img, LI, Link, Loader, NoControlsWarning, NumberControl, OL, ObjectControl, OptionsControl, P, Placeholder, Pre, Preview, PreviewSkeleton, RangeControl, ScrollArea, Separator, Source, SourceError, Spaced, Span, Story, StoryError, StorySkeleton, StorybookIcon, StorybookLogo, StyledSyntaxHighlighter, Subtitle, Symbols, SyntaxHighlighter, TT, TabBar, TabButton, TabWrapper, TabbedArgsTable, Table, TableWrapper, Tabs, TabsState, TextControl, Title, TooltipLinkList, TooltipMessage, TooltipNote, Typeset, UL, WithTooltip, WithTooltipPure, Zoom, argsTableLoadingData, components, format, formatDate, formatTime, getStoryHref, interleaveSeparators, nameSpaceClassNames, parse, parseDate, parseTime, resetComponents)

WARN export 'ResetWrapper' (imported as 'ResetWrapper') was not found in '@storybook/components' (possible exports: A, ActionBar, AddonPanel, ArgsTable, ArgsTableError, Badge, Bar, Blockquote, BooleanControl, Button, Code, ColorControl, ColorItem, ColorPalette, DL, DateControl, Description, Div, DocsContent, DocsPageWrapper, DocsWrapper, DocumentWrapper, FilesControl, FlexBar, Form, H1, H2, H3, H4, H5, H6, HR, IFrame, IconButton, IconGallery, IconItem, Icons, Img, LI, Link, Loader, NoControlsWarning, NumberControl, OL, ObjectControl, OptionsControl, P, Placeholder, Pre, Preview, PreviewSkeleton, RangeControl, ScrollArea, Separator, Source, SourceError, Spaced, Span, Story, StoryError, StorySkeleton, StorybookIcon, StorybookLogo, StyledSyntaxHighlighter, Subtitle, Symbols, SyntaxHighlighter, TT, TabBar, TabButton, TabWrapper, TabbedArgsTable, Table, TableWrapper, Tabs, TabsState, TextControl, Title, TooltipLinkList, TooltipMessage, TooltipNote, Typeset, UL, WithTooltip, WithTooltipPure, Zoom, argsTableLoadingData, components, format, formatDate, formatTime, getStoryHref, interleaveSeparators, nameSpaceClassNames, parse, parseDate, parseTime, resetComponents)

### To Reproduce

https://github.com/nikhilsnayak3473/nextjs-storybook-bug

### System

```bash
Storybook Environment Info:

  System:
    OS: Windows 11 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.11.0 - ~\AppData\Local\pnpm\pnpm.CMD <----- active
  Browsers:
    Edge: Chromium (119.0.2151.93)
```

**Comment by valentinpalkovic** [comment] 2023-11-30 12:27
I can't reproduce the issue on Mac. Seems to be Windows related

**Comment by apetta** [comment] 2023-12-11 17:25
Getting this on mac m1 after upgrading storybook from 7.5.1 to 7.6.4

**Comment by apetta** [comment] 2023-12-13 17:38
I traced this down to a mismatch in `@storybook/components` versions. For me, this was stemming from `@storybook/addon-essentials`. I was able to resolve it by explicitly adding `"@storybook/components": "7.6.4"` to my project dependencies in order to match everything up.

**Comment by shilman** [comment] 2023-12-24 03:48
Closing this as a version mismatch issue. LMK if that's not the case and we can re-open!

**Closed by shilman** 2023-12-24 03:48 UTC
Labels: bug, has workaround, windows

**Comment by kevinprakasa** [comment] 2025-02-23 16:58
In my case, setting the latest version installed of the @storybook/components in `resolutions` package.json field does work.
