### ISSUE TITLE
withActions: CustomEvent detail missing

### ISSUE THREAD

**Issue by rdm** [storybookjs/storybook#8544] opened 2019-10-23 22:51 UTC
**Is your feature request related to a problem? Please describe.**
I had originally filed this as a bug report, but belatedly decided that it's technically a feature request. 

Basically, though, when I am building a WebComponent which generates a CustomEvent, I want to be sure that the CustomEvent is being generated properly.

**Describe the solution you'd like**
withActions (from @storybook/addon-actions) should include in the log the detail property of an event it receives if the event is a CustomEvent (or there should be some other documented way for stories to listen for a CustomEvent and see its detail property in the log).

**Describe alternatives you've considered**
(using html from lit element and render from lit html), I render:
`<button type="button" @click="${this.publishtest}">publish</button>`

And, I add a publish method on that class:
```
publishtest() {
  this.dispatchEvent(new CustomEvent('pubexample', {detail: {a: 1, b: 2}, bubbles: true}));
}
```

And, in my stories I include:
`   .addDecorator(withActions('pubexample'))`

I click the button, and something representing my example event shows up in the console log, but the detail property appears to be missing (or at least is not accessible from the console.log in chrome).

**Are you able to assist bring the feature to reality?**
I don't know - I'll try implementing this tomorrow and submit a pull request if I can make this work.

**Additional context**
Possibly relevant is that the logged message has a data property which has an args property which is an array of one element which is seems to be my CustomEvent but the only visible property of that item is {isTrusted: false}. Meanwhile, if I save that CustomEvent globally, and display it in the log, I see something completely different (with about 16 properties, but Object.keys() on that object only gets me `isTrusted` and `_constructor-name_` -- so a part of the issue here is simply that chrome doesn't let me see inherited properties in the context of the logged message, perhaps because the CustomEvent is deeply nested in the message).

**Comment by rdm** [comment] 2019-10-25 14:12
The @click mechanism is slightly different from onClick -- see, for example https://lit-element.polymer-project.org/guide/events

[And, on the positive side, despite a sordid history of CustomEvent problems with detail, in this context detail is not being lost -- it's just not visible as it's logged here. (But I haven't come up with a better alternative for logging, yet, either.)]

**Comment by dmartinjs** [comment] 2020-01-09 18:08
I have also this issue, can you reopen ?

**Comment by rdm** [comment] 2020-01-30 23:47
Given the current state of things, this is likely to take much longer than 30 days to address.

**Comment by shilman** [comment] 2020-01-31 00:07
@rdm would you like to take a crack at it?

**Comment by rdm** [comment] 2020-01-31 17:12
@shilman there are still too many issues which I do not comprehend, here. I think I'd botch the job.

Still... maybe I should try -- a botched job might at least be a step in the right direction...

**Comment by shilman** [comment] 2020-03-23 05:21
cc @jonspalmer

**Comment by urish** [comment] 2020-03-29 15:37
Seems like this issue is coming from [react-inspector](https://github.com/storybookjs/react-inspector).

I managed to reproduce it there as follow:
1. Go to the [react-inspector playground](https://storybookjs.github.io/react-inspector/)
2. Open the devtools console and type `window.eval = () => new CustomEvent('test', {detail: 123})`
3. Type anything in the code editor on the left (doesn't matter what, as long as you change the value), and you will see that the inspector on the right shows an Object with a single `isTrusted` property, and no mention of the `details` property, similar to what happens in storybook:

![image](https://user-images.githubusercontent.com/892318/77853300-267a6f00-71ec-11ea-8533-0d9d95ed0abd.png)

At the same time, running `console.log(new CustomEvent('test', {detail: 123}))` in chrome devtools shows a bunch of properties, including `detail`:

![image](https://user-images.githubusercontent.com/892318/77853340-54f84a00-71ec-11ea-98dc-948707e790cb.png)

I hope that this is helpful!

**Comment by jeremiej-q** [comment] 2020-06-07 12:49
After doing a few tries, I discovered that almost all the "properties" of the CustomEvent are actually class getters, the only property is `isTrusted`.

It means, that if you try to duplicate or serialize a CustomEvent, you will only get the property `isTrusted` since class getters are not considered as properties.

Examples: 
- `Object.assign({}, new CustomEvent('test', {detail: 123})) // => { isTrusted: false }`
- `JSON.stringify(new CustomEvent('test', {detail: 123})) // => {"isTrusted":false}`

I assume that react-inspector is doing a serialization or a copy of the original event somewhere before to render it. Resulting in the loss of the other "properties". 

I managed to workaround that issue by adding a custom decorator to the addons-actions like this: 

```
// .storybook/helpers/actions.js
import { decorate } from '@storybook/addon-actions';

const eventProperties = [
  'bubbles',
  'cancelBubble',
  'cancelable',
  'composed',
  'currentTarget',
  'defaultPrevented',
  'detail',
  'eventPhase',
  'isTrusted',
  'path',
  'returnValue',
  'srcElement',
  'target',
  'timeStamp',
  'type',
];

const cloneEventObj = (eventObj, overrideObj = {}) => {
  class EventCloneFactory {
    constructor (override){
      for(const prop in override){
        this[prop] = override[prop];
      }

      for(const prop of eventProperties){
        this[prop] = eventObj[prop];
      }
    }
   }
   EventCloneFactory.prototype.constructor = eventObj.constructor;
   return new EventCloneFactory(overrideObj);
}

const uniqueId = (eventName) => `${eventName}-${(new Date()).getTime()}`;

export const customEvent = decorate([args => {
  const originalEvent = args[0];
  const ev = cloneEventObj(originalEvent, {
    id: uniqueId(originalEvent.type),
  });
  return [ev];
}]);
```

```
// story/test.stories.js
import { customEvent } from '../.storybook/helpers/actions';

export default {
  title: 'Test',
  decorators: [
      customEvent.withActions('test'),
  ],
};

...
```

There's probably a better way to do that, but at least it works 🤷‍♂️

**Comment by dmartinjs** [comment] 2020-06-15 08:11
thanks @jeremiej-q , it works very well 👏

**Comment by AGrabovajFitA** [comment] 2020-06-26 15:12
Here is a solution to this problem: https://stackoverflow.com/questions/13333683/javascript-customevent-detail-not-getting-passed

**Comment by dutscher** [comment] 2020-12-10 13:14
@jeremiej-q  
![image](https://user-images.githubusercontent.com/14682/101776938-fd87d900-3af1-11eb-9e7c-d12d9f9ef4d1.png)

but still the "isTrusted" Problem.

cheers

**Comment by dutscher** [comment] 2020-12-10 16:30
@shilman @ndelangen the problem in here is the communication between manager and preview:
https://github.com/storybookjs/storybook/blob/next/lib/channel-postmessage/src/index.ts#L77

look at the console screenshot:
![image](https://user-images.githubusercontent.com/14682/101792236-c40c9900-3b04-11eb-93e9-2e5fc2c1aff0.png)

and the result in the action console is:
![image](https://user-images.githubusercontent.com/14682/101792297-d4bd0f00-3b04-11eb-9608-30d28455510d.png)

the telejson package get the _constructor_name_ and JSON.stringify did the rest and only return "isTrusted"
https://github.com/storybookjs/telejson/blob/master/src/index.ts#L209
as you can see at @jeremiej-q posts.

i think we can reopen this issue!

**Comment by shilman** [comment] 2020-12-11 07:12
@dutscher what are you recommending here? ☝️

**Comment by dutscher** [comment] 2020-12-16 19:44
@shilman 
an update for telesync is necessary 
https://github.com/storybookjs/telejson/blob/master/src/index.ts#L209 in this line we need 

```js

const constructorName = value.constructor.name;
Object.assign(value, {
  '_constructor-name_': constructorName,
  ...(constructorName.toLowerCase().includes('event') ? {
    eventData: JSON.parse(JSON.stringify(value, Object.keys(value.constructor.prototype))),
    details: value.detail,
  } : {}),
});
```

then we get the result as my snapshots above shown.

cheers

**Comment by shilman** [comment] 2020-12-20 09:51
@ndelangen is this an uncontroversial fix that you'd approve @ndelangen ? ☝️

**Comment by gaetanmaisse** [comment] 2021-02-07 20:34
💪🏻  @dutscher, facing the same issue so I would be happy to help on this one. @ndelangen do you think it would be ok to apply the changes suggested above (https://github.com/storybookjs/storybook/issues/8544#issuecomment-746903188)? 

Maybe we need to be stricter on the constructor name check in order to not end in that case for any `*Event*` classes and explicitly list some specific class name. Otherwise, we can keep the check as it and check that `value.detail` is defined before setting it. Feels free to ping me on Discord to discuss that.

**Comment by jesperp** [comment] 2021-03-28 21:40
FYI: This error also happens with Svelte!

**Comment by dutscher** [comment] 2021-03-29 07:18
i use a workarround until the fix is inside of telejson:
```
var uniqueId = function(eventName) {
        return eventName + '-' + (new Date()).getTime();
      };

__STORYBOOK_ADDONS.getChannel()
              .emit('storybook/actions/action-event', {
                count: 0,
                data: {
                  name: eventName,
                  args: event.detail,
                },
                id: uniqueId(eventName),
                options: {
                  depth: 15,
                  clearOnStoryChange: true,
                  limit: 50,
                  allowFunction: false,
                }
              });
```

cheers

**Comment by shilman** [comment] 2021-04-01 04:47
We want to address this in 6.3. If you want to contribute to Storybook, we'll prioritize PR review for any fixes here. And if you'd like any help getting started, please jump into the #support channel on our Discord: https://discord.gg/storybook

**Closed** 2021-05-11 06:38 UTC
Labels: addon: actions, feature request, has workaround, help wanted, small
