### ISSUE TITLE
[Bug]: Components not overflowing their canvas after migration to v7

### ISSUE THREAD

**Issue by msanzv** [storybookjs/storybook#25083] opened 2023-12-01 18:08 UTC
### Describe the bug

We're maintaining a component library, and until v6, components with floating elements looked like this in the docs tab.

![Screenshot 2023-12-01 at 16 45 41](https://github.com/storybookjs/storybook/assets/1478898/3e68a98a-835a-43eb-8eb7-39b46440c2be)

Same for other cases like selects, datepickers, modals or notifications: The input trigger is inside the canvas, but whatever it triggered, could overflow the canvas.

After the migration to Storybook 7, none of this components can flow over the canvas anymore:

<img width="1139" alt="image" src="https://github.com/storybookjs/storybook/assets/1478898/e4e418e6-e26d-414f-b673-d0a6f501b34a">

We've been looking both at the migration docs and the `Canvas` docs for config options to solve this, but we didn't figure it out yet. We tried especially the `iframe` vs `inline` options for stories, the `Canvas` options, and the very simple decorator we use to wrap our stories, but none of these worked.

The story of the screenshots above is a simple one, this is the code. This one is still in mdx, but it also happens in other that we already migrated to tsx.

```tsx
<Canvas>
  <Story
    name="Playground"
    args={{
      defaultValue: 'Banana',
    }}
  >
    {Template.bind({})}
  </Story>
</Canvas>
```

Any clue on what can we do to restore the previous behaviour? Is there some obvious config or migration change we might have missed? Or is this a storybook change and we should rethink our docs accordingly? I thought about this option, but was surprised to not find anything on the internet or in the issues of this repo reporting the same issue.

Any guidance is welcome. Thanks in advance!

### To Reproduce

Sorry, tried creating a repo but couldn't figure out exactly how to reproduce all the needed pieces without using some of the things I'm importing, which I can't share here because of company rules. Asking here mostly looking for pointers to docs where a change that could cause this could be documented.

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 4.0.2 - ~/.nvm/versions/node/v18.18.2/bin/yarn <----- active
    npm: 10.2.1 - ~/Sites/only-ui/node_modules/.bin/npm
  Browsers:
    Chrome: 117.0.5938.62
    Safari: 16.6
  npmPackages:
    @storybook/addon-a11y: ^7.5.3 => 7.5.3 
    @storybook/addon-essentials: ^7.5.3 => 7.5.3 
    @storybook/addon-interactions: ^7.5.3 => 7.5.3 
    @storybook/addon-links: ^7.5.3 => 7.5.3 
    @storybook/cli: ^7.5.3 => 7.5.3 
    @storybook/jest: ^0.2.3 => 0.2.3 
    @storybook/react: ^7.5.3 => 7.5.3 
    @storybook/react-vite: ^7.5.3 => 7.5.3 
    @storybook/test-runner: ^0.15.1 => 0.15.1 
    @storybook/testing-library: ^0.2.2 => 0.2.2 
    @storybook/theming: ^7.5.3 => 7.5.3 
    eslint-plugin-storybook: ^0.6.15 => 0.6.15 
    storybook: ^7.5.3 => 7.5.3
```

**Comment by Marklb** [comment] 2023-12-02 07:22
I checked a 6.5.3 project and it has `overflow: hidden;` set on the root of the story container. So unless there was an earlier version of v6 that didn't have that then I don't think it should have allowed anything outside of the container, if it is inside the container's dom.

Does your component support the floating components rendering at the component level and at another level, such as the body? Most implementations support attaching the overlay to the body, which breaks it out of containers that hide their overflow. Could your component have changed where the overlay element is located in the DOM?

**Comment by valentinpalkovic** [comment] 2023-12-02 15:08
Duplicate of https://github.com/storybookjs/storybook/issues/2358. Please also take a look at the feature proposal in https://github.com/storybookjs/storybook/discussions/23699

**Closed by valentinpalkovic** 2023-12-02 15:08 UTC
Labels: bug, needs triage

**Comment by msanzv** [comment] 2023-12-03 09:53
@Marklb Apparently I went too quickly through the proposal and didn't properly check the bug linked from there. In the comments of that bug, it explains that in fact 7.1 moved from using `zoom` to `transform`, and most probably it was that change causing the rendering change.

In a second bug report (https://github.com/storybookjs/storybook/issues/16774) linked from that one, they suggest this as a patch:

```css
.docs-story div[scale] {
  transform: none !important;
}
```

Quickly tried that and it seems to bring back our previous behaviour, so I think we'll try that as a workaround first, until we decide how we handle it long term. For dropdowns and such, just making the canvas taller could be enough. For bigger things like modals and notifications, we might just replace the canvases for those with a `<Story>` and a `Source` block with the code.

I will keep an eye on that proposal anyway, to see how it's handled. Thanks a lot for your help!
