### ISSUE TITLE
addon-knobs select should be able to have undefined options.

### ISSUE THREAD

**Issue by lifeiscontent** [storybookjs/storybook#4487] opened 2018-10-18 22:34 UTC
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

``` js
    const pressed = select(
      'Pressed',
      { Undefined: undefined, False: false, True: true },
      undefined
    );
```

I'd expect there to be a value called Undefined which is selectable, but it is removed when rendered in the knobs panel.

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react latest
- @storybook/addon-knobs latest (alpha)

### Affected platforms 

- _If UI related, please indicate browser, OS, and version_
- _If dependency related, please include relevant version numbers_
- _If developer tooling related, please include the platform information_

### Screenshots / Screencast / Code Snippets (Optional)

```js
    const pressed = select(
      'Pressed',
      { Undefined: undefined, False: false, True: true },
      undefined
    );
```

**Comment by bennyn** [comment] 2018-10-24 10:06
Supporting `undefined` options is very important when displaying React components which have been written in TypeScript.

In TypeScript it is common sense to use the question mark to declare [optional parameters and properties](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html). So an interface for a component's properties can look like this:

```ts
interface Props {
  environment?: 'linux' | 'mac' | 'win';
}
```

Which is equivalent to:

```ts
interface Props {
  environment: 'linux' | 'mac' | 'win' | undefined;
}
```

But different from:

```ts
interface Props {
  environment: 'linux' | 'mac' | 'win' | null;
}
```

Unfortunately, it is not possible to use `undefined` values with [select](https://github.com/storybooks/storybook/tree/v4.0.0-rc.3/addons/knobs#select), so states with optional props cannot be shown with `@storybook/addon-knobs`. 😢

**Comment by lifeiscontent** [comment] 2018-11-15 00:18
@igor-dv do you know who I could talk to about how knobs work so I could
implement this?

**Comment by igor-dv** [comment] 2018-11-16 16:36
@lifeiscontent , sorry for the delay =) you can chat with us on [Discord](https://discord.gg/3DUuDqn):

**Comment by Hypnosphi** [comment] 2019-04-23 13:36
Looks like the root of the issue is that [`telejson`](https://github.com/storybooks/telejson) library that we use to transmit data between preview and manager frames [uses](https://github.com/storybooks/telejson/blob/master/src/index.js#L263) `JSON.parse(data, reviver())` which [ignores](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#Using_the_reviver_parameter) `undefined` values: 

> If the `reviver` function returns `undefined` (or returns no value, for example, if execution falls off the end of the function), the property is deleted from the object.

@ndelangen you probably need to iterate on object fields manually instead of using reviver parameter of `JSON.parse`.

**Comment by alfnielsen** [comment] 2019-04-24 06:32
Hey, 
Just to add a little extra info to @bennyn comments, it's not just TypeScript but ES6 (EcmaScript 2015) that uses optional parameters which only accepts undefined (not null).

In TypeScript it would be something like this:
```ts
interface Props {
  environment?: 'linux' | 'mac' | 'win';
}
const myComponents = ({ environment = 'win' }: props ){ (...) }
```
but you can do the same in ES6 like this:
```js
const myComponents = ({ environment = 'win' }){ (...) }
```
if ```environment = null``` it will be ```null``` instead the method and **not** the default value  ```'win'```

**Comment by christophehurpeau** [comment] 2019-07-01 06:57
I can create an PR on friday if no one works on this yet ?

**Comment by Hypnosphi** [comment] 2019-07-01 11:16
Sure @christophehurpeau

**Comment by Hypnosphi** [comment] 2019-07-01 11:17
@christophehurpeau note that it's telejson library that needs a PR:

https://github.com/storybookjs/storybook/issues/4487#issuecomment-485805825

**Comment by christophehurpeau** [comment] 2019-07-05 15:22
I can't see how we could fix this in telejson, what about transorming undefined to 'undefined' before stringify ?

**Comment by lifeiscontent** [comment] 2019-07-05 15:38
honestly, I don't think telejson is the right starting point for this work, what about a reviver and replacer for the parse/stringify for the knobs?

**Comment by Hypnosphi** [comment] 2019-07-05 23:31
@lifeiscontent what makes you think so?

**Comment by lifeiscontent** [comment] 2019-07-08 19:33
Well, I guess it would depend on if telejson is only being used for knobs. Considering this is a requirement of just knobs currently it makes sense that it should live there, unless telejson is purposely built for knobs. If we later find we want the same functionality across another part of the platform it should then be revisited.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Hypnosphi** [comment] 2019-07-11 17:33
@lifeiscontent [telejson](https://github.com/storybookjs/telejson) states in the repo description that it supports `undefined` while in fact it doesn't. So it's not some specific requirement of knobs

> JSON parse & stringify with support for cyclic objects, functions, dates, regex, infinity, undefined, null, NaN, Classes, Instances

**Comment by lifeiscontent** [comment] 2019-07-12 14:57
>@lifeiscontent [telejson](https://github.com/storybookjs/telejson) states in the repo description that it supports `undefined` while in fact it doesn't. So it's not some specific requirement of knobs ...

@Hypnosphi okay, then I guess it makes sense to do there. Are you working on this? Or should I open a PR?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Hypnosphi** [comment] 2019-07-13 22:12
> Are you working on this?

No I'm not. Feel free to open a PR

**Comment by shilman** [comment] 2019-09-27 23:04
We probably need to upgrade telejson?

**Comment by ndelangen** [comment] 2019-09-28 09:17
Yeah I'll ship a new version soon.

**Comment by Steven-Gassert** [comment] 2019-11-20 18:55
@ndelangen has a new version been shipped with this functionality yet? If not, is it possible to get a link somewhere this work is being tracked?

**Comment by ndelangen** [comment] 2019-11-21 12:45
Released:
https://github.com/storybookjs/telejson/releases/tag/v3.2.0

**Comment by shilman** [comment] 2019-11-26 03:40
Released in https://github.com/storybookjs/storybook/releases/tag/v5.3.0-beta.8

Closing this. Please holler if this didn't fix the problem

**Comment by lifeiscontent** [comment] 2020-11-25 00:43
@shilman still an issue with args. 
![Screen Shot 2020-11-24 at 4 41 54 PM](https://user-images.githubusercontent.com/180963/100167538-25c9d380-2e74-11eb-9edb-63435474074d.png)

![Screen Shot 2020-11-24 at 4 43 19 PM](https://user-images.githubusercontent.com/180963/100167557-2ebaa500-2e74-11eb-8e2a-27c6fed5dbee.png)

should have an option here to not have a value.

**Closed** 2020-11-25 02:45 UTC
Labels: addon: knobs, bug, good first issue
