### ISSUE TITLE
CSF3: Programmatic Title Generation

### ISSUE THREAD

**Issue by gossi** [storybookjs/storybook#15534] opened 2021-07-09 07:49 UTC
From what I read, the CSF3 automatic title generation is based on the path and a potential prefix to  it? I see, this might work for _some_ frameworks but surely not for all. Also monorepos with workspaces might be affected by this (unless you name each package explcitely - which you don't want, because you choose the workspaces already).

An idea to give an options where the existing generation is not feasible is to provide a generation function, this signature:

```ts
function generateStoryTitle(path: string): string;
```

A function that takes the path as input and returns the title of the story. I can see that in either `.storybook/preview.ts` (more likely here) or `.storybook/main.ts`.

**Comment by shilman** [comment] 2021-07-09 08:09
This all needs documenting, but you can specify the root and also the title prefix:

```js
module.exports = {
  stories: [
    { directory: '/some/path', titlePrefix: 'some/prefix', files: '*.somepattern.whatever' }
  ],
}
```

And you can have as many of these entries as you want.

I believe this is sufficiently general to allow for automatically generating titles based on file paths.

The problem with introducing functions, and the reason why we probably won't ever make that kind of change, is because it shuts down the ability to statically analyze your storybook and makes it much harder to integrate with other tools.

**Comment by gossi** [comment] 2021-07-10 11:18
Ah thanks for the updates. That static typing for stories fell completely out of my radar, but nice you think about this.

Let's see what's possible with the options you have. Will try in one of my next upgrades 👍

**Comment by pribilinskiy** [comment] 2021-09-15 09:34
I've updated to `Storybook 6.4.0-alpha.36` and looks like it is broken now
Storybook is empty even if there's just a single `.stories` file with omitted `title`
![image](https://user-images.githubusercontent.com/3078595/133408990-bc9f8e42-1ba1-4d78-9546-4e9bb6771556.png)

**Comment by pribilinskiy** [comment] 2021-09-15 09:47
Downgraded to `alpha35` and it works again.
One suggestion though

In our codebase files are structured in a way that all component-related files (component, unit tests, stories, helpers) that belong together are placed in a single folder

With the automatic title generation we have this structure with unnecessary duplication of the component name, e.g. `Navbar/Navbar` instead of just `Navbar`

![image](https://user-images.githubusercontent.com/3078595/133410925-b10ab605-c50b-4ffe-bed7-691b32d1cb1c.png)

**Comment by shilman** [comment] 2021-09-15 16:08
@pribilinskiy we just merged a massive PR that broke this feature. i'm working on fixes in #16059

**Comment by JohannesFischer** [comment] 2021-11-10 05:49
Is there a way to have a combination of the exported title and the `titlePrefix` ? At the moment it seems as the prefix is ignored when the story title is not empty.

What I am trying to achieve is having a custom title prefixed by the workspace the component is in.

For example:
```
// main.js
stories: [{ directory: '/packages', titlePrefix: 'workspace' }]

// packages/MyComponent.stories.js
export default { title: 'namespace-my-component' }
```

Results in the title namespace-my-component without the prefix set in the story config.

**Comment by lunelson** [comment] 2022-01-05 10:23
> With the automatic title generation we have this structure with unnecessary duplication of the component name, e.g. `Navbar/Navbar` instead of just `Navbar`

This was my first observation when I tried this feature too. I would prefer to have a function option that receives the title (whether a generated one, or a declared one; along with a flag to indicate which) and which then could modify it:

```js
module.exports = {
  stories: [
    {
      directory: '/some/path',
      titleFn(title, isAutoGenerated) {
        return !isAutoGenerated ? title : title.replace(/\/\w+$/, '');
      },
      files: '*.somepattern.whatever',
    },
  ],
};
```

**Comment by eric-burel** [comment] 2022-01-24 15:26
Big +1 for @lunelson approach, this is relevant in the context of a Monorepo where you run 1 storybook for multiple packages with nested structure. For instance I need only the package folder as a prefix, it'd be nice to set this up in user-land

**Comment by jptaranto** [comment] 2022-02-02 21:39
I did not have much luck after playing around with CSF 3 and automatic title generation yesterday. I think it comes down to the structure of our project, which matches the setup @pribilinskiy talked about [above](https://github.com/storybookjs/storybook/issues/15534#issuecomment-919868456) e.g. `src/components/Accordion/Accordion.stories.jsx`

1. Storybook did not find our stories at all when using [a configuration object](https://storybook.js.org/docs/react/configure/overview#with-a-configuration-object) - in fact I couldn't get it to find them in any sub directories at all when using this config notation in main.js - the `*.stories.*` files needed to be in the top level `src` directory to get picked up. Perhaps something is broken.

2. When using a [glob](https://storybook.js.org/docs/react/configure/overview#configure-story-loading) the stories loaded in fine, however the document structure becomes overly verbose with components nested inside folders which have the same name as the component directory.

I'm not sure this feature is working as expected? I'm on 6.4.17.

**Comment by shilman** [comment] 2022-02-03 02:14
@jptaranto 
1. Do you have a reproduction of the configuration object issue? I did a quick sanity check on an example project & everything looked OK to me, so it would be great to get to the bottom of this.
2. The `Accordion/Accordion.stories.js` problem is noted and I'll do my best to fix it in 6.5--it should be an easy one. PRs also welcome here if you're getting antsy.

**Comment by jptaranto** [comment] 2022-02-03 21:53
Hey @shilman, much appreciated. I've spun up a repo quickly to give you a demo of the issue:

https://github.com/jptaranto/storybook-playground

After a bit more playing around, I figured out the story gets picked up if I remove the `files` value from the config object. Pretty sure it looks ok to me as a copied it form the docs.

**Comment by shilman** [comment] 2022-02-04 14:05
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.35 containing PR #17421 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2022-02-04 14:05 UTC
Labels: feature request, csf3

**Comment by dawidk92** [comment] 2022-02-15 09:21
Hey @shilman, it's very cool that you added auto-generation of titles, but I think that it shouldn't modify parts of its path.

I've added config in my `main.js`:
```javascript
stories: [{ directory: "../src", files: "**/*.stories.*" }]
```

I have a story in the path: `src/pages/app/BuildScreen/components/ScreenList/components/ScreenListItem.stories.tsx`

And Storybook generates path like:
<img width="263" alt="image" src="https://user-images.githubusercontent.com/7023167/154029108-91a9bb8e-2e52-4c35-aff4-1b0f02c3e30d.png">

Instead of this, I would like it to generate path **without** capitalization and spacing so it would look like:
<img width="255" alt="image" src="https://user-images.githubusercontent.com/7023167/154030988-a66c14a2-38c9-4416-830d-b8a2ba26bc22.png">

Could you please change this behavior or add some flag to not modify parts of the output path?

**Comment by shilman** [comment] 2022-02-19 14:15
@elektronik2k5 Storybook runs in three places: node, the "preview" iframe that renders the user's components, and the "manager" UI that surrounds the preview. The manager & preview communicate over a channel, which means that all communication needs to be serialized. If you were to specify a function in your story file, it would be defined in the preview. However, the sidebar is rendered in the manager, so we would need to serialize that function from the preview to the manager. Technically this is possible for some JS functions, but it adds too much complexity. If you want full control over your titles, you can manually specify them.

**Comment by elektronik2k5** [comment] 2022-02-19 14:39
> The manager & preview communicate over a channel, which means that all communication needs to be serialized. If you were to specify a function in your story file, it would be defined in the preview. However, the sidebar is rendered in the manager, so we would need to serialize that function from the preview to the manager.

@shilman, considering the fact we're in control of all parts of storybook, can't we instead bundle the same function/module for more than one target (i.e. manager and preview) , thus removing the need for serialization?

**Comment by nfarina** [comment] 2022-03-01 18:13
We have a monorepo and place our stories like this:

`project-root/packages/web-client/src/components/__stories__/Button.stories.tsx`

With automatic titles, this results in a Story tree like:

```
web-client
  - Src
    - Components
      - Stories
        - Button
```

It would be great if the Storybook UI side ignored folders with common names like `src` and `__stories__` (apparently out of fashion now but we like it).

Ideal resulting tree:

```
web-client
  - Components
    - Button
```

If others are interested I'll open an issue!

**Comment by shilman** [comment] 2022-03-02 16:47
@elektronik2k5 In fact, there is a way to customize the UI separately in the manager. It's not documented yet (cc @jonniebigodes) but there's an example here

https://github.com/storybookjs/storybook/blob/next/examples/official-storybook/manager.js#L38

I think between this little-known feature and the pre-release of https://github.com/storybookjs/storybook/pull/17574, you have everything you need! Feedback welcome

**Comment by Leland** [comment] 2025-11-17 18:59
@nfarina 3 years on:

Update `collapsedDirs` to have e.g. `['Components', 'Stories,']` etc. This is for Webpack but should be easily adjustable for others.

.storybook/main.ts

```ts
import { defineMain } from '@storybook/react-webpack5/node';
import type { Indexer } from 'storybook/internal/types';
import { readFile } from 'fs/promises';

const collapseDirs = (dirs: string[]): Indexer => ({
  test: /\.stories\.(js|jsx|mjs|ts|tsx)$/,
  createIndex: async (fileName, { makeTitle }) => {
    const content = await readFile(fileName, 'utf-8');
    let title = makeTitle();
    
    dirs.forEach(dir => {
      title = title.replace(new RegExp(`\\/${dir}(?=\\/)`, 'g'), '');
    });
    
    return Array.from(content.matchAll(/export\s+(?:const|function)\s+(\w+)/g))
      .map(match => match[1])
      .filter(name => name !== 'default')
      .map(exportName => ({
        type: 'story' as const,
        importPath: fileName,
        exportName,
        title,
        name: exportName,
      }));
  },
});

const collapsedDirs = ['components'];

export default defineMain({
  stories: [
    {
      directory: '../src',
      titlePrefix: '',
      files: '**/*.stories.@(js|jsx|mjs|ts|tsx)',
    },
    '../src/**/*.mdx',
  ],
  addons: [
    '@storybook/addon-webpack5-compiler-swc',
    '@storybook/addon-docs',
  ],
  framework: '@storybook/react-webpack5',
  experimental_indexers: (existingIndexers) => [
    collapseDirs(collapsedDirs),
    ...(existingIndexers || []),
  ],
});
```

**Comment by nfarina** [comment] 2025-11-17 19:43
Wow thanks, this is great!

I have since moved away from “src” and “__stories__” folders (partly
because of this storybook thing!) but this is great to have.
