### ISSUE TITLE
Request: Support React and HTML In Same Storybook

### ISSUE THREAD

**Issue by Undistraction** [storybookjs/storybook#3994] opened 2018-08-10 12:00 UTC
### Request Summary

It appears that at present a Storybook can only contain only one kind of component, for example only React OR HTML. Calling `configure` more than once doesn't appear to be supported. 

It would be great to be able to include both HTML and React components in the same Storybook in cases where a site or app shares classes between both.

- "@storybook/html": "^4.0.0-alpha.16",
- "@storybook/react": "^4.0.0-alpha.16",

Related: #3980

**Comment by Hypnosphi** [comment] 2018-09-15 20:13
@ndelangen AFAIR you had some open ticket on an external platform about this

**Comment by ndelangen** [comment] 2018-09-23 21:33
Yes https://storybook.canny.io/roadmap/p/add-ability-to-run-multiple-frameworks-in-1-storybook

**Comment by Hypnosphi** [comment] 2019-08-27 01:01
@AdamVig Yes, there is. Here's a decorator we use in my company to render React stories in HTML storybook: https://github.com/JetBrains/ring-ui/blob/master/.storybook/react-decorator.js

See also https://github.com/storybookjs/storybook/pull/6826

**Comment by Hypnosphi** [comment] 2019-08-27 01:02
Closing as duplicate of https://github.com/storybookjs/storybook/issues/3889

**Closed by Hypnosphi** 2019-08-27 01:02 UTC
Labels: feature request, todo
