### ISSUE TITLE
[Bug]: render: `key` is not a prop issue since 7.2.0-alpha.0

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#23782] opened 2023-08-10 07:39 UTC
### Describe the bug

Since Storybook 7.2.0-alpha.0, any Storybook throws this error in the console:
![image](https://github.com/storybookjs/storybook/assets/1671563/9d8ebbc6-140a-4487-807d-0bd16833a473)

After investigating, these are the candidate PRs introduced the issue:
[UI: Improve Button layout and props](https://github.com/storybookjs/storybook/pull/23356) - [Chromatic](https://62f0fd349c07f78d10b7c017-ypbpahegoh.chromatic.com/?path=/docs/configure-your-project--docs)
[UI: Add storyStatus to sidebar UI](https://github.com/storybookjs/storybook/pull/23342) - [Chromatic](https://62f0fd349c07f78d10b7c017-getzaymbez.chromatic.com/?path=/docs/configure-your-project--docs)
[UI: Improve tabs component, more type correct, allow for FC as title](https://github.com/storybookjs/storybook/pull/23288) - [Chromatic](https://62f0fd349c07f78d10b7c017-cebkoalmqy.chromatic.com/?path=/docs/configure-your-project--docs)

### To Reproduce

Either of these options:
1. Create a new Storybook project
2. Update an existing Storybook project to 7.2.0-alpha.0 or higher
3. Click on any of the Chromatic links I shared

Then check dev tools console

**Comment by EugeneKamikaZe** [comment] 2023-08-10 09:10
same issue on 7.2.2

**Comment by kasperpeulen** [comment] 2023-08-10 15:15
@EugeneKamikaZe Do you use addon-designs, and if so, could you see if upgrading to the latest version solved it?
https://www.npmjs.com/package/@storybook/addon-designs?activeTab=versions

**Comment by petegraves** [comment] 2023-08-10 18:20
Upgrading to version 7.0.4 of @storybook/addon-designs fixed this error for me

**Comment by aldrichdev** [comment] 2023-08-11 23:02
I was able to reproduce this when I upgraded the main Storybook package from `7.0.4` to `7.2.3`, but once I upgraded the other `@storybook/blah` packages to the same version, I could not reproduce it.

**Comment by kasperpeulen** [comment] 2023-08-14 08:21
Thanks closing this for now. Please let us know if upgrading `@storybook/addon-designs` doesn't fix this for you!

**Closed by kasperpeulen** 2023-08-14 08:21 UTC
Labels: bug, ui, sev:S2, upgrade:7.2

**Comment by n19htz** [comment] 2023-08-21 10:16
I don't use @storybook/addon-designs and getting same error on the tab of "Tests" added by @storybook/addon-jest


https://github.com/storybookjs/storybook/assets/39006390/cb020640-c841-4512-8ae1-da57ae09678f

**Comment by Predhin** [comment] 2023-09-04 14:54
same issue on v7.4.0 also

**Comment by EugeneKamikaZe** [comment] 2023-09-04 15:11
same issue on 7.3.2

**Comment by likeuwill** [comment] 2023-09-12 10:30
same issue on 7.4.1, i updated all libs to 7.4.1

**Comment by kasperpeulen** [comment] 2023-09-12 11:45
@Predhin @EugeneKamikaZe and @likeuwill 
Can you please show the version of `@storybook/addon-designs` you are using?

**Comment by EugeneKamikaZe** [comment] 2023-09-12 11:48
@kasperpeulen 7.0.5

**Comment by likeuwill** [comment] 2023-09-12 11:48
@kasperpeulen i dont use `addon-designs`
main.ts
`
 addons: [
    '@storybook/addon-essentials',
    '@storybook/addon-themes',
    'storybook-addon-apollo-client'
  ]
`
and package.json
`
    "@storybook/addon-essentials": "7.4.1",
    "@storybook/addon-interactions": "7.4.1",
    "@storybook/addon-themes": "7.4.1",
    "@storybook/core-server": "7.4.1",
    "@storybook/nextjs": "7.4.1",
    "@storybook/test-runner": "^0.13.0",
    "@storybook/testing-library": "~0.2.0",
`

**Comment by kasperpeulen** [comment] 2023-09-12 12:02
I see that the bug is still there in `storybook-addon-apollo-client` indeed. I will raise a PR there.

**Comment by kasperpeulen** [comment] 2023-09-12 12:49
@EugeneKamikaZe Can you show my your deps like @likeuwill did?

**Comment by EugeneKamikaZe** [comment] 2023-09-12 13:03
@kasperpeulen 
```addons: [
        '@storybook/addon-links',
        '@storybook/addon-essentials',
        '@storybook/addon-interactions',
        '@storybook/theming',
        {
            name: '@storybook/addon-coverage',
            options: {
                istanbul: {
                    ...coverageConfig,
                },
            },
        },
        '@storybook/addon-storysource',
        '@storybook/addon-a11y',
        '@whitespace/storybook-addon-html',
        '@bbbtech/storybook-formik/register',
        '@geometricpanda/storybook-addon-badges',
        '@storybook/addon-designs',
        'storybook-css-modules',
        'storybook-react-i18next',
        'storybook-addon-mock',
    ],
```

```"@bbbtech/storybook-formik": "^2.6.0",
        "@geometricpanda/storybook-addon-badges": "^2.0.0",
        "@storybook/addon-a11y": "^7.3.2",
        "@storybook/addon-actions": "^7.3.2",
        "@storybook/addon-coverage": "^0.0.9",
        "@storybook/addon-designs": "^7.0.5",
        "@storybook/addon-essentials": "^7.3.2",
        "@storybook/addon-interactions": "^7.3.2",
        "@storybook/addon-links": "^7.3.2",
        "@storybook/addon-storyshots": "^7.3.2",
        "@storybook/addon-storyshots-puppeteer": "^7.3.2",
        "@storybook/addon-storysource": "^7.3.2",
        "@storybook/addon-styling": "^1.3.7",
        "@storybook/builder-vite": "^7.3.2",
        "@storybook/builder-webpack5": "^7.3.2",
        "@storybook/cli": "^7.3.2",
        "@storybook/jest": "^0.2.1",
        "@storybook/react": "^7.3.2",
        "@storybook/react-vite": "^7.3.2",
        "@storybook/test-runner": "^0.13.0",
        "@storybook/testing-library": "^0.2.0",
        "@storybook/theming": "^7.3.2",

**Comment by kasperpeulen** [comment] 2023-09-12 13:29
`@bbbtech/storybook-formik/register` has the issue indeed

**Comment by dawidjablonski89** [comment] 2023-09-20 12:25
@tonai @kasperpeulen  Hi, I believe I've found another addon that needs to be updated: storybook-addon-themes

https://github.com/tonai/storybook-addon-themes
https://storybook.js.org/addons/storybook-addon-themes

**Comment by yannbf** [comment] 2023-09-22 11:57
> @tonai @kasperpeulen Hi, I believe I've found another addon that needs to be updated: storybook-addon-themes
> 
> [tonai/storybook-addon-themes](https://github.com/tonai/storybook-addon-themes) [storybook.js.org/addons/storybook-addon-themes](https://storybook.js.org/addons/storybook-addon-themes)

Thank you so much for that @dawidjablonski89 ! That addon is maintained by the community. It seems like it does not support Storybook 7 though: https://github.com/tonai/storybook-addon-themes/issues/79

Could you try that one out, and if it has the same issue, can you please open an issue on that repo?

**Comment by Predhin** [comment] 2023-09-25 03:05
@kasperpeulen sorry for the delayed response, 
"[@storybook/addon-designs]": "[^7.0.5](https://npmjs.com/package/@storybook/addon-designs)"

**Comment by atomicrobokid** [comment] 2023-09-26 12:37
Same issue with `@storybook/addon-storysource` - v7.4.5

**Comment by yannbf** [comment] 2023-10-03 13:54
@Predhin and @atomicrobokid could you open issues respective to the packages which have them? Thanks!
