### ISSUE TITLE
npx sb init doesn't work

### ISSUE THREAD

**Issue by airtonix** [storybookjs/storybook#17923] opened 2022-04-10 08:22 UTC
![image](https://user-images.githubusercontent.com/61225/162609496-d78dcf25-0739-41a9-b082-f116d83be4ea.png)

but `sb` is actually : 

```
thing on git master [x!+?] via nodejs v16.6.1 took 2s 
x npx sb init --help      

sb version 0.12.20
Usage: sb [options] file ...
   or: sb [options] -{c|i} COMMAND
Send file(s) with ZMODEM/YMODEM/XMODEM protocol
    (X) = option applies to XMODEM only
    (Y) = option applies to YMODEM only
    (Z) = option applies to ZMODEM only
  -+, --append                append to existing destination file (Z)
  -2, --twostop               use 2 stop bits
  -4, --try-4k                go up to 4K blocksize
      --start-4k              start with 4K blocksize (doesn't try 8)
  -8, --try-8k                go up to 8K blocksize
      --start-8k              start with 8K blocksize
  -a, --ascii                 ASCII transfer (change CR/LF to LF)
  -b, --binary                binary transfer
  -B, --bufsize N             buffer N bytes (N==auto: buffer whole file)
  -c, --command COMMAND       execute remote command COMMAND (Z)
  -C, --command-tries N       try N times to execute a command (Z)
  -d, --dot-to-slash          change '.' to '/' in pathnames (Y/Z)
      --delay-startup N       sleep N seconds before doing anything
  -e, --escape                escape all control characters (Z)
  -E, --rename                force receiver to rename files it already has
  -f, --full-path             send full pathname (Y/Z)
  -i, --immediate-command CMD send remote CMD, return immediately (Z)
  -h, --help                  print this usage message
  -k, --1k                    send 1024 byte packets (X)
  -L, --packetlen N           limit subpacket length to N bytes (Z)
  -l, --framelen N            limit frame length to N bytes (l>=L) (Z)
  -m, --min-bps N             stop transmission if BPS below N
  -M, --min-bps-time N          for at least N seconds (default: 120)
  -n, --newer                 send file if source newer (Z)
  -N, --newer-or-longer       send file if source newer or longer (Z)
  -o, --16-bit-crc            use 16 bit CRC instead of 32 bit CRC (Z)
  -O, --disable-timeouts      disable timeout code, wait forever
  -p, --protect               protect existing destination file (Z)
  -r, --resume                resume interrupted file transfer (Z)
  -R, --restricted            restricted, more secure mode
  -q, --quiet                 quiet (no progress reports)
  -s, --stop-at {HH:MM|+N}    stop transmission at HH:MM or in N seconds
      --tcp                   build a TCP connection to transmit files
      --tcp-server            open socket, wait for connection
  -u, --unlink                unlink file after transmission
  -U, --unrestrict            turn off restricted mode (if allowed to)
  -v, --verbose               be verbose, provide debugging information
  -w, --windowsize N          Window is N bytes (Z)
  -X, --xmodem                use XMODEM protocol
  -y, --overwrite             overwrite existing files
  -Y, --overwrite-or-skip     overwrite existing files, else skip
      --ymodem                use YMODEM protocol
  -Z, --zmodem                use ZMODEM protocol

short options use the same arguments as the long ones
```

**Comment by airtonix** [comment] 2022-04-10 08:41
Can you please please please please just outline the steps to manually install storybook into a project.

**Comment by airtonix** [comment] 2022-04-10 09:12
so it turns out that the storybook team naively expected no one else on earth to publish a package providing a binary called `bin`...

for those who want to run the `sb` command properly: 

```
npx --package @storybook/cli  sb init
```

https://github.com/storybookjs/storybook/tree/next/lib/cli

**Comment by shilman** [comment] 2022-04-11 01:43
@airtonix any chance you can figure out which package is installing the binary called `sb`?

**Comment by airtonix** [comment] 2022-04-11 01:56
@shilman There might be a way utilising vscodes javascript debugging tool and breakpoints in npx itself... not heaps hopeful on this outcome.

even if we discover who it was... it feels like a thing that will keep happening, since NPM.js only protects against package name squatting.

**Comment by shilman** [comment] 2022-04-11 02:01
@airtonix what version of npm are you running?

So far I'm not able to reproduce this. We do own the package called `sb`, which is how this currently works for most users.

**Comment by shilman** [comment] 2022-04-11 02:02
What if you run:

```
more ./node_modules/.bin/sb
```

**Comment by airtonix** [comment] 2022-04-11 02:07
@shilman yeah but doesn't npx works like this ? 

- does `sb` exist in some node_modules/.bin ?
- does `sb` exist on the PATH
- try to install something from npmjs that provides `sb`

so in my case Fedora 34 provides a `/usr/bin/sb`: 

```
$ yum provides /usr/bin/sb
...snips butt loads of dnf update spam...

lrzsz-0.12.20-53.fc34.x86_64 : The lrz and lsz modem communications programs
Repo        : @System
Matched from:
Filename    : /usr/bin/sb

lrzsz-0.12.20-53.fc34.x86_64 : The lrz and lsz modem communications programs
Repo        : fedora
Matched from:
Filename    : /usr/bin/sb

```

But it illustrates a problem with the documentation:

- on any OS there might be something else that gives `/usr/bin/sb`,
- the use might have `PATH=${HOME}/bin;${PATH}` in their profile (  and they are amazing at naming things so call a custom tool `~/bin/sb` 🤷🏻  you can't control this.

**Comment by airtonix** [comment] 2022-04-11 02:12
yep, earlier i didn't have `@storybook/cli` installed, but now that I do, `npx sb ...` always uses the cli you created.

if i step outside of the repo or clear my npm cache (I think), then npx goes back to resolving `sb` from `/usr/bin/sb`

**Comment by shilman** [comment] 2022-04-11 02:12
@airtonix when I run:

```
$ which ncdu
/usr/local/bin/ncdu
```

However, when I run:

```
$ npx ncdu
Need to install the following packages:
  ncdu
Ok to proceed? (y)
...
```

It downloads and installs https://www.npmjs.com/package/ncdu, which is a different program.

**Comment by airtonix** [comment] 2022-04-11 02:18
@shilman have you ever downloaded that package before?

**Comment by airtonix** [comment] 2022-04-11 02:18
i'm spinning up a newly created directory with a version of node i've never used before via asdf and wiping my `~/.npm`

**Comment by airtonix** [comment] 2022-04-11 02:20
i think the easiest way to avoid this annoying behaviour and time sink it would bring for you is to update documentation so that any mention of `npx sb ...` is changed to `npx npx --package @storybook/cli  sb ...`

**Comment by airtonix** [comment] 2022-04-11 02:24
i can't reproduce anymore is keeps wanting to correctly install an `sb` package

**Comment by shilman** [comment] 2022-04-11 02:25
Yeah, we also have the package `storybook`, so I think we're going to switch to that instead:

```
npx storybook init
```

This will have the same problem, if somebody installs a binary called `storybook` in their path. But I think that's a much lower possibility than `sb`, which looks like it's a built-in utility in some linux distributions

**Comment by airtonix** [comment] 2022-04-11 11:53
@shilman did you want to leave this issue open? or are you actioning this somewhere else ?

**Comment by shilman** [comment] 2022-04-11 16:36
Tracking at #17934 and closing this. Thanks so much @airtonix for helping debug this!!! 🙏

**Closed** 2022-04-11 16:36 UTC
Labels: bug, cli, linear

**Comment by shilman** [comment] 2022-04-17 12:38
@airtonix if you type `npx sb@latest init` does that fix it?
