### ISSUE TITLE
@storybook/react@6.1.6 build failure

### ISSUE THREAD

**Issue by michaelaflores** [storybookjs/storybook#13269] opened 2020-11-25 16:03 UTC
**Describe the bug**
When running `start-storybook`, the following error occurs:

```
info => Loading 1 config file in "./.storybook"
info => Loading 7 other files in "./.storybook"
info => Adding stories defined in ".storybook/main.js"
ERR! Error: Cannot find module 'react/package.json'
...stacktrace
WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

✖ ｢wdm｣: Hash: 99602bd3a64e5e0dd377
Version: webpack 4.44.2
Time: 94ms
Built at: 11/25/2020 9:58:18 AM

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

ERROR in Entry module not found: Error: Can't resolve './src' in '/Users/michaelflores/workspace/video-client/stories'
```

**To Reproduce**

1. Run `start-storybook`

**Expected behavior**
The build succeeds. Reverting to 6.0.28 fixes the issue.

**Code snippets**
main.js
```js
module.exports = {
  stories: [
    "../**/*.stories.mdx",
    "../**/*.stories.@(js|jsx|ts|tsx)",
  ],
  addons: [
    {
      name: "@storybook/addon-docs",
      options: {
        configureJSX: true,
      },
    },
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/preset-create-react-app",
  ],
  webpackFinal: async (config) => {
    config.module.rules.push({
      test: /\.(ts|tsx)$/,
      exclude: /node_modules/,
      use: {
        loader: "ts-loader",
        options: {
          compiler: 'ttypescript',
        }
      }
    });
    config.resolve.extensions.push('.ts', '.tsx');
    return config
  },
  typescript: {
    check: false,
    checkOptions: {},
    reactDocgen: 'react-docgen-typescript',
    reactDocgenTypescriptOptions: {
      shouldExtractLiteralValuesFromEnum: true,
      propFilter: (prop) => (prop.parent ? !/node_modules/.test(prop.parent.fileName) : true),
    },
  },
};
```

**System**
```
  System:
    OS: macOS 11.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.16.1/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 87.0.4280.67
    Firefox: 76.0.1
    Safari: 14.0.1
```

**Comment by shilman** [comment] 2020-11-25 16:59
Do you have a repro repo you can share?

**Comment by shilman** [comment] 2020-11-25 16:59
@merceyz this seems related to your changes, no?

**Comment by michaelaflores** [comment] 2020-11-25 18:10
@shilman I unfortunately don't have this available on a public repo.

**Comment by merceyz** [comment] 2020-11-25 21:01
> @merceyz this seems related to your changes, no?

Shouldn't be, but without a repro who knows what's going on

**Comment by michaelaflores** [comment] 2020-11-25 21:28
Fwiw this has been occurring since at least before the fix introduced for #13209

**Comment by michaelaflores** [comment] 2020-12-01 00:17
I haven't yet been able to stand up a repo for this but wanted to note that this also occurs on `6.1.9`.

**Comment by fcalizobrandcoders** [comment] 2020-12-01 14:00
Having the same issues here. I have `react` and `react-dom` in the peerDeps, and upgrading to the newest version of storybook (6.1.9) breaks, UNLESS i move `react` and `react-dom` to the normal dependencies.

As of now, reverting back to 6.0.28 (and keeping `react` and `react-dom` in peerDeps works.

**Comment by AleshaOleg** [comment] 2020-12-01 16:26
I have an available repo to reproduce this - https://github.com/ubergrape/grape-ds/pulls

**Comment by steveoh** [comment] 2020-12-01 18:23
https://github.com/agrc-widgets/kitchen-sink is a repro once you upgrade

**Comment by katiawheeler** [comment] 2020-12-01 20:42
Also having this issue with the same scenario - `react` and `react-dom` are peer dependencies. Was able to add them as dev dependencies for time being to get it to work.

**Comment by shilman** [comment] 2020-12-02 04:22
@AleshaOleg Thanks for providing a repro. I was able to repro and fix by adding a `react-dom` dev dependency per @katiawheeler. This is not a breaking change because they were declared as peer dependencies in earlier versions of Storybook. I've added a note about it here:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#react-peer-dependencies

@katiawheeler That's the recommended fix, not a "for the time being" workaround. 😄 If we install our own version of React it opens us up to a world of pain, which is why we made the switch in the first place.

**Comment by katiawheeler** [comment] 2020-12-02 04:26
@shilman awesome, I think that will work for me as long as that’s the recommended path forward and is documented for future developers! Appreciate the update!

**Comment by michaelaflores** [comment] 2020-12-02 04:37
Thanks for looking into this and appreciate that docs update @shilman

**Comment by shilman** [comment] 2020-12-02 08:46
Cool, going to close this one for now! 🚀

**Closed by shilman** 2020-12-02 08:46 UTC
Labels: P0, app: react, bug

**Comment by bugtype** [comment] 2021-01-09 04:07
Hmm... I can't solve it by documentation. I solved it like below. Use it temporarily.

before
```
    "@storybook/react": "^6.1.11",
```

after
```
    "@storybook/react": "6.0.28",
```

**Comment by erikiva** [comment] 2021-02-23 15:41
I had the same problem tried upgrading with `npx sb upgrade` but run into peer dependency problems that I fixed with the flag `--legacy-peer-deps` and then run into this. Fixed it the same way, going back to "6.0.28" is this something that will be fixed?

**Comment by shilman** [comment] 2021-02-25 00:56
@bugtype @erikiva Do you have a repro repo you can share?

**Comment by erikiva** [comment] 2021-02-25 01:10
I can't share the repo but I could share any individual files and show the errors I am getting. And I can try any suggestions and report back.

**Comment by chrisdrifte** [comment] 2021-04-07 14:40
I got this error after adding a package with `npm install` instead of `yarn add` by accident -- leaving this note in case anyone else makes the same mistake

**Comment by jampack** [comment] 2021-07-08 07:35
So it was working in external libraries in previous versions and now it wont :)

**Comment by SaraRavasio** [comment] 2021-07-26 11:43
When I downgrade the version to `6.0.28` I can't run the storybook project, due to invalid hook calls.
But if I put back the `6.3.0` I get `Cannot find module '@storybook/react'.`

Do you have any updates?

For now I just removed the use of types `Story` and `Meta` from `@storybook/react'` but I really hope you can fix this 🙏 

Thanks

**Comment by shilman** [comment] 2021-07-26 11:57
@SaraRavasio we still don't have any reproductio

**Comment by JoeyFenny** [comment] 2021-07-30 19:43
My error was for react-dom `ERR! Error: Cannot find module 'react-dom/package.json'`

Simply running `npm install --save-dev react-dom` fixed it for me.

**Comment by DigiBanks99** [comment] 2022-01-01 10:37
Why is this _fix_ needed for Angular projects? Can it not be a peer dependency for the `@storybook/angular` addon?

**Comment by shilman** [comment] 2022-01-05 09:06
@DigiBanks99 this shouldn't be needed for angular projects. `react-dom` is a dependency of `@storybook/angular`

**Comment by Moalpima** [comment] 2022-01-05 15:27
Just had the same problem in my Angular project. An update of storybook from 6.4.7 to 6.4.9 solved it. (no need to add react-dom)

**Comment by michaelVictoriaDev** [comment] 2022-01-26 01:52
@JoeyFenny Thanks man, Its work like a charm!
