### ISSUE TITLE
Storybook uses own webpack config with angular components that breaks images requiring

### ISSUE THREAD

**Issue by artaommahe** [storybookjs/storybook#11610] opened 2020-07-19 17:39 UTC
**Describe the bug**
Using storybook with angular we faced an issue that storybook does not use angular-cli webpack config for components build and e.x. requiring images resolves to different stuff in the storybook and in the real angular project.

**To Reproduce**
1. new angular project, 6.0.0-rc.8 storybook
2. add any png image and require it in the component like `require('./smth.png')`
3. console.log required content
4. see `/static/media/smth.{hash}.png` in storybook and `{ default: 'smth.{hash}.png' }` in the angular app

So this require returns different types for storybook and for the real app dev/build. This issue forces to use explicit loader usage in the require function that lose default angular-cli file-loader params (e.x. `require('!file-loader!./smth.png')` resolves to `{hash}.png`)

**Expected behavior**
Storybook uses the  same loaders configuration as the angular-cli and has same behavior.

**System:**
```
Environment Info:

  System:
    OS: Windows 10 10.0.19041
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.18.1 - C:\Program Files\nodejs\node.EXE      
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.19041.1.0
```
```
$ yarn why @storybook/core

=> Found "@storybook/core@6.0.0-rc.8"
```

**Additional context**
Angular cli file-loader configuration
https://github.com/angular/angular-cli/blob/9efc3cd1cd91193c41ac193f919fc4bc5d6c8cba/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts#L516
Storybook file-loader configuration
https://github.com/storybookjs/storybook/blob/7a907cff32ade8a0f40515b540c6d882abd2964e/lib/core/src/server/preview/base-webpack.config.js#L70

**Comment by artaommahe** [comment] 2020-08-16 08:54
😕

**Comment by artaommahe** [comment] 2020-09-06 11:28
😕

**Comment by Velenir** [comment] 2020-09-28 13:45
We have this same issue when using `require.context` with custom Webpack config + Typescript and React vs storybook

Storybook version 6.0.21

Here's a [workaround](https://github.com/gnosis/dex-react/blob/require.default_storybook_workaround/src/components/common/TokenImg.tsx#L50-L58) we have employed

**Comment by Velenir** [comment] 2020-09-28 15:17
Found a proper fix.
Storybook has the following rule for images and other files in its `config.module.rules` (accessible through `webpackFinal(config)` in `.storybook/main.js`):
```js
{
        test: /\.(svg|ico|jpg|jpeg|png|gif|eot|otf|webp|ttf|woff|woff2|cur|ani|pdf)(\?.*)?$/,
        loader: 'file-loader',
        options: { name: 'static/media/[name].[hash:8].[ext]', esModule: false }
}
```
Need to change to `esModule: true` to turn the modules generated from images into esModules with `default` field

**Comment by artaommahe** [comment] 2020-12-26 09:44
yep, it has workaround. But default behavior is different to angular-cli one. Components in strorybook and components in dev/prod angular-cli build work differently due to different webpack configuration.

**Comment by peey** [comment] 2021-02-11 05:38
I see 

```
info => Using angular project '<project-name>' for configuring Storybook.
info => Loading angular-cli config.
info => Get angular-cli webpack config.
info => Using default Webpack setup
```

And then I see a build failure (storybook build can't import something, but the angular build can). 
The workarounds seem to be a hit and miss.

I wonder what's happening between `Get angular-cli webpack config` and `Using default Webpack setup`. 

Perhaps it fails to find it?

**Comment by peey** [comment] 2021-02-11 06:12
I found a work-around for my issue. My issue was that webpack and TS6137 were in conflict. Using `import type` instead of `import` fixed my issue. 

But it still remains a mystery why not using `import type` worked with angular cli but not with storybook.

**Comment by shilman** [comment] 2021-02-15 01:42
@peey it's because angular cli uses `tsc` which analyzes your entire project at once, whereas storybook uses babel, which processes each file individually and has problems distinguishing between types (which are only used by typescript and don't end up as exports in the final bundle) and actual exports.

cc @gaetanmaisse @mrmckeb

**Comment by valentinpalkovic** [comment] 2023-05-08 14:54
Please provide a reproduction for Storybook 7. I will close this issue in the meantime because we don't use babel anymore to process files in an Angular project. Feel free to reopen it as soon as the replica is available!

**Closed by valentinpalkovic** 2023-05-08 14:54 UTC
Labels: question / support, configuration babel / webpack, has workaround, angular
