### ISSUE TITLE
Controls incorrectly populating an undefined option

### ISSUE THREAD

**Issue by theAdhocracy** [storybookjs/storybook#14523] opened 2021-04-08 16:41 UTC
**Describe the bug**
Since upgrading to v6.2.5 all optional component props using string literals are also outputting an "undefined" option. Whilst technically accurate, this is causing confusion with users, particularly where default prop values are set that would make an `undefined` value an impossible outcome.

Using TypeScript and React. We've upgraded directly from v6.1.2 so unclear exactly when the behaviour changed.

**To Reproduce**

1. Create a component using a string literal prop type
1. View in Canvas and look in Controls panel
1. `undefined` value should be present

**Expected behavior**
I'd expect `undefined` to be ignored even if it was technically present on the typing (due to being optional), as has historically been the case.

**Screenshots**
Incorrect in v6.2.5:
![image](https://user-images.githubusercontent.com/7009462/114063350-6c065900-9890-11eb-9b37-99cd22d27e10.png)

Expected behaviour as of v6.1.2:
![image](https://user-images.githubusercontent.com/7009462/114064026-2302d480-9891-11eb-8278-f0afff2685d4.png)

**System**

```
  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Binaries:
    Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 89.0.4389.114
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.68)
  npmPackages:
    @storybook/addon-a11y: ^6.2.5 => 6.2.5
    @storybook/addon-actions: ^6.2.5 => 6.2.5
    @storybook/addon-essentials: ^6.2.5 => 6.2.5
    @storybook/addon-links: ^6.2.5 => 6.2.5
    @storybook/node-logger: ^6.2.5 => 6.2.5
    @storybook/preset-create-react-app: ^3.1.7 => 3.1.7
    @storybook/react: ^6.2.5 => 6.2.5
    @storybook/theming: ^6.2.5 => 6.2.5
```

**Comment by shilman** [comment] 2021-04-09 01:20
Do you have a repro repo you can share?

**Comment by theAdhocracy** [comment] 2021-04-12 11:33
@shilman Sorry for the delay, but I've put together a stripped down example showing the behaviour: https://github.com/theAdhocracy/sb-example

Just clone locally, `npm install`, and `npm run storybook` to get it working. You'll see the `Button` component has two props which are being populated with `undefined`. I've tested and confirmed that this only happens when string literals are marked as optional; there seems to be some overlap with TypeScript, too, as I tested on a non-TS project as well today and that upgraded without these issues (that project uses PropTypes).

**Comment by shilman** [comment] 2021-04-12 13:42
I took a quick look at the repro. What I found is that we are passing the following to react-docgen-typescript-plugin using `yarn storybook --debug-webpack`:

```
    DocgenPlugin {
      name: 'React Docgen Typescript Plugin',
      options: {
        shouldExtractLiteralValuesFromEnum: true,
        shouldRemoveUndefinedFromOptional: true,
        propFilter: [Function: propFilter],
        savePropValueAsString: true
      }
    }
```

This is a bit different from what we passed in 6.1. I also found that `Button.__docgenInfo` contains:

```
{
    "defaultValue": {
        "value": "small"
    },
    "description": "The size of the button",
    "name": "size",
    "required": false,
    "type": {
        "name": "enum",
        "value": [
            {
                "value": "undefined"
            },
            {
                "value": "\"small\""
            },
            {
                "value": "\"large\""
            }
        ]
    }
}
```

I think this means there is a bug in `react-dogen-typescript` for these options, since we are passing `shouldRemoveUndefinedFromOptional: true`

**Comment by theAdhocracy** [comment] 2021-04-12 15:42
Just done some local testing, looks like it's a conflict between `shouldExtractLiteralValuesFromEnum` and `shouldRemoveUndefinedFromOptional`. If `shouldExtractLiteralValuesFromEnum` is set to `false` the issue goes away (though unsure what issues that itself might create).

For example, the `docgenInfo` output with `shouldExtractLiteralValuesFromEnum` set to `true` looks like this:
```
size: {
   defaultValue: { 
       value:"small"
   },
   description: "The size of the button",
   name: "size",
   required: !1,
   type: { 
       name: '"small" | "large"'
   }
}
```

Whereas with `shouldExtractLiteralValuesFromEnum` set to `false`:
```
size: {
   defaultValue: { 
       value:"small"
   },
   description: "The size of the button",
   name: "size",
   required: !1,
   type: { 
       name: "enum",
       value: [
          {
              value: "undefined"
           },
          {
              value: "small"
           },
          {
              value: "large"
           }
       ]
'"small" | "large"'
   }
}
```

Out of interest, I tried changing the order of the two options but it didn't make any difference.

Taking a look at `react-docgen-typescript` I think I can see the conflict between the two flags, so will raise a ticket over there as well. In the meantime, if `shouldExtractLiteralValuesFromEnum` is actually not needed that could be a quick fix for Storybook.

**Comment by shilman** [comment] 2021-04-12 17:50
Pretty sure it's all needed in the storybook side unfortunately

**Comment by michelengelen** [comment] 2021-04-23 13:26
just to drop this in here since i have been looking into `react-docgen-typescript` package to solve this issue. I cannot get it to reproduce a property that has a type, values or raw type that includes `undefined` like it does in your example.

Even if I run it in our `storybook` installation directly it does not show the `undefined` value (we have the same problem there as @theAdhocracy )

I will try to look into `react-docgen-typescript-plugin` next to see if I can find a problem there.

**Comment by michelengelen** [comment] 2021-04-23 14:07
cc'ing @shilman @theAdhocracy 
I checked all files and ran some tests over at the `react-docgen-typescript-plugin` repo and could not find a single case where ` | undefined` is added to the value array of the type definition.

One last thing I will try is getting an "old" version of both packages and see if it occurs with them.

**Comment by vinassefranche** [comment] 2021-05-03 12:40
Hi!

I don't know if I need to open another issue but it seems to be on the same subject.
I have this 'undefined' option too and if I use the value of the prop in a object, the actual value passed if 'undefined' (as string) which can crash storybook.
You can see below the gif of the behavior and you can find the repository to reproduce the issue [here](https://github.com/vinassefranche/storybook-issue)

![storybook-issue](https://user-images.githubusercontent.com/15926755/116876696-246bb680-ac1d-11eb-913c-8ff7bf772177.gif)

Despite that, storybook controls are amazing so thanks for them!

**Comment by mod-flux** [comment] 2021-05-06 08:18
I'm also coming across this `undefined` issue where optional props (with defaults) in TS are including an `undefined` radio on Controls.

**Comment by Yonom** [comment] 2021-05-27 17:52
We are also explaining the same issue as the comments above

Storybook is passing `"undefined"` (a string) instead of `undefined` to the component

**Comment by peterctct** [comment] 2022-10-24 17:59
We're still experiencing this issue in 6.4.22, where optional props are being presented in Storybook with an `undefined` option even though a default prop is set within the component.

Is there an ETA on when this might be addressed?

**Comment by dungle-scrubs** [comment] 2023-02-18 08:37
This is still happening today, in v7.  I'm currently looking for the string `"undefined"` now whenever I'm creating a Story where `undefined` is an expected option via the controls.

**Comment by tmeasday** [comment] 2023-05-03 05:23
@dungle-scrubs -- what framework are you using? Do you have a reproduction you can share?

**Comment by tmeasday** [comment] 2023-06-06 05:34
As far as I know this issue was addressed in 6.x, with maybe Angular not being quite resolved completely until 7.0.

By the sounds of it there may be some cases where it still happens in 7.0, but without a reproduction, or even knowing what framework/renderer it was it's difficult to move forward. I'm going to close this issue and can folks open a new ticket with concrete details if they are seeing it in 7.0

**Closed by tmeasday** 2023-06-06 05:34 UTC
Labels: question / support, react, args, addon: controls

**Comment by robcrockhlx** [comment] 2023-07-27 21:44
I'm still experiencing this issue with React and Vite.

Here's my package.json
`{
  "name": "@playgrounds/vite",
  "private": true,
  "version": "0.1.1",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "lint": "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview",
    "start-storybook": "storybook dev -p 6006",
    "build-storybook": "storybook build",
    "test:chromatic": "chromatic --project-token=\"$CHROMATIC_PROJECT_TOKEN\""
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@babel/core": "^7.22.9",
    "@myhelix/ui": "^0.1.0",
    "@nx/storybook": "^16.5.5",
    "@storybook/addon-actions": "^7.1.1",
    "@storybook/addon-essentials": "^7.1.1",
    "@storybook/addon-interactions": "^7.1.1",
    "@storybook/addon-links": "^7.1.1",
    "@storybook/addon-mdx-gfm": "^7.1.1",
    "@storybook/addon-styling": "^1.3.4",
    "@storybook/react": "^7.1.1",
    "@storybook/react-vite": "^7.1.1",
    "@storybook/testing-library": "^0.2.0",
    "@types/react": "^18.2.15",
    "@types/react-dom": "^18.2.7",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "@vitejs/plugin-react": "^4.0.3",
    "babel-loader": "^8.3.0",
    "chromatic": "^6.20.0",
    "eslint": "^8.45.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.4.3",
    "eslint-plugin-storybook": "^0.6.13",
    "storybook": "^7.1.1",
    "typescript": "^5.0.2",
    "vite": "^4.4.5"
  },
  "readme": "ERROR: No README data found!",
  "_id": "@playgrounds/vite@0.1.1"
}
`

**Comment by tmeasday** [comment] 2023-07-28 01:17
@robcrockhlx can you please provide a reproduction on a new ticket?

**Comment by tounsoo** [comment] 2024-04-06 02:34
I believe I still have this issue in SB8, I think what I really need is that `undefined` to be `undefined` and not a string.

**Comment by jussirantala** [comment] 2024-05-07 12:43
Yes, it's still an issue.

**Comment by AndreiSager** [comment] 2024-12-22 07:41
Adding shouldRemoveUndefinedFromOptional and setting it to true fixed my problem 

The solution is from https://github.com/styleguidist/react-docgen-typescript/issues/341

![image](https://github.com/user-attachments/assets/945e5250-32bf-4793-aebc-068d0f89e9ca)

## Before 
![image](https://github.com/user-attachments/assets/da63a9a9-78c7-41a3-a759-257521e5e34a)

## After
![image](https://github.com/user-attachments/assets/158ad9fc-314f-4472-99c0-3097080ea670)
