### ISSUE TITLE
Storyshots is leaking memory

### ISSUE THREAD

**Issue by SimenB** [storybookjs/storybook#3286] opened 2018-03-26 08:27 UTC
### Bug or support request summary
Bug

### Steps to reproduce
See https://github.com/SimenB/storyshots-leak for example, but every single installation of storyshots (at least for React, haven't tested others) should reproduce without issue following the steps in the linked README.

To satisfy template:
1. Install and setup storyshots
1. Run jest
1. See leakage either through Jest's builtin capabilities (`logHeapUsage` and `detectLeaks`) or using some OS tool to see memory usage.

### Please specify which version of Storybook and optionally any affected addons that you're running

```
"@storybook/addon-storyshots": "^3.3.15",
"@storybook/react": "^3.3.15",
```

### Affected platforms 

- Jest@22.4.3

### Screenshots / Screencast / Code Snippets (Optional)

![image](https://user-images.githubusercontent.com/1404810/37894913-0a213072-30e0-11e8-8e57-b9f20bf28db2.png)

(A bonus would be to remove the `info => Loading custom .babelrc` text...)

**Comment by jrmurad** [comment] 2020-03-05 03:35
I think we have narrowed down where the leak is. Our project has 198 test suites and we see ~45mb increase for each one with `node --expose-gc ./node_modules/.bin/jest --runInBand --logHeapUsage`.

We eliminated that (and had tests running same as usual) by commenting out lines in `node_modules/@storybook/core/server.js`:

```
const defaultWebpackConfig = require('./dist/server/preview/base-webpack.config');
const serverUtils = require('./dist/server/utils/template');
//const buildStatic = require('./dist/server/build-static');
//const buildDev = require('./dist/server/build-dev');
const toRequireContext = require('./dist/server/preview/to-require-context');

const managerPreset = require.resolve('./dist/server/manager/manager-preset');

module.exports = {
  managerPreset,
  ...defaultWebpackConfig,
  //...buildStatic,
  //...buildDev,
  ...serverUtils,
  ...toRequireContext,
};
```

We're on 5.3.14.

Before (machine has 64gb RAM):

```
node --expose-gc ./node_modules/.bin/jest --runInBand --logHeapUsage
 PASS  a (9.709s, 252 MB heap size)
 PASS  b (5.631s, 362 MB heap size)
 PASS  c (437 MB heap size)
...
 PASS  x (1937 MB heap size)
 PASS  u (5.015s, 1962 MB heap size)
 RUNS  z

<--- Last few GCs --->

[14445:0x5127f60]   117729 ms: Mark-sweep 1986.7 (2074.5) -> 1973.7 (2076.5) MB, 466.6 / 0.8 ms  (average mu = 0.246, current mu = 0.227) allocation failure scavenge might not succeed
[14445:0x5127f60]   118383 ms: Mark-sweep 1989.2 (2077.5) -> 1974.9 (2079.5) MB, 467.9 / 0.7 ms  (average mu = 0.264, current mu = 0.285) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x145ce19]
Security context: 0x271be7b40921 <JSObject>
    1: _execModule [0x3187af0ba299] [/home/jason/trumid-fe/node_modules/@jest/core/node_modules/jest-runtime/build/index.js:~936] [pc=0x64bf4aa52dc](this=0x1a8368f186e1 <Runtime map = 0x1c6ac7f12d21>,0x17f756364109 <Object map = 0x9dbcc75c5f1>,0x213632f004b9 <undefined>,0x1a8368f18a61 <Map map = 0x357ddfac0f31>,0x31ee342896e1 <String[#98]: /home/jason/trumid-fe/n...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

After:

```
node --expose-gc ./node_modules/.bin/jest --runInBand --logHeapUsage
 PASS  a (9.377s, 241 MB heap size)
 PASS  b (5.489s, 225 MB heap size)
 PASS  c (294 MB heap size)
...
```

**Comment by anuraags** [comment] 2020-05-18 00:12
This is now causing issues for our workflow as well. We were unable to upgrade our storybook dependencies (including storyshots) from version 5.2.6 to 5.3.18 as our jest run would just fail with memory allocation errors.

**Comment by bastiRe** [comment] 2020-06-26 16:23
We had the same problem and fixed it for us by separating our storyshots by folder into different testsuites. We accomplished this by creating separate Storyshot files and using the `storyKindRegex` to only snapshot a specific subset of stories in each file.

**Comment by keverw** [comment] 2020-08-16 12:15
I've ran into this issue too. Had my storybook open for a few days working on my own design system and it ended up eating up 19GB of ram (well my computer doesn't have that much ram so of course it swapping). On a Mac with the latest OS updates and using the MDX plugin too.

**Comment by vidal7** [comment] 2020-09-18 15:14
I've ran into this issue too and while waiting for the fix, we fixed it by mocking @storybook/core/server. This solution was inspired by https://github.com/storybookjs/storybook/issues/3286#issuecomment-595011324 Thank you @jrmurad 

`
jest.mock('@storybook/core/server', () => ({
    toRequireContext: require('@storybook/core/dist/server/preview/to-require-context').toRequireContext
}));
`

Also here is a great article that helped me a lot findind memory leaks : https://chanind.github.io/javascript/2019/10/12/jest-tests-memory-leak.html

**Comment by shilman** [comment] 2020-09-24 06:12
@vidal7 do you know what the proper storyshots fix would be for that?

**Comment by vidal7** [comment] 2020-09-24 12:35
@shilman, I think so. Maybe just changing in this file (addons/storyshots/storyshots-core/src/frameworks/configure.ts) a import. So

Change
`import { toRequireContext } from '@storybook/core/server';`

To
`const toRequireContext = require('../../../core/dist/server/preview/to-require-context');`

I think I would work. The problem is that importing toRequireContext from '@storybook/core/server'; imports too much things in addons/storyshots/storyshots-core/src/frameworks/configure.js. Because of typescript compilation to javascript, the first import is compiled to `var server_1 = require("@storybook/core/server");` in @storybook/addon-storyshots/dist/frameworks/configure.js

**Comment by shilman** [comment] 2020-09-24 12:41
Oof that's pretty ugly though. @ndelangen @tmeasday WDYT about a little refactoring here?

**Comment by ndelangen** [comment] 2020-09-25 06:41
This might work:

```js
import { toRequireContext } from '@storybook/core/server/dist/server/preview/to-require-context';
```

?

**Comment by stu039** [comment] 2021-01-04 12:29
+1

**Comment by rajanlagah** [comment] 2021-02-02 18:05
![Screenshot from 2021-02-02 23-33-42](https://user-images.githubusercontent.com/20952569/106643059-2c30a600-65af-11eb-8222-bb795892b166.png)

It is eating every resource of the PC here. :cry:

**Comment by rajanlagah** [comment] 2021-02-02 18:12
Do we think running all these node processes in docker by limiting resources will help ? 
I think if we limit number of CPU for `yarn dev` command then it will take time but will be in control of developer. 
I can help building this have some experience with running node apps in docker.

**Comment by dheerajk02** [comment] 2022-05-31 13:57
> I've ran into this issue too and while waiting for the fix, we fixed it by mocking @storybook/core/server. This solution was inspired by [#3286 (comment)](https://github.com/storybookjs/storybook/issues/3286#issuecomment-595011324) Thank you @jrmurad
> 
> `jest.mock('@storybook/core/server', () => ({ toRequireContext: require('@storybook/core/dist/server/preview/to-require-context').toRequireContext }));`
> 
> Also here is a great article that helped me a lot finding memory leaks : https://chanind.github.io/javascript/2019/10/12/jest-tests-memory-leak.html

@vidal7 
where did you exactly add this line
jest.mock('@storybook/core/server', () => ({ toRequireContext: require('@storybook/core/dist/server/preview/to-require-context').toRequireContext }));

is it inside the index.spec.js before the initStoryshot()?

**Comment by vidal7** [comment] 2022-05-31 15:28
@dheerajk02 , in a jest setup file

https://jestjs.io/docs/configuration#setupfiles-array

**Comment by ndelangen** [comment] 2023-01-17 22:42
It's been changed to https://github.com/storybookjs/storybook/blob/af0578d99ca3972d01700d7b4aa8c7f2de49ab5e/code/addons/storyshots-core/src/frameworks/configure.ts#L11

Which -I think- solved the issue..

**Closed by ndelangen** 2023-01-17 22:42 UTC
Labels: help wanted, addon: storyshots, performance issue, todo
