### ISSUE TITLE
@storybook/svelte renders all stories simultaneously?

### ISSUE THREAD

**Issue by gersomvg** [storybookjs/storybook#13351] opened 2020-12-01 13:00 UTC
It seems like @storybook/svelte does an initial render of all stories, even the ones that aren't actively shown?

I have a Svelte component that is doing this:

```
export let showNativeCursor = false;

$: document.body.style.cursor = showNativeCursor ? 'initial' : 'none';

onDestroy(() => {
    document.body.style.cursor = 'initial';
});
```

and it is causing the cursor to be hidden on all stories..

**Comment by BlackFenix2** [comment] 2020-12-01 16:17
@gersomvg the svelte components are rendered inline of a story, when you target document.body that applies to the entire DOM versus just the svelte component. 

Ill try to replicate this issue with the svelte storybook example. do you have a repo i could look at as well? it would help me identify a specific bug to fix.

**Comment by gersomvg** [comment] 2020-12-01 19:05
@BlackFenix2 Thanks for chiming in! On the docs page that makes sense, but in the default view there is only 1 iframe visible with just 1 story at a time. In that case I would expect the active story to not be influenced by other stories. But if this is by design, I'll try to work around this by setting the default prop values differently in the stories.

**Comment by BlackFenix2** [comment] 2020-12-01 20:21
i see what is happening, when you called 'document.body.style.cursor' you were targeting the iFrame with the id "storybook-preview-iframe". that is why each iframe in your story has no cursor, its targeting all the iframes with the same id.


the issue is showNativeCursor is always set to false, you are directly assigning a value to a reactive declaration. you should change the showNativeCursor property for your intended use case.

try the refactor below: see if that helps
```js
export let showNativeCursor = false;

$: document.body.style.cursor = showNativeCursor ? 'initial' : 'none';


onDestroy(() => {
    showNativeCursor = true;
});
```

you could add the cursor logic on an onMount lifecycle event, get a ref of the current iframe only to prevent bleeding onto other storybook components.

**Comment by BlackFenix2** [comment] 2020-12-02 15:56
@gersomvg I looked further into this, I added your code snippet into a svelte component and I cannot replicate this issue. you might have your svelte component on the first story rendered when storybook starts up. 

ill close this issue since this doesn't appear to be a storybook/svelte specific bug. You can reach out to us on discord if you need code assistance: https://discord.gg/kkApMQvv.

**Closed by BlackFenix2** 2020-12-02 15:56 UTC
Labels: app: svelte, help wanted, question / support

**Comment by gersomvg** [comment] 2020-12-03 11:00
Thanks, I appreciate you taking the time to have a look at this! It's a good thing you can't replicate the issue, because that means the solution is hopefully on my side :)

I didn't have the time to dig in further yesterday, I'll try so later this week and report back here.

**Comment by gersomvg** [comment] 2020-12-03 12:45
This error seems only to be triggered if using addon-docs. Otherwise it works 🤷

I'm also running into other issues related to using bind:this or bind:propery on components not working, when enabling addon-docs.

Could this be due to automatic addon-docs argTypes inference? @BlackFenix2 

Is there a way to use addon-docs without the automatic argTypes inference?

**Comment by aldrino** [comment] 2021-08-18 11:00
@gersomvg - Were u able to figure the issue with not being able to `bind:this` or `bind.property` on components?

**Comment by gersomvg** [comment] 2021-08-18 13:28
@aldrino We built our own Storybook alternative for use with our Svelte components 🙊
