### ISSUE TITLE
Customizing the page title no longer possible?

### ISSUE THREAD

**Issue by chadlavi-casebook** [storybookjs/storybook#14726] opened 2021-04-26 20:40 UTC
I have been using [this method](https://github.com/storybookjs/storybook/issues/812#issuecomment-610154066) until recently to set a custom page title in storybook, but sometime in the last few releases it seems to have been broken by changes in storybook.

Is there some other, officially supported, means of changing the page title that I should use instead? If not, does anyone know a workaround that still works properly?

**Comment by steffchep** [comment] 2021-08-25 07:52
I would like to ask the same. Ideally, a template to use for each page i.e. "Components/${name} - My Awesome Design Site"

**Comment by shilman** [comment] 2021-08-31 16:36
cc @MichaelArestad

**Comment by dimitrieh** [comment] 2022-02-28 00:18
@ndelangen do you have any update on this? 

When referencing the storybook website URL on for example Jira it converts to a title preview badge that continues to show "Storybook" Not the configured custom title of the referenced page. 

Also, when you watch closely, when the website loads, you see the title of the page change multiple times... I'd say we have landed at an unideal implemented solution 🤔 .

Any insights or help regarding this matter would be welcome 🙏

**Comment by shilman** [comment] 2023-06-08 04:07
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

**Closed by shilman** 2023-06-08 04:07 UTC
Labels: bug, ui

**Comment by artursopelnik** [comment] 2024-12-11 12:26
Here you could find a solution:
https://github.com/storybookjs/storybook/issues/6339#issuecomment-2535833584
