### ISSUE TITLE
Arg changes reset component state

### ISSUE THREAD

**Issue by jonrimmer** [storybookjs/storybook#12960] opened 2020-10-30 11:44 UTC
**Describe the bug**

The [documentation for args](https://storybook.js.org/docs/react/writing-stories/args) says that "When an arg’s value is changed, the component re-renders", but that does not seem to be what happens. Instead of re-rendering, the whole story/component appears to be re-instantiated from scratch, losing any existing state in the process.

**To Reproduce**

1. Run the following story:

```tsx
export const Test: Story<{ count: number }> = args => {
  const [yes, setYes] = useState(false);
  useEffect(() => {
    console.log('Initalised');
  }, []);
  return (
    <div>
      <p>{yes ? 'Yes' : 'No'}</p>
      <p>Count: {args.count}</p>
      <p>
        <button onClick={() => setYes(!yes)}>Toggle</button>
      </p>
    </div>
  );
};

Test.args = {
  count: 0,
};
```

2. Click on "Toggle" to change "No" to "Yes".
3. Change the value of the `count` arg.
4. See that the value of `yes` gets reset to `false`.
5. Check the console and see that the init effect has been re-run.

**Expected behavior**

The story should retain the value of `yes` as `true`. The init effect should only be run once, when the story is first loaded.

**Code snippets**

See above.

**System**
```
Environment Info:

  System:
    OS: macOS
  Binaries:
    Node: 13.8.0 - ~/.nvm/versions/node/v13.8.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.13.6 - ~/.nvm/versions/node/v13.8.0/bin/npm
  Browsers:
    Chrome: 86.0.4240.111
    Firefox: 82.0
    Safari: 14.0
```

**Additional context**

**Comment by shilman** [comment] 2020-11-01 07:04
cc @tmeasday

**Comment by tmeasday** [comment] 2020-11-04 00:32
@jonrimmer are you using any decorators which render the story via JSX? (`<StoryFn />`).

If so this is a dupe of https://github.com/storybookjs/storybook/issues/12255 and a workaround is to just use `StoryFn()`.

**Comment by jonrimmer** [comment] 2020-11-04 12:29
@tmeasday Ah, yes, we are. That'll be it then. Thanks.

**Comment by tmeasday** [comment] 2020-11-04 23:47
Ok, I'm going to close this (and look at that issue again really soon!)

**Closed by tmeasday** 2020-11-04 23:47 UTC
Labels: args, question / support

**Comment by morgs32** [comment] 2020-11-13 01:46
@tmeasday this seems to be an issue without decorators. Here is some logging in the `react-ts-essentials` example: 
https://github.com/morgs32/storybook/tree/next/examples/cra-ts-essentials

**Comment by morgs32** [comment] 2020-11-13 01:47
When you call `reactDOM.render()` with new args it doesn't automatically rerender?
https://github.com/storybookjs/storybook/pull/13069/files#diff-4ff35b6b89e790db308e2624d4187ab9a4cbc01bb54f92c0a0095f7b11a01189L10

**Comment by tmeasday** [comment] 2020-11-13 03:36
@morgs32 it does too have a decorator ;):

https://github.com/morgs32/storybook/blob/94b46dcecab629508b16c805fcd6c650b40090bf/examples/cra-ts-essentials/.storybook/preview.js#L7

> When you call reactDOM.render() with new args it doesn't automatically dismount and remount?

Not if the component hasn't changed, no.

**Comment by tunga2cvp** [comment] 2022-03-14 02:07
Im having a similar problem but with angular, anyone have any idea of how i can fix it for angular ?
