### ISSUE TITLE
Addon-docs broken with emotion11

### ISSUE THREAD

**Issue by neilchaudhuri** [storybookjs/storybook#16716] opened 2021-11-17 18:28 UTC
**Describe the bug**

I am building components using Chakra UI, which uses Emotion. When I navigate to the docs tab, it's blank and breaks all stories after you go there. This means once I encounter the error, Storybook is done until you reload (and not a Docs page of course).

<img width="597" alt="Screen Shot 2021-11-17 at 1 24 42 PM" src="https://user-images.githubusercontent.com/1239158/142259926-7026f42d-9f3a-457c-8eb8-920001dc3cd7.png">

**To Reproduce**

[Use this repo](https://github.com/neilchaudhuri/sb-repro) to run Storybook and reproduce

**System**

```
Environment Info:

  System:
    OS: macOS 12.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 16.12.0 - ~/.nvm/versions/node/v16.12.0/bin/node
    npm: 8.1.0 - ~/.nvm/versions/node/v16.12.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.45
    Safari: 15.1
  npmPackages:
    @storybook/addon-a11y: ^6.3.12 => 6.3.12 
    @storybook/addon-essentials: ^6.3.12 => 6.3.12 
    @storybook/addon-links: ^6.3.12 => 6.3.12 
    @storybook/addons: ^6.3.12 => 6.3.12 
    @storybook/react: ^6.3.12 => 6.3.12 
    @storybook/testing-react: 0.0.22 => 0.0.22 
    @storybook/theming: ^6.3.12 => 6.3.12 
```

**Additional context**

Please let me know if I can provide more information.

**Comment by devzeebo** [comment] 2021-12-09 17:42
#7577

https://github.com/storybookjs/storybook/issues/7577#issuecomment-585347137

describes this issue, and eventually concluded that it is caused by two versions of @emotion/styled being installed. Upgrading the @emotion/styled dependency in @storybook/theming (storybook/lib/theming/package.json) should fix the issue for people using emotion v11, but will likely break for users using emotion v10.

**Comment by trescenzi** [comment] 2022-01-24 22:27
I had this issue as well. Was stumped and then checked out `chakra-ui`'s storybook config and their solution seems to have worked for me. [Their main.js](https://github.com/chakra-ui/chakra-ui/blob/main/.storybook/main.js#L23) aliases `@emotion/core` and `@emotion/theming` both to `@emotion/react`. My main.js now looks like this and everything works

```main.js
const path = require('path');

module.exports = {
  webpackFinal: async (config) => {
    // the emotion aliases ensure that only one context is loaded, without it the `useTheme` hook breaks
    // in storybook
    config.resolve.alias = {
      ...(config.resolve.alias ?? {}),
      '@emotion/react': path.resolve('../../node_modules/@emotion/react'),
      '@emotion/styled': path.resolve('../../node_modules/@emotion/styled'),
      '@emotion/core': path.resolve('../../node_modules/@emotion/react'),
      'emotion-theming': path.resolve('../../node_modules/@emotion/react'),
    };

    return config;
  },
}
```

**Comment by devzeebo** [comment] 2022-01-28 16:07
https://github.com/eirslett/storybook-builder-vite/issues/219 links to:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#emotion11-quasi-compatibility

which mentions the 
```
module.exports = {
  features: {
    emotionAlias: false,
  },
};
```

Which resolves Emotion 11 problem for me (using MUI 5) without the manual webpack aliasing.

**Comment by shilman** [comment] 2022-01-30 15:04
FYI we're working on a fix for this, hopefully available in the next few days

**Comment by shilman** [comment] 2022-02-01 13:35
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.31 containing PR #17000 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2022-02-01 13:35 UTC
Labels: bug, dependencies, has workaround, addon: docs, needs triage, linear
