### ISSUE TITLE
Storybook broken when no React import with new JSX transform from react > 16.14.0

### ISSUE THREAD

**Issue by xavier-villelegier** [storybookjs/storybook#12881] opened 2020-10-23 10:18 UTC
**Describe the bug**
React 16.14.0 introduced the [new JSX transform](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#whats-a-jsx-transform), which means you don't have to import React when when you use JSX anymore. Sadly, I am not able to remove any import from the components/stories used in storybook. Did I miss something ? 🤔

**To Reproduce**

1. Create a new React app `npx create-react-app my-app && cd my-app`
2. Check that it's on React > 16.14 (should be)
3. Add storybook `npx sb init`
4. Run storybook `npm run storybook`
5. Remove the `import React from 'react'` from the `.stories.js` or `.js` file of one component and go to the story of this component (you might need to disable the `react/react-in-jsx-scope` eslint rule)
6. It breaks 💥 `React is not defined` 

**Expected behavior**
A beautiful and shiny story ✨ 

**Screenshots**
![image](https://user-images.githubusercontent.com/17592779/96989364-dc5d3000-1525-11eb-834e-239e525c7966.png)

**System**
```
Environment Info:

  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-8557U CPU @ 1.70GHz
  Binaries:
    Node: 14.13.0 - ~/.nvm/versions/node/v14.13.0/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.13.0/bin/npm
  Browsers:
    Chrome: 86.0.4240.111
    Safari: 13.1.2
  npmPackages:
    @storybook/addon-actions: ^6.0.26 => 6.0.26
    @storybook/addon-essentials: ^6.0.26 => 6.0.26
    @storybook/addon-links: ^6.0.26 => 6.0.26
    @storybook/node-logger: ^6.0.26 => 6.0.26
    @storybook/preset-create-react-app: ^3.1.4 => 3.1.4
    @storybook/react: ^6.0.26 => 6.0.26

```

I also tried with storybook `6.1.0-alpha.28`, same results

**Comment by RookY2K** [comment] 2020-10-23 15:09
Problem is with `@storybook/react`. It adds the `@babel/preset-react` preset without the requisite `runtime: 'automatic'` option set. 

This means you cannot just add the `@babel/preset-react` to the `babel` property in your `main.js`. 

A hacky workaround that worked for me:

```javascript
// main.js
module.exports = {
  // ...
  babel: async (options) => {
    const reactPresetIndex = options.presets.findIndex((preset) => preset.includes('preset-react'));
    const presetsWithoutReact = [
      ...options.presets.slice(0, reactPresetIndex),
      ...options.presets.slice(reactPresetIndex + 1),
    ];

    return {
      ...options,
      presets: [
        [
	  '@babel/preset-react', {
	    runtime: 'automatic',
	  },
	],
        ...presetsWithoutReact
      ],
    };
  },
};
```

**Comment by shilman** [comment] 2020-10-23 17:14
What are the implications of building this option into storybook? Would it be a breaking change?

**Comment by RookY2K** [comment] 2020-10-23 17:20
This depends on how `React` versions without the new jsx transforms would handle the 'automatic' runtime. I'd have to do some testing to figure that out. Don't have the time at the moment, but if no one else has confirmed this by the time I roll back around, I can check.

**Comment by matamatanot** [comment] 2020-10-24 15:01
Create React App, Next.js and Gatsby have already supported new JSX transform.

https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#create-react-app

**Comment by shilman** [comment] 2020-10-24 15:11
Looks like this is also breaking our CI on CRA4:

```
info => Modifying Create React App rules.
info => Using default Webpack setup.
info => Compiling preview..
ERR! => Failed to build the preview
ERR! 
ERR! src/App.js
ERR!   Line 6:5:    'React' must be in scope when using JSX  react/react-in-jsx-scope
ERR!   Line 7:7:    'React' must be in scope when using JSX  react/react-in-jsx-scope
ERR!   Line 8:9:    'React' must be in scope when using JSX  react/react-in-jsx-scope
ERR!   Line 9:9:    'React' must be in scope when using JSX  react/react-in-jsx-scope
ERR!   Line 10:16:  'React' must be in scope when using JSX  react/react-in-jsx-scope
ERR!   Line 12:9:   'React' must be in scope when using JSX  react/react-in-jsx-scope
```

https://app.circleci.com/pipelines/github/storybookjs/storybook/14162/workflows/7f23260d-a9ce-445b-92fd-c15fd98b97c7/jobs/269075

**Comment by RichardVoyles09** [comment] 2020-10-24 15:19
Matthew,

In regards to a computer/ laptop that’s not going to be an option mine recently broke, and on anyone who else is involved could be storybooks.

But I look forward to our call, and the savings plan is right, just don’t understand why I have so many accounts open

Richard Voyles


Richard Voyles

**Comment by shilman** [comment] 2020-10-26 15:48
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-alpha.30 containing PR #12899 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment] 2020-10-26 15:50
NOTE: this is hopefully fixed in 6.1 ☝️ . We need to get it back into the stable release, but are having problems with repros in CI. In the meantime if people can upgrade to 6.1 to test it out, please give it a try and report back:

```
npx sb upgrade --prerelease
```

If it doesn't work right away, try removing regenerating lockfiles.

**Comment by RookY2K** [comment] 2020-10-26 18:58
Upgrading to latest alpha fixed my issue. Will now patiently wait until the fix gets merged into the stable release.

Thanks!

**Comment by DiFuks** [comment] 2020-10-28 17:20
I have a similar problem in browser console:

`ReferenceError: _jsx is not defined`

My packages versions:
```
{
    "@storybook/addon-docs": "^6.1.0-alpha.31",
    "@storybook/react": "^6.1.0-alpha.31",
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
}
```

main.js file:

```
module.exports = {
  stories: ['../src/components/**/*.stories.tsx'],
  addons: ['@storybook/addon-docs'],
  webpackFinal: (config) => {
    config.resolve.plugins.push(new TsconfigPathsPlugin());

    return config;
  }
};
```

**Comment by nandosangenetto** [comment] 2020-10-29 19:23
I'm getting the same error that @DiFuks is getting, `_jsx is not defined`.

![image](https://user-images.githubusercontent.com/7468379/97622265-c3132280-1a02-11eb-8ddb-5158a4ca6ff2.png)

I've created a small repo where you can reproduce this bug: https://github.com/nandosangenetto/storybook-bug-repro

I've tried to remove all addons, as @DiFuks did, but it didn't work.

**Comment by shilman** [comment] 2020-10-29 23:49
@DiFuks are you also using styled components?

**Comment by shilman** [comment] 2020-10-29 23:52
I've opened a separate issue for this @nandosangenetto @DiFuks #12952

**Comment by DiFuks** [comment] 2020-10-30 00:22
> @DiFuks are you also using styled components?

No, I don't use styled-components.

Also, I commented out the addons again. And the error hasn't gone away. So, the problem is @storybook/react

**Comment by sibelius** [comment] 2020-11-12 13:49
fixed for us on v6.1.0-rc.0

**Comment by shilman** [comment] 2020-11-13 02:44
I'm closing this and will follow up on #12952

**Closed by shilman** 2020-11-13 02:44 UTC
Labels: P0, app: react, babel / webpack, bug, has workaround

**Comment by Fernando-Marquardt** [comment] 2020-12-31 22:18
> Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-alpha.30 containing PR #12899 that references this issue. Upgrade today to the `@next` NPM tag to try it out!
> 
> ```
> npx sb upgrade --prerelease
> ```
> 
> Closing this issue. Please re-open if you think there's still more to do.

This doesn't seems to work with Yarn 2. I am not getting the runtime: 'automatic', even with React 17 and react/jsx-runtime being present and that is probably because of the paths used may not be working with Yarn (Yarn 2 does not store files in node_modules but zipped in its .yarn/cache instead).

**Comment by juuyan** [comment] 2021-01-30 17:32
@shilman 
Is is fixed? I still have this issue with the following stack:
`storybook:6.1.15`,`react:17.0.1`,`next:10.0.5`,`Yarn Berry, PnP`

**Comment by shilman** [comment] 2021-01-30 21:31
@gaetanmaisse  any thoughts on yarn 2 compat?

**Comment by Xerkus** [comment] 2021-02-06 08:36
#12899 Added support for new JSX transform and it is included in 6.1 release, however implementation depends on file location with node_modules that prevents it from working with yarn pnp.

CRA uses resolve without specifying paths and it works.
https://github.com/facebook/create-react-app/blob/282c03f9525fdf8061ffa1ec50dce89296d916bd/packages/react-scripts/config/webpack.config.js#L79-L85

Is there something special in storybook setup?

**Comment by TeemuKoivisto** [comment] 2021-04-13 12:45
For any sorry soul who wandered here to fix that pesky `ModuleNotFoundError: Module not found: Error: Can't resolve 'react/jsx-runtime'` error, in my case I was too unfamiliar with the storybook configuration that I didn't notice that it existed in a different spot, away from the root of the project where all the other webpack configs laid. So, heading to `stories/config/webpack.config.js` I finally found the config and added the alias:

```js
  config.resolve.alias = {
    // react: require.resolve('react'),
    'react/jsx-runtime': require.resolve('react/jsx-runtime'),
    'react-dom': require.resolve('react-dom'),
    'react-hot-loader': require.resolve('react-hot-loader'),
    'styled-components': require.resolve('styled-components'),
  }
```

Which actually required me to comment out the react alias. I'm not quite sure why, but it seems to have conflicted with the jsx runtime. Interesting behavior, indeed. Hopefully it now works.

**Comment by renet** [comment] 2021-07-12 21:16
Hi, I still run into this issue after I used `npx react-codemod update-react-imports`. I'm not sure what information to provide - or if it's better to open a new issue. But actually it's pretty much the same problem that is described in this issue, except for I'm already using the latest (not next) SB version with React 17.0.2.

I applied the solution that @RookY2K suggested: https://github.com/storybookjs/storybook/issues/12881#issuecomment-715401423 - Is this still necessary with SB@6.3.4?

I also followed the instructions from @shilman here: https://gist.github.com/shilman/8856ea1786dcd247139b47b270912324#upgrading-from-webpack-4

My main.js looks as follows:

```js
const postcss = require("postcss");

module.exports = {
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    {
      name: "@storybook/addon-postcss",
      options: {
        postcssLoaderOptions: {
          implementation: postcss,
        },
      },
    },
  ],
  babel: async (options) => ({
    ...options,
    presets: [
      ...options.presets,
      [
        "@babel/preset-react",
        {
          runtime: "automatic",
        },
        "preset-react-jsx-transform",
      ],
    ],
  }),
  core: {
    builder: "webpack5",
  },
  stories: ["../src/**/*.stories.@(js|jsx|ts|tsx|mdx)"],
  typescript: {
    // TODO: remove as soon as bug is fixed in react-docgen-typescript
    reactDocgen: "react-docgen",
  },
  webpackFinal: async (cfg) => {
    const config = cfg;
    config.module.rules[0].exclude = [/node_modules\/(?!(gatsby)\/)/];
    config.module.rules[0].use[0].loader = require.resolve("babel-loader");
    config.module.rules[0].use[0].options.presets = [
      require.resolve("@babel/preset-react"),
      require.resolve("@babel/preset-env"),
    ];
    config.module.rules[0].use[0].options.plugins = [
      require.resolve("@babel/plugin-proposal-class-properties"),
      require.resolve("babel-plugin-remove-graphql-queries"),
    ];
    config.resolve.mainFields = ["browser", "module", "main"];
    config.module.rules.push({
      test: /\.(ts|tsx)$/,
      loader: require.resolve("babel-loader"),
      options: {
        presets: [["react-app", { flow: false, typescript: true }]],
        plugins: [
          require.resolve("@babel/plugin-proposal-class-properties"),
          require.resolve("babel-plugin-remove-graphql-queries"),
        ],
      },
    });
    config.resolve.extensions.push(".ts", ".tsx");
    return config;
  },
};
```

Dependencies in package.json:

```json
  "dependencies": {
    "@fontsource/libre-baskerville": "^4.2.2",
    "@fontsource/open-sans": "^4.2.2",
    "@headlessui/react": "^1.1.1",
    "@mdx-js/mdx": "^1.6.22",
    "@mdx-js/react": "^1.6.22",
    "@react-google-maps/api": "^2.2.0",
    "@react-icons/all-files": "^4.1.0",
    "axios": "^0.21.1",
    "eslint-config-airbnb-typescript": "^12.3.1",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-react": "^7.22.0",
    "eslint-plugin-react-hooks": "^4.2.0",
    "firebase": "^8.3.3",
    "firebase-admin": "^9.6.0",
    "gatsby": "^3.0.3",
    "gatsby-plugin-firebase": "*",
    "gatsby-plugin-google-analytics": "^3.0.0",
    "gatsby-plugin-image": "^1.5.0",
    "gatsby-plugin-react-helmet": "^4.0.0",
    "gatsby-plugin-sharp": "^3.5.0",
    "gatsby-plugin-sitemap": "^4.1.0",
    "gatsby-source-filesystem": "^3.5.0",
    "gatsby-source-storyblok": "renet/gatsby-source-storyblok",
    "gatsby-transformer-sharp": "^3.5.0",
    "got": "^11.8.2",
    "jotai": "^0.16.3",
    "node-fetch": "^2.6.1",
    "nodemailer": "^6.5.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-helmet": "^6.1.0",
    "react-markdown": "^6.0.2",
    "storyblok-js-client": "^4.0.9",
    "storyblok-react": "^0.1.2"
  },
  "devDependencies": {
    "@babel/core": "^7.13.14",
    "@babel/preset-typescript": "^7.13.0",
    "@storybook/addon-actions": "^6.3.4",
    "@storybook/addon-essentials": "^6.3.4",
    "@storybook/addon-links": "^6.3.4",
    "@storybook/addon-postcss": "^2.0.0",
    "@storybook/addon-storyshots": "^6.3.4",
    "@storybook/builder-webpack5": "^6.3.4",
    "@storybook/manager-webpack5": "^6.3.4",
    "@storybook/react": "^6.3.4",
    "@types/googlemaps": "^3.43.3",
    "@types/grecaptcha": "^3.0.1",
    "@types/jest": "^26.0.22",
    "@types/nodemailer": "^6.4.1",
    "@types/react-helmet": "^6.1.0",
    "@typescript-eslint/eslint-plugin": "^4.16.1",
    "@typescript-eslint/parser": "^4.16.1",
    "@vercel/node": "^1.9.1",
    "autoprefixer": "^10.2.5",
    "babel-jest": "^26.6.3",
    "babel-loader": "^8.2.2",
    "babel-preset-gatsby": "^1.2.0",
    "babel-preset-react-app": "^10.0.0",
    "cssnano": "^5.0.2",
    "dotenv": "^9.0.2",
    "eslint": "^7.21.0",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-tailwind": "^0.2.1",
    "gatsby-plugin-postcss": "^4.0.0",
    "html-webpack-plugin": "^5.3.1",
    "husky": "^6.0.0",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^26.6.3",
    "postcss": "^8.2.15",
    "postcss-import": "^14.0.0",
    "prettier": "^2.3.0",
    "tailwindcss": "^2.2.4",
    "tailwindcss-interaction-variants": "^5.0.0",
    "typescript": "^4.2.3"
  }
```

And also I used `npm install --force` to bypass the incompatible peer dependency version range for `react@17` with `npm@7`. But before removing the React import from my files, everything worked fine, even with `react@17`. Gatsby works fine without the React imports, btw.

Can anyone please help me tracking this down, please? :)

**Comment by jam-awake** [comment] 2022-10-06 22:42
I'm pretty sure the fix here was only for the Preview, not the Manager. I've written a custom addon that uses React in the Manager and ran into the same problem here.

**Comment by jam-awake** [comment] 2023-02-02 14:57
@sigginjals Yeah. I needed to add `runtime: "automatic"` to React's preset option in the manager's webpack config:
```js
modul.exports = {
  ...
  managerWebpack: (c) =>
     setReactRuntimeAutomatic(c),
};
  
const modifyConfigModuleRules = (fn) => (config) => {
  return {
    ...config,
    module: {
      ...config.module,
      rules: fn(config.module.rules),
    },
  };
};

const setReactRuntimeAutomatic = modifyConfigModuleRules((rules) => {
  return rules.reduce((acc, next) => {
    if (
      isNonNullObjectWithField(next, "use") &&
      isNonNullArray(next.use) &&
      next.use[0] &&
      isNonNullObjectWithField(next.use[0], "options") &&
      isNonNullObjectWithField(next.use[0].options, "presets")
    ) {
      const presets = next.use[0].options.presets;
      next.use[0].options.presets = presets.reduce((pAcc, pNext) => {
        if (
          typeof pNext === "string" &&
          pNext.includes("manager-webpack5") &&
          pNext.includes("preset-react")
        ) {
          pAcc.push([pNext, { runtime: "automatic" }]);
        } else {
          pAcc.push(pNext);
        }
        return pAcc;
      }, []);
    }
    acc.push(next);
    return acc;
  }, []);
});
```

**Comment by ernestostifano** [comment] 2023-04-28 12:46
Hi @shilman, unfortunately this is still an issue for Storybook Manager (using Storybook v7). If React is not explicitly imported when creating a custom panel, the whole app breaks.

**Comment by MihaMixFromGB** [comment] 2024-02-29 04:23
I'm using Vite and **@vitejs/plugin-react** helped me.
```
//vite.config.ts
import react from '@vitejs/plugin-react';

export default defineConfig({
  ...
  plugins: [ react({ jsxRuntime: 'automatic' }) ],
  ...
});
```
