### ISSUE TITLE
Storybook cant resolve dependency

### ISSUE THREAD

**Issue by AasmundEndresen** [storybookjs/storybook#13166] opened 2020-11-18 21:53 UTC
**Describe the bug**
Using the steps to install storybook described in the documentation doesnt work

**To Reproduce**
Run `npx create-react-app some-app-name`
Enter project
Run ``npx sb init`

**Expected behavior**
Storybook will be installed in my project and I'm ready to start coding

**Actual behavior**
`Found: react@17.0.1`
`Could not resolve dependency: peer react@16.8.0 from @storybook/addon-essentials@6.0.28`

**System**
OS: Linux 4.19 Ubuntu 20.04.1 LTS (Focal Fossa)
CPU: (4) x64 Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
Node: 15.0.0
NPM: 7.0.2

**Additional context**
I have tried running the command with the ``--legacy-peer-deps` flag as suggested in the error msg which results in `èrror: unkown option '--legacy-peer-deps'`, also the ``--no-dll` flag as suggested on other issues with the same result.  I also see there is a number of closed issues regarding the same problem that range from 2+ weeks old to more that were closed with the comment this is a duplicate of another issue that when I followed the link seems nothing like this issue, and one where its commented that this should be fixed in the next build - over 2 weeks ago...  When is this next build coming?

**Comment by AasmundEndresen** [comment] 2020-11-18 21:55
Also the Discord link provided in docs doesnt work.

**Comment by shilman** [comment] 2020-11-19 00:09
@AasmundEndresen We release new builds almost every day in the 6.1 `next` npm tag. Releasing 6.1 this week.

Which discord link is broken?

**Comment by niconicoj** [comment] 2020-11-19 10:11
I'm encountering the same problem on a create-react-app with typescript.

I tried to init from the next npm tag and I get this :
```
WARN ERESOLVE overriding peer dependency
npm ERR! Cannot read property 'length' of undefined
```

System
OS: Microsoft Windows 10 Home 
CPU: Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
Node: 15.2.0
NPM: 7.0.8

**Comment by niconicoj** [comment] 2020-11-19 10:30
Looks like the installation is broken with npm-based project. I managed to install on a yarn-based project without issues.

Looking wuickly at the CI, I don't see anything related to npm. I don't know ifstorybook intends to deprecate npm, nevertheless I think I should be mentioned somewhere that you should at least prefer using yarn with sotrybook rather that npm.

**Comment by shilman** [comment] 2020-11-19 11:20
@AasmundEndresen 6.1 has been released so this shouldn't be a problem anymore. I noticed you and @niconicoj are both using npm@7.0.x so I'm closing this as a dupe of #12983

**Closed by shilman** 2020-11-19 11:20 UTC
Labels: app: react, bug, duplicate, yarn / npm

**Comment by shilman** [comment] 2020-11-19 11:21
@niconicoj we fully support npm, but there are issues with npm@7 which was just released with breaking changes and we're still figuring those out.
