### ISSUE TITLE
Tab order of addons is incorrect

### ISSUE THREAD

**Issue by aryyya** [storybookjs/storybook#10073] opened 2020-03-07 02:22 UTC
The [documentation says](https://storybook.js.org/docs/addons/using-addons/#addons-tab-order) the tab order of addons appears in a the order that they are declared:

> The tab order is created by order in which they appear in the array in the main.js file.

My declaration order is "knobs", "storysource":

```javascript
// main.js

module.exports = {
    stories: [
        '../../src/**/*.stories.js'
    ],
    addons: [
        '@storybook/addon-knobs/register',
        '@storybook/addon-storysource'
    ]
};
```

As you can see the tabs don't appear in that order:

<img width="194" alt="Demonstration" src="https://user-images.githubusercontent.com/29365565/76134876-d6d2ca00-5fd6-11ea-9d7c-e9f5bbf490e8.png">

Package versions:

```
        "@storybook/addon-knobs": "^5.3.14",
        "@storybook/addon-storysource": "^5.3.14",
        "@storybook/react": "^5.3.14",
```

**Comment by shilman** [comment] 2020-03-07 02:50
Possible duplicate of #9819

**Comment by shilman** [comment] 2020-04-06 00:49
Closing as dupe to #9819

**Closed by shilman** 2020-04-06 00:49 UTC
Labels: bug, ui
