### ISSUE TITLE
build-storybook ignores -o output option

### ISSUE THREAD

**Issue by Jakobud** [storybookjs/storybook#13700] opened 2021-01-21 22:14 UTC
**Describe the bug**
According to the documentation (https://storybook.js.org/docs/html/workflows/publish-storybook) I should be able to specify the output directory when publishing storybook to static files:

`$ npm run build-storybook -o ./path/to/output`

But when I do this, it ignores the `-o` and outputs to `./storybook-static` directory every time.

**Expected behavior**
It outputs static files to the specified directory.

**System**
Please paste the results of `npx sb@next info` here.
```
    OS: Windows 10 10.0.18363
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    @storybook/addon-actions: ^6.1.14 => 6.1.14
    @storybook/addon-essentials: ^6.1.14 => 6.1.14
    @storybook/addon-links: ^6.1.14 => 6.1.14
    @storybook/html: ^6.1.14 => 6.1.14
```

**Comment by jeffreymoelands** [comment] 2021-01-26 14:40
+1

**Comment by jeffreymoelands** [comment] 2021-01-26 14:49
https://github.com/storybookjs/storybook/issues/10570

**Comment by gaetanmaisse** [comment] 2021-02-03 20:19
Closing as a duplicate of #10570

**Closed by gaetanmaisse** 2021-02-03 20:19 UTC
