### ISSUE TITLE
Babel config incorrectly read (inaccurate docs + incorrect loading of Babel config functions)

### ISSUE THREAD

**Issue by timhwang21** [storybookjs/storybook#12745] opened 2020-10-12 16:38 UTC
**Describe the bug**
Same issue as #11218 is still present in `6.0.26`. Refiling a ticket based on the Stale bot's suggestion.

**To Reproduce**

Same as #11218. In summary:

1. In a Typescript project, declare a non-type-only namespace
1. See that both application and Storybook fails with an error on the namespace
1. In Babel, set `allowNamespaces` to `true` in the Typescript settings
1. See that the application no longer errors
1. See that Storybook still errors

I'm currently investigating why this particular Babel option seems to not be getting picked up by Storybook.

**System**

```
Environment Info:

  System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.7.0 - /usr/local/bin/node
    Yarn: 1.21.0 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.121
    Firefox: 81.0.1
    Safari: 14.0
  npmPackages:
    @storybook/addon-actions: ^6.0.26 => 6.0.26
    @storybook/addon-essentials: ^6.0.26 => 6.0.26
    @storybook/addon-links: ^6.0.26 => 6.0.26
    @storybook/react: ^6.0.26 => 6.0.26
```

**Comment by timhwang21** [comment] 2020-10-12 16:54
I investigated this further, and there appear to be two (fairly minor) problems.

# 1. The docs are inaccurate as to how Babel configs are picked up.

https://github.com/storybookjs/storybook/blob/next/docs/configure/babel.md#custom-config-file

> If your project has a .babelrc file, we'll use that instead of the default config file.
> 
> You can also place a .storybook/.babelrc file to use a special configuration for Storybook only.

This isn't accurate. See [this comment](https://github.com/storybookjs/storybook/blob/next/lib/core/src/server/utils/load-custom-babel-config.js#L69) in the code. 

**Suggested fix:** Specify that only Babel configs nested in `.storybook/` will be read.

# 2. Babel configs written using the [config function API](https://babeljs.io/docs/en/config-files#config-function-api) are not read properly.

Babel supports dynamic configs by exporting a function taking a single argument `api` in `babel.config.js`. However, Storybook doesn't properly handle these. [This line](https://github.com/storybookjs/storybook/blob/next/lib/core/src/server/utils/load-custom-babel-config.js#L47) coerces the function into an empty object.

**Suggested fix:** If `config instanceof Function`, pass the function unchanged to Babel.

**Comment by armandabric** [comment] 2021-06-30 14:05
The comment that explain the issue is now here:

https://github.com/storybookjs/storybook/blob/cc0550ca434121548e5c418210530bf46c35c89b/lib/core-common/src/utils/load-custom-babel-config.ts#L72-L78

**Comment by shilman** [comment] 2021-08-31 17:16
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-alpha.33 containing PR #15928 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2021-08-31 17:16 UTC
Labels: bug, help wanted, babel / webpack, small
