### ISSUE TITLE
[Bug]: Values are incorrectly passed through the url in a new window

### ISSUE THREAD

**Issue by inspector-code** [storybookjs/storybook#24039] opened 2023-09-01 09:17 UTC
### Describe the bug

If you change the primary argument from false to true, it will still be false. For example:

http://localhost:6007/iframe.html?args=primary:!false&id=example-button--primary&viewMode=story - will be false
http://localhost:6007/iframe.html?args=primary:!true&id=example-button--primary&viewMode=story - will be false too

**Comment by sonallux** [comment] 2023-11-06 11:18
I experience the same issue. When I open the iframe using the "Open canvas in new tab" button, I am also getting an URL where boolean values are prefix with `!`. But when I manually remove the `!` in the URL then boolean parameters are respected and everything works as expected.

**Comment by vanessayuenn** [comment] 2023-12-28 11:39
I think this is a dupe of #25035

**Closed by vanessayuenn** 2023-12-28 11:39 UTC
Labels: bug, needs triage
