### ISSUE TITLE
React native fast refresh causes error when reloading

### ISSUE THREAD

**Issue by Mnjaro** [storybookjs/storybook#8734] opened 2019-11-06 09:28 UTC
**Describe the bug**
When activating fast refresh on the device, modifying a story may (not all the time) cause the app to crash and display the following error :

`Type Error: JSON.stringify cannot serialize cyclic structures`
 If I disable fast refresh and reload the app manually (double r tap) it then works

**To Reproduce**

1. Enable Fast Refresh
2. Modify story code
3. Error pops up

**Code snippets**
Here is an example of the story based on the one generated by the sb cli:
```
import React from 'react';
import { Text } from 'react-native';

import { storiesOf } from '@storybook/react-native';
import { action } from '@storybook/addon-actions';
import { linkTo } from '@storybook/addon-links';

// eslint-disable-next-line import/extensions
import Button from './Button';
import CenterView from './CenterView';
import Welcome from './Welcome';

storiesOf('Welcome', module).add('to Storybook', () => (
  <Welcome showApp={linkTo('Button')} />
));

storiesOf('Button', module)
  .addDecorator(getStory => <CenterView>{getStory()}</CenterView>)
  .add('with text', () => (
    <Button onPress={action('clicked-text')}>
      <Text>Hello Button</Text>
    </Button>
  ))
  .add('with some emoji', () => (
    <Button onPress={action('clicked-emoji')}>
      <Text>😀 😎 👍 💯</Text>
    </Button>
  ));

```

**System:**
```

    OS: Linux 5.3 Arch Linux undefined
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 12.2.0 - ~/.nvm/versions/node/v12.2.0/bin/node
    Yarn: 1.19.1 - /usr/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.2.0/bin/npm
  Browsers:
    Firefox: 70.0.1
  npmPackages:
    @storybook/addon-actions: ^5.2.5 => 5.2.5 
    @storybook/addon-links: ^5.2.5 => 5.2.5 
    @storybook/addons: ^5.2.5 => 5.2.5 
    @storybook/react-native: ^5.2.5 => 5.2.5 
    @storybook/react-native-server: ^5.2.5 => 5.2.5 
```

**Comment by Gongreg** [comment] 2019-11-06 10:04
Hi, this issue is duplicate of https://github.com/storybookjs/storybook/issues/7916 . Closing in favour of that one.

**Closed by Gongreg** 2019-11-06 10:04 UTC
Labels: app: react-native, bug, help wanted
