### ISSUE TITLE
[Bug]: After upgrade to `7.4.4` browser hangs

### ISSUE THREAD

**Issue by GarrisonD** [storybookjs/storybook#24273] opened 2023-09-22 12:45 UTC
### Describe the bug

I upgraded to the latest version (`7.4.4`) with `npx storybook@latest upgrade` and now it's unusable.

After any interaction (theme switching or trying to visit another story) browser shows me the `Page Unresponsive` modal.

On `7.4.1` everything works like a charm.

### System

```bash
Environment Info:

  System:
    OS: macOS 13.5.2
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 117.0.5938.88
    Firefox: 115.0.3
    Safari: 16.6
```

**Comment by GarrisonD** [comment] 2023-09-22 13:02
Tested with `7.4.3` - no issues 👍

**Comment by sirtobey** [comment] 2023-09-22 13:46
Same issue here.

**Comment by Wymowny** [comment] 2023-09-22 14:04
Same issue, logged in the console every ~500ms:
```
Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
    in Unknown (created by Downshift2)
    in div
    in Unknown (created by Downshift2)
    in div (created by Styled(div))
    in Styled(div) (created by Downshift2)
    in Downshift2
    in Unknown
    in div (created by Styled(div))
    in Styled(div) (created by Spaced)
    in Spaced (created by Styled(Spaced))
    in Styled(Spaced)
    in div (created by ForwardRef(F2))
    in div (created by ForwardRef(F2))
    in ForwardRef(F2) (created by Scroller)
    in Suspense (created by Scroller)
    in Scroller (created by Styled(Scroller))
    in Styled(Scroller)
    in nav (created by Styled(nav))
    in Styled(nav)
    in Unknown
    in Unknown (created by ManagerConsumer)
    in ManagerConsumer
    in Unknown (created by Layout)
    in div (created by Styled(div))
    in Styled(div) (created by Sidebar)
    in Sidebar (created by Layout)
    in Layout (created by WithTheme(Layout))
    in WithTheme(Layout)
    in Unknown (created by App)
    in div (created by Styled(div))
    in Styled(div) (created by App)
    in App
    in ThemeProvider
    in Unknown (created by ManagerConsumer)
    in ManagerConsumer (created by Manager)
    in EffectOnMount (created by Manager)
    in Manager (created by QueryLocation)
    in QueryLocation (created by Main2)
    in Main2 (created by Root4)
    in Router (created by LocationProvider)
    in LocationProvider (created by Root4)
    in HelmetProvider (created by Root4)
    in Root4
```

**Comment by mnicholstamu** [comment] 2023-09-22 18:52
I just moved our storybook back down to 7.4.3 as well and have had zero issues.

**Comment by coding-tomato** [comment] 2023-09-22 22:03
Same issue here, seems like the issue is related to PostCSS, once I remove the addon Storybook works again in 7.4.4

Downgraded to 7.4.3 and started working again, this seems like a pretty big problem affecting all Tailwind users!

**Comment by mnicholstamu** [comment] 2023-09-22 22:04
> Same issue here, seems like the issue is related to PostCSS, once I remove the addon Storybook works again in 7.4.4
> 
> Downgraded to 7.4.3 and started working again, this seems like a pretty big problem affecting all Tailwind users!

I removed the a11y plugin and it seemed to do the trick.

**Comment by coding-tomato** [comment] 2023-09-22 22:43
Pardon me, I meant @storybook/addon-styling rather than PostCSS.

**Comment by terrymun** [comment] 2023-09-23 16:47
We are also experiencing the same issue with 7.4.4, and this is the list of addons we have:

- `@storybook/addon-a11y`
- `@storybook/addon-essentials`
- `@storybook/addon-interactions`
- `@storybook/addon-docs`
- `@storybook/addon-themes`

Removing `@storybook/addon-a11y` did not work for us @mnicholstamu, but when I removed `@storybook/addon-themes` then our storybook preview and build start working again.

Either that, or downgrading back to `7.4.3` also helps :)

**Comment by gregegan** [comment] 2023-09-23 20:05
> We are also experiencing the same issue with 7.4.4, and this is the list of addons we have:
> 
> * `@storybook/addon-a11y`
> * `@storybook/addon-essentials`
> * `@storybook/addon-interactions`
> * `@storybook/addon-docs`
> * `@storybook/addon-themes`
> 
> Removing `@storybook/addon-a11y` did not work for us @mnicholstamu, but when I removed `@storybook/addon-themes` then our storybook preview and build start working again. Do you by any chance have `@storybook/addon-a11y` as the last addon defined in the array?
> 
> Either that, or downgrading back to `7.4.3` also helps :)

I can confirm also that `@storybook/addon-themes` is causing the issue with the browser timeout `Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.`

<img width="1300" alt="image" src="https://github.com/storybookjs/storybook/assets/6665100/b67776ba-1986-4eea-ac3f-8cc159859dd1">

**Comment by codeth** [comment] 2023-09-24 18:39
I'm also hitting this issue.

Based on the error message in the console, I'm guessing it was this change in the `7.4.4` release, because `useEffect` should always have a dependency array, even if it's empty - https://github.com/storybookjs/storybook/pull/24237/files#diff-8e32cce628af3c63ddc47847b2c89d91619bd9ea0ef43b5e2045fbbc70bf4fb8R412

**Comment by MarcelKnobelsdorf** [comment] 2023-09-25 07:57
Its fixed with `7.4.5`
https://github.com/storybookjs/storybook/commit/a3cdabb025524822807318bc137f69be006596c2

**Comment by terrymun** [comment] 2023-09-25 08:28
Thanks @MarcelKnobelsdorf :) Can confirm that `7.4.5` works 🚀

**Comment by mnicholstamu** [comment] 2023-09-25 12:05
That did it! Thank you @MarcelKnobelsdorf.

**Comment by gregegan** [comment] 2023-09-25 22:06
Confirmed! Thank you!

**Closed** 2023-09-28 10:14 UTC
Labels: bug, needs triage
