### ISSUE TITLE
"No Preview" when starting Storybook for the first time

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#15310] opened 2021-06-21 12:57 UTC
**Describe the bug**

Sometimes when running Storybook for the first time of the day, it opens the browser with a "No Preview" error (404 for story url). 
Then you need to switch between stories a couple of times till they are actually rendered.

![image](https://user-images.githubusercontent.com/1671563/122765169-8309f400-d2a0-11eb-9b9d-696da5e8f997.png)

This was once reported in #14376

**To Reproduce**

I believe you can just use `sb repro` and select any framework, then run it for the first time. That should get you to the error. Another way that I found to reproduce a similar behavior is to:

1 - Open a storybook normally (you can use [this deployed one](https://mealdrop.netlify.app/storybook) for experimentation)
2 - Change url to wrong story name
3 - Get the 404 "No preview" screen
4 - When switching stories one time, you see that it won't render correctly (it does load the args though).

My assumption is that sometimes when initialising Storybook, the initial story is not loaded correctly, giving the 404 screen, and then you have this situation where you need to select another story, and still you have the 404 page, until you select a second story, then it works.

https://user-images.githubusercontent.com/1671563/122765405-c2d0db80-d2a0-11eb-8b3b-fa6b4b552538.mp4

**Comment by shilman** [comment] 2021-06-21 13:21
I think the first 404 might be caused by running Storybook on a port you've already run it on in the past, and some kind of caching there. I don't think most users will experience that. The second click concerns me more.

**Comment by shilman** [comment] 2021-06-25 01:53
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-alpha.1 containing PR #15349 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2021-06-25 01:53 UTC
Labels: P0, bug, core, help wanted, small

**Comment by shilman** [comment] 2021-06-28 09:00
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.1 containing PR #15349 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```
