### ISSUE TITLE
Relative URLs to assets no longer work in CSS now that CSS no longer gets inlined

### ISSUE THREAD

**Issue by Vinnl** [storybookjs/storybook#4645] opened 2018-10-30 14:44 UTC
**Describe the bug**
I just upgraded to Storybook 4, and I _think_ this issue is caused by that (it required a lot of other moving parts as well).

Basically, in my React component, I `import './Widget.css';`. Then in `Widget.css`, I reference a background image located in the same folder as such: `background-image: url(orcid_16x16.png);`.

With Storybook 3, this just worked even using `build-storybook`: the image URL was updated to `static/media/orcid_16x16.2dddb203.png`, and since the CSS was inline, this path was correct.

Now with Storybook 4, however, the URL is still updated to that value, but because it is now located in a CSS file that itself located in `static/css`, the browser is now trying to find the image at `static/css/static/media/`, and hence cannot find it.

**To Reproduce**
1. Visit my [built Storybook v3](http://plaudit.pub/components/?knob-Endorsements=%7B%22first-orcid%22%3A%7B%22endorserName%22%3A%22Alice%20Doe%22%2C%22robust%22%3Atrue%7D%2C%22second-orcid%22%3A%7B%22endorserName%22%3A%22Bob%20Doe%22%2C%22robust%22%3Atrue%7D%7D&selectedKind=Widget&selectedStory=With%20one%20endorsement&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)
2. Notice that there is a green icon to the left-hand side of Alice Doe
3. Now visit [that same page in Storybook 4](https://35-migrate-client-to-creat-review.plaudit.pub/components/?selectedKind=Widget&selectedStory=With%20one%20endorsement&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)
4. Notice that the image is missing

**Expected behavior**
The image to also be present in Storybook 4 - presumably by making sure that URL imports are rewritten to be relative to the CSS file they are in.

**Screenshots**

In Storybook 3:
![image](https://user-images.githubusercontent.com/4251/47726302-81f0a800-dc5a-11e8-9d24-ec8f8c685c5c.png)

In Storybook 4:
![image](https://user-images.githubusercontent.com/4251/47726316-8ae17980-dc5a-11e8-9108-fe3e63a1fd30.png)

**System:**
 - OS: Ubuntu Linux 18.04
 - Device: Dell XPS 13 9360
 - Browser: Firefox
 - Framework: React
 - Addons: [if relevant]
 - Version: 4.0.0

**Comment by igor-dv** [comment] 2018-10-31 10:20
Do you have any custom webpack.config?

**Comment by igor-dv** [comment] 2018-10-31 10:30
So the difference in the `awesome-typescript-loader` vs `ts-loader`, right ? 🤔

**Comment by Vinnl** [comment] 2018-10-31 10:37
Yes, as far as the Webpack config is concerned. Though i don't think they do anything with image imports?

**Comment by igor-dv** [comment] 2018-10-31 11:22
Did you try to use SB v4 with the `ts-loader` (to eliminate this problem)? Nothing is changed in png loading in a new release...

**Comment by Vinnl** [comment] 2018-10-31 11:42
Well, I wanted to, but unfortunately I couldn't get it to work - I ran into this error message:

    Module build failed (from ./node_modules/ts-loader/index.js):
    Error: TypeScript emitted no output for <..>/stories/widget.tsx.
    at makeSourceMapAndFinish (<..>/node_modules/ts-loader/dist/index.js:78:15) 
    at successLoader (<..>/node_modules/ts-loader/dist/index.js:68:9)
    at Object.loader (<..>/node_modules/ts-loader/dist/index.js:22:12)

Since the official docs also use `awesome-typescript-loader`, I figured I'd try it with that, and that worked. (I used to use `ts-loader` because my app used that as well, but that is no longer the case.)

**Comment by igor-dv** [comment] 2018-10-31 14:18
BTW, how does your tsconfig look like? 
(I am asking different questions because idk what is the problem 🤷‍♂️ )

**Comment by Vinnl** [comment] 2018-10-31 14:39
Haha, I was afraid so :P 

The `tsconfig.json` is not that special:

```
{
  "compilerOptions": {
    "target": "es5",
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react",
    "lib": ["esnext", "dom"]
  },
  "include": [
    "src"
  ],
  "exclude": [
    "src/setupProxy.js"
  ]
}
```

I don't have a minimal reproduction, but the project this occurs on luckily is open source: [with Storybook 3](https://gitlab.com/Flockademic/plaudit/tree/master/client), [with Storybook 4](https://gitlab.com/Flockademic/plaudit/tree/35-migrate-client-to-create-react-app/client). (Note that there are several projects in that repo - the one with Storybook is located in `/client`.)

**Comment by igor-dv** [comment] 2018-10-31 15:08
You can exclude stories from `tsconfig` and create another one for storybook (`tsconfig.sb.json`) that will extend your regular tsconfig. In this new tsconfig you can remove the `"noEmit": true,` (it could be a root of your initial ts-loader problem). Excluding stories from the `tsconfig` could boost your apps building time.

**Comment by Vinnl** [comment] 2018-10-31 15:41
@igor-dv Hehe, that's what I was doing already - I just mashed them together here for easier display :)

Setting `noEmit: false` did solve `ts-loader` not working. Unfortunately, images are still not loaded :(

**Comment by igor-dv** [comment] 2018-10-31 15:43
Looks like I need to clone the project 😴

**Comment by Vinnl** [comment] 2018-10-31 15:58
Ah don't bother, that's far too much effort! I'll probably be diving into this again tomorrow; who knows, I might get some fresh insights :)

**Comment by igor-dv** [comment] 2018-10-31 15:59
I see that you've migrated to react-scripts as well. We have a feature that integrates styling from the CRA2. 

CC: @chadfawcett , could it be somehow related to this?

**Comment by chadfawcett** [comment] 2018-10-31 17:47
I believe this is because you're switching to CRA. I believe the file paths need to be relative. So change `orcid_16x16.png` to `./orcid_16x16.png`. 

https://facebook.github.io/create-react-app/docs/adding-images-fonts-and-files
https://github.com/facebook/create-react-app/issues/4574#issuecomment-395081558

**Comment by chadfawcett** [comment] 2018-10-31 17:52
Although, I wasn't actually able to replicate the issue. I cloned the repo, checked out the branch, and ran `yarn storybook`. This may be because I'm on MacOS, and it does a bit of magic when it comes to resolving file paths.

![screen shot 2018-10-31 at 10 50 29 am](https://user-images.githubusercontent.com/3250463/47808056-ce8bc000-dcfa-11e8-8281-813969edaf36.png)

**Comment by chadfawcett** [comment] 2018-10-31 19:18
Sorry @Vinnl, I missed the fact that this was specific to built version. 

Looks like it's a bug in the storybook cra webpack preset. I'll try to get a PR in tonight.

**Comment by Vinnl** [comment] 2018-11-01 07:58
That'd be fantastic @chadfawcett. If you have any pointers I'd be happy to take a shot at it myself, if need be :)

**Comment by Vinnl** [comment] 2018-11-01 10:07
Some more observations: CRA successfully turns it into an absolute URL, as can be seen [here](http://35-migrate-client-to-creat-review.plaudit.pub/widget/?pid=doi:10.1101/318345). However, it knows how to do so because [the developer configures at what location the app will be deployed](https://facebook.github.io/create-react-app/docs/deployment#building-for-relative-paths). Given that that location is different for the built Storybook application, I'm not sure how to deal with that other than providing a similar configuration option for Storybook itself.

Though perhaps an alternative is to always inline images as data URLs, given that data use is probably (?) less of an issue for Storybooks. Or, alternatively, not to extract the CSS into separate files at all, like in Storybook 3.

Anyway, I'm not sure if that is desirable from a Storybook point of view, so that's probably best for you to judge.

**Comment by Vinnl** [comment] 2018-11-02 10:11
No problem @chadfawcett, I'm already indebted to you for even trying to fix it, let alone actually doing so :)

Anyway, I saw the PR and was already trying it out - I've just confirmed that it does, indeed, fix the issue :)

**Comment by Vinnl** [comment] 2018-11-06 09:36
Just upgraded to 4.0.4, and it works flawlessly. Thanks!

**Comment by tulsidaskhatri** [comment] 2020-01-30 14:11
I am getting exactly same issue with 
"@storybook/react": "^5.3.7",

css is trying to look for a font file in 
static/css/static/media/myfont.woff2

but the font is at following url:
static/media/myfont.woff2

**Comment by ppiyush13** [comment] 2020-02-02 11:20
I am also facing same issue

**Comment by VinceVachon** [comment] 2020-02-13 22:18
Same "5.3.9",

**Comment by shilman** [comment] 2020-02-14 02:27
@mrmckeb did something change in the CRA preset that might affect this?

**Comment by mrmckeb** [comment] 2020-02-19 08:49
This looks like a conflict between Storybook and CRA's configurations, which is odd. I can take a look at this.

Has anyone got a reproduction they can share with me? Thanks!

**Comment by YDundie** [comment] 2020-03-05 12:23
Same for the version 5.3.13

**Comment by YDundie** [comment] 2020-03-05 15:50
Hello.
Successfully solved it by adding this to my .storybook/main.js

`const path = require('path');

const publicPath = process.env.DEV ? "http://localhost:9009/" :"https://your-web-address.com/"

module.exports = {
	stories: ['../src/**/*.stories.js'],
	addons: [
		'@storybook/preset-create-react-app',
		'@storybook/addon-actions',
		'@storybook/addon-links',
		'@storybook/addon-knobs'],

	webpackFinal: async (config, { configType }) => {
	
		config.output.publicPath=publicPath

		return config;
	},
};

`

Hopefully it could help you.

**Comment by cherouvim** [comment] 2020-03-23 09:34
> Has anyone got a reproduction they can share with me? Thanks!

Hello. This is the most minimal repro I could come up with. Steps:
1. Confirm that the `woff` font file is loading via the network tab:
```
npm install
npm run storybook
```
2. Confirm that font file is not loading (404s due to `static/css/static/media`):
```
npm run static/css/static/media
# view generated index.html
```

[storybook-repro-4645.zip](https://github.com/storybookjs/storybook/files/4368312/storybook-repro-4645.zip)

**Comment by maniax89** [comment] 2020-03-23 15:40
in my project - i was able to remedy this by adding the `"homepage": "."` to my package json -> https://create-react-app.dev/docs/deployment/#serving-the-same-build-from-different-paths

not sure if this helps anyone^

seems like the relevant lines in CRA look something like this (https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpack.config.js):
```javascript
  // common function to get style loaders
  const getStyleLoaders = (cssOptions, preProcessor) => {
    const loaders = [
      isEnvDevelopment && require.resolve('style-loader'),
      isEnvProduction && {
        loader: MiniCssExtractPlugin.loader,
        // css is located in `static/css`, use '../../' to locate index.html folder
        // in production `paths.publicUrlOrPath` can be a relative path
        options: paths.publicUrlOrPath.startsWith('.')
          ? { publicPath: '../../' }
          : {},
      },
```
 
and public path is set below:
```javascript
      // webpack uses `publicPath` to determine where the app is being served from.
      // It requires a trailing slash, or the file assets will get an incorrect path.
      // We inferred the "public path" (such as / or /my-project) from homepage.
      publicPath: paths.publicUrlOrPath,
```

**Comment by shilman** [comment] 2020-03-23 16:05
@mrmckeb any chance you can look at @cherouvim 's repro?

**Comment by mrmckeb** [comment] 2020-03-24 09:18
@cherouvim, I downloaded your project and ran it - and I see "Rumba" loading as expected.

![image](https://user-images.githubusercontent.com/5043083/77408562-950c9680-6dc0-11ea-9d4c-65415ba88b3d.png)

You also have a `webpack.config.js` file which is not needed, as CRA inserts the necessary config.

I then migrated the project to use the new preset for CRA, and everything was still working correctly.

Can you please provide some more info? Thanks!

**Comment by mrmckeb** [comment] 2020-03-24 09:19
@YDundie, I'd like to find the root cause of this and fix it in the preset. Are you able to share an example of what isn't working for you?

Even just code snippets here.

**Comment by cherouvim** [comment] 2020-03-24 09:20
@mrmckeb it does work on `npm run storybook`, but does it work on `npm run build-storybook`?

**Comment by mrmckeb** [comment] 2020-03-24 09:56
Thanks @cherouvim, I didn't understand that it was build only. Found and hopefully fixed.

**Closed** 2020-03-24 10:27 UTC
Labels: app: react, cra, question / support, typescript

**Comment by ZeeshanTamboli** [comment] 2020-06-09 13:29
@maniax89's solution to add `"homepage": "."` in package.json worked for me. Thanks!

**Comment by rodoabad** [comment] 2021-01-28 18:54
This is still happening on non-CRA apps.

**Comment by kneupper** [comment] 2022-03-16 20:35
For anybody still having this issue down the road on a non-CRA app, please reference [this SO thread](https://stackoverflow.com/questions/66410246/how-can-i-use-static-assets-on-scss-with-storybook)

The key of this is in specifying { url: false } in the CSS Module rule of your webpack config. Here is the specific configuration I used for my CSS Module rule:
```javascript
config.module.rules.push({
    use: [
        require.resolve('style-loader'),
        {
            loader: require.resolve('css-loader'),
            options: {
                modules: {...}, // project-specific module naming conventions, config, etc.
                url: false,
                importLoaders: 1,
            },
        },
    ],
}) 
```

Hope this can save some time for anybody else!
