### ISSUE TITLE
Number control does not update when using useArgs hook

### ISSUE THREAD

**Issue by zygisau** [storybookjs/storybook#15924] opened 2021-08-27 07:17 UTC
**Describe the bug**
I'm using `useArgs` hook in my component's template to sync controls value when the state is changed via function handler. 

```typescript
// Brief view of the story ./stories/Counter.stories.tsx
const Template: ComponentStory<typeof Counter> = (args) => {
  const [{ primary, count }, updateArgs] = useArgs();
  const handleChange = () => updateArgs({ primary: !primary });
  const handleClickUp = () => updateArgs({ count: count + 1 });
  const handleClickDown = () => updateArgs({ count: count - 1 });

  return (
    <div>
      <Counter {...args} handleChange={handleChange} handleClickDown={handleClickDown} handleClickUp={handleClickUp} />
    </div>
  );
};
```

Everything works with boolean type, but when `updateArgs` updates a number, the control tab does not update and shows the previous/initial value.

**To Reproduce**
Repo to reproduce: https://github.com/zygisau/use-args-number-type-control-bug-repro

1. Go to Example/Counter/Primary story (image below).

![image](https://user-images.githubusercontent.com/43187442/131087203-8086696c-5c87-412b-a4f4-6d09366b7fd2.png)

2. Press +1 a couple of times.
   
**Expected behaviour**

- Count value in the control tab is updated with the new value.

**Actual behaviour**

- Count value did not update (image below).

![image](https://user-images.githubusercontent.com/43187442/131087340-4c780ad9-4302-4396-a683-f32b7db170ea.png)

**System**
```
Environment Info:

  System:
    OS: Linux 5.4 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: 3.0.1 - /mnt/c/Users/zygimantas/AppData/Roaming/npm/yarn
    npm: 6.14.12 - /usr/local/bin/npm
  npmPackages:
    @storybook/addon-actions: ^6.4.0-alpha.32 => 6.4.0-alpha.32
    @storybook/addon-docs: ^6.4.0-alpha.32 => 6.4.0-alpha.32
    @storybook/addon-essentials: ^6.4.0-alpha.32 => 6.4.0-alpha.32
    @storybook/addon-links: ^6.4.0-alpha.32 => 6.4.0-alpha.32
    @storybook/react: ^6.4.0-alpha.32 => 6.4.0-alpha.32
```

**Additional context**

There are a few interesting points to note:
- Changing count values in the control tab updates every part of the story (component, control, url).
- As I mentioned, changing boolean value "Primary" updates control tab.
- One more thing to note, going from the `Canvas` tab to `Docs` **updates** the value.

**Comment by tmeasday** [comment] 2021-12-02 05:38
@shilman I recall that maybe there is already an issue about this? The issue here is the number control input (both in the control panel and in docs) doesn't update when the value of the arg changes.

**Comment by sunyatasattva** [comment] 2021-12-15 15:10
@tmeasday Did you end up recalling what's the issue related to this? Perhaps I could follow/contribute to that.

**Comment by tmeasday** [comment] 2021-12-16 05:15
@sunyatasattva I'm not sure if we found the issue, but the problem is reasonably contained as I understand it; the control's component is just not properly responsive to changes in arg value coming from "outside in" -- the classic React form state problem.

**Comment by patrick-mcdougle** [comment] 2021-12-28 19:15
I think the bug is here: https://github.com/storybookjs/storybook/blob/next/lib/components/src/controls/Number.tsx#L31

We only use the value from "on high" to set the initial state. We need a useEffect hook that listens for changes to value and set the internal state based on this being changed.

**Comment by tmeasday** [comment] 2021-12-29 02:05
PS if someone wants to look at it (which would be amazing!) the issue is likely there for (some of) the other controls also.

**Comment by sakito21** [comment] 2021-12-29 05:04
@tmeasday Hi i would like to work on this, please assign this to me.

**Comment by tmeasday** [comment] 2021-12-29 05:40
Sure thing!

**Comment by aritrakoley** [comment] 2022-01-15 14:27
I see that there's not been much activity for a while on this issue so I was trying to see if I could fix this.
I have made a pull request with what I think is a fix for the issue. I'm still pretty new to open source contributions so if there's anything I missed or need to do differently please let me know.

**Comment by shilman** [comment] 2022-01-17 12:05
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.19 containing PR #17247 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2022-01-17 12:05 UTC
Labels: bug, good first issue, app: react, args, addon: controls, P0, linear
