### ISSUE TITLE
Storyshots does not render JSX in addDecorator

### ISSUE THREAD

**Issue by david-golightly-leapyear** [storybookjs/storybook#9771] opened 2020-02-06 00:35 UTC
**Describe the bug**
`addDecorator` from `storybook/react` does not appear to be called in storyshots, even though it's called in Storybook itself.

[EDIT] This appears to be the case only in .jsx and .tsx files.

**To Reproduce**
Minimal repro can be found at this repository:
https://github.com/LeapYear/storybook-storyshots-repro

**Expected behavior**
`addDecorator` should be called with storyshots

**Possibly related issues**
https://github.com/storybookjs/storybook/issues/3246
- Appears superficially related, however, the [migration instructions from 5.2 -> 5.3](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#from-version-52x-to-53x) instruct to move all `require` calls from `config.js` to `main.js`, leaving `addDecorator` in place. However, the documentation for `@storybook/react` [still recommends using `configure(require.context(..), ..)`](https://storybook.js.org/docs/basics/writing-stories/#loading-stories). Is the documentation inconsistent?

**Comment by shilman** [comment] 2020-02-06 01:05
@david-golightly-leapyear It looks to me like it actually recommends using `main.js` `stories` as the most convenient way to load stories, and documents `configure` as a less convenient alternative?

**Comment by david-golightly-leapyear** [comment] 2020-02-06 01:15
@shilman That’s correct. The linked repo uses the `main.js` recommendation.

**Comment by shilman** [comment] 2020-02-06 01:21
My question was about the inconsistency comment. It doesn't seem inconsistent to me, but maybe I'm missing something?

**Comment by david-golightly-leapyear** [comment] 2020-02-06 01:22
The resolution to #3246 recommends ensuring `addDecorator` is called before `configure`, but it’s not clear that migrating from `configure` to `stories` in main.js preserves the load order behavior necessary for decorators to be set up prior to story loading.

**Comment by shilman** [comment] 2020-02-06 01:23
Gotcha. Thanks for clarifying! cc @ndelangen

**Comment by iansan5653** [comment] 2020-02-06 17:23
Confirmed - all of our stories rely on a `theme` context being present, but since this is provided by a decorator, we can't use storyshots at all.

**Comment by ndelangen** [comment] 2020-02-06 19:41
We're going to have to inspect the load order of preview.js in storyshots.

In the repro I see there's a `preview.TSX`. This might be the problem.
AFAK there's no support for TS in preview.js file.

**Comment by iansan5653** [comment] 2020-02-06 20:52
In the meantime, is there any other way to add a decorator? I'm using the following to get `styled-components` to work; can I insert the decorator somewhere in this function? 
```ts
addSerializer(styleSheetSerializer);

initStoryshots({
  test: ({story, context}) => {
    const snapshotFilename = path.join(
      `__snapshots__/${context.kind}.storysnaps`
    );

    const storyElement = story.render(context);
    const tree = renderer.create(storyElement).toJSON();
    expect(tree).toMatchSpecificSnapshot(snapshotFilename);
  }
});
```

**Comment by shilman** [comment] 2020-02-07 02:26
@ndelangen pretty sure there's support for `preview.tsx`? https://github.com/storybookjs/storybook/pull/9775 cc @igor-dv

**Comment by david-golightly-leapyear** [comment] 2020-02-10 18:09
@ndelangen @shilman  I can confirm that changing `preview.tsx` -> `preview.jsx` does not change any behavior here. However, if I rename the file to exactly `preview.js`, it does invoke the file & decorators in the right order. However, this means that `preview.js` cannot have any ES2015+ features, such as module imports or JSX. I had to change the file contents to the following to get it to work:

```js
const { addDecorator } = require('@storybook/react')
const React = require('react')

addDecorator((content) => (
  React.createElement('div', { children: ['Preview Decorator', content()]})
))
```

This is _sort of_ a workaround, but represents a significant behavioral regression from 5.2. Especially more complex React layouts will be tedious to implement in this way.

**Comment by shilman** [comment] 2020-02-10 18:23
Looks like there are a couple bugs here @ndelangen:

https://github.com/storybookjs/storybook/blob/34081437e975ad487e20845e5fda343760a51a03/addons/storyshots/storyshots-core/src/frameworks/configure.ts#L22

Can we just add support for [.tsx,.ts,.jsx,.js] across the board, in a simple find call?

**Comment by ndelangen** [comment] 2020-02-11 16:55
@david-golightly-leapyear would you happen to have some time to fix this issue?

@shilman has pointed out the correct place for the fix.

🙇

**Comment by david-golightly-leapyear** [comment] 2020-02-12 22:21
@ndelangen @shilman Submitted #9834 for your review.

**Comment by shilman** [comment] 2020-02-15 13:00
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.13 containing PR #9834 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2020-02-15 13:00 UTC
Labels: addon: storyshots, bug

**Comment by shilman** [comment] 2020-02-25 15:50
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.14 containing PR #9834 that references this issue. Upgrade today to try it out!
