### ISSUE TITLE
@storybook/source-loader messes with custom hooks - evaluates source code?

### ISSUE THREAD

**Issue by donaldpipowitch** [storybookjs/storybook#8294] opened 2019-10-04 12:24 UTC
**Describe the bug**
I have a custom component using a custom hook. The hook runs an assertion on the context at runtime. I don't know why, but it looks like the source loader runs parts of its logic on _my_ context/hook which throws an error.

**To Reproduce**
Clone this repo and follow README:
https://github.com/donaldpipowitch/storybook-bug-demo-source-loader-context-null

**Expected behavior**
No error should happen.

**Screenshots**
![image](https://user-images.githubusercontent.com/1152805/66207273-af3ba680-e6b2-11e9-8fbd-82ec93e574a7.png)

![image](https://user-images.githubusercontent.com/1152805/66207370-e447f900-e6b2-11e9-831c-2118db950f56.png)

`null` is a valid value in _my_ context. 

**System:**

```
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Browsers:
    Chrome: 77.0.3865.90
    Safari: 13.0.1
  npmPackages:
    @storybook/addon-a11y: ^5.2.1 => 5.2.1 
    @storybook/addon-backgrounds: ^5.2.1 => 5.2.1 
    @storybook/addon-docs: ^5.2.1 => 5.2.1 
    @storybook/react: ^5.2.1 => 5.2.1 
    @storybook/source-loader: ^5.2.1 => 5.2.1 
    @storybook/theming: ^5.2.1 => 5.2.1 
```

**Comment by celinrayen** [comment] 2019-10-05 06:10
Can I take a look on it if it the issue is still open?

**Comment by donaldpipowitch** [comment] 2019-10-05 07:51
The issue should still be open. 🙂 Thank you.

**Comment by donaldpipowitch** [comment] 2019-11-05 12:08
I saw there were some changes to the source-loader (https://github.com/storybookjs/storybook/pull/8499), but this issue still seems to be preset.

```
  npmPackages:
    @storybook/addon-a11y: ^5.3.0-alpha.38 => 5.3.0-alpha.38 
    @storybook/addon-backgrounds: ^5.3.0-alpha.38 => 5.3.0-alpha.38 
    @storybook/addon-docs: ^5.3.0-alpha.38 => 5.3.0-alpha.38 
    @storybook/react: ^5.3.0-alpha.38 => 5.3.0-alpha.38 
    @storybook/source-loader: ^5.3.0-alpha.38 => 5.3.0-alpha.38 
    @storybook/theming: ^5.3.0-alpha.38 => 5.3.0-alpha.38 
```

**Comment by shilman** [comment] 2019-11-11 15:56
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.43 containing PR #8773 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2019-11-11 15:56 UTC
Labels: bug, help wanted, source-loader

**Comment by donaldpipowitch** [comment] 2019-11-11 20:56
Thank you for the quick release 👏

**Comment by shilman** [comment] 2019-12-02 06:34
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.8 containing PR #8773 that references this issue. Upgrade today to try it out!
