### ISSUE TITLE
Static build of Storybook does not load stories on default route

### ISSUE THREAD

**Issue by moarwick** [storybookjs/storybook#11773] opened 2020-08-03 16:59 UTC
**Describe the bug**
We are building Storybook for static deployment, ver `5.3.3`, using Typescript (`ts-loader`). When accessing the root `/` route (on `http-server`), the app is served, route becomes `http://localhost:8080/?path=/story/*` and.. no stories get shown in the UI. Sadly, also no console logs or any errors are thrown. However, if the URL is updated manually to remove the `*`, it picks up the first story and everything works from then on. Any ideas?

**Screenshots**
<img width="899" alt="storybook" src="https://user-images.githubusercontent.com/4442541/89207492-ae440180-d56f-11ea-91ff-976b9b7441ed.png">

**Comment by shilman** [comment] 2020-08-03 17:17
Try upgrading to 6.0 RC?

```
npx sb@next upgrade --prerelease
```

**Comment by jferrettiboke** [comment] 2020-08-27 10:35
I have experienced a similar thing. My stories show, but the ones within `/stories` are missing some CSS. But if I move all my stories within `/stories` to `/components` works.

Everything work in development as expected.

Also, this is what I see once I build and open Storybook for the first time. I need to click other stories to start seeing something.

<img width="819" alt="Screenshot 2020-08-27 at 12 30 16" src="https://user-images.githubusercontent.com/11066224/91431734-1204d600-e861-11ea-8a5a-e21cfb9179b3.png">

More info.

**.storybook/main.js**

```js
module.exports = {
  stories: [
    "../stories/**/*.stories.@(js|jsx|ts|tsx|mdx)",
    "../components/**/*.stories.@(js|jsx|ts|tsx|mdx)",
  ],
  addons: ["@storybook/addon-links", "@storybook/addon-essentials"],
};
```

**postcss.config.js**

```js
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
```

**package.json**

```json
{
  "name": "web",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "storybook": "start-storybook -p 6006 -s ./.storybook/public",
    "build-storybook": "build-storybook -s ./.storybook/public"
  },
  "dependencies": {
    "next": "9.5.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-modal": "^3.11.2",
    "styled-components": "^5.1.1"
  },
  "devDependencies": {
    "@babel/core": "^7.11.4",
    "@storybook/addon-actions": "^6.0.19",
    "@storybook/addon-essentials": "^6.0.19",
    "@storybook/addon-links": "^6.0.19",
    "@storybook/react": "^6.0.19",
    "babel-loader": "^8.1.0",
    "react-is": "^16.13.1",
    "tailwindcss": "^1.7.5"
  }
}
```

**Comment by shilman** [comment] 2020-08-28 02:38
@jferrettiboke sounds like two separate issues. do you have a repro for the "no preview" issue?

**Comment by typeoneerror** [comment] 2020-09-10 20:40
Also experience this here. On first load of this story specifically it does not render css. If I "enter" the story by clicking on "Button" from another story, it does render. 

![Screen Shot 2020-09-10 at 13 39 54](https://user-images.githubusercontent.com/218700/92802268-384f6900-f36b-11ea-9b84-a48f68e17954.png)

**Comment by peterpeterparker** [comment] 2020-10-03 05:57
For what is worth, I was facing the exact same issue when I tried to serve the storybook static build locally using a test server such as `npx serve docs`.

Finally, we decided to go ahead and deploy the docs anyway on our Firebase Hosting and, we were pleasantly surprised that the issue did not happens once served live  😃.

I assume the issue is linked with the way the test serves the pages locally.

**Comment by shilman** [comment] 2020-10-03 08:05
@peterpeterparker `serve` specifically has problems because it seems to rewrite paths dynamically (`/iframe.html` gets rewritten to `iframe`)

@jonniebigodes maybe this is also something good for the FAQ?

**Comment by jonniebigodes** [comment] 2020-10-03 16:02
@shilman yes. We should add some context to the FAQ regarding this. It's not the first time we've ran into issues similar to this one. Adding the documentation label and assigning myself to take care of it. A pull request should be up soon.

**Comment by carlo-colombo** [comment] 2020-10-29 12:48
I have the same issue with both `http-server` as suggested in the documentation (`npx http-server ./path/to/build`) and with `python3 -m http.server` (my usual default for serving locally and static).

I solved forcing webpack to be in developer mode, I am not sure it's the nicest way but I added the following to my `.storybook/main,js`

```js
  webpackFinal: async (config, { configType }) => {
    config.mode = 'development'
    return config;
  },
```

**Comment by pedrohmorais** [comment] 2020-12-11 18:43
> Also experience this here. On first load of this story specifically it does not render css. If I "enter" the story by clicking on "Button" from another story, it does render.
> 
> ![Screen Shot 2020-09-10 at 13 39 54](https://user-images.githubusercontent.com/218700/92802268-384f6900-f36b-11ea-9b84-a48f68e17954.png)

same here

**Comment by jonniebigodes** [comment] 2020-12-11 21:44
@pedrohmorais can you provide a reproduction? As it seems that this is a two-pronged issue. Based on my research the issue with story loading is solved and a pull request to document the problem is up. The css issue might be related to something else. 

Let us know

Stay safe

**Comment by anuragaroraaa** [comment] 2020-12-18 14:42
Since I was using v5.3.9 I was able to fix this by following https://nx.dev/latest/angular/plugins/storybook/overview#upgrading-to-storybook-6-and-nx-versions-gt-10-1-x-  **Step 1: Changing the configuration files from version 5.2 to 5.3**.

I will upgrade to v6 soon.

**Comment by jonniebigodes** [comment] 2021-01-20 15:52
Going to close this issue if you all don't mind. A recent pull request was merged that addressed this.

Feel free to re-open regarding any follow up. 

Stay safe

**Closed by jonniebigodes** 2021-01-20 15:52 UTC
Labels: build-storybook, documentation, question / support
