### ISSUE TITLE
[Feature Request]: Support Next.js 13 useParams Client Component Hook

### ISSUE THREAD

**Issue by desiboli** [storybookjs/storybook#22792] opened 2023-05-25 13:34 UTC
### Is your feature request related to a problem? Please describe

Component stories that uses the useParams hook will get an error.
Like e.g. I have internationalization in my app and in the component I need to get the parameter called "locale", that results in the following error on the story page "Cannot read properties of null (reading 'locale')".

Here is a discussion regarding this [https://discord.com/channels/486522875931656193/1110606122915725403](https://discord.com/channels/486522875931656193/1110606122915725403)

### Describe the solution you'd like

Support the Next.js 13 useParams hook.

### Are you able to assist to bring the feature to reality?

no

**Comment by valentinpalkovic** [comment] 2023-05-30 07:59
Duplicate of https://github.com/storybookjs/storybook/issues/22077. Closing.

**Closed by valentinpalkovic** 2023-05-30 07:59 UTC
Labels: feature request, nextjs, needs triage
