### ISSUE TITLE
Docs tab shows 'no code available' when using CSF format

### ISSUE THREAD

**Issue by mattwaler** [storybookjs/storybook#8104] opened 2019-09-17 18:35 UTC
**Describe the bug**

When composing a story using new CSF format, all stories show `no code available`.

**To Reproduce**
1. Compose story
2. Start storybook
3. Go to Docs tab

**Expected behavior**

Like in the screenshots and docs, code previews should be available to view and copy.

**Screenshots**

![browser](https://user-images.githubusercontent.com/32300026/65069110-070aab80-d958-11e9-8821-cd2bf56f72e0.png)
![code](https://user-images.githubusercontent.com/32300026/65069111-070aab80-d958-11e9-82e8-1e43a98cfd0d.png)
![button](https://user-images.githubusercontent.com/32300026/65069228-420cdf00-d958-11e9-983e-0896cf4b004d.png)

**System:**

```
Environment Info:

  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.4.0/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 68.0.2
    Safari: 12.1.2
  npmPackages:
    @storybook/addon-actions: ^5.2.0 => 5.2.0 
    @storybook/addon-docs: ^5.2.0 => 5.2.0 
    @storybook/addon-links: ^5.2.0 => 5.2.0 
    @storybook/addon-notes: ^5.2.0 => 5.2.0 
    @storybook/addons: ^5.2.0 => 5.2.0 
    @storybook/react: ^5.2.0 => 5.2.0 
```

**Comment by shilman** [comment] 2019-09-17 18:48
Can you share your preset and config files?

**Comment by mattwaler** [comment] 2019-09-17 18:52
```
// addons.js
import '@storybook/addon-actions/register'
import '@storybook/addon-links/register'

// config.js
import { configure } from '@storybook/react'
configure(require.context('../src/stories', true, /\.stories\.(js|mdx)$/), module)

// presets.js
module.exports = [
  {
    name: '@storybook/addon-docs/react/preset',
    options: {
      configureJSX: true,
      babelOptions: {},
      sourceLoaderOptions: null,
    },
  },
]
```

**Comment by karthikbalajikb** [comment] 2019-09-21 21:45
facing the same issue

**Comment by riandy-dimas** [comment] 2019-09-22 00:56
I do have the same issue using typescript preset

**Comment by goszczynskip** [comment] 2019-09-25 21:16
I've found bug in my config. Change `test: /\.(stories|story)\.[tj]sx?$/,` in `source-loader` config to `test: /\.[tj]sx?$/`. After that source code appears in stories.

Also I think docs are wrong. Source-loader test regexp should be set to match sources and stories instead of stories only.

**Comment by shilman** [comment] 2019-09-26 03:43
@mattwaler sorry for the slow reply. this line from your preset is disabling the source loader, so there's no code to show:

> sourceLoaderOptions: null,

**Comment by shilman** [comment] 2019-09-26 03:45
@goszczynskip i don't think so. source-loader is about loading the source for stories only. if you set it to load the source for your components it will slow down your builds etc. i suspect there's some other problem with your setup.

**Comment by goszczynskip** [comment] 2019-09-26 07:46
@shilman You are right. There was other problem. I've just used regexp with starting dot but my stories are like: `story.tsx`.

My working configuration with Typescript, MDX and sources. Maybe someone wants to copy it.
```
const path = require('path');
const createCompiler = require('@storybook/addon-docs/mdx-compiler-plugin');

const docgenLoader = {
  loader: require.resolve('react-docgen-typescript-loader'),
  options: {
    propFilter: prop => {
      // Filter out props from styled-components
      if (prop.name === 'as' || prop.name === 'ref' || prop.name === 'theme') {
        return false;
      }

      if (prop.parent == null) {
        return true;
      }

      // Filter out props which type definition is placed in react package
      return prop.parent.fileName.indexOf('node_modules/@types/react') < 0;
    }
  }
};

const babelLoader = {
  loader: require.resolve('babel-loader'),
  options: {
    presets: [['react-app', { flow: false, typescript: true }]]
  }
};

const mdxLoader = {
  loader: '@mdx-js/loader',
  options: {
    compilers: [createCompiler({})]
  }
};

module.exports = ({ config }) => {
  config.module.rules.push({
    test: /\.(mdx)$/,
    use: [babelLoader, docgenLoader, mdxLoader]
  });

  config.module.rules.push({
    test: /\.(ts|tsx)$/,
    use: [babelLoader, docgenLoader]
  });

  config.module.rules.push({
    test: /(stories|story)\.[tj]sx?$/,
    loader: require.resolve('@storybook/source-loader'),
    include: [path.resolve(__dirname, '../src/components')],
    enforce: 'pre',
    options: {
      injectParameters: true,
      inspectLocalDependencies: false,
      inspectDependencies: false
    }
  });

  config.resolve.extensions.push('.ts', '.tsx');

  return config;
};
```

**Comment by larswittenberg** [comment] 2019-10-08 08:57
> @mattwaler sorry for the slow reply. this line from your preset is disabling the source loader, so there's no code to show:
> 
> > sourceLoaderOptions: null,

thx. this works for me.

**Comment by Elijen** [comment] 2019-11-02 14:41
Same problem here. We use a custom Webpack config for TypeScript support in stories.

```
module.exports = ({ config }) => {
  config.module.rules.push({
    test: /\.(ts|tsx)$/,
    use: "babel-loader"
  });
  config.resolve.extensions.push(".ts", ".tsx");
  return config;
};
```

**Comment by jeffryang24** [comment] 2019-12-02 03:24
![no_code_available](https://user-images.githubusercontent.com/8284757/69928251-acf89b80-14ed-11ea-97fa-c93fb6d00acd.png)

Still got no code available while using CSF format (Docs mode). But, when I switched to Canvas mode, the story source existed.

![canvas_mode](https://user-images.githubusercontent.com/8284757/69928317-d74a5900-14ed-11ea-835c-884f796908ec.png)

webpack.config.js

```javascript
// Core(s)
const path = require('path');
const createMDXCompiler = require('@storybook/addon-docs/mdx-compiler-plugin');

// Summary
module.exports = async ({ config }) => {
  config.module.rules.push(
    {
      test: /\.stories\.mdx$/,
      use: [
        {
          loader: 'babel-loader',
          // May or may not need this line depending on your app's setup
          options: {
            plugins: ['@babel/plugin-transform-react-jsx']
          }
        },
        {
          loader: '@mdx-js/loader',
          options: {
            compilers: [createMDXCompiler({})]
          }
        }
      ]
    },
    {
      test: /\.stories\.tsx?$/,
      use: [
        {
          loader: require.resolve('@storybook/source-loader'),
          options: {
            parser: 'typescript',
            prettierConfig: {
              arrowParens: 'avoid',
              printWidth: 80,
              tabWidth: 2,
              bracketSpacing: true,
              trailingComma: 'none',
              singleQuote: true,
              semi: true,
              jsxBracketSameLine: false
            }
          }
        }
      ],
      enforce: 'pre',
      include: path.resolve(__dirname, '../src')
    },
    {
      test: /\.tsx?$/,
      use: [
        {
          loader: require.resolve('babel-loader'),
          options: {
            presets: [
              [
                require.resolve('babel-preset-react-app'),
                { flow: false, typescript: true }
              ]
            ]
          }
        },
        require.resolve('react-docgen-typescript-loader')
      ]
    },
    {
      test: /\.s[ac]ss$/,
      use: ['style-loader', 'css-loader', 'sass-loader'],
      include: path.resolve(__dirname, '../')
    }
  );

  config.resolve.extensions.push('.ts', '.tsx');

  return config;
};
```

button.tsx

```typescript
import React, { ReactNode, FunctionComponentElement } from 'react';

export type Props = {
  /**
   * Children
   */
  children?: ReactNode;
};

export function Button({ children }: Props): FunctionComponentElement<Props> {
  return <button type="button">{children}</button>;
}

export default Button;
```

button.stories.tsx

```typescript
import React, { FunctionComponent } from 'react';
import { text } from '@storybook/addon-knobs';

import { Button } from './button';

export default { title: 'Genesis|Button', component: Button };

export const withText: FunctionComponent = () => <Button>Hello Button</Button>;

export const withEmoji: FunctionComponent = () => (
  <Button>
    <span role="img" aria-label="so cool">
      😀 😎 👍 💯
    </span>
  </Button>
);

export const withKnobs: FunctionComponent = () => (
  <Button>{text('children', 'Test Children')}</Button>
);
```

:bowing_man:

**Comment by shilman** [comment] 2019-12-02 04:58
@jeffryang24 your webpack config adds source-loader, but addon-docs also adds source-loader. I'd suggest removing yours, or disabling the one in addon-docs per https://github.com/storybookjs/storybook/blob/next/addons/docs/README.md#preset-options

**Comment by jeffryang24** [comment] 2019-12-02 06:31
> @jeffryang24 your webpack config adds source-loader, but addon-docs also adds source-loader. I'd suggest removing yours, or disabling the one in addon-docs per https://github.com/storybookjs/storybook/blob/next/addons/docs/README.md#preset-options

I see... Will try to disable one of them. Will report the result back, probably this night (GMT+7)... :bowing_man:

**Comment by patrick-radulian** [comment] 2019-12-02 10:50
I have a running storybook installation as per instructions here: https://gist.github.com/shilman/bc9cbedb2a7efb5ec6710337cbd20c0c

Currently I also see no code preview in the stories when using CSF - it only works properly when using MDX instead.

**Comment by shilman** [comment] 2019-12-02 12:48
@patrick-radulian I have updated the gist, specifically this part, to reflect recent changes in `addon-docs`:

```
  {
    name: "@storybook/addon-docs/preset",
    options: {
      configureJSX: true,
    }
  }
```

**Comment by jeffryang24** [comment] 2019-12-02 13:15
> @jeffryang24 your webpack config adds source-loader, but addon-docs also adds source-loader. I'd suggest removing yours, or disabling the one in addon-docs per https://github.com/storybookjs/storybook/blob/next/addons/docs/README.md#preset-options

Hmm... Actually, I don't use the default preset, `@storybook/addon-docs/preset` and I don't have `presets.js`. I follow the manual installation from the docs (before this new doc with `main.js` :laughing:). I will try update the storybook to v5.2.8

**Comment by jeffryang24** [comment] 2019-12-02 13:24
> @jeffryang24 your webpack config adds source-loader, but addon-docs also adds source-loader. I'd suggest removing yours, or disabling the one in addon-docs per https://github.com/storybookjs/storybook/blob/next/addons/docs/README.md#preset-options

Here's my full config: https://gist.github.com/jeffryang24/2147d8dbed6189ba6cc9a022ec79ac11 :bowing_man:. Still got no luck...

**Comment by jeffryang24** [comment] 2019-12-02 13:57
> ![no_code_available](https://user-images.githubusercontent.com/8284757/69928251-acf89b80-14ed-11ea-97fa-c93fb6d00acd.png)
> 
> Still got no code available while using CSF format (Docs mode). But, when I switched to Canvas mode, the story source existed.
> 
> ![canvas_mode](https://user-images.githubusercontent.com/8284757/69928317-d74a5900-14ed-11ea-835c-884f796908ec.png)
> 
> webpack.config.js
> 
> ```js
> // Core(s)
> const path = require('path');
> const createMDXCompiler = require('@storybook/addon-docs/mdx-compiler-plugin');
> 
> // Summary
> module.exports = async ({ config }) => {
>   config.module.rules.push(
>     {
>       test: /\.stories\.mdx$/,
>       use: [
>         {
>           loader: 'babel-loader',
>           // May or may not need this line depending on your app's setup
>           options: {
>             plugins: ['@babel/plugin-transform-react-jsx']
>           }
>         },
>         {
>           loader: '@mdx-js/loader',
>           options: {
>             compilers: [createMDXCompiler({})]
>           }
>         }
>       ]
>     },
>     {
>       test: /\.stories\.tsx?$/,
>       use: [
>         {
>           loader: require.resolve('@storybook/source-loader'),
>           options: {
>             parser: 'typescript',
>             prettierConfig: {
>               arrowParens: 'avoid',
>               printWidth: 80,
>               tabWidth: 2,
>               bracketSpacing: true,
>               trailingComma: 'none',
>               singleQuote: true,
>               semi: true,
>               jsxBracketSameLine: false
>             }
>           }
>         }
>       ],
>       enforce: 'pre',
>       include: path.resolve(__dirname, '../src')
>     },
>     {
>       test: /\.tsx?$/,
>       use: [
>         {
>           loader: require.resolve('babel-loader'),
>           options: {
>             presets: [
>               [
>                 require.resolve('babel-preset-react-app'),
>                 { flow: false, typescript: true }
>               ]
>             ]
>           }
>         },
>         require.resolve('react-docgen-typescript-loader')
>       ]
>     },
>     {
>       test: /\.s[ac]ss$/,
>       use: ['style-loader', 'css-loader', 'sass-loader'],
>       include: path.resolve(__dirname, '../')
>     }
>   );
> 
>   config.resolve.extensions.push('.ts', '.tsx');
> 
>   return config;
> };
> ```
> 
> button.tsx
> 
> ```ts
> import React, { ReactNode, FunctionComponentElement } from 'react';
> 
> export type Props = {
>   /**
>    * Children
>    */
>   children?: ReactNode;
> };
> 
> export function Button({ children }: Props): FunctionComponentElement<Props> {
>   return <button type="button">{children}</button>;
> }
> 
> export default Button;
> ```
> 
> button.stories.tsx
> 
> ```ts
> import React, { FunctionComponent } from 'react';
> import { text } from '@storybook/addon-knobs';
> 
> import { Button } from './button';
> 
> export default { title: 'Genesis|Button', component: Button };
> 
> export const withText: FunctionComponent = () => <Button>Hello Button</Button>;
> 
> export const withEmoji: FunctionComponent = () => (
>   <Button>
>     <span role="img" aria-label="so cool">
>       😀 😎 👍 💯
>     </span>
>   </Button>
> );
> 
> export const withKnobs: FunctionComponent = () => (
>   <Button>{text('children', 'Test Children')}</Button>
> );
> ```

cc: @shilman 
Could be #7829? Since I used typescript for this project. https://gist.github.com/jeffryang24/2147d8dbed6189ba6cc9a022ec79ac11 :bowing_man:

**Comment by patrick-radulian** [comment] 2019-12-02 15:21
@shilman Thanks, you are right - I've just commented out a different addon (addon-storysource) and kept only docs running. I do in fact see the code preview now, but with a (rather minor) issue:

![image](https://user-images.githubusercontent.com/12211606/69970680-ef869c00-151e-11ea-9d58-82f7ca037646.png)

The bigger issue I've run into though, is the warnings I receive when storybook starts up / refreshes:

![image](https://user-images.githubusercontent.com/12211606/69970759-16dd6900-151f-11ea-9fef-2ed41a4ec86a.png)

With Button.stories.tsx looking like this:

```typescript
import React from "react";
import { Button } from "./Button";

export default {
    title: "Design System|Atoms/Button",
    component: Button
}

export const Default = () => <Button>Default button</Button>;

export const Positive = () => <Button type="positive">Positive button</Button>;

export const Danger = () => <Button type="danger">Danger button</Button>;
```

**Comment by jeffryang24** [comment] 2019-12-03 03:39
> @jeffryang24 your webpack config adds source-loader, but addon-docs also adds source-loader. I'd suggest removing yours, or disabling the one in addon-docs per https://github.com/storybookjs/storybook/blob/next/addons/docs/README.md#preset-options

![probably_the_culprit](https://user-images.githubusercontent.com/8284757/70018364-73409700-15b8-11ea-9f8c-e784d9b7d3ec.png)

Already found the culprit. I just made another sandbox for reproducing the issue, and finally found the root problimageem. When I set the `parser` option for `@storybook/source-loader`, the "No code available" issue appears, but when I comment the `parser` option, the "Show Code" panel appears and it renders the source code perfectly. I don't know why I can't set the parser to `typescript`, probably #7829?

![after_removing_parser_option](https://user-images.githubusercontent.com/8284757/70018526-0083eb80-15b9-11ea-898e-7b1ec2d816f2.png)

Here's the repo for reproducing the issue: https://github.com/jeffryang24/sandbox/tree/master/javascript-typescript/storybook-addon-docs-repro

**Comment by laij84** [comment] 2019-12-06 21:34
For anyone else still struggling, I've finally managed to get it to work after some painful debugging of react-docgen-typescript-loader.

React-docgen-typescript-loader assigns the `__docgeninfo` using the folder name, not the component name, so you must put your component in a folder of the same name (case sensitive).

I couldnt get CSF format to work (always blank), but when using the `storiesOf` syntax, you must include the component using the `addParameter` function from storybook:

```
storiesOf('CTALink', module)
  .addParameters({
    component: CTALink,
   
  })
  .add('default story', () => (
    <CTALink to="/">Click here</CTALink>
  ))
```

**Comment by Vanuan** [comment] 2019-12-26 14:48
I have renamed `stories.tsx` to `Component.stories.tsx` and it worked.

It looks like the preset ignores values provided from `configure/require.context`. Or maybe it uses heuristics

**Comment by Vanuan** [comment] 2019-12-26 14:51
```
// config.js
import { addParameters, configure } from '@storybook/react';

addParameters({
  options: {
    storySort: (a, b) => (a[1].kind === b[1].kind ? 0 : a[1].id.localeCompare(b[1].id)),
  },
});

configure(
  [
    requireContext('../src', true, /stories\.tsx$/),
  ],
  module
);

// main.js
module.exports = {
  presets: [
    '@storybook/preset-create-react-app',
    {
      name: '@storybook/addon-docs/preset',
      options: {
        configureJSX: true,
      },
    },
  ],
  addons: [
    '@storybook/addon-a11y/register',
    '@storybook/addon-actions/register',
    '@storybook/addon-knobs/register',
 ],
};
```

**Comment by Vanuan** [comment] 2019-12-26 14:57
Found the source: https://github.com/storybookjs/storybook/blob/21b8a7fb2ca2ace85be14accabc5e046f9189377/addons/docs/src/frameworks/common/preset.ts#L36-L45

So, if your story filename is different, no code would be shown.

**Comment by benmvp** [comment] 2020-01-08 22:27
I just ran into this same problem as well when using TypeScript. Turns out the problem was the TypeScript types. My guess is that whatever is loading/parsing the code isn't able to parse TypeScript (probably cuz it doesn't know it's TypeScript), and as a result ti fails. And then when it fails the "no code available" shows up.

**Comment by benmvp** [comment] 2020-01-09 01:45
Ok, I traced it down to a bug in [`@storybook/source-loader`](https://www.npmjs.com/package/@storybook/source-loader). The parsed AST from JS slightly differs from that from TS and the code was only handling the JS version. Luckily @shilman has already [fixed the bug](https://github.com/storybookjs/storybook/pull/8499)! It's in a RC of `@storybook/source-loader` I believe, but `5.3.0` hasn't officially been released, which is why `@storybook/addon-docs` hasn't updated to it.

Once `@storybook/source-loader` v5.3.0 is released and the docs addon is updated, this should be fixed. 👏🏾 The bug was fixed back in October, so not quite sure what the timeline would be on it

**Comment by benmvp** [comment] 2020-01-15 18:02
Just upgraded to `5.3.3` and verified the code shows for me

**Comment by shilman** [comment] 2020-01-16 00:45
🎉 closing this! 🎉

**Closed by shilman** 2020-01-16 00:45 UTC
Labels: addon: docs, block: source, question / support

**Comment by gaurav5430** [comment] 2020-05-16 21:05
In my project I am overriding the default storybook webpack config with my own custom webpack config. This meant that any of the default module.rules from storybook webpack config were not being applied. Due to this the source-loader rule was also not being applied, and DocsPage was showing 'No code available' .

I re-added the source-loader rule and it works fine.

**Comment by andre-brdoch** [comment] 2020-09-18 13:35
ran into the same issue like @Vanuan on v6.0.21. It works if the storyname includes the name of the component. However, our folder structure is like this:
```
/MyComponent
--> index.vue
--> stories.js
```

I am no webpack expert, could someone point me into a direction how to fix this without changing folder structure? 😃

**Comment by pwfisher** [comment] 2020-11-25 00:34
@Vanuan
> @andre-brdoch Maybe try changing `loaders[x][y].test` to a constant, e.g. "stories.js".
> 
> Or, if you're willing to contribute, change this line:
> 
> https://github.com/storybookjs/storybook/blob/57798a108e183d97f94fd4cc396e45e1d4b04d23/addons/docs/src/frameworks/common/preset.ts#L65
> 
> To the following:
> 
> ```
>           test: /\.?(stories|story)\.[tj]sx?$/,
> ```
but that would match, for example, `History.tsx`.

Assuming this tests a path and not a filename alone:
```
          test: /(/|\.)(stories|story)\.[tj]sx?$/,
```

**Comment by pwfisher** [comment] 2020-11-25 00:36
Thanks @andre-brdoch for the tip. Here are specific instructions for a general solution:

Add the following to `/.storybook/webpack.config.js`:

```ts
// /.storybook/webpack.config.js
module.exports = ({ config }) => {
  config.module.rules.push({
    test: /(\/|\.)(stories|story)\.[tj]sx?$/,
    use: '@storybook/source-loader',
  })
  return config
}
```

**Comment by Vanuan** [comment] 2020-11-25 13:20
@pwfisher Good catch!

**Comment by shilman** [comment] 2020-11-26 03:19
@pwfisher @Vanuan what if you just add `\/story.[tj]sx?` i'm afraid that the source-loader would get run twice on e.g. `Foo.stories.tsx` because `addon-docs` already adds a rule for that.

**Comment by penx** [comment] 2021-10-01 14:27
I'm finding that if I have a story as follows:

```tsx
export const Start: Story = () => (
  <Button start>
    Save and continue
  </Button>
);
```

Then I get 'no code available'. But if I add an unused `args` parameter to the function:

```tsx
export const Start: Story = (args) => (
  <Button start>
    Save and continue
  </Button>
);
```

Then the code is correctly displayed.

Not sure if this is a bug or a feature @shilman ? 😀

**Comment by shilman** [comment] 2021-10-01 15:04
@penx it's a feature. you can read more about it here:

https://storybook.js.org/docs/react/writing-docs/doc-blocks#docspage-1

dynamic snippet rendering was introduced at the last minute in storybook 6.0 to fix a broken user experience for args stories, which were introduced in 6.0. however, because the feature was immature, i didn't want to break the experience for existing 5.x users writing no-args stories. now that dynamic snippets are fairly stable, we can probably make them the default and users can opt-in to source snippets when they need them. i'll consider this seriously as part of the 7.0 release.

**Comment by yannbf** [comment] 2022-06-21 19:45
@shilman I found another scenario where it does not show code:

```js
export const parameters = {
  docs: {
    container: (props) => <DocsContainer {...props} />,
  },
};
```

Seems like a bug?

**Comment by isaacebhodaghe** [comment] 2023-04-12 21:36
> @shilman I found another scenario where it does not show code. When using a custom DocsContainer:
> 
> ```js
> import { DocsContainer } from '@storybook/addon-docs';
> 
> export const parameters = {
>   docs: {
>     container: (props) => <DocsContainer {...props} />,
>   },
> };
> ```
> 
> Seems like a bug?

Is there a solution to this, I'm facing this same senerio
