### ISSUE TITLE
Theming doesn't support latest color notation format

### ISSUE THREAD

**Issue by Th3S4mur41** [storybookjs/storybook#17619] opened 2022-03-03 12:15 UTC
Using the [CSS Color Module 4](https://drafts.csswg.org/css-color/#the-hsl-notation) notation format for HSL in some fields (not all?!) a custom theme like the following example leads to errors

```
export default create({
	base: 'dark',

	colorPrimary: 'hsl(205.2 100% 51%)',
	colorSecondary: 'hsl(205.2 100% 51%)',

	// UI
	appBg: 'hsl(0 0% 5.9%)',
	appContentBg: 'hsl(0 0% 5.9%)',
	appBorderColor: 'grey',
	appBorderRadius: 4,

	// Text colors
	textColor: 'hsl(0 0% 100%)',
	textInverseColor: 'hsl(0 0% 100%)',

});
```

![image](https://user-images.githubusercontent.com/5543595/156562414-3031735e-4161-411f-abea-61f93a1539ce.png)

![image](https://user-images.githubusercontent.com/5543595/156562863-f8803d85-0280-47b8-946d-d1eb1c60dd3e.png)

**Comment by josh-degraw** [comment] 2022-03-30 17:41
Currently running into this issue as well. Looks like source of the issue is that polished doesn't know how to parse that syntax correctly (see this [issue](https://github.com/styled-components/polished/issues/605)). I have a minimal repro with storybook [here](https://github.com/josh-degraw/hsl-issues/blob/main/.storybook/theme.js). Would love to have this fixed, whether by polished or by storybook.

**Comment by bhough** [comment] 2022-04-03 16:50
We've addressed this issue in polished in [v4.2.0](https://github.com/styled-components/polished/releases/tag/v4.2.0).

**Comment by bhough** [comment] 2022-04-07 15:57
[v4.2.2](https://github.com/styled-components/polished/releases/tag/v4.2.2) is the better fix, we introduced some edge case regressions in 4.2.1 that have since been addressed.

**Comment by shilman** [comment] 2022-04-08 18:37
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.60 containing PR #17913 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2022-04-08 18:37 UTC
Labels: bug, dependencies, needs triage
