### ISSUE TITLE
[v7] Failed to load preset: "@storybook/react/preset" ERR! Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './preset' is not defined by "exports" in /Users/jeremytenjo/Desktop/starter-website/node_modules/@storybook/react/package.json

### ISSUE THREAD

**Issue by jeremytenjo** [storybookjs/storybook#19514] opened 2022-10-17 18:02 UTC
**Describe the bug**

Error when upgrading to v7

terminal output error:

```
WARN   Failed to load preset: "@storybook/react/preset"
ERR! Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './preset' is not defined by "exports" in /Users/jeremytenjo/Desktop/starter-website/node_modules/@storybook/react/package.json
```

**To Reproduce**
1. run `git clone https://github.com/jeremytenjo/starter-website --branch upgrade-to-storybook-7 && cd starter-website && npm i && npm run storybook:dev`
2. check terminal 
![image](https://user-images.githubusercontent.com/25231946/196249498-104877f5-c7d5-4d69-bf43-7261e54313c5.png)

**System**
```

  System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 95.0.2
    Safari: 16.0
  npmPackages:
    @storybook/addon-actions: 7.0.0-alpha.38 => 7.0.0-alpha.38 
    @storybook/addon-essentials: 7.0.0-alpha.38 => 7.0.0-alpha.38 
    @storybook/addon-interactions: 7.0.0-alpha.38 => 7.0.0-alpha.38 
    @storybook/addon-links: 7.0.0-alpha.38 => 7.0.0-alpha.38 
    @storybook/builder-vite: 7.0.0-alpha.38 => 7.0.0-alpha.38 
    @storybook/cli: 7.0.0-alpha.38 => 7.0.0-alpha.38 
    @storybook/react: 7.0.0-alpha.38 => 7.0.0-alpha.38 
    @storybook/testing-library: 0.0.14-next.0 => 0.0.14-next.0 
```

Thank you 🙏

**Comment by jaysalvat** [comment] 2022-10-18 15:44
Same here. Impossible to install.

**Comment by smallSohoSolo** [comment] 2022-12-12 03:33
same here

**Comment by skratchdot** [comment] 2022-12-17 06:32
i was running into this and i think it was due to my `.storybook/main.js` file in which i had:
```
framework: '@storybook/react',
```

i see that there has been some refactoring done regarding "frameworks" vs "renderers" etc. in the [migration doc](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#frameworkoptions-renamed) i saw some info about the `framework` field. i ended up installing `@storybook/react-webpack5` and changing my `main.js` file to have:
```
  framework: {
    name: '@storybook/react-webpack5',
    options: { fastRefresh: true },
  },
```

that got rid of the error from this issue.  after that i ran into a separate error in which my typescript syntax was not being recognized.  i think that's due to my app not having a babel config file.  i ran `npx sb@next babelrc` and that resolved the 2nd error i ran into.

i now have a storybook server that starts, but my old stories aren't rendering.  i'm going to work on resolving that now (i think this issue should be somewhat easy to solve).  i wanted to send a quick note before i forget to see if the above steps help anyone in this thread.

**Comment by skratchdot** [comment] 2022-12-17 06:38
i feel like we could improve this error in v7.  maybe checking if "framework" is a string. if it starts with `@storybook/`, make sure that it's using a v7 framework:
https://github.com/storybookjs/storybook/tree/next/code/frameworks

**Comment by tmeasday** [comment] 2022-12-18 05:38
@skratchdot did you run the automigrations when you upgraded (i.e. `npx sb@next upgrade --tag next`)? In theory it should have detected this situation and rewritten the framework field for you.

**Comment by skratchdot** [comment] 2022-12-18 09:12
> @skratchdot did you run the automigrations when you upgraded (i.e. `npx sb@next upgrade --tag next`)? In theory it should have detected this situation and rewritten the framework field for you.

yes- i did.  not sure why it didn't rewrite (if i answered a question wrong- or if my setup is odd). i've been working in a branch- so can retry at some point.  the only issue i have remaining is that "function calls to generate my csf3 stories" do not appear to be working. i'm going to log a separate issue for this, but want to have a minimal/reproducible use-case.

the remaining issue i have:

works:
```
const defaultStory = { ...someStoryJson };
export default defaultStory
```
doesn't work:
```
const defaultStory = getSomeStoryJson();
export default defaultStory;
```

**Comment by skratchdot** [comment] 2022-12-18 09:14
@tmeasday - actually, i lied in my last comment :)

i think i followed https://chromatic-ui.notion.site/Storybook-7-migration-guide-dbf41fa347304eb2a5e9c69b34503937 so the command i ran was:

```
npx storybook@next upgrade --prerelease
```

not:
```
npx sb@next upgrade --tag next
```

**Comment by shilman** [comment] 2022-12-18 18:55
FWIW those two commands are equivalent now

**Closed** 2022-12-20 16:58 UTC
Labels: bug, needs triage
