### ISSUE TITLE
[Bug]: Storybook 7.x storysource addon renders story json object instead of source

### ISSUE THREAD

**Issue by Profesor08** [storybookjs/storybook#23634] opened 2023-07-27 14:17 UTC
### Describe the bug

Adding addon `@storybook/addon-storysource` creates additional tab in addons panel. But instead of source code of story it shows json object, something like this:

```js
{
  args: {
    text: "Button"
  }
}
```

#### May be it is related to this issues:

#23484, #22641, #22922, #22362

### System

```
Environment Info:

  System:
    OS: Windows 10 10.0.22621
    CPU: (24) x64 AMD Ryzen 9 3900XT 12-Core Processor
  Binaries:
    Node: 20.3.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.7.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1992.0), Chromium (115.0.1901.183)
  npmPackages:
    @storybook/addon-actions: ^7.1.1 => 7.1.1
    @storybook/addon-backgrounds: ^7.1.1 => 7.1.1
    @storybook/addon-controls: ^7.1.1 => 7.1.1
    @storybook/addon-docs: ^7.1.1 => 7.1.1
    @storybook/addon-essentials: ^7.1.0 => 7.1.0
    @storybook/addon-links: ^7.1.1 => 7.1.1
    @storybook/addon-measure: ^7.1.1 => 7.1.1
    @storybook/addon-outline: ^7.1.1 => 7.1.1
    @storybook/addon-storysource: ^7.1.1 => 7.1.1
    @storybook/addon-toolbars: ^7.1.1 => 7.1.1
    @storybook/addon-viewport: ^7.1.1 => 7.1.1
    @storybook/blocks: ^7.1.0 => 7.1.0
    @storybook/react: ^7.1.0 => 7.1.0
    @storybook/react-vite: ^7.1.0 => 7.1.0
    @storybook/testing-library: ^0.2.0 => 0.2.0
```

**Comment by mayank99** [comment] 2023-07-27 17:51
duplicate of #22922

**Comment by valentinpalkovic** [comment] 2023-11-01 21:07
Closing, since this is a duplicate of https://github.com/storybookjs/storybook/issues/22922

**Closed by valentinpalkovic** 2023-11-01 21:07 UTC
Labels: bug, needs triage
