### ISSUE TITLE
[Bug]: Cannot read properties of undefined (reading 'FEATURES')

### ISSUE THREAD

**Issue by souhailmerroun** [storybookjs/storybook#20393] opened 2022-12-23 12:36 UTC
### Describe the bug

Cannot read properties of undefined (reading 'FEATURES')

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/8895242/209337058-ba6cec4a-1a1a-45c8-aba3-3e1f9f51b523.png">

### To Reproduce

```shell
- Fresh installation of nextjs app on github codespace
npx create-next-app@latest --typescript

- Setup nextjs storybook 
https://github.com/storybookjs/storybook/tree/next/code/frameworks/nextjs#getting-started
npx storybook@next init
```

### System

```shell
Environment Info:

  System:
    OS: Linux 5.4 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz
  Binaries:
    Node: 16.18.1 - ~/nvm/current/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - ~/nvm/current/bin/npm
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.14 => 7.0.0-beta.14 
    @storybook/addon-interactions: ^7.0.0-beta.14 => 7.0.0-beta.14 
    @storybook/addon-links: ^7.0.0-beta.14 => 7.0.0-beta.14 
    @storybook/blocks: ^7.0.0-beta.14 => 7.0.0-beta.14 
    @storybook/nextjs: ^7.0.0-beta.14 => 7.0.0-beta.14 
    @storybook/react: ^7.0.0-beta.14 => 7.0.0-beta.14 
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

**Comment by joshwooding** [comment] 2022-12-25 03:07
Hi, could you try using `@storybook/testing-library@0.0.14-next.1` it adds support for Storybook 7.

**Comment by Alex-Ferreli** [comment] 2022-12-26 16:35
I've updated dependencies at 7.0.0-beta.15 but I have the same error

**Comment by MrBuBBLs** [comment] 2023-01-02 02:06
Hi @joshwooding I can confirm that `@storybook/testing-library@0.0.14-next.1` solved it.
I was using Storybook 7 with NextJS 13 and encounter that same issue.

As of today, for other readers here, this seems to be fixed using :
`npm install -D @storybook/testing-library@next` or `pnpm add -D @storybook/testing-library@next`.

**Comment by Alex-Ferreli** [comment] 2023-01-02 09:06
I have tried with `@storybook/testing-library@0.0.14-next.1` in a fresh project and it work. But in my project the error is not gone.

My project use `@apollo/client` and `MSW` for mocking. Maybe there are some error in this plugins that cause the error

**Comment by Alex-Ferreli** [comment] 2023-01-04 18:02
Hi @yannbf, i have the command and this is the output:

```bash
=> Found "@storybook/instrumenter@7.0.0-beta.12"
info Has been hoisted to "@storybook/instrumenter"
info Reasons this module exists
   - Hoisted from "@storybook#jest#@storybook#instrumenter"
   - Hoisted from "@storybook#testing-library#@storybook#instrumenter"
info Disk size without dependencies: "2.95MB"
info Disk size with unique dependencies: "16.84MB"
info Disk size with transitive dependencies: "83.98MB"
info Number of shared dependencies: 105
=> Found "@storybook/addon-interactions#@storybook/instrumenter@7.0.0-beta.19"
info This module exists because "@storybook#addon-interactions" depends on it.
info Disk size without dependencies: "60KB"
info Disk size with unique dependencies: "13.95MB"
info Disk size with transitive dependencies: "80.86MB"
info Number of shared dependencies: 103
```

Seems like that i have 2 v7 version but one is beta-12 and one beta-19. I will try to fix the first beta-12 to beta-19 and see if it works!

**Comment by Alex-Ferreli** [comment] 2023-01-06 09:20
I have fixed `@storybook/instrumenter` version using yarn "resolutions" key field in `package.json`:
```json
"resolutions": {
  "@storybook/instrumenter": "7.0.0-beta.19"
}
```

Now I have only the correct version (`7.0.0-beta.19`) installed and it works. But I didn't understand why i have a `7.0.0-beta.12` installed, I didn't have it listed, maybe is fixed in some inner package?

**Comment by jg-germain** [comment] 2023-03-25 10:31
I started having this issue after installing `@storybook/jest` so anytime I use `import { expect } from '@storybook/jest';` I get "Cannot read properties of undefined (reading 'FEATURES')"

npm why @storybook/instrumenter:
```
@storybook/instrumenter@7.0.0-rc.8 dev
node_modules/@storybook/instrumenter
  @storybook/instrumenter@"7.0.0-rc.8" from @storybook/addon-interactions@7.0.0-rc.8
  node_modules/@storybook/addon-interactions
    dev @storybook/addon-interactions@"^7.0.0-rc.1" from the root project
  @storybook/instrumenter@"next" from @storybook/testing-library@0.0.14-next.1
  node_modules/@storybook/testing-library
    dev @storybook/testing-library@"^0.0.14-next.1" from the root project

@storybook/instrumenter@6.5.16 dev
node_modules/@storybook/jest/node_modules/@storybook/instrumenter
  @storybook/instrumenter@"^6.4.0" from @storybook/jest@0.0.10
  node_modules/@storybook/jest
    dev @storybook/jest@"^0.0.10" from the root project
```
I'm using storybook 7. 

Any idea how I can solve that?

**Comment by BorisZubchenko** [comment] 2023-03-26 22:23
@jg-germain, for me, works even without reinstalling

**Comment by yannbf** [comment] 2023-04-12 14:41
Hey everyone! This issue relates to a scenario where you end up having duplicated Storybook dependencies.
It's not a big deal if some of your dependencies are duplicated, but some of them might cause problems in Storybook, like the one described in this issue. 

This is caused by one of the following:
- Your lock file already contained some locked versions, and after upgrading Storybook, you end up with duplicated versions of certain packages e.g. `@storybook/core-common@7.0.0-beta.34, @storybook/core-common@7.0.2`. If this is the case, you can fix it by purging your lock file and rerunning install (or manually adjusting only the storybook deps in your lock file if you prefer)
- You have an addon that is not compatible with Storybook 7 yet. This means the addon likely depends on Storybook 6, and therefore you end up having duplicated dependencies e.g. `@storybook/addons@6.5.12, @storybook/addons@7.0.2`. This is a more concerning issue, and it's likely that you will have to disable that addon (and [request the maintainer to update it](https://github.com/storybookjs/storybook/issues/20529)) until it supports Storybook 7.
- You have upgraded to Storybook 7 but forgot to upgrade one of the packages e.g. you might have `@storybook/testing-library@0.14-next.0` instead of `@storybook/testing-library@0.1.0`. This is likely because you upgraded manually rather than running `npx storybook@latest upgrade`. In this case, all you have to do is upgrade the other packages. We highly recommend using storybook's upgrade command, to avoid situations like this.

All in all, we recently introduced a warning banner as part of the `storybook upgrade` experience, which will detect and tell whether there are duplicated dependencies, and from there you can use the guide to figure out what is the culprit, especially if the version difference is quite big:

![image](https://user-images.githubusercontent.com/1671563/231492418-024fa4ca-78ea-4657-aa49-aad05caf0d5c.png)

Unfortunately, there are many package managers out there, and they might behave differently, especially if they're in monorepos or not. We can't control how they behave, so normally deleting the lock file and reinstalling is a good solution to fix the issue. I believe there isn't much more we can do, so I'll be closing this issue and I hope this answer can serve as a guide as well to help other who end up in this scenario! Thank you!

**Closed by yannbf** 2023-04-12 14:41 UTC
Labels: bug, has workaround
