### ISSUE TITLE
6.3rc - storybook-build script hangs

### ISSUE THREAD

**Issue by hoffination** [storybookjs/storybook#15294] opened 2021-06-18 21:58 UTC
**Describe the bug**
After running the build script, the resulting script hangs and times out in our CI.

Last line before timeout:
`info => Output directory: /Users/bh/Dev/<project>/storybook-dist`

**To Reproduce**
https://github.com/hoffination/storybook-timeout-repro
Hoping to see if anyone else has come across this.
Didn't see any others recently in the issues.

**System**
System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Safari: 14.1.1
  npmPackages:
    @storybook/addon-a11y: 6.3.0-rc.11 => 6.3.0-rc.11 
    @storybook/addon-actions: 6.3.0-rc.11 => 6.3.0-rc.11 
    @storybook/addon-essentials: 6.3.0-rc.11 => 6.3.0-rc.11 
    @storybook/addon-links: 6.3.0-rc.11 => 6.3.0-rc.11 
    @storybook/addon-storysource: 6.3.0-rc.11 => 6.3.0-rc.11 
    @storybook/angular: 6.3.0-rc.11 => 6.3.0-rc.11 
    @storybook/builder-webpack5: 6.3.0-rc.11 => 6.3.0-rc.11 
    @storybook/manager-webpack5: 6.3.0-rc.11 => 6.3.0-rc.11 
    @storybook/preset-scss: ^1.0.3 => 1.0.3 (tried with and without this)

**Additional context**
Same issue is present on 6.3.0-rc.0, updated in an attempt to fix.

I've tried dropping my `node_modules/` and `package-lock.json`

**Comment by shilman** [comment] 2021-06-19 05:08
Possible duplicate to #14405

**Comment by hoffination** [comment] 2021-06-21 16:42
@shilman Was able to reproduce here: https://github.com/hoffination/storybook-timeout-repro

**Comment by JSMike** [comment] 2021-06-21 18:26
I'm experiencing this issue as well, it looks to be different than #14405 in that it gets beyond 99% and gets to

```
info => Output directory: /path/to/build/dir
```

This is only happening when I add angular stories. I have some `@storybook/html` stories that work just fine if I exclude the angular config. Both are set up to use webpack5

**Comment by meriturva** [comment] 2021-06-21 19:22
I think it is duplicate to https://github.com/storybookjs/storybook/issues/15227

It is related to scss worker not correctly terminated

**Comment by JSMike** [comment] 2021-06-21 19:54
Note, I'm also getting the following warning up above in the logs.

```
WARN DefinePlugin
WARN Conflicting values for 'process.env'
WARN DefinePlugin
WARN Conflicting values for 'process.env.NODE_ENV'
```

This is even with using the webpackDefine plugin to set a NODE_ENV the same as this previous issue: https://github.com/storybookjs/storybook/issues/14257#issuecomment-842175514

Is something getting stuck in dev mode and listening?

**Comment by JSMike** [comment] 2021-06-21 19:54
@meriturva That looks like it is the same root cause.

**Comment by shilman** [comment] 2021-06-22 07:32
Closing as duplicate to #15227 & have copied repro there

**Closed by shilman** 2021-06-22 07:32 UTC
Labels: bug, build-storybook, needs reproduction
