### ISSUE TITLE
[Documentation]: trouble with IS_STORYBOOK variable returning undefined

### ISSUE THREAD

**Issue by JasonPhat** [storybookjs/storybook#25167] opened 2023-12-11 09:42 UTC
### Describe the problem

I can't seem to console log the status of storybook using IS_STORYBOOK. I am trying to confirm that storybook is running in the browser, i.e using console.log(window.IS_STORYBOOK) in dev tools. 

The documentation isn't super clear on what to do here so I'm not sure if it's something I'm doing wrong, or there's an issue with the variable not working. It just returns as undefined even though storybook is running in the browser. I thought the variable might be node specific, but you also mention that process.env.STORYBOOK is available to use, so I assumed they're different things.

### Additional context

https://storybook.js.org/docs/faq#how-can-my-code-detect-if-it-is-running-in-storybook

using Storybook 7.5.3 for vue3-webpack5

**Comment by shilman** [comment] 2023-12-24 16:48
Storybook has an outer window called "the manager" which is the sidebar & addon UI, and an inner iframe called "the preview" which is where your stories render. If you `console.log(window.IS_STORYBOOK)` make sure you're running that in the preview iframe, which can be selected in the browser dev tools

**Comment by spaghettiguru** [comment] 2024-01-10 08:39
It doesn't work indeed - `window.IS_STORYBOOK` is undefined in preview iframe :(

**Comment by mimamuh** [comment] 2024-01-17 13:52
Same for me since storybook 7 - also using `vue3-webpack5`. `window.IS_STORYBOOK` does not exist in the preview-iframe in Storybook 7.5.3. I've tested it with Storybook 7.6.9 too, but the variable is still not available. It doesn't matter if I `console.log(...)` it in the codebase or use the developer console: `window.IS_STORYBOOK` is `undefined`.

**Comment by JasonPhat** [comment] 2024-01-17 15:04
> If you `console.log(window.IS_STORYBOOK)` make sure you're running that in the preview iframe, which can be selected in the browser dev tools

This doesn't seem to make any difference. So why is the variable just not declared in the manager window, so that it's available everywhere? The whole thing is storybook, right? Why am I checking if I'm using storybook in the preview window?

**Comment by agriffis** [comment] 2024-04-04 16:28
The Storybook team is mistakenly classifying this issue is user error (along with #26641)

This is an actual regression. The setting of `IS_STORYBOOK` disappeared in 534e49cfd0ba4c8bb778249638b92c6f49e70ef7. It is no longer being set by Storybook in any context, preview frame or otherwise.

The easiest way to get it back is to add to your own `.storybook/preview-head.html`:

```html
<script>
  // This used to be defined by Storybook, see https://github.com/storybookjs/storybook/issues/25167
  window.IS_STORYBOOK = true
</script>
```

**Comment by valentinpalkovic** [comment] 2024-04-04 21:20
@tmeasday Was the env variable intentionally removed along with the SSV6 removal?

**Comment by jonniebigodes** [comment] 2024-04-04 21:45
Chiming in here. If that's the case and the variable was removed, let me know, and I'll gladly update the documentation accordingly.

**Comment by tmeasday** [comment] 2024-04-04 23:23
It looks like it was something previously set by the SSv6 API: 
![image](https://github.com/storybookjs/storybook/assets/132554/01efb3ba-7150-405b-9099-6d13d9049d76)

If so, it's been missing with the v7 store enabled since 6.x when that API was introduced, and by default since 7.x.

We could add it back, but given the above I'd be inclined to just remove it from the docs. You can check for `!!__STORYBOOK_PREVIEW__` instead.

**Comment by mimamuh** [comment] 2024-04-05 07:03
@tmeasday Actually this variable was quite helpful. We use storybook-server and had trouble with some DOM loading related events fired by storybook preview first before the content was loaded from the server and this `IS_STORYBOOK` variable helped a lot to handle it by having a different solution for the stories only. I was quite happy that the docs mentioned it. I would plead for reintroducing it, actually.

**Comment by agriffis** [comment] 2024-04-05 11:15
Dev timelines and user timelines can be pretty different. To y'all, it feels like SSv6 was retired a long time ago. Meanwhile, users are only now upgrading and letting go of `storyStoreV7: false`. Upgrades take time and effort, and often don't happen until they must.

So users are still going to be stumbling on this for a while. I don't need it restored personally, since AFAIK it's the same thing to put it in `.storybook/preview-head.html` as mentioned earlier. But I think it would be better to put it back and then you don't even have to change the docs :smile:

**Comment by tmeasday** [comment] 2024-04-08 04:58
@mimamuh does checking for `!!window.__STORYBOOK_PREVIEW__` solve the problem though?

I guess my inclination is to just not clutter up the global namespace. We need `__STORYBOOK_PREVIEW__`, so maybe we should just stick to (and document) one thing, rather than multiple. 

I appreciate it's a breaking change, but 8.0 and the move away from `storiesOf`/SSv6 feels like the right time to make it (even if we could have done it more smoothly)!

**Comment by mimamuh** [comment] 2024-04-09 08:18
@tmeasday Yeah, this works too.

**Comment by agriffis** [comment] 2024-04-09 14:02
> @agriffis totally take your point but I would counter that plenty of folks _have_ been on these new APIs for literally years now and this is the first I am hearing about it, so I am thinking this isn't the most widely used piece of our API :)

Yep, no worries.

**Comment by Codex-** [comment] 2024-06-19 23:56
I encountered this issue as the documentation still references using `IS_STORYBOOK`: https://storybook.js.org/docs/faq#how-can-my-code-detect-if-it-is-running-in-storybook

If there is no desire to restore this, should the references to it be removed from the documentation? 🤔

**Comment by bmulholland** [comment] 2024-09-06 09:39
Yeah, I'd love to know what the officially-supported alternative is, and the docs are where I go to see that. As of now, the official recommendation seems to be something that hasn't been supported for a year :\\. I came here after wasting 10 minutes because of it.

**Comment by tmeasday** [comment] 2024-09-06 23:57
@jonniebigodes can we change the docs here?

**Comment by jonniebigodes** [comment] 2024-11-22 21:47
Going to close this issue as the documentation is already fixed and will be published shortly.

**Closed by jonniebigodes** 2024-11-22 21:47 UTC
Labels: documentation

**Comment by bmulholland** [comment] 2024-11-25 12:32
@jonniebigodes Could we please be notified when the new docs are out? I'd like to see what's recommended now. I just checked and they still talk about IS_STORYBOOK.
