### ISSUE TITLE
[Doc] How to expand a Story's source code by default

### ISSUE THREAD

**Issue by thien-do** [storybookjs/storybook#14850] opened 2021-05-07 16:25 UTC
**What's the problem?**

I searched a lot, and found many related resource, but none of them explain how to expand a **single** story's code. I even found PRs to have that setting globally, but can't find one that expand a CSF's Story

**Is there documentation on this?**

No, unfortunately. There is no "isExpanded", "withSource" or "state" on the doc

**Additional context**

The "Canvas" component has an "isExpanded" and "Preview" has "withSource", so I tried these but none of them work:

![image](https://user-images.githubusercontent.com/5953369/117480231-8749ae80-af8b-11eb-8d26-7c891dbf84ee.png)

Related:
- https://github.com/storybookjs/storybook/issues/10430
- https://github.com/storybookjs/storybook/pull/14729

**Comment by littlewish89** [comment] 2021-05-07 22:16
Run

**Comment by Tim-arts** [comment] 2021-05-21 19:56
Any update on this? All the closed issues are very confusing because it led people think that the current matter has been solved, but is actually not :/

**Comment by shilman** [comment] 2021-05-22 00:11
which version are you using? can confirm that `docs.source.state = 'open'` is working in the latest alpha.

```
npx sb@next upgrade --prerelease
```

Code: 

https://github.com/storybookjs/storybook/blob/next/examples/official-storybook/stories/addon-controls.stories.tsx#L34-L38

Demo:

https://next--storybookjs.netlify.app/official-storybook/?path=/docs/addons-controls--basic

**Comment by thien-do** [comment] 2021-05-22 05:20
@shilman I'm sorry but that is for the whole page. We're looking to auto-open one specific story, in CSF :(

```tax
export const MyStory = () => <div />

// This does NOT work, but I think it should?
MyStory.parameters.docs.source.state = 'open'
```

**Comment by Tim-arts** [comment] 2021-05-22 05:40
Hello @shilman, thank you for bringing light on that subject. @thien-do I'm actually the one who got things mixed up because the issue is linked to the previous ones while it's slightly differently (but talking about two different things).

Anyway I'm really looking forward for the alpha to be released into the stable branch in a near future, thank you for your work!

**Comment by shilman** [comment] 2021-05-22 05:41
Aha thanks for clarifying @thien-do. I'm looking into a fix right now.

**Comment by shilman** [comment] 2021-05-28 08:23
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-beta.3 containing PR #15070 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2021-05-28 08:23 UTC
Labels: P0, addon: docs, block: source, bug

**Comment by shilman** [comment] 2021-05-28 08:40
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-beta.4 containing PR #15070 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```
