### ISSUE TITLE
[Bug]: Error on storybook in production build using version 7.0.18

### ISSUE THREAD

**Issue by rioarray** [storybookjs/storybook#22825] opened 2023-05-27 17:20 UTC
### Describe the bug

Hi..

I think this is a bug, because when i running locally (with command `yarn storybook`). The `"docs"` inside component tree is running well and show.

But when i try to simulate production build with command `yarn build-storybook`, and running it as locally. It show the error like this below when i open my `"docs"` that auto generated by storybook.
```
Uncaught (in promise) ReferenceError: Preview$1 is not defined
    at ./node_modules/@storybook/addon-docs/dist/DocsRenderer-EYKKDMVH.mjs (index.mjs:103:1)
    at Function.__webpack_require__ (runtime~main.865d2a89.iframe.bundle.js:1:381)
    at async Object.renderer (chunk-GRJZJKJ4.mjs:9:1)
    at async CsfDocsRender.renderToElement (runtime.js:85:1904)
```

This is another error console when i move into another story and back again into `"docs"` menu
```
chunk-GRJZJKJ4.mjs:9 Uncaught (in promise) TypeError: DocsRenderer is not a constructor
    at Object.renderer (chunk-GRJZJKJ4.mjs:9:1)
    at async CsfDocsRender.renderToElement (runtime.js:85:1904)
```

screenshots: https://gyazo.com/29cc5ced5b73b4b6c84f16ee50c116d0

### To Reproduce

- execute `yarn build-storybook`
- run `serve storybook-static` (i'm using this library to run the storybook-static https://www.npmjs.com/package/serve)

### System

```shell
System:
    OS: macOS 12.6.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 113.0.2
    Safari: 16.5
  npmPackages:
    @storybook/addon-essentials: ^7.0.18 => 7.0.18
    @storybook/addon-interactions: ^7.0.18 => 7.0.18
    @storybook/addon-links: ^7.0.18 => 7.0.18
    @storybook/addon-styling: ^1.0.8 => 1.0.8
    @storybook/blocks: ^7.0.18 => 7.0.18
    @storybook/nextjs: ^7.0.18 => 7.0.18
    @storybook/react: ^7.0.18 => 7.0.18
    @storybook/testing-library: ^0.1.0 => 0.1.0
```

**Comment by lnchit** [comment] 2023-05-29 02:13
I got the same issue with storybook version 7.0.17 and react 18 as well

**Comment by koloer-blus** [comment] 2023-05-29 06:43
I also meet this problem!!!

**Comment by lnchit** [comment] 2023-05-29 07:58
@rioarray , @koloer-blus , i have solved this issue by upgrading the storybook and all the other addons from 7.0.17 to 7.0.18.

Step to resolve

1. Run npx upgrade for storybook
`npx storybook@latest upgrade`
2. uninstall all stroybook addons, and install back with latest version

Hope it helps

**Comment by rioarray** [comment] 2023-05-29 10:24
Hi @lnchit, previously i already upgrade from storybook v7.0.17 into v7.0.18 but the error still same.

But thanks for your answer, it give me idea to remove `yarn.lock` first and then `yarn install` again. And now, the issue was gone.

Btw. I'm using NextJS as default react framework. And then i'm install storybook with this command `npx storybook@latest init` And there's no `core: { builder: '...' }` as an config in `.storybook/main.ts`.

**Comment by shilman** [comment] 2023-05-30 03:33
Sounds like some kind of lockfile issue. If anybody has a reproduction on a new project, we'd love to take a look at it.

**Comment by koloer-blus** [comment] 2023-05-30 12:16
> Sounds like some kind of lockfile issue. If anybody has a reproduction on a new project, we'd love t

Thanks for your answer. I solve this problem by removing pnpm-lock.yaml and executing pnpm install again.

**Comment by nataliepina** [comment] 2023-05-30 15:57
I have also encountered this problem. I updated it to 7.0.18. 
It runs fine locally, however, it is breaking in CI and I can see the same errors locally when running `npx http-server storybook_static` 
I've attempted to remove my node_modules and package-lock. 

I am seeing these errors `TypeError: DocsRenderer is not a constructor` and `Cannot access 'Welcome_stories' before initialization` 

No core set in my main.js file.

`const customWebpack = require("./webpack.config");
module.exports = {
  stories: [
    "./docs/stories/Welcome.stories.mdx",
    "./docs/stories/Colors.stories.mdx",
    "./docs/stories/Typography.stories.mdx",
    "../packages/**/*.stories.@(tsx|mdx)"
  ],
  webpackFinal: config => {
    return {
      ...config,
      ...customWebpack
    };
  },
  addons: [
    {
      name: "@storybook/addon-essentials",
      options: {
        actions: false
      }
    },
    "@storybook/addon-a11y"
  ],
  features: {
    previewMdx2: true
  },
  framework: {
    name: "@storybook/react-webpack5",
    options: {}
  },
  docs: {
    autodocs: true
  }
};
`

**Comment by koloer-blus** [comment] 2023-05-31 05:28
> I have also encountered this problem. I updated it to 7.0.18. It runs fine locally, however, it is breaking in CI and I can see the same errors locally when running `npx http-server storybook_static` I've attempted to remove my node_modules and package-lock.
> 
> I am seeing these errors `TypeError: DocsRenderer is not a constructor` and `Cannot access 'Welcome_stories' before initialization`
> 
> No core set in my main.js file.
> 
> ```
> const customWebpack = require("./webpack.config");
> module.exports = {
>   stories: [
>     "./docs/stories/Welcome.stories.mdx",
>     "./docs/stories/Colors.stories.mdx",
>     "./docs/stories/Typography.stories.mdx",
>     "../packages/**/*.stories.@(tsx|mdx)"
>   ],
>   webpackFinal: config => {
>     return {
>       ...config,
>       ...customWebpack
>     };
>   },
>   addons: [
>     {
>       name: "@storybook/addon-essentials",
>       options: {
>         actions: false
>       }
>     },
>     "@storybook/addon-a11y"
>   ],
>   features: {
>     previewMdx2: true
>   },
>   framework: {
>     name: "@storybook/react-webpack5",
>     options: {}
>   },
>   docs: {
>     autodocs: true
>   }
> };
> ```

You can try to set `core: {}`, because `core` will have a default value, when you do not explicitly set its value

**Comment by rdebeasi** [comment] 2023-06-14 14:38
I was also encountering this error with `webpack@5.84.0`. Deleting and re-creating `yarn.lock` upgraded the project to  `webpack@5.86.0`, which fixed the error.

**Comment by thanhtran-ct** [comment] 2023-06-16 04:10
@shilman It's not a bug by Storybook and there's solution to it. This can be closed now.

**Comment by trongthanh** [comment] 2023-06-16 04:12
This is not a bug by Storybook and there's a solution. Let's close this ticket.

**Closed by trongthanh** 2023-06-16 04:12 UTC
Labels: bug, dependencies, needs reproduction, yarn / npm
