### ISSUE TITLE
Storybook build failed after updating to version 6.5.3

### ISSUE THREAD

**Issue by suhomozgy-andrey** [storybookjs/storybook#18276] opened 2022-05-19 18:26 UTC
**Describe the bug**
Running `storybook` after updating to the latest version causes webpack error.
The following packages were updated:
![image](https://user-images.githubusercontent.com/5196487/169372662-a3a807f7-0662-434a-949e-e6d9e71f07da.png)
In the previous configuration, everything worked fine. The latest master branch is deployed here https://panthera-tailwind.vercel.app/?path=/story/box-shadow--box-shadow. 

**To Reproduce**
I create a copy of my repo and added exactly the same packages and configuration.
Pull the changes from `https://github.com/suhomozgy-andrey/storybook-reproduction-19-05-2022`. Run `npm run storybook`.
The following error appears
![image](https://user-images.githubusercontent.com/5196487/169372840-819c9379-deac-4d7d-b13d-e4788406303f.png)

**System**
```
  System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.9.0 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 7.21.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Firefox: 98.0.2
    Safari: 15.5
  npmPackages:
    @storybook/addon-actions: ^6.5.3 => 6.5.3 
    @storybook/addon-essentials: ^6.5.3 => 6.5.3 
    @storybook/addon-links: ^6.5.3 => 6.5.3 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/addons: ^6.5.3 => 6.5.3 
    @storybook/builder-webpack5: ^6.5.3 => 6.5.3 
    @storybook/manager-webpack5: ^6.5.3 => 6.5.3 
    @storybook/preset-scss: ^1.0.3 => 1.0.3 
    @storybook/react: ^6.5.3 => 6.5.3 
    @storybook/theming: ^6.5.3 => 6.5.3 
```

**Additional information**

`.storybook/main.js` configuration:
```
const path = require("path");

module.exports = {
	stories: ["../src/**/*.stories.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
	addons: [
		"@storybook/addon-links",
		"@storybook/addon-essentials",
		{
			name: "@storybook/preset-scss",
			options: {
				cssLoaderOptions: {
					modules: true
				}
			}
		},
		{
			name: "@storybook/addon-postcss",
			options: {
				postcssLoaderOptions: {
					implementation: require("postcss", {
						extensions: [".scss", ".css"],
						modules: true
					})
				}
			}
		}
	],
	core: {
		builder: "webpack5"
	},
	webpackFinal: async (config) => {
		config.module.rules.push({
			test: /\.scss/,
			use: ["sass-loader", { loader: "postcss-loader" }],
			include: path.resolve(__dirname, "../")
		});
		return config;
	}
};
```

**Comment by shilman** [comment] 2022-05-20 03:01
@ndelangen @valentinpalkovic this looks related to the IgnorePlugin stuff you added for react18. can you please take a look and see if there's anything you can figure out?

**Comment by valentinpalkovic** [comment] 2022-05-20 21:00
@shilman I will take a look in the beginning of next week :)

**Comment by igor-dv** [comment] 2022-05-25 11:01
if anyone is looking for the workaround (that worked for us), you can replace the problematic `IgnorePlugin` with the instance from your webpack's version. 

something like this:

```js
const webpack = require('webpack');

module.exports = {
    /* whatever is your configuration here */
    webpackFinal: async (config) => ({
        plugins: [
            ...config.plugins.filter(plugin => plugin.constructor.name !== 'IgnorePlugin'),
            new webpack.IgnorePlugin({
                resourceRegExp: /react-dom\/client$/,
                contextRegExp: /(app\/react|app\\react|@storybook\/react|@storybook\\react)/
            }),
        ],
    }),
};
```

of course you can just copy the resourceRegExp and contextRegExp from the existing one.
```js
config.plugins.map(plugin => {
  if (plugin.constructor.name === 'IgnorePlugin') {
    new webpack.IgnorePlugin({
        resourceRegExp: plugin.options.resourceRegExp,
        contextRegExp: plugin.options.contextRegExp
    }),
  }

  return plugin;
})
```

**Comment by valentinpalkovic** [comment] 2022-05-26 10:20
@suhomozgy-andrey I tried to start the repro example (https://github.com/suhomozgy-andrey/storybook-reproduction-19-05-2022) but it didn't started at all due to an `require not found error`. I have deleted the `package-lock.json` and reinstalled the dependencies (used npm 8.10.0, instead of 7.21.1).

After fixing an issue in your `preview.js` (import "../src/input.css"; not available) and installing `@storybook/testing-library` (which is required but was not listed in your package.json) and installing the latest storybook dependencies, storybook started without any issues. You can see the made changes here: https://github.com/suhomozgy-andrey/storybook-reproduction-19-05-2022/pull/1

Therefore, please delete your node_modules folder and the package-lock.json and use the latest npm version and try it again.

**Comment by suhomozgy-andrey** [comment] 2022-05-26 10:35
@valentinpalkovic thank you for an update... looks like I missed the part with `src/index.css` when was creating repro PR. will check in my project and respond to you here

**Comment by suhomozgy-andrey** [comment] 2022-05-26 10:51
Yes, everything works fine with the latest `npm`. Also removing `node_modules` and `package-lock.json` was helpful! Thanks!
Will you close the issue @valentinpalkovic or I will do it?

**Comment by valentinpalkovic** [comment] 2022-05-26 11:50
I can close it :)

**Closed by valentinpalkovic** 2022-05-26 11:50 UTC
Labels: bug, has workaround, webpack5, linear

**Comment by valen22br** [comment] 2022-06-08 14:21
It seems that version 6.5.7 brought this bug back:
![Screen Shot 2022-06-08 at 10 20 20 AM](https://user-images.githubusercontent.com/26287220/172640414-1e351785-2054-422f-8572-4616ef6c4367.png)
![Screen Shot 2022-06-08 at 10 18 37 AM](https://user-images.githubusercontent.com/26287220/172640438-a2d6a28c-eb3a-4146-9bd2-c6cdb37b76cc.png)

**Comment by FBNitro** [comment] 2022-06-08 16:05
Also seeing this on 6.5.7.  I'm using the workaround listed here: https://github.com/storybookjs/storybook/issues/18276#issuecomment-1137101774

**Comment by valen22br** [comment] 2022-06-15 13:58
Hello :)
I can still see the problem with version `6.5.9`. I know that we have the workaround(https://github.com/storybookjs/storybook/issues/18276#issuecomment-1137101774), but I want to know if that will be the permanent solution or not.

**Comment by FBNitro** [comment] 2022-06-16 01:56
> @FBNitro @valen22br did you try removing your lockfile & reinstalling?

Sorry @shilman  that's not an option for me.  I'm in a large corporate environment and lockfile updates are monitored.  If I wiped it and recreated it (basically upgrading all packages) my PR would be rejected.  If that is the fix, it sounds like one the dependencies needs to be upgraded.

**Comment by shilman** [comment] 2022-06-16 04:21
@FBNitro  did you try it in service if debugging the problem?

**Comment by valentinpalkovic** [comment] 2022-06-16 06:48
@FBNitro , @valen22br 

If you are using npm, please execute the following command and let me know, if this has fixed the issue:

```
$ npm update @storybook/core-common @storybook/manager-webpack5 @storybook/react @storybook/telemetry @storybook/core-common @storybook/react @storybook/source-loader @storybook/addon-essentials @storybook/builder-webpack5
```

**Comment by FBNitro** [comment] 2022-06-20 20:59
Sorry I didn't reply sooner, I've got a couple things on the go.

I moved up from 6.5.7 to 6.5.9, that made no difference.

@valentinpalkovic: 
-  npm update the packages above made no difference.  (That's now I upgraded from 6.5.7 to 6.5.9)
- I confirmed that I have webpack@4.46.0, and webpack@5.73.0 in my package lock (npm ls webpack shows both as expected)

@shilman:
I tried both a storybook build and start, both give me the same results.  It's Monday, my brain isn't processing your comment fully, was there something else you wanted me to try?

**Comment by FBNitro** [comment] 2022-06-20 23:14
This worked for me (note I am using NPM workspaces, I'm not sure if that could have any relation):

- Removed webpack, *-loader (webpack loaders), @storybook* from my package.json
- Removed all the node_module folders from root and the workspaces (we have a clean script for this)
- `npm install`
- This left my package-lock intact, but removed everything related to webpack and storybook
- Added back all the webpack, *-loader, @storybook* packages in package.json
- `npm install`
- And my build is working again.

The big change that I have observed in package-lock is that webpack 5 is in the root of the package-lock file now, previously webpack 4 was in the root.  This change caused a number of packages in package-lock to move around and make diffs difficult.

**Comment by shilman** [comment] 2022-06-21 00:05
@FBNitro glad you figured it out! sorry there was a typo in my comment above. i meant "even if you are unable to checkin a completely refreshed lockfile, you could try completely refreshing your lockfile in order to help debug the problem." sounds like your solution of a partial refresh did the trick, though! 🎉

**Comment by nkalinov** [comment] 2023-11-10 10:24
I had multiple Webpack 5.x versions and `yarn dedupe webpack` fixed it for me.
