### ISSUE TITLE
[Bug]: v7/csf3 stories are not recognized when functions generate the csf format

### ISSUE THREAD

**Issue by skratchdot** [storybookjs/storybook#20321] opened 2022-12-18 17:16 UTC
### Describe the bug

I have 2 basic stories, but only 1 "renders" in my storybook v7 migration.  It appears that stories might be statically resolved instead of using the type of module resolution I would expect?

This story "works":

`story-testy-one.stories.tsx`:
```jsx
const StoryTesty = ({ value }) => {
  return (
    <div>
      <div>value is {value ? 'true' : 'false'}</div>
    </div>
  );
};

const MyDefault = {
  component: StoryTesty,
};

export default MyDefault;
export const True = { args: { value: true } };
export const False = { args: { value: false } };
```

This story (which gets the `MyDefault` json/data from a function call), does not "work":
`story-testy-two.stories.tsx`:
```jsx
const StoryTesty = ({ value }) => {
  return (
    <div>
      <div>value is {value ? 'true' : 'false'}</div>
    </div>
  );
};

const getit = () => {
  const MyDefault = {
    component: StoryTesty,
  };
  return { MyDefault };
};

const { MyDefault } = getit();

export default MyDefault;
export const True = { args: { value: true } };
export const False = { args: { value: false } };

```

### To Reproduce

the issue is reproduced in this repo:
- https://github.com/skratchdot/storybook-7-issue

here is the component and 2 stories that should work IMO:
- https://github.com/skratchdot/storybook-7-issue/tree/main/src/components

i published the storybook to a gh-pages branch here:
- source: https://github.com/skratchdot/storybook-7-issue/tree/gh-pages
- site: https://projects.skratchdot.com/storybook-7-issue/

```shell
git clone git@github.com:skratchdot/storybook-7-issue.git
cd storybook-7-issue
yarn
yarn storybook
```

### System

```shell
Environment Info:

  System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 18.7.0 - ~/.asdf/installs/nodejs/18.7.0/bin/node
    Yarn: 3.3.0 - ~/.asdf/installs/nodejs/18.7.0/bin/yarn
    npm: 8.15.0 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 108.0
    Safari: 16.2
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.12 => 7.0.0-beta.12 
    @storybook/addon-interactions: ^7.0.0-beta.12 => 7.0.0-beta.12 
    @storybook/addon-links: ^7.0.0-beta.12 => 7.0.0-beta.12 
    @storybook/blocks: ^7.0.0-beta.12 => 7.0.0-beta.12 
    @storybook/node-logger: ^7.0.0-beta.12 => 7.0.0-beta.12 
    @storybook/preset-create-react-app: ^4.1.2 => 4.1.2 
    @storybook/react: ^7.0.0-beta.12 => 7.0.0-beta.12 
    @storybook/react-webpack5: ^7.0.0-beta.12 => 7.0.0-beta.12 
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

**Comment by shilman** [comment] 2023-01-03 22:15
@skratchdot this is the expected behavior. stories need to be statically analyzable to work with `storyStoreV7`. We need to improve the documentation around this limitation, so I'm taking that as a follow-up task. We don't plan on fixing the underlying issue.

**Comment by shilman** [comment] 2023-04-21 11:02
closing as dupe to https://github.com/storybookjs/storybook/issues/21703

**Closed by shilman** 2023-04-21 11:02 UTC
Labels: question / support, documentation, story index
