### ISSUE TITLE
Installing older version for storybook

### ISSUE THREAD

**Issue by rajanlagah** [storybookjs/storybook#14848] opened 2021-05-07 13:38 UTC
**What's the problem?**
Clear and concise statement of what's troubling you.
I am facing error like 
```
The react-scripts package provided by Create React App requires a dependency:

  "babel-loader": "8.1.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of babel-loader was detected higher up in the tree:

  client/node_modules/babel-loader (version: 8.2.2) 

Manually installing incompatible versions is known to cause hard-to-debug issues.
```

To debug it I did 
``` 
npm ls babel-loader
```
and got 
<img width="559" alt="Screenshot 2021-05-07 at 6 59 06 PM" src="https://user-images.githubusercontent.com/82951880/117457214-a1bd6100-af66-11eb-9391-ccdcb3f8dce5.png">

The latest version for babel in react-script@latest is 8.1.0 but storybook is using 8.2.0

So Do i have any way to install older version of storybook in my react project 
 
**Is there documentation on this?**
If this is documented at https://storybook.js.org/docs/ but the documentation is incomplete or unclear, link to it here.

**Additional context**
what i did
```
npx sb init
```
This is installing the latest version of storybook and i think 6.1.14 will work for me as i have that in my older storybook projects.

**Comment by lagahrajan** [comment] 2021-05-07 18:37
In case anybody has the same requirements then run this
```
yarn add -D @storybook/addon-actions@6.1.14 @storybook/addon-essentials@6.1.14 @storybook/addon-links@6.1.14 @storybook/node-logger@6.1.14 @storybook/react@6.1.14
```

This worked for me

**Comment by littlewish89** [comment] 2021-05-07 22:15
Command

**Comment by shilman** [comment] 2021-05-08 02:08
Yes, you can edit the versions in your package.json by hand.

**Comment by merceyz** [comment] 2021-05-08 18:33
Duplicate of https://github.com/storybookjs/storybook/issues/4764
See https://github.com/storybookjs/storybook/issues/4764#issuecomment-740785850

**Comment by shilman** [comment] 2021-05-09 08:40
closing as dupe to #4764

**Closed by shilman** 2021-05-09 08:40 UTC
Labels: duplicate, question / support, yarn / npm
