### ISSUE TITLE
6.4.1: something removes autofocus from all inputs

### ISSUE THREAD

**Issue by Hypnosphi** [storybookjs/storybook#16847] opened 2021-11-30 19:55 UTC
Reproduction: https://github.com/Hypnosphi/storybook-autofocus

It's probably something non-react, because react devtools still show `autoFocus: true`:
<img width="589" alt="Screenshot 2021-11-30 at 20 55 42" src="https://user-images.githubusercontent.com/6651625/144118409-a3d2683d-70e0-4e94-9e2d-9f926ae37e21.png">

**Comment by Hypnosphi** [comment] 2021-11-30 20:16
Looks like the problem is that React tries to focus the input while `<div id="root">` is hidden by these styles: https://github.com/storybookjs/storybook/blob/next/lib/core-common/src/templates/base-preview-head.html#L10

**Comment by tmeasday** [comment] 2021-11-30 23:44
Ok, this has come up in a couple contexts, interesting about the autofocus @Hypnosphi.

The change I made here was fixing what was clearly an unintended bug (`.sb-main` didn't exist):

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/132554/144145671-607a1f64-104d-4562-aff1-c444c3a78a8d.png">

However, I guess the problem is that (at least the React) framework(s) don't call `showMain` *before* rendering the story. I'm not really sure anyone knows what the correct semantics for this should be. I'm a bit reticent to change the `showMain` behaviour in the frameworks outside of a major version bump.

@shilman what do you think we should do? One option would be to make the "loading story" spinner an *overlay* over the story, so we don't need to hide the story while preparing. Then we could go back to the old "broken" behaviour of having the story always be visible.

**Comment by tmeasday** [comment] 2021-11-30 23:45
cc @MichaelArestad

**Comment by shilman** [comment] 2021-12-01 01:11
@tmeasday I agree that reverting the change and hacking an overlay is the safest path here!

**Comment by shilman** [comment] 2021-12-01 06:49
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.3 containing PR #16850 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2021-12-01 06:49 UTC
Labels: bug, needs triage
