### ISSUE TITLE
[Bug]: TypeError: Cannot redefine property: default

### ISSUE THREAD

**Issue by mbret** [storybookjs/storybook#23684] opened 2023-08-02 12:06 UTC
### Describe the bug

```
Cannot redefine property: default
TypeError: Cannot redefine property: default
    at Function.defineProperty (<anonymous>)
    at ./node_modules/@storybook/nextjs/dist/preview.js (https://storybook.noprod.lacollection.io/158.8196cf66.iframe.bundle.js:401:22094)
    at __webpack_require__ (https://storybook.noprod.lacollection.io/runtime~main.6bb8e3c2.iframe.bundle.js:1:381)
    at Object.getProjectAnnotations [as nextFn] (https://storybook.noprod.lacollection.io/main.21ee001c.iframe.bundle.js:1:139194)
    at https://storybook.noprod.lacollection.io/sb-preview/runtime.js:4:78234
    at Array.forEach (<anonymous>)
    at SynchronousPromise4._runResolutions (https://storybook.noprod.lacollection.io/sb-preview/runtime.js:4:78175)
    at SynchronousPromise4.then (https://storybook.noprod.lacollection.io/sb-preview/runtime.js:4:75717)
    at PreviewWeb.getProjectAnnotationsOrRenderError (https://storybook.noprod.lacollection.io/sb-preview/runtime.js:74:13216)
    at PreviewWeb.initialize (https://storybook.noprod.lacollection.io/sb-preview/runtime.js:74:12534)

```
Getting this error for a while now with nextjs, updating to 7.2.0 did not help. Tried to downgrade nextjs version as suggested here https://github.com/storybookjs/storybook/issues/23314 but it did not help either.

I should note that it works when developing locally. Only does not work when hosted on aws.

### System

```shell
System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.2/bin/yarn
    npm: 9.6.2 - ~/.nvm/versions/node/v18.14.2/bin/npm
  Browsers:
    Chrome: 115.0.5790.114
    Edge: 115.0.1901.188
    Safari: 16.5
  npmPackages:
    @storybook/addon-actions: 7.2.0 => 7.2.0 
    @storybook/addon-essentials: 7.2.0 => 7.2.0 
    @storybook/addon-storyshots: 7.2.0 => 7.2.0 
    @storybook/addon-styling: 1.3.5 => 1.3.5 
    @storybook/addons: 7.2.0 => 7.2.0 
    @storybook/api: ^7.2.0 => 7.2.0 
    @storybook/components: 7.2.0 => 7.2.0 
    @storybook/core-events: 7.2.0 => 7.2.0 
    @storybook/nextjs: 7.2.0 => 7.2.0 
    @storybook/node-logger: 7.2.0 => 7.2.0 
    @storybook/react: 7.2.0 => 7.2.0 
    @storybook/testing-library: 0.2.0 => 0.2.0 
    @storybook/theming: ^7.2.0 => 7.2.0
```

**Comment by MohamadHFallah** [comment] 2023-08-07 11:40
When I upgraded nextjs to "^13.4.12" version , I get error. So I downgrade it to "13.3.2".

**Comment by tobinbc** [comment] 2023-08-07 13:06
FWIW I was working fine on `^7.0.6` and got this error after upgrading storybook to today's latest. Reverted everything back to `7.0.6` and it is still erroring. Next `13.2.4`

**Comment by snaerth** [comment] 2023-08-10 11:05
Getting the same error

**Comment by cullylarson** [comment] 2023-08-10 21:59
I'm seeing this issue too. Confirmed that it's caused by this code in `preview.tsx`:

```
import * as NextImage from "next/image";

const OriginalNextImage = NextImage.default;

// Override next/image so that we can render images unoptimized in Storybook.
Object.defineProperty(NextImage, "default", {
  configurable: true,
  // @ts-ignore
  value: (props) => <OriginalNextImage {...props} unoptimized />,
});
```

**Comment by vstlouis** [comment] 2023-08-11 14:05
> I'm seeing this issue too. Confirmed that it's caused by this code in `preview.tsx`:
> 
> ```ts
> import * as NextImage from "next/image";
> 
> const OriginalNextImage = NextImage.default;
> 
> // Override next/image so that we can render images unoptimized in Storybook.
> Object.defineProperty(NextImage, "default", {
>   configurable: true,
>   // @ts-ignore
>   value: (props) => <OriginalNextImage {...props} unoptimized />,
> });
> ```
> 
> Resolution was to upgrade Storybook (7.2.2) and comment out this code block.

Worked for me, thank you!

**Comment by scmx** [comment] 2023-08-17 11:46
Here's a workaround that avoids `defineProperty` entirely and allows me to keep the unoptimized prop while inside Storybook:
`.storybook/preview.ts`
```typescript
import { unoptimizeNextImageForStorybook } from '@/atoms/Image/Image';
unoptimizeNextImageForStorybook();
```
`components/Image.tsx`
```typescript
import NextImage, { ImageProps } from 'next/image';
import { forwardRef } from 'react';

/** Wrap next/image to allow for unoptimizing all images inside Storybook */
export let Image = NextImage;

const UnoptimizedImage = forwardRef<HTMLImageElement, ImageProps>(function Image(props, ref) {
	return <NextImage ref={ref} {...props} unoptimized />;
}) as typeof NextImage;

/**
 * For usage from .storybook/preview.ts so that images can be unoptimized
 * inside Storybook.
 *
 *     import { unoptimizeNextImageForStorybook } from '@/atoms/Image/Image'
 *     unoptimizeNextImageForStorybook()
 */
export function unoptimizeNextImageForStorybook() {
	Image = UnoptimizedImage;
}
```

I also got a problem with react `cache()` function not working inside storybook that I also worked around:
`utils/reactCache.ts`
```typescript
import { cache } from 'react';

type CachedFunction = Parameters<typeof cache>[0];

/**
 * Wrap react cache() function to be a no-op when running in Storybook where
 * cache doesn't work.
 * (0 , react__WEBPACK_IMPORTED_MODULE_0__.cache) is not a function
 */
export function reactCache<T extends CachedFunction>(fn: T): T {
	return typeof cache === 'function' ? cache(fn) : fn();
}
```
I changed all of my codes references to Image and cache to go through these modules. 🤷

**Comment by oshosh** [comment] 2023-08-17 13:53
@scmx It would be appreciated if you could also include an example of `reactCache`.😀

**Comment by oshosh** [comment] 2023-08-17 13:54
@scmx It would be appreciated if you could also include an example of reactCache.😀

**Comment by e-e-e** [comment] 2023-08-23 09:43
Experiencing this issue too, and can confirm that the temporary fix referenced by @tobinbc works.
Is there any likely hood of this being fixed soon, should this be fixed on within this package or within nextjs? It was previously working because the default was configurable, but there has been some change in next to mean that this no longer works.

**Comment by vladern** [comment] 2023-08-30 11:06
Same, using NextJS 13.1.1 and Storybook 7.4.0

**Comment by AlexNolasco** [comment] 2023-09-29 15:31
Same, using NextJS 12.3.1 and Storybook ^7.4.5

**Comment by valentinpalkovic** [comment] 2023-11-06 09:02
I think a lot of confusion is going on here. The referenced code, which was mentioned earlier:

```tsx
import * as NextImage from "next/image";

const OriginalNextImage = NextImage.default;

// Override next/image so that we can render images unoptimized in Storybook.
Object.defineProperty(NextImage, "default", {
  configurable: true,
  // @ts-ignore
  value: (props) => <OriginalNextImage {...props} unoptimized />,
});
```

It shouldn't be used anymore when `@storybook/nextjs` framework is in use. Many of you are getting this information from https://storybook.js.org/blog/get-started-with-storybook-and-next-js/, which is outdated. Please take a look at the `@storybook/nextjs` documentation, which you can find here: https://github.com/storybookjs/storybook/tree/next/code/frameworks/nextjs This page will always be kept up to date.

cc @jonniebigodes, @kylegach I know the [blog article ](https://storybook.js.org/blog/get-started-with-storybook-and-next-js/) has some information at the top, that mentions a zero-config way of configuring Next.js. I think, we should clearly say, that the information found in this article is out of date and the mentioned workarounds (e.g. to make images work in Next.js) don't work anymore in newer versions of Next.js.

I am closing this, since `@storybook/nextjs` is already configured properly to make the `next/image` component work.

**Closed by valentinpalkovic** 2023-11-06 09:02 UTC
Labels: bug, documentation, has workaround, nextjs, sev:S2, empathy
