### ISSUE TITLE
React-Native 5.3.0-beta.6 shouldPersistSelection not working

### ISSUE THREAD

**Issue by wilau2** [storybookjs/storybook#8943] opened 2019-11-25 15:24 UTC
**Describe the bug**
Always resetting selection uppon emulator refresh

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to story 2
2. Refresh emulator
3. First Story in the list will be displayed.

**Expected behaviour**
When shouldPersistSelection is set to true, it should keep the selection on story 2 when reloading emulator.

**Additional context**
Was working on `5.2.6` we upgraded to `5.3.0-beta.6` for the addon panel bug fix.

**Comment by JeffGuKang** [comment] 2020-01-16 05:20
It is working well in my case in v5.3.x.

**Comment by shilman** [comment] 2020-01-16 06:15
Nice! Closing 😂

**Closed by shilman** 2020-01-16 06:15 UTC
Labels: app: react-native, bug

**Comment by jimmyfortinx** [comment] 2020-01-20 20:18
@shilman @JeffGuKang I just tried in our project and we are facing this issue after moving from v5.2.8 to v5.3.7. We would like to upgrade to solve #8613 but we blocked by this issue.

On Android, after opening Storybook it always shows the first story after reloading the page even if we added the `shouldPersistSelection: true` flag to `getStorybookUI({ ... });`. On v5.2.8 we didn't have this issue.

If you need it, I could try to create a new project to reproduce the issue.

**Comment by jimmyfortinx** [comment] 2020-01-21 14:09
Finally, I took the time to create the repository where I was able to reproduce the issue.

https://github.com/jimmyfortinx/storybook-bug-rn

And to help understand the issue I did record a short video where we see the issue (at the end we have been redirected to `Welcome/to Storybook` screen instead of `Button/with Text` screen):

![storybook-bug-rn](https://user-images.githubusercontent.com/16029436/72811191-22026a80-3c2d-11ea-8f13-399dcc347205.gif)

**Comment by Renji3** [comment] 2020-06-08 09:43
I think this is due to the fact that asyncStorage is not added by default anymore.
Adding this fixed it for me.

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#react-native-async-storage

either 
```
//React Native <= v0.59
getStorybookUI({
  ...
  asyncStorage: require('@react-native-community/async-storage').default
});
```
or
```
//React Native > v0.59
getStorybookUI({
  ...
  asyncStorage: require('react-native').AsyncStorage
});
```
depending on your version.

**Comment by jimmyfortinx** [comment] 2020-06-18 15:37
@Renji3 Thanks, I didn't see that part in the documentation. It worked well :D

**Comment by JeffGuKang** [comment] 2020-06-19 00:55
@Renji3 
Recommend to use `https://react-native-community.github.io/async-storage/` always. 
And `require('react-native').AsyncStorage` is deprecated RN >= v0.59. You made a mistake writing the version.
