### ISSUE TITLE
Addon-centered breaks layout in addon-docs

### ISSUE THREAD

**Issue by TheKnarf** [storybookjs/storybook#8128] opened 2019-09-19 10:46 UTC
**Describe the bug**
When using addon-centered together with addon-docs it creates two problems:

- ~addon-docs suddenly says that it no longer finds a component~
- It still renderes the component centered in the page as an overlay over the docs page.

**To Reproduce**
Setup addon-centered together with addon-docs.

**Expected behavior**
I expect addons-centered not to affect addon-docs.

**Screenshots**
![Screenshot 2019-09-19 at 12 43 06](https://user-images.githubusercontent.com/213777/65237509-0fd7ba80-dadb-11e9-8d4e-89c9cdb7fa23.png)
![Screenshot 2019-09-19 at 12 43 12](https://user-images.githubusercontent.com/213777/65237513-123a1480-dadb-11e9-8868-1f5654a5cc7b.png)

**System:**
```
Environment Info:

  System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Safari: 12.1.2
  npmPackages:
    @storybook/addon-a11y: ^5.2.0 => 5.2.0
    @storybook/addon-actions: ^5.2.0 => 5.2.0
    @storybook/addon-centered: ^5.2.0 => 5.2.0
    @storybook/addon-docs: ^5.2.1 => 5.2.1
    @storybook/addon-knobs: ^5.2.0 => 5.2.0
    @storybook/addon-links: ^5.2.0 => 5.2.0
    @storybook/addons: ^5.2.0 => 5.2.0
    @storybook/react: ^5.2.0 => 5.2.0
```

**Comment by TheKnarf** [comment] 2019-09-19 10:50
![Screenshot 2019-09-19 at 12 48 35](https://user-images.githubusercontent.com/213777/65237894-d489bb80-dadb-11e9-9fcd-8da9a4c16f82.png)

When disabling addon-centered it still says `No component found`, so that seems to be a seperate issue. I suspect that it's because I probably haven't configured typescript support correctly so you can look away from that.

So the only real problem is that addon-centered is still active while in the `docs`-tab.

**Comment by hipstersmoothie** [comment] 2019-09-20 22:10
> It still renderes the component centered in the page as an overlay over the docs page.

Can confirm, seeing this exact issue

**Comment by techieshark** [comment] 2019-09-22 08:15
Seeing same thing.

> To Reproduce
> Setup addon-docs together with addon-docs.

^ this should say:

> To Reproduce
> Setup **addon-centered** together with addon-docs.

**Comment by Zenoo** [comment] 2019-09-24 10:21
Same issue here.

```
"@storybook/addon-centered": "^5.2.1",
"@storybook/addon-docs": "^5.2.1",
```

**Comment by UlanaXY** [comment] 2019-10-03 16:48
Same here.
And this is duplicate of  #7227
![obraz](https://user-images.githubusercontent.com/12629308/66146881-f328a000-e60d-11e9-84c1-7001cf3263d6.png)

**Comment by hipstersmoothie** [comment] 2019-10-07 16:25
This seems like a good opportunity for a pull request @UlanaXY if you don't want to get the ball rolling, I can.

**Comment by UlanaXY** [comment] 2019-10-07 16:53
@hipstersmoothie I already cloned the repo to open a PR, unfortunately I was not able to install dependencies on any of my machines (Win10, OSX) - and I do not want to open an untested PR. So if You'd have the time to test the code and open a PR, that would be great.

**Comment by kevinSuttle** [comment] 2019-10-16 23:46
I have just been putting a CSS grid inside a flexbox and aligning/justifying everything to center.

**Comment by aasili-shoprunner** [comment] 2019-11-08 15:20
I found a temp fix for anyone else needs it. This can be applied globally in `config.js`. I haven't tested how to resolve in individual story files. 

```javascript
// .storybook/config.js
import { addDecorator } from '@storybook/react';
import centered from '@storybook/addon-centered/react';

// Centered addon causes layout issues on docs page.
// This is a weird hack to fix the layout issues.
addDecorator((...args) => {
    if (window.location.href.indexOf('docs') > -1) {
        return args[0]();
    }

    return centered(...args);
});
```

**Closed** 2020-02-03 11:59 UTC
Labels: addon: centered, addon: docs, bug, good first issue, help wanted

**Comment by sinclairnick** [comment] 2020-04-23 10:40
Ive just replaced it with a full width flexbox with justify center. Lacks the vertical centering, but frankly thats desirable

**Comment by ndelangen** [comment] 2020-04-23 10:46
```
addParameters({
  layout: 'centered',
});
```

Should make all stories be centered in the preview 👍

**Comment by luckylooke** [comment] 2020-05-14 14:41
Same problem is also in Vue stories.
Temporary fixed by:
https://github.com/storybookjs/storybook/issues/8128#issuecomment-551868589 👍
