### ISSUE TITLE
[Bug]: Can't get storybook to run on a vanilla install.

### ISSUE THREAD

**Issue by DavidLeonard77** [storybookjs/storybook#19931] opened 2022-11-22 21:46 UTC
### Describe the bug

Can't get storybook to run on a vanilla Angular install. I can reproduce this on macOS and PC on ,multiple computers.

Simple create -> install -> run.

It seems to be looking for storybook-init-framework-entry.js but can't find it.

Node: v18.12.1
Angular: 15.0.0
npm: 18.9.2

Nothing fancy here. Just following the docs as a new user.

Steps to reproduce:
Create angular app `ng n testApp`
Navigate to testApp `cd testApp`
Install: `npx storybook init`
Run: `npm run storybook`

if I run `npm run build-storybook` I get the same error

I have tried deleting .node_modules folder and re-installing.
I have tried the suggested commands in the troubleshooting section:
`npx storybook init --type angular`
`npx storybook init --use-npm`
`npx storybook@next automigrate`

Error:

`...
Field 'browser' doesn't contain a valid alias configuration
/Users/dleonard/Documents/GitHub/theia-design-system-storybook/angular/sandbox/storybook-init-framework-entry.js doesn't exist
.mjs
Field 'browser' doesn't contain a valid alias configuration
/Users/dleonard/Documents/GitHub/theia-design-system-storybook/angular/sandbox/storybook-init-framework-entry.js.mjs doesn't exist
.js
Field 'browser' doesn't contain a valid alias configuration
/Users/dleonard/Documents/GitHub/theia-design-system-storybook/angular/sandbox/storybook-init-framework-entry.js.js doesn't exist
.jsx
Field 'browser' doesn't contain a valid alias configuration
/Users/dleonard/Documents/GitHub/theia-design-system-storybook/angular/sandbox/storybook-init-framework-entry.js.jsx doesn't exist
.ts
Field 'browser' doesn't contain a valid alias configuration
/Users/dleonard/Documents/GitHub/theia-design-system-storybook/angular/sandbox/storybook-init-framework-entry.js.ts doesn't exist
.tsx
Field 'browser' doesn't contain a valid alias configuration
/Users/dleonard/Documents/GitHub/theia-design-system-storybook/angular/sandbox/storybook-init-framework-entry.js.tsx doesn't exist
.json
Field 'browser' doesn't contain a valid alias configuration
/Users/dleonard/Documents/GitHub/theia-design-system-storybook/angular/sandbox/storybook-init-framework-entry.js.json doesn't exist
.cjs
Field 'browser' doesn't contain a valid alias configuration
/Users/dleonard/Documents/GitHub/theia-design-system-storybook/angular/sandbox/storybook-init-framework-entry.js.cjs doesn't exist
as directory
/Users/dleonard/Documents/GitHub/theia-design-system-storybook/angular/sandbox/storybook-init-framework-entry.js doesn't exist

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

info => Loading presets`

### To Reproduce

```shell
npx sb@next repro
╭──────────────────────────────────────────────────────────────────────────────╮
│                                                                              │
│   🤗 Welcome to sb repro! 🤗                                                 │
│                                                                              │
│   Create a new project to minimally reproduce Storybook issues.              │
│                                                                              │
│   1. select an environment that most closely matches your project setup.     │
│   2. select a location for the reproduction, outside of your project.        │
│                                                                              │
│   After the reproduction is ready, we'll guide you through the next steps.   │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯
✔ 🌈 Select the repro renderer › angular
✔ 📝 Select the repro base template › angular
✔ Enter the output directory … angular
🏃 Running angular into /Users/dleonard/Design System/angular/sandbox/angular

🏃 Starting for angular latest

🏗 Bootstrapping angular project (this might take a few minutes)
npx -p @angular/cli@latest ng new angular --routing=true --minimal=true --style=scss --skip-install=true --strict
Error: This command is not available when running the Angular CLI inside a workspace.
Error: This command is not available when running the Angular CLI inside a workspace.
An error occurred while executing: `npx -p @angular/cli@latest ng new angular --routing=true --minimal=true --style=scss --skip-install=true --strict`
🚨 Bootstrapping angular failed
🚨 Failed to create repro
ERR! Error: command exited with code: 1: 
ERR!     at ChildProcess.<anonymous> (/Users/dleonard/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@storybook/cli/dist/generate.js:228:264)
ERR!     at ChildProcess.emit (node:events:513:28)
ERR!     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
ERR!  Error: command exited with code: 1: 
ERR!     at ChildProcess.<anonymous> (/Users/dleonard/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@storybook/cli/dist/generate.js:228:264)
ERR!     at ChildProcess.emit (node:events:513:28)
ERR!     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

### System

```shell
Environment Info:

  System:
    OS: macOS 13.0.1
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Safari: 16.1
  npmPackages:
    @storybook/addon-actions: ^6.5.13 => 6.5.13 
    @storybook/addon-essentials: ^6.5.13 => 6.5.13 
    @storybook/addon-interactions: ^6.5.13 => 6.5.13 
    @storybook/addon-links: ^6.5.13 => 6.5.13 
    @storybook/angular: ^6.5.13 => 6.5.13 
    @storybook/builder-webpack5: ^6.5.13 => 6.5.13 
    @storybook/manager-webpack5: ^6.5.13 => 6.5.13 
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

**Comment by cristobalchao** [comment] 2022-11-22 23:53
Same happens on React. 

Steps to reproduce:

```
npx storybook init
```

```
yarn storybook
```

Tested using `Node v14.19.1` and `v18.12.1`

**Comment by ericledonge** [comment] 2022-11-23 02:30
+1 with a vanilla create-react-app and npm 8.

**Comment by ericledonge** [comment] 2022-11-23 02:44
Related to https://github.com/storybookjs/storybook/issues/19927

**Comment by yuri-scarbaci-lenio** [comment] 2022-11-23 17:18
relates to https://github.com/storybookjs/storybook/issues/19940

**Comment by valentinpalkovic** [comment] 2022-11-30 11:01
The underlying [issue](https://github.com/storybookjs/storybook/issues/19927) got fixed. I cannot reproduce the issue anymore. Therefore, I will close this.

**Closed by valentinpalkovic** 2022-11-30 11:01 UTC
Labels: bug, needs triage
