### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of undefined (reading 'clientApi')

### ISSUE THREAD

**Issue by apomorska** [storybookjs/storybook#23124] opened 2023-06-18 17:42 UTC
### Describe the bug

I have monorepo with storybook-host using react

```
TypeError: Cannot read properties of undefined (reading 'clientApi')

       initStoryshots({
                      ^
          configPath: path.resolve(__dirname, '../../storybook-host/.storybook/preview.tsx')
        });
      

      at ../../../node_modules/@storybook/addon-storyshots/dist/frameworks/react/loader.js:34:49
      at Object.load (../../../node_modules/@storybook/addon-storyshots/dist/frameworks/react/loader.js:39:23)
      at loadFramework (../../../node_modules/@storybook/addon-storyshots/dist/frameworks/frameworkLoader.js:36:19)
      at testStorySnapshots (../../../node_modules/@storybook/addon-storyshots/dist/api/index.js:28:99)
      at Object.<anonymous> (setup-jest.ts:7:15)
```

### To Reproduce

```
import initStoryshots from '@storybook/addon-storyshots';
import path from "path";

initStoryshots({
  configPath: path.resolve(__dirname, '../../storybook-host/.storybook/preview.tsx')
});
```

**Comment by apomorska** [comment] 2023-06-21 11:13
same

**Comment by LuukMoret** [comment] 2023-06-21 11:58
I have the same but with Angular, setting storyStoreV7 to false does not help

**Comment by apomorska** [comment] 2023-06-22 07:14
this part is not working from react loader.js
`jest.mock('@storybook/preview-api', () => {
        const previewAPI = jest.requireActual('@storybook/preview-api');
        return {
            ...previewAPI,
            start: (...args) => {
                mockStartedAPI = previewAPI.start(...args);
                return mockStartedAPI;
            },
        };
    });`

**Comment by samends** [comment] 2023-08-23 17:17
Also experiencing the same issue, I'm on `@storybook/addon-storyshots` version `7.3.2`

**Comment by yobottehg** [comment] 2023-08-29 11:50
Same here, worked fine with 7.3.1 but fails with 7.3.2 and 7.4.0.

My setup for reproduction:

```
import renderOnly from '@storybook/addon-storyshots'

// Somehow jest-fail-on-console is not catching all issues
// Somehow storyshots is doing more than just running jest
// That is why we need this content here
const spyError = jest.spyOn(global.console, 'error')
const spyWarn = jest.spyOn(global.console, 'warn')

renderOnly()

expect(spyError).not.toHaveBeenCalled()
expect(spyWarn).toHaveBeenCalledWith(expect.stringContaining('subcomponents'))

```

We use that as smoke test for all components. Works fine with 7.3.1 and errors with >=7.3.2

```
 FAIL  tests/storybook.test.ts
  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'clientApi')

       7 | const spyWarn = jest.spyOn(global.console, 'warn')
       8 |
    >  9 | renderOnly()
         |           ^
      10 |
      11 | expect(spyError).not.toHaveBeenCalled()
      12 | expect(spyWarn).toHaveBeenCalledWith(expect.stringContaining('subcomponents'))

```

**Comment by abi-spyro** [comment] 2023-09-12 16:45
Experiencing the same issue in nx monorepo, using `@storybook/addon-storyshots` version `7.4.1`

**Comment by irangarcia** [comment] 2023-09-26 17:37
Try running: `npm install @storybook/preview-api --save-dev`

**Comment by flyinglimao** [comment] 2023-10-11 06:11
Same here with 7.4.6
Hello @irangarcia , I wonder if should it work after installing it?

**Comment by fregante** [comment] 2023-10-18 05:34
I can confirm that it works with v7.3.0 and it breaks in v7.3.1

In my case the call was a simple `initStoryshots()`

**Comment by shajjhusein** [comment] 2023-10-18 12:48
@fregante  v7.4.6 is not working

**Comment by fregante** [comment] 2023-10-28 06:20
It suddenly worked [for me](https://github.com/pixiebrix/pixiebrix-extension/pull/6703) in the latest 7.5.1 update. I wonder if the issue was simply due to a bad dependency install, e.g. not every storybook dependency was updated.

**Comment by valentinpalkovic** [comment] 2023-10-28 08:22
@shajjhusein cab you update to the latest version and verify whether the issue is resolved? Thanks!

**Comment by shajjhusein** [comment] 2023-10-28 20:31
@valentinpalkovic I've checked on my end, and everything seems to be working fine.  Thank you!

**Comment by valentinpalkovic** [comment] 2023-10-28 21:00
Alright! Closing the issue.

**Closed by valentinpalkovic** 2023-10-28 21:00 UTC
Labels: bug, addon: storyshots

**Comment by flyinglimao** [comment] 2023-11-07 04:17
Hello @valentinpalkovic 
I was using 7.5.1 ~ 7.5.3, and the problem still happened.
Would you mind to reopen this issue or let me open another one?
I'm using it with next.js and I noticed that [the start function](https://github.com/storybookjs/storybook/blob/69ad2cee0e177df26d7e340197934fff06b102e1/code/addons/storyshots-core/src/frameworks/react/loader.ts#L18) of `@storybook/react` wasn't called, which is necessary to initialize the `clientApi`.
Then I found the following code in the built files (beautified)
```
var import_preview_api = require("@storybook/preview-api");
var import_global2 = require("@storybook/global"),
    import_react = __toESM(require("react")), // the trace stack told me the the mock of @storybook/react is used again here and requires `clientApi`
....
var RENDERER = "react",
    api = (0, import_preview_api.start)(renderToCanvas, { // I guess it should be call earlier
        render
    }),
```

**Comment by valentinpalkovic** [comment] 2023-11-07 06:34
Can you provide a reproduction?

**Comment by flyinglimao** [comment] 2023-11-07 11:14
Hi @valentinpalkovic
I found the problem solved after I deleted the `yarn.lock` and re-installed it again, hence I guess there are some more complex dependency problems that weren't solved by the upgrade script.
Sorry for bothering

**Comment by yannbf** [comment] 2023-11-08 10:38
FYI anyone hitting this issue on a more updated version of Storybook, make sure you don't have multiple versions of the same package. If your package.json looks like this:

```json
{
  "devDependencies": {
    "@storybook/react": "^7.4.0"
  }
}
```

and you run e.g. `yarn install @storybook/addon-storyshots`, therefore resulting in something like:
```json
{
  "devDependencies": {
    "@storybook/react": "^7.4.0",
    "@storybook/addon-storyshots": "^7.5.3"
  }
}
```

there's a big chance that your lockfile will contain duplicated dependencies such as:
```
@storybook/preview-api@7.4.0
@storybook/preview-api@7.5.3
```

and that will cause issues. Therefore the solution is to just clear your lock file and reinstall.

Also, consider checking the [Storybook test-runner](https://github.com/storybookjs/test-runner), as storyshots is going to be deprecated and removed in Storybook 8! Thanks <3
