### ISSUE TITLE
Upgrading to 6.1.14 opens http://192.168.1.48:6006/ instead of http://localhost:6006/  

### ISSUE THREAD

**Issue by Vadorequest** [storybookjs/storybook#13619] opened 2021-01-12 14:31 UTC
**Describe the bug**
Upgrading to 6.1.14 opens http://192.168.1.48:6006/ instead of http://localhost:6006/  

It's a change in behavior, nothing critical.

Wasn't happening in v6.1.11

**Comment by wanderlima** [comment] 2021-01-13 00:19
I can confirm it, I just upgraded to 6.1.14 and local address is not working. It drops a 404 error for vendors.bundle.js

It only works if access it through network using my ip.

**Comment by henrycity** [comment] 2021-01-14 12:04
Seem like this PR introduce this change: https://github.com/storybookjs/storybook/pull/13521 and this PR was merged in 6.1.14.

Now, storybook will always open with a specific address or IP address, instead of an option to open in localhost.

**Comment by Vadorequest** [comment] 2021-01-14 12:30
Thank you @henrycity for the reference.

@wanderlima You can use `start-storybook -h localhost -p 6006` instead of `start-storybook -p 6006` to open `http://localhost:6006/` by default (restores the old behavior). It works on my setup.

**Comment by henrycity** [comment] 2021-01-14 12:34
Yeah we can add localhost as the host. Though it would be still nice to display the IP address in `On your network` as before, instead of localhost
![image](https://user-images.githubusercontent.com/16038403/104591489-6e805a80-5675-11eb-9ef9-0b6650168fc5.png)

**Comment by Vadorequest** [comment] 2021-01-14 12:36
Personally I don't really need to see the IP address, all my projects are running on localhost using a different port, that's what I'm used to. But it's a matter of personal preference, so it's great the old url can still be used through configuration of the `-h` parameter.

**Comment by henrycity** [comment] 2021-01-14 12:41
For my use case, it would still be valuable to see the IP address so that I can test on mobile or another computer. On the other hand, opening `localhost` automatically is still useful when starting the project.

**Comment by PenguinOfWar** [comment] 2021-02-04 09:31
I've created a PR to address this issue by providing flexibility based on the provided args: #13812

Advice welcome on how to make sure this is properly covered in tests.

**Comment by shilman** [comment] 2021-02-04 12:23
Closing as dupe to #13707

**Closed by shilman** 2021-02-04 12:23 UTC

**Comment by shilman** [comment] 2021-02-04 16:08
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.17 containing PR #13812 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

**Comment by shilman** [comment] 2021-02-05 00:22
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.22 containing PR #13812 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```
