### ISSUE TITLE
Angular story code not correct

### ISSUE THREAD

**Issue by daan93** [storybookjs/storybook#15575] opened 2021-07-14 10:02 UTC
After a clean install of Angular and latest Storybook, story code is not showing correctly in the docs. The component tag is shown, but any attributes or content are left out. 

**Expected behaviour**
Storybook 6.1 shows complete story code
![image](https://user-images.githubusercontent.com/7119213/125603674-7e657518-f9c9-47e6-b217-382d2ee535e2.png)

**Current behaviour**
Storybook 6.3 shows only the component tag
![image](https://user-images.githubusercontent.com/7119213/125603735-f2fae4de-75f8-4f61-a64c-b86872492db8.png)

**Comment by Jakob-em** [comment] 2021-07-14 10:10
Looks like a duplicate of https://github.com/storybookjs/storybook/issues/14268

**Comment by daan93** [comment] 2021-07-14 11:12
Could be a duplicate, but as you see in the example not just the template is left out, it's also other story properties.

**Comment by shilman** [comment] 2021-07-14 11:16
@yngvebn any chance you can take a look at this?

**Comment by yngvebn** [comment] 2021-07-14 11:18
@shilman currently on vacation, but if I get the chance, sure

**Comment by shilman** [comment] 2021-07-14 11:19
@yngvebn have a wonderful vacation! 👍

**Comment by dexster** [comment] 2021-07-14 11:50
@daan93 What version of compodoc is in your package.json? There's an issue with 1.1.12/13. Install 1.1.11 and see whether this helps. I do see all attributes in my code view

**Comment by daan93** [comment] 2021-07-14 12:40
@dexster I was using 1.1.13, so I downgraded to 1.1.11. But storybook is still showing only the component tag in the code view.

**Comment by shilman** [comment] 2023-06-07 12:39
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

**Closed by shilman** 2023-06-07 12:39 UTC
Labels: bug, angular, block: source, needs triage
