### ISSUE TITLE
Core: Create opt-out feature flag for `'use strict'` mode in `preview.js`

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#20198] opened 2022-12-12 02:37 UTC

**Comment by tmeasday** [comment] 2022-12-12 02:37
@ndelangen do you know how difficult this would be to achieve?

**Comment by ndelangen** [comment] 2022-12-13 17:37
Are we sure there is no other way?

I have no idea -right now- how to even make this happen. and if we did make this happen it would be a blocker for eventually making the preview code run as ESM. (ESM is always strict-mode).

What did we need non-strict mode for exactly. I know you told me, but I've been having a rough day, and keep looking track.

**Comment by tmeasday** [comment] 2022-12-13 20:37
Haha, it's a lot! I think our thought here was just that if the addition of `'use strict'` to `preview.js` was causing users issues (in particular we've seen that `timemachine` no longer works with it), people could use a flag to opt-out, on a "temporary" basis (i.e. this flag exists now but won't in 8.0) to buy some time to figure out the problems. Sort of like a deprecation mechanism.

I think it depends on how many such issues users run into how important this ends up being.

**Comment by ndelangen** [comment] 2022-12-13 22:05
AFAIK preview.ts will just be part of the regular builder output. meaning, I'd have to hook into each builder and figure out how to make it generate non-strict code.

Have you considered injecting code via preview-head.html? bypassing the builder?

**Comment by yannbf** [comment] 2022-12-14 10:19
I have experimented with both `timemachine` and `datemock` in Storybook 7.0 and was able to successfully mock dates, both in dev and prod mode. Am I missing something?

**Comment by shilman** [comment] 2022-12-16 18:56
why do we need this? can we just refer people to the workaround?

**Comment by yannbf** [comment] 2022-12-17 12:47
I'd love to first understand how to reproduce this error, because so far I had success in the use case presented

**Comment by ndelangen** [comment] 2022-12-17 12:47
I'm not sure there is actually a bug. And the word around would work if it was.

The more modern code should not be an option we'd let people disable.

I propose we close this issue.

**Comment by tmeasday** [comment] 2022-12-20 05:07
@yannbf So I took a look. There's definitely a problem using `timemachine` in SB7 (for better or worse). @yannbf I tried this with both `react-vite/default-js` and `nextjs/default-js`:

1. `yarn start --template...`
2. `cd sandboxes/...`
3. `yarn add --dev timemachine`
4. Updated `preview.js` to `import timemachine from 'timemachine'; timemachine.reset()`
5. Run SB, see error:

<img width="926" alt="image" src="https://user-images.githubusercontent.com/132554/208587874-6139503c-0ca7-4459-ba8e-15694ffc2c43.png">

I also tried similar in a 6.5 nextjs project and didn't see a problem.

Thinking about it a bit more, and comparing details, I don't think the issue is that `preview.js` is run in strict mode (it was already `use strict` in 6.5), it is that the imported module is run strictly. For vite it is literally `import`-ed in the browser which implies strict mode, but in nextjs/WP it isn't, so I can't quite see why that is.

When I compare the two NextJS bundles, there is no `use strict` in the timemachine part of the (7) WP bundle:

<img width="448" alt="image" src="https://user-images.githubusercontent.com/132554/208588074-db52a3b7-34b4-47a9-b23a-8501e50b220c.png">

**Comment by ndelangen** [comment] 2022-12-20 09:50
@tmeasday I'm pretty sure, if you follow up where the script is imported, you'll find the webpack entry scripts are also imported into the browser via an `import`, that's likely the change..

**Comment by tmeasday** [comment] 2022-12-20 12:11
I see, you are right: 
<img width="490" alt="image" src="https://user-images.githubusercontent.com/132554/208663901-80e1926d-4d0b-433f-a130-05f3bece4ad7.png">

I guess that means all the `'use strict'`s inside the bundle are sort of superfluous, and the message here is not quite right: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#add-strict-mode

So we aren't going to be able to opt-out of this easily then, I am guessing?

PS the workaround to use `preview-head.html` doesn't really work if you want to to import anything I suppose 🤔

**Comment by ndelangen** [comment] 2022-12-20 12:22
@tmeasday you could import from a CDN.. Or pre-bundle the thing you're importing, manually.

**Comment by ndelangen** [comment] 2022-12-20 13:42
I wonder if you could get around it using `eval` @tmeasday

**Comment by ndelangen** [comment] 2023-01-26 15:04
@tmeasday What should we do to this ticket?

**Comment by tmeasday** [comment] 2023-01-27 00:24
@ndelangen is it possible/feasible to opt out of [the import there](https://github.com/storybookjs/storybook/issues/20198#issuecomment-1359269018)?

If not, then we should close this and make sure there is a note in the migration guide about this and how to work around it.

**Comment by ndelangen** [comment] 2023-01-30 11:50
adding the ability to opt-out of the imports seems the wrong way to me. It would complicate things a lot, and cause further maintenance burden.

**Closed by ndelangen** 2023-01-30 11:50 UTC
Labels: feature request, core
