### ISSUE TITLE
[Bug]: Ngxs import no longer working in Storybook 7

### ISSUE THREAD

**Issue by nzacca** [storybookjs/storybook#21056] opened 2023-02-11 06:15 UTC
### Describe the bug

We use [Ngxs](https://github.com/ngxs/store) for our State Management and this import is having some trouble in Storybook 7. Note this is working fine in Storybook 6. We're receiving a `NullInjectorError` in the canvas after starting Storybook:

```
NullInjectorError: No provider for StateFactory!
NullInjectorError: NullInjectorError: No provider for StateFactory!
    at NullInjector.get (http://localhost:6006/vendors-node_modules_storybook_addon-docs_angular_index_js-node_modules_storybook_addon-essen-170b5a.iframe.bundle.js:43374:21)
    at R3Injector.get (http://localhost:6006/vendors-node_modules_storybook_addon-docs_angular_index_js-node_modules_storybook_addon-essen-170b5a.iframe.bundle.js:43796:27)
    at R3Injector.get (http://localhost:6006/vendors-node_modules_storybook_addon-docs_angular_index_js-node_modules_storybook_addon-essen-170b5a.iframe.bundle.js:43796:27)
    at R3Injector.get (http://localhost:6006/vendors-node_modules_storybook_addon-docs_angular_index_js-node_modules_storybook_addon-essen-170b5a.iframe.bundle.js:43796:27)
    at injectInjectorOnly (http://localhost:6006/vendors-node_modules_storybook_addon-docs_angular_index_js-node_modules_storybook_addon-essen-170b5a.iframe.bundle.js:36619:29)
    at Module.ɵɵinject (http://localhost:6006/vendors-node_modules_storybook_addon-docs_angular_index_js-node_modules_storybook_addon-essen-170b5a.iframe.bundle.js:36623:59)
    at Object.NgxsRootModule_Factory [as useFactory] (http://localhost:6006/vendors-node_modules_ngxs_store_fesm2015_ngxs-store_js-node_modules_storybook_angular_dist_in-1169a1.iframe.bundle.js:2272:90)
    at Object.factory (http://localhost:6006/vendors-node_modules_storybook_addon-docs_angular_index_js-node_modules_storybook_addon-essen-170b5a.iframe.bundle.js:43968:32)
    at R3Injector.hydrate (http://localhost:6006/vendors-node_modules_storybook_addon-docs_angular_index_js-node_modules_storybook_addon-essen-170b5a.iframe.bundle.js:43886:29)
    at R3Injector.get (http://localhost:6006/vendors-node_modules_storybook_addon-docs_angular_index_js-node_modules_storybook_addon-essen-170b5a.iframe.bundle.js:43787:23)
```

### To Reproduce

```shell
import { Component } from '@angular/core';
import { NgxsModule } from '@ngxs/store';
import { Meta, moduleMetadata, StoryFn } from '@storybook/angular';

@Component({
  selector: 'app-test',
  template: `hello`,
})
class TestComponent {}

export default {
  title: 'Ngxs Error',
  component: TestComponent,
  decorators: [
    moduleMetadata({
      imports: [NgxsModule.forRoot([])],
    }),
  ],
} as Meta;

const Template: StoryFn<TestComponent> = (args: TestComponent) => ({
  props: args,
});

export const Ngxs = Template.bind({});
```

### System

```shell
Environment Info:

  System:
    OS: Windows 10 10.0.22621
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
  Binaries:
    Node: 16.16.0 - C:\dev\nodejs\node.EXE
    npm: 8.13.2 - C:\dev\nodejs\npm.CMD
  Browsers:
    Chrome: 109.0.5414.120
    Edge: Spartan (44.22621.1105.0), Chromium (110.0.1587.41)
  npmPackages:
    @storybook/addon-actions: 7.0.0-beta.45 => 7.0.0-beta.45
    @storybook/addon-essentials: 7.0.0-beta.45 => 7.0.0-beta.45
    @storybook/addon-interactions: 7.0.0-beta.45 => 7.0.0-beta.45
    @storybook/addon-links: 7.0.0-beta.45 => 7.0.0-beta.45
    @storybook/angular: 7.0.0-beta.45 => 7.0.0-beta.45
    @storybook/builder-webpack5: 7.0.0-beta.45 => 7.0.0-beta.45
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

### Additional context

I'm not sure where the issue is as yet. I did a little bit of digging and saw that Providers are stripped out of the NgxsModule as part of the `extractImports` when setting up the Wrapper component here: https://github.com/storybookjs/storybook/blob/1f62f41d6139972249cb26924a0052ae8aaf9f03/code/frameworks/angular/src/client/angular-beta/StorybookWrapperComponent.ts#L55

This sounds like it would lead to the issue we're seeing. That said, I have verified that the Providers from the module are extracted and included in the Wrapped component here: https://github.com/storybookjs/storybook/blob/1f62f41d6139972249cb26924a0052ae8aaf9f03/code/frameworks/angular/src/client/angular-beta/StorybookWrapperComponent.ts#L81

The error occurs when the `NgxsRootModule` is instantiated since it depends on the `StateFactory` in its constructor.

Note this library works just fine in the Angular app itself. I need to do some more tests to see if I can replicate this with a minimal NgModule.

**Comment by valentinpalkovic** [comment] 2023-02-11 10:33
Hey @nzacca,

we are aware of this issue and are currently working on a fix. cc: @sheriffMoose

**Comment by valentinpalkovic** [comment] 2023-02-11 10:38
Duplicate of https://github.com/storybookjs/storybook/issues/21052

**Closed by valentinpalkovic** 2023-02-11 10:38 UTC
Labels: bug, angular, needs triage

**Comment by nzacca** [comment] 2023-02-11 11:35
@valentinpalkovic Sorry about that. Thank you for the update.
