### ISSUE TITLE
React-Native Error: TypeError: JSON.stringify cannot serialize cyclic structures.

### ISSUE THREAD

**Issue by simonepizzamiglio** [storybookjs/storybook#9636] opened 2020-01-25 15:17 UTC
**Describe the bug**
When I try to run Storybook in a React-Native project I always get this error 
`TypeError: JSON.stringify cannot serialize cyclic structures.`
I'm able to navigate through it, but every time I click on something I get this error and have to dismiss it.

Downgrading to `5.3.0-rc.8` version this error doesn't occurs.

**System:**
```
System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 10.14.2 - ~/.nvm/versions/node/v10.14.2/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.13.1 - ~/.nvm/versions/node/v10.14.2/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 71.0
    Safari: 13.0.3
  npmPackages:
    @storybook/addon-actions: ^5.3.9 
    @storybook/addon-links: ^5.3.9 
    @storybook/addons: ^5.3.9 
    @storybook/react-native: ^5.3.9 
    @storybook/react-native-server: ^5.3.9 
```

**Comment by mi5ha** [comment] 2020-01-25 18:16
I think this is duplicate of [this](https://github.com/storybookjs/storybook/issues/9294)

Storybook for React Native seems unusable until this is solved?

**Comment by shilman** [comment] 2020-01-28 07:21
closing as a duplicate of #9294

**Closed by shilman** 2020-01-28 07:21 UTC
Labels: app: react-native, bug
