### ISSUE TITLE
[Bug]: Failed to resolve module specifier "react" (@storybook/react-vite)

### ISSUE THREAD

**Issue by unional** [storybookjs/storybook#22630] opened 2023-05-18 21:21 UTC
### Describe the bug

When running `storybook dev`, it is working fine.
But if it is built by running `storybook build`, and load the resulting `index.html`,

It fails with:

`Failed to resolve module specifier "react". Relative references must start with either "/", "./", or "../".`

![image](https://github.com/storybookjs/storybook/assets/3254987/ffe8f524-591b-4753-b1df-178ec369e855)

### To Reproduce

Do not have a repro yet

### System

```shell
Environment Info:

  System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 112.0
    Safari: 16.4
  npmPackages:
    @storybook/addon-actions: ^7.0.12 => 7.0.12 
    @storybook/addon-backgrounds: ^7.0.12 => 7.0.12 
    @storybook/addon-console: ~2.0.0 => 2.0.0 
    @storybook/addon-docs: ^7.0.12 => 7.0.12 
    @storybook/addon-essentials: ^7.0.12 => 7.0.12 
    @storybook/addon-interactions: ^7.0.12 => 7.0.12 
    @storybook/addon-links: ^7.0.12 => 7.0.12 
    @storybook/addon-measure: ^7.0.12 => 7.0.12 
    @storybook/addon-outline: ^7.0.12 => 7.0.12 
    @storybook/addon-storysource: ~7.0.12 => 7.0.12 
    @storybook/addon-styling: ^1.0.8 => 1.0.8 
    @storybook/addons: ~7.0.12 => 7.0.12 
    @storybook/channel-postmessage: ^7.0.12 => 7.0.12 
    @storybook/channel-websocket: ^7.0.12 => 7.0.12 
    @storybook/client-api: ^7.0.12 => 7.0.12 
    @storybook/jest: ~0.1.0 => 0.1.0 
    @storybook/preview-web: ^7.0.12 => 7.0.12 
    @storybook/react: ^7.0.12 => 7.0.12 
    @storybook/react-vite: ^7.0.12 => 7.0.12 
    @storybook/test-runner: ~0.10.0 => 0.10.0 
    @storybook/testing-library: ^0.1.0 => 0.1.0 
    @storybook/theming: ^7.0.12 => 7.0.12
```

### Additional context

I have also seen `Failed to resolve module specifier "uuid"`, or `Failed to resolve module specifier "some-library"`, where `some-library` is used in `preview.tsx`.

**Comment by Haschtl** [comment] 2023-05-19 11:58
I'm having a similar issue. `dev` working fine, but when I open the build, i'm getting
```
Failed to resolve module specifier "vite/modulepreload-polyfill". Relative references must start with either "/", "./", or "../".
```

**Comment by unional** [comment] 2023-06-06 21:02
This seems to occur after 7.0.7. I have one using that and it seems to be fine. The other one using 7.0.13 has this problem.

**Comment by unional** [comment] 2023-06-06 21:18
![image](https://github.com/storybookjs/storybook/assets/3254987/bbd0b401-c246-4c88-95e5-5b3ecc38ce99)

7.0.18

**Comment by shilman** [comment] 2023-06-07 01:44
Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by unional** [comment] 2023-06-07 04:37
Actually I do have a repro. https://github.com/justland/just-web-react

```sh
pnpm i
pnpm react sb:build
```

The folder will be in `libraries/react/storybook-static`

**Comment by unional** [comment] 2023-06-07 07:13
Thanks. Will try that. 

But if that is the cause, why `storybook dev` is working fine?

Does that uses the cite config differently?

**Comment by JReinhold** [comment] 2023-06-07 07:20
> But if that is the cause, why `storybook dev` is working fine?

That's because Vite only uses Rollup for production builds, and esbuild in development. And the plugin is a rollup-only plugin.

**Comment by JReinhold** [comment] 2023-09-12 22:07
@kylegach ultimately I think this is something we need to document, a quirk when using Vite and building a library, not an application.

I'll be happy to explain it in greater detail if my previous comment isn't enough.
I'm closing this issue though, as it isn't really a bug.

**Closed** 2023-09-12 22:07 UTC
Labels: bug, has workaround, builder-vite

**Comment by steoneill** [comment] 2023-10-17 10:41
I'm sadly having this issue still , after adding the vitefinal fix

**Comment by mehrdad-panahandeh** [comment] 2023-11-03 15:02
I replaced the build with swc

`import type { StorybookConfig } from '@storybook/react-webpack5'

import { dirname, join } from 'path'

/**
 * This function is used to resolve the absolute path of a package.
 * It is needed in projects that use Yarn PnP or are set up within a monorepo.
 */
function getAbsolutePath(value: string): any {
  return dirname(require.resolve(join(value, 'package.json')))
}
const config: StorybookConfig = {
  stories: ['../src/**/*.mdx', '../src/**/*.stories.@(js|jsx|mjs|ts|tsx)'],
  addons: [
    getAbsolutePath('@storybook/addon-links'),
    getAbsolutePath('@storybook/addon-essentials'),
    getAbsolutePath('@storybook/addon-onboarding'),
    getAbsolutePath('@storybook/addon-interactions'),
  ],
  framework: {
    name: getAbsolutePath('@storybook/react-webpack5'),
    options: {
      builder: {
        useSWC: true,
      },
    },
  },
  docs: {
    autodocs: 'tag',
  },
}
export default config`

**Comment by mmospanenko** [comment] 2024-03-26 18:51
"storybook": "^8.0.4"

same issue with Vite in lib mode (react as peerDependency)

**Comment by mmospanenko** [comment] 2024-03-26 19:30
YEAH! Found solution, thanks @JReinhold!

1. check what Vite plugin are you using for your Vite lib vuild:

```diff
  viteFinal: async (config) => {
+  console.log('config', config.plugins);
    return {
      ...config,
      plugins: await withoutVitePlugins(config.plugins, ['peer-deps-external']),
    };
  },
```
<img width="512" alt="image" src="https://github.com/storybookjs/storybook/assets/2766211/508475ed-350c-43f7-b521-6018a62b060d">

2. add this plugin ('peer-deps-external' in my case) to exclude list via withoutVitePlugins

```diff
  viteFinal: async (config) => {
    return {
      ...config,
+      plugins: await withoutVitePlugins(config.plugins, ['peer-deps-external']),
    };
  },
```
