### ISSUE TITLE
Creating angular project with no initial app throws sb init error

### ISSUE THREAD

**Issue by AlokTakshak** [storybookjs/storybook#12058] opened 2020-08-16 14:00 UTC
**Describe the bug**
Creating angular project with no initial app throws sb init error
 • Detecting project type. ✓
 • Adding Storybook support to your "Angular" app
     TypeError: Cannot read property 'architect' of undefined

**To Reproduce**

1. ng new ng-ui --create-application=false
2. cd ng-ui
3. ng g lib button -p ui
4. npx -p @storybook/cli sb init
5. See error

**Expected behavior**
should add storybook to my workspace

**Screenshots**
![image](https://user-images.githubusercontent.com/26347838/90336048-d7947100-dff6-11ea-816c-b559050549d4.png)

**Comment by Rogier-blip** [comment] 2020-10-06 13:19
@AlokTakshak I had the same problem and for me, the fix was to in the angular.json set the   "defaultProject" field to the correct name.

Hope this helps!

**Comment by ThibaudAV** [comment] 2020-12-13 14:52
Seems to be related to https://github.com/storybookjs/storybook/issues/6978

Indeed sotrybook works only if it "finds" an application in angular.json. it doesn't work with a library

**Comment by jongbonga** [comment] 2022-02-23 22:55
I'm having this exact error in ng13

> @AlokTakshak I had the same problem and for me, the fix was to in the angular.json set the "defaultProject" field to the correct name.
> 
> Hope this helps!

What do you mean by "correct name"?

**Comment by ndelangen** [comment] 2023-01-17 21:59
Is this still an existing issue in 7.0 beta?

**Comment by Marklb** [comment] 2023-01-17 22:27
The issue doesn't provide their `angular.json`, so I can't say for sure, but I think this will be solved by #20559.

**Comment by danishaali9** [comment] 2023-01-27 21:43
@AlokTakshak this issue seems to be fixed as i tried to reproduce it but it was already fixed you can move it to fix section
![image](https://user-images.githubusercontent.com/35070443/215206184-9f63976d-6efc-4272-8948-24607d81dc02.png)

**Comment by yannbf** [comment] 2023-04-19 11:34
I'll be closing this issue as it seems to be solved in Storybook 7, but feel free to reopen it in case you are still experiencing it in Storybook 7!

**Closed by yannbf** 2023-04-19 11:34 UTC
Labels: bug, good first issue, help wanted, cli, has workaround, angular
