### ISSUE TITLE
Boolean default value not showing up in Addon-docs prop table

### ISSUE THREAD

**Issue by papeloto** [storybookjs/storybook#9394] opened 2020-01-12 08:37 UTC
**Describe the bug**
When using `addon:docs` prop table for React tsx components the boolean default values don't show up in the table.

**To Reproduce**
1. Follow this [guide](https://gist.github.com/shilman/bc9cbedb2a7efb5ec6710337cbd20c0c)
2. Add some boolean prop like this:

```tsx
import React, { FC } from "react";

interface ButtonProps {
  /**
   * Simple click handler
   */
  onClick?: () => void;
  /**
   * Is primary?
   */
  primary: boolean;
}

/**
 * The world's most _basic_ button
 */
export const Button: FC<ButtonProps> = ({ children, onClick }) => (
  <button onClick={onClick} type="button">
    {children}
  </button>
);

Button.defaultProps = {
  primary: true
};
```
3. Run `yarn storybook` and see the result.

![72208407-20e97480-349a-11ea-9255-647840810252](https://user-images.githubusercontent.com/36263538/72216199-6a7ba300-351e-11ea-8fca-3d0a53e046f8.png)
 

**Expected behavior**
Default values showing up.

**System:**
  System:
    OS: Linux 5.0 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 10.18.0 - /usr/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.13.4 - /usr/bin/npm
  Browsers:
    Chrome: 79.0.3945.88
    Firefox: 71.0
  npmPackages:
    @storybook/cli: ^5.3.0 => 5.3.0

**Comment by mrmckeb** [comment] 2020-01-12 13:11
@shilman I've looked over this and it appears to be an issue with Docs itself.

The default here is 'false' or 'true'. When testing, all default values come through unless Boolean. My guess is that we need to stringify the values, at least when boolean.

@papeloto are you interested in having a go at this? If not, let me know and I can take a look and make the fix :)

**Comment by ZhihaoLau** [comment] 2020-01-15 07:50
same here, boolean defaultProps disappear after upgrade to 5.3.x

**Comment by shilman** [comment] 2020-01-20 07:20
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.7 containing PR #9525 that references this issue. Upgrade today to try it out!

Closing this issue. Please re-open if you think there's still more to do.

**Comment by papeloto** [comment] 2020-01-20 08:54
Just upgraded to v5.3.7

![image](https://user-images.githubusercontent.com/36263538/72712059-99bb9100-3b6a-11ea-8e70-7cc87a1d1e3b.png)

Now false values don't show up 😂
```tsx
Button.defaultProps = {
  variant: "primary",
  disabled: false,
  type: "button",
  inline: false,
  accessibilityLabel: "Button",
  uppercase: true,
  expand: false
};
```

**Comment by shilman** [comment] 2020-01-21 14:42
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.0 containing PR #9560 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2020-01-21 14:42 UTC
Labels: addon: docs, block: props, bug, typescript

**Comment by shilman** [comment] 2020-01-21 17:20
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.8 containing PR #9560 that references this issue. Upgrade today to try it out!

**Comment by zaleGZL** [comment] 2020-01-29 07:43
> Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.8 containing PR #9560 that references this issue. Upgrade today to try it out!

Ifind the  empty string are not show, Is there a fix for this issue?

**Comment by LeandrodeLimaC** [comment] 2022-11-17 18:33
Using 
    "@storybook/react": "^6.5.13",

**Comment by LeandrodeLimaC** [comment] 2022-11-17 18:37
Using "@storybook/react": "^6.5.13" and ran into the same issue 😅 
```
args: {
    defaultChecked: false,
    checked: false,
  },
  argTypes: {
    checked: {
      defaultValue: 'indeterminate',
      options: [false, true, 'indeterminate'],
      control: { type: 'inline-radio' },
    },
    defaultChecked: {
      defaultValue: false,
    },
  }
```

I had to display those as inline radio so at least it shows wich option is select by default
![image](https://user-images.githubusercontent.com/34483410/202530219-5e85c33b-1fe1-4a48-8144-27a9c7f95eed.png)

**Comment by Fritze1602** [comment] 2022-11-25 18:11
Can confirm, that the issue is still around in 6.5.13. But despite @LeandrodeLimaC workaround the default false booleans are NOT shown in the docs.
