### ISSUE TITLE
Docs mode: includes all 555 `react-syntax-highlighter` language extensions

### ISSUE THREAD

**Issue by akdetrick** [storybookjs/storybook#8972] opened 2019-11-26 20:50 UTC
**Description**

Using `^5.3.0-beta.3` of storybook with `MDX`, build artifacts will include all 555 language extensions for `react-syntax-highlighter`.

It looks like storybook is already using the [light build](https://github.com/conorhastings/react-syntax-highlighter#light-build) of `react-syntax-highlighter`, but I'm still seeing artifacts for all languages supported by the highlighter lib.

**To Reproduce**
1. Use storybook `^5.3.0-beta.3`
2. Add at least one `MDX` story
3. Run a static storybook build
4. Build artifacts will include 555 language extensions for `react-syntax-highlighter`

**Expected behavior**
Build should include only the [languages that storybook registers](https://github.com/storybookjs/storybook/blob/5e4e5055fc5460d1768fd2a6648f2fec8c0891bb/lib/components/src/syntaxhighlighter/syntaxhighlighter.tsx#L22) with the highlighter (jsx, bash, css, html, tsx, typescript).

**System:**
```
Environment Info:

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
  Binaries:
    Node: 10.9.0 - ~/.nvm/versions/node/v10.9.0/bin/node
    Yarn: 1.15.2 - ~/.yarn/bin/yarn
    npm: 6.2.0 - ~/.nvm/versions/node/v10.9.0/bin/npm
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 70.0.1
    Safari: 13.0.3
  npmPackages:
    @storybook/addon-actions: ^5.3.0-beta.3 => 5.3.0-beta.3
    @storybook/addon-backgrounds: ^5.2.6 => 5.2.6
    @storybook/addon-centered: ^5.2.3 => 5.2.6
    @storybook/addon-docs: ^5.3.0-beta.3 => 5.3.0-beta.3
    @storybook/addon-knobs: ^5.3.0-beta.3 => 5.3.0-beta.3
    @storybook/addon-links: ^5.3.0-beta.3 => 5.3.0-beta.3
    @storybook/addon-notes: ^5.3.0-beta.3 => 5.3.0-beta.3
    @storybook/addons: ^5.3.0-beta.3 => 5.3.0-beta.3
    @storybook/react: ^5.3.0-beta.3 => 5.3.0-beta.3
    @storybook/theming: ^5.3.0-beta.3 => 5.3.0-beta.3
```

**Additional context**
When publishing to Github pages using a versioned `docs/` dir as the source, PRs appear to have 500+ changed files. We suppress diffs for generated files, but based on`syntaxhighlighter.tsx`, it doesn't look like including all language extensions was the intention behind the code.

**Comment by akdetrick** [comment] 2019-11-27 16:40
If anyone else is having a similar issue, you can work around it by adding the following to your `.gitignore`:

```
#
# Ignore unused language chunks and maps
#
react-syntax-highlighter_languages_highlight_*.*.bundle.js
react-syntax-highlighter_languages_highlight_*.*.bundle.js.map
vendors~react-syntax-highlighter_languages_highlight_*.*.bundle.js
vendors~react-syntax-highlighter_languages_highlight_*.*.bundle.js.map

#
# Unignore all the chunks storybook actually uses for MDX stories.
#
!react-syntax-highlighter_languages_highlight_jsx.*.bundle.js.map
!react-syntax-highlighter_languages_highlight_bash.*.bundle.js.map
!react-syntax-highlighter_languages_highlight_css.*.bundle.js.map
!react-syntax-highlighter_languages_highlight_html.*.bundle.js.map
!react-syntax-highlighter_languages_highlight_tsx.*.bundle.js.map
!react-syntax-highlighter_languages_highlight_typescript.*.bundle.js.map

```

**Comment by shilman** [comment] 2019-11-28 10:24
We don't do anything special about this in Docs. @ndelangen do you mind taking a look at the `Syntax Highlighter` component?

**Comment by ndelangen** [comment] 2019-11-28 21:04
I can't reproduce, could you share a reproduction repo?

**Comment by shilman** [comment] 2020-01-16 18:49
Closing as dupe to #9282

**Closed** 2020-01-23 12:03 UTC
Labels: addon: docs, dependencies, has workaround, needs reproduction
