### ISSUE TITLE
Addon-docs: Dark theme missing dark <code> style

### ISSUE THREAD

**Issue by bgriffith** [storybookjs/storybook#8094] opened 2019-09-16 16:04 UTC
**Describe the bug**
The `<code>` tag is not correctly styled when using the dark theme from `@storybook/theming`. The background is light causing it to be impossible to read.

**To Reproduce**
1. Configure Storybook to use the dark theme.
2. Create a story using MDX and use backticks to create a code tag - `for example`
3. View story

**Expected behavior**
There should be a dark background for the `code` tag. 

**Screenshots**
<img width="1007" alt="Screenshot 2019-09-16 at 16 59 19" src="https://user-images.githubusercontent.com/2854338/64973699-635fc380-d8a3-11e9-81f9-77f34d6d189c.png">

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
```
Environment Info:

  System:
    OS: macOS 10.15
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 10.14.2 - ~/.nvm/versions/node/v10.14.2/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.2 - ~/.nvm/versions/node/v10.14.2/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 69.0
    Safari: 13.0.1
  npmPackages:
    @storybook/addon-actions: ^5.2.0 => 5.2.0 
    @storybook/addon-docs: ^5.2.0 => 5.2.0 
    @storybook/addon-info: ^5.2.0 => 5.2.0 
    @storybook/addon-knobs: ^5.2.0 => 5.2.0 
    @storybook/addon-links: ^5.2.0 => 5.2.0 
    @storybook/addon-options: ^5.2.0 => 5.2.0 
    @storybook/addons: ^5.2.0 => 5.2.0 
    @storybook/react: ^5.2.0 => 5.2.0 
```

**Additional context**

**Comment by sanchez** [comment] 2019-10-02 06:06
I have encountered a similar issue for the code snippet for stories in mdx. See below

![image](https://user-images.githubusercontent.com/5264697/66021589-838fb380-e52e-11e9-9f33-07a65488f4e5.png)

I have fixed this by adding this css snippet into a site wide css file referenced:
```css
.tag:not(body) {
  background-color: inherit;
}
```

**Comment by sanchez** [comment] 2019-10-03 02:50
I have also discovered this little gem that has occured in the source viewer

![image](https://user-images.githubusercontent.com/5264697/66095802-3cf89280-e5dc-11e9-9322-599fc0f5e08b.png)

The code to reproduce this:

```
<Preview>
  <Story name="progress">
    <div style={{ display: 'flex' }}>
      <Loading progress={0} />
      <div style={{ padding: 10 }} />
      <Loading progress={33} />
      <div style={{ padding: 10 }} />
      <Loading progress={75} />
      <div style={{ padding: 10 }} />
      <Loading progress={100} />
    </div>
  </Story>
</Preview>
```

**Comment by sanchez** [comment] 2019-10-03 02:53
Turns out the issue was to do with a css selector from another library sorry. However I am wondering why the code blocks aren't prefixed? Thanks

**Comment by shilman** [comment] 2019-10-03 07:23
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.7 containing PR #8260 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2019-10-03 07:23 UTC
Labels: addon: docs, bug, theming

**Comment by shilman** [comment] 2019-10-07 10:14
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.2 containing PR #8260 that references this issue. Upgrade today to try it out!

**Comment by jeffryang24** [comment] 2020-02-24 02:51
I also still found this issue in `5.3.13`. :thinking: 

![white_bg_code](https://user-images.githubusercontent.com/8284757/75126125-1baf5480-56eb-11ea-93e5-3413e4b43910.png)

**Comment by shilman** [comment] 2020-02-24 06:27
@jeffryang24 I think this is some of your component CSS clashing with the CSS of `react-syntax-highlighter`.

**Comment by jeffryang24** [comment] 2020-02-24 08:12
> @jeffryang24 I think this is some of your component CSS clashing with the CSS of `react-syntax-highlighter`.

I see... Currently I used bulma css, will check its style later... :bowing_man:
