### ISSUE TITLE
validateDOMNesting error when displaying a URL generated by compodocs 

### ISSUE THREAD

**Issue by dexster** [storybookjs/storybook#14176] opened 2021-03-09 08:44 UTC
### Bug

In an Angular project Storybook is displaying this console error for a link generated by Compodocs 

```
Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.
    in a (created by Markdown)
    in a (created by Markdown)
    in p (created by Markdown)
    in Markdown (created by ArgRow)
    in div (created by Context.Consumer)
    in Styled(div) (created by ArgRow)
    ...
```

### Steps to reproduce

Add JSDocs to an `@Input` in an angular component
```
/**
     * This is a test
     * https://example.com
*/
```

or

```
/**
     * This is a test
     * {@link https://example.com|Example}
*/
```

Then run storybook to generate the docs and start the site

Compodocs generates this in documentation.json

`<p>This is a test\n<a href=\"https://example.com\">https://example.com</a></p>`

and then Storybook wraps this in another pair of `<a>` tags

```
<p>This is a test
    <a href="https://example.com">
        <a href="https://example.com">https://example.com</a>
     </a>
</p>
```

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/angular 6.1.21

**Comment by TheMightyPenguin** [comment] 2021-03-12 21:36
@shilman I'd like to give this one a shot, I'll start working on it!

**Comment by TheMightyPenguin** [comment] 2021-03-13 05:10
I was able to reproduce using the https://github.com/chromaui/intro-storybook-angular-template template, I'll keep researching to find the root cause

**Comment by TheMightyPenguin** [comment] 2021-03-13 18:40
After some debugging, the issue seems to be in the `ArgRow` component, which is used to render this table of props with the description, but the issue seems to be caused by an external dependency, `markdown-to-jsx`:

https://github.com/storybookjs/storybook/blob/4f5ab9fe9e590da7b841ec37cb1bed8d6327ea4b/lib/components/src/blocks/ArgsTable/ArgRow.tsx#L86

I was playing with this library in their [playground](https://probablyup.com/markdown-to-jsx/), if you input this text there:

```
<p>Is this the principal call to action on the page?<a href=\"https://example.com\">https://example.com</a></p>
```

And inspect the DOM, it will have an extra anchor tag wrapping the one that's already present. Now I'll check if it's the usage of the library (some option we can use to fix?) or if it's an implementation detail on their side.

**Comment by dexster** [comment] 2021-03-13 19:24
FYI, I've got a PR for that library to fix #14116

**Comment by TheMightyPenguin** [comment] 2021-03-13 20:30
@dexster great 👍 I'll open another PR to that library to fix the anchor issue as well!

**Comment by TheMightyPenguin** [comment] 2021-03-13 23:42
@dexster @shilman I opened a PR to `markdown-to-jsx` fixing this issue, if it does get merged we can update the library version here to fix this issue probablyup/markdown-to-jsx#379

**Comment by TheMightyPenguin** [comment] 2021-05-28 21:26
@shilman @dexster my PR to the library has been merged 😄 and now I opened a PR to Storybook to update the library version: https://github.com/storybookjs/storybook/pull/15083

**Comment by shilman** [comment] 2021-05-30 05:14
Yippee!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-beta.5 containing PR #15083 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2021-05-30 05:14 UTC
Labels: PN, addon: docs, app: angular, good first issue, help wanted
