### ISSUE TITLE
[Feature Request]: Backport zone.js range extension to v6

### ISSUE THREAD

**Issue by kbrilla** [storybookjs/storybook#21447] opened 2023-03-07 09:22 UTC
### Is your feature request related to a problem? Please describe

Currently updating Angular to v15.2 updates zone.js  to v0.12.0 which breaks `npm i `

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @storybook/angular@6.5.16
npm ERR! Found: zone.js@0.12.0
npm ERR! node_modules/zone.js
npm ERR!   zone.js@"0.12.0" from the root project
npm ERR!   peer zone.js@"~0.11.4 || ~0.12.0 || ~0.13.0" from @angular/core@15.2.1
npm ERR!   node_modules/@angular/core
npm ERR!     @angular/core@"15.2.1" from the root project
npm ERR!     peer @angular/core@"^15.0.0" from @angular-builders/jest@15.0.0
npm ERR!     node_modules/@angular-builders/jest
npm ERR!       dev @angular-builders/jest@"15.0.0" from the root project
npm ERR!     28 more (jest-preset-angular, @angular/animations, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer zone.js@"^0.8.29 || ^0.9.0 || ^0.10.0 || ^0.11.0" from @storybook/angular@6.5.16
npm ERR! node_modules/@storybook/angular
npm ERR!   dev @storybook/angular@"6.5.16" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: zone.js@0.11.8
npm ERR! node_modules/zone.js
npm ERR!   peer zone.js@"^0.8.29 || ^0.9.0 || ^0.10.0 || ^0.11.0" from @storybook/angular@6.5.16
npm ERR!   node_modules/@storybook/angular
npm ERR!     dev @storybook/angular@"6.5.16" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### Describe the solution you'd like

Backport #20107

### Are you able to assist to bring the feature to reality?

no

**Comment by valentinpalkovic** [comment] 2023-03-07 13:48
Duplicate of https://github.com/storybookjs/storybook/issues/20758

**Closed by valentinpalkovic** 2023-03-07 13:48 UTC
Labels: feature request, needs triage
