### ISSUE TITLE
FAST_REFRESH=true causes compilation error (Webpack 5 support)

### ISSUE THREAD

**Issue by dn-l** [storybookjs/storybook#13745] opened 2021-01-27 13:18 UTC
**Describe the bug**
FAST_REFRESH=true causes compilation error. 
Same as if I would configure .storybook/main.js or add plugin manually into config.plugins.

**To Reproduce**

1. Default config
2. `FAST_REFRESH=true start-storybook`

The same project builds successfully with webpack & @pmmmwh/react-refresh-webpack-plugin.
The same storybook compiles without FAST_REFRESH=true

```bash
yarn run v1.22.10
$ FAST_REFRESH=true start-storybook
info @storybook/react v6.1.15
info => Using prebuilt manager
info => Loading presets
info => Loading 1 config file in "./.storybook"
info => Loading 7 other files in "./.storybook"
info => Adding stories defined in ".storybook/main.js"
info => Using React fast refresh
info => Using default Webpack setup
0% compilingERR! TypeError: Cannot read property 'tap' of undefined
ERR!     at /Users/dan/github/project/node_modules/@pmmmwh/react-refresh-webpack-plugin/lib/index.js:236:65
```

**Expected behavior**
Succesful compilation

**System**
```bash
Environment Info:

  System:
    OS: macOS 11.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 13.8.0 - ~/.nvm/versions/node/v13.8.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v13.8.0/bin/yarn
    npm: 6.13.6 - ~/.nvm/versions/node/v13.8.0/bin/npm
  Browsers:
    Chrome: 88.0.4324.96
    Firefox: 84.0.2
    Safari: 14.0.2
  npmPackages:
    @storybook/addon-actions: ^6.1.15 => 6.1.15 
    @storybook/addon-essentials: ^6.1.15 => 6.1.15 
    @storybook/addon-links: ^6.1.15 => 6.1.15 
    @storybook/react: ^6.1.15 => 6.1.15 
```

Packages:
```json
    "react-refresh": "^0.9.0",
    "webpack": "^5.18.0",
    "@pmmmwh/react-refresh-webpack-plugin": "^0.4.3",
```

**Comment by dn-l** [comment] 2021-01-28 09:10
It works if I remove `@pmmmwh/react-refresh-webpack-plugin`

**Comment by tooppaaa** [comment] 2021-01-31 14:44
Storybook has a dependency to @pmmmwh/react-refresh-webpack-plugin@0.4.2, which appears to not have webpack 5 support. https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/main/CHANGELOG.md#fixes

> Fixed Webpack 5 compatibility by requiring __webpack_require__ (#233)

Storybook isn't (up to my knowledge) compatible with webpack 5 until 6.2. @shilman

**Comment by shilman** [comment] 2021-01-31 16:21
That's correct. We're shooting for webpack 5 support in 6.2. I guess we'll need to figure out fast refresh in webpack 5 or live without it for now.

**Comment by dn-l** [comment] 2021-01-31 18:55
Oooh gotya! 👍

**Comment by timkindberg** [comment] 2021-02-03 18:16
Hate to be this guy, but any rough ETA on when 6.2 would be release? Days, weeks, months?

**Comment by shilman** [comment] 2021-02-21 14:09
@timkindberg going to beta this week, final in about a month (knock wood)

**Comment by rtrembecky** [comment] 2021-07-07 11:37
Hi, fast refresh still doesn't work for me. Whether I use `FAST_REFRESH = true` or `reactOptions: { fastRefresh: true }`, I get:
```
/Users/richard/uc/web/node_modules/webpack/lib/NormalModuleFactory.js:294
                                                        throw new Error(
                                                        ^

Error: NormalModuleFactory.afterResolve (CaseSensitivePathsPlugin, ReactRefreshPlugin) is no longer a waterfall hook, but a bailing hook instead. Do not return the passed object, but modify it instead. Returning false will ignore the request and results in no module created.
    at /Users/richard/uc/web/node_modules/webpack/lib/NormalModuleFactory.js:294:14
    at _next0 (eval at create (/Users/richard/uc/web/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at eval (eval at create (/Users/richard/uc/web/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:1)
    at /Users/richard/uc/web/node_modules/case-sensitive-paths-webpack-plugin/index.js:176:9
```

`npx sb info`:
```
Environment Info:

  System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 2.4.1 - ~/.nvm/versions/node/v12.16.3/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.16.3/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 88.0.1
    Safari: 14.1.1
  npmPackages:
    @storybook/addon-actions: ^6.3.2 => 6.3.2 
    @storybook/addon-docs: ^6.3.2 => 6.3.2 
    @storybook/addon-essentials: ^6.3.2 => 6.3.2 
    @storybook/addon-links: ^6.3.2 => 6.3.2 
    @storybook/builder-webpack5: ^6.3.2 => 6.3.2 
    @storybook/manager-webpack5: ^6.3.2 => 6.3.2 
    @storybook/react: ^6.3.2 => 6.3.2 
```

`react-refresh-webpack-plugin` is at 0.4.3 already, so this is some new problem 🤔

**Comment by ZJH9Rondo** [comment] 2021-07-14 09:40
@rtrembecky the same problem

**Comment by dcwarwick** [comment] 2021-07-15 01:09
I'm seeing this problem too -- it does indeed look like a new problem, recently appearing. I see some deprecation warnings before, which I don't know if they are relevant:

```
...
info => Using React fast refresh
info => Using default Webpack5 setup
info => Loading custom manager config
[DEP_WEBPACK_MAIN_TEMPLATE_OUTPUT_OPTIONS] DeprecationWarning: MainTemplate.outputOptions is deprecated (use Compilation.outputOptions instead)
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:50426) [DEP_WEBPACK_MAIN_TEMPLATE_REQUIRE] DeprecationWarning: MainTemplate.hooks.require is deprecated (use JavascriptModulesPlugin.getCompilationHooks().renderRequire instead)
(node:50426) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader
info => Using cached manager
/Users/dave/git/ibm-cloud-cognitive/node_modules/webpack/lib/NormalModuleFactory.js:294
							throw new Error(
							^
Error: NormalModuleFactory.afterResolve (CaseSensitivePathsPlugin, ReactRefreshPlugin) is no longer a waterfall hook, but a bailing hook instead. Do not return the passed object, but modify it instead. Returning false will ignore the request and results in no module created.
    at /Users/dave/git/ibm-cloud-cognitive/node_modules/webpack/lib/NormalModuleFactory.js:294:14
    at _next0 (eval at create (/Users/dave/git/ibm-cloud-cognitive/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:17:1)
    at eval (eval at create (/Users/dave/git/ibm-cloud-cognitive/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:33:1)
    at /Users/dave/git/ibm-cloud-cognitive/node_modules/case-sensitive-paths-webpack-plugin/index.js:176:9
    at /Users/dave/git/ibm-cloud-cognitive/node_modules/case-sensitive-paths-webpack-plugin/index.js:125:7
    at /Users/dave/git/ibm-cloud-cognitive/node_modules/case-sensitive-paths-webpack-plugin/index.js:125:7
    at CaseSensitivePathsPlugin.fileExistsWithCase (/Users/dave/git/ibm-cloud-cognitive/node_modules/case-sensitive-paths-webpack-plugin/index.js:95:5)
    at /Users/dave/git/ibm-cloud-cognitive/node_modules/case-sensitive-paths-webpack-plugin/index.js:118:10
    at CaseSensitivePathsPlugin.getFilenamesInDir (/Users/dave/git/ibm-cloud-cognitive/node_modules/case-sensitive-paths-webpack-plugin/index.js:52:5)
    at CaseSensitivePathsPlugin.fileExistsWithCase (/Users/dave/git/ibm-cloud-cognitive/node_modules/case-sensitive-paths-webpack-plugin/index.js:101:8)
    at /Users/dave/git/ibm-cloud-cognitive/node_modules/case-sensitive-paths-webpack-plugin/index.js:118:10
    at /Users/dave/git/ibm-cloud-cognitive/node_modules/case-sensitive-paths-webpack-plugin/index.js:72:5
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
error Command failed with exit code 1.
```

**Comment by ZJH9Rondo** [comment] 2021-07-15 07:20
@shilman SOS!!!

**Comment by iseredov** [comment] 2021-07-21 07:49
Try to remove yarn.lock and reinstall dependencies.

**Comment by rtrembecky** [comment] 2021-07-26 08:07
> Try to remove yarn.lock and reinstall dependencies.

@iseredov tried now, didn't work.

**Comment by dcwarwick** [comment] 2021-08-02 16:09
> Try to remove yarn.lock and reinstall dependencies.

Ditto: removed yarn.lock cleared caches and ran `yarn` afresh, and get the exact same set of messages I posted above. I'm keeping `fastRefresh: true` commented out for the time being as a workaround.

**Comment by shilman** [comment] 2021-08-02 17:39
Try upgrading to the latest prerelease:

```
npx sb@next upgrade --prerelease
```

Does that fix it? It contains this PR that's supposed to fix it: https://github.com/storybookjs/storybook/pull/15616

**Comment by shilman** [comment] 2021-08-02 17:41
In fact, I'm going to close this as fixed in https://github.com/storybookjs/storybook/pull/15616 

Please upgrade and let me know if it's not working. If so, I'll reopen!

**Closed by shilman** 2021-08-02 17:41 UTC
Labels: app: react, babel / webpack, compatibility with other tools

**Comment by rtrembecky** [comment] 2021-08-03 08:23
> Does that fix it? It contains this PR that's supposed to fix it: #15616

@shilman Yes, it works now (having `6.4.0-alpha.22`), thank you for letting us know.

**Comment by dcwarwick** [comment] 2021-08-03 17:12
@shilman I've not been able to check this because my storybook comes up empty on `6.4.0-alpha.22`. In fact, it comes up empty on anything from `6.4.0-alpha.20` onwards -- it's fine up to and including `6.4.0-alpha.19`. I wonder if something in #15399 has caused something to change? My storybook config supplies an array of specific individual path-and-file-names for the `stories` field, as we resolve our own glob and then filter out some unwanted files. Is this a known problem already, or do you need me to open an issue?

**Comment by shilman** [comment] 2021-08-03 17:17
@dcwarwick perhaps there's a regression in #15399? if you could open a new issue with a reproduction that would be really helpful https://storybook.js.org/docs/react/contribute/how-to-reproduce

**Comment by dcwarwick** [comment] 2021-08-03 18:30
Opened issue #15746

**Comment by dcwarwick** [comment] 2021-08-07 20:22
@shilman It works for us too with `6.4.0-alpha.25`, many thanks!
