### ISSUE TITLE
Can't set callback arg to `null` on @storybook/react 6.3.0

### ISSUE THREAD

**Issue by quangv** [storybookjs/storybook#15370] opened 2021-06-25 17:11 UTC
**Describe the bug**
As of @storybook/react 6.3.0 can't seem to set a callback arg to `null`, the `argTypesRegex` seems to over zealously create an actionHandler when manually setting an arg callback to `null`. This wasn't happening with @storybook/react 6.2.9

**To Reproduce**
Please create a reproduction by running `npx sb@next repro` and following the instructions. Read our [documentation](https://storybook.js.org/docs/react/contribute/how-to-reproduce) to learn more about creating reproductions.
Paste your repository and deployed reproduction here. We prioritize issues with reproductions over those without.

https://github.com/quangv/storybook_bug-null-callback

specifically: https://github.com/quangv/storybook_bug-null-callback/commit/4f5a1e898999158ff10221bb11dc2db525399145

```
export const Primary = Template.bind({});
Primary.args = {
  primary: true,
  label: 'Button',
  onClick: null // can't seem to set this to null
};
```

Only way I can figure out how to keep it `null` is tweaking the `argsTypesRegex`

`    parameters: { actions: { argTypesRegex: '^on(?!Click).*' } }
`

**System**

`ᐅ npx sb@next info

Environment Info:

  System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
    Yarn: 2.4.2 - ~/.nvm/versions/node/v12.22.1/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v12.22.1/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Safari: 14.1.1
  npmPackages:
    @storybook/addon-actions: ^6.4.0-alpha.2 => 6.4.0-alpha.2
    @storybook/addon-docs: ^6.4.0-alpha.2 => 6.4.0-alpha.2
    @storybook/addon-essentials: ^6.4.0-alpha.2 => 6.4.0-alpha.2
    @storybook/addon-links: ^6.4.0-alpha.2 => 6.4.0-alpha.2
    @storybook/react: ^6.4.0-alpha.2 => 6.4.0-alpha.2`
    
**Additional context**
n/a

**Comment by quangv** [comment] 2021-06-25 18:28
I noticed it doesn't have to do with `null`, but the `arg.onHandler` gets overwritten regardless of the value... is this suppose to happen now as of v6.3.0 ?

I do see we can still access it via the new `originalStoryFn.args` ...

**Comment by shilman** [comment] 2021-06-28 07:49
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-alpha.4 containing PR #15394 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2021-06-28 07:49 UTC
Labels: P0, args, bug

**Comment by shilman** [comment] 2021-06-28 09:00
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.1 containing PR #15394 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

**Comment by brandonthomas** [comment] 2022-09-06 21:50
@shilman I'm still seeing this in 6.5.9.

**Comment by shilman** [comment] 2022-09-07 01:52
@brandonthomas can you please share a reproduction?  i just tried it in the original repro & it demonstrates the bug, but upgraded to 6.5 and the bug is fixed (for that example, at least)

**Comment by brandonthomas** [comment] 2022-09-12 19:26
> @brandonthomas can you please share a reproduction? i just tried it in the original repro & it demonstrates the bug, but upgraded to 6.5 and the bug is fixed (for that example, at least)

Just did more digging and looks like we had an erroneous argTypesRegex so I think we're good now. It was pulling in a bunch of `on*` render functions. Removal of argTypesRegex fixed the issue.
