### ISSUE TITLE
`StorybookConfig` type missing `env`

### ISSUE THREAD

**Issue by stefanprobst** [storybookjs/storybook#18778] opened 2022-07-24 07:29 UTC
**Describe the bug**

The [`StorybookConfig`](https://github.com/storybookjs/storybook/blob/next/lib/core-common/src/types.ts#L332-L453) type is missing the [`env` config key](https://storybook.js.org/docs/react/configure/environment-variables#using-storybook-configuration).

**To Reproduce**
Please create a reproduction by running `npx sb@next repro` and following the instructions. Read our [documentation](https://storybook.js.org/docs/react/contribute/how-to-reproduce) to learn more about creating reproductions.
Paste your repository and deployed reproduction here. We prioritize issues with reproductions over those without.

**System**
Please paste the results of `npx sb@next info` here.

```
Environment Info:

  System:
    OS: Linux 5.15 KDE neon 5.25
    CPU: (4) x64 Intel(R) Core(TM) i5-6400T CPU @ 2.20GHz
  Binaries:
    Node: 16.16.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.11.0 - /usr/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Firefox: 102.0
  npmPackages:
    @storybook/addon-a11y: ^6.5.9 => 6.5.9 
    @storybook/addon-actions: ^6.5.9 => 6.5.9 
    @storybook/addon-essentials: ^6.5.9 => 6.5.9 
    @storybook/addon-interactions: ^6.5.9 => 6.5.9 
    @storybook/addon-links: ^6.5.9 => 6.5.9 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/builder-webpack5: ^6.5.9 => 6.5.9 
    @storybook/manager-webpack5: ^6.5.9 => 6.5.9 
    @storybook/mdx2-csf: ^0.0.3 => 0.0.3 
    @storybook/react: ^6.5.9 => 6.5.9 
```

**Additional context**

**Comment by shilman** [comment] 2023-06-09 02:11
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

Pretty sure this is fixed in 7.0

**Closed by shilman** 2023-06-09 02:11 UTC
Labels: bug, typescript
