### ISSUE TITLE
Storybook 6.2.0-beta new angular renderer ovverides properties

### ISSUE THREAD

**Issue by criskrzysiu** [storybookjs/storybook#14147] opened 2021-03-05 11:57 UTC
**Describe the bug**
if component has some properties that are not inputs they are overridden
```@Component()
export class SampleComp{
   @Input() input1: string;
   notInputProperty: string;

  ngOnChanges(){
  this.notInputProperty = 'kokos';
   }
}
```

and template will be  
```
notInputProperty : {{notInputProperty }}
```
then notInputProperty will be overridden after change detection we will get rendered ```notInputProperty : `.

if we add ```@Input``` decorator to this property then it works as it should and we get rendered: ```notInputProperty : kokos'.

setting   ```angularLegacyRendering: true,``` solves the issue.

```
export default {
  title: 'Components/Core/SampleComp',
  component: SampleComp,
  decorators: [
    moduleMetadata({
      declarations: [SampleComp],
    }),
  ],
} as Meta;

const Template: Story<SampleComp> = (args) => ({
  props: args,
});

export const Sample = Template.bind({});
Sample.args = {};
```

fun fact: 
after first time storybooks renders You will change the name of property to lets say ```notInputProperty2``` then it will work! 
So maybe it has something to do with controls? 
Restarting storybook  (ctr+c) and npm run storybook again will again cause it to be overridden till You again change the name of property to  lets  say ```notInputProperty3```.

**System**
```
  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 88.0.4324.190
    Edge: Spartan (44.19041.423.0), Chromium (88.0.705.81)
  npmPackages:
    @storybook/addon-actions: 6.2.0-beta.10 => 6.2.0-beta.10
    @storybook/addon-centered: 5.3.21 => 5.3.21
    @storybook/addon-essentials: 6.2.0-beta.10 => 6.2.0-beta.10
    @storybook/addon-links: 6.2.0-beta.10 => 6.2.0-beta.10
    @storybook/addon-storysource: 6.2.0-beta.10 => 6.2.0-beta.10
    @storybook/angular: 6.2.0-beta.10 => 6.2.0-beta.10
```

**Comment by ThibaudAV** [comment] 2021-03-10 07:48
Yes, it's true. But I don't think it's a "bug". 🙈 Give me a few days to find time to make a complete answer. (very busy lately 😞 )

**Comment by criskrzysiu** [comment] 2021-03-10 15:01
Well I don’t think storybook should change in any way properties that are
not inputs and are even private (i know ts private is come and take It).
But, sure will wiat for update on Your side. For now will keep legacy
rendering on.


W dniu śr., 10.03.2021 o 08:48 ThibaudAV ***@***.***>
napisał(a):

**Comment by ThibaudAV** [comment] 2021-03-15 16:05
In fact I don't know where to start... many things are mixed up 


### Problem Replication: 

If I understand correctly your example is this: 
<details>
  <summary>Click to expand!</summary>
  
```ts
import { Story, Meta, moduleMetadata } from '@storybook/angular';
import { Input, Component } from '@angular/core';

@Component({ selector: 'foo', template: 'notInputProperty : {{notInputProperty }}' })
class SampleComp {
  @Input() input1: string;

  notInputProperty = 'rr';

  ngOnChanges() {
    this.notInputProperty = 'kokos';
  }
}

export default {
  title: 'Legacy / angularLegacyRendering',
  component: SampleComp,
  decorators: [
    moduleMetadata({
      declarations: [SampleComp],
    }),
  ],
} as Meta;

const Template: Story<SampleComp> = (args) => {
  console.log(args);

  return {
    props: args,
    // angularLegacyRendering: true,
  };
};

export const Sample = Template.bind({});
Sample.args = {};

```
</details>

here are the steps I do :

- Add story without `angularLegacyRendering: true`
- run `yarn storybook`
> see the console.log `{input1: undefined, notInputProperty: undefined, ngOnChanges: undefined}`
- change `input1` value with controls 
> nothing happen but i have log + error in console : 
![image](https://user-images.githubusercontent.com/4974420/111175081-5448f700-85a8-11eb-906b-371bf3c5f8ff.png)


- change with `angularLegacyRendering: true`
> see the console.log `{}` :wow: empty now 
- change `input1` value with controls 
> see the console.log `{input1: "s"}` 
> It works, we can see Koko in canvas


Now, if i do same step (close storybook client and restart it) but i start storybook with `angularLegacyRendering: true`
> I have the same behavior. 
So, If it's the same problem you encountered, the problem is not the new rendering 

I think the problem comes from compodoc. Which discovers all properties of your component class and adds them to agrs.
If you don't control it, it will do anything. 

Discussions are already in progress to replace compodoc 
https://github.com/storybookjs/storybook/issues/12689
https://github.com/storybookjs/storybook/issues/8672

personally I don't like compodoc at all and I don't use it 

I recommend you not to trust compodoc if you use it and to do something like : 

```ts
const Template: Story<SampleComp> = (args) => ({
  props: {
  input1: args.input1
  },
});
```
to be sure to send only the expected "arg"  

---

### So : 

- `compodoc` reference les propriétés privées

Wait for an alternative. or manually add controls of args

- `props` can override private (or non @input) properties of components 

Several topics are talking about it, it also blocks some features 
I have already made a response in some of them

https://github.com/storybookjs/storybook/issues/11613
https://github.com/storybookjs/storybook/issues/12946

or else https://github.com/storybookjs/storybook/issues/12438

I really wish I could ban it or split it into 2 like: 
`props` : only angular Input / Output / directive (ngClass,...) or html attributs (class,...) 
`overrideComponentProperties`: As before allows to override a property of the component class


Comportement du legacy :
Il y a eu plusieurs discussion sur le sujet mais en gros props représente les propriétés du composant (privée public, avec ou sans @Input)

Je n'ai pas construit le legacy rendering don je n'en connais pas l'intention. ce qui fait penser a cette règle c'est : 








ss

**Comment by criskrzysiu** [comment] 2021-03-24 11:41
one thing is still making me unsure if it is problem with compdoc beacause even if I disable

**Comment by criskrzysiu** [comment] 2021-03-24 11:41
srx, wanted to just cancel comment, srx

**Comment by nicolae536** [comment] 2021-04-01 09:53
Any updates on this ?

**Comment by salmin89** [comment] 2021-04-15 21:22
> ## legacy rendering and ngOnChanges
> I don't recommend to use legacy rendering if you have stories and component with ngOnchanges. it is manually called by the renderer and is not exactly the same as native angular.
> see:

We turned on legacyRendering because we got these kinds of errors:
> ERROR TypeError: provider.ngAfterViewInit is not a function


How would we turn off angularLegacyRendering and solving the above error?

**Comment by ThibaudAV** [comment] 2021-04-16 16:21
@salmin89 can you give more details about the component you added in the story ? 

Make sure that you do not directly pass all `args` in your story `props`
prefer a "destructuring" to control them : 
```
const Template: Story<SampleComp> = (args) => ({
  props: {
  input1: args.input1
  },
});
```

**Comment by ThibaudAV** [comment] 2021-06-03 15:34
I think we can close it a workaround has been added to avoid the override
can you check if the problem is still present with the last version 🙏

**Closed** 2021-06-03 15:46 UTC
Labels: app: angular, bug, has workaround

**Comment by DigiBanks99** [comment] 2022-01-13 10:46
Hi, the problem still persists and the workaround also doesn't work anymore.

**Comment by pscadding** [comment] 2022-06-08 16:58
In case it helps anyone else who ends up here I added `--disablePrivate` and `--disableInternal` to the compodocArgs to get it to stop finding the private properties. 
Added in the `angular.json`:
```JSON
{
  ...
  "projects": {
    "my-lib": {
      ...
      "architect": {
        "storybook": {
          "builder": "@storybook/angular:start-storybook",
          "options": {
            ...
            "compodocArgs": ["-e", "json", "--disablePrivate", "--disableInternal"]
          }
        },
```
