### ISSUE TITLE
Allow defining controls for argTypes that are objects (nested properties)

### ISSUE THREAD

**Issue by franktopel** [storybookjs/storybook#16089] opened 2021-09-17 11:06 UTC
**Is your feature request related to a problem? Please describe**
Also see https://stackoverflow.com/questions/69220096/storybook-how-to-define-argtypes-for-properties-that-are-objects
I have an input web component that has a very simple API - it has both a `get state()` and a `set state(model)`. This web component also handles the `label` which is being used for the input, thus a simple `model` looks like this:

```json
{
  "value": "Foobar",
  "required": true,
  "disabled": false,
  "label": {
    "text": "Label for input",
    "toolTip": "Tooltip for the input's label",
    "position": "east"
  }
}
```

Now to describe the `argTypes` for the stories, I tried this:

```javascript
export default {
    title: `Components/Input/text-input`,
    argTypes: {
        value: { control: 'text' },
        disabled: { control: 'boolean' },
        required: { control: 'boolean' },
        label: {
            text: { control: 'text' },
            toolTip: { control: 'text' },
            position: { control: 'select', options: ['north', 'south', 'east', 'west'] },
        },
    },
};
```

it renders in Storybook as follows:

[![enter image description here][1]][1]

As you can see, I'm not getting proper controls for the `label` aspect, like e.g. a dropdown for `label.position`.

So how do I achieve that without changing my model structure?

Note: I'm using Storybook HTML v6.3.8.

  [1]: https://i.stack.imgur.com/dJBGi.png

**Describe the solution you'd like**
I would love to see the syntax work as shown in the StackOverflow question:

```javascript
    argTypes: {
        value: { control: 'text' },
        disabled: { control: 'boolean' },
        required: { control: 'boolean' },
        label: {
            text: { control: 'text' },
            toolTip: { control: 'text' },
            position: { control: 'select', options: ['north', 'south', 'east', 'west'] },
        },
```
**Describe alternatives you've considered**
Sure, I could compromise on my `state` structure and make all `label` properties *flat* `state` properties like `labelText`, `labelPosition`, and `labelToolTip`. But as I understand, Storybook is not meant to influence design decisions this way.

**Are you able to assist to bring the feature to reality?**
I will probably not be able to help implementing this. This seems like a very basic/common need though and I'm surprised I couldn't find anything on it in the docs/in storybook.

**Additional context**

**Comment by shilman** [comment] 2021-09-17 14:15
closing as dupe to #12078

**Closed by shilman** 2021-09-17 14:15 UTC
Labels: feature request, addon: controls, duplicate, needs triage

**Comment by franktopel** [comment] 2021-09-20 15:38
Sorry, I tried to follow that #12078, but turned out to be totally unable to figure out what is the state of the whole thing.

I understand for objects you originally only had a textarea that allowed editing the object in JSON notation.

Then you implemented a tree view (which is what I'm currently getting, and dissatisfied with, hence this issue).

What I'm asking for is to allow `argTypes` to allow for nested control definitions:
```javascript
      argTypes: {
        value: { control: 'text' },
        disabled: { control: 'boolean' },
        required: { control: 'boolean' },
        label: {
            text: { control: 'text' },
            toolTip: { control: 'text' },
            position: { control: 'select', options: ['north', 'south', 'east', 'west'] },
        },
```

So I'm not asking for any new features here, I'm just asking to allow using existing controls for nested properties.

**Comment by franktopel** [comment] 2021-09-20 16:28
If I can be of any assistance in implementing this, I'd love to, but I'd definitely need some guidance.

**Comment by franktopel** [comment] 2021-09-20 17:11
What I've tried so far:

Im using a `TemplateFactory` function to replace the odd `Template.bind({})` just to create a new instance. Our components each support setting the component state via an `el.state` setter.

```javascript
import { ArgsParser } from '../helper/ArgsParser.js';

export function TemplateFactory(tagName) {
    return (args) => {
        const el = document.createElement(tagName);
        el.state = ArgsParser.expand(args);
        return el;
    };
}
```
```javascript
// ArgsParser
export class ArgsParser {
    static flat = (args) => {
        const parsedArgs = {};
        for (const [key, value] of Object.entries(args)) {
            if (['string', 'boolean', 'number'].includes(typeof value)) {
                parsedArgs[key] = value;
            } else {
                for (const innerKey in value) parsedArgs[`${key}.${innerKey}`] = value[innerKey];
            }
        }
        return parsedArgs;
    };

    static expand(args) {
        const parsedArgs = {};
        for (const [key, value] of Object.entries(args)) {
            const parsedKeys = key.split('.');
            if (parsedKeys.length === 1) {
                parsedArgs[key] = value;
            } else {
                const [parentKey, prop] = parsedKeys;
                parsedArgs[parentKey] = parsedArgs[parentKey] ?? {};
                parsedArgs[parentKey][prop] = value[prop];
            }
        }
        return parsedArgs;
    }
}
```

```javascript
// custom-text.stories.js
import { TemplateFactory } from '../helper/TemplateFactory.js';
const TAG_NAME = 'custom-text';

export default {
    title: `Components/Input/${TAG_NAME}`,
    argTypes: {
        value: { control: 'text' },
        disabled: { control: 'boolean' },
        required: { control: 'boolean' },
        ['label.text']: { control: 'text' },
        ['label.toolTip']: { control: 'text' },
        ['label.position']: {
            control: { type: 'select', options: ['north', 'south', 'east', 'west'] },
        },
    },
};

export const EmptyEnabled = TemplateFactory(TAG_NAME);
EmptyEnabled.args = {
    value: '',
    disabled: false,
    ['label.text']: 'Empty and Labeled',
    ['label.toolTip']: 'Beautiful tooltip',
    ['label.position']: 'north',
};
```
This results in:

<img width="1177" alt="grafik" src="https://user-images.githubusercontent.com/10668603/134044250-06a53215-4a15-4ba5-a686-63252e53d25b.png">

but when I try to use the radio buttons for `label.position` it doesn't affect the component, but (only after picking twice) it results in the JSON suddenly displaying `undefined` for `position`:

<img width="1174" alt="grafik" src="https://user-images.githubusercontent.com/10668603/134044460-f2aacdea-cacf-4871-9c08-457bc88ad193.png">

The same happens if I edit `label.text` and/or `label.toolTip`:

<img width="1174" alt="grafik" src="https://user-images.githubusercontent.com/10668603/134044596-8850ae21-3d2b-45fc-858e-ff4459503296.png">

**Comment by franktopel** [comment] 2021-09-20 17:19
Please let me know if my whole approach is bound to fail, or what modifications I'd need to apply to get it working.

**Comment by cjimmy** [comment] 2022-01-27 03:31
@Sparragus thanks for that! That helped me out. I decided to use lodash's `cloneDeep` and `set` instead, and had a slightly different type signature on `Template` to use `ComponentStory`. 

```tsx
import {ComponentStory, ComponentMeta} from '@storybook/react'
import {set, cloneDeep} from 'lodash-es'
import React from 'react'
import {Foo} from './Foo'

export default {
  component: Foo,
  argTypes: {
    // Allow storybook user to modify question text
    epsilon: {
      control: 'text',
    },
    // Disable object editing
    bar: {
      control: false,
    },
  },
} as ComponentMeta<typeof Foo>

type FooPlusControls = (
  props: React.ComponentPropsWithoutRef<typeof Foo> & {epsilon: string},
) => JSX.Element

/**
 *  Merge our arbitrary Storybook control fields with the necessary
 *  args for the component, if it's changed
 **/
const Template: ComponentStory<FooPlusControls> = ({bar, epsilon}) => {
  if (epsilon !== bar.d.e) {
    const modifiedBar = cloneDeep<typeof bar>(bar)
    set(modifiedBar, `d.e`, epsilon)
    return <Foo bar={modifiedBar} />
  }
  return <Foo bar={bar} />
}

export const Default = Template.bind({})
Default.args = {
  bar: {
    c: 'cat',
    d: {
      e: 'elephant',
      f: 'frank',
    },
  },
  epsilon: 'elephant',
}



```

**Comment by ashnamuh** [comment] 2022-02-11 15:41
I've found workaround for this case!

Follow this comment

https://github.com/storybookjs/storybook/issues/12078#issuecomment-1036316861

**Comment by eliasm307** [comment] 2023-09-17 05:07
Hi guys, I have also been frustrated with this and I've made an addon to make things a bit easier https://www.npmjs.com/package/storybook-addon-deep-controls , feedback welcome

**Comment by matths** [comment] 2024-01-03 14:38
@eliasm307 I tried your extension together with these

```javascript
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
    '@storybook/addon-viewport',
    'storybook-addon-mock',
    '@storybook/addon-options',
    '@storybook/addon-controls',
    'storybook-addon-deep-controls',
    '@storybook/addon-svelte-csf',
  ],
```

I tried either with or without one or both of these '@storybook/addon-options',  '@storybook/addon-controls'.
But I noticed, that I am not able to control the Component inside a story directly. It doesn't update its state.
Might be related to the console info I see?
Omitted potentially unsafe URL args.
More info: https://storybook.js.org/docs/react/writing-stories/args#setting-args-through-the-url

Do you have an advice?

**Comment by eliasm307** [comment] 2024-01-03 19:08
Hi @matths thanks for the feedback, would you be able to move this to an issue on the package ie https://github.com/eliasm307/storybook-addon-deep-controls/issues?

Also when you create the issue would you be able to create a public repo with minimal reproduction of your issue then I can investigate? I dont use most of the addons you have there or svelte so a pre-setup repo with the issue would help me understand and debug your setup better
