### ISSUE TITLE
[Bug]: Storybook 7 is unable to get static assets from subdirectories

### ISSUE THREAD

**Issue by Radouch** [storybookjs/storybook#21556] opened 2023-03-10 17:31 UTC
### Describe the bug

There is configuration option for public assets at `.storybook/main.js`, see https://storybook.js.org/docs/7.0/vue/configure/images-and-assets

```javascript
// .storybook/main.js

export default {
  stories: [],
  addons: [],
  staticDirs: ['../public'],
};
```

This configuration does not work for deeper folders, e. g.

```javascript
staticDirs: ['../public/test'],
```

If e.g. `some.json` is referenced from a story, Storybook looks at `public/some.json`, but not at `public/test/some.json`

### System

```shell
Environment Info:

  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.63)
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.4 => 7.0.0-rc.1
    @storybook/addon-interactions: ^7.0.0-beta.4 => 7.0.0-rc.1
    @storybook/addon-links: ^7.0.0-beta.4 => 7.0.0-rc.1
    @storybook/blocks: ^7.0.0-beta.4 => 7.0.0-rc.1
    @storybook/testing-library: ^0.0.14-next.0 => 0.0.14-next.1
    @storybook/vue3: ^7.0.0-beta.4 => 7.0.0-rc.1
    @storybook/vue3-vite: ^7.0.0-beta.4 => 7.0.0-rc.1
```

**Comment by jonniebigodes** [comment] 2023-03-14 12:11
Hi, @Radouch thanks for reaching out to us with your question. We appreciate it. I've been looking at this issue, and it seems that probably there's something going on. Here are the steps I took to try and reproduce it.
- Spun up a new Vue 3 vite-based project.
- Ran `npx storybook@next init` to install Storybook’s release candidate.
- Instead of a JSON file, I copied over an image to a subdirectory inside `public` to try and emulate the issue.
- Created a simple component/story file to reference it.
- Pushed the [reproduction](https://github.com/jonniebigodes/testing-sb-rc-subdirs-vue3) to GitHub and hooked it up to Stackblitz [here](https://stackblitz.com/edit/stackblitz-webcontainer-api-starter-otvcdy?file=README.md)

If you check Stackblitz and the `With Image Starter story`, Storybook behaves as it should, and the image will not be rendered as per behavior Storybook ignores folders below public, only files located at that root level. But if you look at the `With path Image`, you'll see that I'm explicitly setting the full path and the image loads.
To further test this, I did the following:
- Pushed a new branch to the repo with [change](https://github.com/jonniebigodes/testing-sb-rc-subdirs-vue3/blob/update_subdirectory/.storybook/main.js#L19) to the staticDirs configuration to specifically pull the assets from the subdirectory.
- Checked in on StackBlitz, and now all the stories are loading the image in both scenarios, based on the configuration or by hard coding the subpath (if you want to check it out yourself, on Stackblitz, change from the `main` branch to the `update_subdirectory` branch, refresh and if you cycle through the stories you'll see that the image is loading for both scenarios).

With this, I would like for you to provide us with a reproduction so that it can be looked at and see what may be the issue on your end so that we can better triage this and hopefully help you sort it out and close this issue or continue to work on it until we have a suitable solution.


Looking forward to hearing from you.

Hope you have a great day.

Stay safe

**Comment by shilman** [comment] 2023-06-08 03:27
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

**Closed by shilman** 2023-06-08 03:27 UTC
Labels: question / support, core
