### ISSUE TITLE
[Bug]: storybook build not working due to error from `plugin-transform-block-scoping`: `Cannot set properties of undefined (setting 'kind')`

### ISSUE THREAD

**Issue by Sid-Turner-Ellis** [storybookjs/storybook#20382] opened 2022-12-22 12:24 UTC
### Describe the bug

After initiating a fresh React app, and then initiating storybook and running `yarn build-storybook` I get a build error:

```
ERR! => Failed to build the preview
ERR! Module build failed (from ./node_modules/babel-loader/lib/index.js):
ERR! TypeError: /Users/usrn/Documents/stbk-repro/src/stories/Button.stories.jsx: Cannot read properties of undefined (reading 'constantViolations')
```
I can reproduce this on 2 different computers.

### To Reproduce

```shell
1. `npx create-react-app my-app`
2. `npx storybook init`
3. `npm run build-storybook`
```

### System

```shell
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M2
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 107.0
    Safari: 16.0
  npmPackages:
    @storybook/addon-actions: ^6.5.15 => 6.5.15
    @storybook/addon-essentials: ^6.5.15 => 6.5.15
    @storybook/addon-interactions: ^6.5.15 => 6.5.15
    @storybook/addon-links: ^6.5.15 => 6.5.15
    @storybook/builder-webpack5: ^6.5.15 => 6.5.15
    @storybook/manager-webpack5: ^6.5.15 => 6.5.15
    @storybook/node-logger: ^6.5.15 => 6.5.15
    @storybook/preset-create-react-app: ^4.1.2 => 4.1.2
    @storybook/react: ^6.5.15 => 6.5.15
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

**Comment by mrszympek** [comment] 2022-12-22 14:45
Same problem here, when trying to integrate with next.js

**Comment by ch1qui** [comment] 2022-12-22 15:30
Same problem here, working on an independent package, using `esbuild` to bundle. CRA might be unrelated.

**Comment by cjones26** [comment] 2022-12-22 15:56
Same problem here, I don't believe this is related to CRA, but rather likely something either which is unlocked or upgraded in SB `dependencies`.

**Comment by cjones26** [comment] 2022-12-22 16:27
Note I've found that we can add the following to the `overrides` or `resolutions` field to our `package.json` file which will resolve the issue, for now:

```
"overrides": {
  "@babel/plugin-transform-block-scoping": "7.18.9"
}
```

**Comment by MirKml** [comment] 2022-12-22 18:27
Same here, even pure storybook for react install doesn't work either 😕.
```
$ npx storybook init --use-npm -t react -b webpack5
$ npm i -D webpack@latest
$ npm i react@17.0.2 react-dom@17.0.2
```
then `npm run storybook` and storybook throws error something like this
```
ModuleBuildError: Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: /.storybook/preview.js: Cannot set properties of undefined (setting 'kind')
```

Anyone cannot start with current stable - 6.5.15 - storybook for react component. It makes very bad reputation on newcomers. Even if problem is with 3rd party libs, it's still very bad for project as storybook. No daily QA builds failed?

**Comment by neogeek** [comment] 2022-12-22 19:37
I also ran into this issue, and with a clean copy of create-react-app (TypeScript) and storybook (7.0), I could replicate the issue by removing the `browserslist` from the package.json file. Adding it back resolved the issue.

I'm not sure why this is required, as it wasn't before, and I can't find any information about it in the storybook docs.

```json
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
```

**Comment by cjones26** [comment] 2022-12-22 19:46
@neogeek I'm guessing it's because Babel packages integrate with the `browserslist` package (https://babeljs.io/docs/en/babel-preset-env#browserslist-integration) and this seems to be a Babel issue as opposed to a Storybook issue.

Weirdly enough my error changes after adding `browserslist` from the one listed by the OP to the one listed by your and @MirKml :

```
Cannot set properties of undefined (setting 'kind')
```

**Comment by neogeek** [comment] 2022-12-22 19:50
Looks like they are already working on a solve https://github.com/storybookjs/storybook/pull/20383

**Comment by ndelangen** [comment] 2022-12-22 19:58
Yes, I am, but I'm dependent on the babel team here... I'm afraid..

**Comment by ndelangen** [comment] 2022-12-22 20:06
@neogeek thank you for that information, anything might help.
I posted all info I have here: https://github.com/babel/babel/issues/15300

Hopefully it can be quickly resolved by the babel team.

**Comment by ndelangen** [comment] 2022-12-22 20:07
Thank you for posting your work-around @cjones26 👏 I wish I could upvote it twice

**Comment by ndelangen** [comment] 2022-12-22 20:10
On the storybook side of things, I've tried clearing node_modules and regenerating lockfiles: https://github.com/storybookjs/storybook/pull/20386

And I've even tried that + upgrading babel-loader to latest:
https://github.com/storybookjs/storybook/pull/20383

Both run into the same issue I posted over on the babel repo.

**Comment by ndelangen** [comment] 2022-12-22 20:11
Looks like another issue is created on their repo here: https://github.com/babel/babel/issues/15302

**Comment by emiliosheinz** [comment] 2022-12-22 23:55
Unfortunately, the workaround proposed by @cjones26 isn't working here. Is there anything else that could be tried?

**Comment by emiliosheinz** [comment] 2022-12-22 23:58
> Unfortunately, the workaround proposed by @cjones26 isn't working here. Is there anything else that could be tried?

Using `resolutions` instead of `overrides` worked!

**Comment by cjones26** [comment] 2022-12-22 23:58
@emiliosheinz I know it's a silly question but have you done an `npm i` (or `yarn i`) after setting up the override / resolution?  I would also double check that when you do `npm ls @babel/plugin-transform-block-scoping` and ensure that the override is functioning properly.

**Comment by cjones26** [comment] 2022-12-22 23:58
@emiliosheinz Yep, if you're using yarn you need to use resolutions.

**Comment by emiliosheinz** [comment] 2022-12-22 23:59
@cjones26 didn't know it, my bad! Thank you for the help.

**Comment by neogeek** [comment] 2022-12-23 01:57
There was an updated version of https://www.npmjs.com/package/@babel/plugin-transform-block-scoping pushed. After removing the `browserslist` property from package.json and rebuilding the package-lock file, everything seemed to work as expected.

**Comment by MirKml** [comment] 2022-12-23 10:38
confirmed that babel fix the plugin (thx @neogeek for info) so
- new storybook install for react works
- upgrades to latest stable (6.5.15) work

I didn't test other workaround (resultions, overrides ...), but when new storybook patch will be published, you can remove workarounds and update into latest patch.

I think it can be closed, thank you guys for your work on it.

**Comment by shilman** [comment] 2022-12-23 12:11
Yay!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.14 containing PR #20386 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2022-12-23 12:11 UTC
Labels: bug, babel / webpack
