### ISSUE TITLE
[Documentation]: Importing a story to use it as part of another story will not work in CSF3

### ISSUE THREAD

**Issue by leofavre** [storybookjs/storybook#22278] opened 2023-04-26 20:50 UTC
### Describe the problem

https://storybook.js.org/docs/7.0/react/writing-stories/stories-for-multiple-components#reusing-subcomponent-stories

This page tells us to import the `Unchecked` story from `ListItem.stories` to reuse it as a component:

```tsx
export const OneItem: Story = {
  render: (args) => (
    <List {...args}>
      <Unchecked {...Unchecked.args} />
    </List>
  ),
};
```

But if `Unchecked` uses CSF3 format, it will be an object like `const Unchecked: Story = {}`, making it impossible to do `<Unchecked {...Unchecked.args} />`, even if `Unchecked` has a `render` method.

So, what is the correct way of writing stories for multiple components using CSF3?

**Comment by mogenshoj** [comment] 2023-04-27 06:15
I'm having the same issue.

I've found a workaround if the imported story has a `render` method, you can do this
```
export const OneItem: Story = {
  render: (args) => (
    <List {...args}>
      <Unchecked.render {...Unchecked.args} />
    </List>
  ),
};
```

It's not ideal though, and forces me to add the `render` method to simple stories. 
```
render: (props) => <Unchecked {...props} />,
```

But it does work. I am looking for a better solution though

**Comment by kylegach** [comment] 2023-05-03 22:41
Thanks for bringing this to our attention. Closing as a duplicate of #15954.

**Closed by kylegach** 2023-05-03 22:41 UTC
Labels: documentation, needs triage
