### ISSUE TITLE
[Bug]: Vite - react(ts) storybook broken

### ISSUE THREAD

**Issue by suprsidr** [storybookjs/storybook#23600] opened 2023-07-25 12:53 UTC
### Describe the bug

After bootstrapping a vite site with react or react-ts site demo page displays correctly.
Adding storybook is successful but after stopping and adding additional packages the project no longer works.
See steps to reproduce.
The stackblitz demo shows the project in the broken state.

### To Reproduce

https://stackblitz.com/edit/vitejs-vite-6venkb?file=package.json

Steps:

1. yarn create vite my-app --template react-ts // or plain react
2. cd my app
3. yarn
4. yarn dev // vite demo page works
5. ctrl+c
6. npx storybook@latest init // success yay! storybook works
7. ctrl+c
8. yarn add prettier // or any other package like  @mui
```
warning Pattern ["strip-ansi@^6.0.1"] is trying to unpack in the same destination "/home/name/.cache/yarn/v6/npm-strip-ansi-cjs-6.0.1-9e26c63d30f53443e9489495b2105d37b67a85d9-integrity/node_modules/strip-ansi-cjs" as pattern ["strip-ansi-cjs@npm:strip-ansi@^6.0.1"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["string-width@^4.1.0"] is trying to unpack in the same destination "/home/name/.cache/yarn/v6/npm-string-width-cjs-4.2.3-269c7117d27b05ad2e536830a8ec895ef9c6d010-integrity/node_modules/string-width-cjs" as pattern ["string-width-cjs@npm:string-width@^4.2.0"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["strip-ansi@^6.0.0"] is trying to unpack in the same destination "/home/name/.cache/yarn/v6/npm-strip-ansi-cjs-6.0.1-9e26c63d30f53443e9489495b2105d37b67a85d9-integrity/node_modules/strip-ansi-cjs" as pattern ["strip-ansi-cjs@npm:strip-ansi@^6.0.1"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["string-width@^4.2.0"] is trying to unpack in the same destination "/home/name/.cache/yarn/v6/npm-string-width-cjs-4.2.3-269c7117d27b05ad2e536830a8ec895ef9c6d010-integrity/node_modules/string-width-cjs" as pattern ["string-width-cjs@npm:string-width@^4.2.0"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["wrap-ansi@^7.0.0"] is trying to unpack in the same destination "/home/name/.cache/yarn/v6/npm-wrap-ansi-cjs-7.0.0-67e145cff510a6a6984bdf1152911d69d2eb9e43-integrity/node_modules/wrap-ansi-cjs" as pattern ["wrap-ansi-cjs@npm:wrap-ansi@^7.0.0"]. This could result in non-deterministic behavior, skipping.
```
9. yarn storybook
```
/home/name/my-app/node_modules/cli-table3/src/utils.js:1
const stringWidth = require('string-width');
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/name/my-app/node_modules/string-width/index.js from
/home/name/my-app/node_modules/cli-table3/src/utils.js not supported.
```

### System

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
  npmPackages:
    @storybook/addon-essentials: ^7.1.0 => 7.1.0 
    @storybook/addon-interactions: ^7.1.0 => 7.1.0 
    @storybook/addon-links: ^7.1.0 => 7.1.0 
    @storybook/addon-onboarding: ^1.0.8 => 1.0.8 
    @storybook/addon-styling: ^1.3.4 => 1.3.4 
    @storybook/blocks: ^7.1.0 => 7.1.0 
    @storybook/react: ^7.1.0 => 7.1.0 
    @storybook/react-vite: ^7.1.0 => 7.1.0 
    @storybook/testing-library: ^0.2.0 => 0.2.0
```

### Additional context

same results on windows using powershell

**Comment by suprsidr** [comment] 2023-07-25 13:08
tested using npm w/ no issue so seems related to yarn..

**Comment by valentinpalkovic** [comment] 2023-07-25 13:11
Duplicate of https://github.com/storybookjs/storybook/issues/22431. Closing.

Please take a look at https://github.com/storybookjs/storybook/issues/22431#issuecomment-1630086092 for the proposed workaround and an explanation of the issue

**Closed by valentinpalkovic** 2023-07-25 13:11 UTC
Labels: bug, needs triage
