### ISSUE TITLE
Storybook vue type checking not working

### ISSUE THREAD

**Issue by fallemand** [storybookjs/storybook#14987] opened 2021-05-19 15:15 UTC
**Describe the bug**
After enabling type check in vue, I would expect to see the errors when building, but nothing happens.

**To Reproduce**
1- Add typescript check:
```
// main.ts
module.exports = {
  ...,
  typescript: {
    check: true,
  },
}
```
2- Add any type error in a `vue` file
```
const test: string = 3;
```
 
3- Run `npm run storybook`
It doesn't complain.

**System**
```
  System:
    OS: macOS 11.2.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    npm: 7.12.1 - ~/.nvm/versions/node/v14.15.1/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 88.0
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-a11y: ^6.2.7 => 6.2.9 
    @storybook/addon-essentials: ^6.2.7 => 6.2.9 
    @storybook/vue: 6.2.7 => 6.2.9 
```

**Comment by shilman** [comment] 2021-05-21 16:28
Is that type error in a `.vue` file or a `.ts`/`.tsx` file?

**Comment by fallemand** [comment] 2021-05-21 16:32
@shilman On a `vue` file.

**Comment by shilman** [comment] 2021-05-21 16:33
I think the built-in type checking only works on .ts/.tsx files (not entirely sure)

**Comment by fallemand** [comment] 2021-05-21 16:38
@shilman Adding the issue on a `ts` file, doesn't produce the error either. I don't see `fork-ts-checker-webpack-plugin` being executed.

**Comment by pocka** [comment] 2021-05-29 08:18
Investigated, then found the root cause. However, I'm not sure which approach should I take to fix it.

## The problem

`@storybook/vue` (Vue2) ignores `fork-ts-checker-webpack-plugin` as stated [here](https://storybook.js.org/docs/vue/configure/typescript#default-configuration). However, [vue preset always set `transpileOnly: true`](https://github.com/storybookjs/storybook/blob/abc74c3f93d48734a7b759e2bec10d234fa81b7e/app/vue/src/server/framework-preset-vue.ts#L18) so neither `ts-loader`'s type-checking process nor `fork-ts-checker-webpack-plugin` kicks in.

## Possible fixes

### A) Change `transpileOnly` based on `typescript.check`

Read `typescriptOptions.check` in [here](https://github.com/storybookjs/storybook/blob/abc74c3f93d48734a7b759e2bec10d234fa81b7e/app/vue/src/server/framework-preset-vue.ts) then set `transpileOnly` based on that value. IMO this is the most straightforward approach, but I'm not sure it's okay to do below to access `typescriptOptions` in a framework preset file (`framework-preset-vue.ts`).

```ts
  const typescriptOptions = await presets.apply<TypescriptConfig>('typescript', {} as any);
```

### B) Use the base `fork-ts-checker-webpack-plugin` like other frameworks

Remove `vue` from [this](https://github.com/storybookjs/storybook/blob/abc74c3f93d48734a7b759e2bec10d234fa81b7e/lib/builder-webpack4/src/preview/useBaseTsSupport.ts#L8). In addition to that, we should add `extensions.vue: true` on [here](https://github.com/storybookjs/storybook/blob/abc74c3f93d48734a7b759e2bec10d234fa81b7e/lib/builder-webpack4/src/preview/iframe-webpack.config.ts#L117). (also for webpack5 builder)

This leaks framework-specific configuration to builder `iframe-webpack.config.ts`. Also, we'll need to update docs.

**Comment by shilman** [comment] 2021-05-29 10:35
I can't remember the full rationale for why Vue needed its own Typescript setup, but I'm pretty sure that it does. I think @graup implemented this, so perhaps he can chime in.

@pocka do you think you can make a PR with option A? It sounds reasonable to me!

**Comment by graup** [comment] 2021-05-29 11:20
I don't remember 100%, I believe we had some offline discussions involving @mrmckeb and [this PR](https://github.com/storybookjs/presets/pull/122), after which we concluded that Vue just works better with ts-loader.

Option A sounds good to me too. I'm not sure why we didn't include that back when we added zero-config ts. I believe at that time it was just assumed that most people don't want type-checking in their storybook builds due to the performance overhead it introduces.

**Comment by shilman** [comment] 2021-05-30 05:14
Yay!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-beta.5 containing PR #15089 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2021-05-30 05:14 UTC
Labels: app: vue, bug, typescript
