### ISSUE TITLE
Importing module which does not have a ɵmod property

### ISSUE THREAD

**Issue by IsaacSomething** [storybookjs/storybook#13628] opened 2021-01-13 08:58 UTC
**Describe the bug**
Updating angular modules returns the error

`Unhandled Promise rejection: Importing MarkdownModule which does not have a ɵmod property ; Zone: <root> ; Task: Promise.then ; Value: Error: Importing MarkdownModule which does not have a ɵmod property`

The `MarkdownModule` is on the latest version `ngx-markdown: "^11.0.1",`

I also get this issue with `@angular/flex-layout`,  `@ngneat/content-loader` and `NgApexchartsModule` both at the latest versions. This error prevents the story from running and there is just a blank page. I initially was working on a angular 10 project but after upgrading to angular 11 the issue persists

**To Reproduce**
Update to latest versions of either `ngx-markdown`, `@angular/flex-layout`, `@ngneat/content-loader` with an angular storybook project

**Expected behavior**
No error

**Screenshots**
![error](https://user-images.githubusercontent.com/25283027/104428610-59c89780-558d-11eb-9d66-09facd87e875.PNG)

**System**
![version](https://user-images.githubusercontent.com/25283027/104428986-c9d71d80-558d-11eb-9b59-0bc2b79ffcbe.PNG)

**Comment by shilman** [comment] 2021-02-21 09:43
closing as dupe to #13958

**Closed by shilman** 2021-02-21 09:43 UTC
Labels: app: angular, duplicate, question / support

**Comment by manohara-kp** [comment] 2023-12-27 12:36
we migrating from angular 15 to angular 16.

there is 3rd party library we are using i.e ngx-tribute it's compactable with Angular 2+ but am facing below error when i launch the tool. 

NgxTributeModule does not have a module def (ɵmod property),

**Comment by sdspl-vanmalideshani** [comment] 2024-04-17 09:10
I am  migrating from angular 15 to angular 16.
i did not  use any where **ScrollingModule**, but i got the error, someone please help me to fix the error


**ScrollingModule** does not have a module **def (ɵmod property)**

**Comment by valentinpalkovic** [comment] 2024-05-13 06:55
@sdspl-vanmalideshani Can you provide a simple reproduction? http://storybook.new. And also please open a new issue, if it is still relevant.
