### ISSUE TITLE
5.1.9 Reproduce  #7049 issue; Warning: Received `false` for a non-boolean attribute `loading`.

### ISSUE THREAD

**Issue by cxwwa** [storybookjs/storybook#7219] opened 2019-06-28 01:25 UTC
**Describe the bug**
click sidebar get more menu icon button; at the console: Warning: Received `false` for a non-boolean attribute `loading`.

**To Reproduce**
1. npm i @storybook/react @types/storybook__react @storybook/addon-actions
2. Then follow the doc from [https://storybook.js.org/docs/configurations/typescript-config/](https://storybook.js.org/docs/configurations/typescript-config/)
3. run start-storybook
4. click sidebar more menu icon button
5. See error

**Expected behavior**
show stories and no error

**Screenshots**
![image](https://user-images.githubusercontent.com/8764223/60310657-8191e380-9986-11e9-8818-5624586b1a23.png)

**System:**
 - OS: [MacOS]
 - Device: [Macbook Pro 2016]
 - Browser: [Chrome]
 - Framework: [React, Typescript]
 - Addons: [action]
 - Version: [5.1.9]

**Comment by claudio-moya** [comment] 2019-07-01 05:01
Same here, also using Macbook, Chrome and React

**Comment by djetcgw** [comment] 2019-07-04 14:25
Same here with Windows 10 and Chrome.

**Comment by ckwong90** [comment] 2019-07-14 22:23
Why is this closed. I'm still getting this bug on v 5.1.9.

**Comment by shilman** [comment] 2019-07-14 23:07
@ckwong90 it's not closed?

**Comment by Itrulia** [comment] 2019-07-16 07:53
Hes referencing #7049

**Comment by YoussefTaghlabi** [comment] 2019-07-22 16:32
I'm still getting the same error in 5.1.9

**Comment by ndelangen** [comment] 2019-07-23 11:30
I'll take a look.

**Comment by lonyele** [comment] 2019-07-23 12:01
@ndelangen Ironically, I couldn't reproduce this issue when this one came up. But somehow I could reproduce now. It looks like I could fix this one maybe. Can I take it? I'll make a PR in a few hours(I need to go home first haha)

**Comment by ndelangen** [comment] 2019-07-23 12:03
It's yours! 🤝

**Comment by shilman** [comment] 2019-07-23 12:05
@ndelangen what do you mean?

**Comment by ndelangen** [comment] 2019-07-23 12:45
My question was:
Is what's on master, equal to what's on npm, right now?

**Comment by shilman** [comment] 2019-07-24 03:36
Yes AFAIK with the exception of a handful of documentation fixes. Also there are some `patch` PRs on `next` that haven't been applied back to `master` yet. Why do you ask?

**Comment by shilman** [comment] 2019-07-26 11:59
Zoinks!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.10 containing PR #7548 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2019-07-26 11:59 UTC
Labels: bug, ui

**Comment by Silverium** [comment] 2019-08-14 07:15
In my case, it was the cookies. Removed all cookies and all cached storage, and automagically Addons tab shows again!
