### ISSUE TITLE
Module '"@storybook/vue3"' has no exported member 'app'.

### ISSUE THREAD

**Issue by gygoo** [storybookjs/storybook#19295] opened 2022-09-29 15:48 UTC
**Describe the bug**
Hi!

in file: .storybook/preview.js

`import { app } from '@storybook/vue3'
`

The above line reports an error: 

_Module '"@storybook/vue3"' has no exported member 'app'._

_The requested module '/node_modules/.vite-storybook/deps/@storybook_vue3.js?v=1e8ee5ed' does not provide an export named 'app'_

Is the information in the documentation still valid?
[https://storybook.js.org/docs/7.0/vue/get-started/setup](https://storybook.js.org/docs/7.0/vue/get-started/setup)
--> Component context

---
@storybook/cli v7.0.0-alpha.34

**Comment by enkot** [comment] 2022-10-09 13:44
@gygoo I guess the 7.0 has a different API, so docs should be changed. This works for me:

```ts
// preview.ts
import { setup } from '@storybook/vue3-vite' // or '@storybook/vue3-webpack'

const router = createRouter({
  history: createWebHashHistory(),
  routes: [],
})

setup((app) => {
  app.use(router)
})

```

```ts
// main.ts
const { mergeConfig } = require('vite')

exports.default = {
  stories: ['../src/**/*.stories.@(js|jsx|ts|tsx)'],
  framework: '@storybook/vue3-vite',
  addons: ['@storybook/addon-essentials'],
  core: {
    builder: '@storybook/builder-vite', // or '@storybook/builder-webpack5'
    disableTelemetry: true,
  },
  async viteFinal(config) { // or webpackFinal(config)
    return mergeConfig(config, {
      plugins: []
    })
  }
}


```

**Comment by stefanlivens** [comment] 2023-01-09 09:54
I can confirm, this time for "@storybook/vue3-webpack5": "^7.0.0-beta.21",

I only had to change my preview.js to this:

from:
app.use(i18n);

to:
setup((app) => {
  app.use(i18n)
})

with `setup` coming from `import { setup } from '@storybook/vue3'`

**Comment by matthew-dean** [comment] 2023-03-07 22:31
This still has an issue. I was trying to use PrimeVue, and got a critical error which closed Storybook:
```
TypeError: Cannot set properties of undefined (setting 'STORYBOOK_ENV')
```
This failed when trying with `app.use(PrimeVue)` or `setup(app => app.use(PrimeVue))`

**Comment by shilman** [comment] 2023-03-07 23:50
@matthew-dean Do you have a reproduction? The second approach (`setup`) should work in 7.0

**Comment by shilman** [comment] 2023-03-08 09:36
@jonniebigodes these Vue3 snippets need updating

<img width="942" alt="image" src="https://user-images.githubusercontent.com/488689/223676955-ed866047-bff5-4531-a541-8cda894f7677.png">

**Comment by jonniebigodes** [comment] 2023-03-20 20:07
Closing this for now, as the documentation is already updated to address the new API. Let me know if there's anything that requires additional changes to the documentation and I'll gladly re-open this issue and take it from there.

**Closed by jonniebigodes** 2023-03-20 20:07 UTC
Labels: documentation, vue3

**Comment by stephenhebert** [comment] 2023-03-29 19:00
I'm not finding the new API in the docs.  Would someone mind sharing a link?

**Comment by JReinhold** [comment] 2023-03-29 20:13
It's here: https://storybook.js.org/docs/7.0/vue/get-started/setup#configure-storybook-for-your-stack

Expand the "Component context" section and pick one of the two Vue 3 snippets.

**Comment by Horlamedhey** [comment] 2023-05-18 08:46
Importing "setup" causes error
`_a.decline not found`

**Comment by phily245** [comment] 2023-06-15 10:36
> Importing "setup" causes error `_a.decline not found`

Same

**Comment by mibsbalsante** [comment] 2023-07-26 05:20
> Importing "setup" causes error `_a.decline not found`

Just a little something I had to do to make it work. It's a Nuxt 3 + Vuetify 3 project, using `storybook-addon-nuxt`.

`.storybook/preview-head.html`
```html
<script>
  // temporary fix for @storybook/vue3 module.hot.decline (hmr webpack)
  (function () {
    Object.defineProperty(window, 'module', {
      get: () => ({ hot: { decline: () => {} } }),
      set: () => {},
      configurable: true,
    });
  })();
</script>
```

Hope it helps. @Horlamedhey @phily245

**Comment by VegasChickiChicki** [comment] 2023-07-26 23:06
> > Importing "setup" causes error `_a.decline not found`
> 
> Just a little something I had to do to make it work. It's a Nuxt 3 + Vuetify 3 project, using `storybook-addon-nuxt`.
> 
> `.storybook/preview-head.html`
> 
> ```
> <script>
>   // temporary fix for @storybook/vue3 module.hot.decline (hmr webpack)
>   (function () {
>     Object.defineProperty(window, 'module', {
>       get: () => ({ hot: { decline: () => {} } }),
>       set: () => {},
>       configurable: true,
>     });
>   })();
> </script>
> ```
> 
> Hope it helps. @Horlamedhey @phily245

You're just brilliant! This helped solve my problem! Thank you very much!
