### ISSUE TITLE
[Bug]: invariant expected app router to be mounted

### ISSUE THREAD

**Issue by dfd1123** [storybookjs/storybook#24722] opened 2023-11-06 01:42 UTC
### Describe the bug

The component that imports next/navigation and uses useRouter generates an error saying 'Error: invariant expected app router to be mounted'. I am using storybook version 7.5.2 and next14 version. And I also set nextjs: { appDirectory: true } in the parameters.

However, the error does not go away and continues to occur. Did I possibly do something wrong??

<img width="905" alt="스크린샷 2023-11-06 오전 10 38 18" src="https://github.com/storybookjs/storybook/assets/42544793/58e07aa4-2761-4015-bf20-1c9d92939709">

<img width="816" alt="스크린샷 2023-11-06 오전 10 39 12" src="https://github.com/storybookjs/storybook/assets/42544793/555fcb77-790d-499f-97be-406f12f6e599">

<img width="978" alt="스크린샷 2023-11-06 오전 10 34 26" src="https://github.com/storybookjs/storybook/assets/42544793/1674a486-d310-4801-8f69-acf6bf42b768">

**Comment by felixmagnus** [comment] 2023-11-06 09:55
We're also facing this issue using storybook `7.5.2` and next `13.5.6`.

We notice this behavior since the peer dependency `@babel/core` was upgraded from `7.23.0` (working) to `7.23.2` (not working).

**Comment by whateverneveranywhere** [comment] 2023-11-11 14:40
having this issue with next `^14.0.1`. but unlike @felixmagnus, switching to ^7.23.2 for babel/core didn't help me solve the issue. 
![image](https://github.com/storybookjs/storybook/assets/29921792/41f49020-8139-4fe5-86f9-7eac668895d5)

**Comment by valentinpalkovic** [comment] 2023-11-11 15:14
Can someone provide a reproduction?

**Comment by whateverneveranywhere** [comment] 2023-11-11 15:44
> Can someone provide a reproduction?

Found the issue, it was on my side, so in my case, while on  `"next": "^14.0.1",`:
after adding `appDirectory: true` to the parameters, it worked as expected.
 
`const meta = {
	title: 'Auth/Register',
	component: Register,
	decorators: [
		(Story) => (
			<StorybookLayout>
				<Story />
			</StorybookLayout>
		),
	],
	parameters: {
		layout: 'centered',
		nextjs: {
			appDirectory: true,
		},
	},
	tags: ['autodocs'],
} satisfies Meta<typeof Register>;`

**Comment by valentinpalkovic** [comment] 2023-11-11 15:57
@dfd1123 Can you remove the render functions and the template? For these simple argument mapping it is not necessary. Storybook does this under the hood. Second, do you have some custom add-ons or decorators in place?

**Comment by mecaota** [comment] 2023-12-11 08:05
@valentinpalkovic 

I'll put a reproduction below.I'm also running into the same issue.

https://github.com/mecaota/bugged-nextjs/tree/7122c366fa9bfb465a6b8114875d258b48cb66a0

**Comment by isBatak** [comment] 2024-01-16 14:45
Is there any workarounds for this issue?

**Comment by MiroslavPetrik** [comment] 2024-01-23 16:02
> > Can someone provide a reproduction?
> 
> Found the issue, it was on my side, so in my case, while on `"next": "^14.0.1",`: after adding `appDirectory: true` to the parameters, it worked as expected.
> 
> `const meta = { title: 'Auth/Register', component: Register, decorators: [ (Story) => ( <StorybookLayout> <Story /> </StorybookLayout> ), ], parameters: { layout: 'centered', nextjs: { appDirectory: true, }, }, tags: ['autodocs'], } satisfies Meta<typeof Register>;`

I approve this message.

**Comment by MichaelCasaDev** [comment] 2024-01-24 09:21
Any updates on that? I've also tried using the `nextjs: { appDirectory: true, }` parameter without any success... I'm using the latest nextjs version (14.1.0) and latest storybook (7.6.10)

**Comment by MichaelCasaDev** [comment] 2024-01-24 15:40
For everyone having this issue, I've found a workaround using the `next-router-mock` package!

```jsx
import { AppRouterContext } from "next/dist/shared/lib/app-router-context.shared-runtime";
import mockRouter from "next-router-mock";

const withRouter: Decorator = (Story, context) => (
  <AppRouterContext.Provider value={mockRouter as any}>
    <Story />
  </AppRouterContext.Provider>
);
```

**Comment by isBatak** [comment] 2024-01-24 19:24
@MichaelCasaDev thx for the workaround. Great idea!
I didn't even need the `next-router-mock` package. Also, `next-router-mock` only supports [pages router](https://github.com/scottrippey/next-router-mock/issues/67), which means that `AppRouterInstance` is different form `mockRouter` instance and it feels wrong to pass it to the `AppRouterContext`,

```ts
import {
	AppRouterContext,
	type AppRouterInstance,
} from 'next/dist/shared/lib/app-router-context.shared-runtime';

const meta = {
	decorators: [
		(Story) => (
			<AppRouterContext.Provider value={{} as AppRouterInstance}>
				<Story />
			</AppRouterContext.Provider>
		),
	],
};
```

**Comment by valentinpalkovic** [comment] 2024-02-01 14:12
@mecaota Your reproduction does not set up the `parameters.nextjs.appDirectory: true`. After setting up the parameter correctly, it works. Please follow the documentation here: https://github.com/storybookjs/storybook/blob/main/code/frameworks/nextjs/README.md#nextjs-navigation

This documentation will also be available soon on the official Storybook docs.

**Comment by valentinpalkovic** [comment] 2024-02-01 14:20
@isBatak Your reproduction doesn't bootstrap. But I can see that you are not setting `parameters.nextjs.appDirectory: true`. That's the reason why it is not working.

@isBatak, @MichaelCasaDev
The `AppRouterContext.Provider` doesn't have to be added manually. Storybook does that for you in the case where `parameters.nextjs.appDirectory: true` is set as documented here: https://github.com/storybookjs/storybook/blob/main/code/frameworks/nextjs/README.md#nextjs-navigation

@MichaelCasaDev You are mentioning that `parameters.nextjs.appDirectory: true` doesn't help. Please provide a reproduction in that case.

I am closing this issue for now because it seems that the required parameter is not set accordingly. If `parameters.nextjs.appDirectory: true` is set as documented, and it is still not working; please let me know. In the meantime, I will close this issue because it was about misconfiguration.

**Closed by valentinpalkovic** 2024-02-01 14:20 UTC
Labels: bug, nextjs, sev:S2

**Comment by isBatak** [comment] 2024-02-02 16:00
I can't find any documentation but I can prove that `pages` folder actually have access to `AppRouterContext`, check it here https://stackblitz.com/edit/nextjs-3vyr8e?file=app%2Fpage.tsx,pages%2Ftest.tsx

I would say it's there for easier migration form `pages` to `app` folder.
If you can mimic that in storybook it would fix the issue.

To clarify:
- if `parameters.nextjs.appDirectory` is not defined or set to `false` provide both `RouterContext` and `AppRouterContext`
- if `parameters.nextjs.appDirectory` is set to true provide just `AppRouterContext`

I don't see why would this be a problem.

**Comment by sinashahoveisi** [comment] 2024-02-27 08:45
> @MichaelCasaDev thx for the workaround. Great idea! I didn't even need the `next-router-mock` package. Also, `next-router-mock` only supports [pages router](https://github.com/scottrippey/next-router-mock/issues/67), which means that `AppRouterInstance` is different form `mockRouter` instance and it feels wrong to pass it to the `AppRouterContext`,
> 
> ```ts
> import {
> 	AppRouterContext,
> 	type AppRouterInstance,
> } from 'next/dist/shared/lib/app-router-context.shared-runtime';
> 
> const meta = {
> 	decorators: [
> 		(Story) => (
> 			<AppRouterContext.Provider value={{} as AppRouterInstance}>
> 				<Story />
> 			</AppRouterContext.Provider>
> 		),
> 	],
> };
> ```
@isBatak 
This solution worked for me, thanks for your solution

**Comment by weiying-chen** [comment] 2024-05-01 01:37
`parameters.nextjs.appDirectory` set to `true` didn't  fix `Error: invariant expected app router to be mounted`.

@MichaelCasaDev code did:

```
import {
	AppRouterContext,
	type AppRouterInstance,
} from 'next/dist/shared/lib/app-router-context.shared-runtime';

const meta = {
	decorators: [
		(Story) => (
			<AppRouterContext.Provider value={{} as AppRouterInstance}>
				<Story />
			</AppRouterContext.Provider>
		),
	],
};
```

**Comment by alvis** [comment] 2024-05-02 08:12
> `parameters.nextjs.appDirectory` set to `true` didn't fix `Error: invariant expected app router to be mounted`.
> 
> The code of @MichaelCasaDev and @isBatak did:
> 
> ```
> import {
> 	AppRouterContext,
> 	type AppRouterInstance,
> } from 'next/dist/shared/lib/app-router-context.shared-runtime';
> 
> const meta = {
> 	decorators: [
> 		(Story) => (
> 			<AppRouterContext.Provider value={{} as AppRouterInstance}>
> 				<Story />
> 			</AppRouterContext.Provider>
> 		),
> 	],
> };
> ```

same here, but it worked before. Seems like some version change break the thing under some circumstances

**Comment by dfd1123** [comment] 2024-05-03 03:53
> @MichaelCasaDev해결 방법을 알려주셔서 감사합니다. 좋은 생각이에요! 패키지도 필요 없었어요 `next-router-mock`. 또한 [페이지 라우터](https://github.com/scottrippey/next-router-mock/issues/67)`next-router-mock` 만 지원합니다 . 이는 다른 형식의 인스턴스이고 이를 에 전달하는 것이 잘못된 느낌을 준다는 것을 의미합니다 .[](https://github.com/scottrippey/next-router-mock/issues/67)`AppRouterInstance``mockRouter``AppRouterContext`
> 
> ```ts
> import {
> 	AppRouterContext,
> 	type AppRouterInstance,
> } from 'next/dist/shared/lib/app-router-context.shared-runtime';
> 
> const meta = {
> 	decorators: [
> 		(Story) => (
> 			<AppRouterContext.Provider value={{} as AppRouterInstance}>
> 				<Story />
> 			</AppRouterContext.Provider>
> 		),
> 	],
> };
> ```

That doesn't work, idiot. How on earth do you guys develop something that is worse than what I made with my feet? I'll just write it myself, you idiots.

**Comment by CarlosLeonCode** [comment] 2024-09-18 14:44
> > @MichaelCasaDev thx for the workaround. Great idea! I didn't even need the `next-router-mock` package. Also, `next-router-mock` only supports [pages router](https://github.com/scottrippey/next-router-mock/issues/67), which means that `AppRouterInstance` is different form `mockRouter` instance and it feels wrong to pass it to the `AppRouterContext`,
> > ```ts
> > import {
> > 	AppRouterContext,
> > 	type AppRouterInstance,
> > } from 'next/dist/shared/lib/app-router-context.shared-runtime';
> > 
> > const meta = {
> > 	decorators: [
> > 		(Story) => (
> > 			<AppRouterContext.Provider value={{} as AppRouterInstance}>
> > 				<Story />
> > 			</AppRouterContext.Provider>
> > 		),
> > 	],
> > };
> > ```
> 
> @isBatak This solution worked for me, thanks for your solution

thnks, that works for me.
