### ISSUE TITLE
Expo + Storybook - Navigation links don't work on web

### ISSUE THREAD

**Issue by chrisgeorge87** [storybookjs/storybook#7723] opened 2019-08-08 15:08 UTC
**Describe the bug**
The Storybook page in the web browser isn't updating when you click different stories. It always shows the first (in my case, the Welcome story that is included by default). It does update on Expo in the connected iOS simulator.  I'm using 5.2.0-beta.25 as with 5.1.x, the preview in the Navigator tab on iOS wouldn't update from selecting stories.

**To Reproduce**
Steps to reproduce the behaviour:
1. create an expo init project
2. follow steps from https://github.com/storybookjs/storybook/tree/next/app/react-native (export conditionally in App.js as the guide suggests)
3. run yarn storybook in one terminal tab and yarn ios in another (use iOS simulator from xcode)
4. try changing story in the web storybook - it does not update the story shown in the web page, only the one in the simulator

**Expected behavior**
The story shown should be the correct one in the web browser

**Screenshots**
![image](https://user-images.githubusercontent.com/43953856/62714354-4c9d9580-b9f6-11e9-9c86-ad498ef4c380.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
`[BABEL] Note: The code generator has deoptimised the styling of /Users/c.george/.npm/_npx/90927/lib/node_modules/@storybook/cli/node_modules/lodash/lodash.js as it exceeds the max of 500KB.

Environment Info:

  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 68.0.1
    Safari: 12.1.2
  npmPackages:
    @storybook/addon-actions: ^5.2.0-beta.25 => 5.2.0-beta.25 
    @storybook/addon-links: ^5.2.0-beta.25 => 5.2.0-beta.25 
    @storybook/addons: ^5.2.0-beta.25 => 5.2.0-beta.25 
    @storybook/react-native: ^5.2.0-beta.25 => 5.2.0-beta.25 
    @storybook/react-native-server: ^5.2.0-beta.25 => 5.2.0-beta.25 `

**Additional context**

**Comment by chrisgeorge87** [comment] 2019-08-08 15:34
Adding to the above, I've since found that the 'Welcome' page content it is showing all the time is from PreviewHelp.js from react-native-server, rather than the Welcome component and story that is created when you first add storybook to a project, just for added info.

**Comment by Gongreg** [comment] 2019-11-03 14:28
Hi.

This is not a bug but intended behaviour, there is no content to show in the web (it is React Native app that you are playing around, not the web).

Closing the issue.

**Closed by Gongreg** 2019-11-03 14:28 UTC
Labels: app: react-native, app: react-native-server, bug, high priority, todo
