### ISSUE TITLE
Webpack - Module not found Error Can't resolve '.storybook/preview.js-generated-config'

### ISSUE THREAD

**Issue by rtturner** [storybookjs/storybook#19927] opened 2022-11-22 17:57 UTC
### Describe the bug

Earlier today I started having issues trying to build storybook. Receiving an error complaining about not being able to resolve `.storybook/preview.js-generated-config-entry.js`. I assumed it was something in our codebase but trying many older commits that were working is still failing.

I noticed that the latest commits in storybook were failing this check: [ci/circleci: build-sandboxes](https://circleci.com/gh/storybookjs/storybook/444618)

The error message within that check is very similar to what I am seeing.

```
Field 'browser' doesn't contain a valid alias configuration
```

Curious if this is a storybook issue

### System

```shell
Environment Info:

  System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.12.1 - ~/.volta/tools/image/node/18.12.1/bin/node
    Yarn: 1.22.17 - ~/.volta/bin/yarn
    npm: 8.11.0 - ~/<redacted>/gdl_js/node_modules/.bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: 107.0
    Safari: 15.4
  npmPackages:
    @storybook/addon-a11y: 6.4.19 => 6.4.19 
    @storybook/addon-actions: 6.4.19 => 6.4.19 
    @storybook/addon-backgrounds: 6.4.19 => 6.4.19 
    @storybook/addon-console: 1.2.3 => 1.2.3 
    @storybook/addon-controls: 6.4.19 => 6.4.19 
    @storybook/addon-docs: 6.4.19 => 6.4.19 
    @storybook/addon-links: 6.4.19 => 6.4.19 
    @storybook/addon-measure: 6.4.19 => 6.4.19 
    @storybook/addon-outline: 6.4.19 => 6.4.19 
    @storybook/addon-storysource: 6.4.19 => 6.4.19 
    @storybook/addon-toolbars: 6.4.19 => 6.4.19 
    @storybook/addon-viewport: 6.4.19 => 6.4.19 
    @storybook/addons: 6.4.19 => 6.4.19 
    @storybook/builder-webpack5: 6.4.19 => 6.4.19 
    @storybook/manager-webpack5: 6.4.19 => 6.4.19 
    @storybook/react: 6.4.19 => 6.4.19
```

**Comment by yannbf** [comment] 2022-11-22 18:19
Hey @rtturner thanks for opening this issue and investigating!

A few hours ago, there was a release of [enhanced-resolve](https://www.npmjs.com/package/enhanced-resolve) v5.11.0, which ended up breaking Storybooks that use Webpack. You might be experiencing this issue if you:

- Installed a fresh Storybook, regardless of version (could be 6 or 7)
- Do not use package lock files
- Deleted your package lock files and ran install

We notified the maintainers here, please upvote: https://github.com/webpack/enhanced-resolve/issues/362

In the meantime, the workaround is to pin the version of `enhanced-resolve` to its previous working version in your package.json:

**npm (if you're using npm 8 or higher)**
```js
{
  "overrides": {
    "enhanced-resolve": "5.10.0"
  }
}
```

**Yarn**
```js
{
  "resolutions": {
    "enhanced-resolve": "5.10.0"
  }
}
```

**pnpm**
```js
{
  "pnpm": {
    "overrides": {
      "enhanced-resolve": "5.10.0"
    }
  }
}
```

**Comment by tyhurson** [comment] 2022-11-22 20:58
Adding the `enhanced-resolve` override in `package.json` on a fresh project doesn't work for me. Still getting the webpack error.

For reference, I am using `@storybook/react` version `6.5.13`.

**Comment by pm0u** [comment] 2022-11-22 23:21
I just did a fresh install of storybook and I'm running into an issue implementing this fix as there is also a dependency on webpack4 coming from "@storybook/core-server@6.5.13" that relies on "enhanced-resolve@^4.5.0" so setting a global resolution seems to break that dependency

**Comment by pm0u** [comment] 2022-11-22 23:26
repro:
```
mkdir test
cd test
yarn add react react-dom @types/react typescript
npx sb init
```

Check the lockfile, there is enhanced-resolve@^4.5.0 and enhanced-resolve@^5.10.0 called out

**Comment by pm0u** [comment] 2022-11-22 23:56
the following resolved the above error for me:

```json
  "resolutions": {
    "webpack@5/enhanced-resolve": "5.10.0"
  }
```

**Comment by CharowDEV** [comment] 2022-11-23 08:50
Same issue after fresh install. A workaround if the temporary solutions above not work is to comment out 

```
 "core": {
    "builder": "@storybook/builder-webpack5"
  },
```

In `.storybook/main.js`

**Comment by dungmidside** [comment] 2022-11-23 16:07
Please, please publish a new version of storybook with fixed version of broken package 😢

**Comment by kylegach** [comment] 2022-11-23 20:06
This issue has been addressed by a new release of `enhanced-resolved`: https://github.com/webpack/enhanced-resolve/pull/364.

We've confirmed that it works in a few sample projects, but please let us know if you continue to experience problems.

**Closed by kylegach** 2022-11-23 20:06 UTC
Labels: bug, compatibility with other tools, babel / webpack, has workaround

**Comment by DavidLeonard77** [comment] 2022-11-23 20:48
New release fixes the issue. 😄 ❤️

**Comment by wojtekxtx** [comment] 2022-11-29 11:21
@DavidLeonard77 This is what I thought it would be. Im starting looking for an alternative for sorybook. If none found, we (our team) will write our own one.

**Comment by ndelangen** [comment] 2022-11-29 23:06
First: This issue (yes urgent!) is actually resolved! It's not just closed "without further ado" that's simply not true.

---

Hey @wojtekxtx I'm sad to hear you feel this way. As a storybook maintainer it's never a great moment when a user voices their displeasure. But it happens, I understand. You feel somehow that this is our fault, that we should do better.

We try, but you know, sometimes building a project such as storybook, standing on the shoulders of giants, it's a blessing and a curse. We would not be where we are today without those giants! But these giants are moving, and new giants get created to stand upon.

I'm talking about webpack, which is exactly what this issue is about. Users want to use webpack, we support it; we have to.
It's a tool with 24+ million weekly installs.
We found out storybook was broken within 2 hours of the webpack team releasing a minor version of a package they depend on. This minor version change broke storybook in a unexpected way. The storybook team had no way of knowing this change was coming, we didn't choose to update to `enhanced-resolve`, in fact because it's a transitive dependency, we couldn't even fix it on our end, it was impossible.

Within 1 hour after discovery we had a PR up fixing the issue at the origin, we had ping'ed the author of the PR breaking and the package maintainer on multiple platforms.

The storybook team works hard to keep up with the ever changing landscape of bundles (new versions get released, new bundles come unto the scene) new UI frameworks, breaking changes in existing ones (hello react 18!). We try to support it all. It's a lot and complex work.

If you're looking for alternatives to storybook, there are a few actually. There's https://github.com/doczjs/docz https://previewjs.com/ https://react-styleguidist.js.org/ and a bunch more.
Building something yourself can also be great, I recommend it!

You mention that storybook has tons of open issues, and you're right. I feel guilty about this all the time.
As a team we have been looking for help and hiring people to help us put procedures in place to make sure this will get dealt with in the future!

I hope that whatever you do, whatever tool you use, fits your use-case, and makes your development better and more fun.

And if you ever feel like helping out with existing issues, I'd be happy to guide you on how to get started contributing in a 1-on-1 zoom meeting any time: https://calendly.com/chromaui <- schedule a meeting with me, and I'll show up.

**Comment by DavidLeonard77** [comment] 2022-11-30 00:29
Very happy with the quick response time. Thanks!

**Comment by wojtekxtx** [comment] 2022-11-30 00:59
@ndelangen Thats seriously great answer. Many thanks :)

> We try, but you know, sometimes building a project such as storybook, standing on the shoulders of giants, it's a blessing and a curse. We would not be where we are today without those giants! But these giants are moving, and new giants get created to stand upon.

Its good you try, keep doing this :) Im well aware, that `giants are moving`, but the thing is to move with them; follow them step-by-step ( every release they make; you incorporate changes so your product uses latest version etc ). Ideal situation would be to even be one step ahead of them. Would be great :)

> We found out storybook was broken within 2 hours of the webpack team releasing a minor version of a package they depend on. This minor version change broke storybook in a unexpected way. The storybook team had no way of knowing this change was coming, we didn't choose to update to enhanced-resolve, in fact because it's a transitive dependency, we couldn't even fix it on our end, it was impossible.
Within 1 hour after discovery we had a PR up fixing the issue at the origin, we had ping'ed the author of the PR breaking and the package maintainer on multiple platforms.

As per this *incident* with `webpack`: incidents can (and will) happen; but what (not even who; what) is t fault here is: pile of bad/badly implemented practices on the line team<>community. Respect for quick response times, but, lets face it, this is NOT fixed. And, whats more, this escalated into, whats called **bug cascade**. One bug leads to two (or more) another bugs and so on. **This is exactly the case here**. Tested it no more than 4 hours ago by doing an fresh install of `storybook`. Whats more: by Googling error messages, there are multiple answers on possible fixes (its somewhat normal), but guess what: 99% of them either:
* dont wok at all, or
* solves said bug but unhides one or more another,

And guess what? All bugs that I encountered while installing `storybook` are reported as [issues](https://github.com/storybookjs/storybook/issues)! All of them! 99% of these issues have either:
* no conclusive answer from team member, or
* does not have answer AT ALL.

This inident with `webpack` uncovered other, not connected with `webpack`, problems that runs deep inside code of `storybook`. One of such problems I [described in this answer](https://github.com/storybookjs/storybook/discussions/19910#discussioncomment-4244363); I even captured screen video of it.
In order to get rid of them, the best course of action would be **to fully rewrite `storybook` from absolute scratch**. Meaning new mindset, new (well-designed) AWD (Application WorkFlow Diagram), and so on.
Why? Simply because by changing existing codebase, the probability of not fixing but deepening existing bugs while (not willfully) creating new ones is close to 90%. Its just pointless. 
Full rewrite would be MASSIVE job, Im well too well aware of this, but sometimes there is no other option if you want project to survive.

Seriously @ndelangen is this how you run projects that aims to be succesull? Jesus man, no! This is not way to go. There are so many new issues added daily that the more you wait with deep changes within teams' mentality, the harder it will be to keep this project afloat/alive.

Thanks for the links to other projects. I appreciate.

**Comment by ndelangen** [comment] 2022-11-30 09:47
I do not appreciate your tone of voice @wojtekxtx 
In my humble opinion you're not giving constructive feedback, but rather, are lecturing. It seems to me you're not interested in actually improving the situation, but rather dragging it down. This is toxic behavior.

You say you are still having this exact issue? please supply a reproduction.

You say when you were trying this 4 hours ago you ran into a list of issues, please list them.
You say none of those issues get replies from maintainers, that seems unlikely to me, but if you list them we can actually know what issues you're running into.

You suggest we drop all existing code, and rewrite from scratch; uprooting the entire user-base, dropping backwards compatibility, giving users a very hard time waiting for this rewrite and then when it lands, migrate.
This is a terrible plan, I assume you know this; why you suggest this, is beyond me.

You seems to be of the impression that the storybook team is required to read all issues for you, is required to fix all bugs for you. You're acting in a way that makes open source maintainers lose interest and burn out. Please stop.

You might think you comment is helping, but it's not. 
You've done none of the work required to make your comment actually useful to this project.

It's fine if you feel like an open source is not for you, but you should not go around open source project you don't like and actively try to make their maintainers feel bad.

If I see another toxic message from you, I'd feel forced to use the [code of conduct](https://github.com/storybookjs/storybook/blob/next/CODE_OF_CONDUCT.md#2-warning), this message is a `warning`, and the next step would be a [temp ban](https://github.com/storybookjs/storybook/blob/next/CODE_OF_CONDUCT.md#3-temporary-ban)

**Comment by wojtekxtx** [comment] 2022-11-30 10:19
@ndelangen just as I expected. You understand nothing, but I dont care one bit. If you think Im the one doing sth wrong - ok, its your right tothink that way. And no, Im not breaking your CoC; the one breaking it is you alone. Read carefully and maybe you will know whatIm talking about.

> You're acting in a way that makes open source maintainers lose interest and burn out. Please stop.

What do we see here? Pushing guilt away from yourself. How classy! Fact is: thats acting like this, thats making people stop contributing to FOSS.

As of banning me: I dont care, ban me if it will boost your (ill) ego. Cannot care less.

========

In my reply ( the one you are replying to ) I even offered to talk privately via email to explain things and work in my free time together for the project to be better.  For what? Only to read that Im at fault here. There is absolutely no sense in helping.

Now go ahead and ban me. I give a FUCK.

**Comment by rtturner** [comment] 2022-12-07 15:09
😮 sorry to ping a closed issue but just wanted to give thanks to the storybook team - you guys rock - real bummer this issue exploded into a temper tantrum but think you handled it well. Hope you all have a good holiday and happy new year 😄

**Comment by yyx990805** [comment] 2023-11-07 02:30
just FYI: I agree with @wojtekLs, there's mess and in my opinion his feedback was constructive.
