### ISSUE TITLE
[Bug]:  In V7, subcomponents not works, only auto generate component docs API

### ISSUE THREAD

**Issue by Flcwl** [storybookjs/storybook#23205] opened 2023-06-25 03:26 UTC
### Describe the bug

In V7, subcomponents not works, only auto generate `SoFilterForm` docs API. 

the `SoFilterForm` and `SoFilterFormItem` components all have Props TS defined in `src`.

```tsx
import React from 'react'
import type { Meta, StoryObj } from '@storybook/react'

import { SoFilterForm, SoFilterFormItem } from '../src'

const meta: Meta<typeof SoFilterForm> = {
  title: 'form/SoFilterForm ',
  component: SoFilterForm,
  subcomponents: { SoFilterForm, 'SoFilterForm.Item': SoFilterFormItem },
  tags: ['autodocs'],
}

export default meta
export type Story = StoryObj<typeof SoFilterForm>
```

![image](https://github.com/storybookjs/storybook/assets/26050644/9a1a3f44-692c-4ed5-827b-a488f6899c1a)

### To Reproduce

1. main.ts
```
import type { StorybookConfig } from '@storybook/react-webpack5'
import remarkGfm from 'remark-gfm';

const config: StorybookConfig = {
  stories: [
    '../packages/**/*.@(mdx)',
    '../stories/**/*.stories.@(tsx|mdx)',
    '../packages/**/index.stories.@(tsx|mdx)'
  ],
  features: {
    storyStoreV7: true,
  },
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
    '@storybook/preset-ie11',
    '@storybook/preset-ant-design',
    {
      name: '@storybook/addon-docs',
      options: {
        mdxPluginOptions: {
          mdxCompileOptions: {
            remarkPlugins: [remarkGfm],
          },
        },
      },
    }
  ],
  framework: {
    name: '@storybook/react-webpack5',
    options: {},
  },
  docs: {
    autodocs: 'tag'
  },

}
export default config
```

### System

```shell
Environment Info:

  System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.20.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Firefox: 104.0.2
    Safari: 16.0
  npmPackages:
    @storybook/addon-docs: ^7.0.23 => 7.0.23 
    @storybook/addon-essentials: 7.1.0-alpha.29 => 7.1.0-alpha.29 
    @storybook/addon-interactions: 7.1.0-alpha.29 => 7.1.0-alpha.29 
    @storybook/addon-links: 7.1.0-alpha.29 => 7.1.0-alpha.29 
    @storybook/addons: 7.1.0-alpha.29 => 7.1.0-alpha.29 
    @storybook/blocks: 7.1.0-alpha.29 => 7.1.0-alpha.29 
    @storybook/manager-api: 7.1.0-alpha.29 => 7.1.0-alpha.29 
    @storybook/preset-ant-design: ^0.0.2 => 0.0.2 
    @storybook/preset-ie11: ^0.0.1 => 0.0.1 
    @storybook/react: 7.1.0-alpha.29 => 7.1.0-alpha.29 
    @storybook/react-webpack5: 7.1.0-alpha.29 => 7.1.0-alpha.29 
    @storybook/testing-library: ^0.0.14-next.2 => 0.0.14-next.2 
    @storybook/theming: 7.1.0-alpha.29 => 7.1.0-alpha.29 
```
```


### Additional context

_No response_

**Comment by Flcwl** [comment] 2023-06-26 05:20
Hello, here have any solutions for this problem. I need your help please!

**Comment by Flcwl** [comment] 2023-06-28 08:00
Please tell me if need any infos to reappear this problem. I really like and need the ability~

**Comment by bangank36** [comment] 2023-08-16 02:15
@Flcwl `subcomponents` is deprecated on v7, you may want to follow these workaround to enable it
[[Feature Request]: Subcomponents support](https://github.com/storybookjs/storybook/issues/20782#issuecomment-1482771013)
For example psui UI components use `argTable` as workaround: [preview.tsx](https://github.com/x7ddf74479jn5/psui/blob/4e8e850dc5897e698a5da4c8475662a085de77ff/packages/components/.storybook/preview.tsx#L42) / [HoverCard stories](https://x7ddf74479jn5.github.io/psui/?path=/docs/components-hovercard--docs)
Another design system that has `subcomponents` workaround [equinor/design-system](https://github.com/equinor/design-system), check [PropsTable](https://github.com/equinor/design-system/blob/dc8c22fcf950bab923ed11f9432bdb76e7891924/packages/eds-lab-react/.storybook/components/PropsTable.tsx#L3)

<img width="1296" alt="image" src="https://github.com/storybookjs/storybook/assets/10071857/7d7e96d1-f057-4364-a027-699b94bdf66e">

**Comment by alasdair009** [comment] 2023-09-07 20:48
Gona bump this with the same comment i made on a duplicate bug:

We found the subcomponent docs feature particularly useful for our composite structure. I understand why it was removed but I feel this feature does add a lot of value for onboarding our team.

**Comment by vanessayuenn** [comment] 2023-09-20 04:57
closing as duplicate of #20782

**Closed by vanessayuenn** 2023-09-20 04:57 UTC
Labels: bug, needs triage
