### ISSUE TITLE
sh: start-storybook: command not found after upgrading to latest release

### ISSUE THREAD

**Issue by zackhamin** [storybookjs/storybook#18923] opened 2022-08-12 08:55 UTC
**Describe the bug**
I upgraded our version of Storybook in our React project to the latest version ^6.5 
Afterwards I have the following issue when trying to run Storybook - `sh: start-storybook: command not found`
Using a Macbook. 

Then upgraded to pre-release to see if it resolved. 

**To Reproduce**
Upgrade Storybook and try to run it. 

**System**
Environment Info:

  System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    npm: 8.17.0 - ~/Desktop/customer_contact_work/cc-component-library/node_modules/.bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Safari: 15.2
  npmPackages:
    @storybook/addon-actions: ^7.0.0-alpha.18 => 7.0.0-alpha.19 
    @storybook/addon-essentials: ^7.0.0-alpha.18 => 7.0.0-alpha.19 
    @storybook/addon-links: ^7.0.0-alpha.18 => 7.0.0-alpha.19 
    @storybook/builder-webpack5: ^7.0.0-alpha.18 => 7.0.0-alpha.19 
    @storybook/cli: ^6.5.10 => 6.5.10 
    @storybook/manager-webpack5: ^7.0.0-alpha.10 => 7.0.0-alpha.10 
    @storybook/react: ^7.0.0-alpha.18 => 7.0.0-alpha.19 
**Additional context**

**Comment by zackhamin** [comment] 2022-08-12 08:56
I should also add, I have tried to remove node_modules and re-install etc etc.

**Comment by coopbri** [comment] 2022-08-14 04:06
I had this issue too, and discovered in the [v7 release notes](https://github.com/storybookjs/storybook/blob/next/CHANGELOG.md#breaking-changes-1) that `start-storybook` and `build-storybook` were removed. [Here's the PR](https://github.com/storybookjs/storybook/pull/17899) and a similar discussion here: https://github.com/storybookjs/storybook/issues/18675

I had to install `@storybook/cli` (make sure the version is the same as the Storybook core you are using, e.g. `7.0.0-alpha.19` based on your listed env info) and then `sb dev` worked!

**Comment by brianfoody** [comment] 2022-08-16 03:18
If you have upgraded to storybook 7 and found yourself here then the problem is [start-storybook is removed](https://github.com/storybookjs/storybook/issues/18923) and the migration doesn't modify for some reason.

To fix modify your scripts to;

```
"storybook": "sb dev",
"build-storybook": "sb build"
```

Also check out the migration guide - https://github.com/storybookjs/storybook/blob/4a532ec8d8922ddf6b7a7e1cc68d88b35377b0a6/MIGRATION.md#start-storybook--build-storybook-binaries-removed

I was missing  some things

**Comment by zackhamin** [comment] 2022-08-22 09:06
> I had this issue too, and discovered in the [v7 release notes](https://github.com/storybookjs/storybook/blob/next/CHANGELOG.md#breaking-changes-1) that `start-storybook` and `build-storybook` were removed. [Here's the PR](https://github.com/storybookjs/storybook/pull/17899) and a similar discussion here: #18675
> 
> I had to install `@storybook/cli` (make sure the version is the same as the Storybook core you are using, e.g. `7.0.0-alpha.19` based on your listed env info) and then `sb dev` worked!

Brilliant, I have some run time errors- however this has helped a lot!

**Comment by zackhamin** [comment] 2022-08-22 09:06
> If you have upgraded to storybook 7 and found yourself here then the problem is [start-storybook is removed](https://github.com/storybookjs/storybook/issues/18923) and the migration doesn't modify for some reason.
> 
> To fix modify your scripts to;
> 
> ```
> "storybook": "sb dev",
> "build-storybook": "sb build"
> ```
> 
> Also check out the migration guide - https://github.com/storybookjs/storybook/blob/4a532ec8d8922ddf6b7a7e1cc68d88b35377b0a6/MIGRATION.md#start-storybook--build-storybook-binaries-removed
> 
> I was missing some things

Awesome! Thanks, having a read through and it helped loads. 

Thanks again, Brian.

**Comment by coopbri** [comment] 2022-08-22 09:11
> > I had this issue too, and discovered in the [v7 release notes](https://github.com/storybookjs/storybook/blob/next/CHANGELOG.md#breaking-changes-1) that `start-storybook` and `build-storybook` were removed. [Here's the PR](https://github.com/storybookjs/storybook/pull/17899) and a similar discussion here: #18675
> > I had to install `@storybook/cli` (make sure the version is the same as the Storybook core you are using, e.g. `7.0.0-alpha.19` based on your listed env info) and then `sb dev` worked!
> 
> Brilliant, I have some run time errors- however this has helped a lot!

Awesome! Happy to help with the runtime errors if you are still stuck, feel free to reach out.

**Comment by zackhamin** [comment] 2022-08-22 09:42
> > > I had this issue too, and discovered in the [v7 release notes](https://github.com/storybookjs/storybook/blob/next/CHANGELOG.md#breaking-changes-1) that `start-storybook` and `build-storybook` were removed. [Here's the PR](https://github.com/storybookjs/storybook/pull/17899) and a similar discussion here: #18675
> > > I had to install `@storybook/cli` (make sure the version is the same as the Storybook core you are using, e.g. `7.0.0-alpha.19` based on your listed env info) and then `sb dev` worked!
> > 
> > 
> > Brilliant, I have some run time errors- however this has helped a lot!
> 
> Awesome! Happy to help with the runtime errors if you are still stuck, feel free to reach out.

I am going to swiftly take you up on that offer. 

we are using TSX in our app and it seems to have some conflicting issues with the upgrade. The new script runs fine and begins to build.

![Screenshot 2022-08-22 at 10 40 59](https://user-images.githubusercontent.com/56539344/185891153-e95fd2e6-9342-436e-b038-94bc8531406b.png)

Run time errors 
![Screenshot 2022-08-22 at 10 41 53](https://user-images.githubusercontent.com/56539344/185891394-5b5b2e59-6062-4256-a79d-b0a33fa5db14.png)

**Comment by EightArmCode** [comment] 2023-02-11 16:27
`npx sb@next automigrate`

**Comment by shilman** [comment] 2023-02-13 07:58
Closing this. Please follow the migration instructions to upgrade: https://storybook.js.org/migration-guides/7.0

**Closed by shilman** 2023-02-13 07:58 UTC
Labels: bug, needs triage

**Comment by Abeinevincent** [comment] 2023-04-07 07:29
Run `npx storybook@next automigrate` and follow the prompts because youre using a newer version of storybook where `start storybook` and `build storybook` have been removed

**Comment by amerllica** [comment] 2023-04-13 11:14
> Run npx storybook@next automigrate and follow the prompts because youre using a newer version of storybook where start storybook and build storybook have been removed

Thanks. it helped me a lot

**Comment by MahmonirB** [comment] 2023-04-25 22:01
Thanks @Abeinevincent, It works well.

**Comment by Abeinevincent** [comment] 2023-04-26 04:05
Youre welcome

**Comment by andrewmelnyk** [comment] 2023-05-18 22:35
I tried following the migration guide and when I run that upgrade command and the result is:
```
Need to install the following packages:
  storybook@7.0.12
Ok to proceed? (y) y
make: *** [upgrade] Error 1
```

**Comment by helloint** [comment] 2024-08-07 03:15
I met this same issue and now I figured it out what happens.
If you upgrade to storybook@7 via command:
```
npx storybook@7 upgrade
```
The auto migration will handle this:
<img width="1155" alt="image" src="https://github.com/user-attachments/assets/78d4ab50-e160-4f94-8aee-37fcf5ff75ed">
<img width="1642" alt="image" src="https://github.com/user-attachments/assets/6d0ccfc7-515f-46d3-a1ea-b747782b7728">
The migration will install `storybook` (Looks like it is actually same as `@storybook/cli` just have better name?) which includes binary `storybook` and `sb`. The migration will also help to auto update the npm scripts in packages.json
So if in some case you have skipped that step (maybe you upgrade storybook via just upgrading storybook related packages), then just manually install `npm i storybook -D` or `yarn add storybook -D` and update the npm scripts from:
```
    "storybook": "start-storybook -p 6006",
    "buildStorybook": "build-storybook",
```
to:
```
    "storybook": "storybook dev -p 6006",
    "buildStorybook": "storybook build",
```
