### ISSUE TITLE
Addon-docs: list style bleeds on stories components

### ISSUE THREAD

**Issue by elevatebart** [storybookjs/storybook#6803] opened 2019-05-16 16:48 UTC
**Describe the bug**
Using addon-docs to showcase material powered Menu, I get an unwanted padding caused by the docs `.12345xx ul{padding-left:30px;}` coming from the docs.

**To Reproduce**
1. install addon-docs alpha 8
1. show case a component with a ul list in the docs tab
1. it's padding-left will be too big

**Expected behavior**
The style of the docs should not bleed down on the components showcased

**Screenshots**
![Normal](https://user-images.githubusercontent.com/5592465/57872002-55ecdc80-77d0-11e9-92a9-93a47c24979b.png)

![InTheDocsTab](https://user-images.githubusercontent.com/5592465/57872005-58e7cd00-77d0-11e9-99b3-bf0e50690d1c.png)

**System:**
 - OS: Windows10
 - Browser: Mozilla Firefox 67.0 64bits
 - Framework: React
 - Addons: addon-docs
 - Version:5.2.0-alpha8

**Comment by anselmdk** [comment] 2019-07-13 12:31
Same happening to me.
See the "edit" button, it should be 16px, but it's being overwritten by some CSS-in-JS styling.
Also margins and paddings seem to be affected.

![2019-07-13_14h28_08](https://user-images.githubusercontent.com/1316533/61171641-b901b200-a57a-11e9-9e3f-c809dc2a3028.png)
![2019-07-13_14h28_41](https://user-images.githubusercontent.com/1316533/61171642-ba32df00-a57a-11e9-9729-ab64a4c81e62.png)

**Comment by danielknell** [comment] 2019-07-13 20:17
I am seeing the same with anchor colors in external stylesheets being overridden, can the markdown elements be styled directly rather than using a single class and child element selectors?

**Comment by city41** [comment] 2019-07-30 23:22
I have also encountered this. I just upgraded to beta.18 to see if it's been fixed, but still see the issue.

In my case it's the same `ul { padding-left: 30px }` that OP is seeing.

**Comment by shilman** [comment] 2019-07-31 01:29
That's why the issue is still open :trollface:

**Comment by shilman** [comment] 2019-08-16 10:23
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.31 containing PR #7771 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2019-08-16 10:23 UTC
Labels: addon: docs, bug, high priority, in progress

**Comment by shilman** [comment] 2019-08-17 13:51
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.32 containing PR #7788 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
