### ISSUE TITLE
[Bug]: Using Meta<PropType> is broken when using discriminating types

### ISSUE THREAD

**Issue by alex1701c** [storybookjs/storybook#23629] opened 2023-07-27 06:49 UTC
### Describe the bug

The snippet below gives a TypeScript error. If I were to change the meta type to `Meta<typeof TestButton>` it would work as expected.

### To Reproduce

```tsx
import type { MouseEvent } from 'react';
import type { Meta } from '@storybook/react';

type TestButtonProps = {
    text: string;
} & (
    | {
          id?: string;
          onClick?: (e: MouseEvent<HTMLButtonElement>, id: string | undefined) => void;
      }
    | {
          id: string;
          onClick: (e: MouseEvent<HTMLButtonElement>, id: string) => void;
      }
);
const TestButton: React.FC<TestButtonProps> = ({ text }) => {
    return <p>{text}</p>;
};

const meta: Meta<TestButtonProps> = {
    title: 'Components/Button',
    component: TestButton,
    args: {
        text: 'Button',
    },
};

export default meta;
```

This gives the followign error:
```log
src/ui/components/Button/stories/Demo.stories.tsx:22:5 - error TS2322: Type 'FC<TestButtonProps>' is not assignable to type 'ComponentType<{ text: string; } & { id?: string | undefined; onClick?: ((e: M
ouseEvent<HTMLButtonElement, MouseEvent>, id: string | undefined) => void) | undefined; }> | ComponentType<...> | undefined'.
  Type 'FunctionComponent<TestButtonProps>' is not assignable to type 'FunctionComponent<{ text: string; } & { id?: string | undefined; onClick?: ((e: MouseEvent<HTMLButtonElement, MouseEvent>, id: stri
ng | undefined) => void) | undefined; }>'.
    Types of property 'propTypes' are incompatible.
      Type 'WeakValidationMap<TestButtonProps> | undefined' is not assignable to type 'WeakValidationMap<{ text: string; } & { id?: string | undefined; onClick?: ((e: MouseEvent<HTMLButtonElement, Mouse
Event>, id: string | undefined) => void) | undefined; }> | undefined'.
        Type 'WeakValidationMap<{ text: string; } & { id: string; onClick: (e: MouseEvent<HTMLButtonElement, MouseEvent>, id: string) => void; }>' is not assignable to type 'WeakValidationMap<{ text: st
ring; } & { id?: string | undefined; onClick?: ((e: MouseEvent<HTMLButtonElement, MouseEvent>, id: string | undefined) => void) | undefined; }>'.
          Types of property 'onClick' are incompatible.
            Type 'Validator<(e: MouseEvent<HTMLButtonElement, MouseEvent>, id: string) => void> | undefined' is not assignable to type 'Validator<((e: MouseEvent<HTMLButtonElement, MouseEvent>, id: stri
ng | undefined) => void) | null | undefined> | undefined'.
              Type 'Validator<(e: MouseEvent<HTMLButtonElement, MouseEvent>, id: string) => void>' is not assignable to type 'Validator<((e: MouseEvent<HTMLButtonElement, MouseEvent>, id: string | undef
ined) => void) | null | undefined>'.
                Type '(e: MouseEvent<HTMLButtonElement, MouseEvent>, id: string) => void' is not assignable to type '(e: MouseEvent<HTMLButtonElement, MouseEvent>, id: string | undefined) => void'.     
                  Types of parameters 'id' and 'id' are incompatible.
ined) => void) | null | undefined>'.
                Type '(e: MouseEvent<HTMLButtonElement, MouseEvent>, id: string) => void' is not assignable to type '(e: MouseEvent<HTMLButtonElement, MouseEvent>, id: string | undefined) => void'.     
                  Types of parameters 'id' and 'id' are incompatible.
                    Type 'string | undefined' is not assignable to type 'string'.
                      Type 'undefined' is not assignable to type 'string'.

22     component: TestButton,
       ~~~~~~~~~

  node_modules/@storybook/types/dist/index.d.ts:1221:5
    1221     component?: (TRenderer & {
             ~~~~~~~~~
    The expected type comes from property 'component' which is declared here on type 'ComponentAnnotations<ReactRenderer, { text: string; } & { id?: string | undefined; onClick?: ((e: MouseEvent<HTMLBut
tonElement, MouseEvent>, id: string | undefined) => void) | undefined; }> | ComponentAnnotations<...>'

```

### System

```shell
System:                                                      
    OS: Windows 10 10.0.19044                                  
    CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz      
  Binaries:                                                    
    Node: 16.16.0 - C:\SPU\tools\node-v16.16.0-win-x64\node.EXE
    Yarn: 1.22.19 - C:\SPU\web\tools\nodejs_16.16.0\yarn.CMD   
    npm: 8.11.0 - C:\SPU\tools\node-v16.16.0-win-x64\npm.CMD   
  Browsers:                                                    
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.183) 
  npmPackages:                                                 
    @storybook/addon-a11y: ^7.0.24 => 7.0.24                   
    @storybook/addon-actions: ^7.0.24 => 7.0.24                
    @storybook/addon-essentials: ^7.0.24 => 7.0.24
    @storybook/addon-links: ^7.0.24 => 7.0.24
    @storybook/addons: ^7.0.24 => 7.0.24
    @storybook/react: ^7.0.24 => 7.0.24
    @storybook/react-webpack5: ^7.0.24 => 7.0.24
    @storybook/theming: ^7.0.24 => 7.0.24
```

### Additional context

Error occurs with "storybook": "^7.0.24" and both typescript versions:
"typescript": "^5.1.6",
"typescript": "^4.8.3",

**Comment by momi-bita** [comment] 2023-08-04 05:42
I'm having the same issue where I use React.FC to annotate the component type.
Maybe a simple change to the type definition for Meta will fix this?

```typescript
export type Meta<TCmpOrArgs = Args, TArgsNotDistributed extends TCmpOrArgs = TCmpOrArgs> =
TCmpOrArgs extends ComponentType<any>
  ? ComponentAnnotations<ReactRenderer, ComponentProps<TCmpOrArgs>>
  : ComponentAnnotations<ReactRenderer, TArgsNotDistributed>;
```

**Comment by kasperpeulen** [comment] 2023-08-04 08:25
@momi-bita I will try to look at this next, but PR's are welcome!

**Comment by eduardopatrick** [comment] 2023-08-04 18:20
Same issue here when tried to update the stories flows.

**Comment by reubenayres** [comment] 2023-08-14 22:11
Same here specifically when component is annotated with `React.FunctionComponent<Props>`

**Comment by thathurtabit** [comment] 2023-08-29 20:20
Looks like the same issue I'm getting below.
It will work if I remove the `FC` type from my component though, but should Storybook demand that?

Story:
```ts
const meta: Meta<typeof MyComponent> = {
  title: 'Atoms/MyComponent',
  component: MyComponent, // ERROR HERE
  parameters: {
    backgrounds: {
      default: 'dark',
    },
  },
};
```

Error:
```bash
Type 'FC' is not assignable to type 'ComponentType<FC> | undefined'.
  Type 'FunctionComponent<{}>' is not assignable to type 'FunctionComponent<FC>'.
    Type 'ReactNode' is not assignable to type 'ReactElement<any, any> | null'.
      Type 'undefined' is not assignable to type 'ReactElement<any, any> | null'.ts(2322)
index.d.ts(1222, 5): The expected type comes from property 'component' which is declared here on type 'ComponentAnnotations<ReactRenderer, FC>'
```

**Comment by viper3400** [comment] 2023-09-01 09:10
Hi, I use Storybook with React and Next.js.

I ran into this issue when one of my repositories got a [renovate](https://github.com/renovatebot/renovate) PR from v7.23.0 to v7.24.0 and the `next build` [failed with the error from this issue](https://github.com/viper3400/nextjs-playground/actions/runs/6025751567/job/16347158579#step:6:21).

Turned out - that at least on my side - here was some dependency mismatch in my `package-lock.json`. When I deleted my `node_modules` directory and the `package-lock.json` and re-ran `npm install` the build worked, eventually.

Not sure, if this is the issue for all, but I thought it's worth to share my experiences to help at least some of you.

**Comment by kasperpeulen** [comment] 2023-09-08 15:35
Should be fixed in this canary release:
[0.0.0-pr-24110-sha-9e9d8374](https://www.npmjs.com/package/@storybook/cli/v/0.0.0-pr-24110-sha-9e9d8374)

**Closed** 2023-09-12 10:35 UTC
Labels: bug, typescript

**Comment by alex1701c** [comment] 2023-09-15 19:40
Thanks a lot :)

**Comment by kasperpeulen** [comment] 2024-04-17 08:12
@ProductOfAmerica Can you make a https://storybook.new repro? I can not reproduce this.

**Comment by ProductOfAmerica** [comment] 2024-04-17 21:09
@kasperpeulen I tried used this instead: https://turbo.build/repo/docs/handbook/tools/storybook and it worked fine. Previously I had followed the Next.js example https://storybook.js.org/docs/get-started/nextjs which I guess just doesn't work with Turborepo for some reason?

Didn't work:
`pnpm dlx storybook@latest init`

Worked:
`pnpm dlx sb init --skip-install`
`pnpm install --save-dev @storybook/cli`
