### ISSUE TITLE
npx sb extract not working as expected

### ISSUE THREAD

**Issue by Niznikr** [storybookjs/storybook#13561] opened 2021-01-05 16:07 UTC
**Describe the bug**
Running `npx sb extract` results in the following error:

```
npx sb extract
info connecting to: http://localhost:57011/iframe.html
info installing puppeteer...
TimeoutError: waiting for function failed: timeout 30000ms exceeded
    at new WaitTask (/Users/rniznik/.npm/_npx/37097/lib/node_modules/sb/node_modules/puppeteer-core/lib/DOMWorld.js:549:28)
    at DOMWorld.waitForFunction (/Users/rniznik/.npm/_npx/37097/lib/node_modules/sb/node_modules/puppeteer-core/lib/DOMWorld.js:454:12)
    at Frame.waitForFunction (/Users/rniznik/.npm/_npx/37097/lib/node_modules/sb/node_modules/puppeteer-core/lib/FrameManager.js:657:28)
    at Page.waitForFunction (/Users/rniznik/.npm/_npx/37097/lib/node_modules/sb/node_modules/puppeteer-core/lib/Page.js:1141:29)
    at read (/Users/rniznik/.npm/_npx/37097/lib/node_modules/sb/node_modules/@storybook/cli/dist/extract.js:30:14)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async extract (/Users/rniznik/.npm/_npx/37097/lib/node_modules/sb/node_modules/@storybook/cli/dist/extract.js:87:18)
```

**To Reproduce**

1. Go to a Storybook project
2. Run `npx sb extract` from the terminal

**Expected behavior**
The command runs and creates a `stories.json` file.

```
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Edge: 87.0.664.66
    Firefox: 84.0.1
    Safari: 14.0.2
  npmPackages:
    @storybook/addon-a11y: ^6.1.11 => 6.1.11 
    @storybook/addon-actions: ^6.1.11 => 6.1.11 
    @storybook/addon-controls: ^6.1.11 => 6.1.11 
    @storybook/addon-docs: ^6.1.11 => 6.1.11 
    @storybook/addon-storysource: ^6.1.11 => 6.1.11 
    @storybook/addon-viewport: ^6.1.11 => 6.1.11 
    @storybook/addons: ^6.1.11 => 6.1.11 
    @storybook/react: ^6.1.11 => 6.1.11 
    @storybook/source-loader: ^6.1.11 => 6.1.11 
    @storybook/theming: ^6.1.11 => 6.1.11 
    @storybook/web-components: ^6.1.11 => 6.1.11 
```

**Additional context**

**Comment by diegofss11** [comment] 2021-02-16 03:29
Did it work yet?

**Comment by Niznikr** [comment] 2021-02-18 13:21
Nope still failing.

**Comment by shilman** [comment] 2021-02-18 14:32
Perhaps you can install puppeteer manually by hand to avoid hitting this timeout? It's slow to install. @ndelangen WDYT?

**Comment by Niznikr** [comment] 2021-02-18 15:05
Still times out even after manual install.

**Comment by cy6erskunk** [comment] 2021-03-09 13:35
The same issue here... It seems that there's no way to use pre-intalled puppeteer if understood #13724 correctly.

**Comment by NiklasPor** [comment] 2021-03-12 13:23
Ran into the same issue. Strangely I resolved it by calling `sb extract` from the root of the repository with the dist folder as a parameter:

```
npx sb extract dist/storybook/your-lib/
```

This strangely worked in opposite to `cd dist/storybook/your-lib/ && sb extract` in my case.

**Comment by pjoulot** [comment] 2021-07-22 18:25
Same issue here.
Installing the package manually seems to not work for me.

**Comment by mtsmachado8** [comment] 2021-08-10 02:04
Same issue here... It's a really bad bug because i cannot use storybook composeable feature.

**Comment by shilman** [comment] 2021-08-10 12:15
There is an experimental built-in `stories.json` generation. Here's how to use it:
- [ ] Doesn't work on `storiesOf` stories, only CSF (MDX added today #15808)
- [ ] Upgrade 6.4-alpha (`npx sb upgrade --prerelease`)
- [ ] Set the following experimental flag in your `.storybook/main.js` config:

```js
module.exports = {
  features: {
    buildStoriesJson: true,
  }
};
```

Then when you `yarn build-storybook` it should also generate `stories.json` in the output folder. This stories.json is not exactly the same format as what comes out of `sb extract`, but it seems to work pretty well already even though it's experimental. It will become the default in 6.4.

**Comment by shilman** [comment] 2021-11-04 10:42
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-beta.27 containing PR #16505 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2021-11-04 10:42 UTC
Labels: bug, cli, has workaround, composition, P1

**Comment by itwasmattgregg** [comment] 2022-01-27 22:20
I'm on v6.4.13 and am getting this error. I'm not opted in to v7 store mode.

**Comment by itwasmattgregg** [comment] 2022-01-28 14:28
Coming back to this: I figured out I was starting to use auto generated titles. For some reason removing the explicit titles on stories caused this error to fire on our custom a11y test function which currently uses extract.

**Comment by tmeasday** [comment] 2022-01-31 02:51
@itwasmattgregg I will bet looking at a fix to this soon.

**Comment by stabback** [comment] 2022-02-08 19:59
https://github.com/storybookjs/storybook/issues/13561#issuecomment-953675506

I ran into this error on `6.4.18` on the v6 store @tmeasday.  We are using a mix of modern CSF and legacy `storiesOf` in our codebase.  I'm wondering if the `storiesOf` syntax is confusing things.

I had to downgrade back to `6.3.x` to avoid this issue.

**Comment by stabback** [comment] 2022-02-08 20:51
Unfortunately, I do not have a reproduction I can share :(.  I was commenting hoping the additional context of the mix of CSF and `storiesOf` could help explain some of the discrepancies.  I can reliably cause this error by updating from 6.3 to 6.4, with no other change to my code.

**Comment by tmeasday** [comment] 2022-02-08 22:59
@stabback can you share your `main.js` and `preview.js`?

**Comment by shilman** [comment] 2022-02-11 05:13
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.39 containing PR #17447 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

**Comment by shilman** [comment] 2022-02-12 10:13
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.19 containing PR #17447 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

**Comment by ritz078** [comment] 2023-07-22 17:21
I am on 7.1.0 and I am still facing this issue.

**Comment by HashemKhalifa** [comment] 2023-09-15 12:54
I'm on 7.4.1 and still facing the same issue!!

**Comment by HashemKhalifa** [comment] 2023-09-15 13:05
the way to solve this issue is to override puppeteer-core in the package.json with version `13.7.0 `

I'm using pnpm so it will be 

```

  "pnpm": {
    "overrides": {
      "puppeteer-core": "^13.7.0",
    }
  },
```

you can use `resolutions` in case of yarn, npm
